### ISSUE TITLE
[SUBMIT] How to create a menu app for restaurants with NextJS (TypeScript) and Strapi

### ISSUE THREAD

**Issue by daryllukas** [strapi/community-content#1002]
**How to create a menu app for restaurants with NextJS (TypeScript) and Strapi**

I recently built a [demo/portfolio project](https://wazz-gud-here.vercel.app/) using Strapi and I think I have enough content for a great tutorial. There is a lot things I've learned and issues I faced that I feel haven't been properly documented. I have documentated the steps I took to build and deploy the demo app on GCP. The source code is [available on Github](https://github.com/daryllukas/wazz-gud-here).  I'm also adding additional functionality like search and filtering.

Here's the outline for my tutorial:

Introduction
Project Setup and Dependency Installation
Creating Content-Types in Strapi
Creating content using the Content Manager
Exploring the GraphQL endpoint: Playground and Postman
Creating frontend in NextJS using Tailwind CSS
Reading and Filtering data via API.
Deploying Backend to GCP (App Engine + Cloud SQL)
Deploying Frontend to Vercel
Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@daryllukas We have many articles in the queue and are only accepting new articles in January of next year. 

I will put this on hold for topic review in January.  The suggested change I would make, is to maybe have all the frontend code and backend code already done.  And just write the article to focus on the deployment process to GCP.  And talk about the  issues you faced that you feel haven't been properly documented.

We also have decided to focus our efforts on producing higher-quality content for our readers.

Also, we will be introducing new tags by level beginner, intermediate, and advanced.   As well as update the rate to encourage our writers to write about more intermediate/advanced Strapi content.

We are working on redoing WFC guidelines to reflect these changes and providing some common topics that our community and members request.

**Comment by daryllukas** [comment]
@PaulBratslavsky Sounds good. Thanks for the update. I'll follow your suggestions and redo the outline.

**Comment by PaulBratslavsky** [comment]
Upon further review, it seems that your app is mostly focused on Next js development.  At the moment we are looking for Strapi backend development and customization.  I will be closing this issue for now, but feel free to submit additional topics or updated outline in the future.
