### ISSUE TITLE
[SUBMIT] : How To Build Social Card Application With Strapi TypeScript and React

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [strapi/community-content#1003]
**My resource**

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by Sachin-chaurasiya** [comment]
I would like to work on this tutorial and I will share the outline of the tutorial here.

**Comment by Nomzy-kush** [comment]
I would like to work on this tutorial. I’ll provide an outline shortly.

**Comment by Nomzy-kush** [comment]
Here's an [outline](https://docs.google.com/document/d/11ZYdY7eNrIQTSBHKYCSJhIdFdP-KsduRE_t3sRv57H8/edit?usp=sharing). What do you think?

**Comment by Sachin-chaurasiya** [comment]
Hello @Nomzy-kush, I already build a social card application and I will prepare the outline for the same.
Can you please look at the other issues?

**Comment by PaulBratslavsky** [comment]
@Nomzy-kush and @Sachin-chaurasiya at the moment we are looking for articles that focus on the Strapi side of things more than building something in a framework that is powered by Strapi. 

At the moment we have too many entry-level articles on the web site and looking for more intermediate and advanced topics.

**Comment by PaulBratslavsky** [comment]
Closing this for now, due to a beginner level content idea.  At the moment we have too many entry-level articles on the web site and looking for more intermediate and advanced topics.  We can revisit this in the future.
