### ISSUE TITLE
ecommerce

### ISSUE THREAD

**Issue by fabiopasilva1** [strapi/community-content#1006]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by noblefresh** [comment]
I would like to write on this, can it be assigned to me?

**Comment by PaulBratslavsky** [comment]
@noblefresh We are currently looking for topics that show Strapi's ability to be highly customizable, so looking for ways to customize controllers, services, middleware, and policies.  

You can do something around e-commerce but the focus would have to be more on the Strapi side of things rather than the frontend side.

**Comment by PaulBratslavsky** [comment]
@noblefresh We have many articles in the queue and are only accepting new articles in January of next year. 

I will put this on hold for topic review in January.  

We also have decided to focus our efforts on producing higher-quality content for our readers.

Also, we will be introducing new tags by level beginner, intermediate, and advanced.   As well as update the rate to encourage our writers to write about more intermediate/advanced Strapi content.

We are working on redoing WFC guidelines to reflect these changes and providing some common topics that our community and members request.

If you have any questions, feel free to reach out to me on Discord in the WFC community channel.

**Comment by danielonugha0** [comment]
Hi
I would love to write on this topic

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky @Mcastres 
I would love to write on this topic

**Comment by Enecode** [comment]
> **My Request**
> 
> **Community vote** +1 Upvote if you like this topic rocket If you can make the article/video!
> 
> Thank you.

I would love to write on this topic.

**Comment by Enecode** [comment]
Kindly assigned this topic to me.

**Comment by PaulBratslavsky** [comment]
Because we have similar post around this topic already will be closing this issue.
