### ISSUE TITLE
How to Build a News Blog using Laravel, Breeze & Blade  + TailwindCSS with Strapi API

### ISSUE THREAD

**Issue by noblefresh** [strapi/community-content#1008]
**My Article Proposal is**

**Introduction**
In this article, we will be learning How Build a News Blog using Laravel, Breeze & Blade  + TailwindCSS with Strapi API. This will serve as a guild for Laravel developers who has been finding it difficult to integrate Strapi API with Laravel.

**Outline**
Introduction
What is Laravel
What is Strapi
Prerequisites
Setup Strapi
Create a Content Type
Create an Entry
Generate Token
Setup Laravel
Install Breeze + Tailwind
Configuring .env file
Integrating Strapi API with Laravel
Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article

**What do you all think?**
❤️ I love it!

**Comment by dessireugarte** [comment]
Hello @noblefresh 👋 We already have similar articles, and we are trying to focus more on intermediate-advanced content. 
Please feel free to check the open issues that are looking for an author in Write For The Community and Update v4 or suggest another topic. 
Take care!
