### ISSUE TITLE
[TOPIC] How to connect Strapi to a MySQL db

### ISSUE THREAD

**Issue by RazvanCretu** [strapi/community-content#101]
Hi there,

I'm currently a new developer with Strapi and I think a tutorial on how to connect Strapi to a MySQL db would be nice.

Thanks in advance.

**Comment by RazvanCretu** [comment]
How am I supposed to create a MySQL db using strapi ?

I've run the following commands:
? Choose your installation type Custom (manual settings)
? Choose your main database: MySQL
? Database name: demodatabase
? Host: 127.0.0.1
? Port: 3306
? Username: root
? Password: *****
? Enable SSL connection: false

And I got the following error:
⏳ Testing database connection...
It might take a minute, please have a coffee ☕️
⚠️  Database connection has failed! Make sure your "demodatabase" database exist.
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

I am using MySQL 8.0.20 and the database was created using MySQL Workbench.

Did I miss something or got it wrong ?
Can someone help me?

**Comment by Mcastres** [comment]
Hello @RazvanCretu ! Did you created the `demodatabase` database first?

**Comment by RazvanCretu** [comment]
> 
> 
> Hello @RazvanCretu ! Did you created the `demodatabase` database first?

Hi @Mcastres 

I managed to connect it to the mysql db somehow with from help from this https://github.com/strapi/strapi/issues/2782 issue. I needed to downgrade MySQL version to 5.6. As it seems MySQL authentication pulgin was upgraded to caching_sha2_password which Strapi doesn't support.

**Comment by malgamves** [comment]
Hey @RazvanCretu are you willing to document your solution to the issue with an article? I think it would be really helpful for other people with the same problem.

**Comment by RazvanCretu** [comment]
> Hey @RazvanCretu are you willing to document your solution to the issue with an article? I think it would be really helpful for other people with the same problem.

Hi @malgamves 

Yes, thanks for writing me. I would be really glad to help. Should we get in touch somewhere else? Mainly not to spam here and to further discuss.

**Comment by malgamves** [comment]
Yes please! You can text me in the [Strapi Slack](https://slack.strapi.io), my name is Daniel Madalitso Phiri. Happy to discuss further there.

**Comment by malgamves** [comment]
[Configuring Strapi and MySQL](https://strapi.io/blog/configuring-strapi-mysql-database)

**Comment by Mehrdad-Dehghanzadeh** [comment]
if you use MySql Version 8 you must reconfigure to authentication method to legacy
![image](https://user-images.githubusercontent.com/77623680/158034246-12e89bb9-b5cc-433f-92eb-8735833a93d2.png)

**Comment by malgamves** [comment]
Looks like we'll have to update this article @Mehrdad-Dehghanzadeh ?

**Comment by jpcmf** [comment]
I'm facing this issue when deploying the app to GCP. There is any way to use mysql2 in the database config or any other workaround?

**Comment by nwokolawrence6** [comment]
> I'm facing this issue when deploying the app to GCP. There is any way to use mysql2 in the database config or any other workaround?
For a temp fix use the following:

```shell
yarn add mysql2 patch-package postinstall-postinstall
```

**Create a folder in the root project called `patches`**

[@strapi+database+4.1.11.patch.zip](https://github.com/strapi/community-content/files/8698991/%40strapi%2Bdatabase%2B4.1.11.patch.zip)

Download the zip file above and extract its content

copy or move the content of the zip to the folder you created called `patches` in your project.

add the following to your package.json scripts 

"postinstall": "patch-package"
 
 Your Package.json should not look like this

``` json
{
  "name": "deeptechwebsiteserver",
  "private": true,
  "version": "0.1.0",
  "description": "Deep tech cms",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "postinstall": "patch-package",
    "strapi": "strapi"
  },
  "devDependencies": {
    "patch-package": "^6.4.7",
    "postinstall-postinstall": "^2.1.0"
  },
  "dependencies": {
    "@strapi/plugin-i18n": "4.1.11",
    "@strapi/plugin-users-permissions": "4.1.11",
    "@strapi/strapi": "4.1.11",
    "mysql": "2.18.1",
    "mysql2": "^2.3.3"
  },
  "author": {
    "name": "Deep technology's"
  },
  "strapi": {
    "uuid": "d8ee59f4-dd4f-4cd9-9adf-cac0182c35b6"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```
 Then run `yarn install` to implement the patch.

**Comment by jpcmf** [comment]
@nwokolawrence6 We decided to use the mysql 5.7 at the moment so we downgrade our database. But thank you for your message. All the best!

**Comment by hossj** [comment]
For anyone having this issue you can always go ahead and make your MySQL user use the native password method like so:

`ALTER USER myuser IDENTIFIED WITH mysql_native_password BY 'mypassword';`

Change "myuser" and "mypassword" of course.

**Comment by Black1978** [comment]
> ```json
> "devDependencies": {
>     "patch-package": "^6.4.7",
>     "postinstall-postinstall": "^2.1.0"
>   },
> ```

This method does not work.

**Comment by TharunBalaji2004** [comment]
I solved the issue:
>ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

by installing `mysql2` node module directly to my strapi backend folder.

Run the command: `npm install mysql2 --save` and re run the strapi project. 

You are good to go now!
