### ISSUE TITLE
[SUBMIT] How to link your Strapi notification systems with Novu for central management

### ISSUE THREAD

**Issue by MwendwaDev** [strapi/community-content#1010]
**My resource**

Hello @PaulBratslavsky I would love to write an article on How to link your Strapi notification systems with Novu for central management 👋 

Outline
Introduction
What is Novu and why you need it
Setting up a Strapi project with a notification system e.g email
Setting up Novu
Linking Novu with the project for central notification management
Conclusion and a CTA

**My content is**

- [x] A Strapi Tutorial

**Comment by PaulBratslavsky** [comment]
@MwendwaDev  We have many articles in the queue and are only accepting new articles in January of next year. 

I will put this on hold for topic review in January.  But this topic does sound interesting.  Quick question, is the email be sent by Strapi or Novu.

We also have decided to focus our efforts on producing higher-quality content for our readers.

Also, we will be introducing new tags by level beginner, intermediate, and advanced.   As well as update the rate to encourage our writers to write about more intermediate/advanced Strapi content.

We are working on redoing WFC guidelines to reflect these changes and providing some common topics that our community and members request.

If you have any questions, feel free to reach out to me on Discord in the WFC community channel.

**Comment by PaulBratslavsky** [comment]
At the moment we are looking for more specific articles on Strapi backend customization.  For the time being will be closing this issue.  Maybe we can revisit this topic in the future.
