### ISSUE TITLE
[SUBMIT] Building a Remix app with Tailwind and fetching data via GraphQL from a Strapi server

### ISSUE THREAD

**Issue by Dmuasya** [strapi/community-content#1012]
**My resource**

Hello 👋 @PaulBratslavsky @Mcastres

This article will examine how we can set up a Remix app with Tailwind, and Typescript, and fetch data via GraphQL from a Strapi server. With Strapi, we have access to multiple resources that enable user requests to the Headless CMS API to fetch data easily and perform actions only available to the users. With Strapi API, users can quickly fetch data for our application and focus on building.

Outline:
- Introduction
- What is Stapi 
- What is Remix
- Set up Strapi and Create collection Types 
- Set up the Remix Application and components
- Tailwind CSS Setup with Remix
- Add a link to our new page
- Create Fetch Route
- Fetching all the posts from Strapi
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jam stack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@Dmuasya We have many articles in the queue and are only accepting new articles in January of next year. 

I will put this on hold for topic review in January.  

We also have decided to focus our efforts on producing higher-quality content for our readers.

Also, we will be introducing new tags by level beginner, intermediate, and advanced.   As well as update the rate to encourage our writers to write about more intermediate/advanced Strapi content.

We are working on redoing WFC guidelines to reflect these changes and providing some common topics that our community and members request.

Currently reading this description, I feel like it is a `beginner` type of article.  If you wanted to take it to the next lever, I would change this to, how to create a Submission Form with Remix where you show how to submit a form with an Image Upload.  That would make it more `intermediate` lever article.  

If you would also add a function to send an email via Strapi each time a from is submitted that would putt the article to `intermediate/advanced` which will increase your chances of acceptance. 

If you have any questions, feel free to reach out to me on Discord in the WFC community channel.

**Comment by PaulBratslavsky** [comment]
Thank you for your submission. After further review, we have decided to close this issue as we are currently seeking more articles on Strapi backend customization. We appreciate your contribution and hope to consider your topic in the future.
