### ISSUE TITLE
[SUBMIT] : TypeScript Generics -  Ability to abstract types

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [strapi/community-content#1014]
**My resource**
Hello 👋 , I would like to submit a proposal for the topic **TypeScript Generics -  Ability to abstract types**

**Outline:**
- Introduction to typescript
- Introduction to typescript generics
- What problems generics solves
- When to Use Generics
- Generic interface
- Generic Classes
- Generic Functions
- Generic Constraints
- Generics use cases
- Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [x] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by Sachin-chaurasiya** [comment]
Hello @PaulBratslavsky @dessireugarte, I would like to work on this article and I have provided the outline in the issue template.
Thank you.
[Sachin Chaurasiya](https://strapi.io/user/sachin-chaurasiya)

**Comment by PaulBratslavsky** [comment]
@Sachin-chaurasiya quick question is this something you will do within Strapi or is this going to be stand alone example using a frontend framework?

**Comment by PaulBratslavsky** [comment]
@Sachin-chaurasiya so not in relation to Strapi?  Still interesting idea.  For the moment we are not accepting new article submissions till January.  But I will put this on hold and revisit.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya so not in relation to Strapi? Still interesting idea. For the moment we are not accepting new article submissions till January. But I will put this on hold and revisit.

Thanks @PaulBratslavsky

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky @Sachin-chaurasiya 

I would love to write on this topic

Best regards
DO

**Comment by PaulBratslavsky** [comment]
At the moment we are looking for Strapi specific content around backend customizations, I will be closing this issue and maybe we can revisit this topic in the future.
