### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Deploying a Strapi API on Heroku in 5 min

### ISSUE THREAD

**Issue by malgamves** [strapi/community-content#1024]
Hey [this article is updated](https://strapi.io/blog/deploying-a-strapi-api-on-heroku), we need to add the need for env vars to the blog post. 

happy to take this on next week!

**Comment by PaulBratslavsky** [comment]
Thanks for taking this up @malgamves I will change to on hold for now until you are able to get to it.

**Comment by malgamves** [comment]
updated this @PaulBratslavsky - I think we can close it.
