### ISSUE TITLE
[SUBMIT] Build Electronic Signature and Agreement Platform with Strapi and Sign Now

### ISSUE THREAD

**Issue by amirtds** [strapi/community-content#1025]
**Outline**
- Pre-requisites
- Goals
- Introduction
- What we are going to build ?
- Step 1 - Create Customers content type
- Step 2 - Create Contracts  content type
- Step 3 - Add a customer and create a contract
- Step 4 - Setup GraphQL Apis on Strapi
- Step 5 - Sign Now Configuration
- Step 6 - Generate PDF on Contract creation on Strapi
- Step 7 - Upload the contract to Sign Now
- Step 8 - Send signing Invite to the customer
- Step 9 - Notify both parties when the contract is signed
- Let's see how it works in real world
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@amirtds I know you are starting working on the LMS articles, is this going to be part of that series or is this separate?  If so, lets focus on one article at a time.

**Comment by amirtds** [comment]
@PaulBratslavsky This is going to be a separate article, makes sense let's hold off on this one for now until i finish the LMS article. Thank you

**Comment by PaulBratslavsky** [comment]
Just to clean up the issues, I will be closing this topic for the time being and we can revisit in the future.
