### ISSUE TITLE
[SUBMIT] Build Headless Learning Management System with Strapi - Part 1

### ISSUE THREAD

**Issue by amirtds** [strapi/community-content#1026]
**My resource**
- Pre-requisites
- Goals
- Introduction
- What is an LMS  ?
- Why Headless LMS and problems it's going to solve ?
- What we are going to build ?
- Step 1 - Install Strapi
- Step 2 - Create Users content type
- Step 3 - Handling Authentication and Authorizations
- Step 4 - Integration with third party IDP
- Step 5 - Build the Frontend of the LMS (We use Next.js)
- Step 6 - Connect Frontend and Backend together
- Step 7 - Test Login and Registration
- Next Article ( in this article we go through course structure and it's content type in Strapi )
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@amirtds Thanks for creating the issue, we talked a while back so glad to see this moving forwards.  Will assign to you.

**Comment by amirtds** [comment]
Awesome, thank you @PaulBratslavsky I start working on it and will send some updates here soon

**Comment by amirtds** [comment]
@PaulBratslavsky The Part 1 is ready https://www.dropbox.com/scl/fi/3wi4exproq5e1cawd2pes/Build-Headless-Learning-Management-System-with-Strapi-Part-1.paper?dl=0&rlkey=pypi5i3xakj8r3elkqpnsex3v

**Comment by PaulBratslavsky** [comment]
@amirtds I will take a look and review.

**Comment by PaulBratslavsky** [comment]
@amirtds I am finally able to get to your article, sorry for the delay,  should be done with the review tomorrow ( Friday ).

**Comment by amirtds** [comment]
Thanks @PaulBratslavsky let me know if you have any feedbacks

**Comment by PaulBratslavsky** [comment]
@amirtds reviewing your article today did not get to it on Friday will let you know if I have feedback or changes.

**Comment by PaulBratslavsky** [comment]
@amirtds finished the review great job.  We were going to release it as a series, so it you haven't started working on part 2 yet, you can do so.  Let me know if you have any additional questions.

**Comment by amirtds** [comment]
Awesome thank you @PaulBratslavsky

**Comment by vcoisne** [comment]
Hello @amirtds  do you have an ETA for when part 2 might be ready ?

**Comment by dessireugarte** [comment]
Hello @amirtds! Thanks for submitting your invoice. 
This article is intermediate, so we need you to submit it again for $250. 
Also, before starting with the other part (or parts), could you please submit the content brief of the other parts of the tutorials? That way, we can establish a timeline since we won't be able to publish this article until we have the rest of the articles ready.

**Comment by amirtds** [comment]
Thanks @dessireugarte I submitted new request for $250
Sure thing, I add the outline for the next articles so you can organize stuff on your end.

**Comment by vcoisne** [comment]
Hey @amirtds we would love to publish this article. Did you get a chance to work on part ?

**Comment by PaulBratslavsky** [comment]
@amirtds just wanted to check in one more time if you had a chance to start working on the second part of the article?

**Comment by amirtds** [comment]
Hi @vcoisne @PaulBratslavsky Thanks for following up. I had to pause working on these series but i wanted to know if Strapi is interested to sponsor a final product of LMS headless implementation with Strapi and I can document it as well to multiple blog posts. let me know please what do you think

**Comment by vcoisne** [comment]
Hi @amirtds we don't have the budget to sponsor products but I will send you a DM to understand your expectations in terms of compensation.
