### ISSUE TITLE
[SUBMIT] Real-time tic-tac-toe app built using Strapi, Socket IO and Vue

### ISSUE THREAD

**Issue by i1d9** [strapi/community-content#1030]
Hello 👋 

This tutorial will guide you on how to power a tic-tac-toe game using Strapi. Users will use Strapi to authenticate. We will add sockets to Strapi's HTTP server to broadcast our users' moves. Our Strapi instance will also be responsible for pairing two users in a gaming room(socket channels). Our users will interact with a Vue application which will broadcast and subscribe to socket events associated with a specific gaming room.  Through this implementation, our users have as many simultaneous gaming sessions as they like. Since we are using sockets, their moves will be displayed to their opponents as soon as they occur.

Outline
- Introduction
- Prerequisites 
- Why Socket IO and Vue
- Initializing a Stapi Project
- Setting up Socket IO 
- Initializing the Vue Project
- Persisting State
- UI Component Mapping
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
Thank you for the submission.  Upon farther review and similar topics already present in our blog https://strapi.io/blog/how-to-create-a-real-time-bidding-app-using-strapi-v4-vue-and-socket-io we are going to close this issue for the time being to clean up our issues in WFC.
