### ISSUE TITLE
[SUBMIT] How to integrate machine learning with Tensorflow.js into your Strapi application

### ISSUE THREAD

**Issue by i1d9** [strapi/community-content#1031]
Hello 👋 

In this tutorial we will be creating a machine learning socket API powered by Strapi. We will learn how to extend default Strapi functionalities to add full duplex communication channels. In addition to this, we will integrate a machine learning library and train a model. We will then use the communication channels to serve authenticated users with predictions based on input they provide. Finally we will set up a cron job that will be responsible for retraining the model.

Outline
- Introduction
- What is tensorflow?
- Why pair tensor flow with strapi
- Setting up Strapi
- Tensorflow Setup
- Training and prediction with a tensor flow model
- Setting up a Vue project
- Consuming the ML API
- Conclusion

**My content is**

- [X] A Strapi Tutorial / Guide / How to article
- [X] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**Comment by hanakhelifa** [comment]
Hello @i1d9, 
Thanks for this submission. I will close this issue as we are revamping the program. I found the topic very interesting and will come back to you.
