### ISSUE TITLE
How to Use the Strapi Console [SUBMIT]

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#1032]
**My resource**

Hello @dessireugarte 👋 
I will like to write on this topic **How to Use the Strapi Console**, here is my outline for the article.

- Introduction
- Brief introduction to strapi?
- Strapi installation
- What is strapi console?
- Benefit of using strapi console
- How the strapi console works
- How to use the strapi console
- Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by dessireugarte** [comment]
Hello @popoolatopzy 👋
Thanks for submitting the topic. We are currently looking for more advanced topics, and this one is a topic we have already covered in other tutorials in the past. Feel free to send another one or provide an outline proposal for topics already requested.

**Comment by Chudroy** [comment]
Information on the strapi console is scarce. I have tried looking at the docs, the strapi blog and youtube, and I have found one relevant video, which is 7 minutes long. More information, or a page on the docs would be useful.
