### ISSUE TITLE
[Request New Content] On Premise vs. Cloud

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#1034]
**My Request**
 An article that explains the meaning of each, key differences in terms of deployment, cost, security, cost, etc. And which one should the people choose depending on their use case. 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Saintdavidking** [comment]
Hi @dessireugarte,
I will like to take on this topic

**Comment by dessireugarte** [comment]
Hello @Saintdavidking 👋 Could you please share an outline of how the article would look like?

**Comment by Saintdavidking** [comment]
Hello @dessireugarte  here is my proposed outline

Topic: On-Premise vs. Cloud

Outline:

- Introduction
- What is Cloud?
- What is On-Premise?
- Pros and Cons of On-Premise
- Pros and Cons of Cloud
- On-Premise vs. Cloud the difference.
- Conclusion

**Comment by Saintdavidking** [comment]
Hello, @dessireugarte

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky I would like to write on this topic

**Comment by danielonugha0** [comment]
Hi @dessireugarte I would love to write on this topic

**Comment by dessireugarte** [comment]
Hello @Saintdavidking!
Sorry for the late answer. 
Yes please go ahead. 
@danielonugha0 , we will add other topics about cloud soon that you could take.

**Comment by danielonugha0** [comment]
Comparing On-Premise Vs. Cloud
The difference between cloud vs on-premise software is where it resides.
Cloud is the practice of using a network of remote servers hosted on the internet to store, manage, and process data, rather than a local server or a personal computer.
On-premises is the software and technology that is located within the physical confines of an enterprise often in the company’s [data center](https://www.webopedia.com/definitions/data-center/) as opposed to running remotely on hosted [servers](https://www.webopedia.com/definitions/server/) or in the [cloud](https://www.webopedia.com/definitions/cloud/).

Goal
In this article, we will zoom in on two popular software programs: on-premise vs. cloud.

Table of Content

- introduction
- what is on-premise?
    - Advantages of on-premise
    - Disadvantages of on-premise
- What is Cloud?
    - Advantages of cloud
    - Disadvantages of cloud
- Differences between on-premise and cloud
    - deployment
    - Cost 
    - Control
    - Security
- Comparison between on-premise and cloud
- Conclusion

**Comment by Saintdavidking** [comment]
Hi @dessireugarte!
Alright, thanks.

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky @Saintdavidking @dessireugarte 

Should I go ahead ?

**Comment by dessireugarte** [comment]
Hello @danielonugha0 ! This topic is taken, but you can take a look at [this](https://github.com/strapi/community-content/issues/1080) one and submit an outline if you are interested.

**Comment by Saintdavidking** [comment]
Hello @dessireugarte ! here is the link to the article draft 

https://www.dropbox.com/scl/fi/93gypv656pnna01ynlwqn/On-Premise-vs-Cloud.paper?dl=0&rlkey=p8ptc9f1nfpdiurt4z99rv753

**Comment by dessireugarte** [comment]
Hello @Saintdavidking !
Sorry for the late reply, I'll review the article and will get back to you with comments in case we need to change something.

**Comment by dessireugarte** [comment]
Hello @Saintdavidking  👋 
Your article is [live](https://strapi.io/blog/on-premise-vs-cloud-solutions-which-is-the-best-for-your-business)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also, please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) for $150, and soon you will receive your payment.
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by dessireugarte** [comment]
@Saintdavidking please remember to submit the invoice!

**Comment by Saintdavidking** [comment]
Hi @dessireugarte, Thanks, I have submitted the invoice.

**Comment by dessireugarte** [comment]
Hello @Saintdavidking! 
Just wanted to let you know that instead of submitting the invoice, you submitted your bank account proof. We need the invoice to request the payment.

**Comment by Saintdavidking** [comment]
Hi @dessireugarte  Thanks for the update and correction, I have issued the correct invoice
