### ISSUE TITLE
[SUBMIT] Monitoring Strapi with Datadog  

### ISSUE THREAD

**Issue by omarkhairy21** [strapi/community-content#1036]
**My resource**
Hello, I noticed there are no tutorials for monitoring(collecting logs, tracing, and APM) and I can write a tutorial so if there is interest in that topic i would start to prepare the outline.
**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by hanakhelifa** [comment]
Hello @omarkhairy21 
I see the issue is nearly a year old. The topic was very interesting, and I'll reach out to you as soon as it will be launched. I am closing this issue in the meantime as we are revamping the program.
