### ISSUE TITLE
[Request New Content] Multi-tenancy Approach in Strapi 

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#1038]
**My Request**

A tutorial diving into Multi-tenancy in Strapi. Reference: [StrapiConf talk](https://www.youtube.com/watch?v=TPhuNTm5hqg). 
@eventyret will take this topic. 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Eventyret** [comment]
Sure will do it 😊🚀👍

**Comment by Eventyret** [comment]
Sorry i have not been able to start this @dessireugarte will see if I get some time this month.

**Comment by dessireugarte** [comment]
After discussing with @Eventyret, we decided to close this issue for now.
