### ISSUE TITLE
Import-content plugin issue with Strapi 3.01.

### ISSUE THREAD

**Issue by jay01011986** [strapi/community-content#104]
import-content plugin is not working on Strapi 3.0.1

Which tutorial has an issue?

Strapi 3.0.1 onwards, strapi has changed the way it was supporting the plugins. Therefore the following comaanda are not working now with latest Strapi:
strapi generate:plugin import-content

Would you please upload the revised version of this plugin that is supported by latest version of Strapi?

**Comment by chirdeeptomar** [comment]
Can this plugin be made a part of the marketplace? I tried upgrading the plugin but it uses outdated npm packages like request and uuid/uuid4. Having fixed all the node issues, I gave up as Admin wouldn't show up which could be to do with how strapi registers plugins etc post 3.0.1

**Comment by Mcastres** [comment]
Hello @jay01011986, thanks for noticing this issue.

@pouyamiralayi is the creator of this plugin and might be able to fix this when he will be available :)

**Comment by zarcode** [comment]
@pouyamiralayi +1
