### ISSUE TITLE
[SUBMIT] Series About building complex backend with Strapi

### ISSUE THREAD

**Issue by goodhoko** [strapi/community-content#1040]
Hi,
right now I'm finishing a complex backend built with Strapi that is unfortunately closed-source. However, I'm considering to share the experience in form of a series of articles. Because I can't share the business logic my idea is to base the series around building the [well](https://strapi.io/blog/strapi-next-restaurants)-[known](https://strapi.io/blog/nextjs-react-hooks-strapi-restaurants-2) Restaurant demo but diving deep into all the auxiliary topics that are required to build a *robust* backend. Here's a list of articles and the topics they'd touch upon:

###  Development Setup for Building Complex Strapi Apps
- repeatable environment using docker compose
- keeping code clean with linters
- maintaining clean git history by leveraging git hooks
- bringing up basic CI pipeline on GitHub actions to uphold standards with every commit
- managing Strapi configuration with the config-sync plugin

### How to Thoroughly test Your Strapi App
- How to test your Strapi code
- Reusing the environment codified with docker-compose to run tests
- Seeding database with testing data and pruning them after tests finish
- How to isolate tests with transactions
- How to test endpoints that require authentication and avoid rate limiting

### How to Deploy Strapi to Digital Ocean
- Using Terraform to codify and provision infrastructure and to manage secrets
- Using separate environments for staging and production
- CD pipeline
- Observability: collecting runtime logs
- Monitoring: uptime checks and alerts

In every article I'd always try to start from first principles (e.g. "Why it's important to codify your development environment?") then going through my solution diving into all its details and decisions (e.g. "We'll use docker compose for it's prevalence and availability of ready-made images for databases") to finally discuss it's limitations and possible next steps (e.g. "Building the and running docker images is resource intensive and we may want to avoid docker for some tasks that can be run natively, for instance, linting")

Let me know if this kind of content *and form* is wanted and if you'd like to add/remove some topics.

PS: I know that accepting new articles is paused until new year. I'm fine with you getting to this whenever you'll get to this.

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by Xemarij** [comment]
Hi @PaulBratslavsky and @Mcastres,

I am interested in helping you here is my outline: 

I. Introduction
Definition of Strapi and its capabilities as a backend platform
Importance of building a complex backend for modern web and mobile applications

II. Prerequisites
Setting up a Strapi project
Familiarity with Node.js, Express, and the MongoDB database

III. Building a complex backend with Strapi
Setting up content types and relationships in the Strapi admin panel
Defining custom routes and controllers for advanced functionality
Using Strapi's hook system to customize the backend behavior
Integrating with external APIs and services

IV. Testing and debugging the backend
Setting up testing and debugging tools, such as Postman and the Strapi debugger
Testing the backend endpoints and functionality

V. Deploying the backend
Choosing a hosting provider and setting up a production environment
Configuring the Strapi project for deployment
Deploying the backend to the production environment

VI. Conclusion
Recap of the steps to build a complex backend with Strapi
Tips for successful development and deployment of the backend.

**Comment by PaulBratslavsky** [comment]
@goodhoko this sounds like a valuable article,  I will assign it to you.  You can start working on it.

**Comment by goodhoko** [comment]
@PaulBratslavsky Thanks! Maybe it wasn't clear but I proposed a series of 3 articles. Let me know if that changes your decision in any way.

**Comment by PaulBratslavsky** [comment]
@goodhoko thank you for clarifying.  Sounds good.

**Comment by goodhoko** [comment]
I'll first need to clear some licensing details on my side so I probably wont start writing sooner than at the end of February. I will keep this issue updated.

**Comment by PaulBratslavsky** [comment]
@goodhoko sorry for the late response.  Let us know when you are able to continue with the article.

**Comment by PaulBratslavsky** [comment]
@goodhoko hope you are well, just wanted to check in if you still have the bandwidth or the time to write this series.

**Comment by goodhoko** [comment]
@PaulBratslavsky Hi, sorry for taking much time to respond.

To be honest, since I put down this proposal I reconsidered viability of Strapi as a base for anything more complex than a simple blog. I can't recommend Strapi for building _robust_ apps with a straight face.

Mainly because Strapi is developed with little care for stability and backward compatibility. It's unnecessarily complex to develop anything outside the most simple use-cases. The performance isn't there. And lastly, the product's approach to security is questionable.

I'm sorry, but I don't plan to work on these articles anymore.

**Comment by PaulBratslavsky** [comment]
@goodhoko thank you for your feedback. To help us improve, are there any specific examples that you would mind sharing.  You can email me at paul.bratslavsky@strapi.io  

Your feed back will be appreciated.
