### ISSUE TITLE
[SUBMIT] Using transactions with Strapi v4 - with tests 

### ISSUE THREAD

**Issue by team-strapi-ufirst** [strapi/community-content#1043]
**My resource**

Hello Strapi team 👋 

I'd like to write an article about transactions with Strapi v4, including tests. 
We show how to avoid currupted data by using transactions. You will learn how to use transactions in Strapi v4 in oder to either commit new data or rollback the whole transaction - and how to create unit tests for those transactions.

This article will be intermediate level.

Required for being able to understand the article: 

- Basic knowledge of JavaScript
- Basic understanding of Strapi
- Basic knowledge of testing and Jest

Outline:

- Introduction
- Why are we wanted to use transactions
- How we use transactions
- Testing
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@team-strapi-ufirst sorry for really later response, this issue went under my radar.  If you would still like to write this article please let me know.  Again apologies for not getting back to you on time. It was my fault.

**Comment by team-strapi-ufirst** [comment]
Thanks @PaulBratslavsky. We still would very much like to write the article.

**Comment by PaulBratslavsky** [comment]
@team-strapi-ufirst I finished the review and we are ready to publish your article.  Please confirm that you received this message.

**Comment by team-strapi-ufirst** [comment]
@PaulBratslavsky Thank you for reviewing the article.
