### ISSUE TITLE
[SUBMIT] Deploy Strapi on AWS Elastic Beanstalk using Docker

### ISSUE THREAD

**Issue by yinjisheng311** [strapi/community-content#105]
**My resource**
Deploying Strapi onto AWS Elastic Beanstalk using Docker. I've got the steps documented out using eb-cli and the Dockerfile needed to get this to work. I personally struggled with this part a bit and hope this can help others. You can check out my Medium post [here](https://medium.com/@yinjisheng/how-to-deploy-strapi-on-aws-elastic-beanstalk-using-docker-31766b2dd73e)

**My format**

- [X] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Thanks @yinjisheng311 
I'll take some time to review it this week ;)
