### ISSUE TITLE
complete steps for installing strapi because am getting error

### ISSUE THREAD

**Issue by PadminiP2603** [strapi/community-content#1059]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ranjithjupaka** [comment]
i am interested in writing an article

**Comment by PadminiP2603** [comment]
Yes.. Please

**Comment by ranjithjupaka** [comment]
do i need to provide an outline or will you assign directly?

**Comment by PadminiP2603** [comment]
Provide outline.. 
Before that i will explain my error.. 
Command line:npx create-strapi-app@latest my-projects. 
Error:Cannot find module '@sentry/hub'
I have installed nodejs and npm latest version

**Comment by ranjithjupaka** [comment]
can you specify the version numbers as well

**Comment by PadminiP2603** [comment]
All latest version

**Comment by ranjithjupaka** [comment]
did you opted manual installation ?

**Comment by ranjithjupaka** [comment]
will reproduce the error and then will share the routine here

**Comment by PadminiP2603** [comment]
Thank you for helping me out..

**Comment by PaulBratslavsky** [comment]
This will be more appropriate as a forum post rather than a blog post.  You can create it here https://forum.strapi.io/. Closing this issue for now since a forum post on this topic will be more appropriate.
