### ISSUE TITLE
[SUBMIT] Integrating Reactjs App with Strapi(Headless CMS) 

### ISSUE THREAD

**Issue by Geo-free** [strapi/community-content#1065]
## Introduction
Strapi was basically developed as a bootstrap for API and later evolved to a headless CMS.

What is Headless CMS? Headless CMS implies that all the content that you publish can be retrieved via an API, Headless CMS, is very common today in the technology field.

## Outline
In this article, I will be looking at how a Reactjs app can be integrated with Strapi. The key points will be:
- What is Strapi
- What is a Headless CMS
- Setting up Strapi
- Authoring the content
- Using the authored content to build a Reactjs log-in form

**Comment by Xemarij** [comment]
Hi @PaulBratslavsky and @Mcastres,

I am interested in writing on the topic. Please see my outline in the following:

I. Introduction

Definition of React and Strapi
Importance of integrating a React app with a headless CMS like Strapi

II. Prerequisites

Installing and setting up React
Installing and setting up Strapi

III. Integrating the React app with Strapi

Setting up the Strapi server and creating a new content type
Installing the Strapi client library in the React app
Fetching data from the Strapi server and displaying it in the React app

IV. Customizing the integration

Setting up authentication and authorization in the React app
Creating, updating, and deleting content using the Strapi API
Customizing the data displayed in the React app based on user input

V. Testing the integration

Sending requests to the Strapi server from the React app
Debugging any issues that may arise

VI. Conclusion

Recap of the steps to integrate a React app with Strapi
Tips for successful integration and future development with Strapi and React.

**Comment by PaulBratslavsky** [comment]
@Xemarij we already have similar articles published in our blog, so for time being will be closing this issue.
