### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Cooking a Deliveroo clone with Nuxt.js (Vue), GraphQL, Strapi and Stripe V4

### ISSUE THREAD

**Issue by sonicviz** [strapi/community-content#1073]
**Description**
Hi,

re: https://github.com/strapi/community-content/tree/master/tutorials/code/deliveroo-clone-nuxt-strapi-tutorial

It says this was updated for Strapi V4, yet the github repo for the server is:
“dependencies”: {
“knex”: “latest”,
“lodash”: “^4.17.5”,
“sqlite3”: “latest”,
“strapi”: “3.6.10”,
“strapi-admin”: “3.0.0-beta.16.4”,
“strapi-hook-bookshelf”: “3.0.0-beta.16.4”,
“strapi-hook-knex”: “3.0.0-beta.16.4”,
“strapi-plugin-content-manager”: “3.0.0-beta.16.4”,
“strapi-plugin-content-type-builder”: “3.0.0-beta.16.4”,
“strapi-plugin-email”: “3.0.0-beta.16.4”,
“strapi-plugin-graphql”: “3.0.0-beta.16.4”,
“strapi-plugin-settings-manager”: “3.0.0-beta.16.4”,
“strapi-plugin-upload”: “3.0.0-beta.16.4”,
“strapi-plugin-users-permissions”: “3.0.0-beta.16.4”,
“strapi-utils”: “3.0.0-beta.16.4”,
“stripe”: “^8.11.0”

Trying to update it by changing version number 4.5.4 with yarn pulls up a dialog that asks you to select from version 3 choices only.

Is there a V4 github repo of this that is consistent with the tutorial saying " [Strapi v4]This tutorial was updated with Strapi v4."?

Trying to upskill on Strapi using tutorials is discouraging when the first thing you hit is the repo doesn’t reflect the actual tutorial, and as such there’s no guarantee it will work especially with out of date versions and packages (node18 issues anyone?).

If it hasn’t actually been tested under V4 (as it shows in the repo) then you can’t put " [Strapi v4](https://strapi.io/blog/categories/tutorials?type=v4) This tutorial was updated with Strapi v4." on the tutorial. Code has to be verified to work in order for it to be useful as a tutorial. I just spent time debugging another tutorial here so I’m wary of this issue. [Registration and Login (Authentication) with Vue.js and Strapi](https://forum.strapi.io/t/registration-and-login-authentication-with-vue-js-and-strapi/19954)

Also, if the tutorial repo cannot be updated to properly reflect what it says it is (ie: V4 compatible) then it should be removed. There is nothing worse than tutorials which are innacurate and end up wasting a developers time, especially when they are trying to learn a new technology. The learning content MUST be reliable and accurate.

Thanks!

**Comment by lucky4242** [comment]
Hi @dessireugarte  
Can I start working on updating this article?

**Comment by petipois** [comment]
I would like to update this article, however I would like to know do i have to start from scratch and use this article as a guide or can I reuse the parts that are still relevant? Also what would be compensation look like?

**Comment by petipois** [comment]
I am going through this tutorial locally on my machine and would documenting my updates so far I am using tailwind css instead of uikit and nuxt nuxt apollo instead of graphql tags.

**Comment by sonicviz** [comment]
Does it work?

**Comment by petipois** [comment]
I haven't reach the stripe section yet but so far it is working. I'm documenting the differences in the code to get a similar result.

**Comment by hanakhelifa** [comment]
Hello, I see this issue is open for nearly a year. As we are revamping the Write For the Community program, I am closing issue so we can start fresh. If you have any question, please feel free to reach out to me on Strapi's Discord. I have the same name there, and can also be found on the #write-for-the-community canal.
