### ISSUE TITLE
[SUBMIT] Create a Task Time Tracker Chrome Extension with Strapi and ReactJs

### ISSUE THREAD

**Issue by Theodore-Kelechukwu-Onyejiaku** [strapi/community-content#1077]
# Introduction
Chrome extensions are potent tools at the disposal of any user. It can increase effectiveness, solve problems, and lots more. In summary, it extends the browser's capabilities. A task tracker is an application that allows users to allocate time to a particular task. 
## Outline
1. Introduction
2. Setup
3. Strapi Installation
4. Building the React Application
5. Creating a manifest.json file
6. Generating a Build file
7. Customizing Strapi Backend Controller
8. Joining everything together.
9. Adding our application to Google Chrome Extension.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
@PaulBratslavsky @dessireugarte 
Hope you are doing great!

Please can I write about this now? It has been over a month and I have gotten no response. 

Thanks.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
I have been assigned this by @PaulBratslavsky 

Does it mean I can proceed, please?

Best, 
Theodore.

**Comment by dessireugarte** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku! 
Yes please go ahead.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @dessireugarte , @PaulBratslavsky  and Strapi Team.

Thanks for giving me the opportunity to write.

Here is my first draft link:

https://www.dropbox.com/scl/fi/2mor3wl09iblcv2rlvdcj/How-to-Create-a-Task-Time-Tracker-Chrome-Extension-With-Strapi-and-ReactJs.paper?dl=0&rlkey=c21d17y6tfkt2yvf18o3g9eqm

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku I will add it to our review cue and will let you know if I have any feedback.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
That would be great @PaulBratslavsky .

Thanks.

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku I added some notes on your draft. Let me know if you have any questions.

**Comment by PaulBratslavsky** [comment]
I had issues saving some of my comments in the drop box, I think it was my internet.  But here is my repo you can see some of the changes I made.  

1. In Task and App files I would useCallback.

`Task.js`

``` jsx

  // get the time in string of minutes and seconds
  const getTimeString = useCallback(() => {
    const mins = Math.floor((parseInt(task?.attributes?.realTime) - Date.now()) / 60000);
    const seconds = Math.round((parseInt(task?.attributes?.realTime) - Date.now()) / 1000) % 60;
    if (mins <= 0 && seconds <= 0) {
      setTimeString('done');
      return;
    }
    let timeString = 'starting counter';
    timeString = `${mins} min ${seconds} secs`;
    setTimeString(timeString);
  }, [task]);


  const markCompleted = async () => {
    try {
      await axios.put(`${serverUrl}/api/tasks/${task?.id}`, {
        data: {
          completed: true,
          realTime: 0,
        },
      });
      const { chrome } = window;
      let badgeValue = 0;
      chrome?.action?.getBadgeText({}, (badgeText) => {
        badgeValue = parseInt(badgeText);
      });
      badgeValue = (badgeValue + 1).toString();
      chrome.action?.setBadgeText({ text: badgeValue });
      window.location.reload(false);
    } catch (err) {
      alert(err.message);
    }
  };

  const handleDelete = async () => {
    try {
      await axios.delete(`${serverUrl}/api/tasks/${task?.id}`, {
        data: task,
      });
      window.location.reload(false);
    } catch (err) {
      alert(err.message);
    }
  };

  useEffect(() => {
    const timer = setInterval(() => {
      setCount((count) => count + 1);
      getTimeString();
    }, 1000);
    return () => clearInterval(timer);
  }, [getTimeString]);

```

`app.js`

``` jsx

  const getAllTask = useCallback(async () => {
    setFetchError('');
    try {
      // fetch tasks from strapi
      const res = await axios.get(`${serverUrl}/api/tasks`);
      // get result from nested object destructuring
      const {
        data: { data },
      } = res;
      // get tasks that have not been completed
      const tasks = data
        .filter((task) => !task.attributes.completed)
        .map((task) => {
          // check if task has expired
          if (Date.now() > parseInt(task?.attributes?.realTime)) {
            task.attributes.realTime = 0;
            return task;
          }
          return task;
        });
      // get completed tasks
      const completedTasks = data.filter((task) => task.attributes.completed);
      setTasksCompleted(completedTasks);
      updateChromeBadge(completedTasks.length.toString());
      setTasks(tasks.reverse());
    } catch (err) {
      setFetchError(err.message);
    }
  }, [updateChromeBadge]);

  useEffect(() => {
    // get all tasks
    getAllTask();
  }, [getAllTask]);

```

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku we published your article and you can send in your invoice.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thanks @PaulBratslavsky  😊

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky 

Good evening from here. 


I have issues with my US account. Can I send my GBP account in the invoice to receive the money in Great Britain Pounds?

Thanks.

**Comment by dessireugarte** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku! Yes, of course, you just need to submit the information about your bank account and proof it.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you Dessi! 😊

**Comment by dessireugarte** [comment]
Thank you @Theodore-Kelechukwu-Onyejiaku ! I already submitted your invoice, you should receive it by the end of next week. Please feel free to contact me otherwise.

**Comment by dessireugarte** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku! I want to let you know that we received a request from the bank to provide bank details for the intermediary bank by **4/13/2023**. Could you please provide us with that information?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @dessireugarte,

Thanks for the update.
I have sent you an email.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @dessireugarte ,

Please can I use a friend's US account details and create a new invoice if the current issue of bank details for intermediary still persists?

Thanks

**Comment by dessireugarte** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku! I sent you an email with the follow-up to this topic. 
If the payment cannot be made to the bank account you already provided, we could do that next. 
I'll keep you updated.
