### ISSUE TITLE
[SUBMIT] How we used Strapi V4 and Next to create a GitLab App Marketplace in a few hours

### ISSUE THREAD

**Issue by acoudouy** [strapi/community-content#1078]
**My resource**

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

Hey there, I had the idea of explaining how we used Strapi V4 and Next to create https://gitlabintegrations.com/ in a few hours. 

There were tutorials for the Next part (to create generic [appName].js and [category].js with getStaticProps and getStaticPaths) but I did not find any specific to Strapi. 

I'd be happy to write a tutorial if you're interested as well. Let me know what you think!

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by Xemarij** [comment]
Hi,
I am interested in the topic. In case if you do not know me. I am a pro SEO technical writer with 20 years of experience under my belt. My portfolio is as follows:
https://zemaarij.contently.com/

Please assign me the articles, and mention the deadline and guidelines, if any and I will reach back to you.

**Comment by acoudouy** [comment]
Hey @PaulBratslavsky & @Mcastres, I hope you're doing well. Do you have any feedback on this proposal? Thank you

**Comment by PaulBratslavsky** [comment]
At the moment we are not looking on article on how to create web sites powered by Strapi but instead looking for more intermediate/advance articles covering Strapi code backend development and customization. But thank you for your submission.
