### ISSUE TITLE
[SUBMIT] How to create a message hub with Strapi

### ISSUE THREAD

**Issue by zeppaman** [strapi/community-content#1082]
**How to create a message hub with Strapi and websockets**

In this article, I will configure Strapi to activate web socket connections and deliver targeted messages to users or user groups. The tutorial is deep dive into the strapi plugin system and can be reused in real projects that need to send push notifications from server to client.

The outline of the article (1300-1400 words estimated) will be:
1. Introduction
2. What are WebSockets and how to use it
3. Configure strapi
4. Create the WebSocket plugin
5. Create a demo application
6. Conclusions

**My content is**

- [x ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**Comment by PaulBratslavsky** [comment]
@zeppaman can you a little more information on what you will cover when building the WebSockets plugin and what functionality it will have?

**Comment by zeppaman** [comment]
Hello @PaulBratslavsky , my idea is to use Strapi for creating a notification system. Most modern applications need to have an interaction between server and client (eg. open a snack bar message when your order was shipped or just show a notification). Most ready-to-go services for push notifications don't support any business logic (eg. https://azure.microsoft.com/en-us/products/notification-hubs  provides only APIs for subscribing to events and sending a direct notification message to the user). So, in complex applications, you still need to implement the logic for delivering the right message to the right users. What I want to build with Strapi is an API-based system that could allow any developer to manage notifications easily. I want to enable the strapi users to send push messages to users or user groups without writing code o buying external services.


**How this will be possible?**
My idea is to use the data object model of Strapi for mapping the configuration of target groups, topics etc., and then create an endpoint that any client application can trigger to deliver a message. Moreover, the user can write code to trigger notifications based on their needs (eg. when an item is updated). The API will add a message to the queue and will save the delivery status to ensure it is properly delivered to the destination (a user or a group of users). Then, using native cron jobs of Strapi, I would deliver asynchronously the notification with the websocket to the user when connected. This tutorial will be a great showcase because:
- it shows how it is easy to solve problems using Strapi
- it shows how cron jobs work and how to manage the background process 
- it shows how to create a custom endpoint in Strapi and how to use Strapi API for reading/writing data

**Comment by PaulBratslavsky** [comment]
Thanks for expanding on the description. We already have some similar articles on the blog. Also not sure if you knew but we recently released plugin that allows you to integrate socket.io https://market.strapi.io/plugins/strapi-plugin-io.  Will be closing this issue due to similar articles.
