### ISSUE TITLE
[SUBMIT] Overcome the "To do or to buy" dilemma with Strapi

### ISSUE THREAD

**Issue by zeppaman** [strapi/community-content#1083]
** Overcome the "To do or to buy" dilemma with Strapi**

Strapi is a flexible platform that can be used as a headless low-code platform for boosting the time to market and overcoming the limitations of vertical solutions like blogs or e-commerce software. In this article, I will introduce the dilemma of "to buy" or "to do" and I will explain why Strapi is a solution that can be ideal to get the benefits of using a ready-to-go solution without losing the flexibility of having custom software.

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by dessireugarte** [comment]
Hello @zeppaman  
Thank you for sharing this content request. Unfortunately, we will not proceed with it since we are currently looking for Strapi intermediate and advanced topics. Stay tuned for more content requests coming soon.
