### ISSUE TITLE
[SUBMIT] How to Build Custom GraphQL Subscriptions in Strapi v4

### ISSUE THREAD

**Issue by Tes-program** [strapi/community-content#1087]
**My resource**

Hello 👋 
### Introduction
I am writing to propose an article on building custom GraphQL subscriptions in Strapi v4. GraphQL subscriptions are a powerful feature that enables real-time updates in a GraphQL API. I will provide a comprehensive, step-by-step guide to building custom GraphQL subscriptions in Strapi v4, including setting up a GraphQL server, defining custom subscription types and fields, and implementing custom resolvers. I believe this article will be of interest to advanced users of Strapi v4 who are looking to take their skills to the next level by building custom GraphQL subscriptions.

### Outline
- Introduction to GraphQL subscriptions and how they are used to enable real-time updates in a GraphQL API
- Benefits of building custom GraphQL subscriptions in Strapi v4
- Setting up a GraphQL server in Strapi v4 and defining custom subscription types and fields
- Implementing custom resolvers for GraphQL subscriptions in Strapi v4
- Testing and debugging custom GraphQL subscriptions in Strapi v4
- Deploying and maintaining custom GraphQL subscriptions in a production environment
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@Tes-program  Currently we are not implementing subscriptions in Strapi so would love to get more detail information on your implementation. Do you have some examples that you can share?

**Comment by Tes-program** [comment]
Hello @PaulBratslavsky,
I found that I probably didn't make the intention of my proposed article clear in my outline and title and for the sake of clarity, I will be closing it and creating a new issue. My intention was to use Strapi and GraphQL Subscription with React to create a real-time voting website that gives feedback on the vote cast etc.
