### ISSUE TITLE
[REQUEST] Tutorial with Next js 9.4, Apollo client 3 and Strapi

### ISSUE THREAD

**Issue by tarekbozo** [strapi/community-content#109]
Tutorial  for  strapi next js 9.4 apollo client 3

**Comment by ghoshnirmalya** [comment]
I can pick this one up.

**Comment by malgamves** [comment]
Great! @ghoshnirmalya when do you think you'll have this out?

**Comment by ghoshnirmalya** [comment]
> Great! @ghoshnirmalya when do you think you'll have this out?

I can have it out by 19th August.

**Comment by malgamves** [comment]
Great! Can't wait to see it 👍
