### ISSUE TITLE
[SUBMIT] Article about how to add a custom provider to Strapi 4

### ISSUE THREAD

**Issue by ChristopheCVB** [strapi/community-content#1108]
**My resource**

In this article, I will cover the required steps to add a custom provider to Strapi 4

Outline
- Introduction
- How to
  - Patch-Package
  - Packages that need a patch
    - grant
      - config/oauth.json
      - config/profile.json
    - purest
      - config/providers.json
    - @strapi/plugin-users-permissions
      - server/bootstrap/grant-config.js
      - server/services/providers-registry.js
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ChristopheCVB** [comment]
@PaulBratslavsky I finally took the time to finish it ;)
I have a Dropbox Paper document, how should I proceed?

**Comment by ChristopheCVB** [comment]
https://www.dropbox.com/scl/fi/8fyoq2np96ul8dci2kmcj/How-to-add-a-custom-OAuth2-Provider-to-Strapi-4.paper?dl=0&rlkey=xayxg71oxgthwzbq34njskbqb

**Comment by PaulBratslavsky** [comment]
@ChristopheCVB thank you.  Will let you know when I review it or have any questions.

**Comment by ChristopheCVB** [comment]
As discussed earlier, I just added a link to a demo repo in the conclusion

**Comment by dessireugarte** [comment]
Hello @ChristopheCVB  👋 
Your article is [live](https://strapi.io/blog/how-to-add-a-custom-o-auth2-open-id-connect-provider-to-strapi-4)! 🎉

To ensure you don't miss any comments on your post, please register on our forum by clicking the discussion link at the bottom of your article. Please follow our [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice for your work. 

You should register yourself once as an "Individual Vendor," please fill out [this](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform) form. If you have any questions about the form, please do not hesitate to ask. Please note that in the W-8BEN form, section 5 is not mandatory, and sections 6a & 6b are only required if you have a tax number in your country.

You should submit your invoice to receive payment for your work [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) for $200, and soon you will receive your payment.

If you would like to promote your article, we have some [templates](https://github.com/1645b77a97a640d2a32047297b6bc3f0) that can help you get started! Please feel free to reach out to us if you have any further questions.

**Comment by dessireugarte** [comment]
Hello @ChristopheCVB! 
Just want to remind you to please send your invoice when it is ready so we can pay for the article :)

**Comment by dessireugarte** [comment]
Thank @ChristopheCVB! Did you submit your invoice on [this](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) form? We didn't receive it.

**Comment by ChristopheCVB** [comment]
I did yes :/

**Comment by ChristopheCVB** [comment]
@dessireugarte Did you receive it this time?

**Comment by PaulBratslavsky** [comment]
@ChristopheCVB our team and @dessireugarte  were having there onsite in Paris last week.  We will check you invoice submission this week.

**Comment by dessireugarte** [comment]
Hello @ChristopheCVB!
Yes, we have recieved it and submitted your invoice 2 weeks ago. You should get the payment tops by the end of next week.
