### ISSUE TITLE
Notice: No AI written content in community content

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/community-content#1112]
NOTICE: At this time Strapi DOES NOT allow for content written by ANY AI platform, while you can use these AIs for research, the content SHOULD NOT be written by the AI. We take an ABSOLUTELY ZERO TOLERANCE policy on this, any content submitted will be given one (1) warning and any further submissions that violate this rule will be banned from our writing programs.

**Comment by hanakhelifa** [comment]
This is super true! Thanks Derrick :)
 I'll add it to the upcoming new guidelines. Until then, as I am doing a bit of cleaning up on this repo, I'll close this issue.
