### ISSUE TITLE
[SUBMIT] Build a visual dashboard with Vuetify and Strapi

### ISSUE THREAD

**Issue by adisamicheal** [strapi/community-content#1114]
**Introduction**

Vuetify is a Material Design component framework for Vue.js. It aims to provide all the tools necessary to create beautiful content rich applications with predefined components.

Vuetify now has a latest version since the introduction on vue 3 and we will learn how to integrate strapi into our vuetify application.

Requirement to being able to understand the article:

- Basic knowledge of css
- Basic understanding of Strapi
- A code editor like [VSCode](https://code.visualstudio.com/)

**Outline**

1. Introduction
2. Setup
3. Strapi Installation
4. Building the Vuetify application
5. Customizing Strapi Backend Controller
6. Joining everything together.
7. Conclusion

**Comment by dessireugarte** [comment]
Hello @adisamicheal! Thank you for submitting this topic. Currently, we are only accepting intermediate and advanced topics, so we will close this issue for now. But stay tuned for new requests that we create in the future.
