### ISSUE TITLE
[SUBMIT]

### ISSUE THREAD

**Issue by OmaJuliet** [strapi/community-content#1117]
**Article Topic:** Implementing Authentication in React Applications Using Supabase.

**Outline:**

- What is Supabase?
- Difference between Supabase and Firebase
- Connecting to Supabase & Supabase Settings
- Creating your React app and Installing Packages
- Enabling Google Sign-In Functionality
- Conclusion & Recommendation

**Prerequisite:** Familiarity with React

**Tag:** Intermediate

**Introduction:** Supabase is a backend-as service that provides services such as Authentication, Storage, Real-Time, and database. It is a Firebase alternative. Firebase is used more by front-end developers as compared to Supabase. 
In this article, I would go in-depth on how to implement user authentication with Supabase using email addresses or google/social media sign-in, the similarities, and the differences between Firebase and Supabase. Supabase can be used in JavaScript or any JavaScript framework but in the article, I'll be making use of ReactJS.
At the end of this article, readers would be able to effectively implement Supabase in their React apps and this can subsequently be applied to other frameworks.

**Comment by dessireugarte** [comment]
Hello @OmaJuliet!
Thanks for submitting your outline. This article does not include Strapi so we will close this issue. 
But stay tuned for new requests that we create in the future.
