### ISSUE TITLE
[TOPIC]: Implementation of social auth providers like facebook, google, twitter and linkedin 

### ISSUE THREAD

**Issue by Shaggy1357** [strapi/community-content#1127]
**My Request**
Hi Team,

I recently started using strapi for fast backend depoyment. Its a ready made backend for me. Just the thing is that theres no proper instructions on how I can implement social auth providers with latest auth flow. Those mentioned above to be specific.

It would be great if we got a tutorial of these auth providers as the one's which are living on the internet are outdated and doesn't lead anywhere.

This is only thing which might holding developers back from using strapi because of outdated content. Also in the docs, it states that ngrok is needed for redirection which is not the case. Facebook has changed policies I think. 

So, please consider this as a request and help us with an updated tutorial on social auth providers implementation.

Thanks
 
**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by yhuakim** [comment]
🚀

**Comment by prosperyong** [comment]
Hello @Shaggy1357 @PaulBratslavsky @kilinkis ,

I'm interested in writing this piece.
Here is the outline:

I. Introduction
A. Overview of Strapi
B. Explanation of social authentication
C. Purpose of the tutorial

II. Prerequisites
A. Strapi installation
B. API keys/credentials for social providers

III. Setting up social authentication in Strapi
A. Installing plugins for social providers
1. Facebook
2. Google
3. Twitter
4. LinkedIn
B. Configuring plugins with API keys/credentials
1. Facebook
2. Google
3. Twitter
4. LinkedIn
C. Enabling social providers in Strapi's authentication settings

IV. Testing the implementation
A. Logging in/registering with a social account
B. Verifying successful authentication

V. Conclusion
A. Summary of the process
B. Additional resources and recommendations

I hope to hear from you soon😊.

**Comment by Shaggy1357** [comment]
Thanks Prosperyong for considering it. It would be very helpful if you do so. Also if possible can you also cover how to add custom providers in strapi v 4.5.6 for the same. Like Twitter uses oauth 1.0 under the hood and if want to apply oauth 2.0 need to add custom providers I think so. So please consider doing this too. 

Thanks again

**Comment by prosperyong** [comment]
Ok @Shaggy1357 . I'll get started right away😊

**Comment by PaulBratslavsky** [comment]
@Shaggy1357 we have a blog post coming on custom providers will share it with you as soon as it is published.

As for all the other provides.
![Screenshot 2023-02-27 at 12 41 28 PM](https://user-images.githubusercontent.com/6153188/221654693-595e2a5f-22e6-4e50-8bd6-0190a7505f63.png)

This should be clarified better in the docs rather than in a blog post.  I will get back to you when I see the direction we will take.

**Comment by y0ngdev** [comment]
> @Shaggy1357 we have a blog post coming on custom providers will share it with you as soon as it is published.
> 
> As for all the other provides. ![Screenshot 2023-02-27 at 12 41 28 PM](https://user-images.githubusercontent.com/6153188/221654693-595e2a5f-22e6-4e50-8bd6-0190a7505f63.png)
> 
> This should be clarified better in the docs rather than in a blog post. I will get back to you when I see the direction we will take.

I'll be on dock

**Comment by balogunkeji** [comment]
Hello @Shaggy1357 @PaulBratslavsky, I am interested in writing this piece.
here is the outline for the course
 Implementing social authentication providers like Facebook, Google, Twitter, and LinkedIn using Strapi:

I. Introduction
   A. Explanation of social authentication and its benefits
   B. Brief overview of Strapi as a backend framework
   C. Mention the goal of integrating social auth providers with Strapi

II. Setting Up Strapi for Social Authentication
   A. Installing Strapi and creating a new project
   B. Configuring database and authentication settings
   C. Enabling user registration and authentication in Strapi

III. Preparing Authentication Providers
   A. Registering your app on each social platform
   B. Obtaining API keys, secrets, and redirect URLs for each provider
   C. Configuring callback URLs and permissions in each platform's developer dashboard

IV. Implementing Social Authentication in Strapi
   A. **Facebook**
      1. Installing the `strapi-provider-auth-facebook` plugin
      2. Configuring the Facebook provider in Strapi admin panel
      3. Handling user creation and linking with Facebook account

   B. **Google**
      1. Installing the `strapi-provider-auth-google` plugin
      2. Configuring the Google provider in Strapi admin panel
      3. Managing user accounts and permissions for Google authentication

   C. **Twitter**
      1. Installing the `strapi-provider-auth-twitter` plugin
      2. Configuring the Twitter provider in Strapi admin panel
      3. Implementing OAuth 1.0a authentication flow with Strapi

   D. **LinkedIn**
      1. Installing the `strapi-provider-auth-linkedin` plugin
      2. Configuring the LinkedIn provider in Strapi admin panel
      3. Setting up OAuth 2.0 authentication for LinkedIn

V. Customizing User Data and Access
   A. Defining user models and attributes in Strapi
   B. Mapping user data received from social providers to Strapi's user model
   C. Managing access tokens and permissions for each social provider

VI. Handling User Experience and Redirection
   A. Designing UI for social authentication on frontend
   B. Implementing frontend logic to initiate social authentication flows
   C. Redirecting users to appropriate callback URLs after successful authentication

VII. Error Handling and Security
   A. Handling authentication errors and edge cases gracefully
   B. Ensuring secure token storage and transmission
   C. Implementing CORS and security headers for frontend communication

VIII. Testing and Debugging
   A. Testing social authentication flows in a development environment
   B. Debugging common issues related to authentication
   C. Using debugging tools and logs to troubleshoot problems

IX. Scalability and Maintenance
   A. Considering scalability and load balancing for larger user bases
   B. Keeping up with Strapi updates and plugin changes
   C. Monitoring user activity, permissions, and security regularly

X. Conclusion
   A. Recap of the successful integration of social auth with Strapi
   B. Emphasizing the enhanced user experience and security benefits
   C. Encouraging ongoing optimization and improvement of the authentication process
   
   I hope to hear from you soon

**Comment by PaulBratslavsky** [comment]
Our docs have been updated and currently you can follow this guide on how to implement all the available providers. https://docs.strapi.io/dev-docs/plugins/users-permissions#providers

@balogunkeji based on the outline, you have the step for installing providers, can you share the links to where I can find them.  

Since the improved documentation does a great job covering the topic I will close this issue for now.

**Comment by y0ngdev** [comment]
@PaulBratslavsky, It's one of the reasons I didn't work on it
