### ISSUE TITLE
[SUBMIT]How to build a Secure Web App with Strapi Policies and Next.js

### ISSUE THREAD

**Issue by Theodore-Kelechukwu-Onyejiaku** [strapi/community-content#1128]
# Introduction
In this article, we will explore how to build a secure web application using the power of Strapi policies and NextJs. With Strapi you can build and secure your web application using customizable policies including caching, rate limiting, data validation, authentication and authorization, ip whitelisting and much more. By the end of the article, you will have a solid understanding of how to build a secure web application with Strapi policies.

## Outline

- Introduction
- Setup
- Explanation of What NextJs/ReactJs and Strapi are
- Overview of policies and thier use cases
- Implementing Policies for Authentication and Authorization
- Implementing Ploicies for data validation using joi or express-validator
- Implementing Policy for rate limiting using express-cache-controller
- Implementing Policy for caching using express-cache-controller
- Implementing IP whitelisting Policy using ​​ip2location-nodejs
- Customizing Strapi Routes and Controllers
- Settinp a Next.js/React.js Frontend
- Building frontend application Layouts
- Building a Simple Location Based CRUD application
- Interaction with Strapi 
- Conclusion

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky @Mcastres @malgamves 
I sure hope you are doing great.

This would make great content about Strapi Policies. 
But I have gotten no response on this. 

Thanks.

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku I know it has been a while.  We have been working with a smaller team and have been playing catch up with the back log of post.  And this fell under the radar.  I agree, this will definitely be a good article.  Let us know if you are still interested in writing it?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky,

I hope you are doing great. Sure I am very much interested in writing this. Can I start immediately?

Cheers.

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku yes, thank you.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky ,

I trust everything is going well for you. Here is the link to the draft for this article. 

https://www.dropbox.com/scl/fi/2l4ap53mzvwoucj4fstcr/How-to-Build-a-Secure-Web-App-with-Strapi-Policies.paper?rlkey=sdwmacc5wfk0drxdh4pwobvjd&dl=0

Cheers!

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku thank you.  Very well written article.  Ready to publish.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky ,

Thanks! I am glad you find the article very well written. And happy it has been published.

Have a great day Paul!

**Comment by PaulBratslavsky** [comment]
@Theodore-Kelechukwu-Onyejiaku thanks again. I will close this issue to clear up the board but please submit your invoice if you hadn't.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
@PaulBratslavsky  I just went through the article. Can you please have the title of the article as :

"How to build a Secure Web App with Strapi Policies" 

Instead of "How to build a Secure Web App with Strapi Policies and Next.js"

Cheers.
