### ISSUE TITLE
[UPDATE OUTDATED CONTENT] 7 Top React UI Packages to use in 2020

### ISSUE THREAD

**Issue by Marktawa** [strapi/community-content#1129]
**Description**
This article about React UI Packages needs an update. I believe there have been significant changes in the React UI ecosystem with UI frameworks like Material UI, Ant Design, Semantic UI, Storybookjs, etc gaining more popularity. I would like to write an article profiling the top 7 React UI Packages in 2023.

**Link of the content**
[The 7 Top React UI Packages to use in 2020](https://strapi.io/blog/7-top-react-ui-packages-to-use-in-2020)

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by JericksonJ** [comment]
Hi @PaulBratslavsky ,

I would like to work on this article.

**Comment by Gunkev** [comment]
Hi @dessireugarte would like to work on this if it's still requested
