### ISSUE TITLE
[SUBMIT] Deploy Strapi on Heroku and configure file upload on Digital Ocean Spaces

### ISSUE THREAD

**Issue by hemanshum** [strapi/community-content#113]
**My resource**
In this tutorial, we will deploy Strapi on Heroku. We will also learn to upload images on Digital Ocean Space.

**Source**
https://youtu.be/lAPWwXcNa7Q

**My format**

- [ ] Article
- [x] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Awesome tutorial @hemanshum ! Thanks for this useful contribution
Are you present on our public Slack?

**Comment by hemanshum** [comment]
> Awesome tutorial @hemanshum ! Thanks for this useful contribution
> Are you present on our public Slack?

Yes, I am connected to Slack.

**Comment by Mcastres** [comment]
Awesome! I'll contact you during the week :)
