### ISSUE TITLE
Viaticos

### ISSUE THREAD

**Issue by gaibarra** [strapi/community-content#1130]
**My resource**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [x] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
Closing this issue to "no provided topic"
