### ISSUE TITLE
Building a Grocery Delivery App with Strapi and SwiftUI[SUBMIT]

### ISSUE THREAD

**Issue by i1d9** [strapi/community-content#1143]
Hello 👋 

In this tutorial we will be using Strapi to power a grocery delivery app using SwiftUI. The app will be divided into two modules, namely the administrator module and customer module. The administrator will only be accessed by users with admin privileges. Through Strapi, the administrator module will be responsible for user, grocery item and order management. The customer module will be responsible for making orders which are then confirmed by the administrator module. To understand data flow from strapi to SwiftUI view, we will use the MVVM architecture. We will also learn how to customise Strapi's user-permissions plugin, we will add a custom route to it. We will also extend a collection to process the order details before they are saved to the database. We will override the collections routes and controller to add the logic. 

Outline
- Introduction
- Why use SwiftUI with Strapi
- Setting up Strapi
- Extending Users Permission Plugin
- Extending a collection route and controller
- SwiftUI MVVM setup
- Building Swift Data Models
- SwiftUI Authentication flow
- Data Persistence using CoreData
- Building the View Models
- Conclusion

- [X] A Strapi Tutorial / Guide / How to article
- [X] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**Comment by dessireugarte** [comment]
Hello @i1d9 ! Thank you for submitting this topic. Currently, we are only accepting intermediate and advanced topics, and there are already similar topics as this one, so we will close this issue for now. But stay tuned for new requests that we create in the future.
