### ISSUE TITLE
Building a Blog with Strapi + Next and Spin [SUBMIT]

### ISSUE THREAD

**Issue by coderoflagos** [strapi/community-content#1144]
Hello 👋 

In this tutorial, we will be using Spin - a WebAssembly Framework for building microservice applications, and Strapi with Next to build a  blog that runs on Spin and built with Strapi and Next. In this tutorial, the readers will understand how to set up Spin, use the Spin Next  Template with Strapi.

Outline

- Introduction

- How to set up Spin

- Installing the Spin Next JS template

- Setting up Strapi Project

- Configuring Strapi to use Next JS

- Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack

**Comment by coderoflagos** [comment]
@PaulBratslavsky - How can I be assigned my topic?

**Comment by dessireugarte** [comment]
Hello @coderoflagos ! Thank you for submitting this topic. Currently, we are only accepting intermediate and advanced topics and there are already similar articles as this one on our blog, so we will close this issue for now. But stay tuned for new requests that we create in the future.
