### ISSUE TITLE
[SUBMIT]Powering a Job Board application using Strapi and SwiftUI

### ISSUE THREAD

**Issue by i1d9** [strapi/community-content#1148]
Hello 👋 

In this tutorial we will build a job board application iOS app using SwiftUI and Strapi. We will learn how to extend Strapi collections to add custom routes and HTTP request handlers(controllers). We will use our custom controller functions to handle file uploads associated with a specific record. We will add web sockets functionality to enable an applicant and a job advertiser to send each other messages in real time. We will use the user-permissions plugin to authenticate each socket connection. By the end of the tutorial a user will be able to sign up as an individual or company. A user with a company profile will be able to manage(create/view/update/delete) jobs, manage job applications and initiate conversations with job applicants. An individual user will be able to upload their CVs while applying for jobs. They will also be able manage their applications and profile. These functionalities will backed by a Strapi server instance.

Outline
- Introduction
- Pairing SwiftUI with Strapi
- Setting up Strapi
- Extending Users Permission Plugin
- Extending Collection routes and controllers
- Setting up socket connections 
- SwiftUI project setup
- Setting up Network Services
- Building Data Models 
- JWT Authentication and user persistence.
- Integrating network services to UI views
- Conclusion

- [X] A Strapi Tutorial / Guide / How to article
- [X] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**Comment by PaulBratslavsky** [comment]
@i1d9 you can start working on this article.  Thank you.

**Comment by i1d9** [comment]
Hello @PaulBratslavsky Here's the link to the [tutorial](https://www.dropbox.com/scl/fi/nx6d1sxfe6zu2clurjmac/Powering-a-Job-Board-application-using-Strapi-and-SwiftUI.paper?dl=0&rlkey=7xsit8sufpsz8c6m1e8j094fy)

**Comment by dessireugarte** [comment]
Thank you @i1d9! Could you please give us access to edit the document? 
Also, could you please use the [new design](https://www.figma.com/file/gI8PcsqInk3DAwfIxmcyPI/Writers-Blog-Banners?node-id=2105-102&t=nYyiHeZFFLjRL7VN-0) for the visuals?

**Comment by i1d9** [comment]
@dessireugarte Done

**Comment by dessireugarte** [comment]
Hello @i1d9 👋  
We are reviewing your article. @PaulBratslavsky will get back to you if there is any feedback regarding the content. 
We will publish the article the last week of June.

**Comment by PaulBratslavsky** [comment]
@i1d9 your article has been published and you may submit an invoice. https://strapi.io/blog/powering-a-job-board-application-using-strapi-and-swift-ui

Thank you 🙂
