### ISSUE TITLE
Create a news feed with Strapi, i18n plugin and React Native

### ISSUE THREAD

**Issue by dueka** [strapi/community-content#1149]
#Introduction
A news feed helps us keep our users updated on newly published content on our blog. In this project, we create a news feed application that makes use of the Strapi i18n plugin for internationalization. We build a react native application for displaying and interacting with our news feed. 

## Outline
Introduction
What is Strapi?
What is the i18n plugin?
What is React Native?
Prerequisites
Set up Strapi Backend 
Writing unit tests for our Strapi Backend
Set up React Native app
Fetch data from Strapi
Design the news article card
Persist store data
Search news with specific keywords
Conclusion

-->

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by dessireugarte** [comment]
Hello @dueka! Thank you for submitting this topic. We are only accepting intermediate and advanced topics, and this outline covers similar topics we already have covered on the Strapi blog. So we will close this issue for now, but stay tuned for new requests that we create in the future.
