### ISSUE TITLE
[SUBMIT] Introduction to Strapi - Headless CMS (Pt-br)

### ISSUE THREAD

**Issue by willianjusten** [strapi/community-content#115]
**My resource**
I wrote a post and recorded a 32min lenght video explaining what's Headless CMS, what's Strapi, advantages and how to use it.

My post/video in in Brazilian Portuguese, since almost nobody knows about Strapi in Brazil, so I thought it would be better to communicate in our native language. But I can translate it as well, if needed.

**My format**

- [x] Article (https://willianjusten.com.br/introducao-ao-strapi-headless-cms/)
- [x] Video (https://www.youtube.com/watch?v=L3LWzYOaWMQ)

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
That is great @willianjusten! 
Communicating in your native language is really awesome since we want everyone to understand what is Strapi why is Strapi and a lot of people don't understand English!

Thanks for this awesome resource! Are you present on our public slack?

**Comment by willianjusten** [comment]
Yeah, exactly, in Brazil the percentage of people that understands English is not that high and I don't want this to stop them from learning Strapi, which is an amazing CMS =)

I didn't know about this slack, is there any link somewhere?

**Comment by Mcastres** [comment]
Yes join us here https://slack.strapi.io.
Please ping me when you'll join it :)

**Comment by willianjusten** [comment]
Hey, I just joined there @Mcastres =)

**Comment by willianjusten** [comment]
Since it's there already, I'll close the issue =)
