### ISSUE TITLE
How to add user authentication and authorization to your Strapi API using Passport.js

### ISSUE THREAD

**Issue by AugustBemsen** [strapi/community-content#1152]
**My resource**
Hello 👋 
This tutorial will guide readers through the process of adding user authentication and authorization to a Strapi API using Passport.js. With user authentication and authorization, readers can restrict access to certain routes or data, add user roles and permissions, and keep user data secure. Passport.js is a popular authentication middleware for Node.js that is easy to use and highly configurable. By the end of this tutorial, readers will have a solid understanding of how to implement user authentication and authorization in your Strapi API using Passport.js.

OUTLINE
I. Introduction

II. Setting up a new Strapi project
Walk through the steps of installing Strapi and creating a new project with user authentication enabled
Necessary Strapi plugin installations
Discuss the default user authentication and authorization options provided by Strapi
Details on how to set up the user model and API endpoints

III. Setting Up Passport.js with Strapi
Benefits of using Passport.js for user authentication and authorization
Steps of installing and configuring Passport.js in a Strapi project
How Passport.js works with various authentication strategies (e.g. local, OAuth, JWT)

IV. Implementing Authentication and Authorization
Adding Passport.js authentication middleware to Strapi controllers
How to create login and registration API endpoints using Passport.js
How to authenticate users using a variety of strategies (e.g. email and password, social login)

V. Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@AugustBemsen currently passport is not one of our supported providers, were you going to create a custom provider?  Can you provide a little bit more context?

**Comment by AugustBemsen** [comment]
Hi @PaulBratslavsky, I was planning on creating a custom provider. The guide would cover the steps involved in configuring Passport.js with Strapi.
Explaining the need for a custom provider for Strapi
Step-by-step guide on how to create the custom Provider for Strapi
How to configure Strapi to use the custom Passport.js provider

**Comment by PaulBratslavsky** [comment]
> Step-by-step guide on how to create the custom Provider for Strapi

We currently use grant under the hood and I am a bit confused about how you would implement passport without doing massive amount of work.  Do you have a working example in code that you can share?
