### ISSUE TITLE
A guide to building a blog using Strapi, Gatsby.js and Graphql

### ISSUE THREAD

**Issue by AugustBemsen** [strapi/community-content#1153]
**My resource**

Hello 👋 
This guide will provide readers with a detailed and practical tutorial on how to use Strapi, Gatsby.js, and GraphQL to build a fully-functional blog. It will cover everything from setting up the Strapi backend to building the Gatsby front end and adding features like pagination and search. It also includes a section on styling the blog with CSS. By the end of the guide, readers will have a solid understanding of how to use these technologies together to build dynamic and engaging blogs.

OUTLINE
I. Introduction

II. Setting up the Strapi Backend
Installing Strapi and setting up a new project
Creating the content types for blog posts and categories
Defining fields for the content type
Adding data to the Strapi API
Creating the API routes for fetching blog posts and categories 

III. Setting the Gatsby Frontend
Installing Gatsby.js and setting up a new project
Creating the page templates for displaying blog posts and categories
Setting up GraphQL
Querying the Strapi API for data to display in the templates

IV.Customizing the Blog
Adding features such as pagination and search functionality

V. Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
Thank you so much for taking the time to submit your outline. We truly appreciate your interest in contributing to our community. 

However, at this time we are hoping to focus on more advanced topics that haven't been covered as much on our site. 

Specifically, we're looking for articles that delve into Strapi backend customizations and extensions, as we already have a lot of great content available on the basics of Strapi.

We encourage you to check out issue #1155 for some topic ideas that we think would be a great fit for our current needs. And please don't hesitate to submit future ideas as well. Thank you again for your time and effort!
