### ISSUE TITLE
  [ LEARN MORE ] We are always looking for writers to write posts about Strapi Dev Best Practices.

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/community-content#1155]
If you're interested in sharing your knowledge and expertise in Strapi development, the Strapi team is always looking for writers to contribute to their blog. They are specifically looking for posts that cover best practices for Strapi development, and they encourage potential writers to watch their best practices videos on their Discord channel to get ideas.

You can also participate during the best practices live sessions that happen every third Wednesday of every month at 1:00 PM CST.

You can find all prerecorded videos on Discord where you can ask questions. [https://discord.gg/strapi](Discord)
![2023-02-16_11-30-37](https://user-images.githubusercontent.com/6153188/219442902-9262f45c-b676-41a4-82de-ad5bcb849692.png)

You can also find the videos on YouTube:   [Best Practices Playlist](https://youtube.com/playlist?list=PL7Q0DQYATmvg5Ip7hpXypLf_G3-zEWhR6&si=EnSIkaIECMiOmarE)

To submit an article, simply choose a topic from one of the best practices videos and create an outline for your proposed post. The Strapi team will review your outline and provide feedback before you start writing.

It's important to note that the team is looking for content that is focused on Strapi development and customization, as opposed to basic implementation. This is what the Strapi community has been asking for, so they want to prioritize content that will be the most beneficial for our community.

Overall, if you're a Strapi developer with experience in best practices, this is a great opportunity to share your insights with a wider audience and help others improve their Strapi development skills.

**Comment by vcoisne** [comment]
Closing in favor of this one https://github.com/strapi/community-content/issues/1276
