### ISSUE TITLE
Nextjs vs Sveltekit: Which one Should you Used on Your Next Strapi Project  [SUBMIT]

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#1156]
**My resource**
<!--
Hello 👋 

SvelteKit is a framework for Svelte that creates web applications and static sites that are build-optimized and only load the bare minimum of code.

This article explain which site generator is suitable to use for your strapi project.  

Here is an example:
Outline
Introduction
What is Nextjs 
What is sveltekit
Comparing Nextjs with Sveltekit 
Initiating a Project
Which Should i Choose?
Choose Either or Both with Cloud Cannon
Conclusion

**Comment by lucky4242** [comment]
Hi @dessireugarte 
Here is the 
Outline:
introdution 
What is Nextjs
What is Sveltekit 
Sveltekit vs Nextjs Comparison
_i will be comparing the followng features_
-Initaiting a strapi Project 
-Routing
-Error Handling
-Api Routing
-Prerending pages as Static Site Generator 
-Styling 
-Deploment
Which Should i Pick?
Conclusion

I summited a draft last week (on the in progress), but it has yet to be addressed. Could you please look into it? 
Here is the link of the aticle.
https://www.dropbox.com/scl/fi/awgmxnmpcnxb3ur6j5lbf/Developing-a-Meme-Generator-with-React-and-Strapi-V4.paper?dl=0&rlkey=aqveoyolniwi3ad9d0jyblsub   

Thanks.

**Comment by dessireugarte** [comment]
Thank you @lucky4242! Here are some suggestions to add to the article: 

Outline:
- Introduction
- What is Next.js?
-- Key features of Next.js 
-- How Next.js integrates with Strapi? (Don't do a step-by-step, instead mention [this](https://strapi.io/integrations/nextjs-cms) page and [this](https://strapi.io/blog/build-a-blog-with-next-react-js-strapi) tutorial to get started with Next.js) 
-- Pros & cons of using Next.js with Strapi
- What is Sveltekit?
-- Key features of Sveltekit 
-- How to integrate it with Strapi (the same as Next.js, you can mention [this](https://strapi.io/blog/how-to-create-a-blog-with-svelte-kit-strapi) blog post and any other relevant source you consider important to integrate them both)
-- Pros and cons of using Sveltekit with Strapi
- What is Strapi?
-- Create a Strapi Project
- Sveltekit vs Nextjs Comparison (features comparison)
--Routing
--Error Handling
--Api Routing
--Prerending pages as Static Site Generator
--Styling
-- Deploment
- Which Should You Pick?
- -  Mention use cases for Next.js and Sveltekit with Strapi
- Conclusion
--Recap of the main points of the article
-- Add any additional resource or tutorial you consider relevant, including the Strapi documentation, to get started. 
-- Invite writers to our Discord community (example on [this](https://strapi.io/blog/on-premise-vs-cloud-solutions-which-is-the-best-for-your-business) article). 
You can get started with this article. 
Could you please send me the GH issue of the other article please?

**Comment by lucky4242** [comment]
Hi @dessireugarte 
ok. Working on it.

Here is the GH issue ( https://github.com/strapi/community-content/issues/706 ) for the other article.

Thanks.

**Comment by lucky4242** [comment]
Hi @PaulBratslavsky or @dessireugarte . 
Please what is the update on this article?
Thanks.

**Comment by vcoisne** [comment]
Hello @lucky4242 sorry about the delay. Some of us were OOO and focused on Strapi Cloud. We will resume the review shortly.

**Comment by lucky4242** [comment]
Hi @vcoisne, @PaulBratslavsky and @dessireugarte.
Please what is the update on this article?
Thanks.

**Comment by dessireugarte** [comment]
Hello @lucky4242! Hope you are doing well. We have scheduled this article for the third week of April. We will let you know if there is feedback before publishing it.

**Comment by dessireugarte** [comment]
Hello @lucky4242  👋 
Great job on this article. It is [live](https://strapi.io/blog/nextjs-vs-sveltekit-which-one-is-better-for-your-next-strapi-app)! 🎉

To receive payment for your work, you should submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform). 

If you would like to promote your article, we have some [templates](https://github.com/1645b77a97a640d2a32047297b6bc3f0) that can help you get started! Please feel free to reach out to us if you have any further questions.

**Comment by lucky4242** [comment]
Thanks @Dessire Ugarte Amaya ***@***.***>..
I've submitted an invoice for it.

**Comment by lucky4242** [comment]
Hi @Dessire Ugarte Amaya ***@***.***>.
How are doing from your end?
Any update on the payment this article. Thanks

**Comment by lucky4242** [comment]
Hi @Dessire Ugarte Amaya ***@***.***> .
Please what the update on the payment of this article?
