### ISSUE TITLE
Strapi vs Firebase-Comparison [SUBMIT]

### ISSUE THREAD

**Issue by danielonugha0** [strapi/community-content#1157]
My resource

**Comment by danielonugha0** [comment]
Here is the outline:
These days, APIs bring many benefits to the web development and app development industry. APIs allow developers to connect the back end of their application to the front end for a better user experience and better backend functionality. 

Strapi is an open-source headless content management system (CMS) that allows developers to build custom APIs and create, manage, and distribute their digital content. It provides an intuitive admin panel for creating and managing content types, which can be customized to fit a wide range of use cases.

Firebase is a mobile and web application development platform owned by Google. It provides developers with a range of tools and services to help them build high-quality apps quickly and easily. Firebase offers features such as a real-time database, cloud messaging, authentication, hosting, and more.

Goal
In this context, we shall elucidate more on which framework to use on your program between Strapi and firebase.

Table of Content

- Introduction
- What is Strapi?
- Features of Strapi
    - Customizable content types
    - User management
    - API-based
    - Open-source
    - Plugins and integrations
- Advantages and disadvantages of using Strapi
- What is Firebase?
- Features of Firebase
    - Real-time database
    - Cloud messaging
    - Authentication
    - Analytics
    - Hosting
- Advantages and disadvantages of using Firebase
- What are the differences between Strapi and Firebase?
- Firebase vs Strapi Comparison
- Conclusion

**Comment by danielonugha0** [comment]
@PaulBratslavsky @dessireugarte 
here is the link to the topic:
https://www.dropbox.com/scl/fi/iockczom2ampdzts0vcua/Strapi-vs-Firebase-Comparison.paper?dl=0&rlkey=m31m1ryl3mags52gtyk49kb6t

**Comment by PaulBratslavsky** [comment]
I like the article's idea, it will be great to see the comparison and talk about the pros and cons of both.  

We are about to release Strapi cloud which will make deployment of the app really easy.  As well as include all the other features that Strapi is known for.

- authentication
- content management for not developers
- with the cloud easy to deploy
- have the ability to point to your own database
- if talking about firebase I feel it's important to mention the pros and cons of relational vs not relational db like firebase.

I will provide you with more details about Strapi cloud as it becomes available and you can mention it in the article.  But for now, you can start on the draft.  You can share it with me when you are finished.

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky 
Ok. I'm working on it.

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky 
I have finished writing this piece, and this is the link to the Draft below:
https://www.dropbox.com/scl/fi/tz1ybgkehmnoc8k3jnfdl/Strapi-vs-Firebase-A-Comparison.paper?dl=0&rlkey=dapufrgybbr2ucxuw0d5p5i03

**Comment by danielonugha0** [comment]
Hi sir @PaulBratslavsky 
I haven't received any response from you sir .

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky @dessireugarte 
What's the status of my article

Best 
Daniel onugha

**Comment by dessireugarte** [comment]
Hello @danielonugha0!
We have scheduled your blog post for the last week of April. We will get back to you before if we have any feedback.

**Comment by danielonugha0** [comment]
Hello @PaulBratslavsky @dessireugarte 
I would love to know the status of my article, thanks.

Best regards
Daniel

**Comment by dessireugarte** [comment]
Hello @danielonugha0! We have scheduled to publish this post for the second week of May. We still need to review it. Just take into consideration the Cloud is not mentioned in Strapi description and it should be mentioned.

**Comment by danielonugha0** [comment]
Hi @dessireugarte I have made the necessary adjustment by adding Cloud to my article draft, thanks for the corrections.

Best regards 
Daniel

**Comment by danielonugha0** [comment]
Hello @PaulBratslavsky @dessireugarte

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky @dessireugarte 
Sorry for the inconvenience, the status of my article hasn't been made known to me yet.

Best
Daniel Onugha

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky @dessireugarte 
Happy new month!
A few days to our #Strapiconf 🎊👏
Please, I would love to know the status of my article draft as it has been  more than 3 months since I submitted it. Thanks.

Best
Daniel Onugha

**Comment by PaulBratslavsky** [comment]
Thank you for your effort and time in composing and submitting your article. Our team has carefully evaluated it and have found that it doesn't provide an in-depth view of Strapi's features to conduct a balanced comparison with Firebase. 

Additionally, it's missing references that were used in the writing process. Regrettably, we're unable to display your article on the Strapi website in its existing condition.
