### ISSUE TITLE
Creating Ecommerce mobile app with Strapi and React native[SUBMIT]

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#1159]
# Creating Ecommerce mobile app with  React native and Strapi

Hello 👋 @dessireugarte , I'll like to work on this topic. 

Outline

- Introduction
- Prerequisites 
- Goal of the tutorial 
- Strapi installation 
- Creating Strapi collections type 
- React native installation 
- Creating the ecommerce app
     Authentication screen 
     Home screen 
     Product preview screen 
     Check out screen 
- Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
Thank you so much for taking the time to submit your outline. 

However, at this time we are hoping to focus on more advanced topics that haven't been covered as much on our site.

Specifically, we're looking for articles that delve into Strapi backend customizations and extensions, as we already have a lot of great content available on the basics of Strapi.

We encourage you to check out issue https://github.com/strapi/community-content/issues/1155 for some topic ideas that we think would be a great fit for our current needs. And please don't hesitate to submit future ideas as well. Thank you again for your time and effort!
