### ISSUE TITLE
[SUBMIT] How to properly secure your Strapi API: a post on strapi best practice.

### ISSUE THREAD

**Issue by TechMakanaki** [strapi/community-content#1161]
**My resource**

Outline:

*Introduction
*Authentication and Authorization
*Data Security
*Infrastructure Security
*Monitoring and Logging
*Best Practices for Development and Deployment
*Conclusion

-->

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**Comment by PaulBratslavsky** [comment]
@TechMakanaki I like the idea, can you provide a little more context of what you will cover for each of the outlined bullet points?  Thank you.

**Comment by TechMakanaki** [comment]
@PaulBratslavsky, below is my reply;

 Certainly! Here is little more context on the outline on how to properly secure your Strapi API:

I. Introduction: 
   ** Importance of securing your Strapi API
   **Overview of the best practices.

II. Authentication and Authorization;
   **. Implementing authentication using JWT or OAuth.
 
III. Data Security; 
    ** Preventing SQL injection attacks by validating user input and sanitizing database queries 
    ** Securing passwords with hashing algorithms

IV. Infrastructure Security:
     **. Hosting your Strapi API on a secure server 
    **. Protecting against cross-site scripting (XSS) attacks by sanitizing user input.

V. Monitoring and Logging;
   **. Monitoring your Strapi API for security threats.

VI. Best Practices for Development and Deployment;
   **. Keeping your Strapi version updated to the latest stable version
    **Using environment variables to store sensitive information.
   **. Writing secure code and following coding best practices 
   ****. Testing your Strapi API for security vulnerabilities.

VII. Conclusion 
  ** Summary of best practices for securing your Strapi API.
   **Final thoughts on the importance of securing your Strapi API

**Comment by TechMakanaki** [comment]
@PaulBratslavsky, I'm awaiting your response on the above outline. Thanks

**Comment by PaulBratslavsky** [comment]
@TechMakanaki this seems too broad of a topic.  I would recommend picking a single topic like "V. Monitoring and Logging. Monitoring your Strapi API for security threats." and creating an in-depth article with implementation steps.

At the moment we are working on more in-depth articles that cover more advanced topics.

**Comment by TechMakanaki** [comment]
Okay, I can write on that topic too.

@PaulBratslavsky what do you say?

**Comment by PaulBratslavsky** [comment]
@TechMakanaki sorry for a delayed response we have many articles in the cue and working through the list.  Can you provide a modified outline for the topic that you would like to cover in depth in regard to securing your Strapi application.

**Comment by TechMakanaki** [comment]
@PaulBratslavsky here is the outline:

How to properly secure your Strapi API: a post on strapi best practice.
- introduction
- prerequisites
- what is strapi API?
- Creating collection type
- How to secure your Strapi API
1. enabling API permission
2. tracking API action using strapi audit log
3. securing API the frontend
- conclusion

Awaiting your response.

**Comment by TechMakanaki** [comment]
@PaulBratslavsky .
I'm waiting for your feedback.

**Comment by dessireugarte** [comment]
Hello @TechMakanaki!
We reviewed the outline with Paul and this is the one we suggest you write: 
**Headline**: Best Practices of API Security in Strapi
**Primary keyword**: API security
**External links to include in the body copy**: https://www.forbes.com/sites/forbestechcouncil/2023/03/09/preventing-data-breaches-in-2023-why-api-security-is-critical/?sh=645a13b5442b (maybe on the introduction or What is API security section)
**Content outline**: 
- What is API security & Importance of API security
- What is Strapi: For getting started and creating collection type, I suggest you direct people to the documentation. 
- Best practices Setting it up and Monitoring: enabling API permission, tracking API action using Strapi audit log, and securing API the front-end. 
- Best Practices for Development and Deployment: Tips for securely developing and deploying Strapi API.
- Conclusion: Please include one or two inviting people to other resources to expand their knowledge ([this](https://strapi.io/blog/how-to-build-a-hotel-management-app-using-strapi-and-nextjs) article conclusion is an example). 

Let me know what you think 😊

**Comment by TechMakanaki** [comment]
@dessireugarte good one, I will work on this outline. I love it. 

Kindly let he know when to proceed.

**Comment by dessireugarte** [comment]
Thank you @TechMakanaki! You can get started 👍

**Comment by TechMakanaki** [comment]
hello @dessireugarte 

here is the draft for the article kindly go through and let me know what to add and remove;

https://www.dropbox.com/scl/fi/tlxlqne8h2y7tkp1h7pcb/Best-Practices-of-API-Security-in-Strapi.paper?dl=0&rlkey=gz1189va41bv6nq4v1sswr3hr

thanks.

**Comment by TechMakanaki** [comment]
Hello, @PaulBratslavsky, @dessireugarte please kindly review my draft so I can know where to correct and what to add or remove.

Thank you.

**Comment by TechMakanaki** [comment]
Hello @dessireugarte, @PaulBratslavsky kindly review that draft.
Thank you.

**Comment by dessireugarte** [comment]
Hello @TechMakanaki 👋
We are reviewing your article. @PaulBratslavsky will get back to you if there is any feedback regarding the content.
We will publish the article the third week of July.

**Comment by TechMakanaki** [comment]
Hello. @PaulBratslavsky, @dessireugarte.
No change ha been made to the draft I submitted and I can't know where and what to work on in the article please let me know if there is an issue so I can solve it.

**Comment by dessireugarte** [comment]
Hello @TechMakanaki 👋  
We have scheduled the article to be published on July 31st. We will review it and get back to you before to add it to the admin panel when it is already reviewed.

**Comment by BraydenGirard** [comment]
@TechMakanaki The article has been reviewed technically, you can take a look at the comments I have left.

**Comment by dessireugarte** [comment]
Please let us know when the changes are done @TechMakanaki 👍

**Comment by TechMakanaki** [comment]
@BraydenGirard, @dessireugarte I have made all the necessary changes according to the comments.

**Comment by dessireugarte** [comment]
Hello @TechMakanaki!
I sent you an email. Could you please confirm you received it?

**Comment by TechMakanaki** [comment]
@dessireugarte I received your email successfully.

**Comment by TechMakanaki** [comment]
I am updating my bank account in the vendor form.

**Comment by TechMakanaki** [comment]
Good day @dessireugarte it seem this article has been published.can I request for a new topic proposal?

**Comment by dessireugarte** [comment]
Hello @TechMakanaki! @vcoisne will give a follow-up to your article.

**Comment by vcoisne** [comment]
Thanks @dessireugarte 

@TechMakanaki Your article update is [live](https://strapi.io/blog/best-practices-of-api-security-in-strapi)! 🎉
You can now publish the article on [Dev.to](http://dev.to/) and Hashnode.

To ensure you don't miss any comments on your post, please register on our forum by clicking the discussion link at the bottom of your article. Please follow our [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice for your work.

You should register once as an "Individual Vendor," please fill out [this](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform) form. If you have any questions about the form, please do not hesitate to ask. Please note that in the W-8BEN form, section 5 is not mandatory, and sections 6a & 6b are only required if you have a tax number in your country. If you already did this step, there is no need to do it again.

To receive payment for your work, you should submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform).

If you would like to promote your article, we have some [templates](https://github.com/1645b77a97a640d2a32047297b6bc3f0) that can help you get started! Please feel free to reach out if you have any further questions or any other article in mind.

**Comment by TechMakanaki** [comment]
Thank you

**Comment by TechMakanaki** [comment]
Invoice sent successfully.

**Comment by TechMakanaki** [comment]
@PaulBratslavsky @vcoisne @dessireugarte  please make some corrections on the publication. Thank you.

**Comment by PaulBratslavsky** [comment]
> please make some corrections on the publication.

@TechMakanaki are there new edits that you want us to make.

**Comment by TechMakanaki** [comment]
@PaulBratslavsky nope. The publication has some error.

**Comment by PaulBratslavsky** [comment]
@TechMakanaki can you screen capture and share so I know exactly what to fix.  Thank you.

**Comment by TechMakanaki** [comment]
@PaulBratslavsky please I have not received my payment yet. Kindly help me verify.

Thanks.

**Comment by PaulBratslavsky** [comment]
@TechMakanaki can you email Victor at victor.coisne@strapi.io to check on your invoice.  He is the one who handles that at the moment.

**Comment by vcoisne** [comment]
@PaulBratslavsky payment was confirmed via email. Closing.
