### ISSUE TITLE
[SUBMIT]

### ISSUE THREAD

**Issue by mohita-madaan** [strapi/community-content#1162]
I am an expert writer who writes for India's best job portal(Naukri.com).I have written 140+ articles so far that are published on Naukri.com website. And my 80+ articles are ranking on google. You can check my work samples here. [https://www.naukri.com/learning/articles/author/mohita-madaan/page/12/](https://www.naukri.com/learning/articles/author/mohita-madaan/page/9/)
Recently my paper got selected in Elsevier(proof attached).
I am interested in writing technical content, especially on the topics of machine learning and operating systems. 
I am interested in writing on topic- 
1. Machine Learning and data mining(with infographics)
In this article i will explain about machine learning and data mining vy real life examples with infographics.
2. Best practices of machine learning (with infographics)
In this i will explain best practices of machine learning with infographics.

Note: No plagiarism will be there and the content will be original and engaging.

3. Book chapter(12-13 pages) on the future of cyber security
I will write about the future of cyber security present and future demand with statistical information.

Note- I have written many articles on machine learning and posted it on Naukri.com.
I am attaching my resume for your reference.

I believe in writing quality content and have good technical knowledge as I am doing Ph.D. in data science.

I will wait to hear from you.
-
Regards
Mohita Narang
Email id-cecm.cse.mohita@gmail.com
![Capture](https://user-images.githubusercontent.com/92908539/221003678-6a60e28a-959b-4517-a3f4-0e662d7d8ef0.JPG)
Linkedin-https://www.li
[Resume-Mohita-Narang.pdf](https://github.com/strapi/community-content/files/10817180/Resume-Mohita-Narang.pdf)
![1](https://user-images.githubusercontent.com/92908539/221003781-86021f92-e434-44eb-b441-b7197d6e9909.jpeg)
![2](https://user-images.githubusercontent.com/92908539/221003785-1e64d904-ed55-4ae4-806c-618d82c2ca67.jpeg)
![3](https://user-images.githubusercontent.com/92908539/221003795-09dc2cf3-50b5-4310-9930-b0d1808f7958.jpeg)
![4](https://user-images.githubusercontent.com/92908539/221003797-e1dfb425-4d85-4269-a8c1-3651e9eb1aac.jpeg)
nkedin.com/in/mohita-narang-2a1b01229/
Ph no-9910709968
Infoedge (India) Limited-Naukri.com
Noida

**Comment by PaulBratslavsky** [comment]
@mohita-madaan thank you for your interest in writing for the community.  We are currently looking for developers to write on topics around our product Strapi and best practices around its customization, extension, and deployment.  Since those are the topics that our community is looking for. 

I will be closing this issue due to not having relative content for our community.  Thank you for your time.
