### ISSUE TITLE
Integrating Strapi CMS with Medusa: A step-by-step guide

### ISSUE THREAD

**Issue by DannyXGee** [strapi/community-content#1163]
**Integrating Strapi CMS with Medusa: A step-by-step guide**

This article will explains the steps to integrate Strapi with Medusa, including creating a Strapi project, modifying permissions, installing the Medusa plugin, and running the Medusa plugin within Strapi. It also highlights why Strapi is a good choice for integration and concludes by summarizing the key points and benefits of the integration process.

**Outline**
Introduction:
- Briefly introduce what Strapi and Medusa are.
- Explain why integrating Strapi with Medusa can be useful.

**Prerequisites**
- Provide a list of prerequisites required for the integration process.

**Why Strapi?**
- Explain why Strapi is a suitable choice for integration with Medusa.
- Highlight its key features and advantages.

**Creating Strapi Project**
- Explain how to create a new Strapi project.
- Provide step-by-step instructions on how to use the Strapi CLI to create a new project.
- Explain the different options available when creating a Strapi project.

**Modify Permissions**
- Explain how to modify Strapi's default permissions to work with Medusa.
- Provide step-by-step instructions on how to create and modify permissions in Strapi.

**Install Strapi Plugin**
- Explain how to install the Medusa plugin for Strapi.
- Provide step-by-step instructions on how to install and activate the Medusa plugin in Strapi.

**Run Medusa Plugin**
- Explain how to run the Medusa plugin within Strapi.
- Provide step-by-step instructions on how to start the Medusa plugin and how to configure it.

**Conclusion**

**My content is**

-  [x] A Strapi Tutorial / Guide / How to article

- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@DannyXGee are you referring  to this https://www.npmjs.com/package/medusa-plugin-strapi 

Also, can you give me more details on the prerequisite that are required?

**Comment by DannyXGee** [comment]
@PaulBratslavsky yes, I'll be giving a detailed guide on how to integrate it while also explaining some concepts along the integration process

The prerequisites for this are:
- node.js installed
- medusa cli
- redis installed as Strapi plugins, rely on Redis to improve performance and provide real-time features.

**Comment by DannyXGee** [comment]
@PaulBratslavsky I am still looking forward in hearing from you

**Comment by PaulBratslavsky** [comment]
@DannyXGee sounds good you can start working on this.

**Comment by DannyXGee** [comment]
@PaulBratslavsky 
I've finished writing this piece, and this is the link to the Draft
https://www.dropbox.com/scl/fi/7iyfmgywutbjy9hy4thek/Integrating-Strapi-CMS-with-Medusa_-A-step-by-step-guide.paper?dl=0&rlkey=uzsc0fu3renmhx80g32a1exc3

thanks.
i will be looking forward to your reply

**Comment by dessireugarte** [comment]
Hello @DannyXGee! We will review this article and get back to you in the following weeks.

**Comment by PaulBratslavsky** [comment]
@DannyXGee I am reviewing your article now.  I made some small notes.  Thank you for your patience.

**Comment by PaulBratslavsky** [comment]
@DannyXGee let me know when you get a chance to make the changes in your article.  Thank you.

**Comment by dessireugarte** [comment]
Hello @DannyXGee! Please take a look at Paul's comment. It would be good to look at how the integration of Medusa and Strapi would look like to start creating products and managing them.

**Comment by DannyXGee** [comment]
@hello PaulBratslavsky @dessireugarte I'm on it....I will get back ASAP

**Comment by DannyXGee** [comment]
Hello @PaulBratslavsky I'm done making changes to the article. Thank you.

**Comment by DannyXGee** [comment]
Hello @PaulBratslavsky I'm still waiting for your reply....I'm done with the changes on the article

**Comment by dessireugarte** [comment]
Hello @DannyXGee! We will publish your article next Tuesday. 
When the article is live in [Strapi's blog](https://strapi.io/blog), to ensure you don't miss any comments on your post, please register on our forum by clicking the discussion link at the bottom of your article. Please follow our [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice for your work. 

You should register yourself once as an "Individual Vendor," please fill out [this](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform) form. If you have any questions about the form, please do not hesitate to ask. Please note that in the W-8BEN form, section 5 is not mandatory, and sections 6a & 6b are only required if you have a tax number in your country.

After your article is live, you should submit your invoice to receive payment for your work [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform). 

If you want to promote your article, we have some [templates](https://github.com/1645b77a97a640d2a32047297b6bc3f0) that can help you get started! Please feel free to contact us if you have any further questions.

**Comment by DannyXGee** [comment]
Hi @dessireugarte 
I have made adjustment to this article 
Please check
Thank you.

**Comment by DannyXGee** [comment]
Hello @dessireugarte @PaulBratslavsky
I just want to ask when my article will be reviewed
I've made the correction to the article.
Please check it. Thanks

I will be looking forward to your reply
Best
Daniel

**Comment by PaulBratslavsky** [comment]
@DannyXGee reviewing the post today.  Thank you for your patience.

**Comment by DannyXGee** [comment]
@PaulBratslavsky Thank you for your quick response…I will be looking forward to your response on the article…

**Comment by PaulBratslavsky** [comment]
@DannyXGee Upon reviewing your article in collaboration with my manager, we noticed strong similarities to the Medusa documentation available [here](https://docs.medusajs.com/plugins/cms/strapi). We were hoping for additional insights, particularly regarding structuring content within the Strapi app.

Regrettably, due to the close resemblance to the Medusa documentation, we won't be able to accept this article. We appreciate your effort and hope to collaborate on future submissions.
