### ISSUE TITLE
A deep dive into Strapi Cloud: best pracitices

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#1169]
This article will encourage and even entice more people to use strapi cloud. It will also educate users on the importance of cloud computing, including both its security and best practices.

Outline
Introdution to Cloud
Importance of Cloud
What is Cloud Security
Cloud Comparison
_the comparison include_ 
-Public 
-Private
-Hybrid
principles of cloud service 
_i will list and explain six (6) principles_ 
Best practice for a successful cloud implementation
Conclusion

**Comment by PaulBratslavsky** [comment]
@lucky4242 thank you for the outline but at the moment we are not accepting new WFC submissions due to the outstanding backlog of topics that we have in our queue. I will be closing this submission for the time being.
