### ISSUE TITLE
GETTING STARTED WITH STRAPI CLOUD(ADMIN WALKTHROUGH) [SUBMIT]

### ISSUE THREAD

**Issue by danielonugha0** [strapi/community-content#1172]
My resource

**Comment by danielonugha0** [comment]
Here is the Outline below:
In computing, the term "cloud" usually refers to a network of remote servers that are hosted on the internet and used to store, manage, and process data. Cloud computing allows users to access computing resources and services on demand, without having to invest in or maintain their infrastructure.

[Strapi Cloud](https://strapi.io/cloud) is a hosting solution for websites and web applications built using the Strapi headless CMS (Content Management System). It is a cloud-based platform that offers an all-in-one solution for creating, deploying, and managing Strapi projects.
With Strapi Cloud, developers can focus on building their projects instead of worrying about server infrastructure and maintenance. It offers a scalable, secure, and reliable platform for hosting Strapi applications that can be accessed from anywhere in the world.

Goal
In this article, we will adapt ourselves to the Strapi Cloud Admin area.

Table of Content

- Introduction
- Logging in
- Dashboard view
- Profile section menu
- Setting menu
- Deploy menu
- Getting Help
- Documentation and community
- Conclusion

**Comment by danielonugha0** [comment]
@PaulBratslavsky @dessireugarte 
Here is the link to the topic:
https://www.dropbox.com/scl/fi/jk5gq61yz1ajqyrveur29/Getting-started-with-Strapi-cloudadmin-walkthrough..paper?dl=0&rlkey=b695opn9s0ydkf9bte9b1wsoq

**Comment by danielonugha0** [comment]
Hi @PaulBratslavsky @dessireugarte

**Comment by PaulBratslavsky** [comment]
@danielonugha0 thank you for the outline but at the moment we are not accepting new WFC submissions due to the outstanding backlog of topics that we have in our queue. I will be closing this submission for the time being.
