### ISSUE TITLE
[SUBMIT] CRUD AUTHENTICATION USING STRAPI CMS

### ISSUE THREAD

**Issue by DeeVineWill** [strapi/community-content#1173]
**CRUD AUTHENTICATION USING STRAPI CMS**
The actions that users can carry out on the data stored in a web application are controlled by CRUD authentication, a sort of access control method used in web development. The four fundamental operations that may be carried out on data are called CRUD, which stands for Create, Read, Update, and Delete.

In CRUD authentication, a user's identification and the degree of privileges that have been granted to them determine whether or not access to these activities is permitted. A user with administrator rights, for instance, would be able to carry out all four actions, whereas an ordinary user might only be able to read data—not modify it.

For a number of reasons, CRUD authentication is crucial in web development. Initially, it controls access to the online application so that the data is secure.

Strapi has a robust user management system that allows developers to define user roles and permissions, control access to specific content types, and enforce authentication and authorization for all API requests. This means that developers can easily implement CRUD authentication for their content and ensure that only authorized users can perform the desired CRUD operations on specific content types.

**OUTLINE**

Setting up Strapi CMS

- Installation of Strapi CMS
- Creating a Strapi project and configuring it

Creating a User Model

- Create a user model in Strapi
- Add fields to the user model and set up validation

CRUD policy

- What is the CRUD policy
- How CRUD works with Strapi
- Importance of CRUD in web development 
- How to generate a CRUD policy for our user model

CRUD authentication

- CRUD authentication using the Strapi admin panel

Conclusion

**Comment by PaulBratslavsky** [comment]
@DeeVineWill thank you for the outline but at the moment we are not accepting new WFC submissions due to the outstanding backlog of topics that we have in our queue. I will be closing this submission for the time being.
