### ISSUE TITLE
[SUBMIT] How to Build a Personal Podcast Platform Using Strapi CMS, React, and MUI

### ISSUE THREAD

**Issue by a7medayman6** [strapi/community-content#1177]
# How to Build a Personal Podcast Platform Using Strapi CMS, React, and MUI

The tutorial will be an intermediate project that walks through building a Podcast platform where the user can add his favorite podcasts and episodes and listens to them. The tutorial will include Creating Strapi Content types, and Relations, it will also include creating a complex React application with multiple components and features that will teach the reader about routers, APIs, components, hooks, states, search, and other React concepts. The tutorial will also include how to use MUI for styling and creating a nice looking application. 

Outline:

I. Introduction

  - What is Strapi?
  - What are we building?
  - Why MUI?

  
II. Setting up Strapi

  - Install Strapi and create a new project
  - Content structre (Podcasts, and Episodes)
  - Define the content types for Podcasts and Episodes
  - Set up permissions for creating and updating Podcasts and Episodes

III. Building the React Frontend

  - Create a new React project 
  - install necessary dependencies
  - Implement routing for the Podcasts page and Podcast page using react-router-dom
  - Implement a SearchBar component using MUI
  - Implement a PodcastList component to display all available podcasts
  - Implement a CreatePodcastModal component for creating new podcasts
  - Implement a PodcastCard component to display a single podcast in the PodcastList
  - Implement a PodcastDetails component to display all episodes for a selected podcast
  - Implement a SearchEpisodes component to allow users to search for episodes by name
  - Implement a SortEpisodes component to allow users to sort episodes by date
  - Implement an EpisodeCard component to display a single episode in the PodcastDetails
  - Implement a DownloadButton component to allow users to download episode mp3s
  - Implement an EpisodePlayer component to allow users to play and control episode audio

IV. Overview

  - Overview of the project and its features
  - Overview about what we learned
  - How to take the project further!

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by dessireugarte** [comment]
Hello @a7medayman6! Thank you for the suggestion. We are not receiving new content requests at the moment, so I will close this issue. But stay tuned to the new topics with which we will need support from writers in the following months.

**Comment by a7medayman6** [comment]
@dessireugarte @PaulBratslavsky
Hey, can this be reopened ?

**Comment by dessireugarte** [comment]
Hello @a7medayman6! 
Thanks for reaching out. Not for the moment. We will let you know in case we are interested in writing this topic.
