### ISSUE TITLE
[TOPIC] DigitalOcean one-click droplet to production

### ISSUE THREAD

**Issue by ihadabs** [strapi/community-content#118]
There is a video on YouTube for you doing this on the 27th of March, I believe, but the thing is there was a bug and you didn't complete the whole process. I believe this would be great for a lot of people since it was super easy to setup.

**Comment by Mcastres** [comment]
Hello @ihadabs !
Which video are you referring to?

**Comment by ihadabs** [comment]
Hey @Mcastres,
I'm referring to [this video](https://www.youtube.com/watch?v=Rw7FTdhbgI8)
Tbh, this is the best tutorial as they went through the setup and the configs step by step.
Unfortunately, they faced a problem and they didn't complete it till the production phase.
It would be really really great if there is a written or another video that explains all that was intended to be covered in the referred video!

Thx ❣️

**Comment by creotip** [comment]
Second on that here. I can't figure how to deploy to production after creating strapi one-click Digital Ocean.

**Comment by derrickmehaffy** [comment]
Hi all (I'm the one from that video, and I found my typo for it),

Before something like this progresses I wanted to get some initial feedback on what exactly you want to see:

- DNS setup? Cloudflare maybe?
- Domain Management?
- Dealing with SSL with stuff like Let's Encrypt via automated tools like certbot, acme.sh, ect?
- Source control with GitHub?
- Scaling, load balancing, distributed or centralized deployment?
- Automation?

We have to ensure we scope what we write to apply to most people and not go too in-depth (we want to encourage people to learn, not just blindly follow some copy/paste solutions)

**Comment by ihadabs** [comment]
Hey @derrickmehaffy,

Its been a long time since a posted the issue. I really like the way you explained everything in that video, thank you, really!

I guess, for me, what was missing is the way to use Strapi in production (like securing everything and that stuff) but I have figured it out (hopefully its the right way 😂 ).

I am a backend developer but sometimes people (like me 🚶‍♂️) want to use new tech to get something done rather than to learn it and understand it and I guess your tutorial kind of did the job.

I think Strapi is a great framework and people would really want to use it, especially those who are not experienced enough in the backend dev.

So my suggestion is if you are going to redo the tutorial that you do it and fully covered those things which are not very easy to do for those who have never touched a sever. The topics you suggested are very interesting!

Good luck!

**Comment by ChrisMulvanyGH** [comment]
This could really be a series of tutorials where you can take a Digital One-Click Droplet and show:

How to add a react frontend 
How to use nginx and modify this where somebody might want Strapi on a sub domain.
How to add Let's Encrypt SSL
How to link the frontend and Strapi backend
Add some best practices both in terms of DevOps and coding.
Source Control with git and possibly git actions 

Just take a beginners view of how it can be daunting to have to do all these different jobs.

**Comment by derrickmehaffy** [comment]
> how it can be daunting to have to do all these different jobs.

Yes DevOps can get very very deep.

**Comment by ChrisMulvanyGH** [comment]
Honestly I am not sure if it is DevOps in general or the tools you use.  This could also be another Article/Tutorial?

**Comment by ShadaW11** [comment]
Hey @derrickmehaffy what do you think can be done with this topic?

**Comment by derrickmehaffy** [comment]
> Hey @derrickmehaffy what do you think can be done with this topic?

@ShadaW11 we are planning to deprov the one-clicks since they are recommended for production and instead we will refactor the manual documentation later in the year with @pwizla

**Comment by ShadaW11** [comment]
@derrickmehaffy thank you for the update.
