### ISSUE TITLE
A Step-by-Step Guide on Implementing Push Notifications in React Native with Strapi APIs

### ISSUE THREAD

**Issue by josephotienoowino** [strapi/community-content#1180]
### Description of the project
This tutorial aims to provide a step-by-step guide on how to implement push notifications in a React Native app using Strapi APIs. It will cover the basics of push notifications, Strapi APIs, and Firebase Cloud Messaging (FCM), and how they can be used together to send and receive push notifications in a mobile app. The tutorial will include code examples and explanations for each step of the process, as well as testing and debugging tips. By the end of the tutorial, readers will have a solid understanding of how to implement push notifications in their React Native apps using Strapi APIs.
### Outline

1. Introduction
2. Setting Up the Project
3. Creating the API Endpoint
4. Handling Push Notifications in React Native
5. Testing Push Notifications
6. Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by josephotienoowino** [comment]
Any update @PaulBratslavsky @dessireugarte

**Comment by dessireugarte** [comment]
Hello @josephotienoowino!
We already have some articles covering this topic, so I will close this issue, but feel free to submit another topic that is more intermediate or advanced. Otherwise, stay tuned for other content requests the team requests in the future.
