### ISSUE TITLE
A deep dive into Strapi Cloud: best pracitices

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#1181]
This article will encourage and even entice more people to use strapi cloud. It will also educate users on the importance of strapi cloud computing, including its security and best practices implementation.  

Outline
Introduction to Cloud
Introduction to Strapi Cloud
what is strapi
Scaffolding a new Strapi project
Importance of Cloud
-_i will also state the importance of strapi Cloud_ 
What is Cloud Security
Cloud Comparison
the comparison include
-Public
-Private
-Hybrid
principles of Strapi Cloud Service
_i will list and explain six (6) principles_
Best practice for a successful cloud implementation with Strapi
Conclusion

I can also assist in raising awareness on social media and other platforms after the article has been published.

**Comment by lucky4242** [comment]
Hi @PaulBratslavsky and @dessireugarte.
Can I start working on this article?

**Comment by dessireugarte** [comment]
Hello @lucky4242!
Thanks for submitting this topic, but we will reject it for now.
