### ISSUE TITLE
[SUBMIT]

### ISSUE THREAD

**Issue by ijayhub** [strapi/community-content#1186]
**My resource**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by dessireugarte** [comment]
Hello @ijayhub!
What would be the content request?

**Comment by PaulBratslavsky** [comment]
Closing due to no topic provided.
