### ISSUE TITLE
Building a Multi-language Blog with Strapi and Next.js [SUBMIT]

### ISSUE THREAD

**Issue by icode247** [strapi/community-content#1189]
## Introduction

- Briefly explain Strapi and Gatsby
- Describe the purpose of the tutorial
- Setting up the development environment

## Install Strapi, Gatsby, and other required tools
- Initialize a new Gatsby project
- Creating the Strapi content model

## Design the content model for a multi-language blog
- Add fields for different languages
- Configuring the Strapi API

## Enable and configure the Strapi GraphQL plugin
- Secure the API with authentication
- Setting up Gatsby

## Install the required Gatsby plugins (e.g., gatsby-source-strapi)
- Configure Gatsby to use the Strapi API
- Building the Gatsby frontend

## Create components for the blog (e.g., blog list, blog post, language switcher)
- Fetch and display data from the Strapi API
- Implement language switching logic

## Conclusion

- Summarize the tutorial
- Suggest potential improvements or extensions to the project

**Comment by PaulBratslavsky** [comment]
@icode247 I now it has been a while.  We were working with a decreased team size, and I am finally catching up with our back log of articles.  

If you are still interested in writing this article, let us know, and would you be open to using Next JS instead.

**Comment by icode247** [comment]
Okay, sure I will use Next.js instead. I will send over the draft as soon as it's ready,

**Comment by PaulBratslavsky** [comment]
@icode247 thank you.

**Comment by icode247** [comment]
Hi @PaulBratslavsky,
This draft is ready, I have also invited mailto:dessire.ugarte-amaya@strapi.io to the Hackmd file.

**Comment by PaulBratslavsky** [comment]
@icode247 thank you, alos Dessi no longer is with Strapi.  Not sure if you send me an invite also, did not see it in my mail box.  paul.bratslavsky@strapi.io

**Comment by icode247** [comment]
Hello @PaulBratslavsky,
I have forwarded the draft to your email.

**Comment by icode247** [comment]
Hello @hanakhelifa 
Have you had time to review the draft? I have been looking forward to your feedback.

**Comment by hanakhelifa** [comment]
Hi @icode247–Could you share the draft here, please? :) I don't have access to it yet. Thank you

**Comment by icode247** [comment]
Hi @hanakhelifa, Here is the link: https://hackmd.io/@ovxvnE7IQLGjaZv2kEaAGw/H1_MfuJy6

**Comment by hanakhelifa** [comment]
Awesome, thank you. Review to be made before EoW :)

**Comment by icode247** [comment]
Hi @hana75 
Any update on this draft?

**Comment by vcoisne** [comment]
@icode247 please note that Hana is no longer with Strapi. Good news, your article has been published today https://strapi.io/blog/building-a-multi-language-blog-with-strapi-and-next-js Please feel free to submit your invoice now.  Do you have an account on dev.to and Medium?  it would be great for you to be listed as the author of the article there as well.

**Comment by icode247** [comment]
@vcoisne  I have sent an invoice. My username on Dev.to and Medium is codev206.

**Comment by vcoisne** [comment]
@icode247 thanks, payment should be processed shortly.
