### ISSUE TITLE
[SUBMIT] - STRAPI + Gatsby tutorial uptated to use typescript and gatsby-image

### ISSUE THREAD

**Issue by kilinkis** [strapi/community-content#119]
**My resource**
I'd like to submit my upated version of your article/tutorial about [creating a blog with STRAPI and Gatsby](https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi).
My addition is to have added typescript and gatsby-image.

here's the repo [https://github.com/kilinkis/gatsby-strapi-blog-typescript ](https://github.com/kilinkis/gatsby-strapi-blog-typescript ) 
and the directory with my updated front end is `gatsby-starter-typescript-plus`, which is the starter I used.

the code still needs some cleanup but that's basically it

**My format**

- [x] Article

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Hello @kilinkis ! That is awesome!
I'll take some time this week to review it ;)

**Comment by Mcastres** [comment]
Where this `localFile` come from exactly?
I don't have it in the Graphql explorer

```
strapiArticle: {
      image: {
        localFile: {
          url: string
          childImageSharp: {
            fixed: FixedObject
          }
        }
      }
      title: string
      content: string
    }
```

**Comment by kilinkis** [comment]
hi @Mcastres, thanks for taking time to review this.

I'm not sure but I think it's coming from gatsby-image.
Are you using the graphql explorer from gatsby or from strapi?
On the gatsby one I can see it no problem.

**Comment by kilinkis** [comment]
hello again @Mcastres,

okay, I tried to reproduce the problem, and could :)

so I think there is a version update that changed it
if you remove `localFile` and use it like this, it works again :) 

```
image {
        childImageSharp {
          fixed(width: 660) {
            ...GatsbyImageSharpFixed
          }
        }
      }
```

naturally, that changed the ts interface and how the images are invoked:

`<Img className="banner-bg" fixed={article.image.childImageSharp.fixed} />`

**Comment by Mcastres** [comment]
Can you make a PR to the official starter repo where you update the frontend folder by yours? 
However updating the code means updating the tutorial: https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi?redirectPage=1

Is that something you are interested in?

**Comment by kilinkis** [comment]
yeah, great, and thank you for accepting my contribution :) 

two things:
1. just to mention it: by updating the current tutorial with the typescript alternative, users who want the plain js version are left with no tutorial. Have you considered having a separate typescript version? I say this because typescript can be a little intimidating for less experienced users.
2. I'm fine with updating the existing one, but I was wondering if it's possible to have my name listed in the article as a contributor or co author maybe. Since I'd like to share this later on linkedin :) 

thank you again

**Comment by Mcastres** [comment]
1. You are right, I'll be happy to have a separate typescript version! Let's do that!
2. Of course you'll get full credits for it like we did for other contributors on our blog :)

**Comment by kilinkis** [comment]
okay, perfect then!

how should I proceed?
I might reuse part of the original tutorial, since it's very similar, specially regarding CSS and images

**Comment by Mcastres** [comment]
Absolutely, you can write the article using markdown then I'll review it and it will be ready to go.
Are you on the Strapi Slack? I'll can send you the markdown article

**Comment by malgamves** [comment]
Hey @kilinkis  just checking in the progress of this. How is this going?

**Comment by kilinkis** [comment]
> Hey @kilinkis  just checking in the progress of this. How is this going?

@malgamves it has been published now :) this can be closed

**Comment by malgamves** [comment]
Awesome! Thanks for the update and congratulations 🎊
