### ISSUE TITLE
Implementing Webhooks in Strapi for Real-time Notifications [SUBMIT]

### ISSUE THREAD

**Issue by Claradev32** [strapi/community-content#1190]
## Introduction
- Explain Strapi and webhooks
- Describe the purpose of the tutorial

## Setting up the development environment
- Install Strapi and other required tools
- Initialize a new Strapi project

## Creating the Strapi content model
- Design the content model for the example project
- Implement the content model in Strapi

## Setting up a webhook receiver
- Explain the role of a webhook receiver
- Create a simple webhook receiver using an external service (e.g., webhook.site)

## Implementing webhooks in Strapi
- Discuss different Strapi events that can trigger webhooks
- Write custom Strapi middleware to handle webhook events
- Configure the middleware to send requests to the webhook receiver

## Conclusion

**Comment by Claradev32** [comment]
Hi @dessireugarte, @PaulBratslavsky 
I want to write a tutorial on this topic.

**Comment by PaulBratslavsky** [comment]
@Claradev32 sorry for the late response.  We have been working with smaller team size and had many article submissions in the backlog.  

I am finally catching up.

We would still love to have you write this article if you are still open to it.  Thank you for your understanding and Patience.

**Comment by Claradev32** [comment]
Okey great, I'm still open to writing it. I will send the draft over as soon as possible. @PaulBratslavsky

**Comment by PaulBratslavsky** [comment]
@Claradev32 thank you.

**Comment by hanakhelifa** [comment]
Hi @Claradev32, do you have a draft to share with us so far?

**Comment by Claradev32** [comment]
Hi @hanakhelifa,
I will be rounding up today, need to do some proof reading before sending it over.

**Comment by Claradev32** [comment]
Hi @hanakhelifa,
The draft is ready: https://hackmd.io/@lbENA7rcQrWucUl6Z3Kidg/HJ3m7XGZ6

**Comment by Claradev32** [comment]
Hi @hanakhelifa 
I have submitted this draft for a long time now, but I have no feedback from you yet.

**Comment by hanakhelifa** [comment]
Hello @Claradev32–thanks for pinging me again here, and my apologies for the delay. 
The review of the article has been done. I left a suggestion for the meta-description, let me know if it works for you.
The article is a great resource, congrats! It looks all good to me to be published next week. 

As a final step, could you share with us a picture of you so we can properly credit you as an author in the publication? The picture will appear in our banner, as well as your author profile. You can do it here, or by email at hana.khelifa@strapi.io

**Comment by Claradev32** [comment]
I am not really a photo person (:, but I have an avatar I use for all my blog posts; can I share that?

**Comment by hanakhelifa** [comment]
Yes–an avatar will do fine in that case. Is the name you have on your GitHub account the one you'd like to sign the article with?

**Comment by Claradev32** [comment]
Yes- Clara Ekekenta.

**Comment by Claradev32** [comment]
Hello @hana75 
Any update on this draft?

**Comment by hana75** [comment]
Hi @Claradev32! Draft has been reviewed, and the article is great to be published for us. We'll published it in two weeks. I'll update you with the link here. Many thanks for your contribution!

**Comment by PaulBratslavsky** [comment]
@Claradev32 thank you for your article, you can find it live on https://strapi.io/blog/implementing-webhooks-in-strapi-for-real-time-notifications

**Comment by vcoisne** [comment]
Thanks @Claradev32 Please feel free to submit your invoice

**Comment by Claradev32** [comment]
@vcoisne Please, how do I submit the invoice? Any link for that?

**Comment by vcoisne** [comment]
@Claradev32 yes https://forms.gle/6bdcQRayAAUraGT78

**Comment by Claradev32** [comment]
@vcoisne  I don't this part of the form, because I can not find the invoice instructions here: https://strapi.io/write-for-the-community
<img width="706" alt="Screenshot 2024-03-07 at 21 09 41" src="https://github.com/strapi/community-content/assets/89540623/6d05096a-25ac-4860-b5ac-b6abc7e4ba02">

**Comment by vcoisne** [comment]
@Claradev32 I updated the form to remove that line. Simply upload a proof of account. Thanks!

**Comment by Claradev32** [comment]
@vcoisne 
I have sent the invoice. I sent my brothers account.

**Comment by vcoisne** [comment]
@Claradev32 I only got the proof of account but not the invoice. Can you make sure to include the invoice on page 1 and proof of account on page 2?

**Comment by Claradev32** [comment]
Hi @vcoisne 
I have sent a new invoice

**Comment by vcoisne** [comment]
@Claradev32 the invoice says 250 instead of 200. Can you please update and re-submit ?

**Comment by Claradev32** [comment]
@vcoisne, I have sent the updated invoice. Thank you

**Comment by vcoisne** [comment]
@Claradev32 thanks, payment has been requested and should be processed soon.

**Comment by Claradev32** [comment]
Hi @vcoisne 

Are you able to process the payment?

**Comment by Claradev32** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku 
Any update for me on the payment for this?

**Comment by vcoisne** [comment]
@Claradev32 I have checked with our finance team. Stay tuned.
