### ISSUE TITLE
Combining the Github API With Strapi to Create a Changelog Content Model

### ISSUE THREAD

**Issue by userJeremiah** [strapi/community-content#1192]
The article will be a step-by-step tutorial on creating a Changelog content model in Strapi using data from the GitHub API. The tutorial will walk readers through setting up a new Strapi project, authenticating with the GitHub API, creating a Changelog content type in Strapi with fields for data from the GitHub API, and importing data from the API into the content type.

**Topic Outline;**
**Introduction**
- A brief explanation of what a Changelog is and why it's important for developers and project managers
- An outline of the tutorial's objective: to create a Changelog content model in Strapi using data from the GitHub API

**Prerequisites**
- List the prerequisites for following the tutorial (e.g. basic knowledge of JavaScript, GitHub account, etc.)
- Provide links to any resources readers may need to complete the tutorial successfully

**Setting up Strapi**
- A quick walkthrough on how to create a new Strapi project

**Setting up the GitHub API**
- Walk readers through the process of authenticating with the GitHub API and retrieving data
- Provide code snippets and screenshots to help readers follow along

**Creating a Changelog content type in Strapi**
- Explain what a content type is in Strapi
- Walk readers through the process of creating a Changelog content type with fields for data from the GitHub API (e.g. release date, description, author)
- Show how to import data from the GitHub API into the new Changelog content type
- Provide code snippets and screenshots to help readers follow along

**Displaying the Changelog on a website**
- Explain how to use Strapi's API to retrieve data from the Changelog content type
- Provide an example of how to display the Changelog on a website using a frontend framework (e.g. React)

**Conclusion**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by userJeremiah** [comment]
Hi @dessireugarte and @PaulBratslavsky any update on the article?

**Comment by PaulBratslavsky** [comment]
@userJeremiah I like your idea.   I am sorry for the late response.  We have been working with smaller team size and had many article submissions in the backlog.  

I am finally catching up.

We would still love to have you write this article if you are still open to it.  Thank you for your understanding and patience.

**Comment by userJeremiah** [comment]
Alright Paul, I will start work on it as soon as possible

**Comment by PaulBratslavsky** [comment]
@userJeremiah Thank you.

**Comment by hana75** [comment]
Hello @userJeremiah,
The draft you proposed have been reviewed. I made a few corrections directly into the document to add some details, and fix the copy. A few comments have been added–could you take care of them? As soon as it's done, and the images have been added, please ping me and we'll publish your article shortly after.
Do you have an account into Strapi to upload your article there?

**Comment by userJeremiah** [comment]
Hello,
Yes i have an account with strapi, please chaeck again i have added the
needful

**Comment by userJeremiah** [comment]
Hello @hana75
Any update on this article?

**Comment by hana75** [comment]
Hello @userJeremiah–I don't see your article as a Draft's on Strapi's blog yet. So it looks like you don't have an account yet. Could you provide me with your name, and your email, so we can correct that?

**Comment by userJeremiah** [comment]
hello @hana75 
here you go: Name- Isijola Jeremiah
                     Email- isijolajerry@gmail.com

**Comment by userJeremiah** [comment]
Hello @hana75 
I would love to know if the article is good to go, and if there are any changes you need me to work on please let me know on time.

**Comment by vcoisne** [comment]
@userJeremiah apologies for the delay. We'll take one last look at the article before publishing it ideally next week. Thank you for your understanding.

**Comment by userJeremiah** [comment]
No problem, thank you for the update.

**Comment by PaulBratslavsky** [comment]
@userJeremiah hey just to follow up.  I  could not find a link to the final code so I can test it out.  Can you share the repo with me when you get a chance. Thank you.

**Comment by userJeremiah** [comment]
hello @PaulBratslavsky @vcoisne @hana75 here is the link to the project repo https://github.com/userJeremiah/my-changelog-project-

**Comment by PaulBratslavsky** [comment]
Thank you.  I will take a look and get back to you as soon as I test it.

**Comment by PaulBratslavsky** [comment]
@userJeremiah upon further review and testing your code, we can not accept this article do to not functional code.

**Comment by vcoisne** [comment]
@userJeremiah closing this issue per @PaulBratslavsky comment.
