### ISSUE TITLE
[SUBMIT] How to deploy Strapi to a Digital Ocean droplet using Bitbucket pipelines

### ISSUE THREAD

**Issue by i1d9** [strapi/community-content#1195]
Hello 👋 

In this tutorial we will be deploying a Strapi instance using bitbucket's CI/CD pipelines. We will create a digital ocean droplet, setup nodejs, Postgres and a reverse proxy using Nginx. We will learn how to use SSH keys to authenticate to different machines. We will write a bash script that will pull our source code, build for production and start the strapi instance. Our pipeline will be trigger when our repository's master branch is updated.  Finally we will setup a firewall and a reverse proxy on the production server to map Strapi's default port to http and https ports.

Outline
- Introduction
- CI/CD Basics
- Setting up Strapi
    - Collections
    - Authorisation Rules
- Digital Ocean Droplet Setup
    - Configurations
    - Connecting to the droplet
    - Node Installation
    - Postgres DBMS Installation
    - SSH Authentication Setup
    - Firewall Rules Setup
    - Nginx Reverse Proxy
- Pipeline Setup
- Testing the Production Build
- Conclusion.

- [X] A Strapi Tutorial / Guide / How to article
- [X] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**Comment by PaulBratslavsky** [comment]
@i1d9  sorry for the late response.  We have been working with smaller team size and had many article submissions in the backlog.  

I am finally catching up.

We would still love to have you write this article if you are still open to it.  Thank you for your understanding and Patience.

**Comment by i1d9** [comment]
Hello @PaulBratslavsky I'm still interested in writing this. I'll share my draft as soon as possible

**Comment by PaulBratslavsky** [comment]
@i1d9 ok thank you will mark it as in progress.

**Comment by i1d9** [comment]
@PaulBratslavsky @dessireugarte  Here's the [article](https://www.dropbox.com/scl/fi/n1nwgfi2idydo6v7ubb40/How-to-deploy-Strapi-to-a-Digital-Ocean-droplet-using-Bitbucket-pipelines.paper?rlkey=ioho33tjx6rqe2zksfbbzkeqv&dl=0), Let me know if I need to make any changes.

**Comment by hanakhelifa** [comment]
Thanks @i1d9, we'll review the article as soon as we can and get back to you

**Comment by hanakhelifa** [comment]
Hi @i1d9,

I left a few comments on the dropbox link. Could you check them out when you have a chance? We'll schedule a date right after the modification have been made.

**Comment by hanakhelifa** [comment]
Hello @i1d9,
I saw you treated the comments–thanks. We can go ahead and publish it tomorrow. You already have your Strapi account to add your article there, but please keep it in Draft until I made a final review.
