### ISSUE TITLE
[SUBMIT] Integrating Strapi with MkDocs for Building Fast Static Sites

### ISSUE THREAD

**Issue by kwennB** [strapi/community-content#1196]
**Integrating Strapi with MkDocs for Building Fast Static Sites**

Integrating Strapi with MkDocs will create a fast and scalable static site that is easy to manage and update. Strapi provides a powerful content management system, while MkDocs allows you to generate a beautiful and functional site from that content. This article will show how to achieve these results. 

I. Introduction

- A brief overview of Strapi and MkDocs
- Advantages of using Strapi and MkDocs together
- An overview of what the article will cover

II. Getting Started

- Prerequisites for integrating Strapi with MkDocs
- Creating a new Strapi project
- Creating a new MkDocs project

III. Connecting Strapi with MkDocs

- Installing necessary dependencies
- Configuring Strapi to allow CORS requests
- Creating Markdown files in MkDocs to fetch data from Strapi
- Implementing MkDocs to display the data

IV. Building a Fast Static Site with Strapi and MkDocs

- Optimizing images with MkDocs plugins
- Minimizing bundle size with MkDocs' theme configuration
- Leveraging Strapi's caching capabilities
- Deploying the site to production

V. Conclusion

- Recap of the benefits of using Strapi and MkDocs together
- Final thoughts and next steps

-->

**My content is**

- [ *] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

I look forward to hearing your thoughts and feedback!

**Comment by PaulBratslavsky** [comment]
@kwennB sorry for the late response.  We have been working with smaller team size and had many article submissions in the backlog.  

I am finally catching up.

We would still love to have you write this article if you are still open to it.  Thank you for your understanding and patience.

**Comment by kwennB** [comment]
> 
> 
> @kwennB sorry for the late response.  We have been working with smaller team size and had many article submissions in the backlog.  
> 
> 
> 
> I am finally catching up.
> 
> 
> 
> We would still love to have you write this article if you are still open to it.  Thank you for your understanding and patience.


Thank you @PaulBratslavsky I will get started.

**Comment by PaulBratslavsky** [comment]
Thank you @kwennB

**Comment by hanakhelifa** [comment]
Hi @kwennB, do you have a draft to share with us yet?

**Comment by kwennB** [comment]
Hello @hanakhelifa, @PaulBratslavsky 

The draft would have been completed but it is not due to issues currently faced with the plugin.  Kindly find the details in this Google Docs file. 

https://docs.google.com/document/d/1Cns5W5GiGGhzhcQFTa80vZmhyt23MarlGGMyuIhSKak/edit?usp=sharing

**Comment by hana75** [comment]
@kwennB I'll review the article this week, thank you for your submission

**Comment by vcoisne** [comment]
@kwennB do you have plans to add more details to the article ? What about submitting the plugin on the Strapi Marketplace ?

**Comment by vcoisne** [comment]
Hi @kwennB I did not hear from you, so closing the issue for now.
