### ISSUE TITLE
Deploying your first Strapi app on Strapi cloud [SUBMIT]

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#1197]
# Deploying your first Strapi app on Strapi cloud
Here is my outline 
- Introduction 
- Prerequisites
- what is Strapi cloud 
- strapi cloud VS self host
- creating Strapi app locally 
- deploying your app to Strapi cloud 
- setting up Github repository
- pushing your app to Github 
- running the app on Strapi cloud 
- Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@popoolatopzy we already have the docs and a yt video that describes this process so will be closing this issue.
