### ISSUE TITLE
[UPDATE] Update version of the Next/Strapi blog

### ISSUE THREAD

**Issue by ryanbelke** [strapi/community-content#120]
**My resource**
The updated version of the Next/Strapi blog

**My format**

- [X] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hey @ryanbelke is there any progress on this?

**Comment by Mcastres** [comment]
Ryan already finished the blog post @malgamves :) 
I'm closing this
