### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Set up Amazon S3 Upload Provider Plugin for your Strapi App

### ISSUE THREAD

**Issue by Marktawa** [strapi/community-content#1201]
**Description**

Update to the tutorial [How to Set up Amazon S3 Upload Provider Plugin for your Strapi App](https://strapi.io/blog/how-to-set-up-amazon-s3-upload-provider-plugin-for-our-strapi-app):
- Updated middleware.js for plugin configuration
- Updated with CORS instructions for image thumbnails to appear in Strapi Dashboard
- Updated screenshots
- Fixed grammar and code syntax

**Link of the content**

[How to Set up Amazon S3 Upload Provider Plugin for your Strapi App](https://strapi.io/blog/how-to-set-up-amazon-s3-upload-provider-plugin-for-our-strapi-app)

**What do you all think?**
👍 Nice!
❤️ I love it!

**Comment by Marktawa** [comment]
Hi 👋  @dessireugarte 

Here's the link to the draft:
[Dropbox Draft Link](https://www.dropbox.com/scl/fi/nvdeztrr4wmtdo0eci3gl/UPDATE-How-to-setup-Amazon-S3-Upload-Provider-Plugin-for-your-Strapi-App.paper?dl=0&rlkey=l8j2hz3lz50olahgr18isz394)

**Comment by dessireugarte** [comment]
Thank you for giving it a follow-up @Marktawa 👍 
I added it to the pipeline review, we will publish this article around the first two weeks of June. We will review it and let you know if we need to make some changes before going live.

**Comment by Eventyret** [comment]
Just to add btw Under Prerequisites:

Docker repo is wrong as this is v3 and not used. Docker is supported but you have to make your own dockerfile or community tools built to make them for you.

Under Mac it says Mojave but not arm, using m2 Mac myself and it works ☺️ so this info is also incorrect.

It also suggests to be min node version 14 it would be 16 if this was v4.

**Comment by PaulBratslavsky** [comment]
@Eventyret for the feedback.

**Comment by Marktawa** [comment]
Thanks for the feedback @Eventyret

**Comment by Marktawa** [comment]
Hi @dessireugarte 

Yes, I have updated the article. Please review.

**Comment by dessireugarte** [comment]
Hello @Marktawa! 👋 
The article is live! We published it on the how-to-set-up-amazon-s3-upload-provider-plugin-for-our-strapi-app and [Medium](https://medium.com/strapi/how-to-set-up-amazon-s3-upload-provider-plugin-for-your-strapi-app-ececd9caa934). You can now go ahead an upload it on Dev.to & Hashnode as well ✨

Feel free to submit your invoice. Also if you would like to promote your article, we have some [templates](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) that can help you get started! Please feel free to reach out to us if you have any further questions.
