### ISSUE TITLE
JSON-Server for Web Developers: Making HTTP Requests in React

### ISSUE THREAD

**Issue by Cejay101** [strapi/community-content#1203]
Hi Team, 
I'd like to write on the topic "JSON-Server for Web Developers: Making HTTP Requests in React" In this article, I'll talk about how to set up JSON Server and the server file, create basic form components in React and use them to perform the four main HTTP request which is to GET,POST, PUT and DELETE data. Also I Will display the data on the  browser so it's more like a practical guide on making HTTP request.

Table of Content
Introduction
JSON Server
Setting up JSON-Server
Making HTTP Requests to the JSON-server
Overview of different types of HTTP requests (GET, POST, PUT, DELETE)
Introduction to the useFetch custom hook for making HTTP requests in React
Implementing POST, PUT, and DELETE request functions using useFetch
Conclusion

I would love to know if there is a better way I can write this article to meet your requirements. Please let me know.

Best Regards
Clinton.

**Comment by PaulBratslavsky** [comment]
@ sorry for the late response.  We have been working with smaller team size and had many article submissions in the backlog.  

I am finally catching up, thank you for your understanding and patience.

Looking at your topic it seems that you would be using JSON server and not Strapi.  We are currently looking for articles that dive into Strapi use cases and backend customizations.  

You can browse article suggestions under issues and see if there is a topic you would like to write about. 

For now I will be closing this issue.  You can always open another one, once you come up with a new topic.
