### ISSUE TITLE
3 Common mistakes made using useEffect in Reactjs

### ISSUE THREAD

**Issue by favour-onyeke** [strapi/community-content#1204]
useEffect is one of the most popular built-in hooks of react that enables developers to handle State outside a functional component. It is used for fetching API data, manipulating the DOM, or subscribing to a web socket. 
Although some might not necessarily give an error, it is, therefore, necessary to know best practices. 

Prerequisite: 
Knowledge of javascript, and React(just its basic knowledge).
Outline:

1. Detailed Introduction
2. Understanding useEffect.
3. Common Mistakes

- Not including dependencies in the dependency array.
- Not using the cleanup function
- use async in the useEffect callback.

Here are some of my articles https://medium.com/@favouronyeke2002

**Comment by dessireugarte** [comment]
Hello @favour-onyeke, 
Thank you for sharing this content request. Unfortunately, we will not proceed with it since we are currently looking for Strapi intermediate and advanced topics.
