### ISSUE TITLE
Building a custom plugins for Strapi: step- by- step guild 

### ISSUE THREAD

**Issue by Sarahaburu** [strapi/community-content#1206]
My title is Building a custom plugins for Strapi: step- by- step guild 

**My content is**
Is a step by step guild of building a custom plugins for Strapi 
- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by dessireugarte** [comment]
Hello @Sarahaburu!
Please refer to the [blog](https://strapi.io/blog), as some articles already cover this topic. 
I will close the issue.
