### ISSUE TITLE
[SUBMIT] How to use schema stitching to merge multiple GraphQL subgraphs with Strapi and Next.js

### ISSUE THREAD

**Issue by KatanaHaley** [strapi/community-content#1207]
### Content Brief: 
- Target audience: Intermediate -> Advanced
- Keywords: Schema stitching, GraphQL, Strapi, JAMStack

## Content objective:

# The purpose of this article is to show how your application can aggregate and display data from various sources as a cohesive API.

## Content outline:

I. The benefits of merging multiple GraphQL subgraphs with Strapi
II. Prerequisites
III. Installing and configuring the Strapi Project
IV. Creating Multiple GraphQL Subgraphs
V. Schema Stitching and Combining Subgraphs with Strapi
VI. How to Resolve Field Conflicts and Test
VII. Best Practices
VIII. Conclusion

**My content is**

- [ ✓] A Strapi Tutorial / Guide / How to article

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by hanakhelifa** [comment]
Hello @KatanaHaley, 
Thanks for your contribution here! I'm glad to see great ideas in this board :)
As we are revamping the WFC program, we are stopping incoming requests to give us room for the new processes. 
I see this issue has been inactive for month, so I'll close it. I'll be sure to reach out to present to you the new program.
You can reach out to me on Discord if you have any question, my username is the same, and you can ping me on the #write-for-the-community channel
