### ISSUE TITLE
How to Build a Mobile Food Blog with Flutter and Strapi

### ISSUE THREAD

**Issue by Gunkev** [strapi/community-content#1208]
**My resource**

Hello 👋 

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax and you have read the [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md). 

Please describe what your article will be about in a few sentences and include a content brief of the article: 
This article describes how to create a mobile food blog with Flutter and Strapi. Google built Flutter, an open-source mobile application development platform, whereas Strapi is a headless content management system (CMS) that allows developers to simply create and manage content. The post goes over the fundamentals of both Flutter and Strapi, including installing the necessary dependencies. It also looks at how to construct a Strapi API and connect it to the Flutter app via HTTP requests. The post covers the fundamentals of both Flutter and Strapi, including installing the required dependencies. It also looks at how to construct a Strapi API and connect it to the Flutter app via HTTP queries.

### Content Brief: 
- Target audience: Intermediate developers
- Keywords: build a blog with flutter and strapi, integrate strapi with flutter, mobile flutter blog, strapi blog with flutter
- Industries this content will target: Food Industry
- Source: Strapi reddit
- Content objective: Build a functional mobile blog with Strapi Flutter
- Content outline:

1. Introduction
2. Overview of Flutter and Strapi
3. Benefit of using Strapi and Flutter for Mobile food blog development
4. Installing and Setting up Strapi
5. Creating content types for recipes
6. Creating API endpoint
7. Creating Flutter PROJECT
8. Setting up and connecting the API
9. Creating Models
10. Building UI
11. Quering Recipes
12. Quering and Displaying Categories
13. Adding Search and Filter features
14. Adding share and save recipe feature
15. Preparing the APP for Deployment
16. Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@Gunkev We currently have these two articles on Flutter that are outdated.  
https://strapi.io/blog/how-to-build-a-simple-crud-application-using-flutter-and-strapi
https://strapi.io/blog/build-a-to-do-app-with-strapi-graph-ql-plugin-and-flutter

At the moment we are prioritizing updates on outdated content first.

Let me know if you would be interested in updating any of the articles. Thank you.

**Comment by Gunkev** [comment]
All right @PaulBratslavsky I would like to work on the second article: 
https://strapi.io/blog/build-a-to-do-app-with-strapi-graph-ql-plugin-and-flutter

Thanks.

**Comment by popoolatopzy** [comment]
Hi @PaulBratslavsky

I will like to update the article 
https://strapi.io/blog/how-to-build-a-simple-crud-application-using-flutter-and-strapi
If it's still available.

**Comment by PaulBratslavsky** [comment]
@popoolatopzy yes that would be awesome, thank you.  I will assign it to you.  You can get started.

**Comment by Gunkev** [comment]
Hi @PaulBratslavsky 
How about the second article?

**Comment by PaulBratslavsky** [comment]
@Gunkev you can work on the second article.  Thank you.

**Comment by popoolatopzy** [comment]
Hi @PaulBratslavsky, the draft for this article is ready.
https://www.dropbox.com/scl/fi/mle0x5y9o0icxwbhu0sa2/How-to-Build-a-Simple-CRUD-Application-Using-Flutter-Strapi.paper?dl=0&rlkey=mggtbn2bevnx9yu03gb7z6gvx

**Comment by PaulBratslavsky** [comment]
@popoolatopzy thank you will add it to review.

**Comment by PaulBratslavsky** [comment]
@Gunkev can you confirm with me that you are able to work on the update.

**Comment by Gunkev** [comment]
@PaulBratslavsky yes Almost done. I will be rounding up and sending it tomorrow

**Comment by Gunkev** [comment]
Hi @PaulBratslavsky article draft is ready
https://www.dropbox.com/scl/fi/fiackeos8wo4vi7c4ityy/Build-a-To-Do-App-with-Strapi-GraphQL-Plugin-and-Flutter.paper?rlkey=wul43ipsglw2mb7s8d2k9ebqx&dl=0
