### ISSUE TITLE
[SUBMIT] Building a dynamic pagination component using Next.js and Strapi.

### ISSUE THREAD

**Issue by Daiveedjay** [strapi/community-content#1210]
**My resource**

**My content is**

### Content Brief:
- Target audience: Web developers and bloggers who use Next.js and Strapi for their projects.
- Keywords: Next.js, Strapi, pagination component, dynamic pagination, user experience, blog.
- Industries this content will target Web development, blogging, and content management.
- Source: The need for a dynamic pagination component is frequently raised by the community on platforms like GitHub, Reddit, and the Strapi forum.
- Content objective: The objective of this article is to provide a step-by-step tutorial on building a dynamic pagination component using Next.js and Strapi. It will cover the implementation details, best practices, and tips for enhancing the user experience of a blog by enabling seamless navigation through paginated content.
- Content outline: 
  1. Introduction to the importance of pagination in a blog.
  2. Overview of Next.js and Strapi as the chosen technologies.
  3. Setting up a Next.js project and integrating Strapi as the backend.
  4. Designing the pagination component.
  5. Implementing the logic for dynamic pagination based on content length.
  6. Enhancing the user experience with smooth transitions and loading indicators.
  7. Additional tips and considerations for advanced pagination features.
  8. Conclusion and next steps.

- [x] A Strapi Tutorial / Guide / How-to article
- [ ] About Headless, CMS, JavaScript, open source, or Jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@Daiveedjay   This would be a great topic, sorry for the late response.  We have been working with smaller team size and had many article submissions in the backlog.  

I am finally catching up.

We would still love to have you write this article if you are still open to it.  Thank you for your understanding and patience.

**Comment by consolexyz** [comment]
@PaulBratslavsky Hello I would love to write this article  if he is not available

**Comment by PaulBratslavsky** [comment]
@Daiveedjay just to check in, are you still able to write this post, otherwise @consolexyz would like to write it.

**Comment by Daiveedjay** [comment]
Hi @PaulBratslavsky, my apologies for not reaching out earlier. As of when I pitched the topic, my schedule was free enough to accommodate writing it. I’m still interested in writing the article, but unfortunately, my schedule is a little tight at the moment so he can have it.
Hopefully, in the future, I'll be able to pitch and write more informative articles for Strapi. All the best!

**Comment by Daiveedjay** [comment]
Hi Paul, I've sent a reply on GitHub.
ᐧ

**Comment by consolexyz** [comment]
@hanakhelifa i pinged you on discord
