### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Creating a Strapi Dynamic Zone & Rendering it in Your Nuxt.js App

### ISSUE THREAD

**Issue by JericksonJ** [strapi/community-content#1214]
Hi @PaulBratslavsky and @dessireugarte , I would like to update this article "Creating a Strapi Dynamic Zone & Rendering it in your Nuxt.js App". Please see below for my submission. Thank you!

Target Audience: Intermediate — Advance

Sources:
https://strapi.io/blog/creating-strapi-dynamic-zone-in-nuxtjs-app

https://strapi.io/documentation

https://nuxtjs.org/docs

https://github.com/strapi/strapi

https://github.com/nuxt/nuxt.js

https://forum.strapi.io/

https://nuxtjs.community/

Content Objective:
Dynamic zones in Strapi allow you to create flexible and customizable content structures for your applications. When combined with the power of Nuxt.js, you can effortlessly build dynamic and engaging user interfaces. In this article, I'll guide you on how to create a dynamic zone in Strapi and seamlessly render it in your Nuxt.js app.

Content Outline:
I. Introduction
II. Setting up a Strapi Backend
III. Creating Dynamic Content Modules
IV. Building a Nuxt.js App
V. Customizing Dynamic Zone Rendering
VI. Enhancing the Dynamic Zone Functionality
VII. Conclusion

**Link of the content**
https://strapi.io/blog/creating-strapi-dynamic-zone-in-nuxtjs-app

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
This post has already been updated.  I am going to pull the repo and double check that everything is working correctly.  Thanks for letting us know.  If it still is not working I will contact the original author to fix.
