### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Build a To-Do App with Strapi GraphQL Plugin and Flutter

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/community-content#1215]
**Description**

[Build a To-Do App with Strapi GraphQL Plugin and Flutter
](https://strapi.io/blog/build-a-to-do-app-with-strapi-graph-ql-plugin-and-flutter)

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by divofred** [comment]
Hello @PaulBratslavsky, there is no response to this.
Can I write it?

**Comment by PaulBratslavsky** [comment]
There was someone who already asked about this first.  https://github.com/strapi/community-content/issues/1208#issuecomment-1602992950  let me confirm with them if they are still working on it.

**Comment by dessireugarte** [comment]
Hello 👋 
Based on the conversation on [this](https://github.com/strapi/community-content/issues/1208#issuecomment-1602992950) issue, I will close this one.
