### ISSUE TITLE
Strapi - Build a blog using Strapi and Next.js - yarn build crashes with Error occurred prerendering page 

### ISSUE THREAD

**Issue by Husky931** [strapi/community-content#1218]
I have followed and completed the tutorial on "Build a blog using Strapi and Next.js". It is working as it should in dev mode. 
However, when you try to build it it crashes with the prerendering page Error:

Error occurred prerendering page "/en/how-ai-will-change-the-landscape-of-building-products/how-ai-will-change-the-landscape-of-building-products". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: (0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxDEV) is not a function
    at RootLayout (webpack-internal:///(sc_server)/./app/layout.tsx:20:94)
    at attemptResolveElement (webpack-internal:///(sc_server)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js:1167:30)
    
    This goes on for all the articles that were inserted by the tutorial

**Comment by hanakhelifa** [comment]
Thanks for the letting us know for the error. We'll look into it. 
For next time, you can comment the article directly, that would open an issue on https://forum.strapi.io/
