### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to build a To-do App using Next.js and Strapi

### ISSUE THREAD

**Issue by divofred** [strapi/community-content#1221]
Hello @dessireugarte @PaulBratslavsky can I work on this update?
The article makes use of Strapi v3, I'll update it to Strapi v4 using graphql.

**Link of the content**
https://strapi.io/blog/how-to-build-a-to-do-app-using-next-js-and-strapi

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@divofred you can start working on this, just make sure to use the new next 13 features with the app folder since that is the direction next is going.  Thank you.

**Comment by divofred** [comment]
Alright @PaulBratslavsky, I'll get started immediately.

**Comment by divofred** [comment]
Hello @PaulBratslavsky @dessireugarte, I'm done with this article.
Here is the link to the [article](https://www.dropbox.com/scl/fi/8ntnr2qbg9ilb416am0qo/How-to-build-a-To-do-App-using-Next.js-and-Strapi.paper?rlkey=gd8ml96pt1eha458d6pf32mtj&dl=0)
https://www.dropbox.com/scl/fi/8ntnr2qbg9ilb416am0qo/How-to-build-a-To-do-App-using-Next.js-and-Strapi.paper?rlkey=gd8ml96pt1eha458d6pf32mtj&dl=0

**Comment by dessireugarte** [comment]
Thank you @divofred. We will accept the article on Dropbox, but please take into consideration the [new guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md) where you should submit your content on HackMD. Also, please update the covers with the new design 👍

**Comment by divofred** [comment]
> Thank you @divofred. We will accept the article on Dropbox, but please take into consideration the [new guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md) where you should submit your content on HackMD. Also, please update the covers with the new design 👍 

Alright, noted.

**Comment by divofred** [comment]
Hello @dessireugarte, I've updated the covers with the new design.
