### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Build a Simple CRUD Application Using Flutter & Strapi

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#1224]
Update to v4

**Link of the content**

https://strapi.io/blog/how-to-build-a-simple-crud-application-using-flutter-and-strapi

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by dessireugarte** [comment]
Hello @PaulBratslavsky 👋 I created an issue for the update of [this](https://strapi.io/blog/how-to-build-a-simple-crud-application-using-flutter-and-strapi) article by @popoolatopzy discussed on [this](https://github.com/strapi/community-content/issues/1208) issue. 

The draft is ready for review https://www.dropbox.com/scl/fi/mle0x5y9o0icxwbhu0sa2/How-to-Build-a-Simple-CRUD-Application-Using-Flutter-Strapi.paper?rlkey=mggtbn2bevnx9yu03gb7z6gvx&dl=0

**Comment by popoolatopzy** [comment]
Hi @PaulBratslavsky and @dessireugarte any update on the draft.

**Comment by PaulBratslavsky** [comment]
@popoolatopzy I made the final edits and scheduled should be published soon.  You can send in your invoice.   Thank you.🙂

**Comment by vcoisne** [comment]
@popoolatopzy  Your article is [live](https://strapi.io/blog/how-to-build-a-simple-crud-application-using-flutter-and-strapi)! 🎉
You can now publish the article on [Dev.to](http://dev.to/) and Hashnode.

To ensure you don't miss any comments on your post, please register on our forum by clicking the discussion link at the bottom of your article.

If you would like to promote your article, we have some [templates](https://github.com/1645b77a97a640d2a32047297b6bc3f0) that can help you get started! Please feel free to reach out if you have any further questions or any other article in mind.

Your invoice has been submitted to our finance team for payment.
