### ISSUE TITLE
Building a complete food recipe app with react native and Strapi [SUBMIT]

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#1228]
### Features of the application
- User authentication
- User profile
- Add order to cart
- Card payment
### Building the application screen 
- Food home screen 
- authentication screens
- User profile screen 
- Add to Cart screen
- Orders/history screen
- Handling payment with paystack 
## Testing the application 

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@popoolatopzy sorry for the late response.  We have been working with smaller team size and had many article submissions in the backlog.  

I am finally catching up.

We would still love to have you write this article if you are still open to it.  Thank you for your understanding and patience.

**Comment by popoolatopzy** [comment]
Alright I'll start working on it and send the draft once I'm done it

**Comment by PaulBratslavsky** [comment]
@popoolatopzy thank you.

**Comment by hanakhelifa** [comment]
Hi @popoolatopzy , do you have a draft or an ETA to share with us?

**Comment by popoolatopzy** [comment]
Hi @hanakhelifa am not done with the article  yet, but i should be done in the next two weeks.

**Comment by popoolatopzy** [comment]
Hi @hanakhelifa any update on this draft?

**Comment by hanakhelifa** [comment]
Hi @popoolatopzy – a review has been made in the article. Once the comments I put on the draft have been treated, you can go ahead and add the article into Strapi's blog as a draft. How about we publish it on November 30th?

**Comment by popoolatopzy** [comment]
Thanks @hanakhelifa, November 30th is okay by me. I will address your comments over this weekend.

**Comment by popoolatopzy** [comment]
Hi @hanakhelifa, I have addressed your comments.

**Comment by hanakhelifa** [comment]
Hi, @popoolatopzy,
Thanks, looks good to me. Can you go ahead and add it as a draft to our blog, and send the invoice my way?

**Comment by popoolatopzy** [comment]
Thank you @hanakhelifa. I do not understand what you mean by "Can you go ahead and add it as a draft to our blog, and send the invoice my way?"
