### ISSUE TITLE
[TOPIC] Strapi authentication with Next.js?

### ISSUE THREAD

**Issue by mbudak** [strapi/community-content#123]
Could you provide an strapi authentication with nextjs? 
I don't want to use third party authentication system such as auth0 but I want to stick with strapi jwt.

I struggled to implement a real world application which has "app nav bar, mainlayout and footer" with nextjs strapi authentication.

Thank you,
Murat

**Comment by ghoshnirmalya** [comment]
I can pick this one up. I've worked with [NextAuth](https://next-auth.js.org/) and can use it with Strapi for authentication.

**Comment by malgamves** [comment]
hey @ghoshnirmalya is this the same as #109 or would you like to do them separately?

**Comment by ghoshnirmalya** [comment]
> hey @ghoshnirmalya is this the same as #109 or would you like to do them separately?

This will be a separate tutorial.

**Comment by Fl4zher** [comment]
@ghoshnirmalya when can we expect this tutorial? And will it be with REST or GraphQL?

**Comment by ghoshnirmalya** [comment]
> @ghoshnirmalya when can we expect this tutorial? And will it be with REST or GraphQL?

I can have this tutorial ready by 26th August. The authentication be done via REST.

**Comment by malgamves** [comment]
Awesome! I'll schedule it that way then 😄

**Comment by malgamves** [comment]
Awesome! I'll assign you as an Author. Lot's of auth articles coming out! Love it 🎊

**Comment by ghoshnirmalya** [comment]
@malgamves The boilerplate for building applications using Strapi and Next.js is available on [Github](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate).

This boilerplate is built using the following technologies:

1. [Chakra UI](https://chakra-ui.com/)
2. [Emotion](https://emotion.sh/)
3. [GraphQL](https://graphql.org/)
4. [Apollo](https://www.apollographql.com/)
5. [NextAuth](https://next-auth.js.org/)
6. [TypeScript](https://www.typescriptlang.org/)

The [readme](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate/blob/master/readme.md) file contains all the necessary documentation. I also plan to do a detailed documentation [on my website](https://nirmalyaghosh.com/docs/nextjs-strapi-boilerplate).

**Comment by malgamves** [comment]
This looks amazing!! I really like how well this is documented. Can't wait to have a look at the article. Do you have a demo app running somewhere?

**Comment by ghoshnirmalya** [comment]
> This looks amazing!! I really like how well this is documented. Can't wait to have a look at the article. Do you have a demo app running somewhere?

@malgamves I haven't deployed it anywhere yet. However, I plan to deploy the Strapi application on Heroku and the Next.js application on Vercel soon.

**Comment by sebacampos** [comment]
@ghoshnirmalya Thanks for the boilerplate!! I cloned the repo and had some trouble but finally could make it work. My problems were mostly on DB settings part so I left a comment on this [here explaining my steps to make it work](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate/issues/4#issuecomment-683794773) in case someone else finds it useful

**Comment by ghoshnirmalya** [comment]
@sebacampos Thank you for your help. I've [added a comment](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate/issues/4#issuecomment-683886301) which should help in fixing the issue.

**Comment by ghoshnirmalya** [comment]
@malgamves @sebacampos Do you guys know if it's a good idea to save the volume (in case of Docker) or default data for Strapi? I'd like to save a few records in my database so that anyone who clone the [boilerplate](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate) can get the development server up and running very easily.

I'd like to save the default data:
1. GraphQL plugin enabled by default.
2. Google provider enabled by default. The value can be added later or extracted from an env file.
3. Default permissions of a few models (User and Feed) for Authenticated users.

**Comment by sebacampos** [comment]
> @malgamves @sebacampos Do you guys know if it's a good idea to save the volume (in case of Docker) or default data for Strapi? I'd like to save a few records in my database so that anyone who clone the [boilerplate](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate) can get the development server up and running very easily.
> 
> I'd like to save the default data:
> 
> 1. GraphQL plugin enabled by default.
> 2. Google provider enabled by default. The value can be added later or extracted from an env file.
> 3. Default permissions of a few models (User and Feed) for Authenticated users.

@ghoshnirmalya That would be nice! I don't have that much experience with Strapi on Docker to determine the best way to do it. I guess using Docker would be easier for this need, but i'm thinking that without Docker you will need to provide a DB dump with the records already inserted, and then anyone cloning the repo will import that dump into their local DB, maybe? Anyway should wait someone from Strapi team answer on this one for any hint or suggestions

**Comment by malgamves** [comment]
> 
> 
> @malgamves @sebacampos Do you guys know if it's a good idea to save the volume (in case of Docker) or default data for Strapi? I'd like to save a few records in my database so that anyone who clone the [boilerplate](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate) can get the development server up and running very easily.
> 
> I'd like to save the default data:
> 
>     1. GraphQL plugin enabled by default.
> 
>     2. Google provider enabled by default. The value can be added later or extracted from an env file.
> 
>     3. Default permissions of a few models (User and Feed) for Authenticated users.

Hey, what we do with our Starter is we populate the database on build using the `bootstrap.js` a good example is our [Gatsby Starter](https://github.com/strapi/strapi-starter-gatsby-blog). No need for Docker volumes then. I hope this helps somehow.

**Comment by malgamves** [comment]
hey @ghoshnirmalya any updates on this?

**Comment by ghoshnirmalya** [comment]
> hey @ghoshnirmalya any updates on this?

@malgamves I've shared the link to the article with you on Slack.

**Comment by 7alip** [comment]
> @malgamves The boilerplate for building applications using Strapi and Next.js is available on [Github](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate).
> 
> This boilerplate is built using the following technologies:
> 
> 1. [Chakra UI](https://chakra-ui.com/)
> 2. [Emotion](https://emotion.sh/)
> 3. [GraphQL](https://graphql.org/)
> 4. [Apollo](https://www.apollographql.com/)
> 5. [NextAuth](https://next-auth.js.org/)
> 6. [TypeScript](https://www.typescriptlang.org/)
> 
> The [readme](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate/blob/master/readme.md) file contains all the necessary documentation. I also plan to do a detailed documentation [on my website](https://nirmalyaghosh.com/docs/nextjs-strapi-boilerplate).
> 
> It'd be great if you guys could help me by reporting any bugs, typos or anything that'd make the boilerplate better. Please feel free to create a new [issue](https://github.com/ghoshnirmalya/nextjs-strapi-boilerplate/issues/new).

Hi @ghoshnirmalya!

Thanks for your great work. I couldn't make it work because I don't know what will be the redirect urls in both Google and Strapi sides. I got an error when I click sign in button:

`<my-deployed-frontend-url>/api/auth/callback/google, does not match the ones authorized for the OAuth client.`

**Comment by kulbon** [comment]
I also have problems with this tutorial. The biggest one is that Strapi has a token and next-auth has a token also, no matter if you replace it with this code:
`if (isSignIn) {
        const response = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL}/auth/${account.provider}/callback?access_token=${account?.accessToken}`
        );

        const data = await response.json();
        token.jwt = data.jwt;
        token.id = data.user.id;
      }
}
`
You can set Strapi token expiration to 1h. When you log in with next-auth after 1h all yours api calls will be unauthorized (401) and you still will be logged in on frontend. Correct me if i am wrong.

**Comment by ghoshnirmalya** [comment]
@7alip Can you try adding the following callback urls?

```
http://localhost:3000/api/auth/callback/google
http://localhost:1337/connect/google/callback
```

Let me know if this works for you.

**Comment by ghoshnirmalya** [comment]
@kulbon Thank you for reporting this issue. I think that you can set the `maxAge` in NextAuth. [Check out their documentation](https://next-auth.js.org/configuration/options#session).

**Comment by kulbon** [comment]
@ghoshnirmalya I did it already.

// Seconds - How long until an idle session expires and is no longer valid.
  maxAge: 30 * 24 * 60 * 60, // 30 days

I think that IDLE is a keyword. I Set maxAge to 60, if you refresh page once in 60s then token expiration will be renewed.

**Comment by 7alip** [comment]
@ghoshnirmalya

### 1. mongodb peerOptionalDependencies

![image](https://user-images.githubusercontent.com/22167684/98451043-1a964a00-20f7-11eb-8641-b8f62f4e4cbc.png)

I have noticed that the solution of this problem might be @iaincollins 's [solution](https://github.com/nextauthjs/next-auth/issues/552#issuecomment-671662283) in vercel. But I've also tried it in netlify I got the same screen and when I check the function logs in netlify I've seen the following error: 

```
ERROR	[next-auth][error][adapter_connection_error] MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "better-sqlite3", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".
```

___

### 2. Serverless Functions Limitation

When I try to login in [your app](https://nextjs-strapi-boilerplate.vercel.app/) not always but sometimes I encounter with this error page. You can check your functional logs in vercel dashboard. The reason of the error is might be because of limitations. 

![image](https://user-images.githubusercontent.com/22167684/98460587-8cec4600-215a-11eb-998a-a80b700cc67a.png)

**Comment by TasTing** [comment]
Is graphql an essential plugin? Next's dynamic routing is one of reason I'd like to use it.

**Comment by kulbon** [comment]
> Is graphql an essential plugin? Next's dynamic routing is one of reason I'd like to use it.

It is not. You can replace graphql queries with REST API calls

**Comment by malgamves** [comment]
This was published - [User Authentication in Next.js with Strapi](https://strapi.io/blog/user-authentication-in-next-js-with-strapi)

**Comment by fodurrr** [comment]
> > I can pick this one up. I've worked with [NextAuth](https://next-auth.js.org/) and can use it with Strapi for authentication.
> 
> I'm trying to use [NextAuth](https://next-auth.js.org/) with Strapi. But, it seems like the schema that NextAuth uses is different from what Strapi uses for users, accounts, etc. As a result, I might be using JWT to handle authentication instead of using NextAuth.
> 
> I'll post updates on this issue.
Hi, @ghoshnirmalya , I try to use your final version of the  next-auth tutorial but with Amazon cognito, It seems working but no new user created in Strapi database. How did you solved the different schema you mentioned here? (next-auth creates accounts and users tables, but strapi stores users in the users-permission-users table. Any help would be appreciated.
