### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Build a static blog with Gatsby 4 and Strapi

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#1230]
**Link of the content**
https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi 

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by dessireugarte** [comment]
Hello @Marktawa! I created the issue, you can let Paul know over here when the article is ready.

**Comment by PaulBratslavsky** [comment]
@Marktawa just wanted to follow up on the progress of this update.

**Comment by Marktawa** [comment]
Hey @PaulBratslavsky 
I am still working on the article. I will let you know once it is ready.

**Comment by hanakhelifa** [comment]
Hi @Marktawa, do you have a draft or an ETA to share with us?

**Comment by Marktawa** [comment]
Hi @hanakhelifa 
Please review my article I'm done.
[**ARTICLE DRAFT**](https://hackmd.io/@markmunyaka/BypTn0hA3/edit)

**Comment by Marktawa** [comment]
Hi @hanakhelifa, I have made the link to the draft public and sent an invite to your email.

Please review the article:
Link: [How to Build a Static Blog with Gatsby and Strapi](https://hackmd.io/@markmunyaka/BypTn0hA3/edit)

**Comment by Marktawa** [comment]
Thanks @hanakhelifa for the review.
Yes you can publish the article next week. I am fine with that.

Cheerio

**Comment by Marktawa** [comment]
Hey @hana75 
Is there any update concerning publishing this article?

**Comment by hana75** [comment]
Hello @Marktawa, and happy new year. Your blog post is scheduled to be published on January 9th. :)

**Comment by Marktawa** [comment]
Happy New Year @hana75 to you too. Thanks for the update!
