### ISSUE TITLE
Deployment and Hosting Best Practices for Strapi Applications

### ISSUE THREAD

**Issue by TechMakanaki** [strapi/community-content#1231]
**My resource**

**My content is**
* Introduction
* Strapi overview
* Deployment preparation
* Choosing the right hosting
** Strapi cloud
** Shared Hosting vs. Dedicated Hosting
** Cloud Hosting Providers
        1. Amazon Web Services (AWS)
        2. Google Cloud Platform (GCP)
        3. Microsoft Azure
* Configuration and requirements
* Monitoring and Logging
* Securing the Deployment
* Load Balancing (For Scalability)
* Upgrading Strapi
* Conclusion.
- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by TechMakanaki** [comment]
@dessireugarte kindly help me review this topic. Thanks

**Comment by PaulBratslavsky** [comment]
@TechMakanaki we have a similar article here https://strapi.io/blog/6-top-deployment-options-for-your-strapi-application was wondering 

What would be interesting to compare each service by cost, difficulty level of the setup process, cost of managing and time commitment.  

I can see if I can get you a Strapi Cloud account free for 30 days while you are writing this article.  

Let me know if you would be interested in writing this type of article.  Thank you.

**Comment by TechMakanaki** [comment]
@PaulBratslavsky I will like to write on it. Kindly send me the outline you want me to work on.

Thanks and awaiting your response.

**Comment by PaulBratslavsky** [comment]
@TechMakanaki will do

**Comment by TechMakanaki** [comment]
@PaulBratslavsky I Will be waiting please.

**Comment by TechMakanaki** [comment]
@PaulBratslavsky please kindly reply me with the outline.

**Comment by PaulBratslavsky** [comment]
@TechMakanaki I am in the process of preparing the outline.

**Comment by TechMakanaki** [comment]
@PaulBratslavsky I just want to remind you and ask about the progress of the outline.

Thanks.

**Comment by hanakhelifa** [comment]
Hello @TechMakanaki, thank you so much for your interest in updating the 6 top deployment options article. As we are revamping the Write For the Community program, we have to close a few topic to ensure that we have the bandwith to handle the revamp, including this topic.
We'll present the new version of the program next community week, and I'll be sure to share the updates on Discord. If you have any question, you can find me on Discord.
