### ISSUE TITLE
[SUBMIT] API data validation in Strapi

### ISSUE THREAD

**Issue by divofred** [strapi/community-content#1232]
# API data validation in Strapi
Validating the data received from an API request is a critical aspect to consider when building robust and scalable applications. API (Application Programming Interface) acts as an intermediary that enables data to be shared between various software applications. Certifying the data shared through APIs is important as it handles errors and guarantees data integrity and consistency. This tutorial demonstrates the need for API data validation by building a blog application.

# Table of Content
- Introduction.
- What is API validation?
- Importance of API validation.
- Getting Started.
    - Initializing the application.
    - Setting up Strapi.
- Creating API data validation.
- Implementing the data validator.
- Setting up the front end.
- Creating CRUD requests.
- Conclusion.
- Resources.

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack.

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@divofred you can started on this thank you.

**Comment by divofred** [comment]
Hello @PaulBratslavsky, I'm done with the article.
[Here](https://www.dropbox.com/scl/fi/yhu8079s4901vznnc0w29/API-data-validation-in-Strapi.paper?rlkey=gb7ks38ixidogoppg27dq17tl&dl=0) is the link to the draft.

https://www.dropbox.com/scl/fi/yhu8079s4901vznnc0w29/API-data-validation-in-Strapi.paper?rlkey=gb7ks38ixidogoppg27dq17tl&dl=0

**Comment by PaulBratslavsky** [comment]
@divofred got it.  Thanks.

**Comment by divofred** [comment]
Hello @PaulBratslavsky,
What's the progress on this?
https://www.dropbox.com/scl/fi/yhu8079s4901vznnc0w29/API-data-validation-in-Strapi.paper?rlkey=gb7ks38ixidogoppg27dq17tl&dl=0

**Comment by divofred** [comment]
Hello @PaulBratslavsky @hanakhelifa, I haven't gotten a response concerning this.

**Comment by hanakhelifa** [comment]
Hello Divofred, as we discussed on Strapi's Discord, I am currently reviewing your article. I assigned myself to the ticket, and I'll keep you updated you right here.

**Comment by divofred** [comment]
Alright @hanakhelifa

**Comment by divofred** [comment]
Hello @hanakhelifa, I still haven't got feedback on this.

**Comment by hanakhelifa** [comment]
Hello @divofred–I made a review, and left a few suggestions on the copy. The article looks good to me other than that, and we could have the article published on December 13th. Is that OK with you?

**Comment by divofred** [comment]
Hello @hanakhelifa, I've made the necessary changes, waiting for the article to be published 🙂.

**Comment by divofred** [comment]
Hello @hanakhelifa, this article was scheduled to be published on the 13th of December. I haven't got any feedback in regards to this.

**Comment by vcoisne** [comment]
Published https://strapi.io/blog/api-data-validation-in-strapi Thank you!

**Comment by divofred** [comment]
@vcoisne 🎉🎉
