### ISSUE TITLE
[SUBMIT] Understanding the Strapi Request Chain: from KOA to Modern Middleware Architecture

### ISSUE THREAD

**Issue by hubertnare** [strapi/community-content#1234]
## Abstract
The article seeks to uncover the workings of the Strapi Request Chain. Explore how Strapi's middleware structure, rooted in KOA's foundation, guides the flow of requests and responses. Learn why the collaboration between these frameworks underscores the significance of effective middleware systems in shaping today's web applications.

### Content Outline
- Introduction
- KOA Perspective: Middleware Cascading and `await next()`
- The Strapi Request Chain: Building Upon KOA's Legacy
- `await next()` in Strapi
- Anatomy of the Strapi Request Chain
  - Global Middlewares
  - Routes
  - Route Middlewares
  - Route Policy
  - Controllers and Services
  - Models and Databases
 - How Strapi maintains the cascading middleware approach for consistent behavior.
 - Key Differences and Advancements
 - Where to put logic, (Best Practices)
 - The Evolution of Middleware: From KOA to Strapi
 - Conclusion
 - Additional Resources

**My content is**
- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@hubertnare I have assigned this to you. Thank you.

**Comment by hubertnare** [comment]
Noted, @PaulBratslavsky

**Comment by hanakhelifa** [comment]
Hi @hubertnare, do you have an ETA to share with us? :)

**Comment by hubertnare** [comment]
Hello Hana,

I apologize for my absence. You can expect the finished draft to be ready soon, but no later than Friday, the 20th.

**Comment by hubertnare** [comment]
Hi @hanakhelifa and @PaulBratslavsky ,

Please find the attached link to the draft;
https://www.dropbox.com/scl/fi/38na40y1mhzaq0xpkgx03/Untitled.papert?rlkey=et9wdzs3z0ehauu8tsb3g6yrg&dl=0

**Comment by hanakhelifa** [comment]
Hi @hubertnare, besides the few comment I left on the article, everything looks good to me.
We can schedule a publication date

**Comment by hubertnare** [comment]
👌🏻 Parfait, @hanakhelifa,

Well, when you say 'We,' are you referring to the Strapi team?

In the meantime, I'm considering writing a much more detailed best practice guide on Middlewares Vs. Controllers in Strapi. I couldn't cover that in depth without making the article considerably longer.

I can go ahead and create an issue, of course, but not without your green light.

Let me know what you think.

**Comment by hanakhelifa** [comment]
I did meant on our publishing calendar. It's publish [right here](https://strapi.io/blog/understanding-the-strapi-request-flow-a-journey-from-koa-to-modern-middleware-architecture), and we'll communicate about it starting tomorrow!

That's a great topic idea. Before opening an issue, can you confirm that you have seen last month's update on the Write for the Community program? While every interesting topic is more than welcome as a contribution, they are not all automatically compensated. If that's OK for you, you can go ahead and submit an issue. :)

**Comment by hubertnare** [comment]
Hey @hanakhelifa ,

I'm not aware of the new updates, but please feel free to brief me on them or perhaps refer me to where I can read through and catch up. I'm a bit confused when you say, 'They are not all automatically compensated'.

Nevertheless, I believe it's acceptable, so I'll proceed with submitting an issue.

**Comment by hanakhelifa** [comment]
Hi there, @hubertnare You can find the informations right here or here for the revamp of the program. 
In a few words, our goal is to provide more intermediate to expert content on how to use Strapi, and highlight the great use cases and project that are being built on Strapi. Different set of expectation will be set depending of it's a community contribution, or a paid contribution for instance. Thanks for your feedback, I'll update the Read.me again in the upcoming days to ensure that everything is clear for everyone. :)

You can send my way your invoice on hana.khelifa@strapi.io for the request chain articles.
