### ISSUE TITLE
Best practice usage of Strapi’s entityService vs Query Engine vs Direct Knex queries

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/community-content#1235]
**My resource**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by TechMakanaki** [comment]
I will love to write on this topic.

**Comment by Timileyhin** [comment]
I am interested in writing on this topic, upon request I can go ahead an present an outline of how I intend to bring the topic to life

**Comment by PaulBratslavsky** [comment]
@TechMakanaki let me check with the team, this may be an article that will need to be written internally.   I will get back to you as soon as I get the answer.

**Comment by TechMakanaki** [comment]
Okay. Thanks.

**Comment by hanakhelifa** [comment]
Closing the issue as the topic as been cleared
