### ISSUE TITLE
Have questions? Stop by for Open Office Hours (open to all) Mon - Friday 6AM CST and 12:30 PM CST

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/community-content#1237]
Stop by for Open Office Hours Mon - Friday 6AM CST and 12:30 PM CST
Do you have a burning question? Or would like to hang out. Stop on by on Discord: [Strapi Community](https://discord.com/invite/strapi)

**Comment by KaKi87** [comment]
Update :

> 🕰️ Our Europe - Open Office Hours event time has changed! 🕰️
>
> Due to the recent timezone changes, we're moving our event from its original slot at 12:00 UTC 🕛 to a new time at 9:00 UTC 🕙.
>
> — Simen D. on Discord

![Discord message screenshot](https://github.com/strapi/community-content/assets/21284089/31ce0d11-eb87-472d-bccf-d4e00e07e55d)
