### ISSUE TITLE
[SUBMIT] How to Build a Multilingual Blog with Strapi Headless CMS, Vue.js and GraphQL 

### ISSUE THREAD

**Issue by Gunkev** [strapi/community-content#1238]
# How to Build a Multilingual Blog with Strapi Headless CMS, Vue.js and GraphQL 

**My resource**
Creating a bilingual blog can help you reach a larger global audience, improve search engine optimization, and demonstrate cultural sensitivity and inclusion. By publishing information in different languages, you can attract visitors who do not speak the major language of your blog while also providing a better user experience for non-native speakers. Furthermore, search engines may favor multilingual websites in search results, resulting in greater traffic and interaction. Creating a bilingual blog can demonstrate your brand's dedication to diversity and cultural awareness, thus improving its reputation and appeal to a larger audience.

**My content is**

A Strapi Tutorial / Guide / How to article

# Table of Content
## Introduction
- Objective
- What is a Headless CMS
- Why Strapi?
## Conclusion

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by hanakhelifa** [comment]
Thanks @Gunkev for your submission. This tutorial proposition is a nice one!
 As we are revamping the Write For the Community program, we'll pause incoming request. I'll make sure to come back to you to present the new program.
Feel free to reach out to me on Discord (same name as here) if you have any question
