### ISSUE TITLE
[TOPIC] Realtime Data with Strapi

### ISSUE THREAD

**Issue by kaseer** [strapi/community-content#124]
when i change api my front end data remain same unless i refresh my webpage

**Comment by Mcastres** [comment]
Hello @kaseer, can you explain which starter are you referring to?

**Comment by kaseer** [comment]
I want to make a students portal

**Comment by kaseer** [comment]
I want to make students portal where they would share documents to each
other

**Comment by Mcastres** [comment]
Hey @kaseer, just checking if there is any update about this one?

**Comment by kaseer** [comment]
yes
Thanks and Regards,:
*Qaisar Mehmood*
+92 336 5526 289

**Comment by Mcastres** [comment]
How is it going? Should we keep this topic open?

**Comment by kaseer** [comment]
yes i would
Thanks and Regards,:
*Qaisar Mehmood*
+92 336 5526 289

**Comment by malgamves** [comment]
This was published - [How to Build a Real-time Chat Forum using Strapi, Socket.io, React and MongoDB](https://strapi.io/blog/how-to-build-a-real-time-chat-forum-using-strapi-socket-io-react-and-mongo-db)
