### ISSUE TITLE
[SUBMIT] STRAPI FOR NON-DEVELOPERS

### ISSUE THREAD

**Issue by Timileyhin** [strapi/community-content#1242]
Strapi for Non-Developers: A Beginner's Guide to Content Management
**My resource**
To write a user-friendly manual on how Strapi may be used by non-developers (such as content producers and marketers) to manage content and data without the requirement for technical knowledge(coding skills), this would help attract marketers and content creators without strong technical background or coding skills. 

### Content Brief: Strapi for Non-Developers: A Beginner's Guide to Content Management
- Target audience: Non-developers, content creators, marketers, and business professionals who want to manage website content without technical expertise.
- Keywords: Strapi
Content management
CMS
Non-developers
Content creation
User-friendly
media management
- Industries this content will target:  Non-developers, content creators, marketers and business professionals.
- Source: https://forum.strapi.io/
- Content objective: To create a beginner-friendly blog post that introduces non-developers, content creators, and marketers to Strapi as a user-friendly content management system. The goal is to provide step-by-step guidance on setting up Strapi, managing content, and utilizing its features without needing coding skills. 
- Content outline:        1. 	Introduction
Introduce Strapi as a user-friendly content management system.
Specify the target audience: non-developers, content creators, and marketers.
2.	What is Strapi?
Define Strapi as a tool for managing website content.
Emphasize its simplicity and suitability for non-technical users.
3.	Getting Started
Download and installation.
Creating an admin account.
4.	The Dashboard
Overview of the Strapi admin dashboard.
Highlight essential sections and their purposes.
5.	Creating Content
How to create, edit, and publish content in Strapi.
Organizing content using categories or tags.
6.	Managing Media
Uploading and handling images, videos, and other media files.
7.	User Permissions
Introduction to user roles and permissions.
Controlling who can access and modify content.
8.	Multilingual Content
Managing content in multiple languages.
Basic steps to set up multilingual content.
9.	Connecting to Websites or Apps
Briefly describe how Strapi connects to websites or apps through APIs.
Mention the basics of frontend integration.
10.	Additional Features
Highlight advanced features, including SEO settings and scheduled publishing.
11.	Conclusion
Summarize the main points.
Encourage non-developers to explore Strapi for their content needs.

-->

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
The outline looks great.  I would just add a part on content modeling.  Something that a lot of people struggle with.    Maybe we can title this `Strapi Content Modeling For Non dDevelopers`.

You can use this talk I did as reference. It is doing very well on youtube.  https://youtu.be/PDnWCnA6qTg

Let me know if you are ok with integrating this into your post.

**Comment by Timileyhin** [comment]
Thank you Paul for the response, I'm very well on board with integrating content modelling into the article. Just need your go ahead to start working in the article.

**Comment by vcoisne** [comment]
@Timileyhin sorry about the delay. We had some changes in the team. please go ahead with the draft :)

**Comment by Timileyhin** [comment]
No problem at all. Thank you for the update. I will proceed with the draft.

**Comment by vcoisne** [comment]
Hi @Timileyhin that's great news, when do you think you'll have the draft ready ?

**Comment by vcoisne** [comment]
Hi @Timileyhin just checking on timeline. It would be great to have some visibility

**Comment by Timileyhin** [comment]
Sorry for the delay in response

**Comment by vcoisne** [comment]
Hi @Timileyhin based on the outline it's a beginner-level article. A lot of this is covered under https://docs.strapi.io/user-docs/intro so I can't increase the compensation. Totally understand if you don't want to to move forward. If you do, please make sure to cover the use of Dynamic zones and useful plugins from the marketplace i.e https://market.strapi.io/plugins/strapi-plugin-preview-button

**Comment by Timileyhin** [comment]
Hello @vcoisne, the initial draft is ready kindly go through it and give me your feedback. Here is link to the draft https://docs.google.com/document/d/1L14x9pk3Wo1N4IilVmU6KYMPgOnWl4KfH6vrWLEAXr8/edit?usp=drivesdk

**Comment by vcoisne** [comment]
Thanks! I will let @Theodore-Kelechukwu-Onyejiaku take it from here.

**Comment by Timileyhin** [comment]
Ok thank you @vcoisne , looking forward to your  feedback @Theodore-Kelechukwu-Onyejiaku.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Timileyhin ,

Thanks for providing us with the draft. I will take it from here!

**Comment by Timileyhin** [comment]
@Theodore-Kelechukwu-Onyejiaku You're welcome! If you need any further assistance or revisions, feel free to reach out.

**Comment by Timileyhin** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku would do that

**Comment by Timileyhin** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku, here's the link to the article draft on HackMD 
https://hackmd.io/@atolani/H1j8wuMeA/edit

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Timileyhin ,

Thank you! At the moment, could you please go over it as your content is not properly formatted?

Cheers.

**Comment by Timileyhin** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku the article as been formatted. Look forward to more feedbacks from you

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Timileyhin,

After reviewing your article, we discovered that it consists of approximately 79.3% AI content. Regrettably, we have decided not to publish this piece. Consider this as your final warning.

Should a similar occurrence take place in the future, you will face immediate banning. Thank you!

**Comment by Timileyhin** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
I am seriously sorry for this, though I wrote the larger part of the content.
Would plead for a chance to rectify the mistake and rewrite the content. Would be glad if my request can be granted. Take this as an apology also.
