### ISSUE TITLE
[SUBMIT] Custom Soft Delete with Strapi and NextJs 14: Building a Recycle Bin

### ISSUE THREAD

**Issue by Theodore-Kelechukwu-Onyejiaku** [strapi/community-content#1254]
Soft deletion is an interesting topic when it comes to software development. It ensures that records or data are not deleted permanently in a database. Databases such as MySQL and PostgreSQL have support for this process.

In this tutorial, we will look at building a custom soft delete feature using Strapi.js. Coupled with this, we will implement our UI with the new Next.Js !4 App Router. At the end, we will have a working article gathering system with an inbuilt recycle bin.

### Content Brief: 
- Target audience: Strapi users and developers, React (Next.Js) Developers, Backend Developers
- Keywords: strapi, nextjs, nextjs 14, soft delete, recycle bin
- Source: Strapi blog, Discord, General questions,
- Content objective:
  * Explain the concept of soft delete
  * Learn how to implement soft delete logic
  * Understand how to customize Strapi routes and controllers.
  * Using Next.Js App Router for building applications using React's latest features
- Content outline:
  * What is Soft Delete
  * What is Strapi
  * What is Nextjs
  * Create User, Article, and Bin Collections
  * Adding Fields and Soft Delete Fields
  * Customizing controllers and Routes for Soft Delete Operations and Logic.
  * Bootstraping a NextJs App Router Project
  * Setting up folder pages (server and client), layouts, components, utils, error page and not found page. 
  * Implementing business logic in UI.
  * Testing App
  * Conclusion
  * Resources

**My content is**
For more informations about the categories, [refer to this page](https://strapi.io/write-for-the-community).
- [x] Tutorials
- [ ] Best practices
- [ ] Use cases & case studies
- [ ] API integration & frontend development
- [ ] Plugin development

**What do you all think?**
💙 I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @hanakhelifa,
Compliments of the season! I trust you are doing great.

Here is the draft to this article: https://www.dropbox.com/scl/fi/7pj0mtc1uvaz68nk0b3bu/Custom-Soft-Delete-with-Strapi-and-NextJs-14_-Building-a-Recycle-Bin.paper?rlkey=oaaxsxray3ej94is56k4i4aqc&dl=0

I can't wait to see it published!

Cheers

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @hanakhelifa @PaulBratslavsky , 

I hope your week is going great! I just want to ping you about this. Please let me know what you think.

All the best.

**Comment by hana75** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku, thank you for your draft. I loved that you showcased the demo though gifs.
I left a few comments in the draft you shared, and fixed a few typos and smooth out the copy. Could you check them out, and ping me when they are treated? We'll be able to publish you right after.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @hana75 ,

I hope you are doing fantastic. Thanks for the review, and I am glad you loved that I showcased the demo through gifs. Thank you. I want to let you know that I have resolved the comments.  

Cheers.

**Comment by hana75** [comment]
@Theodore-Kelechukwu-Onyejiaku That's great–we'll publish the article this Thursday then. I'll keep you updated here for promotion.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @hana75 , 

Thanks for letting me know.

**Comment by hana75** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku,
As you have seen, you are now a published author and your blog post has been published at this page: https://strapi.io/blog/custom-soft-delete-with-strapi-and-next-js-14-building-a-recycle-bin  
We've promoted it on our newsletter, as well as our social media platforms. We encourage you to share it too where you feel it could resonate (Reddit, HackerNews, Dev.to, etc.)
Have a great day!
