### ISSUE TITLE
[SUBMIT] How to Build a Multilingual Blog with Strapi Headless CMS, Vue.js and GraphQL

### ISSUE THREAD

**Issue by Gunkev** [strapi/community-content#1255]
# How to Build a Multilingual Blog with Strapi Headless CMS, Vue.js and GraphQL

My resource
Creating a bilingual blog can help you reach a larger global audience, improve search engine optimization, and demonstrate cultural sensitivity and inclusion. By publishing information in different languages, you can attract visitors who do not speak the major language of your blog while also providing a better user experience for non-native speakers. Furthermore, search engines may favor multilingual websites in search results, resulting in greater traffic and interaction. Creating a bilingual blog can demonstrate your brand's dedication to diversity and cultural awareness, thus improving its reputation and appeal to a larger audience.

My content is

A Strapi Tutorial / Guide / How to article
## Introduction

  -  Objective
  -  What is a Headless CMS
  -  Why Strapi?

#### What do you all think?
❤️ I love it!
🚀 I can help you!

**Comment by hanakhelifa** [comment]
Hello Gunvek,
Thanks for your submission. We already have a few tutorial online on how to build a blog with Strapi, so I'm mainly interested in the take on the multilingual website here. Do you have experience building a multilingual website on Strapi that will allow you to give out best practice? Both technically, but also on the content side (using AI, plugins, etc).
I'd love to pursue that topic

**Comment by Gunkev** [comment]
Hi @hanakhelifa,

Yes that is a great idea. Thanks for the suggestion. I have experience building multilingual application with Strapi. 

1. Enhancing User Experience: Multilingual Website Best Practices with Strapi
2. Common Mistakes to Avoid When Building a Multilingual Website with Strapi
3. Scaling Your Multilingual Website: Best Practices with Strapi

These are some generated topics from your idea. Please let me know which is suitable so that I can create the outline 

Thanks

**Comment by hanakhelifa** [comment]
Hi @Gunkev,
I like 1 and 3, they look quite similar so I think we can regroup the two

**Comment by Gunkev** [comment]
Hi @hanakhelifa this is the proposed outline

## Scaling Your Website and Enhancing User Experience: Multilingual Website Best Practices with Strapi

### Introduction

### What is Localization?

### Why is it Important to Localize Your App?

### Current Scope of Multilingual Website with Strapi

### Best Practices When Building Multilingual App with Strap

### Common Challenges You Can Face with Strapi

### Case Study: How to Localize Your Strapi Application

#### Prerequisites

#### Setup Strapi

#### Create Collection Type and Content

#### Prepare Content For Localization

#### Testing with GraphQL

### Summary

## Conclusion

**Comment by Gunkev** [comment]
Hi @hana75

Thanks for the suggestions. I will adjust and proceed immediately with article

**Comment by hana75** [comment]
@Gunkev Could you share a new outline that would include the type of best practices you had in mind before starting with the article?

**Comment by Gunkev** [comment]
Hi @hana75  here is the outline. Please let me know what you think.

# Scaling Your Website and Enhancing User Experience: Multilingual Website Best Practices with Strapi

## What is Localization?
## Why is it Important to Localize Your App?
## Current Scope of Multilingual Website with Strapi
## Best Practices When Building Multilingual App with Strapi
### Accommodate various Cultural Differences
### Understand How Localization works in Strapi
### Use the Strapi i18n Plugin
### Setup and Configure Your Localization Settings
### Update and synchronise content regularly in all locales
### Regularly update your Strapi Instance to get the latest i18n Plugin features
### Make sure to have a default Locale
## Common Challenges You Can Face with Strapi
## Conclusion

**Comment by Gunkev** [comment]
Hi @hana75

**Comment by vcoisne** [comment]
hi @Gunkev sorry about the late reply. We had some changes in the team.  I think we already have articles / docs that cover this topic so I will close this issue. Please feel free to submit other topic.
