### ISSUE TITLE
[TRANSLATE] Building a Complete Food Mobile App with React Native and Strapi - (FR)

### ISSUE THREAD

**Issue by Gunkev** [strapi/community-content#1256]
**The tutorial I want to translate**

Hello 👋 

I would like to translate the tutorial Building a Complete Food Mobile App with React Native and Strapi in French

https://strapi.io/blog/building-a-complete-food-mobile-app-with-react-native-and-strapi

**Community vote**
👍 Upvote if you need it too
❤️ I love it!
🚀 I can help you!

**Comment by hanakhelifa** [comment]
Hello @Gunkev,

Thank you for your submission. Right now, we are focusing on english-only content.
I'll keep your name in mind for when we'll look into translating our articles. :)
