### ISSUE TITLE
How to send a custom newsletter to users in Strapi [SUBMIT]

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#1260]
Hi @hanakhelifa I would like to write on this topic. below is my outline.

#### Conclusion

**Comment by hana75** [comment]
Hello @popoolatopzy 

I think you can merge 1. Introduction and 2.Importance of newsletter in your application as I believe they should be the same here.
Which plugin are you going to use for this tutorial?

**Comment by popoolatopzy** [comment]
Hi @hana75. Okay i will merge the two together. 

Yes that is the plugin i want to use. https://market.strapi.io/plugins/@strapi-newsletter-strapi

**Comment by hana75** [comment]
@popoolatopzy The plugin page contains the information on how to install the plugin, as well as how to configure it with Mailchimp and ConvertKit. Could you provide me an outline that will help me understand the difference between the plugin page and the blog post you want to write so we can better understand the angle of your proposition here? :)

**Comment by popoolatopzy** [comment]
Thanks @hana75 here is the updated outline:

Introduction
Importance of newsletter in your application
creating a new Strapi app
creating collection types
Newsletter plugin installation
Newsletter plugin configuration
Creating newsletter user subscriber page(react app)
Creating a customize newsletter message
How to send daily, weekly and monthly newsletter 
testing the newsletter
Conclusion

**Comment by hana75** [comment]
Hello @popoolatopzy,
Thank you very much for sending over your outline. 
After reviewing the material, I've noticed that most of the information is already available on our platforms, which you can find [here](https://market.strapi.io/plugins/@strapi-newsletter-strapi) and [here](https://www.npmjs.com/package/@strapi-newsletter/react). In our content strategy, we're currently focusing on _compensated_ writing missions that cater to a more intermediate to expert level audience, or on highly requested use case (alas, newsletter are not here).

**Comment by popoolatopzy** [comment]
Alright thanks.  I find another topic.
