### ISSUE TITLE
Comparison: Strapi Cloud vs. Joomla and WordPress[SUBMIT]

### ISSUE THREAD

**Issue by Oluwoleopeyemi** [strapi/community-content#1262]
Hi, @hana75, I would like to write about this article, and below is my outline.

I. Introduction
A. Overview of Strapi Cloud, Joomla, and WordPress as leading CMS options
B. Importance of selecting the right CMS for specific project requirements

II. Feature Analysis
A. Key features and functionalities of Strapi Cloud, Joomla, and WordPress
B. Comparison of core capabilities, including content management, design flexibility, e-commerce, SEO, etc
C. Hosting options and compatibility (hosting and expensive themes and plugins)

III. Performance and Scalability
A. Evaluation of performance metrics such as page load times and server response

IV. Security 
A. Overview of built-in security features with industry standards
B. Vulnerability management and security updates for Strapi Cloud, Joomla, and WordPress

V. Adaptability and Personalization
A. A comparison of the capabilities, design, and layout modification choices B. Extensibility via plugins, extensions, and third-party service integration

VI. Community Assistance and User Experience
A. Evaluation of developer resources, community involvement, and user satisfaction
B. Case studies illustrating successful applications in the real-world

Conclusion.

**Comment by vcoisne** [comment]
Hi @Oluwoleopeyemi we are working on comparison pages and therefore won't focus on CMS blog posts covering that topic.  Please do suggest other topics though :)
