### ISSUE TITLE
[SUBMIT] Building a Personal Development Tracker with Flutter, Strapi, and GraphQL: A Riverpod Integration Guide

### ISSUE THREAD

**Issue by nazlicankurt** [strapi/community-content#1263]
Hello 👋 

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax and you have read the [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md). 

Please describe what your article will be about in few sentences and inclide a content brief of the article: 
I propose a short guide on building a Personal Progress Tracker using Flutter with Strapi as the backend, focusing on GraphQL for data fetching and Riverpod for state management. This article will walk through the setup of Strapi for managing personal goals and progress and show how the headless CMS seamlessly integrates with Flutter to deliver dynamic content. We will leverage GraphQL for efficient communication between the application and backend and Riverpod for state management within Flutter, ensuring a seamless user experience.

### Content Brief: 

- Target audience: Mobile app developers interested in using Strapi with Flutter.
- Keywords: Personal Development Tracker, Strapi, Flutter, GraphQL, Riverpod.
- Content objective: To illustrate how to build a dynamic content app with Flutter and Strapi, utilizing GraphQL and Riverpod.
- Source: Flutter, Graphql and riverpod are requirements that I personally use daily and have contributed to the growth of our company.
- Content outline:
Quick intro to Flutter, Strapi, GraphQL, and Riverpod.
Configuring Strapi for managing personal development content.
Implementing GraphQL for data fetching in Flutter.
Using Riverpod for efficient state management.
Final thoughts 

- [+] API integration & frontend development

**What do you all think?**
💙 I love it!
🚀 I can help you!

**Comment by hana75** [comment]
Hello @nazlicankurt, thank you for your submission! We are interesting in this Riverpod integration, you can go ahead and start the article. Another team member will review your draft when it will be ready :)

**Comment by nazlicankurt** [comment]
good news! I'll start this week, thanks

**Comment by vcoisne** [comment]
hi @nazlicankurt just checking in. Did you get a chance to start ?

**Comment by vcoisne** [comment]
hi @nazlicankurt confirm you saw my message and able to proceed with the draft ?

**Comment by nazlicankurt** [comment]
hi @vcoisne sorry for delay.  it's been a busy month,  because of my regular job, I haven't completed a draft yet. what's the maximum time you can give me for a draft?we keep or close the issue accordingly? thanks

**Comment by vcoisne** [comment]
Hi @nazlicankurt thanks for the update. Lets say end of month ? would that work for you ?

**Comment by nazlicankurt** [comment]
hello @vcoisne  thanks for the feedback. Good, I will finish the draft by the end of this month at the latest.

**Comment by nazlicankurt** [comment]
Hello @vcoisne 

**Here is my draft:**

### Developing a Personal Target Tracking Application with Flutter Riverpod and Strapi GraphQL

With the evolution of technology, mobile application development processes are also evolving. In this article, we will explore how using Flutter and Riverpod for Strapi API and GraphQL integration can simplify and even transform application development processes.
The modern application development process with Flutter, Riverpod, and Strapi offers developers flexibility and scalability. With these technologies, you can create user-friendly and high-performance mobile applications. These aspects of application development play a critical role in the success of your project.  

Why Choose Riverpod for State Management?
In the realm of Flutter development, managing the state of an application can often become complex as the app grows. This is where Riverpod comes into play, offering a refined and advanced solution for state management that addresses the limitations of its predecessor, Provider. Here’s why Riverpod stands out:
* Scoped Access to State: Riverpod allows for the scoped access of state, ensuring widgets have access to the state they need and nothing more. This encapsulation enhances performance and reduces the likelihood of unintended side effects.
* Flexible State Modification: Riverpod simplifies state modification with its support for immutable state objects. By embracing the principles of immutability, it ensures that state changes are predictable and manageable.
* Incorporating Riverpod with freezed for Immutable State Management To leverage Riverpod alongside freezed in your Flutter project for even more robust state management, you'll be enhancing components like GoalNotifier to efficiently handle immutable state. freezed complements Riverpod by enabling the use of immutable objects in Dart, which aids in making your state management more predictable and safer.

**Combining Strapi with GraphQL for your Flutter application**, especially when managed with Riverpod, creates a powerful, efficient, and flexible development ecosystem. Here's why this combination is particularly effective:

Flexibility and Customizability: Strapi is a headless CMS that provides the flexibility to define your data structures (models), content types, and relations tailored to your application needs. This adaptability is crucial for Flutter apps that may require a custom set of data.

Together, Strapi, GraphQL, Flutter, and Riverpod create a cohesive development ecosystem that balances backend flexibility, efficient data management, cross-platform UI development, and robust state management. This combination is particularly potent for building modern, scalable, and high-performance mobile applications that require real-time data updates, custom content structures, and a smooth user experience across multiple platforms. 

**Requirements:**
* UI Development: Your application's user interface can be easily created using Flutter widgets. This shapes the look and feel of your application.
* State Management: Developing the core part of your application with a state management system enhances the scalability and maintainability of your app. Riverpod offers a strong and flexible solution in this regard.
* Backend Integration: The ease provided by the Strapi API makes backend integration less cumbersome at this stage of the project. Working with Strapi offers a significant advantage in terms of data management and API calls.

**Integration Steps:**
* Setting Up Components: Create the user interface (UI) components of your application.
* Creating Providers: Use Riverpod to create providers for state management. These providers manage the data flow between different parts of your application.
* Adding Routers: Set up routers to manage transitions between pages. This ensures a smooth navigation experience within the app.
* Testing with Mock Data: In the initial stage, test your providers and UI components with mock data. This provides quick feedback on your application's data structures and workflows.

**Transition from Mock Data to Strapi and GraphQL:**
* Strapi Setup and Configuration: Set up your Strapi project and create the necessary API endpoints. These endpoints define the data types and structures your application needs.
* Defining GraphQL Schemas: From the Strapi administration panel, define your GraphQL schemas. These schemas determine the structure of the data your application will query from Strapi.
* Updating Your Providers: Update the providers in your application to make queries to real Strapi endpoints instead of mock data. Configure your Riverpod providers to execute your GraphQL queries and connect the data to your application.
* Queries and Mutations: Write your GraphQL queries and mutations. These queries enable your application to fetch or send data to Strapi.

Before starting your project, it's essential to have your Flutter development environment properly set up. This requires having the Dart SDK and downloading Flutter directly from its official website (flutter.dev). To verify you are using the latest version of Flutter, run the flutter doctor command in your terminal. Additionally, if you're using an advanced Integrated Development Environment (IDE) like Visual Studio Code (VSCode), you can directly use iOS or Android emulators through the IDE.
We named our project 'personal_goals_app'. This name reflects our aim to create an application where users can set personal goals. A clean Flutter setup and the establishment of a state management system with Riverpod greatly facilitate Strapi API integration.

### 1. Setting Up Your Flutter Project
Through the terminal or command prompt, run the command flutter create personal_goals_app to create a new Flutter project named 'personal_goals_app'.
<img width="768" alt="image" src="https://github.com/strapi/community-content/assets/46849299/5d0972b1-ec38-4805-b3b3-41de6d553bf7">

Navigate to the created project directory (cd personal_goals_app) and start your application with the flutter run command. This confirms that your first Flutter application is running successfully.

VSCode Command Palette: 

<img width="615" alt="Screenshot 2024-03-29 at 09 12 15" src="https://github.com/strapi/community-content/assets/46849299/2f2636d7-f202-4b8f-9025-ff6cc9ccd39a">

VSCode Terminal:
<img width="615" alt="Screenshot 2024-03-29 at 09 12 40" src="https://github.com/strapi/community-content/assets/46849299/29a2055a-c8e2-4c90-89ae-7aecb975ca59">

The src/goals/components and src/goals/provider directories hold your UI components and state management logic, respectively. This separation makes your code more readable and manageable.
<img width="323" alt="• home dart" src="https://github.com/strapi/community-content/assets/46849299/2cd6c986-d564-477b-926e-d7b4cc9a569f">

The src/goals directory contains your Goal model and general files. main.dart includes your application's navigation and basic settings.

### 2. Setting Up Your Providers with Riverpod
State management is one of the cornerstones of modern application development. Riverpod stands out for its flexibility and ease of use in this area.

Navigate to your pubspec.yaml file and add the following line under dependencies to include Riverpod in your project:

```
dependencies:
 flutter:
   sdk: flutter

 # The following adds the Cupertino Icons font to your application.
 # Use with the CupertinoIcons class for iOS style icons.
 cupertino_icons: ^1.0.2
 flutter_riverpod: ^2.5.1
 intl: ^0.18.0
```

**Define Your Goal Model in goal_model.dart:**
Use the Goal class and GoalStatus enum.

```
enum GoalStatus { active, completed, pending }
enum GoalCategory { vacation, money, exercise, smoke, language }

class Goal {
  final String id;
  final String name;
  final String description;
  final DateTime startDate;
  final DateTime? endDate; // End date is optional because some goals might not have a specific end date
  final GoalCategory category;
  GoalStatus status;
  double? targetValue; // Numeric value representing the goal target (e.g., amount to save)
  double? currentValue; // Current progress towards the goal (e.g., current savings)

  Goal({
    required this.id,
    required this.name,
    required this.description,
    required this.startDate,
    this.endDate,
    required this.category,
    this.status = GoalStatus.pending,
    this.targetValue,
    this.currentValue,
  });



  // Calculate the status of the goal based on dates
  static GoalStatus calculateStatus(DateTime startDate, DateTime endDate) {
    final currentDate = DateTime.now();
    if (currentDate.isAfter(endDate)) {
      return GoalStatus.completed;
    } else  if (currentDate.isAfter(startDate)) {
      return GoalStatus.active;
    } else {
      return GoalStatus.pending;
    }
  }


}

```
**Define Your State with Freezed**
Create a new file for your state, e.g., goal_state.dart. Use freezed to define an immutable state class. In this example, the state will directly hold a list of goals, but you could expand it to include other state properties as needed.

```
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:personal_goals_app/src/goals/models/goal_model.dart'; 
part 'goal_state.freezed.dart';

@freezed
class GoalState with _$GoalState {
  const factory GoalState({
    @Default([]) List<Goal> goals,
  }) = _GoalState;
}
```


**Create a State Notifier:**
In the lib/src/providers directory, create a file named goal_provider.dart. In this file, set up a structure using StateNotifier that allows you to add, update, and delete goals.

```
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:personal_goals_app/src/goals/models/goal_model.dart';
import 'package:personal_goals_app/src/provider/goal_state.dart';

class GoalNotifier extends StateNotifier<GoalState> {
  GoalNotifier()
      : super(GoalState(goals: [
          Goal(
            id: '1',
            name: 'Vacation in Milan',
            description: 'Enjoy the beauty of Milan',
            startDate: DateTime(2024, 04, 29),
            endDate: DateTime(2024, 11, 1),
            category: GoalCategory.vacation,
            status: GoalStatus.active,
          ),
          Goal(
            id: '2',
            name: 'Quit Smoking',
            description:
                'Reduce cigarette intake gradually and increase smoke-free days',
            startDate: DateTime.now(),
            endDate: DateTime.now().add(const Duration(days: 90)),
            category: GoalCategory.smoke,
          ),
        ]));

  // Add a new goal
  void addGoal(Goal goal) {
    state = state.copyWith(goals: [...state.goals, goal]);
  }

  // Update an existing goal
  void updateGoal(String id, Goal updatedGoal) {
    state = state.copyWith(
      goals: state.goals
          .map((goal) => goal.id == id ? updatedGoal : goal)
          .toList(),
    );
  }

  // Delete a goal
  void deleteGoal(String id) {
    state = state.copyWith(
      goals: state.goals.where((goal) => goal.id != id).toList(),
    );
  }
}

final goalProvider = StateNotifierProvider<GoalNotifier, GoalState>((ref) {
  return GoalNotifier();
});

```

**Wrap Your Application with ProviderScope:**
In the main.dart file, which is the main entry point of your application, wrap your MaterialApp widget with ProviderScope to make Riverpod's state management system available throughout your application.
void main() {
 runApp(const ProviderScope(child: MyApp()));
}

### 3. Setting Up Your Router and Components
Flutter operates through the main.dart file. In this file, you use the MaterialApp widget to bring your application to life and start it with runApp. Here, you can set up routing, define themes, and launch your homepage.

In the main.dart file, set up the navigation logic that will manage your application's transitions between pages. 
 
```

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Strapi Api Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const HomePage(),
      initialRoute: '/',
      routes: {
        '/start': (context) => StartGoal(),
        '/add': (context) => const GoalFormPage(),
        
      },
         onGenerateRoute: (settings) {
        if (settings.name == '/edit') {
          final goal = settings.arguments as Goal;
          return MaterialPageRoute(
            builder: (context) {
              return GoalEditPage(goal: goal); 
            },
          );
        }
        return null;
      },
    );
  }
}
```

Create UI Components:
Now we need to expand the component structure in src:
So home.dart will list our goals. Creating detailed components like goal_add.dart, goal_edit.dart, goal_start.dart, goal_card.dart will make our work and state management easier as the project progresses.
<img width="395" alt="Screenshot 2024-03-31 at 13 43 33" src="https://github.com/strapi/community-content/assets/46849299/2014bfdf-f21f-4ebf-8ac9-1cf3a815d0ec">



SECOND PART DRAFT




**Implement the Home Page in home.dart:**
    * Display a list of goal cards.
    * Use a FloatingActionButton to navigate to the 'Add Goal' page.
    * Call provider here to read data.

```
class HomePage extends ConsumerWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final goals = ref.watch(goalProvider).goals;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Targets'),
      ),
      body: ListView.builder(
        itemCount: goals.length, 
        itemBuilder: (context, index) {
          final goal = goals[index];
          return GoalCard(goal: goal);
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
          Navigator.pushNamed(context, '/start'); 
        },
        label: const Text('Add New Target'),
        icon: const Icon(Icons.add),
      ),
    );
  }
}

```
**Create Goal Cards in goal_card.dart:**
    * Design a card widget that displays goal information.
    * Add buttons or gestures to each card to trigger edit or delete actions.

```
class GoalCard extends StatelessWidget {
  final Goal goal;

  const GoalCard({Key? key, required this.goal}) : super(key: key);

  String formatDate(DateTime date) {
    return '${date.month}/${date.year}';
  }

  Color getStatusColor(GoalStatus status) {
    switch (status) {
      case GoalStatus.active:
        return Colors.deepPurple;
      case GoalStatus.pending:
        return Colors.blue;
      case GoalStatus.completed:
        return Colors.green;
      default:
        return Colors.grey; 
    }
  }

  @override
  Widget build(BuildContext context) {
        goal.status = Goal.calculateStatus(goal.startDate, goal.endDate!);

    return Card(
      margin: const EdgeInsets.all(24),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          Container(
            width: 120,
            color: getStatusColor(goal.status),
            padding: const EdgeInsets.symmetric(vertical: 4, horizontal: 16),
            alignment: Alignment.center,
            child: Text(
              goal.status.toString().split('.').last.toUpperCase(),
              style: const TextStyle(color: Colors.white),
            ),
          ),
          ListTile(
            leading: const Icon(Icons.track_changes),
            title: Text(goal.name),
            subtitle: Text(
              'Target duration: ${goal.endDate?.difference(goal.startDate).inDays ?? 'N/A'} days',
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Expanded(
                  child: Text(
                    "End Date: ${goal.endDate != null ? formatDate(goal.endDate!) : 'N/A'}",
                    textAlign: TextAlign.left,
                  ),
                ),
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Expanded(
                  child: Text(
                    "Description: ${goal.description}",
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ),
          ButtonBar(
            children: [
              TextButton(
                child: const Text('Go Details'),
                onPressed: () {
                  Navigator.pushNamed(context,'/edit', arguments: goal);
                },
              ),
            ],
          ),
      const SizedBox(height: 40)

        ],
      ),
      
    );
  }
}

```

![Simulator Screenshot - iPhone 15 - 2024-03-31 at 15 24 40](https://github.com/strapi/community-content/assets/46849299/1dba825f-eaef-4874-bee8-c8d0ab2d142b)

**Build the Start Goal Page in goal_start.dart:**
```
class StartGoal extends StatelessWidget {
  StartGoal({super.key});

  final List<GoalList> targetList = [
    GoalList(
      title: 'Plan your vacation',
      icon: Icons.flight_takeoff,
      subtitle: 'Plan your next getaway',
    ),
    GoalList(
      title: 'Save Money',
      icon: Icons.attach_money,
      subtitle: 'Start saving money',
    ),
    GoalList(
      title: 'Quit Smoking',
      icon: Icons.smoke_free,
      subtitle: 'Track smoke-free days',
    ),
    GoalList(
      title: 'Exercise',
      icon: Icons.directions_run,
      subtitle: 'Keep up with your workouts',
    ),
    GoalList(
      title: 'Learn a new language',
      icon: Icons.book,
      subtitle: 'Stay on top of your studies',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add a new target')),
      body: ListView.builder(
        itemCount: targetList.length,
        itemBuilder: (BuildContext context, int index) {
          return Card(
            child: ListTile(
              leading: Icon(targetList[index].icon, size: 36,        color: Colors.deepPurple,),
              title: Text(targetList[index].title),
              subtitle: Text(targetList[index].subtitle),
              trailing: const Icon(
                Icons.arrow_forward_ios,
                color: Colors.deepPurple,
              ),
              onTap: () {


                Navigator.pushNamed(context, '/add');
              },
            ),
          );
        },
      ),
    );
  }
}

```
![Simulator Screenshot - iPhone 15 - 2024-03-31 at 15 25 06](https://github.com/strapi/community-content/assets/46849299/fc24a7b0-7b66-4a1a-8e3b-1405993802da)

 **Build the Add Goal Page in goal_add.dart:**
    * Create a form for adding a new goal.
    * Consider using a PageView if you want a step-by-step guide to input the information, but a single form would be simpler and is usually sufficient.

```

class GoalFormPage extends ConsumerStatefulWidget {
  const GoalFormPage({Key? key}) : super(key: key);

  @override
  GoalFormPageState createState() => GoalFormPageState();
}

class GoalFormPageState extends ConsumerState<GoalFormPage> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();

  DateTime? _startDate;
  DateTime? _endDate;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Add Target')),
        body: Form(
            key: _formKey,
            child: SingleChildScrollView(
                padding: const EdgeInsets.all(16.0),
                child: Column(children: [
                  TextFormField(
                    controller: _nameController,
                    decoration: const InputDecoration(labelText: 'Goal Name'),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter a goal name';
                      }
                      return null;
                    },
                  ),
                  TextFormField(
                    controller: _descriptionController,
                    decoration: const InputDecoration(labelText: 'Description'),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter a description';
                      }
                      return null;
                    },
                  ),
                  ListTile(
                    title: Text(
                        'Start Date: ${_startDate != null ? DateFormat('yyyy-MM-dd').format(_startDate!) : 'Select'}'),
                    trailing: const Icon(Icons.calendar_today),
                    onTap: () async {
                      final picked = await showDatePicker(
                        context: context,
                        initialDate: DateTime.now(),
                        firstDate: DateTime.now(),
                        lastDate: DateTime(2050),
                      );
                      if (picked != null && picked != _startDate) {
                        setState(() {
                          _startDate = picked;
                        });
                      }
                    },
                  ),
                  ListTile(
                    title: Text(
                        'End Date: ${_endDate != null ? DateFormat('yyyy-MM-dd').format(_endDate!) : 'Select'}'),
                    trailing: const Icon(Icons.calendar_today),
                    onTap: () async {
                      final picked = await showDatePicker(
                        context: context,
                        initialDate: DateTime.now(),
                        firstDate: DateTime(2000),
                        lastDate: DateTime(2100),
                      );
                      if (picked != null && picked != _endDate) {
                        setState(() {
                          _endDate = picked;
                        });
                      }
                    },
                  ),
                  const SizedBox(
                    height: 10,
                  ),
                  ElevatedButton(
                    onPressed: _saveGoal,
                    child: const Text("Save your goal"),
                  )
                ]))));
  }

  void _saveGoal() {
    if (_formKey.currentState!.validate()) {
      final newGoal = Goal(
        id: DateTime.now().millisecondsSinceEpoch.toString(),
        name: _nameController.text,
        description: _descriptionController.text,
        startDate: _startDate ?? DateTime.now(),
        endDate: _endDate,
        category: GoalCategory.vacation,
        status: GoalStatus.active,
      );

      ref.read(goalProvider.notifier).addGoal(newGoal);

      Navigator.pop(context);
    }
  }
}

```

![Simulator Screenshot - iPhone 15 - 2024-03-31 at 15 25 11](https://github.com/strapi/community-content/assets/46849299/a9331269-5a93-4388-94e8-8e1e05031c39)

* Craft the Edit Goal Page in goal_edit.dart:
    * This will be similar to goal_add.dart but for editing existing goals.
    * Ensure you pass the goal object to be edited to this page.

```


class GoalEditPage extends ConsumerStatefulWidget {
  final Goal goal;

  const GoalEditPage({Key? key, required this.goal}) : super(key: key);

  @override
  ConsumerState<GoalEditPage> createState() => _GoalEditFormPageState();
}

class _GoalEditFormPageState extends ConsumerState<GoalEditPage> {
  final _formKey = GlobalKey<FormState>();
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _descriptionController = TextEditingController();

  DateTime? _startDate;
  DateTime? _endDate;
  @override
  void initState() {
    super.initState();
    _nameController.text = widget.goal.name;
    _descriptionController.text = widget.goal.description;
    _startDate = widget.goal.startDate;
    _endDate = widget.goal.endDate;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: const Text('Edit Target')),
        body: Form(
            key: _formKey,
            child: SingleChildScrollView(
                padding: const EdgeInsets.all(16.0),
                child: Column(children: [
                  TextFormField(
                    controller: _nameController,
                    decoration: const InputDecoration(labelText: 'Goal Name'),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter a goal name';
                      }
                      return null;
                    },
                  ),
                  TextFormField(
                    controller: _descriptionController,
                    decoration: const InputDecoration(labelText: 'Description'),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Please enter a description';
                      }
                      return null;
                    },
                  ),
                  ListTile(
                    title: Text(
                        'Start Date: ${_startDate != null ? DateFormat('yyyy-MM-dd').format(_startDate!) : 'Select'}'),
                    trailing: const Icon(Icons.calendar_today),
                    onTap: () async {
                      final picked = await showDatePicker(
                        context: context,
                        initialDate: DateTime.now(),
                        firstDate: DateTime(2000),
                        lastDate: DateTime(2100),
                      );
                      if (picked != null && picked != _startDate) {
                        setState(() {
                          _startDate = picked;
                        });
                      }
                    },
                  ),
                  ListTile(
                    title: Text(
                        'End Date: ${_endDate != null ? DateFormat('yyyy-MM-dd').format(_endDate!) : 'Select'}'),
                    trailing: const Icon(Icons.calendar_today),
                    onTap: () async {
                      final picked = await showDatePicker(
                        context: context,
                        initialDate: DateTime.now(),
                        firstDate: DateTime(2000),
                        lastDate: DateTime(2100),
                      );
                      if (picked != null && picked != _endDate) {
                        setState(() {
                          _endDate = picked;
                        });
                      }
                    },
                  ),
                  const SizedBox(
                    height: 10,
                  ),
                  ElevatedButton(
                    onPressed: () {
                      if (_formKey.currentState!.validate()) {
                        Goal updatedGoal = Goal(
                          id: widget.goal.id,
                          name: _nameController.text,
                          description: _descriptionController.text,
                          startDate: _startDate!,
                          endDate: _endDate,
                          category: widget.goal.category,
                          status: widget.goal.status,
                        );

                        ref
                            .read(goalProvider.notifier)
                            .updateGoal(widget.goal.id, updatedGoal);

                        Navigator.pop(context);
                      }
                    },
                    child: const Text("Edit your goal"),
                  ),
                 const SizedBox(
                    height: 20,
                  ),
                  IconButton(
                    color: Theme.of(context).hintColor,
                    icon: Icon(
                      Icons.delete,
                      color: Theme.of(context).primaryColor,
                    ),
                    onPressed: () {
                      if (_formKey.currentState!.validate()) {
                        ref
                            .read(goalProvider.notifier)
                            .deleteGoal(widget.goal.id);

                        Navigator.pop(context);
                      }
                    },
                  )
                ]))));
  }
}
```

![Simulator Screenshot - iPhone 15 - 2024-04-01 at 11 20 43](https://github.com/strapi/community-content/assets/46849299/b76ae6cd-46f3-42a3-9600-766643f4cc2b)

### 3. Transition from Mock Data to Strapi and GraphQL:
If you haven't already, start by installing Strapi. You can choose to use Strapi in a project-specific manner or globally. For a new project, running npx create-strapi-app my-project --quickstart will set up a new Strapi project and start it with a SQLite database for quick development. 
It's generally a good idea to keep your backend and frontend projects in separate directories to maintain a clear separation of concerns. This separation helps manage dependencies, version control, and deployment processes more efficiently for each part of your application.

In this setup, both your Flutter project (personal_goals_app) and your Strapi project (strapi_goals_app) are located under the same parent directory (strapi_flutter), but they are kept in separate folders.

strapi_flutter/ 
│
├── personal_goals_app/       # Your Flutter project
│   ├── lib/
│   ├── android/
│   ├── ios/
│   └── ...
│
└── strapi_goals_app/         # Your Strapi project
    ├── api/
    ├── config/
    ├── extensions/
    └── ...

￼
Create Content Types in Strapi
Before you start fetching or submitting data from your Flutter app, you'll need to create the corresponding content types in Strapi that reflect the data structure of your app's goals.
* Log in to your Strapi admin panel.
PHOTOOO
* Navigate to the "Content-Types Builder" section.
* Create a new content type named Goal, for instance. Add fields that correspond to your Flutter app's goal model, such as name (Text), description (Rich Text), startDate and endDate (Date), category (Enumeration or Relation, depending on your setup), and status (Enumeration with values like active, completed, pending, drafted).
* Save the content type, and Strapi will automatically restart.  
https://pub.dev/packages/graphql_flutter


My last yaml file shape   dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  build_runner: ^2.4.9
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  intl: ^0.18.0 
  graphql_flutter: ^5.1.0
 
* Create Content Types: Using Strapi's admin panel, create the content types that match the goals in your Flutter app. For instance, a Goal content type with fields like name, description, startDate, endDate, category, and status.
* Set Permissions: In the "Settings" > "Users & Permissions plugin" > "Roles" section, set the public role (or whichever role you prefer) to have permissions to create, read, update, and delete entries for your content types. This step is crucial for allowing your Flutter app to interact with Strapi.
 Defining GraphQL Schemas
* Enable GraphQL: In Strapi v4, the GraphQL plugin is not installed by default. You need to add it by running npm run strapi install graphql in your Strapi project directory. Once installed, Strapi auto-generates the GraphQL schema based on your content types, which is accessible at /graphql on your Strapi server.
* Explore with GraphQL Playground: Use the built-in GraphQL Playground at http://localhost:1337/graphql (adjust the port if necessary) to explore the schemas and test queries and mutations.
Updating Your Flutter App to Use Strapi and GraphQL
* GraphQL Client Setup in Flutter: Use a GraphQL client package in your Flutter project, such as graphql_flutter, to make queries and mutations to your Strapi backend. Add the package to your pubspec.yaml and configure it with your Strapi server's GraphQL endpoint.
dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.0.0 # Check for the latest version
Fetch Data: Replace the mock data in your GoalNotifier with real data fetched from Strapi. Implement fetching logic inside your GoalNotifier methods. Use GraphQL queries to fetch goals and mutations to create, update, or delete goals.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @nazlicankurt ,

Thank you so much! I have added this to the review backlog. And yes please a Github repo would be best.

Please let me know if you have any questions.

**Comment by nazlicankurt** [comment]
Thank you @Theodore-Kelechukwu-Onyejiaku  

Here are both project repositories: https://github.com/nazlicankurt/strapi_flutter/


https://github.com/strapi/community-content/assets/46849299/e0f053fc-3e54-42cb-9687-9a8bdb07fbe9

I would like to add a video of the final version of the app. And I haven't encountered any problems. I don't have any questions for now, but if you have any questions, I am ready to answer them outside of my working hours.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @nazlicankurt,

Thank you very much. This is an intermediate article. For the videos, a GIF or a Youtube link would be great!

Please let me know if that works for you.

**Comment by nazlicankurt** [comment]
Hey @Theodore-Kelechukwu-Onyejiaku , I will add them for sure.

**Comment by nazlicankurt** [comment]
https://media.giphy.com/media/Mh1mgPFgBXtq8pBY0v/giphy.gif 
https://media.giphy.com/media/C4nwQZg9yKF9VywoX2/giphy.gif

Ready 💯  !

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @nazlicankurt !

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @nazlicankurt,

Thank you for your contribution to the "Write For The Community" program. I have reviewed your article after moving it to a Dropbox Paper file, as we use hackmd.io or Dropbox Paper for drafts. Excellent article by the way! 💪

Link to article: https://www.dropbox.com/scl/fi/3dxhh8gbpclli6ofap30q/Developing-a-Personal-Target-Tracking-Application-with-Flutter-Riverpod-and-Strapi-GraphQL.paper?rlkey=k35qm7zi2b7zos0p0hpi4yfoz&dl=0

I have left a few comments for you to review. Please feel free to reach out if you have any questions.

Following that, another reviewer will conduct the final review.

**Comment by nazlicankurt** [comment]
Hello!

Thanks for the info
I'm Nazlican Kurt. I added my profile photo.
I do not use twitter/X so i add my linkedin profile
https://www.linkedin.com/in/kurtnazlican/
My email : ***@***.***
my current position is Software Engineer

Best regards,
Nazlican


Theodore Kelechukwu Onyejiaku ***@***.***>, 24 Nis 2024 Çar,
13:00 tarihinde şunu yazdı:

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @nazlicankurt ,

One more thing. You forgot to provide me your bio on discord.
