### ISSUE TITLE
Building an ecommerce website with SvelteKit and Strapi CMS [SUBMIT] 

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#1265]
Hi 👋 i will like to work on the topic **Building an ecommerce website with SvelteKit and Strapi CMS**
Here is my outline for the topic. 
#### Creating the ecommerce application pages:
- Store home page
- User authentication page
- Cart list page
- User dashboard
- Adding payment method
#### Conclusion

**Comment by vcoisne** [comment]
Hello @popoolatopzy. Sorry about the late reply. We had some changes in the team. This seems like a good topic / outline. Please go ahead with the draft. Would it be possible to skip the Overview / installation part to go straight to the implementation (we already have many tutorial showing the installation steps, etc).

**Comment by vcoisne** [comment]
Ping @popoolatopzy are you still interested in writing this article ?

**Comment by popoolatopzy** [comment]
Sorry for the late reply. Yes, I have started working on the article. 
Thank you.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @popoolatopzy ,

I hope you are doing great! Thanks so much for your contributions and efforts so far. Please what is the status of this article or are you experiencing any difficulties writing it?

**Comment by popoolatopzy** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
I'm sorry for the delay. The article will be ready by the middle of next week.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @popoolatopzy ,

Thank you 😊

**Comment by popoolatopzy** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 

Sorry for the delay, here is the link to the article draft: https://hackmd.io/OPfjpqHTTpusCQuB92wZqA

**Comment by popoolatopzy** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku , I have not received any response from you concerning the article draft.

**Comment by popoolatopzy** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku and @vcoisne  I just want to check if you get the draft for the article.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @popoolatopzy,

So sorry for the delay. Thanks for your contribution to the "Write for the Community" program!

This looks good, but could you please provide a Github Repo for the complete code of your app?

**Comment by popoolatopzy** [comment]
here is the for the application Github Repo -https://github.com/popoolatopzy/my-ecommerce-app

**Comment by popoolatopzy** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku , any update on the draft.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @popoolatopzy,

Thank you for your contribution to the "Write for the Community" program! 💪

Your article is still in the review backlog. I will get back to you if I need anything. Thank you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @popoolatopzy, could you please ping me the following:

* Full Name
* Photo
* Bio
* Email 
* Twitter handle

Thank you for your contribution!
Thank you for

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Also, could you please provide me with edit access. Thank you.

**Comment by popoolatopzy** [comment]
Alright.
I will need your email address

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Ping me on discord please.

- Full Name
- Photo
- Bio
- Email
- Twitter handle

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi Please fix bugs and ensure your code runs smoothly. As discussed on Discord community channel, we might reject this draft if it persists. Please fix your code and push changes.

<img width="1440" alt="Screenshot 2024-08-27 at 1 03 21 PM" src="https://github.com/user-attachments/assets/1957b5aa-1a8e-4565-a349-0503df3fad8e">

Is there add to cart? If there is not, let the reader know.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @popoolatopzy ,

I left some corrections on your work. Please replace the image of the `UserInfo` collection. It shows `fullName` but you implemented `fullname` in your work.

Aslo, "Add to cart" is not also working. It takes me to a new page.

Please incorporate them. Thank you.

**Comment by popoolatopzy** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 

I have fixed the error and update the article

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @popoolatopzy ,

Thank you for your contribution. Great work by the way.

 Here are some suggestions:

* It would be great you add images to your contents. Images are sometimes better than long sentences. The `cartPage`, `loginPage`, and other pages could have been better using visuals. 

* Also, a GIF too showing the demo of your app would have been interesting.

Do not worry, I have done them for you. This is for future contents. Thank you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you for your contribution @popoolatopzy  🚀 

This has been published. So I will close it. Can't wait to see more of your contributions.
