### ISSUE TITLE
How to Build a Real Estate Management Application with Svelte and Strapi

### ISSUE THREAD

**Issue by Gunkev** [strapi/community-content#1269]
# How to Build a Real Estate Listing Application with Svelte and Strapi

This piece outlines the creation process for a real estate listing application utilizing Svelte for the frontend and Strapi as the Content Management System (CMS) backend. Svelte, a lightweight JavaScript framework, offers a performant and reactive user interface. Strapi, a headless CMS, provides a user-friendly interface for content management and a robust API for data retrieval.

**My content is**
For more information about the categories, [refer to this page](https://strapi.io/write-for-the-community).
- [ ] Tutorials

## Introduction
Introduction + demo
### Test Application

**What do you all think?**
💙 I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by vcoisne** [comment]
Hello @Gunkev this sounds like a good topic. Please go ahead with the draft. You can skip the following parts i.e Setting up Strapi, Create Collection Type, Add Content for the blog post to spend more time on more important topics such as authentication, maybe add pagination as well ?

**Comment by Gunkev** [comment]
Hi @vcoisne Alright. I will get started

**Comment by vcoisne** [comment]
@Gunkev awesome! when do you think you'll have a first draft ready ? Please note that we have recently updated our program guidelines https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md You can use ChatGPT or another genAI tool to write an outline but not most of the actual article. Authors will be banned from the program if we detect AI content.

**Comment by Gunkev** [comment]
Hi @vcoisne. The first draft will be ready in two weeks

**Comment by Gunkev** [comment]
Hi @vcoisne and @Theodore-Kelechukwu-Onyejiaku . Here is the draft for this article https://hackmd.io/@Gunkev/HJrHzftMA/edit

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Gunkev ,

Thanks for your amazing contribution to the "Write for the Community Program". Please could you provide a link that is viewable and with an edit access. The one you provided has a 403 error message.

Thank you!

**Comment by Gunkev** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku . This is the link https://hackmd.io/@Gunkev/HJrHzftMA/edit

**Comment by Gunkev** [comment]
Hey @Theodore-Kelechukwu-Onyejiaku there is already a link in the article to the demo in the introduction section

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @Gunkev 🙌

**Comment by Gunkev** [comment]
Hi Théodore,

Seems you reassigned this.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Gunkev , 

Yea, I had to assign it to you. I want to know who is assigned any topic. Thanks.

**Comment by Gunkev** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 

Please is this still under review?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Gunkev ,

We currently have lots of articles in the review backlog. When it is time, I will let you know. Thank you!
