### ISSUE TITLE
Guide on authenticating requests with the REST API

### ISSUE THREAD

**Issue by vcoisne** [strapi/community-content#1270]
**My Request**

How to send API tokens with Postman, comparison of API token vs. JWT, etc.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
## Introduction:
In web security, authentication stands as a cornerstone for safeguarding sensitive data. Two prevalent methods, API tokens and JSON Web Tokens (JWTs), play pivotal roles in this landscape. 
This guide provides the exploration of these mechanisms, offering insights into their generation, management, and implementation in Strapi and in building fortified web applications.

### 1. Understanding API Tokens:

- What are API tokens and their role in authenticating and authorizing API requests?
- How are API tokens typically generated and managed?
- Advantages of using API tokens for authentication.

### 2. The Basics of JSON Web Tokens (JWTs):

- What are JWTs and their structure (header, payload, signature)?
- How JWTs are used for authentication and authorization.
- Benefits of JWTs over traditional API tokens, such as statelessness and payload flexibility.

### 3. Pros and Cons

- Scenarios where one might be more suitable than the other.

### 4. Implementing API tokens in Strapi

- API token generation on Strapi.
- API token configuration in Strapi.
- Send API tokens with Postman.
- Demo using API token.

### 5. Sending JWTs with Postman:

- JWT generation in Strapi.
- JWT configurations in Strapi.
- Demo on how to work with JWTs in Postman, including how to obtain and include them in requests, including decoding and verifying them.

### 6. Best Practices for API Token and JWT Management:

- Tips for securely managing API tokens, such as rotating keys, using HTTPS, and implementing rate limiting.
- JWT Security Best Practices

### 7. Conclusion:

- Summarize the key points in the article.
- Encourage the readers to consider their specific use cases and security requirements when choosing between API tokens and JWTs.
- Emphasize the importance of secure API token and JWT management practices.

### 8. Additional Resources:

- Links to relevant documentation, tutorials, or tools for further learning about API token management and JWTs.

**Comment by vcoisne** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku great outline. Please go ahead with a draft. Please note that we have recently updated our program guidelines https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md You can use ChatGPT or another genAI tool to write an outline but not most of the actual article. Authors will be banned from the program if we detect AI content.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @vcoisne,

I hope you are doing great!

Here is my first draft to this content: https://www.dropbox.com/scl/fi/l3ehma6it4n8tjehckx7f/Guide-on-authenticating-requests-with-the-REST-API.paper?rlkey=o3eb7qlqpzryd8joqbgy4czzs&dl=0

Cheers

**Comment by pwizla** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku! I'm Pierre, Lead Technical Writer at Strapi. I reviewed your draft, updated some links to docs.strapi.io, and fixed some wordings ("collection" → "collection type") and the content looks good to me. Thank you very much! I will let people from the Strapi marketing team handle the next steps.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @pwizla,

Thanks for the review. I am glad you find it good. Great working with you. 

Cheers
