### ISSUE TITLE
[Partner Blog Post Submission] Building your site in Next JS using Strapi as a page builder  

### ISSUE THREAD

**Issue by codemoe** [strapi/community-content#1271]
We noticed there are different tutorials on how to achieve things on Strapi but had to work real hard on planning, trial and error and different approaches to take advantage of all that and actually apply it successfully on the frontend of a real site that currently gets over 2 million pageviews per month and keep the site scalable and workable so we thought that might be a good tutorial laying out some of the basics on structuring Strapi and Next to really take advantage of each one

Here are some of the ideas we want to share

Strapi can be a powerful platform as a page builder taking advantages of components and dynamic zones.

Matching that with Next JS capabilities as the frontend can deliver a top notch performing site 

Knowing how to structure the project, sections, components and networking is critical to achieve the best result possible

Planning the structure will allow for scalability and maintanability

Taking advantage of cache on either end or both

Tutorial with step by step example on how and where to create components, sections and structures mostly focused on the Next JS frontend

@PaulBratslavsky 

Thank you.

**Comment by PaulBratslavsky** [comment]
@codemoe this sounds great. Once you have a draft you can share here.  Once everything looks good we will schedule it.

**Comment by PaulBratslavsky** [comment]
@codemoe hope you are doing well. Just wanted to check in and see how is the progress going on the blog post.

**Comment by codemoe** [comment]
Hey @PaulBratslavsky just beat me to it but thanks for the follow up

Wasn't sure how to share it so here is the Google Docs Link with commenting permissions https://docs.google.com/document/d/1dSsz9Z20kitvSd30UnjYO4OxU5EywgpvMab0nBCrSUI/edit?usp=sharing

Please let me know your thoughts and comments

**Comment by PaulBratslavsky** [comment]
@codemoe I like the pattern, would it be possible to provide a repo for the example project.  Will be a great reference for folks wanting to look at the code who will read this post.

**Comment by PaulBratslavsky** [comment]
@codemoe I am currently getting the post ready to be published but upon further review when using the link that you provided [here](https://nextjs.org/docs/getting-started/installation) to install Next.js, it shows how to set up the Next.js project using typescript and app router, but your provided code seems to be using the `page` folder.

**Comment by codemoe** [comment]
@PaulBratslavsky thanks for the follow up

We haven't been able to create the sample repo but the team has it on their pipeline

Let me check on the link and understand how or why and get back to you

**Comment by PaulBratslavsky** [comment]
@codemoe thank you

**Comment by PaulBratslavsky** [comment]
@codemoe I am going to close this issue for now.  Please let me know when your team has the bandwidth to create the code example in an update project.
