### ISSUE TITLE
Integrating Strapi with Waku the new React framework 

### ISSUE THREAD

**Issue by Claradev32** [strapi/community-content#1273]
Waku is a React.js framework that has been getting massive traction from developers. This tutorial will cover how to combine the framework to build a minimalistic React application

This tutorial will cover:
- What's new in Strapi?
- Why use Waku and Strapi?
- Setup New Waku application
- Build UI interface
- Setup Model on Strapi
- Create App routes
- Server-Side data fetching
- Implementing State Management

**Comment by vcoisne** [comment]
Hi @Claradev32 thank you for suggesting this topic. At the moment, a tutorial on Waku is not a priority so I will close this issue. Feel free to propose other topics.
