### ISSUE TITLE
Building a Storefront with Strapi and Vue Storefront

### ISSUE THREAD

**Issue by icode247** [strapi/community-content#1274]
This tutorial will cover creating an online storefront using Strapi for content management and Vue Storefront for the front-end e-commerce interface.

## What are the key takeaways from your post?
In this tutorial, the reader will learn how to build a fully functional e-commerce application with minimal code using the Vue Storefront and Strapi. Below are the key takeaways:

- Why use Strapi and Vue Storefront
- Setting Up the Development Environment
- Configuring Strapi for E-commerce
- Integrating Strapi with Vue Storefront
- Developing the Storefront with Vue Storefront
- Adding Shopping Cart and Checkout Features
- User Authentication and Account Management

**Comment by vcoisne** [comment]
Hi @icode247 we don't currently have a good tutorial featuring Vue Storefront so it seems like a good option. Please go ahead with a draft

**Comment by icode247** [comment]
Hi @vcoisne @Theodore-Kelechukwu-Onyejiaku 
There is no plugin available for this integration. I need some help.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @icode247 ,

Could you please let me know the plugin you are mentioning? Thanks.

**Comment by icode247** [comment]
@Theodore-Kelechukwu-Onyejiaku 
I mean a plugin to integrate Strapi in Vue storefront

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @icode247 ,

So sorry you couldn't find any plugin to integrate VueFront and Strapi. Thanks for letting me know. I will get back to you shortly.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @icode247 ,

Since we don't have any plugin to integrate VueFront and Strapi, we will have to discontinue this article. Thanks for your time and contribution. It has been awesome! 💪
