### ISSUE TITLE
Strapi tutorial with Pinia, the intuitive store for Vue.js

### ISSUE THREAD

**Issue by vcoisne** [strapi/community-content#1278]
**My Request**

This is a request from [Linkedin](https://www.linkedin.com/feed/update/urn:li:activity:7173681209623994371/?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7173681209623994371%2C7173780977616334850%29&actorCompanyId=11251903). 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Marktawa** [comment]
Hey @vcoisne 

I'm interested in writing an article for this topic.

**Comment by vcoisne** [comment]
@Marktawa awesome! can you share an outline so that we can define the level of complexity / compensation ?

**Comment by Marktawa** [comment]
Sure @vcoisne 

# Build a Shopping Cart System using Vue, Pinia, and Strapi

## Outline

### Introduction

Create a shopping cart system using Vue.js for the frontend, Pinia for state management, and Strapi for backend services.

- Project Explanation
- Overview of technologies to be used: Vue.js, Pinia, and Strapi
- Importance of each technology in the project.

### Strapi Backend Setup

- Strapi project setup
- Define "Product" content type collection with name and price fields
- Populate "Product" collection with sample product data
- Expose Strapi Backend API

### Integrate Vue.js with Strapi

- Vue.js frontend setup
- Fetch product data from Strapi API
- Add Header, Cart components
- Display product listings on Vue app home page
- Create Cart page to display cart contents
- Add Styling

### Integrate Pinia with Vue frontend
- Add Pinia to Vue.js project
- Define global stores for products, cart management
- Define Pinia actions to fecth data from Strapi backend and list products on home page

### Manage Cart State with Pinia
- Define actions and mutations for adding,removing, and updating cart items
- Implement getters for total price and quantities
- Access cart data in Vue components using Pinia

### Conclusion
Recap of what was achieved, lessons learned, and next steps for further enhancements.

**Comment by vcoisne** [comment]
Hi @Marktawa this outline looks great and seems intermediate level of complexity. Please proceed with a draft.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Marktawa ,

Thank you for your contribution. Do you mind sharing the status of your draft? Meanwhile, would you be willing to use Strapi 5?

Please let me know.

**Comment by Marktawa** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku
 I am still working on the draft. Yes, I am willing to use Strapi 5.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you. Please let me know when it is ready. It is long overdue.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Marktawa ,

I hope you are doing great! Please, I will have to close this.
