### ISSUE TITLE
[SUBMIT] Adding advanced search to a Strapi and Next.js project with Algolia

### ISSUE THREAD

**Issue by Claradev32** [strapi/community-content#1281]
In this tutorial, the reader will learn how to add advanced search functionality to an e-commerce application built with Strapi and Next.js using Algolia Search.

This tutorial will cover:
- Introduction
   - Explain the importance of advanced search in web applications and introduce Strapi, Next.js, and Algolia.
Setup Environment
   - Detail the setup process for a Strapi backend and a Next.js frontend project.
- Integrating Algolia with Strapi:
   - Setting up an Algolia account and obtaining API keys.
   - Configuring Algolia in the Strapi project to index content.
- Building the Search Interface in Next.js
   - Installing Algolia search client in the Next.js project.
   - Creating search components to display results.
- Syncing Strapi Content with Algolia:

   - Automating the indexing process of Strapi content to Algolia.
   - Handling updates and deletions in Strapi content.
Enhancing Search Experience:

    - Implementing search features like faceting, filtering, and sorting.
    - Customizing the UI for a better user experience.
- Testing the integrated search functionality.
- Conclusion

**Comment by Claradev32** [comment]
@vcoisne

**Comment by vcoisne** [comment]
Hi @Claradev32 seems like a great article. It should be different / complementary from https://www.algolia.com/blog/engineering/add-autocomplete-search-to-your-strapi-cms/. Depending on the content this will either be beginner or intermediate. Please go ahead with a draft.

**Comment by Claradev32** [comment]
Hi @vcoisne 
This draft is ready. https://hackmd.io/@6lsL1T6ATQCTzLIepzyXHA/ByFQGPcC6

**Comment by vcoisne** [comment]
Thanks @Claradev32 we'll start reviewing asap.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Claradev32,

I hope you are doing great. I left a comment on your draft. Please check it out. Thank you.

**Comment by Claradev32** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 

I have addressed the comment.

Thank you.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Claradev32,

I have left some comments on your draft. Could you please address them? Thank you.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @Claradev32 ,

I will let you know if I have any questions or concerns.

**Comment by Claradev32** [comment]
@Theodore-Kelechukwu-Onyejiaku 
Please, the payment for the previous work is not yet processed?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Claradev32 ,

I am sorry to hear you haven't received payment. Please send me an email with the blog post and your payment invoice. 

Thank you.

**Comment by Claradev32** [comment]
@Theodore-Kelechukwu-Onyejiaku 
I sent you an email. Thanks

**Comment by Claradev32** [comment]
Hi @MattieBelt 
I have responded to all your comments and fixed the requested issues.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Claradev32,

Thank you, will look at it.

**Comment by MattieBelt** [comment]
Hi @Claradev32,

Thanks for updating the Article, I have looked at your changes and have added two more comments and 👎🏼 on the comments that haven't been picked up correctly. If you can, pls have another look at it:

I have summed up the last few points:
- I would recommend using the Strapi [env utility function](https://docs.strapi.io/dev-docs/configurations/environment/#casting-environment-variables) as it is the standard when dealing with configs in Strapi. ([comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=bf8b1d6b-94bf-474e-a4f0-d48ceca76751&utm_source=comment-card&utm_medium=icon))
- The ENV usage in Next.js results in a type issue ([comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=a7063d3c-6b5f-4fbe-9b7c-f0763899a35f&utm_source=comment-card&utm_medium=icon))
  pls fix accordingly: 
  ```ts
  const searchClient = algoliasearch(
    process.env.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID || '',
    process.env.NEXT_PUBLIC_ALGOLIA_API_KEY || ''
  );
  ```
- The Search component is not being exported ([comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=35989a43-72e3-415c-8ca5-69ec30cabdf3&utm_source=comment-card&utm_medium=icon)) ([new comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=c0c5636d-22d5-4a4d-bc1d-31c34b3a3921&utm_source=comment-card&utm_medium=icon))
- ENV file example consistency ([comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=f97b5f83-5d04-4b8b-9f8a-96bbcaf2a60d&utm_source=comment-card&utm_medium=icon))

Let me know if you have any other questions about my feedback.
Feel free to ping me in Discord

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thanks @MattieBelt for the reviews and your time 💪. You are amazing!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Claradev32 , thanks for updating your article and making the required changes. could you please let me know if you have implemented the last few points mentioned by @MattieBelt ?

Please let me also know if you have any challenges or concerns. Thanks.

**Comment by Claradev32** [comment]
Hi @MattieBelt, @Theodore-Kelechukwu-Onyejiaku 

I have addressed the last comments y

> Hi @Claradev32,
> 
> Thanks for updating the Article, I have looked at your changes and have added two more comments and 👎🏼 on the comments that haven't been picked up correctly. If you can, pls have another look at it:
> 
> I have summed up the last few points:
> 
> * I would recommend using the Strapi [env utility function](https://docs.strapi.io/dev-docs/configurations/environment/#casting-environment-variables) as it is the standard when dealing with configs in Strapi. ([comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=bf8b1d6b-94bf-474e-a4f0-d48ceca76751&utm_source=comment-card&utm_medium=icon))
> * The ENV usage in Next.js results in a type issue ([comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=a7063d3c-6b5f-4fbe-9b7c-f0763899a35f&utm_source=comment-card&utm_medium=icon))
>   pls fix accordingly:
>   ```ts
>   const searchClient = algoliasearch(
>     process.env.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID || '',
>     process.env.NEXT_PUBLIC_ALGOLIA_API_KEY || ''
>   );
>   ```
> * The Search component is not being exported ([comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=35989a43-72e3-415c-8ca5-69ec30cabdf3&utm_source=comment-card&utm_medium=icon)) ([new comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=c0c5636d-22d5-4a4d-bc1d-31c34b3a3921&utm_source=comment-card&utm_medium=icon))
> * ENV file example consistency ([comment](https://hackmd.io/X_RHQvY1SGK1_jDVl6OFNw?comment=f97b5f83-5d04-4b8b-9f8a-96bbcaf2a60d&utm_source=comment-card&utm_medium=icon))
> 
> Let me know if you have any other questions about my feedback. Feel free to ping me in Discord

Hi @MattieBelt, @Theodore-Kelechukwu-Onyejiaku 
I have addressed these comments.

Thanks

**Comment by MattieBelt** [comment]
Yes all looking good now 💪🏼

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Claradev32,

Thanks for incorporating the required changes and for your contributions, you are awesome! 💪

Your article should be live by Thursday. 🚀

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @MattieBelt ,

Thanks for your time and efforts. You are doing great! 🍻

**Comment by Claradev32** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
Any update on this payment?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Claradev32 ,

It seems you are yet to receive payment. I am sorry about that. Please email me concerning your payment related issues.  Thanks.
