### ISSUE TITLE
Intro to JWT and cookie storage

### ISSUE THREAD

**Issue by vcoisne** [strapi/community-content#1282]
**My Request**

A deep dive into JWT, API Tokens and why you should store your cookie as httpOnly cookie

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by TechMakanaki** [comment]
Hi @vcoisne can I work on this project?

**Comment by vcoisne** [comment]
@TechMakanaki sure go ahead, please note that this is a beginner topic that could be raised to intermediate depending on the draft.

**Comment by vcoisne** [comment]
@TechMakanaki outline looks good, please go ahead with the draft.

**Comment by TechMakanaki** [comment]
hello @vcoisne and @Theodore-Kelechukwu-Onyejiaku, i am done with the draft to this article. Below is the link to review;

https://hackmd.io/@tibson/SJU5LCQJR

thank you and I'm awaiting your response

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @TechMakanaki ,

Sorry about not letting you know. Your article is under review. Thank you!

**Comment by TechMakanaki** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku,

Code implementation was not included in the outline but I will definitely work on that.
Thank you.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @TechMakanaki .

**Comment by TechMakanaki** [comment]
hi @Theodore-Kelechukwu-Onyejiaku 
kindly check the draft again, necessary and required actions have been added to the article.

thank and awaiting for your response.

**Comment by TechMakanaki** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku, 
Please kindly confirm the correction made to the draft again. I have done all the necessary bits.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you!

I will check it out and get back to you.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @TechMakanaki,

I have left some comments in your draft. Please do ensure to go through your draft before submitting as there were many typos and not properly written words everywhere. 

When you are done incorporating them, please let me know. Thank you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @TechMakanaki ,

I hope you are doing great. Just wanted to remind you about the message above. Thanks.

**Comment by TechMakanaki** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku .

I have done all the necessary corrections, kindly check the draft.
Thank you.

**Comment by TechMakanaki** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku.

I tried uploading a clear GIF but Hackmd did not allow more than 1m file.

What should I do?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Sorry to hear about that @TechMakanaki. Could you please share it with me here on Github? Thanks.

**Comment by TechMakanaki** [comment]
Okay @Theodore-Kelechukwu-Onyejiaku .
Below is the file attachment:
![strapi 2 - Made with Clipchamp](https://github.com/strapi/community-content/assets/53910979/841fb8b6-9ebb-4380-82a1-12ea8548f1a0)

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @TechMakanaki !

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @TechMakanaki ,

Meanwhile, could you please ping me your full name, photo, bio, job title, email and twitter handle on discord or email if you are a new writer ?

Else, could you share your full name with me? 

Thank you!

**Comment by TechMakanaki** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku ,
I have been writing for strapi before.
Name: Onisile Tobi

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @TechMakanaki .

**Comment by TechMakanaki** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku and @vcoisne ,
Please what form I'm to use for generating invoice in order to submit my payment form.

Thank you.

**Comment by TechMakanaki** [comment]
Hello @vcoisne and @Theodore-Kelechukwu-Onyejiaku ,

I have sent in my invoice via the form.
