### ISSUE TITLE
[Request New Content] How to use get different type of API response with TypeScript unions?

### ISSUE THREAD

**Issue by vcoisne** [strapi/community-content#1283]
**My Request**

How to create TypeScript base type that you can extend and then unions for multiple types?

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by vcoisne** [comment]
Closing as we will cover this topic here https://github.com/strapi/community-content/issues/1284

**Comment by Alpheus-godswill1** [comment]
Ohh @vcoisne this is a nice rephrase I could still work with this, should I ?
