### ISSUE TITLE
API keys: The ultimate guide.

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#1285]
Outline:
What Are API Keys?
Why Use API Keys?
Types of API Keys
When to Use API Keys
Securing API Keys
This includes: Demonstrating Encryption of API Keys and Tokenization Methods
API Key Authentication Methods
this include: JWT Authentication, OAuth Authentication, and HMAC Authentication
 API Key Management
we'll discuss on Key Generation, Monitoring and Logging, Revocation and Expiration
API Key Best Practices 
Conclusion

**Comment by vcoisne** [comment]
Hi @lucky4242 this seems like a good beginner topic. Please go ahead with the draft.

**Comment by lucky4242** [comment]
Hi @vcoisne and @Theodore-Kelechukwu-Onyejiaku.
I am done with this article and here is the link:

https://www.dropbox.com/scl/fi/ryw4xl35vv95miarkdnh9/API-keys_-The-ultimate-guide.paper?rlkey=1kwit7glom1w3599k7siua1j2&dl=0

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @lucky4242 ,

Thank you for your contribution. I will add it to review. Thank you!

**Comment by lucky4242** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
What is the update on this article?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @lucky4242 ,

It is in the review backlog. When it is time, we will publish it. Thank you for your contribution! 💪

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @lucky4242 ,

Thanks for your contribution! 

However, your content is 64% AI generated and 22.3% plagiarized. At this point in time it's doubtful if we will accept future work of yours.
