### ISSUE TITLE
[TOPIC] How to make Learning Management System platform for school using Next.js and Strapi

### ISSUE THREAD

**Issue by maskho** [strapi/community-content#129]
I would like to thanks if someone can make a tutorial about how to make Learning Management System platform for school using Next.js and Strapi

**Comment by ghoshnirmalya** [comment]
I can pick this one up. It'd be good if I can get a list of features that is necessary for building a Learning Management System platform for school.

**Comment by malgamves** [comment]
Do you have a short list of features that would make up such an application @ghoshnirmalya ?

**Comment by malgamves** [comment]
That sounds great for a start. Think you can an app built with these and probably write about it?

**Comment by ghoshnirmalya** [comment]
> That sounds great for a start. Think you can an app built with these and probably write about it?

Sure. I'll do that. I'll try to wrap it up by 6th September.

**Comment by malgamves** [comment]
Sounds great! You're doing amazing @ghoshnirmalya thank you 👏

**Comment by Mcastres** [comment]
Hey @ghoshnirmalya, just checking if there is any news about this :)

**Comment by ghoshnirmalya** [comment]
@Mcastres I'm waiting for [this article](https://github.com/strapi/community-content/issues/123) to be published first and then work on Learning Management System.

**Comment by Mcastres** [comment]
Got it!

**Comment by ShadaW11** [comment]
@ghoshnirmalya Heyy been a while, any update on this topic?
