### ISSUE TITLE
Build a Progressive Web App with NextJs and Strapi

### ISSUE THREAD

**Issue by Theodore-Kelechukwu-Onyejiaku** [strapi/community-content#1294]
**My Request**

How to build a NextJS PWA powered by Strapi
Implement features like push notification, add to home screen, splash screen, etc.
Build a minimalistic application
Serve data using Strapi

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you

**Comment by lucky4242** [comment]
Hi @Theodore
I would love to work on this topic

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @lucky4242 , please proceed. Thanks!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @lucky4242 ,

Thanks for showing interest in writing this. However, you can't continue with this article. You already have two articles that are either "in progress" or "in review" in the publicaction queue. I have now changed the label to "looking for author".
Thank you.

**Comment by Finniki** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku can I pick up the topic then? 
I can work within the same outline

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Finniki ,

Thanks for your interest in writing this article. Could you please share a better outline that would incorporate what was requested for? Thanks.

**Comment by Finniki** [comment]
Here you go @Theodore-Kelechukwu-Onyejiaku 

Build a Progressive Web App with NextJs and Strapi (Recipe Book)

1. Introduction
2. Setting Up the Project
3. Setting Up Strapi Backend
        Scaffold the Strapi backend
        Configure content types and API endpoints.
4. Creating a Recipe Collection
        Define a simple recipe content structure (title, ingredients, instructions).
        Add a few sample recipes using the Strapi admin panel.
5. Building the Next.js Frontend
        Fetch recipe data from the Strapi backend using API endpoints.
        Display recipes in a clean, minimalistic UI.
        Implement responsive design for mobile and desktop.
6. PWA Features Implementation
        Add to Home Screen
        Splash Screen
        Set up push notification subscriptions using a service worker
7. Testing and Deployment
        Test the PWA features locally.
        Deploy the Strapi backend and Next.js frontend to a hosting service (e.g., Vercel, Netlify).
8. Conclusion

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Finniki, 

This looks good. Please go ahead. Thank you!

**Comment by Finniki** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
Just reaching out with an update as the article timeline has exceeded what I anticipated. 
I've not had a lot of time to work on it aside from the weekends. I should have it wrapped up and ready for a revision by this weekend. I hope that's okay.
Thanks!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
That is fine @Finniki ,

Thank you.

**Comment by Finniki** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku !

Thanks for the beep. I finished working on the article but it totally fell off my radar. I thought I had sent it in for a review. 

Here’s the link - https://hackmd.io/@cqg6wK4tQEWHiizBEJmu1w/Byf8NOiyR/edit

Please accept my apologies for the delay. Looking forward to feedback!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Finniki,

Thanks for your contribution and effort into creating this content. Unfortunately, it is not up to par with what we have requested. Please feel free to publish this on your blog or elsewhere.

**Comment by lucky4242** [comment]
HI @Theodore-Kelechukwu-Onyejiaku 
i know u have closed it as completed but can I work on it?
