### ISSUE TITLE
[SUBMIT] Introduction to Node.js: A Comprehensive Guide for Beginners

### ISSUE THREAD

**Issue by king-lox2** [strapi/community-content#1295]
**Introduction to Node.js:  A Comprehensive Guide for Beginners**

 
My article focuses on a detailed briefing of what a Beginner developer should know about Node.js in other to guide them in web development.

### Content Brief: Introduction to Node.js:  A Comprehensive Guide for Beginners

- Target audience: Beginners 

- Keywords: JavaScript, Node.js

- Content objective: This article focuses more on aiding learners to learn and understand Node.js. 

 Outline :

1. What is Node.js?

2. Step-by-step instructions for installing Node.js.

3. Writing your first Node.js Application.

Conclusion

**Comment by vcoisne** [comment]
Hi @king-lox2 this is a very generic / entry level topic that we don't want to prioritize at this time. Please feel free to submit new ideas or apply to one of the Request for content from the Strapi team.

**Comment by king-lox2** [comment]
please @vcoisne  how do I request content from the Strapi team?
