### ISSUE TITLE
[REQUEST NEW CONTENT] Tutorial: Request Strapi's REST API behind a Content Delivery Network (CDN) 

### ISSUE THREAD

**Issue by pwizla** [strapi/community-content#1300]
Hello 👋 

We'd like to have a tutorial on how to request Strapi's REST API behind a Content Delivery Network (CDN).
This should notably include how to request media assets through AWS S3 and CloudFront.

- Target audience: Advanced users who already know how to use Strapi
- Keywords: REST API, CDN, AWS, CloudFront

**Comment by simioluwatomi** [comment]
Hello @pwizla @Theodore-Kelechukwu-Onyejiaku 

I'd be very much interested in writing this article

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @simioluwatomi ,

I am very glad you are interested in writing this article. As for the clarification, @pwizla will attend to you shortly. 

Thank you very much!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @pwizla.

Hi @simioluwatomi , thanks for your patience. Please you can proceed. Thank you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @simioluwatomi ,

I hope you are doing great! Thanks for choosing to contribute to the "Write for the Community" program! Please I would love to know the status of this article. 

Cheers.

**Comment by simioluwatomi** [comment]
> Hi @simioluwatomi ,
> 
> I hope you are doing great! Thanks for choosing to contribute to the "Write for the Community" program! Please I would love to know the status of this article.
> 
> Cheers.

Hello, I've started working on the article but got sidelined with things from work.

I should be able to have the first draft complete by Friday, May 31 though

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @simioluwatomi ,

Thank you! Your contribution is very much appreciated 💪

**Comment by pwizla** [comment]
Hello! Just wanted to check if the first draft is complete and if yes, when could this blog post be out?
@Theodore-Kelechukwu-Onyejiaku please let me know when the article is out and I'll cross-reference it in our official docs at docs.strapi.io 🙂

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @pwizla, thanks for the notification. Unfortunately, we don't have the completed draft at the moment.

Hi @simioluwatomi , I trust you are doing great. Could you please update me on the status of this article. Thank you!

**Comment by simioluwatomi** [comment]
Please re-assign this to someone else. I'm swamped at work at the moment and can't dedicate enough time to finish this

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @simioluwatomi ,

Thanks for letting me know.

**Comment by pwizla** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku.
I've just seen this issue was closed as marked as completed, but it's not. 
Should we re-open a similar issue with the same topic and look for other authors? This content gap still needs to be filled in for Docs team.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @pwizla ,

I am so sorry I forgot to inform you. I have assigned this to another writer (one of our top writers). Also, if the current writer cannot deliver the content soon, then I will have no choice but to do it myself.
