### ISSUE TITLE
[SUBMIT] Tutorial on Unit Testing (Jest, Supertest)

### ISSUE THREAD

**Issue by pwizla** [strapi/community-content#1301]
Hello 👋 
We'd like to have a tutorial on how to do unit testing with Strapi. It should cover the following topics:
- Setting up a testing environment for Strapi with Jest and Supertest
- Testing a basic Strapi endpoint controller (such as a reaching a `/hello` route that simply returns "Hello!" with its context
- Testing a more advanced controller such as a controller that would authenticate a user or return users data based on Authentication headers

* Target audience: Advanced users who already know how to use Strapi but are not familiar with testing frameworks
* Keywords: Testing, Unit testing, Jest, Supertest, Controllers

**Comment by Eunit99** [comment]
Hello @pwizla , I would like to work on this piece.

**Comment by pwizla** [comment]
Oh, I missed this one, @Theodore-Kelechukwu-Onyejiaku! Thank you.

We would need an update for Strapi 5, but for now, the current goal was to have this ready for v4, and the topic is already indeed covered by the blog post you mentioned.

What shall we do? Close this issue and create a new "Request update on outdated content" one once Strapi 5 stable is out?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thanks for the suggestion @pwizla, will do so once Strapi v5 stable is out.
