### ISSUE TITLE
[REQUEST NEW CONTENT] Monitoring and Logging - Top Services

### ISSUE THREAD

**Issue by Theodore-Kelechukwu-Onyejiaku** [strapi/community-content#1308]
Hello 👋,

We would like to have an article that gives a detailed exploration of the top Monitoring & Logging services available in the market today. A good list of them is fine.

The guide will delve into each service's features, capabilities, integrations, and use cases, providing readers with valuable insights to make informed decisions about their monitoring and logging needs.

### Content Brief: 
- Target audience: Developers, DevOps engineers, system administrators, and businesses looking to optimize their infrastructure monitoring and logging practices.
- Keywords: Monitoring services, Logging services

### Community vote
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Queen-esther01** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku I would love to write about this. Monitoring and logging are things I enjoy working on.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you Esther for your interest. Please go ahead. Thank you!

**Comment by Queen-esther01** [comment]
Is there a writing guide Strapi uses? How do I share my draft? @Theodore-Kelechukwu-Onyejiaku

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Queen-esther01 ,

I hope you are doing great! Thanks for your contribution to the "Write for the Community"  Program!

Please, may I know the status of this article?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Queen-esther01 ,

I hope you are doing great!

I just want to let you know that I will be handing this over to another writer on Monday. Is that ok with you?

**Comment by Queen-esther01** [comment]
@Theodore-Kelechukwu-Onyejiaku That's fine, I'm happy to share some work I've done if they like.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Queen-esther01 ,

Since you are already working on it. Do you think you can complete it any time soon. If so, may I know when please.
