### ISSUE TITLE
[SUBMIT]Build A Customer Review and Rating Page Using Strapi and Solid.js

### ISSUE THREAD

**Issue by oyedeletemitope** [strapi/community-content#1313]
### Content Brief: 
In this tutorial, I'll walk the readers through building a customer review and rating page, where customers can provide their reviews and also give a star rating. We'll explore how to integrate Strapi CMS with Solid.js, to create this.

Outline

### Introduction
- Brief overview of the article's purpose: to guide the reader through building a customer rating and review system using Strapi as the backend and Solid.js for the frontend.
- Highlight the benefits of using Strapi and Solid.js for such a system, including Strapi's ease of use for managing content and Solid.js's reactive UI capabilities.

### Prerequisites
- Basic knowledge of JavaScript, Node.js, and the command line.
- Familiarity with Strapi and Solid.js would be beneficial but not strictly necessary.

### Setting Up Strapi
- Installing Strapi
- Creating a New Strapi Project: Guide the reader through creating a new Strapi project and setting up the admin user.
- Configuring Content Types.

### Setting Up Solid.js
- Introduction to Solid.js: Briefly introduce Solid.js as a reactive UI library.
- Setting Up a New Solid.js Project: Provide instructions on setting up a new Solid.js project.

### Building the Frontend with Solid.js
- Fetching the rating and reviews from Strapi.
- Creating a rating and review form.
- Displaying reviews.

### Conclusion

**My content is**
For more informations about the categories, [refer to this page](https://strapi.io/write-for-the-community).
- [x] Tutorials
- [ ] Best practices
- [ ] Use cases & case studies

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oyedeletemitope ,

This is great! Please proceed. Thank you.

**Comment by oyedeletemitope** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku , 

Here is the link to the draft :

https://hackmd.io/@koded001/B1l-hVjgC/edit

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Great! Thank you @oyedeletemitope!

I will add it to the review backlog.

**Comment by oyedeletemitope** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku. Am I free to create new issues or wait till it gets published before submitting another pitch?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oyedeletemitope , 

Yes you can create a new issue. The maximum at this time is two, whether in progress or in review. I hope you understand.

Thank you!

**Comment by oyedeletemitope** [comment]
Thank you! @Theodore-Kelechukwu-Onyejiaku

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oyedeletemitope ,

Thanks for your contribution! 💪

I will be publishing this today. Unfortunately, I will have to tag this as a beginner article. It is pretty straightforward and basic and nothing much complex.

I hope you understand.
