### ISSUE TITLE
Web Api security hack : Setting up rate limiters

### ISSUE THREAD

**Issue by oluwatobi2001** [strapi/community-content#1316]
**My resource**

**My content is**
For more informations about the categories, [refer to this page](https://strapi.io/write-for-the-community).
- [○ ] Tutorials
- [ ] Best practices
- [ ] Use cases & case studies

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

This looks good! Could you please provide an outline. Thank you.

**Comment by oluwatobi2001** [comment]
Good day editor,  I wrote the outline within the issue
.Thanks

**Comment by oluwatobi2001** [comment]
I. Introduction to Web API Security
   A. Importance of securing Web APIs
   B. Overview of common security threats

II. Understanding Rate Limiting
   A. Definition and purpose
   B. Benefits of implementing rate limiters

III. Setting Up Rate Limiters
   A. Choosing the appropriate rate limiting strategy
   B. Selecting the right tools and technologies
   C. Configuring rate limits for different endpoints
   D. Handling rate limit exceeded scenarios

IV. Best Practices for Rate Limiting
   A. Implementing sliding window algorithms
   B. Setting reasonable rate limits based on API usage patterns
   C. Considering strategies for handling burst requests
   D. Monitoring and adjusting rate limits over time

V. Advanced Techniques for Rate Limiting
   A. Implementing token buckets and leaky bucket algorithms
   B. Combining rate limiting with other security measures like
authentication and authorization
   C. Exploring cloud-based solutions for scalable rate limiting

VI. Testing and Monitoring
   A. Strategies for testing rate limiting implementation
   B. Monitoring tools and metrics to track rate limiting performance
   C. Handling and analyzing rate limit-related incidents

VII. Conclusion
    A. Recap of the importance of rate limiting in Web API security
    B. Final considerations and next steps for securing Web APIs

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

Thanks for the outline. Please are you going to include codes and a github repo we can use to test the technical aspects of this article?

Please let me know, thank you!

**Comment by oluwatobi2001** [comment]
Yes we will.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

That is great. Please go ahead. Thank you.

**Comment by oluwatobi2001** [comment]
Thank you. What's the time limit?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

Thank you for sharing your article idea. I understand that this article is about rate limiting. It would be great if your code example and GitHub code demonstrate rate limiting in Strapi.

Kindly let me know if you plan on incorporating this. Thanks.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001,

I would appreciate it if you could. Thank you!

**Comment by oluwatobi2001** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku , i have updated the hackmd documents  with the relevant code examples and the github repo. I await your feedback.  Thank you

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @oluwatobi2001! I will definitely check it out.

**Comment by oluwatobi2001** [comment]
Hi Sir. Please how many days does it take to get a article reviewed? And
can i apply for other ones while waiting for the feedback?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

Your article is in the review backlog. I will let you know if we need anything from you. 

Cheers.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

Thanks for your contribution! This is supposed to be an intermediate article, so I have some suggestions to make it better. Could you please provide more information about rate limiting by doing the following:

* Real life use cases of rate limiting
* How Popular Social Media sites like Twitter and co add rate limiting.
* How does Rate Limiting works.
* For the Project Demo, It would be great if you precisely provide a step-by-step guide. This should be a real-world project scenario that involves Rate Limiting. You could build it also add a frontend technology or use Postman. The goal is to make this a rich content.

Please let me know what you think.

**Comment by oluwatobi2001** [comment]
GOOD DAY SIR. i USED POSTMAN  AND I EVEN ATTACHED IMAGES THAT INDICATED A
LIVE DEMO DONE

**Comment by oluwatobi2001** [comment]
I WOULD INCLUDE THE SUGGESTIONS MADE IN THE DRAFT AND GET BACK TO YOU AS
SOON AS POSSIBLE. THANK  YOU

**Comment by oluwatobi2001** [comment]
Good day Sir. i have added the suggestions made by you. I await your
feedback Sir.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001,

Your time and effort is very well appreciated. I have left a comment on your draft. 

I could not find this heading in your draft.
* How Popular Social Media sites like Twitter and co add rate limiting.

**Comment by oluwatobi2001** [comment]
I feel both real life use cases of rate  limiting and how popular sites use
rate limiting  are quite similar. I might have to replace the section
header on where i discussed  Twitter's adoption of rate limiting and its
usage. Thank you

**Comment by oluwatobi2001** [comment]
Thank you Sir. The comment has been addressed

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

I hope you are doing great! Please you haven't incorporated the changes I asked for. Please incorporate them so we don't go back and forth. 

Thank you.

**Comment by oluwatobi2001** [comment]
Good day Sir. I have addressed the 2 comments you raised. I am currently
addressing the last comment you made on the real life use cases. It would
be on the article  before the end of the day. Thank you.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

Thank you so much. I will review it soon. Meanwhile, I observed your images are quite blurry. Please do well to fix them. 


Please do well to join our Discord community channel if you haven't, https://discord.gg/invite/strapi. 😊

**Comment by oluwatobi2001** [comment]
Noted with thanks.

**Comment by oluwatobi2001** [comment]
Sorry please i'm yet to get any additional comments on the work done so far
and any plans for it to be published

**Comment by oluwatobi2001** [comment]
Hello, please any response so far?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

I just took a look at your article once more. Could you please ping me the following on Discord:

* Full Name
* Photo
* Bio
* Job Title
* Twitter Handle

Thank you for your contribution once again! If I need any other thing from you, I will let you know! 💪

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

I left some comments in your work. Please review and implement. Thank you for your patience and contribution to the "Write for the Community" program!

**Comment by oluwatobi2001** [comment]
Good day . I have fixed all comments. Thank you

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @oluwatobi2001!

**Comment by oluwatobi2001** [comment]
Thank you for the response. Is there any other issue that needs to be
rectified as regarding the article?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

There is none for now. I will let you know if I need any. Thank you for your contribution to the "Write for the Community" program.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

After several forth and back on this, especially on discord, I will love to assign this to another author. You seem not to proceed and cooperate with the multiple suggestions and reviews.

**Comment by oluwatobi2001** [comment]
I will rectify any ongoing complaints this week. I have issues with electricity and this has affected my ability to work on the errors you pointed out.

**Comment by oluwatobi2001** [comment]
Good day sir, I have updated the doc. Thank you

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @oluwatobi2001. I will perform a final review.

Meanwhile, next time, if you want to share your project structure, you can use File Tree to Text Generator VS Code extension or any other tool, rather than a photo of your project structure.

**Comment by oluwatobi2001** [comment]
Thank you sir. Noted with thanks.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Due to so many back and forth, I will have to discontinue and re-assign this work. Thank you.

**Comment by oluwatobi2001** [comment]
Good day sir. I will revert with the complete article today. My apologies
for the delay so far. I had issues figuring out the documentation.

**Comment by oluwatobi2001** [comment]
***@***.***/ByLYUNbxR here is the link to the final draft

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

We have reassigned this content.

**Comment by oluwatobi2001** [comment]
No problem. Thanks.
