### ISSUE TITLE
[Partner Blog Post Submission] - A low-code/no-code approach to strapi enablement

### ISSUE THREAD

**Issue by rrubio** [strapi/community-content#1317]
**My Request**

- Tedix
- A low-code/no-code approach to strapi enablement
- With the advancement of no-code/low-solutions and the rapid development of AI, Strapi is in a unique situation to rapidly integrate and enable solutions of the future via it's API driven strategy and built-in security.

This blog post dives into how Strapi, a powerful yet user-friendly headless CMS, empowers even non-technical teams to build robust business solutions.

**Here's what you'll learn:**

Strapi's Superpower: Effortless integration with popular tools like Typeform and Make.com.
No Coding Headaches: Automate workflows and user registration using webhooks and APIs (without writing a single line of code!).
Rapid Development: See your ideas come to life faster than ever before with Strapi's intuitive interface.

**Get ready to:**

Simplify complex tasks and streamline your operations.
Empower your entire team to contribute to building solutions.
Focus on innovation while Strapi handles the technical heavy lifting.

This blog post is a guide to unlocking the potential of Strapi and taking businesses to the next level, even with limited coding expertise!

@PaulBratslavsky

**Comment by PaulBratslavsky** [comment]
That sounds great.  You can start working on it @rrubio

**Comment by rrubio** [comment]
@PaulBratslavsky  just so that i'm clear on the next steps. Am I posting all my content in here on git?

**Comment by rrubio** [comment]
To get started with typeform, we'll need to register first, once registered select personal, and start from scratch to create our registration form - 

```
https://www.typeform.com/signup/
```

<img width="1192" alt="image" src="https://github.com/strapi/community-content/assets/4221574/73fc473a-582e-492e-a158-753d01c0e395">

<img width="1335" alt="image" src="https://github.com/strapi/community-content/assets/4221574/8b46db2b-1a6c-4f51-934e-f2e4c4b628a1">

Next give your form a "Name" and select "Registration form" - 

<img width="1212" alt="image" src="https://github.com/strapi/community-content/assets/4221574/5ff0921e-5c45-4cb2-8625-b6607b8da971">

Once you've created the form proceed to add our registration fields on the top left and corner click on the "+" sign and select "Short Text" - 

<img width="1770" alt="image" src="https://github.com/strapi/community-content/assets/4221574/184663e3-826b-40f5-b119-2b3eb4dc8803">

**Comment by rrubio** [comment]
@PaulBratslavsky hope you're well! when you get a minute to view my first draft and provide any feedback or recommendations, I'd really appreciate it.

**Comment by PaulBratslavsky** [comment]
@rrubio I am getting the post ready to be published.

Can you send some info for your author's bio? paul.bratslavsky@strapi.io
- name
- company and position
- image
- social
  --LinkedIn
  --Twitter 
  etc
  
  Thank you

**Comment by rrubio** [comment]
Great to hear! @PaulBratslavsky see details below.

name - Rodrigo Rubio

company and position - Tedix | Head of Digital 

image
![tedix-rodrigo-profile-pic-colour](https://github.com/strapi/community-content/assets/4221574/470a2dc7-c359-49e6-9a0e-12f85eeddc6e)

social
-- https://www.linkedin.com/in/rodrigoarubio18/

--[Twitter ](https://twitter.com/RodrigoARubio18)

-- https://www.youtube.com/@TedixAIDigitalConsulting

**Comment by PaulBratslavsky** [comment]
@rrubio I tried downloading the demo video but was unsuccessful, can you send me the file to my email paul.bratslavsky@strapi.io so I can embed it in the post.

**Comment by rrubio** [comment]
@PaulBratslavsky  all good, you can download from here - https://tedix-my.sharepoint.com/:v:/g/personal/rodrigo_rubio_tedix_ai/EZnEVV3ZODRFmRtQV4apB5QBV44qDErV1cS125cKVgFsuw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=BJXVoY

**Comment by PaulBratslavsky** [comment]
@rrubio hank you, we have published your article. https://strapi.io/blog/a-low-code-no-code-approach-to-strapi-enablement
