### ISSUE TITLE
API development best practices: Integrating monitoring and logging tools 

### ISSUE THREAD

**Issue by oluwatobi2001** [strapi/community-content#1322]
I would love to add this article idea to my todos

**Comment by ExitoLab** [comment]
Hello, I am interested in working on this article as well

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

Please use the issue template to submit an article proposal. I will have to close this one. Thanks.

**Comment by ExitoLab** [comment]
Sure @oluwatobi2001
