### ISSUE TITLE
How to Send Strapi Content Updates to Discord via Webhooks

### ISSUE THREAD

**Issue by vicradon** [strapi/community-content#1329]
### What is your article idea?

This article goes through the process of sending updates that occur on a Strapi instance to a Discord channel using Webhooks. It goes over the setup of a Discord channel for Webhooks and how content that is sent to the channel can be customized to suit different presentation requirements.

## Outline

- Introduction to webhooks
- How Strapi handles webhooks
- How Discord receives Webhook updates
- How to setup a Discord channel to receive Webhooks
- How to Customize Webhooks from Strapi going to Discord
- Summary and conclusion

### What are the objectives of your article?

To teach the reader how to set up a Discord channel to receive updates from a Strapi instance via webhooks.

### What is your expertise as a developer or writer?

Advance

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @vicradon ,

Thanks for your article idea. At the moment, we already have enough contents related to Strapi webhook.

I will close this issue. Please feel free to submit any article idea in the future. Thank you.
