### ISSUE TITLE
Deploy Strapi on shared hosting using cPanel 

### ISSUE THREAD

**Issue by monacodelisa** [strapi/community-content#1330]
### What is your article idea?

I would like to provide current and tested guide for deploying Strapi to a shared hosting environment, I would like to cover all missing information such as: 
A bit of theory first:
- Identifying what option is available in the cPanel
- The different options of deployment trough cPanel
- I will go over missing cPanel features - why they are missing and why they matter 
- Selecting the preferred option supported in ClaudLinux

A step by step guide in which I will put emphasis on:
- Setting up the database and establishing a remote connection (PostgreSQL pgAdmin)
- I will go over common issues that may arise and how to troubleshoot them (they are only a couple)
- A next step after the database is set and the Strapi app is running I will also briefly go over how to transfer the content from the local Strapi app to the deployed Strapi app - or I will link the official documentation so that the process can be complete.

I do have an intention of making a YouTube video to go along with the article - if that is supported / allowed. I already have a some tutorials on my YouTube channel including NodeJS workflows. 

Of course this is my initial idea, small details may be added or removed where necessary for clarity.
If appropriate I may cover the other DB integrations too. 

### What are the objectives of your article?

The point of my article would not be to promote cPanel integration, I do not enjoy working with it, however it is still widely used. I would like for readers to have a complete guide including all the steps of the process and not having to look trough different sources that may or may not be helpful. I would like to put emphasis on database connection & integration since I feel that has not been covered well enough when it comes to cPanel integration. 

@pwizla 

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by pwizla** [comment]
@Theodore-Kelechukwu-Onyejiaku The author proposes an article on a topic I discussed with her, following a [`strapi/documentation` request](https://github.com/strapi/documentation/issues/2073). We can move forward with this article when you're ready, and I'll review it :) Please let me know if I can be of any other help 🙂

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @pwizla,

This is fantastic! Appreciate the update. Thank you @monacodelisa , glad to have you on board for the "Write for the Community" program! We appreciate your willingness to share your expertise.

Please, feel free to start working on your draft using HackMd or Dropbox Paper. Thank you.

**Comment by monacodelisa** [comment]
@Theodore-Kelechukwu-Onyejiaku thank you very much I am going to start working on the draft :)

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @monacodelisa ,

I hope you are doing great! Please may I know the status of this article.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @monacodelisa,

I hope you are doing great!

I just want to let you know that I will be handing this over to another writer on Monday. Is that ok with you?

**Comment by monacodelisa** [comment]
Yes, that is the best thing to do, I'm really sorry I just can't manage with time

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @monacodelisa

**Comment by malagant** [comment]
Any plans on the article?
