### ISSUE TITLE
[REQUEST NEW CONTENT] Top External Email Providers for your Strapi Application

### ISSUE THREAD

**Issue by Theodore-Kelechukwu-Onyejiaku** [strapi/community-content#1335]
Hello 👋,

We're excited to propose a comprehensive guide that explores the top external email providers like Resend, Sendgrid, Nodemailer, AWS SES etc, that are compatible with Strapi applications. This guide aims to assist developers in selecting the most suitable email provider for their Strapi projects, providing steps for integrations and configurations of each of them in your Strapi project.

### Content Brief: 
- Target audience: Developers, Strapi users, and businesses seeking to integrate email functionality into their Strapi applications.
- Keywords: Strapi, email providers, external email services, configuration, email configuration integration

### Community vote
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by oluwatobi2001** [comment]
I'm interested.  
Here is my outline


introduction to Strapi

Detailing  its use cases and various implementations

Popular email Providers 
Highlighting pros and cons of each email provider

Setting up a strapi web application 


Demo project 
integrating an email provider to the strapi application  and testing it's features.

Additional Information  and Conclusion

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001 ,

Thanks for showing interest. Could you please share one of your works with us so as to know if you should proceed with this tutorial?

Cheers

**Comment by oluwatobi2001** [comment]
https://www.freecodecamp.org/news/mongodb-data-migration/

Also, i sent the draft to an article i pitched last week. Please i would
like to get a feedback.  Thank you

**Comment by oluwatobi2001** [comment]
I sure can. Thank you

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001,

Could you please share an outline with us so we can ensure we are on the same page?

Thanks.

**Comment by Claradev32** [comment]
@Theodore-Kelechukwu-Onyejiaku can I submit an outline for this topic?

**Comment by oluwatobi2001** [comment]
Apologies for the delay in response.


- overview of email providers
-

- Top email providers
- Highlighting features and benefits of each provider
- Key differences among the email providers
- Consideration in choosing the right Email provider for your Strapi
Application
- Demo Project Section
- Integrating the Email provider to your strapi application
- Testing the email provider
- Recap
- Conclusion

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oluwatobi2001  ,

I am not satisfied with your outline.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Claradev32 ,

Please provide an outline. Thank you.

**Comment by Claradev32** [comment]
-  Introduction
   - Overview of Email Integration in Strapi Applications
- Criteria for Evaluating Email Providers
- Top External Email Providers
    - SendGrid
    - Mailgun
    - Amazon SES (Simple Email Service)
    - SMTP.com
    - Twilio SendGrid
- Comparison of Email Providers
- Choosing the Right Email Provider for Your Strapi Application
- Setting Up Email Integration in Strapi
- Configuring SMTP Settings and Email Templates
- Conclusion

**Comment by Claradev32** [comment]
@Theodore-Kelechukwu-Onyejiaku

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Claradev32 ,

Just realized I can't assign this to you at the moment. You already have two articles in progress or in review.

Thanks.

**Comment by oluwatobi2001** [comment]
Can i have it? I have only one article in review

**Comment by gitChimp88** [comment]
@Theodore-Kelechukwu-Onyejiaku If this is free then can I submit an outline for it?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @gitChimp88 ,

Please do. Thank you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @gitChimp88 ,

Your outline looks great. Please proceed. Thank you!

**Comment by gitChimp88** [comment]
Great i'll get started with this!

**Comment by gitChimp88** [comment]
@Theodore-Kelechukwu-Onyejiaku Here's the first draft - https://hackmd.io/Aq3fZ4okSlyg9REr03SEPQ?view

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @gitChimp88 ,

So sorry I missed this. I just checked it out, there was a little bit of miscommunication, we might have to make this intermediate.

**Comment by gitChimp88** [comment]
Hey @Theodore-Kelechukwu-Onyejiaku No problem!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @MikkelScheike 😊

**Comment by gitChimp88** [comment]
Hey @Theodore-Kelechukwu-Onyejiaku, I'm trying to post this to dev.to and Medium but it seems I can't export any of the screenshots from Hackmd, also the code isn't formatting correctly on Dev.to for the markdown, do you have the same issue?
