### ISSUE TITLE
Which is better for your NextJS application? SSR or SSG

### ISSUE THREAD

**Issue by mercy0002** [strapi/community-content#1348]
### What is your article idea?

Server-Side Rendering (SSR)
Cons and Pros of SSR
The best time to use SSR?
Static Site Generation (SSG)
Cons and Pros of SSG
Use case of SSR and SSG
In this use case, we will explain in different forms using codes
The best time to use SSR?
Other SSG and SSR frameworks you should know
Factors to Consider When Choosing
we consider this factors:
Content Requirements
Performance Needs
Development and Maintenance Complexity
SEO Considerations
Team Expertise and Resources
Wrapping Up

### What are the objectives of your article?

Static Site Generation (SSG) and Server-Side Rendering (SSR) are the
two most prominent methodologies in present web development. This
article, dive deeply into the differences between SSG and SSR,
their advantages, common frameworks, and when best to use each one, to
know which is preferable for your NextJS application.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @mercy0002 . This proposal looks good. Will you be willing to change the title to "SSG vs. SSR in Next.js"? And also include code snippets and diagrams where needed?

**Comment by mercy0002** [comment]
Hi @Theodore.
I have no problem changing the title. And I will also include code snippets and diagrams where needed.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you!

Please proceed @mercy0002.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @mercy0002 ,

Thanks for your contribution! I just skimmed through your work. It doesn't meet up to the expectations of this article proposal. The content is great but I feel there are some more information that could still be sprinkled in it. Also, adding diagrams to an article makes it rich, lively, interesting and for good SEO, we already agreed on that.

**Comment by mercy0002** [comment]
Hi @Theodore
 I'm done with the update, and here is the link:
https://www.dropbox.com/scl/fi/f507ptc1vycr150v8p1up/SSR-vs.-SSG-in-Next.js.paper?rlkey=138y3wajvb0to2wy8vehmc220&dl=0

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @mercy0002 ,

Thank you! 🚀 

I will add this to the review backlog. I will ping you when I need something else. We can't wait to see more of your contribution!

**Comment by mercy0002** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku
How are you doing?
What is the latest update on the article? Here is the HackMD link:

https://hackmd.io/@zu4iIMLZTIqK-_Db-WZlyA/HkqmxZoNA/edit

After reviewing the guidelines, I switched from Dropbox to HackMD.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @mercy0002 ,

Thanks for letting me know. Your article is still in the review backlog. And presently, we have a lot of articles in the backlog. So please be patient. Thank you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @mercy0002,

Could you please share me the following details on Discord:

- Full Name
- Photo
- Email
- Job Title
- Twitter Handle
- Please ensure to follow Strapi on Linkedin so I can be able to tag.

Thank you for your contribution!

**Comment by mercy0002** [comment]
Hi @Theodore,

Here are the details and file you asked for:


   - Full Name: Mercy Tanga
   - Photo:
   - Email: ***@***.***
   - Job Title: Software developer
   - Twitter Handle: https://x.com/MercyTanga
   - Please ensure to follow Strapi on Linkedin so I can be able to tag:
   Yes i will

Sorry i could  not share the details you asked on discord.

Thanks hope to hear from you soon.

**Comment by lucky4242** [comment]
Hi @Theodore. 

I have share the details you asked for on discord.

**Comment by mercy0002** [comment]
Hi @Theodore

I have share the details you asked for on discord

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @mercy0002 ,

I left some comments on your draft. Please incorporate the reviews so I can publish your work. Thank you!

**Comment by lucky4242** [comment]
Seen. Working on them

**Comment by mercy0002** [comment]
Hi @Theodore
I have finished working on the comment, and here is the link:
https://hackmd.io/@zu4iIMLZTIqK-_Db-WZlyA/HkqmxZoNA/edit

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @mercy0002 ,

Please fix your code, it appears you did not. 

You can first start by telling the reader the Next.js paradigm you are implementing (pages or app router). After that, a brief explanation on the paradigm is great.

For instance there is `getServerSideProps` and `getStaticProps` for the pages router.

And there is the "use client" for app router. 

Please incorporate. Thank you 💪

**Comment by mercy0002** [comment]
Hi @Theodore

The code has been fixed and here is the link :

https://hackmd.io/@zu4iIMLZTIqK-_Db-WZlyA/HkqmxZoNA/edit
