### ISSUE TITLE
How to Build Accessible Web Applications with WAI-ARIA

### ISSUE THREAD

**Issue by ArafatAbdussalam** [strapi/community-content#1354]
### What is your article idea?

This article entails the definition of web accessibility, the need for web accessibility, assistive technologies, and how they are related to accessible web applications. The article further talks about WAI-ARIA Roles, States, and Properties; when to use them, and when not to use them.

### Content Brief:
-  Target audience: Web Application developers, Accessibility Engineers, Software Engineers, and anyone interested in building accessible web applications
- Keywords: accessibility, WAI-ARIA, web development

### Proposed Outline:
-  Introduction to Web Accessibility
- Importance of Web Accessibility
- Assistive Technologies and how they relate to web applications
- How to Build Accessible Web Applications
   - HTML Semantics and attributes (with code samples including attributes like alt text, id, for, and tab index for keyboard navigation)
   - CSS Styling (with code samples explaining colour contrast)
   - WAI-ARIA
- Introduction to ARIA Roles, States, and Properties
- How to Implement ARIA Roles, States, and Properties (with code samples)
- When to use and when not use ARIA Roles, States, and Properties
- Conclusion

### What are the objectives of your article?

This article aims to teach web application developers how to implement WAI-ARIA Roles, States, and Properties in their web applications. It enables web developers to gain further practical knowledge on web accessibility beyond the practice of semantic HTML, and CSS Styling.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorials

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by ArafatAbdussalam** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku I would be glad if you could take a look at the proposed article.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @ArafatAbdussalam ,

We already have a blog post on web accessibility [here](https://strapi.io/blog/how-to-improve-the-accessibility-of-strapi-powered-websites-1) that published recently. At this time, we won't be accepting this. 

I will close this. Thank you!
