### ISSUE TITLE
A Deep Dive into Loading Balancing Web Applications

### ISSUE THREAD

**Issue by vicradon** [strapi/community-content#1356]
### What is your article idea?

This article covers the importance of load balancing and the common strategies that are used to load balance web applications. It concludes with a section on load balancing Strapi on several Ubuntu instances using Nginx as the frontend load balancer.

NB: frontend here refers to the fact that the machine running Nginx will be exposed to the internet. 

## Outline

- Introduction to load balancing
  - What is load balancing
  - Why is load balancing important
- An overview of common load balancing strategies and their best use-cases
  - Robin Robin
  - Weighted Round Robin
  - Sticky Round Robin
  - Least time
  - Least connections
  - IP/URL Hash
- Choosing the right Load Balancing Strategy
- How to Load Balance Strapi Deployment between three Backend Servers using Nginx
  - Obtaining the Backend Server IP Addresses and SSH credentials
  - Installing Nginx on the Frontend Load Balancer Machine
  - Configuring Nginx to handle incoming HTTP Traffic and Load Balance to the Backend Servers
  - Configuring SSL on the Frontend Load Balancing Machine
- Conclusion
  - What you learned in the Article
  - Call to action to use Strapi for Content Management

Expected Word Count: 1800 - 2000 words

### What are the objectives of your article?

1. Teach the reader the importance of load balancing in software engineering
2. Expose the reader to commonly used load-balancing strategies
3. Teach the reader how to load balance an application like Strapi between several server instances using Nginx

### What is your expertise as a developer or writer?

Advance

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @vicradon,

This is excellent. Since there is a similar one here #1268, I will reply to you shortly. I appreciate your understanding. Thank you!
