### ISSUE TITLE
Build  a Survey App With Strapi and Solid.js

### ISSUE THREAD

**Issue by oyedeletemitope** [strapi/community-content#1358]
### What is your article idea?

This article will delve into the process of creating a survey application that leverages the strengths of both Solid.js and Strapi. It will cover the setup and configuration of Strapi for managing survey data, including content types for surveys and responses. On the frontend, the article will guide readers through setting up a Solid.js project, creating the survey interface, and integrating it with the Strapi backend to fetch survey data and submit responses. 

OUTLINE

- Introduction
   - Brief overview of Solid.js and Strapi.
   - Importance of survey applications in gathering customer feedback.
 - Installing Strapi and creating a new project.
    - Configuring Strapi for the survey application.
- Setting Up Solid.js
   - Introduction to Solid.js.
   - Setting up a new Solid.js project.
   - Creating the survey interface with Solid.js.
- Integrating  Strapi into Solid.js
  - Fetching survey data from Strapi to display in the Solid.js app.
   - Submitting survey responses from the Solid.js app to Strapi.
- Conclusion

### What are the objectives of your article?

Objectives of this article include the following:

- Equip Solid.js developers with the knowledge to integrate Strapi for content management.
- Showcase a practical approach to fetching, displaying, and potentially managing Strapi content within a Solid.js application.
- Contribute to a growing collection of resources that bridge the gap between Strapi and Solid.js development.
- Encourage wider adoption of Strapi among Solid.js developers for streamlined content management.

### What is your expertise as a developer or writer?

Advance

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @oyedeletemitope,

Thank you for your proposal. We currently have a SolidJs tutorial under review, coincidentally from you #1313. Therefore, at this time, we won't accept this proposal. I will have to close this one.

Please feel free to submit another proposal. Thank you.
