### ISSUE TITLE
Implementing a Media Gallery in a Flutter App with Strapi's Media Library

### ISSUE THREAD

**Issue by icode247** [strapi/community-content#1367]
### What is your article idea?

This tutorial will cover the following:

- Introduction to Strapi's Media Library
- Setting up Strapi with the Media Library
- Uploading Media Files to Strapi
- Creating a Flutter Project
- Retrieving Media Files from Flutter
- Displaying Media Files in Flutter
- Handling Media Uploads from Flutter
- Advanced Media Library Features
- Conclusion 

### What are the objectives of your article?

This tutorial will teach developers how to build a Media Gallary application in Flutter with Strapi's Media Library. 

### What is your expertise as a developer or writer?

Advance

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by icode247** [comment]
@Theodore-Kelechukwu-Onyejiaku

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @icode247 , this looks interesting. Please go ahead. Thank you!

**Comment by icode247** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
This draft is ready for review: https://hackmd.io/8dnzeTJmRrihFZpUBzNTjQ

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @icode247 ,

Thank you for your contribution!🚀 I will add it to the review backlog. 

Meanwhile, could you please add the art cover for the article? Thank you!

**Comment by Claradev32** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
I have added the cover image to the draft.

**Comment by icode247** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
I have added the cover image as requested!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @icode247 😊

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @icode247 ,

Thanks for your great contribution to the community. I left some comments in your draft. Please incorporate so I can move ahead with the complete review and publishing of your article!

**Comment by icode247** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
Thank you for the review. I have worked on the comments, please take another look.
