### ISSUE TITLE
How to build an invoicing app with Next.js, Redux, and jspdf

### ISSUE THREAD

**Issue by OmaJuliet** [strapi/community-content#1374]
### What is your article idea?

This article will be a detailed guide on how to build an interactive invoicing app step by step using technologies like Next.js, Redux for state management, and jspdf to make the invoices downloadable.

### Introduction to Next.js and Redux: 

- Brief overview of Next.js and Redux

### Setting up the Next.js project: 

- Creating the Next.js Project
- Step-by-step guide to setting up a Next.js project
- Installing necessary dependencies and configuring the development environment
- Integrating Redux into the Next.js app
- Configuring Redux store in the Next.js application

### Implementing functionality with Redux: 

- Building components for creating, editing, and deleting invoices
- Implementing Redux actions and reducers to handle invoice data
- Integrating form validation and error handling

### Integrating jspdf for PDF invoicing:

- Overview of the jspdf library for generating PDF documents in JavaScript
- Installing and configuring jspdf library in the Nextjs project
- Implementing the logic to convert the invoice data into a PDF document
- Customizing PDF layout
- Adding a download button to each invoice

### Conclusion

- Overview and a quick recap of the article

### What is your expertise as a developer or writer?

Beginner

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @OmaJuliet ,

This looks good. Could we please use Strapi as the backend to store all invoice data? 

Please let me know if you have any questions.

**Comment by OmaJuliet** [comment]
Alright, I'll use Strapi for the backend

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
@OmaJuliet , thank you. I can't wait to see your contribution! 🥳

**Comment by OmaJuliet** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku , for this tutorial, you said I should use Strapi as the backend storage for the invoice data. The invoice data is already being managed and stored in the Redux store, so should I use one instead of the two?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @OmaJuliet ,

I would advise you use Strapi to store the data for historical reasons. You can use the both of them, but for simplicity, I would suggest you use Strapi alone. Store your data in Strapi so they can be accessed anytime as the redux store is for complex state management and not a database as well.

Please let me know if you have any other questions. Thank you!

**Comment by OmaJuliet** [comment]
Great @Theodore-Kelechukwu-Onyejiaku . Thanks.

**Comment by OmaJuliet** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
This article is ready for review. Here's the draft link: https://hackmd.io/@Juliet-Oma/SkQt8yXfC

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @OmaJuliet ,

Thank you for your contribution! 🚀. I will add this to the review backlog. Meanwhile, I checked the demo videos. Is it possible you provide a GIFs of them since their durations are not long. If Hackmd limits the size upload, you can share them here. Just make sure they are clear enough and are viewable. That would be much appreciated. 

Thank you. 

Please do well to join our Discord community channel "#Write for the Community" if you haven't, https://discord.gg/invite/strapi. 😊

**Comment by OmaJuliet** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku I planned to use Giphy to make the videos into GIF but it wasn't clear. The GIF came out blurry

**Comment by OmaJuliet** [comment]
I've created the GIFs and embedded them in the article. Check if they're ok.

Here are the links for them: 
https://media.giphy.com/media/UTfX3ebXfSw48oClNz/giphy.gif
https://media.giphy.com/media/WF3SwxCvc8LCxuTIhg/giphy.gif

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @OmaJuliet.

Could you please provide clear ones.They look quite blurry. @OmaJuliet .

**Comment by OmaJuliet** [comment]
Yeah, I will @Theodore-Kelechukwu-Onyejiaku

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @OmaJuliet

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @OmaJuliet ,

Thanks for your contribution. I left some comments in your draft. Please review it. Thank you!

**Comment by OmaJuliet** [comment]
All done @Theodore-Kelechukwu-Onyejiaku
