### ISSUE TITLE
Mux Video Uploader - Partner Blog Post Submission

### ISSUE THREAD

**Issue by erikpena** [strapi/community-content#1379]
**My Request**

Hello @PaulBratslavsky! 😁
I have a blog post request for a set of updates that we've included in our [latest version](https://docs.mux.com/integrations/strapi#current-release) of the mux-video-uploader plugin.

- Added the ability to specify encoding tier setting on new uploads ([More details](https://docs.mux.com/integrations/strapi#encoding-tiers))
- Added the ability to specify static renditions when uploading a Baseline encoding tier Asset ([More details](https://docs.mux.com/integrations/strapi#static-renditions))
- Added the ability to auto-generate captions or manually upload a captions for an Asset ([More details](https://docs.mux.com/integrations/strapi#captionssubtitles))

In addition to the above, we also updated our own internal documentation with updated and refreshed screenshots so please feel free to use them!  There is also a video that shows the upload process which you are also welcome to embed.  The video is accessible by the following URL—

```
https://stream.mux.com/kBwjf6dl6028FjELH4p0297dLcPM6AvQ1D.m3u8
```

Please feel free to reach out to me on Slack or Discord if you want to dig further into this.

Thank you!

**Comment by PaulBratslavsky** [comment]
@erikpena Hey just wanted to check in about the blog post regarding the updates you mentioned.

**Comment by erikpena** [comment]
Hey @PaulBratslavsky,
Here is the Blog (below)—

---

# Unleash the Power of Video in Your Strapi Projects with the Mux Video Uploader Plugin

We've got some fantastic news about the latest version of the Mux Video Uploader plugin for Strapi. With the latest release, Strapi projects will now be capable of utilizing some of the latest features offered by Mux!

## Why Add Video to Your Strapi Projects?

| |
|--------|
| ℹ️ _If you're not already using the Mux Video Uploader plugin with your projects, keep reading to see what you might be missing out on (or, if you are already privy, skip this section)._ | 

Video has become the ultimate tool for engaging audiences. It's like a magnet that draws people in and keeps them hooked. By integrating video into your Strapi projects, you'll be able to create immersive experiences that captivate your users.

With the Mux Video Uploader plugin for Strapi, you can:

- Upload, manage, and publish videos without ever leaving the Strapi interface.
- Blend video content with your text, images, and other rich media. It's the perfect recipe for creating cohesive and compelling content.
- Harness the full potential of Strapi's content modeling and collaboration features for your video assets.

This Strapi plugin benefits from Mux's core features which include:

- Adaptive bitrate streaming, ensuring optimal playback on any device.
- A global content delivery network (CDN) for lightning-fast video delivery. Even better— Mux utilizes a multi-CDN strategy to ensure both availability and performance 💪.
- Comprehensive video analytics to track viewer engagement. It's like having a detective that uncovers how your videos are performing.
- Automatic transcoding and format optimization for maximum compatibility.

With Mux by your side, you can focus on crafting epic content while we handle the technical complexities 🤓.

## New Features That Will Blow Your Mind

The latest release of the Mux Video Uploader plugin comes with new features that will take your video capabilities to new heights.

1. **[Encoding Tiers](https://www.mux.com/blog/more-pixels-fewer-problems-introducing-4k-support-for-mux-video)**: Take advantage of our new Encoding Tier feature which allows you to choose between better pricing and more flexible resolutions on playback.
2. **[Max Resolution Setting](https://www.mux.com/blog/more-pixels-fewer-problems-introducing-4k-support-for-mux-video)**: Deliver jaw-dropping, high-resolution video experiences with support for resolutions up to 1080p, 2K, and even 4K!
3. **[Auto-generated Captions](https://www.mux.com/blog/guau-wauw-vau-wow-vod-auto-generated-captions-are-now-available-in-22-languages)**: Expand your reach and accessibility with AI-based auto-generated captions for on-demand videos in 22 languages.
4. **[Static MP4 Renditions](https://docs.mux.com/guides/enable-static-mp4-renditions)**: Enable static MP4 renditions of your videos for increased flexibility and compatibility. For use cases that require static MP4 files as opposed to web-optimized HLS content.

Each of the above features can be set on a per-asset basis so you can control your journey more discretely.

## Get Started Today

Visit the [plugin documentation](https://docs.mux.com/integrations/strapi) to learn more about installation, configuration, and usage.

If you ever find yourself stuck, don't worry! Mux’s friendly support team is here to help. Reach out to us at [support@mux.com](mailto:support@mux.com), and they'll be happy to provide you with the assistance you need to succeed.

New to Mux? Mux is offering **$50** in Pay-as-you-go credits to get you started. Sign up for a Mux account and when you're asked “How did you hear about Mux?” just select “Promo Code” and enter `STRAPIUPDATE`.

**Comment by PaulBratslavsky** [comment]
@erikpena thank you, will let you know when it is live.

**Comment by PaulBratslavsky** [comment]
@erikpena thanks for all your help, I shared the post with video https://strapi.io/blog/integrating-mux-video-uploader-plugin-with-strapi-and-next-js and reposted on socials.
