### ISSUE TITLE
[TOPIC] Facebook login with Strapi 

### ISSUE THREAD

**Issue by chrissnoek** [strapi/community-content#138]

**Comment by lelouchB** [comment]
Hey @Mcastres 
I would like to work on this.
Here are few of my writing samples

https://www.freecodecamp.org/news/author/ashutosh/

https://medium.com/@lelouchb

https://dzone.com/users/3800520/lelouchb.html

**Comment by alloyking1** [comment]
I can build an authentication system with strapi and the facebook log. I can handle this topic

**Comment by purnimagupta** [comment]
@alloyking1  Hey, are you working on this? If not, I would like to work on this. Let me know.

**Comment by alloyking1** [comment]
hi @purnimagupta. Yes. I'm working on it. Thanks

**Comment by alloyking1** [comment]
@Mcastres @purnimagupta @malgamves just a little curious as this has not been assigned to me yet.

**Comment by alloyking1** [comment]
hi, @Mcastres @malgamves . The draft for this article is ready. You can find a link to it on dropbox [here](https://www.dropbox.com/scl/fi/6apwae2y5yng4bd2xsm7o/Facebook-Login-with-Strapi.paper?dl=0&rlkey=dzp1gmkezn9j2uklmlnimf1yu).

**Comment by malgamves** [comment]
Thanks, having a look.
