### ISSUE TITLE
CRUD App with Qwik (City) & Strapi

### ISSUE THREAD

**Issue by b4s36t4** [strapi/community-content#1385]
## What is Qwik?
Qwik is an alternative frontend framework that is evolving and gives good performance score. 

## Why Qwik?

* Similar syntax as JSX.
* Good performance and best principles like lazy loading etc.
* Less Javascript on client side.
* Works with existing React tools, less to no changes.
* Signals & good state management.

Qwik does also have a meta framework called `qwik-city` which is kind of `Next.js` to react to support SSR, ISG etc. 

The article is about how we can leverage new age frameworks to build the application without less or no learning curve.

Qwik is a great alternative to React when people feel React is slow or Next.js too complex, qwik can be a good alternative to build application. 

### What are the objectives of your article?

* Understanding React Tradeoffs i.e How react hyderation is working.
* Need of Modern age framework like Qwik.
* Understanding Qwik's architecture and principles.
* Intro Qwik & Qwik city.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @b4s36t4,

This looks good 💪. Along with your intended content, can we also have the following headings:

1. Qwik peculiar/cool features (compared to popular frameworks like React, Vue or Angular)
2. Real World Use case of products built with qwik.
3. Qwik Ecosystem
4. Getting Started with Qwik (Perhaps build a little app to demonstrate some cool features of Qwik)
5. Deployment

Please let me if you will be willing to do this. Thank you!

**Comment by b4s36t4** [comment]
Yea sure, I'm down with the changes you suggested. @Theodore-Kelechukwu-Onyejiaku .

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Please proceed. Thank you!

Depending on the submitted content, this might change to intermediate content.

**Comment by b4s36t4** [comment]
@Theodore-Kelechukwu-Onyejiaku I have completed this as well please check here https://www.dropbox.com/scl/fi/js33hofva5nuqd398fxve/How-to_-Qwikly-build-a-Strapi-App.paper?rlkey=gm92p3yd1a4pyyfkd9x77aj0k&dl=0.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @b4s36t4 ,

Thank you 🥳

Please do well to join our Discord community channel (#write-for-the-community) to learn more about the recent updates and developments, https://discord.gg/invite/strapi. 😊

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @b4s36t4,

After careful review, we discovered we won't be able to publish this article at the moment. I would love that you publish it elsewhere. You could try Bejamas, Freecodecamp, HackerNoon or Smashing Mag.

Thank you for your contribution.
