### ISSUE TITLE
[TOPIC] Serverless Strapi on AWS

### ISSUE THREAD

**Issue by pfeilbr** [strapi/community-content#139]
a tutorial on how to run a serverless / pay-per-use strapi on aws using Cognito (access & auth), API Gateway, Lambda, [DynamoDB | Aurora Serverless], CloudFront (CDN) + S3 (static assets).  End result is a [CloudFormation | SAM | serverless framework] template or aws serverless application repository application that provisions all the AWS resources for strapi and outputs an API Gateway endpoint URL.  When there are no requests, you pay nothing since it's all pay-per-use.

This would also be a great model for a Strapi SaaS offering and/or allowing an enterprise customer to self-host in the cloud of their choice (aws, azure, gcp).

**Comment by malgamves** [comment]
Would you like to take this on @pfeilbr ?

Not sure if you're still interested

**Comment by ShadaW11** [comment]
Hey @pfeilbr Are you still interested in working on this topic?

**Comment by pfeilbr** [comment]
@ShadaW11 thanks for the follow up.  

unfortunately i'm unable to due to limited time.  admirer of the product and in order to make more accessible and cost effective thought pay-per-use would be a good fit.

**Comment by ShadaW11** [comment]
@pfeilbr thank you for the feedback and update. No worries at all. Looking forward to seeing your articles soon once your time allows.

**Comment by suhajda3** [comment]
Is this still open? If yes, I'm willing to take the challenge.

**Comment by ayhid** [comment]
I am also interested in this topic. IMHO it has to be splitted in multiple articles.

**Comment by malgamves** [comment]
Hey @ayhid could you share more? Afaik Serverless Strapi isn't really a best practice.

**Comment by Xemarij** [comment]
Hi, I like to take this project if it is available.

**Comment by PaulBratslavsky** [comment]
We are not currently recommending this as a method of deployment and will me marking it as closed since this is not something we will be supporting in the future.
