### ISSUE TITLE
How to Build a Language Translator with Strapi, Streamlit and Hugging Face Models.

### ISSUE THREAD

**Issue by adejumoridwan** [strapi/community-content#1399]
### What is your article idea?

In this article, readers will learn how to build a language translator application that allows users to give text in any language and translate it to English. The article will walk the users through getting the language translation model on hugging face to building the user interface with Streamlit. Readers will also learn how to implement Strapi as a Backend service that would allows users to access the history of inputs and outputs, which will be stored in a Strapi backend. The following is the outline for the article:
- Introduction
- Prerequisites
- Project Setup
- Build the Frontend
   - Select a Model from Hugging Face
   - Build the User Interface with Streamlit
- Build the Backend
   - Set up Strapi
   - Connect Stapi with Streamlit
- Deployment
   - Deploy the Backend on Strapi Cloud
   - Deploy the Frontend on Streamlit Cloud
 - Conclusion

### What are the objectives of your article?

The key things the reader will learn are:
- How to use a model from Hugging Face
- How to build a frontend application with Streamlit
- How to use Strapi as a Backend for an application
- How to make API requests back and forth between Strapi and Streamlit.
- How to deploy a Strapi application on Strapi Cloud
- How to deploy a Streamlit frontend on Streamlit Cloud.

### What is your expertise as a developer or writer?

Advance

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @adejumoridwan ,

This is good. Would you be willing to provide a working Github repo to the final application?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @adejumoridwan ,

This is good. Would you be willing to provide a working Github repo to the final application?

**Comment by adejumoridwan** [comment]
Yes, I will provide a working github repo with a readme to guide users on how to set it up on their local machine.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @adejumoridwan ,

Thank you! Please proceed. Meanwhile, depending on the effort put into this work and quality of the content, we might upgrade it to intermediate. Let's go 🚀

**Comment by adejumoridwan** [comment]
@Theodore-Kelechukwu-Onyejiaku here is the link to the draft https://hackmd.io/@adejumoridwan/B1Ab4WBzC/edit

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @adejumoridwan ,

Thank you so much for your contribution. I have a request. Could you please provide a demo, perhaps a GIF of the functional app in this blog post?

**Comment by adejumoridwan** [comment]
@Theodore-Kelechukwu-Onyejiaku I have added a GIF showing the app functionality in the blog post

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @adejumoridwan! Your contribution is highly appreciated! 🥳


I will add it to the review backlog.

**Comment by adejumoridwan** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku hope you are doing great. I will like to know the status of my draft. Thanks

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @adejumoridwan ,

Thanks for your patience. Your article is in the review backlog. When I need anything I will let you know.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @adejumoridwan 

I added some comments on your draft. Please incorporate. Thank you.

**Comment by adejumoridwan** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 
I have incorporated the comments.
