### ISSUE TITLE
[TOPIC] Deploy Strapi on Shared hosting, Cpanel that Supporting NodeJs apps

### ISSUE THREAD

**Issue by Tarekrida1** [strapi/community-content#140]
Deploy Strapi on Shared hosting, Cpanel that Supporting NodeJs apps

**Comment by bigpreshy** [comment]
I'd like to write an article on this, as I have hosted strapi on namecheap.com(a shared hosting)

**Comment by touha98** [comment]
@bigpreshy  I also want to host strapi on namecheap.com. Please tell me how to get started.

**Comment by piersdeseilligny** [comment]
@bigpreshy any update? I've been struggling to set up strapi on shared hosting

**Comment by samverrall** [comment]
Also having trouble setting this up, keen to know if anyone has any solutions.

**Comment by derrickmehaffy** [comment]
We do not support shared hosting environments. 

Marking as closed.
