### ISSUE TITLE
Conversational Transcription with Whisper and GPT

### ISSUE THREAD

**Issue by gitChimp88** [strapi/community-content#1404]
### What is your article idea?

I would like to propose a ten article series where I show how to build a transcription app which listens in to video calls from speaker output and transcribes the audio and then provides context / answers to questions etc, I would like to start from the beginning and go through to deployment. I can use Next or Astro for the frontend. Let me know if this idea sounds interesting and I will then submit a detailed outline.

### What are the objectives of your article?

To show the user how they can use strapi to spin up a backend fast and use cutting edge technology like whisper and chatGPT to build useful apps, I would also like to show how to build an app from scratch to deployment.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @gitChimp88 ,

Your proposal is great, thank you! Can this be divided into 3 parts, if so, could you share an outline?

It is worthy to note that series are labeled as advanced with a one time payment.

**Comment by gitChimp88** [comment]
@Theodore-Kelechukwu-Onyejiaku Just to clarify series are marked as advanced so this series would be 3 x advanced articles paid one time at the end?

**Comment by gitChimp88** [comment]
Hey @Theodore-Kelechukwu-Onyejiaku,

That's all fine, just wanted to clarify.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you Mike! 🥳
