### ISSUE TITLE
Building a multi-lanugage Blog with Strapi and Astro

### ISSUE THREAD

**Issue by noahflk** [strapi/community-content#1408]
### What is your article idea?

This article will be a tutorial on how to build a multi-language blog using Strapi and web framework for content sites Astro. This enables writers to expand their Blog's reach globally.

We will highlight Astros integrated Internationalization functionality and how to best combine it with Strapis infrastructure. This will allow features like automatic detection of the reader's language and seamless switching between languages. Furthermore, we'll make use of Astros static generation functionality to build a blog that meets the highest performance standards.

**Sections**

- Introduction
  - Show our Tech Stack: Strapi, Astro and Tailwind
  - Reasons for writing in multiple languages
  - Put a special focus on Astros internationalization and static generation capabilities
  - Requirements (Node.js)
- Setting up strapi
  - Initial setup
  - Content model for multi-lang (category, author, post, language)
  - Configure API access
 - Getting started with Astro
   -  Bootstrapping project
   - Adding Tailwind, design skelleton
   - Accessing Strapi API
 - Making it international
   - Multi language i18n setup
   - Rendering posts in multiple languages
 - Conclusion

### What are the objectives of your article?

Showing readers that both Strapi and Astro have excellent internationalization features that enable you to reach a global audience. We do this by first outlining the features and benefits of this approach and then giving a clear step-by-step instruction on how to achieve this. With this, readers will be able to set up their own Strapi and Astro Blog with multi-language support.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @noahflk ,

Thank you for your outline! Please proceed.

**Comment by noahflk** [comment]
Once I have a draft ready on hackmd, which email should I share it with? @Theodore-Kelechukwu-Onyejiaku

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @noahflk ,

Thank you for your contribution! I will add this to the review backlog. At the moment, I need nothing from you. I will ping you when I need anything. 

Please do well to join our Discord community channel if you haven't, https://discord.gg/invite/strapi. 😊

**Comment by noahflk** [comment]
Could you give me an update on this @Theodore-Kelechukwu-Onyejiaku ?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @noahflk ,

Thank you for contributing to the "Write for the Community" program. Sorry we can't publish this at the moment, and would love it if you publish them on HackerNoon or Smashing Mag. This was a misunderstanding from our own end.

And please don't forget to send your invoice. 🙂

**Comment by noahflk** [comment]
Thanks @Theodore-Kelechukwu-Onyejiaku 

I have published the post here: https://noahflk.com/blog/strapi-astro-multilang-blog
And will publish mirrors on other platforms today.

I have submitted the invoice through the Google Form.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @noahflk,

Could you please provide a valid proof a bank account details (for instance, letter from bank, web banking screen shot, canceled check etc.)? Currently we have just the copy of your identity which doens’t work for us. We won’t be able to process the invoice without it. 

Please send to my official email address or on Discord so I can forward it to the Finance Team. 

Thank you!

**Comment by noahflk** [comment]
@Theodore-Kelechukwu-Onyejiaku sent you a DM on Discord

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Please attend to the new DM I sent you.

Thank you!
