### ISSUE TITLE
accessiBe: How Web Accessibility Can Improve Your Website

### ISSUE THREAD

**Issue by mberk1** [strapi/community-content#1409]
### What is your article idea?

1. -High-level introduction to web accessibility 
2. Overview of business benefits of having an accessible website
- Specific to e-commerce/online retail
- Benefits for business and the end user
-Spending habits of online shoppers with disabilities (we have new case studies that were just released on this)
3. Overview of the legal side of web accessibility
-WCAG
-ADA/ACA/AODA and other regional accessibility laws
4. (Optional) Topics such as: 
-Tax Credit
-Comprehensive guide to legal requirements
-Brand Image benefits
-see if your website is accessible (accessScan tool)
-Where web accessibility fits into your software development lifecycle/how and why to integrate
-(For developers) front and back end considerations

### What are the objectives of your article?

The objective of this article is to give a high-level overview of the basics of web accessibility. The article would include topics and metrics related to the necessity of web accessibility, the benefits your clients and their end users can expect, legal considerations, and even technical information for software developers.

We have an extensive library of content, collateral, and case studies, and we are happy to have this article be as in-depth as you want it to be based on what type of information you want your clients to be seeing.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Best Practices

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @mberk1 ,

Thank you so much for your contribution. Unfortunately, we have a similar content that is already published https://strapi.io/blog/how-to-improve-the-accessibility-of-strapi-powered-websites-1. 

Please feel free to propose another one.
