### ISSUE TITLE
Build Your Portfolio Website With Strapi And Gridsome

### ISSUE THREAD

**Issue by psalmuelle** [strapi/community-content#1417]
### What is your article idea?

This topic will cover the following sections:

- Introduction
     - Brief overview of purpose of creating a portfolio website
     - Introduction to Strapi and Gridsome as tools for building dynamic and performant websites
     - Prerequisites
     - Design/Sample to follow
- Overview of Strapi and Gridsome
- Starting the project 
   - Installation and setup of Strapi
   - Creating content types for the portfolio websites (e.g Projects, About, Contact, Blog)
   - Defining fields and relationships within the content types
   - Creating sample data or populating content through the Strapi admin panel
   - Configuring user roles and permissions
   - Setting up Strapi API
   - Testing
   - Installation and setup of Gridsome
   - Basic project structure and file organization
   - Integrating Strapi with Gridsome
   - Fetching data from the Strapi API using GraphQL
   - Creating pages (homepage, projects, about, contact -implementing contact form using Strapi contact form plugin
   - Implementing dynamic routing in Gridsome for individual project pages
   - Utilizing Gridsome's built-in features for code splitting and pre-fetching.
- Building and deploying the portfolio website
- Setting up automatic deployment pipelines for continuous updates.
- Conclusion 
   - Recap on the process of building a portfolio website with Strapi and Gridsome.
   - Final thoughts on the benefit of using Strapi as headless CMS
   - Further exploration and customization of the portfolio website.the 

### What are the objectives of your article?

This article aims to demonstrate how to leverage Strapi to build a dynamic portfolio website efficiently. It educates readers on Strapi's role in content management, its flexibility and security.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @psalmuelle ,

Thanks for your contribution. At the moment we won't be accepting this. Please feel free to propose another one in the future.
