### ISSUE TITLE
Build a Google Meet Clone using LiveKit and Astro

### ISSUE THREAD

**Issue by b4s36t4** [strapi/community-content#1422]
### What is your article idea?

Livekit is an open source implementation of webrtc with Rich SDK and dev tools to build realtime web application to build and audio and video communications into web apps.

My idea is to build a Video call application like google meet clone to be built with livekit and Astro. 

Why Astro?
While there are great frameworks out there astro gives the best of all frameworks i.e I can choose my own frameworks and integrations. I feel like applications like this can use Astro's powerful apis and core structure.

### What are the objectives of your article?

* Intro to Livekit and WebRTC
* Setting up the Livekit APIs & SDK
* Concepts like Room, Member etc.
* Establishing the frontend for communication i.e browser permissions, livekit sdk intro for React.
* Livekit streaming & Room creation etc.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by b4s36t4** [comment]
@Theodore-Kelechukwu-Onyejiaku Please take a look at the above article and share your feedback!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @b4s36t4 ,

Your outline is very much appreciated. Unfortunately, we won't be accepting this because we already have contents in progress related to the topic "real time" or "web socket". See #13771, https://github.com/strapi/community-content/issues/1390, https://github.com/strapi/community-content/issues/1415 and some other published articles. Thank you.

Please do well to join our  "Write for the Community" channel on our Discord community if you haven't, https://discord.gg/invite/strapi. 😊

**Comment by b4s36t4** [comment]
@Theodore-Kelechukwu-Onyejiaku maybe there's a misunderstanding with my title and what my intention was. 

I proposed a solution to build a google meet clone which uses webrtc while the articles you've mentioned above was using websockets to build real time communication vs webrtc for video and audio communication. 

It's like building a zoom and gmeet with open source technologies. 

Maybe you can review again please?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @b4s36t4 ,

This cool. Thanks for the clarification! Could we give it the title "Build a Google Meet Clone using LiveKit and Astro"?

Please let me know what you think.

**Comment by b4s36t4** [comment]
Hey, @Theodore-Kelechukwu-Onyejiaku . Thanks a lot for re-opening the issue :).

Yep, I should've done that earlier 😅. I'm good with the title you suggested.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @b4s36t4 🥳

Depending on your content quality and effort, we will have to eventually label this as intermediate. Thanks

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @b4s36t4 ,

I am so sorry, you already have two articles in progress or in review. I will close this. Please propose it when any of your current articles is published. Thank you!

**Comment by b4s36t4** [comment]
Oh, sure. Will keep this in my bucket.

**Comment by magl88** [comment]
Very interesting topic!
I am also trying to figure out how to integrate strapi with LiveKit.
Unfortunately, I can't find any information on this at all
