### ISSUE TITLE
Creating Programmatic SEO Pages with Strapi and Next.js

### ISSUE THREAD

**Issue by noahflk** [strapi/community-content#1429]
### What is your article idea?

This article will be a tutorial on how to build programmatic SEO pages (pSSO) using Strapi and Next.js. This approach enables websites to rank on Google by displaying human-written content on automatically generated pages.

We will highlight the powerful features of Strapi for storing content and how to seamlessly integrate it with Next.js to dynamically render SEO pages. We will use the example of a real estate company that manages its property listings in Strapi. We will then use the Strapi API and Next.js to generate various pages, such as:

- All listings in a town
- Apartments in a town
- Houses in a town

**Rough outline**

- Introduction
  - Show our Tech Stack: Strapi, Next.js and Tailwind
  - What is pSSO
  - Benefits of pSSO
  - Requirements (Node.js)
- Setting up Strapi
   - Initial setup
   - Content model for (listings)
   - Configuring API access
- Getting started with Next.js
  - Setting up project
  - pSSO page skeletons
  - Accessing Strapi API
- Rendering the content from Strapi in Next
  - Ensuring it's static
  - Adding meta SEO tags
  - Publishing Sitemap
- Conclusion

### What are the objectives of your article?

Showing readers how to leverage the power of the Strapi CMS along with Next.js to build a directory of SEO pages. First, we show them what programmatic SEO is and what the benefits are. Then we give a step-by-step tutorial on how to use Strapi to store the relevant data for SEO pages and then leverage Next.js to render and display these pages.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
This makes sense @noahflk ,

Do you plan on also discussing the downsides or risks associated with pSEO?

**Comment by noahflk** [comment]
Sorry for the late response, somehow didn't get pinged on this issue! 

Yes, I can add a chapter "Downsides of pSSO" to the introduction. In there I'd talk about quality control issues since content is generated automatically and mistakes can happen.

What do you think @Theodore-Kelechukwu-Onyejiaku ?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @noahflk ,

Thanks for your interest and your patience. We have decided that this will be done in-house. We will close this now. Please feel free to propose another article (especially blog series as at this moment) in the future.

Thank you!
