### ISSUE TITLE
[TOPIC] Frontend plugin development

### ISSUE THREAD

**Issue by syedhasanabbaszaidi** [strapi/community-content#144]
Need tutotials for front end plugin development. Thanks

**Comment by alloyking1** [comment]
Hi @malgamves I can pick this up. Hope to hear from you soon.

**Comment by malgamves** [comment]
Hey @alloyking1 this would be a guide on creating a plugin for Strapi is that still something you'd like to write about?

**Comment by alloyking1** [comment]
yes. Definitely.
You can add me to this

**Comment by malgamves** [comment]
Sure, assigned to you.

Can't wait to see what plugin you create ✨

**Comment by alloyking1** [comment]
Okay. Thanks. Im on it

**Comment by alloyking1** [comment]
Hi @malgamves wondering if I can start since this has not been assigned yet?

**Comment by malgamves** [comment]
It should be all good now @alloyking1

**Comment by alloyking1** [comment]
Okay. Thanks for letting me know

**Comment by alloyking1** [comment]
still working on this. Almost done.

**Comment by Mcastres** [comment]
Great!

**Comment by alloyking1** [comment]
Hello @Mcastres @malgamves. The draft for this is ready. Here is a link to it on dropbox paper  [here](https://www.dropbox.com/scl/fi/7jul7978a4m7d2a8xkz83/Build-a-Strapi-custom-plugin.paper?dl=0&rlkey=vejistnr0d4wy3mx3pdd2rxqb)

**Comment by malgamves** [comment]
Thanks, will have a look and make comments where necessary.

**Comment by alloyking1** [comment]
Okay. Thank you. Please do. I'll be waiting for your response.
