### ISSUE TITLE
Creating a Blog Post app with Strapi, GraphQL, and React Native (Part 1: editor's UI)

### ISSUE THREAD

**Issue by leviOnNet** [strapi/community-content#1474]
### What is your article idea?

**Introduction**
In this part, we will set up a Strapi backend and a React Native app, and implement the Create, Read, Update, and Delete (CRUD) operations for blog post editors.

**Prerequisites**
Basic knowledge of React Native
Familiarity with Strapi and GraphQL
Node.js and npm installed
Setting Up Strapi

**Setting Up the React Native App**
creating the UI for editors to manage posts

**Implementing CRUD Operations**
1. Create Operation
2. Read Operation
3. Update Operation
4. Delete Operation

**Testing CRUD Operations**
testing the CRUD operations on the app

**conclusion**
final thoughts 

### What are the objectives of your article?

Setting up Strapi.
Creating React Native app.
creating crud operations against a Strapi database.
Integrating Strapi and React Native using GraphQL.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by leviOnNet** [comment]
hi @Theodore-Kelechukwu-Onyejiaku, I just submitted another proposal.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @leviOnNet ,

At the moment, we won't be accepting this as we have similar related blog posts.
