### ISSUE TITLE
Creating a Blog Post app with Strapi, GraphQL, and React Native (Part 2: User's UI) 

### ISSUE THREAD

**Issue by leviOnNet** [strapi/community-content#1475]
### What is your article idea?

**Introduction**
In this part, we will implement user authentication to protect the blog posts and ensure that only authenticated users can view them. We will also ensure that the application looks professional and elegant.

**Setting Up User Authentication in Strapi**
1. Install Strapi Users & Permissions Plugin
2. Configure Roles and Permissions
3. Register and Login Endpoints

**Setting Up the React Native App for Authentication**
1. Install Axios for HTTP Requests
2. Create Authentication Service
3. Create Authentication Context
4. Login and Register Screens

Protecting Routes and Displaying Posts
1. Protected Route Component
2. Update Navigation to Include Authentication Screens

**Setting Up the Display Component**
1. Create Query for Fetching Posts
6. Posts List Component

**Styling the Application for a Professional Look**
1. Global Styles
3. Applying Global Styles

**Conclusion**
final thoughts

### What are the objectives of your article?

Strapi authentication.
React Native authentication.
Protecting routes.
Styling React Native Components.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @leviOnNet ,

We won't be accepting this because we have similar related blog posts. We don't accept posting different blog series outline. Propose an outline and we will work on it together. Thank you! Can't wait to see your contribution.
