### ISSUE TITLE
Submission request: Exploring Strapi v5: The 5 Most Anticipated New Features

### ISSUE THREAD

**Issue by omikulcik** [strapi/community-content#1477]
**Submission request: Exploring Strapi v5: The 5 Most Anticipated New Features**

Hello, I am Ondřej from Notum.

We have recently published an [article about the 5 most anticipated features coming in v5](https://medium.com/@notum/exploring-strapi-v5-the-5-most-anticipated-new-features-cd83ae1411ee). And soon there will also be a video. If we could get it published on any Strapi channels it would be great!

There is also another one about [test migration to v5](https://medium.com/@notum/how-we-migrated-a-simple-production-project-to-strapi-v5-514a54d5348b) and [video](https://www.youtube.com/watch?v=wNnz9NykEos) with the same content is already published

Thank you.

**Comment by PaulBratslavsky** [comment]
Thanks, @omikulcik @Theodore-Kelechukwu-Onyejiaku. Can you repost this article on our Twitter and LinkedIn pages while I am away?

@omikulcik I will be back this Wednesday when you have the video ready.  Share it with me, and I will add it to our YT channel and your post to our blog simultaneously.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky ,

Will do so shortly. Thanks.

**Comment by omikulcik** [comment]
Hi @PaulBratslavsky, here is the new video [https://www.youtube.com/watch?v=SYWA5EDvgvw](https://www.youtube.com/watch?v=SYWA5EDvgvw). If you need the source it is here [https://drive.google.com/file/d/16I5lmM2ESkXP2CeeLpYyb3RCCfYkoCH9/view?usp=sharing](https://drive.google.com/file/d/16I5lmM2ESkXP2CeeLpYyb3RCCfYkoCH9/view?usp=sharing). Thanks for sharing! :)

**Comment by PaulBratslavsky** [comment]
@omikulcik, that's okay. Perfect. I will repost your blog post and video on our YT channel and Blog and let you know when it goes live.

**Comment by PaulBratslavsky** [comment]
Hey @omikulcik we have published your post and linked to the videos. 

https://strapi.io/blog/the-5-most-anticipated-new-features-in-strapi-5

I also linked to the post about migration tool, it was very insightful post.  Mentioned to Derrick, he will reach out to schedule a mini feedback session on the process.
