### ISSUE TITLE
Building a Video Conference Online Learning Platform with React.js, Strapi and Zegocloud 

### ISSUE THREAD

**Issue by okosaleo** [strapi/community-content#1484]
### What is your article idea?

This article will be a tutorial showing readers how to use three technologies. React.js for creating user interfaces, using Strapi to design the data Model for users and Zegocloud to enable live video conferencing on our web app. An explanation of the overall architecture of the application.

### Introduction
1. Brief overview of the importance of online learning platforms.
2. Introduction to the technologies: React.js, Strapi, and Zegocloud.
3. Purpose and scope of the article.

### Section 1: Project Setup
1. Prerequisites: Basic knowledge of React.js, Strapi, and Zegocloud.
2. Setting up the development environment.
3. Installing Node.js and npm.
4. Initializing a new React.js project.
5. Setting up Strapi as the backend CMS.

### Section 2: Integrating Strapi
1. Overview of Strapi and its benefits for content management.
2. Setting up Strapi project.
3. Creating and managing content types (e.g., courses, teachers, students).
4. Connecting Strapi with React.js front end.
Section 3: Implementing Zegocloud for Video Conferencing
Introduction to Zegocloud and its features.

### Setting up Zegocloud account and obtaining API keys.
1. Integrating Zegocloud SDK with React.js.
2. Creating video conferencing components (e.g., video call, chat, screen sharing).

### Section 4: Building the Frontend with React.js
1. Structuring the React.js application.
2. Creating reusable components (e.g., navigation bar, course list, lesson details).
4. Connecting the front end with Strapi and Zegocloud.

### Section 5: User Authentication and Authorization
1. Setting up user authentication with Strapi.
2. Implementing role-based access control for different user types (e.g., students, instructors).

### Conclusion
Benefits of the completed video conference online learning platform and recap of key points.

### What are the objectives of your article?

1. Building User Interfaces with React.js
4. Using Strapi to design the data model for users of our web app.
7. Using Zegocloud as a tool for live video conferencing.
8. Building a product that can be used at different organizations and that is in demand.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by vcoisne** [comment]
Hello! We're already discussing with several writer about an LMS tutorial. So I will go ahead and close this one but feel free to suggest new topics.
