### ISSUE TITLE
Build a Strapi Powered WebNote Keeper Chrome Extension

### ISSUE THREAD

**Issue by jaybharadia** [strapi/community-content#1500]
### What is your article idea?

The idea is to create a Chrome extension called "WebNote Keeper" that allows users to save notes related to webpages they visit. The extension will leverage Strapi as the backend CMS to store and manage these notes. 

When a user clicks the extension while browsing a webpage, it will automatically capture the URL of the current webpage and prompt the user to add a note. Users will be able to view, edit, and delete their notes directly from the extension's interface. 

The extension will integrate with Strapi API for CRUD operations on notes. This project combines the use of Strapi as a headless CMS and Chrome extension development skills to create a practical tool for users to organize their web research and thoughts.

TECH STACK
- Vue.js
- Vite bundler
- REST API
- HTML CSS
- Cookies

MODULES & Screens
- Login
- Signup
- Notes
- Edit Note
- Delete Note

### What are the objectives of your article?

Readers will learn 
- Strapi Integration
- Vue.js
- Chrome Extension Development
- Strapi API Integration
- User Interface Design

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Use cases and case studies

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @jaybharadia ,

This sounds interesting. Could you please use Strapi V5?

**Comment by jaybharadia** [comment]
> Hi @jaybharadia ,
> 
> This sounds interesting. Could you please use Strapi V5?
> 

Sounds Good 👍 Strapi v5 will be used for this project

**Comment by jaybharadia** [comment]
@Theodore-Kelechukwu-Onyejiaku  I am not assigned yet. Waiting for your confirmation...

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @jaybharadia ,

Please proceed. I just realized this 😅: https://github.com/directus-labs/guest-authoring/issues/102

Thank you!

**Comment by jaybharadia** [comment]
@Theodore-Kelechukwu-Onyejiaku 
✅ Project is ready for review. 
- Here is the article draft link https://jaybharadia.hashnode.dev/preview/66b985f73d1c6631003bb2b5
- Project link https://github.com/jaybharadia/strapi-webnote-keeper-extension

**Comment by jaybharadia** [comment]
@Theodore-Kelechukwu-Onyejiaku Any feedback ? Let me know once you are available for review

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @jaybharadia!

I will add this to the review backlog. Thank you! 

We have been a bit busy with Strapi 5 release. But our time should clear up starting next week.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @jaybharadia ,

I just skimmed through your work. Please go through our writing guidelines.

We use HackMd for drafts. And we do not publish articles on other blogs. 

Please let me know if you have any questions.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
I will have to close this since it has been published on another blog.
