### ISSUE TITLE
Developing a Personalized Learning Companion for Kids with Strapi, Next.js, and AI

### ISSUE THREAD

**Issue by Arbanus54** [strapi/community-content#1511]
### What is your article idea?

In the article, I will take the readers through a roadmap for creating a learning companion application for kids using Strapi, Next.js, and Artificial Intelligence. Each child will be given a chance to learn at their own pace, and the platform will provide additional activities they will enjoy while learning. These will include the users’ profiles, progress monitoring, suggestions of the contents, learning activities, game aspects, and a control panel.

### What are the objectives of your article?

The article will cover the following steps:
Setting up a backend using Strapi as the platform for managing users and learning content.
Creating a front using Next.js to develop a well-optimized and good-looking application.
Applying AI algorithms to understand better the user and their needs to guide them on the best path to success.
Providing a solution to incorporate elements of fun and games into learning by incorporating activities into the online course.
The incorporation of parental controls enables the parents to monitor the progress of the child as well as blocklist specific content.

### What is your expertise as a developer or writer?

Advance

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Arbanus54 ,

Thanks for your article outline. At the moment, we are not accepting this.
