### ISSUE TITLE
Client-based Search on Strapi Static Sites with Next.js, Fuse.js, and Cloudflare

### ISSUE THREAD

**Issue by win-ne** [strapi/community-content#1512]
### What is your article idea?

Strapi provides a host of search APIs. There are also several third-party services that one could integrate Strapi with for more fine-grained search functionality like Algolia. But I was hoping to propose an alternative search method that is client-based, that does not rely on external calls to Strapi or any third-party services, has great performance, and would work well with static sites that host Strapi content. 

### 1. Introduction
* Importance of search and filtering as features
* Use cases for search
* Benefits of forgoing third-party search services
* Limitations for this kind of search
* Introduce real-life example to illustrate search - a publication
* Introduce fuse
### 2. Setup up your Strapi backend
* Create a Strapi backend
* Setup several related multi-field Strapi content types
* Adding Strapi webhooks for different events
* Add sample data to search
### 3. Setting up your Next.js app
* Building and updating a search index for faster search
* Make a service to handle search
* Creating a search results page 
* Creating a filtering component
### 4. Deployment
* Setup deployment on Cloudflare
* Create a deployment hook to rebuild site and index when Strapi content changes 
* Setup caching for the index
### 5. Conclusion
* Summarize what was covered in the article
* Highlight key takeaways from the tutorial
* Mention a point or two about Strapi and its features

### Technologies
* Strapi V5 - as the headless CMS
* Next.js - as the frontend and for generating an SSG site
* Fuse.js - to provide search and search indexing functionality
* Cloudflare - for hosting
* Tailwind - for styling

### User Story
A publication reader would want to search for content by titles, keywords, authors, tags, and categories so that they can quickly find content that matches their interests. They need a quick and seamless search experience that allows them to filter results based on multiple criteria. This will help them easily discover relevant content without navigating through multiple pages.

### Article Objectives
- Provide alternatives to external search services and search calls to Strapi that work well for static sites
- Illustrate a more straightforward versatile means to search Strapi content with an easier learning curve
- Help developers cut costs and improve performance in their applications when it comes to search

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @winnie-n ,

Thanks for your article outline. I can't wait to see more of your contributions 🚀

I think your suggestions looks similar to these: 
* https://strapi.io/blog/deep-filtering-alpha-26
* https://strapi.io/blog/demystifying-strapi-s-populate-and-filtering

Please let me know if I am missing something. Thank you,

**Comment by winnie-n** [comment]
You're right @Theodore-Kelechukwu-Onyejiaku . Really appreciate your feedback and the catch. I'll review the blog more carefully be for proposing and idea. Thank again. Closing it now.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you @winnie-n .

Please feel free to propose another one in the future. Thank you!

**Comment by winnie-n** [comment]
Hey @Theodore-Kelechukwu-Onyejiaku. 

Apologies for the typos in my earlier message. I was in a bit of a hurry.

I read through both the articles you linked and thought about how the search and filtering could differ from what was covered in those. I was thinking about covering a different angle. 

The search and filter features I'm proposing would work great on statically generated sites like, for example, publications, news sites, lifestyle blogs, and static e-commerce storefronts. No need to make external requests to the Strapi API to perform the searches. It will be all local. Since many content sites opt for SSG for better performance, I think it would appeal to developers who work on these kinds of Jamstack sites. The search index is only updated and generated as a static asset when content is modified and the site is rebuilt, which happens anyway.   

I think changing the title to `Local Multi-field Search and Filtering on Strapi Content for Static Next.js Sites Without Third-Party Services or External Calls`. I can rework the title if it sounds weird. What do you think?

**Comment by winnie-n** [comment]
If you like the new angle, I can revise the outline to cover updates regarding static sites, deployment, and setting up deployment hooks for the static sites. Looking forward to your feedback.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @winnie-n , thank you.

Could you please elaborate on "with the search index updated and generated as a static asset whenever content changes and the site is rebuilt."

Also, previously, were you intending on adding indexes to Strapi? And what will be the purpose of Fuse.js and Cloudflare?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
This sounds interested. Please proceed.

Please don't forget to use Strapi 5. Thank you. 

Meanwhile, you can please update the title of this article idea to reflect the purpose of your work.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @winnie-n , please would you be willing to turn in this article by this week or next?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @win-ne ,

Trust you are doing well. Could you please ping me the following on Discord:

* Full Name
* Photo
* Email Address
* Bio
* Job Title
* Twitter Handle

Thank you for your contribution! 💪

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @win-ne ,

Trust you are doing great. Just to remind you of the messages above. Thank you.
