### ISSUE TITLE
NextJs Optimisation Techniques 

### ISSUE THREAD

**Issue by ArafatAbdussalam** [strapi/community-content#1519]
### What is your article idea?

This article entails how to improve user interaction using Interaction to Next Paint, a metric for measuring responsiveness of web applications. It explains one of the core vitals of web performance.

What are the objectives of your article?

Content Outline:
- Introduction 
- Overview of web performance 
- Overview of User Interaction
- What is Interaction to Next Paint (INP)?
- Measuring INP
- Understanding INP Score
- Causes of Low INP Score
- How to Improve INP Score
- Improving INP Score in NextJs using Hydration and Suspense
- Conclusion 

### What are the objectives of your article?

Web performance, User Interaction, Latency, Responsiveness 

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Best Practices

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by ArafatAbdussalam** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku I will like you to give your opinion on this proposed article.

Thanks.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Will get back to you on this soon. I am thinking of making this topic to include other Next.js optimization techniques. Please hold on.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @ArafatAbdussalam ,

I am back! How about we talk about "Next.js Optimization Techniques". Please as part of the techniques, we would love it if you include "URL redirects".

This is an in-house requested content, therefore it should be very outstanding 🙂.

Please let me know if you are willing to proceed. Thank you.

**Comment by ArafatAbdussalam** [comment]
Alright. Accepted.

Does the article need code examples?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Sure, it does. That is one of the ingredients of a great article.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Here are examples:

1. https://www.freecodecamp.org/news/next-js-performance-optimization/
2. Here is one I wrote for Turing which ranks well: https://www.turing.com/kb/optimizing-build-performance-in-nextjs

Please let me know if you are willing to proceed.

**Comment by ArafatAbdussalam** [comment]
Alright. I create an outline proposal

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you. I will be waiting.

**Comment by ArafatAbdussalam** [comment]
### Optimisation Techniques in NextJs

- Introduction
- ⁠Overview of User Interactivity 
    - Speed
    -  ⁠User Experience 
- ⁠Factors Affecting Web Performance
    - ⁠Huge multimedia file size
    - ⁠URL Redirect 
    - ⁠Network Request
    - ⁠Memory usage
- Optimisation Techniques in NextJs
    - ⁠Adjust the size of images with built-in Image component 
    - ⁠Enhance video display with built-in Video component 
    - ⁠Minimize external fonts download
    - ⁠Implement lazy loady strategies 
- ⁠Measuring web performance 
    - ⁠Core Web Vitals
    - ⁠Observability and Monitoring 
- ⁠Conclusion

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Please procceed. I will let you know if I need anything else.

**Comment by ArafatAbdussalam** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 

Here is a final draft of the article:

https://hackmd.io/XEJmH-g0SS6qIVa1qNjqog?edit

I will like to request for your feedback.

**Comment by ArafatAbdussalam** [comment]
Thanks for the feedback. I have done that.

**Comment by ArafatAbdussalam** [comment]
![blurDataURL](https://github.com/user-attachments/assets/091eb8e0-7c97-40db-afad-efdaf14aa7ca)

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
This has been published. Thank you for your contribution! 🚀
