### ISSUE TITLE
[TOPIC] Gridsome and Strapi

### ISSUE THREAD

**Issue by bastianhilton** [strapi/community-content#152]
**My Request**
What tutorial/article would you like to see?
I would like to see a blog site created with Gridsome and Strapi. Possibly to include a mutation so i can see how to add content from the frontend to the backend(strapi).

Things i struggle with are:
Making proper links via Graphql to templates in Gridsome using Strapi
Showing images as all my images show blank
Mutations for things like creating a form with Gridsome and Strapi.

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by malgamves** [comment]
Hey @remi2j just checking. Is this being worked on?

**Comment by remi2j** [comment]
Yes that's the next thing on my plate. "Strapi + Gridsome portfolio starter" should be out next week

**Comment by malgamves** [comment]
Awesome! Can't wait to see it 👍

**Comment by remi2j** [comment]
Here it is: [https://github.com/strapi/strapi-starter-gridsome-portfolio](https://github.com/strapi/strapi-starter-gridsome-portfolio)

**Comment by bastianhilton** [comment]
Thank you for this starter. One question though if you have more than one page template like found in your gridsome.server.js how do you go about adding them

Sebastian Hilton

________________________________

**Comment by remi2j** [comment]
@bastianhilton let's say you want to add a template for articles, in addition to projects. I think in the `gridsome.server.js`, the `api.createPages` method would look like this:

```js
api.createPages(async ({ createPage, graphql }) => {
    // Use the Pages API here: https://gridsome.org/docs/pages-api/
    const { data } = await graphql(`{
      strapi {
        projects {
          slug
        }
        articles {
          slug
        }
      }
    }`)

    // Create a page for each project
    data.strapi.projects.forEach((project) => {
      createPage({
        path: `/project/${project.slug}`,
        component: './src/templates/Project.vue',
        context: {
          slug: project.slug,
        },
      })
    })

    // Create a page for each article
    data.strapi.articles.forEach((article) => {
      createPage({
        path: `/article/${article.slug}`,
        component: './src/templates/Article.vue',
        context: {
          slug: article.slug,
        },
      })
    })
```

That would be after you create the `Article.vue` template.

---

I'm closing the issue since we have provided the starter. If you have more issues or questions, please submit them on the [starter's repo](https://github.com/strapi/strapi-starter-gridsome-portfolio)
