### ISSUE TITLE
Video Sharing Platform with User Subscriptions with Strapi, MongoDB, and Angular.js

### ISSUE THREAD

**Issue by preshenv** [strapi/community-content#1535]
### What is your article idea?

Build a YouTube-like platform where users can upload videos, subscribe to channels, and interact through comments. Implement advanced user permissions to manage video content and subscriber access using Angular.js and MongoDB.

### Features:
- Video uploads with categorization
- User subscriptions and notifications
- Comment and like the system
- Lifecycle hooks to track video views and interactions

### 1.1. Initialize the Project
- Set up a new Strapi project with MongoDB as the database.
- Install and configure Angular.js for the frontend.

### 1.2. Basic Configuration
- Set up environment variables for database connections.
- Configure Strapi plugins needed for file uploads, user authentication, and permissions.

### 2.1. User Model Customization
- Extend the default `User` model to include fields for profile information, subscriptions, and user roles.
- Implement custom roles (e.g., Admin, Uploader, Viewer).

### 2.2. Video Model
- Define a `Video` collection with fields like `title`, `description`, `category`, `uploader`, `views`, and `likes`.
- Set up relations:
  - `Uploader` (many-to-one with `User`).
  - `Categories` (many-to-many with a `Category` collection).
  - `Comments` (one-to-many with `Comment` collection).
  - `Likes` (many-to-many with `User`).

### 2.3. Category Model
- Create a `Category` collection for video categorization.
- Include fields for `name` and `description`.

### 2.4. Comment and Like System
- Define a `Comment` model with fields for `content`, `user`, and `video`.
- Set up a relation between `Comment` and `Video`.
- Implement a like system using a relation between `Video` and `User`.

### 2.5. Subscription System
- Extend the `User` model to include a `subscribers` field (many-to-many relation with other `User` models).
- Implement logic for subscribing/unsubscribing from a channel.
- Use lifecycle hooks to send notifications when a user subscribes or uploads a video.

### 2.6. Lifecycle Hooks
- Implement hooks for tracking video views:
  - `beforeCreate` for initializing view count.
  - `afterCreate` or `beforeUpdate` for incrementing view count on play.
- Implement hooks to manage notifications for new subscribers or video uploads.

### 3.1. User Authentication
- Set up user login, signup, and profile management.
- Implement JWT-based authentication with Strapi.

### 3.2. Video Upload and Management
- Create components for video uploads, including file handling and metadata input.
- Implement video categorization and display on the frontend.
- Provide a dashboard for uploaders to manage their videos.

### 3.3. Video Playback and Interaction
- Build a video playback component.
- Integrate the comment system below the video player.
- Implement like/dislike buttons with real-time updates.

### 3.4. User Subscriptions
- Develop a subscription button component for user channels.
- Display a list of subscribed channels on the user profile page.
- Show a feed of new videos from subscribed channels on the home page.

### 3.5. Notifications
- Create a notification component for new subscribers and video uploads.
- Use real-time updates to notify users of new content.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by preshenv** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 

Please let me know if this is a good fit

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @preshenv ,

Sorry, we are not accepting this at the moment. By the way, Strapi doesn't have support and integration for MongoDB.

Feel free to propose another one. Thank you.
