### ISSUE TITLE
How to build a Recipe App with Next.js and Strapi v5

### ISSUE THREAD

**Issue by TJ324694** [strapi/community-content#1540]
### What is your article idea?

This article will walk readers through the process of creating a fully functional recipe app using Next.js for the frontend and Strapi v5 for the backend. The app will allow users to browse, filter, and view detailed recipes, all managed through a Strapi-powered CMS. The tutorial will cover everything from setting up the development environment to deploying the finished application.

### What are the objectives of your article?

- Guide readers through setting up Strapi v5 to manage recipe content, including ingredients, steps, and categories.
- Teach how to create API endpoints in Strapi to fetch and filter recipes.
- Demonstrate building a Next.js frontend to display and filter recipes dynamically.
- Explain how to implement dynamic routing in Next.js for individual recipe pages.
- Show how to enhance the UI using TailwindCSS and ShadCN UI components.
- Provide instructions on deploying the completed recipe app.

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by TJ324694** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku,

I would like to work on this topic. Please let me know if that’s okay, so I can provide the outline for it.

Thanks,
TJ

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @TJ324694 ,

We are not interested in this at the moment.
