### ISSUE TITLE
[TOPIC] Strapi starter React blog v2

### ISSUE THREAD

**Issue by lelouchB** [strapi/community-content#155]
**My Request**
React version of this article
https://strapi.io/blog/strapi-starter-gatsby-blog-v2?utm_content=135721540&utm_medium=social&utm_source=twitter&hss_channel=tw-3832252517

I can  write this article. 
Here are my writing samples
https://www.freecodecamp.org/news/author/ashutosh/
https://dzone.com/users/3800520/lelouchb.html
https://medium.com/@lelouchb

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by Mcastres** [comment]
Hello @lelouchB! 
That would be awesome! I'm sure Vue.js developers would love it!

Making such an article requires to use the same [backend](https://github.com/strapi/strapi-starter-gatsby-blog-v2/tree/master/backend) for Strapi. Concerning Vue.js, you are free to use what you want but it has to be the simplest way of doing it :)

Are you present on our [Slack](https://slack.strapi.io/) ? Please send me a DM to discuss about it (Maxime Castres)

**Comment by malgamves** [comment]
Hey @lelouchB just checking to see if there is any progress on this.

**Comment by lelouchB** [comment]
Hi @malgamves 
I am working on this and I hope to submit the first draft by 20-25 August.

**Comment by lelouchB** [comment]
Hi @malgamves 
I am working on this and I hope to submit the first draft by 20-25 August.

**Comment by malgamves** [comment]
Awesome! Can't wait to take a look 👍

**Comment by malgamves** [comment]
Hey @lelouchB noticed you closed this. Did you finish it up already?
