### ISSUE TITLE
Build a decentralized knowledgebase bot with Strapi, XMPT and Galadriel

### ISSUE THREAD

**Issue by maxiggle** [strapi/community-content#1565]
### What is your article idea?

The idea is to build an AI bot knowledgebase that users can chat with on website while utilizing Strapi's friendly user interface to create, update and store these content on the blockhain.

### What are the objectives of your article?

# What readers will learn
- Learn to integrate Strapi with blockchain technology
- Learn to write smart contracts that communicate with LLM oracles
- Learn to create secure chat system with XMTP
- How to work with decentralized storage systems like ipfs
- Learn how to connects all the components to create an functional bot

# Introduction

- What is a decentralized knowledgebase bot?
- Why use Strapi, IPFS, and XMTP?
- What You'll Learn (detailed section below)

## Prerequisites

- Required software and accounts (including Ethereum wallet)
- Basic knowledge requirements
- Setting Up the Project

## Building the project
- Creating a new Strapi project
- Configuring the Article content type
Integrating IPFS

- Installing IPFS HTTP client
- Creating an IPFS service in Strapi
- Modifying Strapi Controllers

- Updating the Article controller to use IPFS
- Building the XMTP Bot

- Setting up XMTP client
- Creating the XMTP bot script
- Connecting the Bot to Strapi and IPFS

- Retrieving and displaying article content

- Creating test articles in Strapi
- Interacting with the bot using XMTP
- Advanced Topics and Next Steps
- Implementing user authentication with accounts abstraction

Conclusion

### What is your expertise as a developer or writer?

Advance

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @maxiggle ,

We are not interested in this at the moment, We have similar blog posts covering these features. I would suggest topics or tutorials around Strapi internals and customizations, with integrations of other technologies.
