### ISSUE TITLE
How to Build an Event Listing App with Strapi and React Native

### ISSUE THREAD

**Issue by Oluwoleopeyemi** [strapi/community-content#1578]
### What is your article idea?

In this tutorial, we’ll walk through how to build an event listing app using Strapi and React Native.  Strapi serves as the backend, where events are created and stored. On the frontend, React Native will be used to fetch and display this event information in a mobile app. The app will feature a list of upcoming events and users will be able to search for events and filter through some categories. This tutorial will teach readers how to build their own event listing app.

### What are the objectives of your article?

Introduction
 A brief introduction on how Strapi can be used with React Native to create a responsive event listing app.

Section 1: Setting Up Strapi
Install Strapi: This section features how to install Strapi.
Create Strapi Collection types: we will define the data structure for our app.
Configure Permissions: To ensure public access is granted to event data so the app can retrieve it.
Add Sample Events: Insert some event records in Strapi for testing.
Section 2: Creating the API Connection
Configure API URL: Set up the API URL in Strapi so it can be consumed by the React Native app.
Test API: In here, we will use tools like Postman to verify that the API is returning event data correctly.
Section 3: Setting Up React Native
Initialize React Native Project: Create a new React Native project. 
Install Axios: Install Axios to make API requests from the app to Strapi.
Create Event List Screen: Fetch event data from Strapi and display it in a FlatList component in React Native.
Section 4: Adding Search and Filter Functionality
Implement Search: Add a search bar to allow users to filter events by name.
Add Category Filter: Use the Picker component to enable users to filter events by category.
Section 5: Style
Basic Styling: We will add simple styles to improve the visual appearance of the app.
Handle Loading and Errors: Add functionality to show a loading spinner when fetching data and display error messages if something goes wrong.
Conclusion
Recap

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by SAMBILI** [comment]
I think this will help you.

https://bit.ly/3TCbXO6

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @Oluwoleopeyemi,

Thank you for your interest! Due to the high volume of submissions, we're currently pausing new article submissions. However, we'd love for you to explore the existing articles labeled "Looking for Author" and choose one that interests you.
