### ISSUE TITLE
Building a Real-Time Voting System with Strapi v5 and InstantDB

### ISSUE THREAD

**Issue by miracleonyenma** [strapi/community-content#1582]
### What is your article idea?

The article will provide a comprehensive tutorial on building a real-time voting system using Strapi v5 and InstantDB. Strapi will be customized to manage polls, user permissions, and results tracking, while InstantDB will handle real-time voting updates and display live results instantly. This project is ideal for developers looking to integrate real-time capabilities into their applications, especially for polls, surveys, or event-based voting.

Key technologies:

- Strapi v5 for creating and managing polls, users, and permissions, as well as handling custom routes and API extensions.
- InstantDB for real-time data synchronization, ensuring that vote submissions and results update dynamically across all connected clients.
- Next.js as the frontend framework for rendering the voting interface and live results.

Outline:

- Introduction: Overview of the real-time voting system use case and technologies.
- Setting up Strapi v5: Install and configure Strapi to manage users and polls.
    - Customizing Strapi models to handle poll creation, options, and vote tracking.
    - Extending Strapi routes to handle vote submission.
- Integrating InstantDB: Connect InstantDB for real-time vote synchronization.
    - Setting up InstantDB and creating real-time updates for poll submissions.
- Building the Frontend with Next.js: Creating a simple voting interface with real-time results display.
    - Integrating the frontend with Strapi and InstantDB.
    - Handling real-time updates on the client side with live vote count and percentage display.
- Finishing Touches: Authentication, security measures, and deploying the system.

### What are the objectives of your article?

The key learning outcomes for the reader are:

- How to customize Strapi v5 to manage polls and handle voting logic with API extensions.
- How to integrate InstantDB for real-time synchronization, ensuring votes are instantly reflected across all clients.
- Building a voting interface using Next.js that dynamically updates as votes are cast.
- Understanding how to build scalable real-time applications using Strapi and InstantDB for projects that require live user interaction (e.g., polls, surveys, or quizzes).

### What is your expertise as a developer or writer?

Intermediate

### What type of post is this?

Tutorial

### Terms & Conditions

- [X] I have read the Write for the Community program guidelines.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @miracleonyenma ,

Please proceed. Thank you!

**Comment by miracleonyenma** [comment]
Hi @Theodore-Kelechukwu-Onyejiaku 

Thanks for your patience. Here's my draft submission:
Building a Real-Time Voting System with Strapi v5 and InstantDB - Part 1 - https://hackmd.io/@miracleio/H14ZwSYR0
Building a Real-Time Voting System with Strapi v5 and InstantDB - Part 2 - https://hackmd.io/@miracleio/H1TR7vYAA

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @miracleonyenma ,

Could you please give me access to the drafts?

**Comment by miracleonyenma** [comment]
Thanks for informing me @Theodore-Kelechukwu-Onyejiaku. I've invited you to the document ✅

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thank you. 

I have also tested your code. The votes are not changing instantly, but require reload. Please fix. Thank you.
