### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by dwoodman2008** [strapi/community-content#159]
Are there any guides to using strapi with eleventy

**Comment by malgamves** [comment]
Hey @dwoodman2008  a community member wrote this article - [Eleventy(11ty) + Strapi CMS with dynamic page creating](https://medium.com/@richyinbeta/eleventy-strapi-headless-cms-with-automatic-page-creating-and-updating-86942f10c19a) 

I'll close the issue for now. If you need something a little more up to date, please re-open the issue following the issue template so someone can easily pick it up.
