### ISSUE TITLE
[UPDATE CONTENT] Delete the mention of Python from the article, as not needed

### ISSUE THREAD

**Issue by teinett** [strapi/community-content#1594]
**Article**: https://strapi.io/blog/implement-pagination-and-infinite-scrolling-in-astro-js-with-strapi

**Current text**: 

> Prerequisites
> You will need the following to get started:
> - [Node.js v18](https://nodejs.org/en) or later.
> - A code editor on your computer.
> - [Python](https://www.python.org/downloads/)

**The error**: you don't need Python for this tutorial.

**TODO**: Please delete the mention of Python from the article.

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Thanks for the catch @teinett.

I have now removed the mention.
