### ISSUE TITLE
Nuxt.js and Strapi Integration please. 

### ISSUE THREAD

**Issue by jomskidoodle** [strapi/community-content#160]
**My Request**
Nuxt.js and Strapi Integration please. 

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by malgamves** [comment]
Hello @jomskidoodle could you be more specific with your request?
Do you want content on [this](https://strapi.nuxtjs.org) Nuxt and Strapi Integration?
