### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by EslamXDR** [strapi/community-content#161]
**My resource**
Describe what your resource will be about. (tutorial or article)

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hello @EslamXDR, could you provide us with extra content what you would like your article to be about and what problems that would solve for you.

I'll close this for now. I'm happy to re-open it when you provide more context.
