### ISSUE TITLE
admin dashboard 

### ISSUE THREAD

**Issue by officialrajdeepsingh** [strapi/community-content#162]
Hey Everybody my name Rajdeep Singh.
Recently I add my friend on my website as the author but that person not access  my admin dashboard with an article Collection type

![STRAPI ADMIN PROBLEM](https://user-images.githubusercontent.com/32416397/89319991-8b643b00-d69e-11ea-855b-51deeef14038.PNG)

**Comment by malgamves** [comment]
Hey @officialrajdeepsingh could you give a little more details on what you need? Will close the issue for now. I'm more than happy to reopen it when you give more context.
