### ISSUE TITLE
[REQUEST] Explain User Roles and Permissions for Admin panel

### ISSUE THREAD

**Issue by officialrajdeepsingh** [strapi/community-content#163]
Plz, Write Article or Youtube Video On strapi Roles & Permissions.
How To Access dashboard like that stuff and most importantly how to install other people create a plugin with npm. me face a lot of issue in this Roles & Permissions and plugin installation with npm

plz any person who create an article on that topic plz tell me

**Comment by hannydevelop** [comment]
Hello @malgamves! Can I work on this as my next topic.

**Comment by Mcastres** [comment]
Hey @hannydevelop, are you still interested? Ping me if yes ;)

**Comment by hannydevelop** [comment]
Hello @Mcastres! Sure, I'm still interested.

**Comment by Mcastres** [comment]
Great! So what is the plan? Did you started to work on it already?

**Comment by hannydevelop** [comment]
Hello @Mcastres I'm working on it, the piece is almost ready.

**Comment by Mcastres** [comment]
Awesome!
