### ISSUE TITLE
[SUBMIT] Recreating Udemy lessons structure with Dynamic Zones and Components (Pt-BR)

### ISSUE THREAD

**Issue by willianjusten** [strapi/community-content#165]
**My resource**

Hey guys, I recorded a video where I show how to recreate a part of Udemy lessons using Dynamic Zones and Components. 

**My format**

- [ ] Article
- [x] Video (https://youtu.be/ReEutDvYPQY)

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hey @willianjusten thanks for the contribution 🎊
