### ISSUE TITLE
[TOPIC] Deploy Strapi on Render.com

### ISSUE THREAD

**Issue by remidej** [strapi/community-content#166]
**My Request**

Provide a tutorial to help users deploy Strapi on [Render](https://render.com/).

Render is clould platform that allows users to deploy apps from a Github repo. Is still a young product, but has grown quite fast. It would be interesting to make sure Strapi users know about it.

Unlike Netlify or Vercel, it's not limited to static or serverless apps. You can host real Node apps on it.

~~Unlike Heroku, Render's file system isn't ephemeral~~. Render's file system can be made permanent using [disks](https://render.com/docs/disks). This means we don't need external providers for the database or uploaded files.

The tutorial would likely explain how to write a [Render.yaml](https://render.com/docs/infrastructure-as-code) config file, then follow the steps on the Render dashboard to publish a project.

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by derrickmehaffy** [comment]
Something we will have to watch for, similar to Heroku is how they manage the build/start process, the filesystem lifecycle (do they wipe the Dyno like Heroku does), and if there is resource limits (CPU/RAM/ect)

**Comment by jakemalachowski** [comment]
@derrickmehaffy I work at Render.

- We offer [disks](https://render.com/docs/disks) that you can attach to your services and persist data across deploys.
- You can define your start/build commands in the `render.yaml` file. If using Docker, you can default to what's used in the Dockerfile or you can override it.  
- You can define the [plan](https://render.com/pricing) that makes sense for the resource requirements of your service.

Happy to answer any other questions.

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy I work at Render.
> 
> * We offer [disks](https://render.com/docs/disks) that you can attach to your services and persist data across deploys.
> * You can define your start/build commands in the `render.yaml` file. If using Docker, you can default to what's used in the Dockerfile or you can override it.
> * You can define the [plan](https://render.com/pricing) that makes sense for the resource requirements of your service.
> 
> Happy to answer any other questions.

Thank you very much @jakemalachowski I'll do some playing around myself and see if I can come up with any questions :wink:

**Comment by krissnawat** [comment]
@malgamves I would like to paticipant on this topic . it's should be fun

**Comment by remidej** [comment]
Thanks @krissnawat! FYI Render just published [a docs page for Strapi](https://render.com/docs/deploy-strapi) a couple of days ago.

Maybe could also add Render to the list of [hosting provider guides](https://strapi.io/documentation/v3.x/getting-started/deployment.html#hosting-provider-guides) instead of making it an article. What do you think @malgamves?

**Comment by davidmauskop** [comment]
@remidej @malgamves @derrickmehaffy @krissnawat I'm an engineer at Render and worked on our 'Deploy Strapi' doc and Strapi example repos. I'd be happy to help with this however I can. Btw, we recently added a [development -> staging -> production](https://render.com/docs/deploy-strapi#development-%E2%86%92-staging-%E2%86%92-production) section to the doc based on feedback from @pierreburgy.

**Comment by malgamves** [comment]
Thanks for that @davidmauskop, would you like to add the guide to the Strapi Docs under [hosting guide providers](https://render.com/docs/deploy-strapi) like @remidej mentioned. @derrickmehaffy could guide you on how to go about making that happen.

@krissnawat how different would your article be from the Render Guide?

**Comment by krissnawat** [comment]
@malgamves nothing different will move to this  #69

**Comment by davidmauskop** [comment]
@malgamves Absolutely!

@derrickmehaffy Should I just add the doc as part of a PR on the main strapi repo? Any other guidelines?

**Comment by derrickmehaffy** [comment]
Hi @davidmauskop 

Yup that should be fine, we can work through the PR together if you want to write it as you need now and I can suggest any changes needed. As we are kinda in the process of moving the documentation to it's own repo (and doing a massive rewrite of the docs entirely) I don't have any specific guidelines to give at the moment as we are reworking those as well.

Lets play this one by ear and just see what you can do and I'll bring in @meganelacheny to provide some of the better technical writing suggestions :)

**Comment by davidmauskop** [comment]
Sounds good @derrickmehaffy! I'll open a PR with my draft in the next few days.

**Comment by Mcastres** [comment]
Closing this as we now have a official doc for this

**Comment by desdamo** [comment]
Hello everybody, i have a question about this discussion. i created my strapi project with docker compose.
Folders :
---- / app
---- / data
---- docker-compose.yml

And i want to deploy on render but i dont find the right way because if i understood everything the database and the service are separate. can i use my dockerfile to deploy everything?? thanks for your help

**Comment by jakemalachowski** [comment]
@desdamo Can you create a post on https://community.render.com? We'd be happy to help get you set up there.
