### ISSUE TITLE
[TOPIC] How to populate/seed data into your database in both development and production.

### ISSUE THREAD

**Issue by shindosu** [strapi/community-content#169]
**My Request**
I would like to see a tutorial on how to populate/seed data into your database in both development and production. 

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by Mcastres** [comment]
Hello @shindosu we do not have a tutorial on this but you can check out how I seed data into the [Gatsby starter](https://github.com/strapi/strapi-starter-gatsby-blog-v2)

  - `./backend/config/functions/bootstrap.js` which is executed everytime you run your server: https://github.com/strapi/strapi-starter-gatsby-blog-v2/blob/master/backend/config/functions/bootstrap.js
  - `./backend/seed` data: https://github.com/strapi/strapi-starter-gatsby-blog-v2/tree/master/backend/seed

The `boostrap.js` file check if this is the first time that the server runs, if yes then it populate data into development or production database.
