### ISSUE TITLE
Audit Log/Trail with Strapi

### ISSUE THREAD

**Issue by abbeyseto** [strapi/community-content#173]
**My resource**
My article will be about creating an Audit log or trail for a Strapi Application using strapi middleware. This will enable the admin to see all requests to API routes and all other activities which include Admin page visits and all CRUD done. This will also cover visibility to public API calls by unauthenticated users.

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by lucasfrutig0** [comment]
![image](https://user-images.githubusercontent.com/47028939/90764551-d1d0b100-e2be-11ea-939e-4d7de6c2bbe7.png)
