### ISSUE TITLE
[TOPIC] Strapi installation under Traefik

### ISSUE THREAD

**Issue by carloshs94** [strapi/community-content#178]
**My Request**
What tutorial/article would you like to see?
Seems like is the only proxy left to explain in the tutorial

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by derrickmehaffy** [comment]
@Mcastres might be best to include this also within the docs similar to Nginx, HAProxy. I was not familiar enough with Traefik to write it when I made those guides.
