### ISSUE TITLE
[TOPIC] Strapi beginner to advanced tutorials

### ISSUE THREAD

**Issue by Busani-396** [strapi/community-content#185]
**My Request**
Strapi beginner to advanced tutorials

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by malgamves** [comment]
Hello @Busani-396 , could you provide us with extra context on what you would like the beginner resources to tackle.

**Comment by Mcastres** [comment]
I'm closing this since we didn't have more details about it
