### ISSUE TITLE
[SUBMIT] Deploying Strapi CMS to Azure Cloud using Docker container and CI/CD with Github

### ISSUE THREAD

**Issue by abachuk** [strapi/community-content#193]
**My resource**
In the video, I'll walk you through how to deploy Strapi from localhost to Azure Cloud using their App Service and managed MySQL database. By the end, you will have working REST and GraphQL API running in the cloud and can push the updates through git.
https://pragmaticlead.com/posts/deploying-strapi-to-azure

**My format**

- [ ] Article
- [ x] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hey @abachuk could you open a PR to add this to our tutorials resource? [Here is a guide](https://github.com/strapi/community-content/tree/master/tutorials) on how to go about doing that.

**Comment by pakwai122** [comment]
How about AWS? with best practices, use let's encrypt, split it into dev, staging and production mode. is there any friendly way to manage Strapi on AWS?

**Comment by malgamves** [comment]
Hey @pakwai122 this would be a great question for our [forum](https://forum.strapi.io)
