### ISSUE TITLE
[SUBMIT] A Great NodeJs Backend Option for Frontend Developers

### ISSUE THREAD

**Issue by cwray-tech** [strapi/community-content#197]
**My resource**
This is an article with a video sharing about Strapi CMS and why it is a great NodeJs backend option for frontend developers or no-coders. 

**My format**

- [x] Article https://dev.to/cwraytech/a-great-nodejs-backend-option-for-frontend-developers-or-no-coders-43d0
- [x] Video https://youtu.be/TF4ZWUhUC5E

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Ayye! You are on fire with the content @cwray-tech thanks. Could you open a PR to add them to the [tutorials page](https://github.com/strapi/community-content/tree/master/tutorials) on the Strapi site?

**Comment by cwray-tech** [comment]
@malgamves Do you want this to go in the tutorials, or in the articles section? Thanks a bunch!

**Comment by malgamves** [comment]
Ah yes, @cwray-tech let's get this in tutorials

**Comment by cwray-tech** [comment]
This has been published. Thanks!
