### ISSUE TITLE
[TOPIC] Build a beautiful app with NextJS and Electron, powered by a Strapi backend.

### ISSUE THREAD

**Issue by whizkidefos** [strapi/community-content#198]
**My Request**
What tutorial/article would you like to see?

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by Favouroked** [comment]
Hi @malgamves I can pick this up. Hope to hear from you soon.

**Comment by malgamves** [comment]
Hey @Favouroked sure, please follow the review and submission process in the [FAQ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46)

before you start, could you share an outline of what you think this article will look like?

**Comment by Favouroked** [comment]
Ok. Will share before the end of today

**Comment by Favouroked** [comment]
@malgamves 

Outline:
Topic: How to build a Quiz App with NextJS and Electron, powered by a Strapi backend.

- Introduction
- Requirements
- Scaffold Strapi Project - Quiz App
- Build the desktop app
- Demo - create quiz and take quiz
- Conclusion

**Comment by malgamves** [comment]
hey you could even use the Strapi [Quiz Template](https://github.com/malgamves/strapi-template-quiz) thoughts?

**Comment by Favouroked** [comment]
Sure, I will check it out

**Comment by ShadaW11** [comment]
Heyyyy @Favouroked hows it going? any update on the article?

**Comment by Favouroked** [comment]
The first draft will be available soon

**Comment by ShadaW11** [comment]
Hey @Favouroked awesome news. thank you for the update. Happy to hear from you. Looking forward to receiving the draft. Please let me know if you need any help.

**Comment by Favouroked** [comment]
Sure, thanks.

**Comment by ShadaW11** [comment]
Hey @Favouroked any update regarding the article? could you also please add your author details by registering in the form in this page [here](https://strapi.io/write-for-the-community) and please check our FAQ to go over the process for payments and article guidelines and submissions.

**Comment by ShadaW11** [comment]
Hey @Favouroked any update on the article?

**Comment by Favouroked** [comment]
Hi @ShadaW11, the first draft is ready. The final changes I'm making have to do with the SEO guidelines. I have also registered via the link you sent.

**Comment by ShadaW11** [comment]
Great so happy to hear that. @Favouroked Please share the dropbox link here once its done and ill take a look at the article.

**Comment by Favouroked** [comment]
Hi @ShadaW11, the article is [here](https://www.dropbox.com/scl/fi/bhgpspx0evgpj2myh8m3j/How-to-build-a-Quiz-App-with-NextJS-and-Electron-powered-by-a-Strapi-backend..paper?dl=0&rlkey=ceiy747j5c57b58mg43isnyvy).

**Comment by ShadaW11** [comment]
Hey @Favouroked awesome article, it will be published soon. Will keep you updated.

**Comment by Favouroked** [comment]
Thanks @ShadaW11

**Comment by ShadaW11** [comment]
Hello @Favouroked your article has been published 🎉🎉🎉 https://strapi.io/blog/how-to-build-a-quiz-app-with-next-js-electron-powered-by-a-strapi-backend 

Please check our FAQ [here](https://strapi.io/write-for-the-community) to submit your invoice and get paid. 
Also make sure you click on discussion under your blog post, register  https://forum.strapi.io/ and click on "watching" to receive automatically a notification once a new comment is made. We rely on you to supoort the community. Thank you.
