### ISSUE TITLE
[TOPIC] Universal Angular + Strapi for SSr and Seo 

### ISSUE THREAD

**Issue by JomaKar** [strapi/community-content#199]
Strapi + Universal Angular

I would like you to do a tutorial on how to mix strapi with universal angular https://angular.io/guide/universal which is the SSr solution for that js framework.

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by Lith** [comment]
Hi @JomaKar 

We have developed our project with Angular Universal and Strapi.
Which type of tutorials or articles do you want ?
- Example of implementation
- Explanation about Angular SSR and Strapi API call ?
- Step by step tutoriel ?

I'm not sure to have time to write it, but maybe give some help if need.

Thanks !

**Comment by JomaKar** [comment]
Hi @Lith ! thanks for getting in touch! Well, the first two would be awesome! an example and the explanation on how to connect with strapi api with ssr... what I had found is this: https://medium.com/@avishwakarma/server-side-rendering-using-koajs-and-angular-universal-9270fe182f41 and this PR from angular's team to develop a koa provider: https://github.com/angular/universal/pull/1714 which is still not merged. on Angular Universal the documentation is using ExpressJs, but, however as strapi uses KoaJs I could follow it. Also I believe the first tutorial I shared, is uncomplete, as it asks you to do part of Universal documentation, but, as I said, is not so helpful

**Comment by malgamves** [comment]
Hey @JomaKar thanks for being so patient on this. I think this tutorial would be awesome! 

@Lith would you like to get started on this? 

Bringing in @lucasnevespereira who just shared his portfolio built with Angular. Maybe you can take this up with help from @Lith ?

**Comment by lucasnevespereira** [comment]
> Hey @JomaKar thanks for being so patient on this. I think this tutorial would be awesome!
> 
> @Lith would you like to get started on this?
> 
> Bringing in @lucasnevespereira who just shared his portfolio built with Angular. Maybe you can take this up with help from @Lith ?

Funny u bring me up on this 'cause I was actually thinking about preparing a video tutorial and post it on Youtube.<br> Idk when it will be ready.  <br>An article could be nice as well 👍

**Comment by malgamves** [comment]
Haha amazing! Shall I assign this to you then @lucasnevespereira ? Can't wait for that video 🔥

**Comment by lucasnevespereira** [comment]
Oh I'm sorry @malgamves @JomaKar just realize you were talking about **Angular Universal**, I did not use this on my project so sorry 😅 

_But I'm still writing an article or maybe filming a video about how I did my project._

**Comment by malgamves** [comment]
Awesome! thanks for letting me know, if you'd like we can still publish the article on your project to our blog @lucasnevespereira

**Comment by octalpixel** [comment]
@mascarell I would like to take this up if it's still open.

**Comment by Mcastres** [comment]
Hey @octalpixel, it seems that this topic is free! Are you still interested?

**Comment by zaracooper** [comment]
@Mcastres @malgamves if this topic is still free, could I tackle it?

**Comment by zaracooper** [comment]
@vcoisne  if this topic is still free, could I tackle it?

**Comment by vcoisne** [comment]
@zaracooper yes it is. Could you please send an outline first ?

**Comment by zaracooper** [comment]
Here's the outline @vcoisne :

**Title:** Using Strapi with Angular Universal Apps

**Outline:**
1. Introduction
    - What server-side rendering is
    - Why choose SSR and how it affects SEO
    - What Angular Universal is and how it works
2. Setting up Strapi locally 
3. Initializing and setting up your Angular app
4. Adding services to use with Strapi 
5. Adding Angular Universal
6. Previewing the app locally
6. Conclusion

**Comment by vcoisne** [comment]
@zaracooper looks great. Please refer to our [FAQ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46) for next steps. When do you think you can have a draft by ?

**Comment by zaracooper** [comment]
Thanks, @vcoisne . I'll be down with the draft by the 30th of this month.

**Comment by zaracooper** [comment]
[Here](https://www.dropbox.com/scl/fi/74vu275qosh8a0ydignea/Draft-Using-Strapi-with-Angular-Universal-Apps.paper?dl=0&rlkey=dt6js71wyq6phw56hjyubopk9) is the draft.

**Comment by Lith** [comment]
> [Here](https://www.dropbox.com/scl/fi/74vu275qosh8a0ydignea/Draft-Using-Strapi-with-Angular-Universal-Apps.paper?dl=0&rlkey=dt6js71wyq6phw56hjyubopk9) is the draft.

Thanks :) I've request an access to look at it ^^

**Comment by zaracooper** [comment]
@Lith shared the draft with you.

**Comment by zaracooper** [comment]
@Lith did you get a chance to check out the draft?
