### ISSUE TITLE
[TOPIC] Building a Booking System with Strapi

### ISSUE THREAD

**Issue by sunsgs** [strapi/community-content#204]
**My Request**
What tutorial/article would you like to see?

I would like to understand how to build a Booking system 

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by samuelarogbonlo** [comment]
I am interested in authoring this work for the community; I have some experience working with a booking system. What're the next steps?

**Comment by Mcastres** [comment]
Hey @samuelarogbonlo, you can learn everything [here](https://www.notion.so/strapi/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46)

Ping me if you are interested and I'll assign you the topic

**Comment by alloyking1** [comment]
@samuelarogbonlo . This is an interesting topic. I can take this up @samuelarogbonlo has not started working on it already.

**Comment by number304** [comment]
I would **love** to read that article, please let me know when it's done!

**Comment by oviecodes** [comment]
Hey @malgamves , @Mcastres and @alloyking1 , what the progress on this, I could take this if no one is working on it.

**Comment by oviecodes** [comment]
Hey @malgamves  , @Mcastres and @alloyking1 , what the progress on this, I could take this if no one is working on it.

**Comment by malgamves** [comment]
hey @oviecodes I just #313 so maybe someone can take this for now. If no one does then we can get back to it after you're done

**Comment by oviecodes** [comment]
@malgamves is this project still available? I'm done with #313

**Comment by ShadaW11** [comment]
Hey @oviecodes yes, still available. If you would like to start working on it, please write an outline of what you would like to talk about?

**Comment by oviecodes** [comment]
Hey @ShadaW11 the outline for this article includes

1. Getting started with Strapi
2. Setting up our Strapi back-end
3. Setting users permission
4. Building the front-end
5. Using the Nuxt-Strapi module for authentication
6. Setting up emails using Node-mailer
7. Using templates with Node-mailer

**Comment by ShadaW11** [comment]
Hey @oviecodes thank you, would you be able to use nextjs instead of Nuxt?

**Comment by oviecodes** [comment]
Unfortunately, I'm not really familiar with Next.js, but is there anything else we could do @ShadaW11

**Comment by oviecodes** [comment]
Hey, @ShadaW11 I'm not really familiar with Next.js, I don't know if it's still ok that I use Nuxt.js on the project?

**Comment by ShadaW11** [comment]
Hey @oviecodes thank you for getting back to me, you can go ahead and use Nuxt for this tutorial.

**Comment by ShadaW11** [comment]
Hey @oviecodes any update on the article?

**Comment by oviecodes** [comment]
Hello @ShadaW11 I'll have the application and the article up by next week. Thanks

**Comment by ShadaW11** [comment]
Hey @oviecodes any update?

**Comment by oviecodes** [comment]
Hey Shada, 

here's the link to the article:

https://www.dropbox.com/scl/fi/6r1j2eyluiiqwvisf03jw/Building-a-booking-System-with-Strapi-and-Nuxt.paper?dl=0&rlkey=tfac0lhrwz2vfsix1qu6k7ssk

**Comment by oviecodes** [comment]
hey @ShadaW11, I've invited you to review the article. Hope you're having a good day?

**Comment by ShadaW11** [comment]
Hey @oviecodes thank you. Please always add a link to the article here in GitHub. Here is the [article link ](https://www.dropbox.com/scl/fi/6r1j2eyluiiqwvisf03jw/Building-a-booking-System-with-Strapi-and-Nuxt.paper?dl=0&rlkey=o5l1beliyvd1ppjejf5ngihf2) I will review the article and get back to you as soon as possible.

**Comment by ShadaW11** [comment]
Hello @oviecodes I will get back to you as soon as possible regarding the article.

**Comment by ShadaW11** [comment]
Hello @oviecodes could you please issue an invoice. Your article has been published.
