### ISSUE TITLE
[SUBMIT] How to cross-publish posts Strapi-Zapier

### ISSUE THREAD

**Issue by cwray-tech** [strapi/community-content#209]
**My resource**
This is an article/ tutorial based on the request in this issue: https://github.com/strapi/community-content/issues/131

Here is the resource: https://chriswray.dev/posts/how-to-cross-publish-posts-from-strapi-with-zapier

This can be used on the Strapi blog if you would like!

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
This is such a lovely article! Thanks for sharing If you'd like to show up on our tutorials page. Could you add it to the articles.yml file like you did in #206 @cwray-tech

**Comment by cwray-tech** [comment]
@malgamves for sure. Thank you!

**Comment by cwray-tech** [comment]
This article has been published! Thank you!
