### ISSUE TITLE
[TRANSLATE] More tutorials in Spanish

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#21]
**The tutorial I want to translate**
Some users inside the community asked for more tutorials in Spanish. If you are interested in translating an existing tutorial, feel free to comment which one!

**Community vote**
👍 Upvote if you agree

**Comment by dazmoob** [comment]
if you need help with the translation I can help with the translation

**Comment by Mcastres** [comment]
Hello @dazmoob , do you have some tutorials/articles you'd like to translate?

**Comment by dazmoob** [comment]
@Mcastres none in specific, would start with documentation that is the most recurrent

**Comment by Dev-Freak** [comment]
Hello @Mcastres , I'd like to help translating some tutorials into Spanish. Maybe some related to creating a BackEnd for a JAMstack app?

**Comment by Mcastres** [comment]
Which tutorials are referring to? :)

**Comment by Dev-Freak** [comment]
I'm talking about "Use a Custom Strapi Back-End to Build a Jamstack App", "Create a Custom Back-End for Jamstack Apps with Strapi" or "Building APIs FAST with Strapi"

**Comment by Ernesto385291** [comment]
Hola!, I would like to help with the translation of some tutorials, for example the tutorial "Learning Strapi Authentication Flows with the Facebook Provider" And many more. I love Strapi and this is a way to support. So more Spanish-speaking people like me can get to know Strapi.

**Comment by Ernesto385291** [comment]
Hola!, I would like to help with the translation of some tutorials, for example the tutorial "Learning Strapi Authentication Flows with the Facebook Provider" And many more. I love Strapi and this is a way to support. So more Spanish-speaking people like me can get to know Strapi.

**Comment by ShadaW11** [comment]
Hola, If you would like to submit any translation, you can create an issue and click on ["translate an article"](https://github.com/strapi/community-content/issues/new?assignees=&labels=In+progress&template=translate-a-resource.md&title=%5BTRANSLATE%5D) and submit your request. 

@Ernesto385291 Happy to hear this awesome feedback. Did you get a chance to work on the tutorial? If yes, please let me know once it is ready. Gracias 🙏
