### ISSUE TITLE
[TOPIC] Video on the new Draft & Publish feature

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#214]
**My Request**
I would love to see a video demonstration of our new Draft & Publish feature on a real case application

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by bigpreshy** [comment]
I'd like to make a video on this. I have recently seen it work on a little app that I did

**Comment by Mcastres** [comment]
Hey @bigpreshy, are still interested by it? Ping me if yes?

**Comment by bigpreshy** [comment]
Yes... I am still interested.

**Comment by Mcastres** [comment]
Alright, let me assign it to you then :)

**Comment by bigpreshy** [comment]
Okay...
Can we continue on Slack?

**Comment by Mcastres** [comment]
Sure!

**Comment by ShadaW11** [comment]
Hey @bigpreshy any update on this video?

**Comment by bigpreshy** [comment]
Hey @ShadaW11, my article has been  [https://strapi.io/blog/strapi-draft-system-explained](here)
Should I still make a video?

**Comment by ShadaW11** [comment]
Thank you for the update @bigpreshy no need for a video
