### ISSUE TITLE
[TOPIC] How to create a ? website with Strapi

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#215]
**My Request**
It would be awesome to have some sort of "How to create a (dating, blog, game, corporate) website with Strapi"

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by santoshyadavdev** [comment]
Hey @Mcastres, 
As discussed over mail, can you assign this to me please.

**Comment by Mcastres** [comment]
Sure! What type of website will you create with Strapi?

**Comment by santoshyadavdev** [comment]
I am planning to create my blog with it.

**Comment by Mcastres** [comment]
Hey @santoshyadavdev, just checking if there is any news about this one?

**Comment by malgamves** [comment]
hey @santoshyadavdev still interested in this??

**Comment by ShadaW11** [comment]
Hey @santoshyadavdev any update on this article?

**Comment by danielharven** [comment]
Hi, i can write an articles on how to create a blog,corporate,dating website with angular front and strapi backend. what sort of game would be expected on the game site?

**Comment by ShadaW11** [comment]
Hey @danielharven can you [create a new issue here](https://github.com/strapi/community-content/issues/new?assignees=ShadaW11&labels=In+progress&template=submit-a-resource.md&title=%5BSUBMIT%5D) with the title of your tutorial and a proposed outline? a gaming website would be a great idea.

**Comment by miracleonyenma** [comment]
Hey @Mcastres @ShadaW11 
I'm really interested in writing an article on this topic. 
I chose to go for a **corporate** website with Strapi. After doing some research, I've managed to come up with a detailed outline for the article. 
It's on _Building a Corporate Design Agency site with NuxtJS and Strapi_. 

I'll share my outline in my next comment and I'll be looking forward to hearing your feedback 😊

**Comment by miracleonyenma** [comment]
# Title: Building a Corporate Design Agency site with NuxtJS and Strapi

## Introduction

For a while, most corporate sites have been built using a traditional CMS like WordPress or Drupal. These CMSes can be seen as “monolithic” as the frontend and backend are packed into one system. Headless CMSes like Strapi allow you to decouple the two and give you the freedom to choose however you want to build your frontend. Creating a Design Agency site with pages for blogs, projects, case studies, and other content requires not only the database but also a system to easily create and manage it. Strapi handles all of that for you.

## Brief Summary

In this tutorial, we’ll quickly cover the concept of a Traditional and Headless CMS and its benefits. Then, we’ll go through the process of setting up a working Strapi instance. We’ll create all the routes, collection types, and content for our backend. Also, set up our frontend with with with Server Side Rendering for SEO, performance gains, and static hosting using NuxtJS. On our front end, we’ll connect and create the necessary routes to communicate with our Strapi backend.

## Goal

At the end of this tutorial, we would have created a complete design agency site with all the functionality on the frontend and content managed in the backend with Strapi. Readers will learn the benefits of Headless CMS and its real-world application in building Corporate sites with any frontend of choice.

## Outline

- A brief overview of Traditional and Headless CMS
  - What Strapi is

  In this section, I would briefly explain what a CMS is, and the differences between a traditional and headless CMS, what Strapi is, and how it works

- Prerequisites
  Here, I’d share what we need to follow along

- What we’re building
  Here, I’d highlight the features of the site and how we would implement them

- Set up website backend with Strapi
  - Install and configure Strapi
  - Create collection types for various content
  - Test and deploy Strapi backend

- Set up frontend with NuxtJS
  - Install and configure Nuxt and TailwindCSS
  - Create components and pages for content
  - Deployment

## Conclusion

In this section, I’d share what we’ve covered in the tutorial and how useful Strapi is in real-world applications.

## Further Reading

Here, I’ll share useful resources for readers on Strapi and related content.

_@Mcastres @ShadaW11, That's the outline. Thanks in advance for your feedback 😊_

**Comment by ShadaW11** [comment]
Hello @miracleonyenma thank you for the outline, could you mention some of the features that the website will include?

**Comment by miracleonyenma** [comment]
Hey @ShadaW11, 
Thanks for the reply.
Some of the features the website will include are:
- A collection of agency projects or works: containing images and a brief case study
- A collection of blog posts/articles
- A contact form where visitors can submit their name, email and project details to the agency

I feel these are good enough for the article, I'm open to suggestions though. 😊
Thanks.

**Comment by ShadaW11** [comment]
Hello @miracleonyenma thank you for the above. Looks good. If this is your first article, please register here https://strapi.io/write-for-the-community. Then go over the guidelines (payment, how to submit and article guidelines)

Please note that a new version of Strapi will be released in the next few weeks. Therefore, you can wait one month to use the new strapi and work on this article. Or you can work on it right now. You will get paid for your article. However, you should commit that when the new strapi is released after a month you will need to update the content and code to the new strapi v4 without additional expenses. 

Please let me know if you would like to work right now on the article or if you prefer to wait. Thank you.

**Comment by ShadaW11** [comment]
Hey @miracleonyenma yes no worries no need to use the V4.

**Comment by miracleonyenma** [comment]
Hey @ShadaW11, 
I'm done with the article draft 😊.
You can check it out here - https://www.dropbox.com/scl/fi/t1nzd1xhq4ypmbexbh2sn/How-to-build-a-Corporate-Design-Agency-site-with-NuxtJS-and-Strapi.paper?dl=0&rlkey=ytovb3idn94c5r4wmfxygektk

Thanks for being patient, I'll be expecting your feedback.

**Comment by ShadaW11** [comment]
Hello @miracleonyenma Awesome, our team will review the article content and get back to you as soon as possible.

**Comment by miracleonyenma** [comment]
Awesome! Thanks 🙌🏾

**Comment by ShadaW11** [comment]
@miracleonyenma happy new year, I wanted to check if you had time to update the tutorial with strapi v4?

**Comment by miracleonyenma** [comment]
Happy new year to you too @ShadaW11 🎆🙌🏾

Yeah, the article has been updated with v4. 
The frontend codebase has also been updated to work with v4

**Comment by ShadaW11** [comment]
@miracleonyenma our team will review it and get back to you.

**Comment by miracleonyenma** [comment]
Great! Thanks!

**Comment by ShadaW11** [comment]
@miracleonyenma awesome article, please issue your invoice. thank you
