### ISSUE TITLE
[TOPIC] How to create a Strapi app and deploy it to Heroku ?

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#218]
**My Request**
People prefer to follow deployment instructions in video rather than in writing. It can be on AWS, DO, Heroku, Azure and more...

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the article/video!

**Comment by pooyaX14** [comment]
Hi @Mcastres, I would love to write on this topic! Would you kindly assign this to me?

**Comment by Mcastres** [comment]
Hey @purnimagupta, sure! On what cloud service are you willing to deploy the app?

**Comment by purnimagupta** [comment]
Hi @Mcastres, I was thinking of choosing between Heroku or AWS. If you have a specific preference, I would like to hear that.

**Comment by Mcastres** [comment]
I think it would be better to have an AWS video as it might be more complicated than Heroku for people to deploy Strapi on

**Comment by purnimagupta** [comment]
Okay, I was thinking of writing an article with some visuals/images to begin with. Is video also necessary?

**Comment by purnimagupta** [comment]
I agree that Heroku might not be as complicated as AWS. Shall I first write an article on Heroku to begin with?

**Comment by Mcastres** [comment]
Article can be great! No need for a video actually, it really depends on you ;)
If you prefer to start with Heroku then yes :)

**Comment by purnimagupta** [comment]
Sure, thanks! I'll begin on it right away :)

**Comment by purnimagupta** [comment]
@Mcastres Do we have any preference w.r.t to the app itself, or can it be anything I like? I was thinking of going with something simple like a todo app using ReactJS (because it will be easy to show how to create one using Strapi and deploy it on Heroku). Does that look good, or do we want something else?

**Comment by Mcastres** [comment]
I think that a little bit more complex example should be better as todo list is a very used example. It would be great to have more and more different examples

**Comment by purnimagupta** [comment]
Okay. So I have a few ideas around these topics. Let me know if you find anything useful.

- This [app](https://authoring-app.purnimagupta.xyz/) is static at the moment and is deployed at Netlify. Thinking of integrating Strapi into it.

- Another one would be building a simple chat app with Strapi and socket.io, strapi being used to store and retrieve chat messages.

- Last, a simple Image uploading app, where one can upload an image from the UI, and will be stored in the database. And display the images in a grid gallery in the UI.

WDYT?

**Comment by Mcastres** [comment]
I like the second idea :)

**Comment by purnimagupta** [comment]
Cool! Okay, in-case the article length gets longer than 2000 words, would it make sense to divide it into Part 1 & 2? (I'll know for sure once I begin with the writing)

**Comment by Mcastres** [comment]
Yes it does :)
Better to split in order to not have big big article

**Comment by purnimagupta** [comment]
Hey, I'm getting an error while integrating socket with strapi server. I've posted my question on this thread: 

[https://github.com/strapi/strapi/discussions/8593](url)

Do you know how do I resolve this?

**Comment by purnimagupta** [comment]
Hey, It works now :)

**Comment by oviecodes** [comment]
Hey @Mcastres I could take up this project. I don't know if @purnimagupta is still on it

**Comment by purnimagupta** [comment]
Hey, @oviecodes, I've been a bit delayed due to interviews in between. I'm working on it. I'll have an update by next week.

**Comment by purnimagupta** [comment]
Hi @Mcastres, I've written the code for the backend and frontend and would like to put it up on Github for review? I've begun writing about it, will finish it by this weekend probably. 

Shall I push it to my Github repo? Or is there any examples directory within the Strapi repository to which I can make a PR?

**Comment by oviecodes** [comment]
hey, @purnimagupta on what platform are you writing about it. I would like to know because I don't know the platform to begin writing on. thanks in advance for the help

**Comment by purnimagupta** [comment]
Hey, do you mean which platform am I using to write?

I'm using dropbox to draft my content.

Let me know if I understood you correctly.

Best,
Purnima

**Comment by oviecodes** [comment]
Thanks a lot, @purnimagupta and yes you understood the question correctly. Does dropbox support markdown.

**Comment by purnimagupta** [comment]
Hi @Mcastres, this is a [draft ](https://www.dropbox.com/scl/fi/q8gi42xweu6q9jhxlbudg/How-to-Build-a-Real-time-Chat-Forum-using-Strapi-Socket.io-React-and-MongoDB.paper?dl=0&rlkey=6opobbj3wzl72b0b8m6761ojy)of my blog. Please let me know your feedback. I've also submitted it on the slack channel as well.

**Comment by purnimagupta** [comment]
@oviecodes Dropbox doesn't support markdown as per my knowledge.

**Comment by purnimagupta** [comment]
@Mcastres  Here is the app link - https://strapi-chat.purnimagupta.com/

**Comment by Mcastres** [comment]
Hey @purnimagupta, sorry for no seeing this. I'll review your article and your application during the week :)

**Comment by ShadaW11** [comment]
@Mcastres was the article reviewed and published?
