### ISSUE TITLE
[SUBMIT] Connecting a Strapi API to an Angular App

### ISSUE THREAD

**Issue by lucasnevespereira** [strapi/community-content#219]
**My resource**
This is an article about connecting a Strapi API to an Angular App
Resource here : https://pereiraneveslucas.medium.com/connect-custom-strapi-api-to-an-angular-app-e03ea487796e

**My format**

- [X] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by hasnentai** [comment]
@Mcastres I would love to create a Video Tutorial on this

**Comment by lucasnevespereira** [comment]
@hasnentai That would be great 👍

**Comment by Mcastres** [comment]
Hey @hasnentai, in fact it would be great but I'm not sure if we should two create pieces of content on the same same topic. It might be better to diversify

**Comment by Mcastres** [comment]
Great article @lucasnevespereira!
It's very complete!

**Comment by hasnentai** [comment]
@Mcastres Ofcourse I will be creating a simple Quiz App which will be feeding the data from strapi.
So I guess I will be a total different from the above artical.
What so you say about this idea?

**Comment by Mcastres** [comment]
Oh that is interesting in fact!
Can we have more details about this? 
  - How long will be the video?
  - Will it be published on your Youtube channel?

**Comment by hasnentai** [comment]
@Mcastres 
I consider that we need to put more fouce on Strapi Set Up right but we need to show the completion of whole app as well. which makes it more interesting.
So What I think  is we can create a two part .
My purpose for two videos is to show the complete flow.(Part 2 will be a supporting video for part 1)
1/2 - Part (Primary focus on Strapi) Contains the Configrations of Strapi and Fetching the data from strapi around 25-30 mins.
2/2 - Part (Primary founs on Front end) Styling the UI and Stuff.

**Comment by Mcastres** [comment]
Alright great! Then let's do it. Do you mind creating a dedicated issue here: https://github.com/strapi/community-content/issues/new?labels=In+progress&template=submit-a-resource.md&title=%5BSUBMIT%5D ?

**Comment by hasnentai** [comment]
@Mcastres refer #238
