### ISSUE TITLE
[SUBMIT]How to make your first open source contribution

### ISSUE THREAD

**Issue by viclotana** [strapi/community-content#227]
**My resource**
This article is in line with GitHub's HacktoberFest where people are encouraged to join communities and contribute more to open source.  This article will be a guide for beginners to open source contributions to start with their very first PR.

**My format**

- [ *] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hey @viclotana sadly this doesn't fit the requirements for articles we'll be publishing going forward. If you have any other ideas around Strapi or requests, feel free to open an issue in the repo.
