### ISSUE TITLE
[SUBMIT] Best React UI packages to use in 2020 

### ISSUE THREAD

**Issue by viclotana** [strapi/community-content#228]
**My resource**
This article will showcase a few popularly used user interface React libraries with mass adoption and actively maintained in 2020

**My format**

- [ * ] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hey @viclotana sadly this doesn't fir the requirements for articles we'll be publishing going forward. If you have any other ideas around Strapi or requests, feel free to open an issue in the repo.

Happy to talk about building full stack react applications with any of the UI libraries you were going to put in the proposed blog post.
