### ISSUE TITLE
[SUBMIT] Best Angular Component Libraries for developers  in 2020 

### ISSUE THREAD

**Issue by viclotana** [strapi/community-content#229]
**My resource**
This article will showcase a few actively maintained component libraries in Angular, most of which are open source

**My format**

- [* ] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hey @viclotana sadly this doesn't fir the requirements for articles we'll be publishing going forward. If you have any other ideas around Strapi or requests, feel free to open an issue in the repo.
