### ISSUE TITLE
[TOPIC] How to create an application using Strapi and Svelte (Sapper)

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#23]
**My Request**
There is no tutorials on how to create an application with Svelte (Sapper) and Strapi so why not be the first one to provide one for the community!

**Preferred Format**
- [x] Article
- [x] Video

**Community vote**
👍 Upvote if you need it too
🚀 If you can make the tutorial

**Comment by malgamves** [comment]
Hey, I was doing research for my article on static sites and Sapper looked so interesting I actually ended up building something similar. I could take this.

**Comment by Mcastres** [comment]
Well it seems that @Alameen688 reacted with the Rocket emoji which means that maybe he's working on it. I'll ask him right now but if he doesn't, it's yours :)

**Comment by malgamves** [comment]
Sure, let me know what he says

**Comment by jarmitage** [comment]
Just posting this here for reference:
- https://dev.to/heithemmoumni/build-a-blog-with-svelte-strapi-and-apollo-2ad5
- https://github.com/heithemmoumni/strapi-starter-svelte-blog

**Comment by Mcastres** [comment]
Thank you @jarmitage, I really appreciate! 

I landed on this Starter yesterday and started a conversation with Heithem. As the starter is not totally complete like the other ones (Gatsby, Next.js etc..) I'm therefore planning to finish it with him and making it an official starter in the Strapi organization.

What's awesome here is that @malgamves also built one using Sapper which means 2 starters are coming soon ;)

**Comment by tidiview** [comment]
Hey @Mcastres, @jarmitage jarmitage.
Seen the work of heithemmouni: looks great ☆
Just a question: 
what do you think of the choice of Apollo and GraphQL?
What about Sapper and [groq](https://nordicapis.com/review-of-groq-a-new-json-query-language/)?

**Comment by malgamves** [comment]
Hey, I'm done with writing this! 

This is the [project repo](https://github.com/malgamves/strapi-starter-minimal-sapper-blog)

I'll be sharing the blog post soon

**Comment by malgamves** [comment]
For anyone following, the post was published on [Smashing Mag](https://www.smashingmagazine.com/2020/08/static-blog-sapper-strap)

**Comment by malgamves** [comment]
This is really cool @AnandChowdhary you should add this to our [showcase](https://github.com/strapi/community-content/tree/master/showcase) 

Is your whole site powered by Strapi or just your blog?

**Comment by AnandChowdhary** [comment]
> This is really cool @AnandChowdhary you should add this to our showcase

Thanks for the tip! I've added it here: https://github.com/strapi/community-content/pull/216

> Is your whole site powered by Strapi or just your blog?

All our "content" pages are powered by Strapi, such as our blog (https://koj.co/en-ch/blog/), careers (https://koj.co/en-ch/careers/), and support (https://koj.co/en-ch/support/) sections. The "app" parts are written in Svelte.

**Comment by malgamves** [comment]
That's pretty sweet! Thanks for that 🎊

**Comment by robots4life** [comment]
https://svelte-ecommerce.netlify.app/ is a Svelte e-commerce app with a Strapi backend, the tut and code to it is the 2nd project in this course https://www.udemy.com/course/svelte-tutorial-and-projects-course/ that I like quite a bit.

Got the course some time ago and by chance I found out just now that the e-commerce app is built on a Strapi backend and quite thoroughly explained. Can only recommend it. :+1:
