### ISSUE TITLE
[SUBMIT] Introduction to GitHub's Project Board

### ISSUE THREAD

**Issue by viclotana** [strapi/community-content#230]
**My resource**
Learn all you need to easily get started with creating and effectively using Github’s free project management tool.

**My format**

- [ * ] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hey @viclotana the Write for the Community Program caters for the Strapi community, this topic submission doesn't match the content in the program. I'll close the issue - feel free to open up another one if you have a topic related to building with Strapi.
