### ISSUE TITLE
[SUBMIT] Connecting a Strapi API to an Flutter App #219

### ISSUE THREAD

**Issue by hasnentai** [strapi/community-content#235]
**My resource**

**How about if I make a video tutorial on building a Flutter E-commerce app using Strapi**

I will be covering how to connect the Strapi with the flutter and how you can use the strapi in a production and making a flutter app Live to playstore.

- [ ] Article
- [X] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by hasnentai** [comment]
@Mcastres This is my Proposal

**Comment by Mcastres** [comment]
Hey @hasnentaim sorry for the late reply. Are you planning to use our official e-commerce template: https://github.com/strapi/strapi-template-ecommerce ?

Because if yes, you can actually make a starter out of it ;)

**Comment by hasnentai** [comment]
@Mcastres I am gonna write mobile app in Flutter 
Dose it contains flutter templete ?

**Comment by hasnentai** [comment]
@Mcastres Now i Understood you are talking about back end ecommerce templete (DB's) right ?

**Comment by Mcastres** [comment]
Yes!

**Comment by Mcastres** [comment]
Hey @hasnentai, any new for this one too?

**Comment by malgamves** [comment]
hey @harshcrop still interested in this??

**Comment by hasnen712** [comment]
@malgamves I will publish by the end of this month Sorry for the delay

**Comment by malgamves** [comment]
Hey @hasnen712, please follow the review and submission process in the [FAQ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46)

**Comment by vcoisne** [comment]
@hasnen712 How are things going on this post ?
