### ISSUE TITLE
[SUBMIT] Build a Quiz App using a Strapi API with Angular

### ISSUE THREAD

**Issue by hasnentai** [strapi/community-content#238]
I will be creating a complete Video tutorial on building and configuring a strapi api with Angular.

The Tutorial will be divied into 2 parts
1. The first part will be dedicated to the strapi API configration and connnecting with the angular.
2. The second part will be dedicated to build the front end for Angular App.

This will be upload on the Youtube.
Thanks

**My format**

- [ ] Article
- [X] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by hasnentai** [comment]
@Mcastres Here is the dadicated issue.
Please assign me if possible

**Comment by Mcastres** [comment]
Let's go :)

**Comment by Mcastres** [comment]
Hey @hasnentai, any new about this one :)

**Comment by malgamves** [comment]
hey @hasnentai still interested in this??

**Comment by ShadaW11** [comment]
Hello @hasnentai any updated on this topic?

**Comment by zaracooper** [comment]
Hey @ShadaW11, 

Could I work on this? Here's an outline

Outline:
1. Introduction
    - What Strapi is
    - CRUD & Authentication on Strapi
    - How the quiz project will work
2. Set up the Strapi Server
3. Create Content Types
4. Set up Permissions
5. Generate the Angular app
6. Create user and quiz HTTP services 
7. Create sign up and login pages
8. Create quiz page
9. Conclusion

**Comment by ShadaW11** [comment]
Hey @zaracooper Great outline, yes please go ahead and start working on the article

**Comment by zaracooper** [comment]
Hey @ShadaW11. I started working on this and it turns out the scope of the project is really big. It may result in a really long article that may be 6000+ words. I was hoping to limit the scope of this article to just the quiz portion. Or if authentication with Angular and Strapi is really important, cover it in a separate article. 

Is this possible?

**Comment by ShadaW11** [comment]
Hey @zaracooper Yes, I would suggest focusing more on the quiz portion. Do you have an estimated date of delivery?

**Comment by zaracooper** [comment]
I'll have a draft for you by end of the day tomorrow @ShadaW11

**Comment by ShadaW11** [comment]
@zaracooper awesome news thank you.

**Comment by zaracooper** [comment]
@ShadaW11 [here is the draft](https://www.dropbox.com/scl/fi/r99y9ry4m96b8pr56bv49/Draft-Build-a-Quiz-App-using-a-Strapi-API-with-Angular-11.paper?dl=0&rlkey=l0vj82gux2i3o8lh6ziw7cvj6).

**Comment by zaracooper** [comment]
Hey @ShadaW11 . Did you get a chance to look at the draft linked above?

**Comment by ShadaW11** [comment]
Hey @zaracooper unfortunately I haven't reviewed the article yet but I will get back to you as soon as possible.

**Comment by ShadaW11** [comment]
@zaracooper thank you for writing the article and submitting the invoice. Payment will be issued asap. Thank you.
