### ISSUE TITLE
[SUBMIT] An Overview of Static Site Generator (HUGO)

### ISSUE THREAD

**Issue by MenakaBasker** [strapi/community-content#245]
I will be creating an overview article of static site generator fundamentals for web developers who are new to JAMstack architecture. The article consist of following ideas on brief.

1.  Introduction to Static site Generators?
2. Installation of HUGO, Creation of sites.
3. Archetypes and Layouts
4. Configuration, variables and  so on.

Thanks,
Menaka Baskar
- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by MenakaBasker** [comment]
@Mcastres Kindly assign me this if possible.

**Comment by Mcastres** [comment]
Oh that would be cool stuff!
Would you integrate HUGO with Strapi? I'm not sure there is an official integration between

**Comment by Mcastres** [comment]
Hey @MenakaBasker, is there any news about this topic?

**Comment by malgamves** [comment]
hey @MenakaBasker still interested in this??

**Comment by zaracooper** [comment]
@malgamves if this is free, could I work on it?

**Comment by zaracooper** [comment]
@vcoisne if this is free, could I work on it?

**Comment by vcoisne** [comment]
@zaracooper yes I don't think @MenakaBasker is actively working on it. Could you please send an outline first of what you have mind?

**Comment by zaracooper** [comment]
Here's the outline @vcoisne:

**Title:** A guide to using Hugo

**Outline:**
1. Introduction
    - What static site generators are
    - Benefits of using static site generators
    - Hugo overview and its features
2. Installing Hugo, generating sites, and site structure
3. Creating layouts
4. Creating and organizing content
5. Generating archetypes
6. Adding configuration, data, and static files
7. Using functions, variables, and pipes
8. Conclusion

**Comment by vcoisne** [comment]
@zaracooper thank you, looks great :) Please refer to our [FAQ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46) for the next steps. When do you think you can have a draft by ?

**Comment by zaracooper** [comment]
[Here is the draft.](https://www.dropbox.com/scl/fi/ukpdfoe6pvtgnkmqwfi1n/Draft-A-Guide-to-Using-Hugo.paper?dl=0&rlkey=q1kgy7wnqtsanymw811q8id8f)
