### ISSUE TITLE
[SUBMIT] "Building ML/Deep Learning Model To Detect Plant Diseases with Relation to Strapi"

### ISSUE THREAD

**Issue by samuelarogbonlo** [strapi/community-content#249]
**My resource**

**My format**

_- Discussing briefly the relationship between ML and DL with its direct connection to predictions and detections
- Discussing types of models to be used in this design
- Detailing the process of gathering the required data for model training
- Discussing how the models were trained; time spent, machine used, software used and other requirements
- Explaining how mobile development can be relevant in this task as well as how to implement ios/mobile applications for the operation
- Showing how to configure the models, applications and other parts of the system with the required programming languages; Python, flutter and the necessary libraries
- Testing and screenshots of models tested
- Concluding on results and making projections for other applications of the model in other fields.
-_ 

- [ ] Article

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hello @samuelarogbonlo I'm having trouble seeing where Strapi fits here. How will you use Strapi in this application?

**Comment by ShadaW11** [comment]
@samuelarogbonlo Any update on this?
