### ISSUE TITLE
[SUBMIT] Build a FullStack Ecommerce with Nextjs, Strapi, Magic and Stripe

### ISSUE THREAD

**Issue by GalloDaSballo** [strapi/community-content#253]
**My resource**
This Video is Sponsored by Magic

In this 2 hours and a half video, you'll use NextJs with Strapi, Magic, and Stripe, to build an SEO focused eCommerce store.
The site will load blazingly fast thanks to Static Site Generation.
It will use Strapi as an easy to use CMS for Products and Orders
You'll add Authentication seamlessly with Magic to store user orders and simplify the checkout process
You'll process payments with Stripe Checkout.

Video premieres tonight 8pm CET
https://youtu.be/385cpCpGRC0

**My format**

- [ ] Article
- [x] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by GalloDaSballo** [comment]
It seems like this tutorial was already merged but it's not showing on the site

**Comment by malgamves** [comment]
We'll be fixing this soon 👍
