### ISSUE TITLE
[SUBMIT] Replacing Draft.js with custom CKEditor 5 WYSIWYG editor with the media library

### ISSUE THREAD

**Issue by OssiPesonen** [strapi/community-content#257]
**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

# Replacing Draft.js with custom CKEditor 5 WYSIWYG editor with the media library

This tutorial explains how you can replace the default markdown rich text editor with a custom build of CKEditor 5 and get the Media Library working. This tutorial is actually an extension of another one, [How to change the WYSIWYG in Strapi](https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi) which is completely missing the media library integration portion.

So, to get started, I recommend everyone to go and [build a custom CKEditor 5](https://ckeditor.com/ckeditor-5/online-builder/) to your liking. Don't use the default editor, as you will run into complications if you ever want to extend your editor. The online editor allows you to select the features you like and download the entire package (development anb build) yourself. You can extend it later and just build it again. 

But anyway, please follow the steps on the tutorial above and then move on to the next portion.

### Importing your custom CKEditor 5 build

First, create a new folder for our CKEditor build, called `module`:

    extensions/content-manager/admin/src/components/CKEditor/module

Unpack your downloaded build there. This should include folders such as `build` and `src`.

*You can run `npm install` on the `module` folder so it's ready for extension and re-building if needed*.

Now, if you followed along with the first tutorial, you should have the following `index.js` file:

    extensions/content-manager/admin/src/components/CKEditor/index.js

Open it and and replace the `import ClassicEditor from '@ckeditor/ckeditor5-build-classic';` with the following:

    const ClassicEditor = require('./module/build/ckeditor');

*Recommended: You should also create a `ckeditor.css` file that you import in this file (`index.js`), and add style definitions prefixed with `.ck-content` class so you can create styles for your editor, that match your website.*

You can now edit your `CKEditor` instance how ever you like, but first let's add a component for the media library. 

Create a `MediaLibrary.js` in the same folder and import that in the `index.js `folder. This will be a basic React functional component.

```js
import React, { useEffect, useState } from 'react';
import { useStrapi, prefixFileUrlWithBackendUrl } from 'strapi-helper-plugin';
import PropTypes from 'prop-types';

/**
 * Strapi media library component which accepts a callback for the onChange event
 *
 * @param isOpen
 * @param onChange
 * @param onToggle
 * @returns {JSX.Element|null}
 * @constructor
 */
const MediaLibrary = ({ isOpen, onChange, onToggle }) => {
  const {
    strapi: {
      componentApi: { getComponent },
    },
  } = useStrapi();

  const [data, setData] = useState(null);
  const [isDisplayed, setIsDisplayed] = useState(false);

  useEffect(() => {
    if (isOpen) {
      setIsDisplayed(true);
    }
  }, [isOpen]);

  const Component = getComponent('media-library').Component;

  const handleInputChange = data => {
    if (data && Array.isArray(data)) {
      const dts = data.map(x => {
        const { name, alternativeText, url } = x;
        const alt = alternativeText || name;
        return { alt, url: prefixFileUrlWithBackendUrl(url) };
      });

      setData(dts);
    }
  };

  const handleClosed = () => {
    if (data) {
      onChange(data);
    }

    setData(null);
    setIsDisplayed(false);
  };

  if (Component && isDisplayed) {
    return (
      <Component
        allowedTypes={['images', 'videos']}
        isOpen={isOpen}
        multiple={true}
        noNavigation={false}
        onClosed={handleClosed}
        onInputMediaChange={handleInputChange}
        onToggle={onToggle}
      />
    );
  }

  return null;
};

MediaLibrary.defaultProps = {
  isOpen: false,
  onChange: () => { },
  onToggle: () => { },
};

MediaLibrary.propTypes = {
  isOpen: PropTypes.bool,
  onChange: PropTypes.func,
  onToggle: PropTypes.func,
};

export default MediaLibrary;

```

I won't go into much detail here, but you should look into the `handleInputChange` and `handleClosed` functions which are the necessary ones here. Basically the `handleInputChange` adds selected images to state, and once the dialog closes, that data gets handled back with the `onChange` call.

So, anyway, import that in your `index.js` page as so:

    import MediaLibrary from './MediaLibrary';

Then render it, and the button that opens it in the `index.js` file.

```js
<Button type="button" onClick={toggleMediaLib} style={{ marginBottom: '0.5rem' }}>Media Library</Button>
<MediaLibrary isOpen={isMediaLibOpen} onToggle={toggleMediaLib} onChange={addImageCallback}
```
> I haven't figured out how I could override the CKEditor image button to actually execute something other than open up the explorer, so instead I added an extra button right on top of the editor which opens up the library. Much like what Wordpress does.

So now we have to write the missing code before the `return`.

```js
// Media library
const [isMediaLibOpen, toggleMediaLibOpen] = useState(false);
// Editor instance
const [editorRef, setEditorRef] = useState(null);

/**
 * Toggle media library on
 */
const toggleMediaLib = () => {
  toggleMediaLibOpen(!isMediaLibOpen);
};

/**
 * When ever the onChange event in MediaLib fires,
 * all selected image data is passed here and
 * we have to append it to the editor
 *
 * @param data
 */
const addImageCallback = (data) => {
  for (const image of data) {
    // Grab cursor position
    let position = editorRef.model.document.selection.getFirstPosition();

    // Create the image element
    const htmlString = `<img src="${image.url}" alt="${image.alt}">`;

    // Create a model for the image (ckeditor stuff)
    const htmlDP = editorRef.data.processor;
    const viewFragment = htmlDP.toView(htmlString);
    const modelFragment = editorRef.data.toModel(viewFragment);

    // Add to content
    editorRef.model.insertContent(modelFragment, position);
  }
};

```

And that should do it! In essence, the `addImageCallback` is what gets called when the media library closes and we have an array of objects to handle there. CKEditor requires their own data model to be used so you can insert HTML into the editor's content field. The editor instance can be set into the state via the `onReady` call.

Here's the full `index.js` that I ended up with.

```js
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { Button } from '@buffetjs/styles';

// Media library
import MediaLibrary from './MediaLibrary';

// CKEditor
import './ck-editor.css';

const ClassicEditor = require('./module/build/ckeditor');
import { CKEditor } from '@ckeditor/ckeditor5-react';

const Editor = ({ onChange, name, value }) => {
  // Media library
  const [isMediaLibOpen, toggleMediaLibOpen] = useState(false);
  // Editor instance
  const [editorRef, setEditorRef] = useState(null);

  /**
   * Toggle media library on
   */
  const toggleMediaLib = () => {
    toggleMediaLibOpen(!isMediaLibOpen);
  };

  /**
   * When ever the onChange event in MediaLib fires,
   * all selected image data is passed here and
   * we have to append it to the editor
   *
   * @param data
   */
  const addImageCallback = (data) => {
    for (const image of data) {
      // Grab cursor position
      let position = editorRef.model.document.selection.getFirstPosition();

      // Create the image element
      const htmlString = `<img src="${image.url}" alt="">`;

      // Create a model for the image (ckeditor stuff)
      const htmlDP = editorRef.data.processor;
      const viewFragment = htmlDP.toView(htmlString);
      const modelFragment = editorRef.data.toModel(viewFragment);

      // Add to content
      editorRef.model.insertContent(modelFragment, position);
    }
  };

  // Editor configuration
  const configuration = {
    toolbar: {
      items: [
        'heading',
        '|',
        'bold',
        'italic',
        'underline',
        'strikethrough',
        'code',
        '|',
        'link',
        'bulletedList',
        'numberedList',
        '|',
        'alignment',
        'indent',
        'outdent',
        'horizontalLine',
        '|',
        'blockQuote',
        'insertTable',
        'mediaEmbed',
        'undo',
        'redo',
        '|',
        'codeBlock'
      ]
    },
    language: 'en',
    image: {
      toolbar: [
        'imageTextAlternative',
        'imageStyle:full',
        'imageStyle:side',
        'linkImage'
      ]
    },
    table: {
      contentToolbar: [
        'tableColumn',
        'tableRow',
        'mergeTableCells',
        'tableCellProperties',
        'tableProperties'
      ]
    },
  };

  return (
    <>
      <Button type="button" onClick={toggleMediaLib} style={{ marginBottom: '0.5rem' }}>Media Library</Button>
      <CKEditor
        editor={ClassicEditor}
        data={value}
        config={configuration}
        onChange={(event, editor) => {
          const data = editor.getData();
          onChange({ target: { name, value: data } });
        }}
        onReady={editor => setEditorRef(editor)}
      />
      <MediaLibrary isOpen={isMediaLibOpen} onToggle={toggleMediaLib} onChange={addImageCallback}
      />
    </>
  );
};

Editor.propTypes = {
  onChange: PropTypes.func.isRequired,
  name: PropTypes.string.isRequired,
  value: PropTypes.string,
};

export default Editor;
```

**Comment by OssiPesonen** [comment]
Further testing has revealed that Strapi seems to save all content in markdown, so this should not affect your front-end. I was afraid this affected my front-end, changing the API responses from markdown to HTML.

**Comment by malgamves** [comment]
Hey @OssiPesonen could you look at our [FAQs ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46)for how to submit content once approved. 

A quick review, I'd love to see some pictures (screenshots) of the implemented editor as well as GIFs of adding entries and possibly some description of how that data is delivered via the API should that be different.

**Comment by malgamves** [comment]
hey @OssiPesonen any updates here??

**Comment by OssiPesonen** [comment]
Hi @malgamves! Sorry, I've been swamped with work. I'll try to get around and post some screenshots of the editor and how it works. I will also add how the data differs (image URL's might be different). It took such a long time for you to respond that I already forgot that this post existed.

**Comment by malgamves** [comment]
Sorry about the late response, glad to know your still interested. Could you follow the submission process in this [FAQ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46)? 

also just checking that this isn't published anywhere on the internet, is it?
