### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by mohmmadmoussa1988** [strapi/community-content#267]
I have a content type which has 2 rich texts :

<img width="1423" alt="Screen Shot 2020-12-16 at 4 28 54 PM" src="https://user-images.githubusercontent.com/37548159/102361366-d3d02580-3fbb-11eb-8877-788c189ac913.png">

When i go to the listing page of the content type -> Configure View -> View 

I can show title - created_at- updated_at only,
<img width="1424" alt="Screen Shot 2020-12-16 at 4 30 36 PM" src="https://user-images.githubusercontent.com/37548159/102361571-0bd76880-3fbc-11eb-9618-df551d3104ed.png">

i cant add one of the riich texts to the below list 

<img width="1421" alt="Screen Shot 2020-12-16 at 4 31 10 PM" src="https://user-images.githubusercontent.com/37548159/102361642-1f82cf00-3fbc-11eb-982e-76fde3857acc.png">

**Comment by JelmerV-WFC** [comment]
First of all, I don't think this is the place to ask this kind of things. You can't show rich text types in this view, I think if you want to display something in this view use a normal text field instead of rich text.

**Comment by mijorus** [comment]
I believe it's design like this because rich text is meant for blog articles and long content, which would be impossible to show in the UI

**Comment by derrickmehaffy** [comment]
Issues should be directed towards https://github.com/strapi/strapi closing
