### ISSUE TITLE
Strapi authentication for Next using next-auth

### ISSUE THREAD

**Issue by hgulersen** [strapi/community-content#274]
Strapi authentication for Next using next-auth

Hi folks. I have been working to get next-auth to work with Strapi for a couple of days and I have succeeded in the end. The only specific article I found over the web is this one, which does not go in depth (https://nirmalyaghosh.com/articles/2020-10-06-authentication-in-next-js-with-strapi-and-next-auth). Would it be helpful if I wrote an in depth strapi blog article so it's available to other people? Wanted to get your opinion before I dive in. 

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hey @hgulersen we went a step ahead with that article and updated it [here](https://strapi.io/blog/user-authentication-in-next-js-with-strapi) - how different would yours be?

I'd be very interested in seeing a practical implementation of Auth in a Next App where content is 'gated' - a recipe book? chat forum? job board? What do you think?

**Comment by hgulersen** [comment]
Hey @malgamves!
I took another look at the linked article. I think it's very helpful but there's a big emphasis on OAuth rather than directly signing in as a strapi user. I think this is a common use case, especially when it comes to storing the strapi jwt token and using it to fetch gated data as you mentioned. In my project I embedded strapi's jwt in next-auth's own jwt and stored it on the server; then used next.js's API routes to consume the strapi jwt without exposing it to the browser. There isn't a lot of information out there on how to property store the tokens, so I think it'd be helpful for the community. 

We can maybe have some arbitrary listings of books and a signed in user can favorite/like the books and then view those in their profiles? We can gate the liked/favorited books per user and use the strapi jwt to fetch those. Let me know what you think!

**Comment by malgamves** [comment]
This is an interesting take! Do you think you can send me a demo app that shows this functionality? 

I really like the book idea to!

**Comment by osmarpb97** [comment]
@malgamves I could do the same yesterday in a simple app if you don't have an answer I can write the article :D

**Comment by hgulersen** [comment]
Hey @malgamves. I'm in the process of writing the app and the draft, hopefully I can send the first draft by the end of next week. Hope that works!

**Comment by malgamves** [comment]
Hey @hgulersen thanks for the update. Can't wait to have a look.

Also, @osmarpb97 I appreciate you coming and wanting to write. Do you think you could write that up for React? Maybe a Recipe App?

**Comment by osmarpb97** [comment]
@malgamves  The problem is this auth uses server side rendering :( and next become important.

**Comment by malgamves** [comment]
Ahh I see, what about the useState hook as they did [here](https://www.digitalocean.com/community/tutorials/how-to-add-login-authentication-to-react-applications)? @osmarpb97

**Comment by malgamves** [comment]
Hey @hgulersen any luck with this? When do you think you can have a draft out?

**Comment by osmarpb97** [comment]
@malgamves I have a beautiful codebase of this. If you want I can share that codebase and write some draft document today.

**Comment by hgulersen** [comment]
Hi @malgamves, if @osmarpb97 already has it ready then I don't want to be the botteneck here. I'm a bit tight on time these days, it doesn't matter to me where the doc comes from as long as the community benefits from it as soon as possible.

**Comment by malgamves** [comment]
hey @hgulersen thanks for the heads up. I'm happy to let @osmarpb97 take over it.. one thing though. Please follow the [FAQ ](https://www.notion.so/strapi/Strapi-Write-for-the-Community-FAQ-b1fa0282d68a4c3e933fdd5e05f61a46) when putting together your article.

**Comment by malgamves** [comment]
hey @osmarpb97 any progress here?

**Comment by osmarpb97** [comment]
Hello @malgamves i have the draft ready! How I share it with you?
