### ISSUE TITLE
[TOPIC] To-do app using Next.js and Strapi

### ISSUE THREAD

**Issue by philipszdavido** [strapi/community-content#279]
I will be creating an article that shows how o build a simple to-do app using next.js and strapi.

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hello, @philipszdavido could you tell me more about the features that this app will have?

**Comment by philipszdavido** [comment]
The features will be:

- Create a to-do lists
- Edit a to-do item (CRUD)

**Comment by malgamves** [comment]
Great! You can go ahead with it. Do add delete functionality too! @philipszdavido when do you think you'll have a draft ready?

**Comment by philipszdavido** [comment]
On Monday.

**Comment by philipszdavido** [comment]
Hello @malgamves I am done with the article. How can I submit it? 
Sorry for the delay.

**Comment by malgamves** [comment]
hey @philipszdavido our [FAQs](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46) will be able to help you out on how to submit articles. Looking forward to seeing this.
