### ISSUE TITLE
[TRANSLATE]goog

### ISSUE THREAD

**Issue by kyle8581** [strapi/community-content#280]
**The tutorial I want to translate**

**Community vote**
👍 Upvote if you need it too
❤️ I love it!
🚀 I can help you!

**Comment by malgamves** [comment]
Hello @kyle8581 could elaborate on what you'd like?

**Comment by kyle8581** [comment]
oops...I don't really know why this issue has opened...I've never opened issue on your repo. Sorry bro I think my account is hacked by someone
