### ISSUE TITLE
[TOPIC] How to use NextAuth.js with Strapi?

### ISSUE THREAD

**Issue by RiczCalixto** [strapi/community-content#283]
**My Request**
How to use NextAuth.js with Strapi? If can, is there any example ?

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by malgamves** [comment]
We just published this article on User Auth using [NextAuth](https://strapi.io/blog/user-authentication-in-next-js-with-strapi) @RiczCalixto
