### ISSUE TITLE
[ISSUE] Nuxtjs Ecommerce tutorial: mLab has discontinued their addon 'mongolab'

### ISSUE THREAD

**Issue by dertrockx** [strapi/community-content#284]
This isn't much of a technical side ( I think so ). I was following the nuxtjs ecommerce tutorial using apollo, and in part 7 I had troubles deploying my strapi backend to heroku.

The problem was not the code, but the add-on that was used in the tutorial, i.e. the _mongolab:sandbox_. When I first ran the command from the tutorial, this was the result
![image](https://user-images.githubusercontent.com/19862244/104068456-ebf43700-523f-11eb-88a0-27d9da974ad9.png)

So I looked up the add-on on heroku, and I was shocked to find out that the add-on was discontinued by its creators, [here's the link](https://devcenter.heroku.com/articles/mongolab).

I really hope you can update the tutorial soon, because it was really helpful to get started with strapi + stripe.

**Comment by Mcastres** [comment]
Thanks @dertrockx for mentioning this. We are working on updating our outdated tutorials. Can you create an 'Update a content' issue mentioning this, using the outdated resource label and closing this one?
Thanks!

**Comment by dertrockx** [comment]
Will do. Thank you!
