### ISSUE TITLE
Getting started with Chakra UI in Nextjs

### ISSUE THREAD

**Issue by Qodestackr** [strapi/community-content#287]
**My resource**

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by ReactifyStudio** [comment]
@kilinkis I will be using Chakra UI and Next.js to build an authentication with Firebase

**Comment by malgamves** [comment]
Hello, where would you be using Strapi in the architecture of your application?

**Comment by ReactifyStudio** [comment]
Hey I didn't know that this blogs are actually tied to the strapi products.
Maybe I need to change my article?
