### ISSUE TITLE
Import content plugin tutorial errors [ISSUE]

### ISSUE THREAD

**Issue by AnthonyPhan** [strapi/community-content#29]
**The concerning tutorial**
How to create an import content plugin [(4 part series)](https://strapi.io/blog/how-to-create-an-import-content-plugin-part-1-4)

**Issue**
I would first like to first say thank you to all contributors to this blog series. I feel this series was very helpful and help me to understand some of the core concepts within Strapi.

I have followed the tutorial though to the end, however i encounter the following error when trying to import a file. Does anyone know what my issue might be?

![image](https://user-images.githubusercontent.com/12785492/77975226-081b8d00-732c-11ea-8192-e9b495a71d8b.png)

**Additional Details**

- I can confirm that the importconfig model was generated using the command line as per the instructions 
- I do have the Importconfig.setting.json and Importconfig.js files generated. 
- I can confirm that i have set the roles and permission to my plugin to be publicly accessible. 
![image](https://user-images.githubusercontent.com/12785492/77975401-8b3ce300-732c-11ea-88db-9f8b34fdab95.png)

**System Details**
- Strapi version: 3.0.0-beta.19.3 (node v12.6.0)  
- Operating System: Windows 10
- Database: Postgres, SQL Lite (tested on both)

Lastly is there any way for me to simply install you plugin into my project? I tried simply replicating your files into my plugins folder but doing so seems to break my admin panel and makes it in accessible. 

--

**Comment by AnthonyPhan** [comment]
Hi I belive something must have changed in the Strapi plugin system since this tutorial was released. I downloaded the source code for the tutorial here and ran it and everything worked perfectly. Then i updated the version from 3.0.0-beta.18.3 to 3.0.0-beta.19.4 , rebuilt the project and now i receive the following error

![image](https://user-images.githubusercontent.com/12785492/78006301-6584fd80-736f-11ea-830e-a31e838fbd60.png)

I was able to manually resolve this error by adding the "create" action but then my admin panel will no long open and i receive a blank white screen when navigating to localhost:1337/admin 
![image](https://user-images.githubusercontent.com/12785492/78006356-7cc3eb00-736f-11ea-928e-39348e54e485.png)

**Comment by pouyamiralayi** [comment]
Hi @AnthonyPhan do you confirm using graphql plugin inside your project?

**Comment by pouyamiralayi** [comment]
We had this issue with graphql and we provided some default endpoints for CRUD actions to remedy the situation!

**Comment by AnthonyPhan** [comment]
Hi Pouyamiralyi, yes i can confirm I use graphQL in my project.
I did add the create actions for importconfig and ImportedItem however after doing this my admin panel would not open. Let me know if you have more success :)

**Comment by pouyamiralayi** [comment]
Hi @AnthonyPhan until i apply the patch to the tut and it's official repo, you can use this [repo](https://github.com/pouyamiralayi/strapi-import-content-plugin-tutorial/tree/migrate_to_19.4) which is compatible with Strapi 19.4 beside compatibility with graphql. 
**what are the changes?** 
1.basically we do not export the plugin configuration object anymore, instead we must export a function which registers the plugin inside the ``index.js`` file of the plugin's root directory!
2. the ``getmodels`` endpoint of CTB no longer exists and we use ``content-types`` endpoint for the sake of retrieving the details of content types.

> Lastly is there any way for me to simply install you plugin into my project? I tried simply replicating your files into my plugins folder

you are doing it correctly. after the replacement, just remove your build directory and issue ``yarn build`` to build the admin with the new changes.

Cheers!

**Comment by AnthonyPhan** [comment]
Hi Pouya,

I very much appreciate your help. 
I tried cloning your fork and running the code but received the following error. 
![image](https://user-images.githubusercontent.com/12785492/78095002-82214400-7408-11ea-846a-f011f4013976.png)


I will continue to investigate on my end to see the reason for the issue.

**Comment by pouyamiralayi** [comment]
Hi @AnthonyPhan ``403`` means you have not allowed access to plugin endpoints in the ``roles & permissions`` plugin. Please follow the instructions on the readme file of the plugin [setup section].
Cheers!

**Comment by AnthonyPhan** [comment]
O boy I feel dumb for not remembering to do that! 
Cloning and running your repo works perfectly now, thank you :)

**Comment by istian** [comment]
hello @pouyamiralayi ,

I did tried downloading your fork and just copied the import-content plugin in my `plugins` directory but after running `build` and `develop` my strapi won't start with the following:

```[2020-04-16T03:07:41.344Z] debug ⛔️ Server wasn't able to start properly.
[2020-04-16T03:07:41.349Z] error Error: [GraphQL] Cannot find action "plugins::import-content.importconfig.findOne". Check your graphql configurations.
    at getAction (C:\Users\CRVicente\Development\NodeJs\Strapi\myApi\node_modules\strapi-plugin-graphql\services\resolvers-builder.js:159:11)
    at buildQuery (C:\Users\CRVicente\Development\NodeJs\Strapi\myApi\node_modules\strapi-plugin-graphql\services\resolvers-builder.js:97:18)
    at buildCollectionType (C:\Users\CRVicente\Development\NodeJs\Strapi\myApi\node_modules\strapi-plugin-graphql\services\type-definitions.js:379:27)
    at models.map.model (C:\Users\CRVicente\Development\NodeJs\Strapi\myApi\node_modules\strapi-plugin-graphql\services\type-definitions.js:239:16)        
    at Array.map (<anonymous>)
    at buildModels (C:\Users\CRVicente\Development\NodeJs\Strapi\myApi\node_modules\strapi-plugin-graphql\services\type-definitions.js:228:17)
    at buildModelsShadowCRUD (C:\Users\CRVicente\Development\NodeJs\Strapi\myApi\node_modules\strapi-plugin-graphql\services\schema-generator.js:135:8)    
    at Object.generateSchema (C:\Users\CRVicente\Development\NodeJs\Strapi\myApi\node_modules\strapi-plugin-graphql\services\schema-generator.js:29:7)     
    at Object.initialize (C:\Users\CRVicente\Development\NodeJs\Strapi\myApi\node_modules\strapi-plugin-graphql\hooks\graphql\index.js:87:9)
    at Promise.resolve.then (C:\Users\CRVicente\Development\NodeJs\Strapi\myApi\node_modules\strapi\lib\hooks\index.js:37:28)

```

Also, is `graphQL` plugin required for the `import-content` plugin to work?

Strapi: 3.0.0-beta.19.5
Node: 10.15.0
npm: 6.4.1

**Comment by AnthonyPhan** [comment]
@istian Are you using the repo from this link:
https://github.com/pouyamiralayi/strapi-import-content-plugin-tutorial/tree/migrate_to_19.4

or this link:
https://github.com/strapi/community-content/tree/master/tutorials/code/import-content-plugin-tutorial

**Comment by istian** [comment]
hi @AnthonyPhan , I used the first one as I read that one has the patch for beta 19.4 so I'm assuming it will work to 19.5 as well.

I am not able to get the latter in my admin page doesn't work.

**Comment by pouyamiralayi** [comment]
Hi @istian can you confirm that you have the below files inside your plugin ``controllers`` directory?
```
ImportConfig.js
ImportContent.js
```

**Comment by pouyamiralayi** [comment]
> Also, is graphQL plugin required for the import-content plugin to work?

No! but if you are using the graphQL plugin, you must provide the default crud endpoints for all your content-types (for our scenario ImportConfig & ImportedItem)
Cheers!

**Comment by istian** [comment]
hey @pouyamiralayi , I don't have the 3 files in my `controllers` directory` and the `admin/src/index.js` content is also different on my copy. I fixed those and `voila`, it works! Thanks so much for you both for helping me!

Although, I have another annoying issue :) Everytime I click on the import content nav in the left panel, there's always a 404 mini popup error appear and the url is `content-type-builder/models`

![image](https://user-images.githubusercontent.com/200690/79511803-986b0900-8072-11ea-9ad9-5ec69dc9cf8a.png)

**Comment by pouyamiralayi** [comment]
Hi @istian i am glad it works! based on your clarification on the structure of the project, i am sure that your clone is not from [migrate_to_19.4 branch](https://github.com/pouyamiralayi/strapi-import-content-plugin-tutorial/tree/migrate_to_19.4). the ``404`` error is typically because of the missing controllers, please fork the mentioned branch, follow the setup section in the README and let us know if this happens again.
Cheers!

**Comment by istian** [comment]
hi @pouyamiralayi , I indeed cloned your fork but did not pull to get the other files :) It is working now and I already tried importing records and it works! Again, thank you! This will speed up my personal project.
