### ISSUE TITLE
[SUBMIT] Getting Started WIth Laravel Events

### ISSUE THREAD

**Issue by jumamiller** [strapi/community-content#291]
Laravel's events provide a simple observer pattern implementation, allowing you to subscribe and listen for various events that occur within your application.

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hey @jumamiller would you like to submit an article around this topic? if yes, could you please provide an outline of the article?

**Comment by daacode** [comment]
@ShadaW11 I will like to work on this.

**Comment by ShadaW11** [comment]
We published an article around Laravel and Strapi a few days ago; https://strapi.io/blog/strapi-and-laravel

I will close this topic. Feel free to suggest new ones.
