### ISSUE TITLE
[TOPIC] How to create corporate websites using strapi

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#3]
**The Request**
Strapi is looking for a writer for our new tutorial program. A lot of our users are using strapi in order to build corporate websites, this is why we want to release an **"How to create corporate websites using strapi"** tutorial. 

One of our great inspiration is Docker and we would like to showcase a Docker-like corporate website.

This tutorial will consist of recreating the Docker corporate website using strapi and one of the following frontend techno (Gatsby, Next.js, Nuxt.js, React, VueJs, Angular)

Why write tutorials?
- Make a tutorial, improve your writing skills and teach people!
- Contribute to an open source project
- We’ll send you an invite to the tutorial makers channel to discuss further about this
- Receive some goodies 

If you think that you can make this tutorial, let me know below or contact me at maxime.castres@strapi.io, I'll give you more details about it.

**Preferred Format**
- [x] Article
- [ ] Video

**Community vote**
👍 Upvote if you need it too
🚀 If you can make the tutorial to help the community!

**Comment by Atinux** [comment]
Upvote and wish to see it with Nuxt.js 😍

**Comment by pouyamiralayi** [comment]
i have already followed nuxt tutorial for strapi and i have polished it to be production ready.
things i have added to the stack and would be happy to share with you guys:
1) integrating apollo link error for debuggin the graphql requests and proper error handling.
2) using apollo mutations with respect to graphql api amountLimit.
3) properly setup apollo cache.
4) properly setup apollo for authentication token.
5) pagination
the result of this work is in my github repo titled as "nuxt-excel". this work is using my native language: "persian" but i would be happy to help on sharing the experience and also updating my project to suit your needs.
cheers!

**Comment by Palgie** [comment]
Glad to be taking this on! Confirming that I'll be doing this tutorial with Nuxt.js @Atinux. 🎉
