### ISSUE TITLE
Import content plugin tutorial broken links [ISSUE]

### ISSUE THREAD

**Issue by AnthonyPhan** [strapi/community-content#30]
**The concerning tutorial**
How to create an import content plugin ([4 part series](https://strapi.io/blog/how-to-create-an-import-content-plugin-part-1-4))

**Issue**
Links to the code for the tutorial are broken. 

Tutorials links to this url: https://github.com/strapi/community-content/tree/master/tutorials/import-content-plugin-tutorial

![image](https://user-images.githubusercontent.com/12785492/77990343-a96a0980-7353-11ea-861a-9f3ba4a0485f.png)

**Comment by Mcastres** [comment]
Thanks Anthony! I fixed it
