### ISSUE TITLE
[REQUEST] Auth0 Provider and Strapi Tutorial

### ISSUE THREAD

**Issue by javakian** [strapi/community-content#301]
Interested in logging into 
Next.js using Auth0 for google, Twitter, and Facebook.

**Comment by malgamves** [comment]
Hey @Heziode you added the Auth0 provider func. in this [issue](https://github.com/strapi/strapi/pull/8362) - would you mind writing up a tutorial on it and how you use it?

**Comment by Heziode** [comment]
Hi,

I added Auth0 into the documentation: strapi/documentation#81

> would you mind writing up a tutorial on it and how you use it?

Did you mean, create a small application in [./tutorials/code](https://github.com/strapi/community-content/tree/master/tutorials/code) to show how to use it ?

**Comment by malgamves** [comment]
Hey @Heziode Yes, that and writing about the tutorial building process and publishing it to the Strapi Blog.

**Comment by Heziode** [comment]
The documentation i wrote give example of configuration based on an older version of [login-react](https://github.com/strapi/strapi-examples/tree/master/login-react).

You can take a look of my archived version here (frontend part): https://github.com/Heziode/strapi-auth0-example

---

I do not use Auth0 anymore, and I currently do not have the time to write about it for now.

**Comment by malgamves** [comment]
Thanks for sharing this! No worries, I'll leave this open so someone can take it up.

**Comment by alloyking1** [comment]
Hi @malgamves @Heziode . Interesting topic. I would like to write on this one or would I say finish up what @javakian started.

**Comment by malgamves** [comment]
I like this idea. Let's make the Auth0 Support part of the application. I would like you to do something like a note sharing app and have that working with the Auth0 provider.

**Comment by alloyking1** [comment]
Sounds good. On it.

**Comment by purnimagupta** [comment]
@alloyking1, still working on it?
