### ISSUE TITLE
[SUBMIT] Jamstack with Scully.io

### ISSUE THREAD

**Issue by asotog** [strapi/community-content#302]
**My resource**
Hi there, [Scully.io](https://scully.io/) is quite a new library for JAMStack, right now seems there is nothing similar for angular, you can generate static pages, but keep dynamic once rendered in the browser, so the pages can get hydrated any time. And deploy the app to [Netlify](http://netlify.com/)

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by asotog** [comment]
@malgamves how is the process, can I write for this?

**Comment by malgamves** [comment]
Hey @asotog - the process is highlighted [here](https://www.notion.so/strapi/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46). Let me know if you have any questions.

**Comment by asotog** [comment]
All right thanks @malgamves will work take care of it

**Comment by malgamves** [comment]
Hey @asotog How is this going?

**Comment by asotog** [comment]
Hi @malgamves, actually I'm wrapping up some stuff, almost done, I can send you the dropbox paper on Monday

**Comment by asotog** [comment]
Hi @malgamves I just shared with daniel.phiri@strapi.io the draft of the post, should I share with you too ?

**Comment by asotog** [comment]
> Hi @malgamves I just shared with [daniel.phiri@strapi.io](mailto:daniel.phiri@strapi.io) the draft of the post, should I share with you too ?

Ah nevermind just noticed you are Daniel 👍

**Comment by malgamves** [comment]
Just seen it, will review!!

**Comment by asotog** [comment]
hi Daniel, appreciate your feedback that was useful, thanks man, made the modifications already, please check if you get chance

**Comment by asotog** [comment]
@malgamves applied the latest updates, please let me know if there is any other modification, thanx in advance

**Comment by malgamves** [comment]
Hey @asotog - thanks. I will have a look :D
