### ISSUE TITLE
[TOPIC] Implementing Previews with Next Applications using a Strapi backend

### ISSUE THREAD

**Issue by malgamves** [strapi/community-content#305]
I'd like to see a post that shows how to use the Next preview feature for applications powered by Strapi

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by purnimagupta** [comment]
@malgamves, Hi, I haven't worked with Nextjs yet. But I would be interested in working on it.

It would give me some clarity if you could explain a little bit what's meant by "previews with Next App".

 Thanks!

**Comment by Quadrisheriff** [comment]
Hi @ShadaW11 , sorry for the delay. This is the dropbox link.

https://www.dropbox.com/scl/fi/0cdl3p2olrg9928rlpsd9/Previews-with-Strapi-and-Next.js..paper?dl=0&rlkey=6aws1yp5ue3ws3nupkohdayg5

**Comment by ShadaW11** [comment]
Hey @Quadrisheriff Could you please register your author details in the form in this page https://strapi.io/write-for-the-community

**Comment by Quadrisheriff** [comment]
Done*  @ShadaW11

**Comment by ShadaW11** [comment]
Hey @Quadrisheriff your article has been published, could you please check the  https://strapi.io/write-for-the-community to learn how to issue and submit an invoice please.
