### ISSUE TITLE
[TOPIC] Implementing Previews with Nuxt Applications using a Strapi backend

### ISSUE THREAD

**Issue by malgamves** [strapi/community-content#306]
**My Request**

I'd like to see an article showing how to use the Nuxt preview feature for a web app powered by Strapi

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by Kaperskyguru** [comment]
Hello @malgamves I will love to work on this topic.

**Comment by malgamves** [comment]
Hey @Kaperskyguru - could you share an outline of what the article would look like??

**Comment by Kaperskyguru** [comment]
Hello @malgamves,

Below is my outline for this article.

1. Introduction
2. Enabling preview mode in Nuxt (> v2.13)
3. Previewing brand new pages
4. Generating the target URL in Strapi
5. Opening the preview in a new tab
6. Showing the preview inside an iFrame
7. Handling draft preview with Strapi
8. Be careful with content validation when previewing drafts with Strapi
9. Preview banner with $nuxt.refresh
10. Conclusion.

The article will be focused on introducing beginners or readers to integrating Nuxt Previews using Strapi as the backend.

**Comment by malgamves** [comment]
Hey @Kaperskyguru love this outline! Can't wait to see the draft. When do you think you'll have that??

**Comment by Kaperskyguru** [comment]
@malgamves @ShadaW11 @vcoisne 

Done working on this article.

Here is the link
https://www.dropbox.com/scl/fi/d7ci1shqk9mogrg1cqhuo/Implementing-Previews-with-Nuxt-Applications-using-a-Strapi-backend.paper?dl=0&rlkey=1mxwolrzrbfnz7meafpgc3icn

**Comment by ShadaW11** [comment]
Hey @Kaperskyguru awesome job. Just posted your article.

**Comment by Kaperskyguru** [comment]
Thanks for publishing.
