### ISSUE TITLE
[TOPIC] A Beginners Guide to Authentication and Authorization in Strapi

### ISSUE THREAD

**Issue by malgamves** [strapi/community-content#307]
**My Request**

I'd like to see a guide that details how authentication and authorization work in Strapi. 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by Kaperskyguru** [comment]
I will love to work on this topic

**Comment by malgamves** [comment]
Sure @Kaperskyguru could you share a brief outline of how you'll approach the article?

**Comment by Kaperskyguru** [comment]
Hello @malgamves,

Below is my outline for this article.

1. Introduction

2. What is Authentication?
  a. Popular Authentication Methods

3. What is Authorization?
  a. Popular Authorization methods

4. Explore different authentication methods support by Strapi.

5. Authenticate a Strapi User using JWT
   a. Create Token Content Types.
   b. Validate the tokens.
   c. Sending Request as an Authenticated user.

6. Detailed overview of authorization methods in Strapi.
   a. Creating different roles and permissions.
   b. Assigning different roles and permissions to users.
   c. Managing Roles and Permissions.
   d. Restricting authenticated Users based on roles and permissions.

7. Testing our project with Postman.

8. Conclusion.

The article will be focused on introducing beginners or readers to the Authentication and Authorization processes with Strapi.

**Comment by malgamves** [comment]
This looks really good @Kaperskyguru You can go ahead and get started. When do you think you can send over a draft?

**Comment by Kaperskyguru** [comment]
Thanks @malgamves,

I will send in my first draft on or before 10th March.

Thanks,

**Comment by malgamves** [comment]
Awesome!!

**Comment by malgamves** [comment]
Hey @Kaperskyguru that's alright. Please do take note of [submission guidelines](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46) before submitting a draft for review :)
