### ISSUE TITLE
[REQUEST] Create Registration and Login(authentication) with Vue.js and Strapi 

### ISSUE THREAD

**Issue by Shjani49** [strapi/community-content#313]

**Comment by brunogonzales** [comment]
I can do this if you like

**Comment by Shjani49** [comment]
It would be very helpful as I’m beginner. 
Thank you so much. 

Sincerely,
Shivani Jani.

**Comment by oviecodes** [comment]
hey @malgamves  , I could take this up. I could show authentication by building a recipe app. Vue.js frontend and Strapi backend.

**Comment by malgamves** [comment]
Hey @oviecodes do you have an outline for how this article will look??  Happy to have you take this on

**Comment by oviecodes** [comment]
Hey @malgamves  , I'll send a draft of the outline to your mail.

**Comment by malgamves** [comment]
Makes it easier to manage if you add it here. Please send it here @oviecodes

**Comment by oviecodes** [comment]
Ok @malgamves I'll send it here

**Comment by oviecodes** [comment]
Hey @malgamves how about I finish building the application first before drafting the outline?

**Comment by oviecodes** [comment]
Hey @malgamves I'll have the recipe application up soon.
The outline will cover the following:
User registration
User login
User roles and permissions
Forgot password
Reset password
Setting up email with nodemailer
relationship between Content types

**Comment by oviecodes** [comment]
hey @malgamves here's the link to the recipe application https://hardcore-hopper-1e0692.netlify.app/

**Comment by ShadaW11** [comment]
Hey @malgamves any feedback from your side?

**Comment by oviecodes** [comment]
hey @ShadaW11 here are the links to the articles

part 2 - https://www.dropbox.com/scl/fi/fm4xzric3mzlzu4k7higa/Registration-and-Login(authentication)-with-Vue.js-and-Strapi-(Part-2).paper?dl=0&rlkey=uthtgg6x999hwerwzm4ozvp9w

part 1 - https://www.dropbox.com/scl/fi/fcj96a00opmntkfkcrnnj/Registration-and-Login(authentication)-with-Vue.js-and-Strapi-(Part-1).paper?dl=0&rlkey=mqb9q4qglknhv0q20j8nb1lv6

**Comment by ShadaW11** [comment]
Hey @oviecodes awesome thanks. We will review the content and get back to you.

**Comment by ShadaW11** [comment]
Thank you @oviecodes updated link to article: https://www.dropbox.com/scl/fi/fcj96a00opmntkfkcrnnj/Registration-and-Login(authentication)-with-Vue.js-and-Strapi.paper?dl=0&rlkey=mqb9q4qglknhv0q20j8nb1lv6

**Comment by ShadaW11** [comment]
Hey @oviecodes your article is still in review, I will get back to you as soon as possible.

**Comment by oviecodes** [comment]
Thanks for the information @ShadaW11

**Comment by oviecodes** [comment]
Good day @ShadaW11 , are there any new updates on this.

**Comment by ShadaW11** [comment]
Hey @oviecodes you article is now published, congratulations. Please register to our forum by clicking on discussion at the bottom of your post so you receive automatically the notifications when someone adds comments. Also please follow the guidelines to issue and submit an invoice.
https://strapi.io/blog/registration-and-login-authentication-with-vue-js-and-strapi

**Comment by oviecodes** [comment]
Ok @ShadaW11 , I'll do that. Thanks
