### ISSUE TITLE
Error in query for a single article

### ISSUE THREAD

**Issue by quebone** [strapi/community-content#318]
Hello

The tutorial [Build a blog with React, Strapi and Apollo](https://strapi.io/blog/build-a-blog-with-react-strapi-and-apollo) has an error in the graphql query that fetches a single article (`./src/queries/article/article.js`).

Instead of fetching a single article, it fetches all of the articles (the query is exactly the same as `./src/queries/article/articles.js`)

Regards,
Carles

**Comment by Mcastres** [comment]
Thanks @quebone, I just fixed it :)
