### ISSUE TITLE
[SUBMIT]How To Setup Strapi using Docker

### ISSUE THREAD

**Issue by malithmcr** [strapi/community-content#319]
**My resource**
A tutorial about How to setup Strapi using Docker and Mongo DB Atlas.

Video Link: https://www.youtube.com/watch?v=oEtj0Vpmgro&t=255s

**My format**

- [ ] Article
- [x] Video

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hey @malithmcr awesome content, would you please [submit your tutorial](https://github.com/strapi/community-content/tree/master/tutorials) so we can feature it on our [website](https://strapi.io/tutorials)? we would also love if you would register to join our ["write for community" program](https://strapi.io/write-for-the-community) to discuss future tutorials!
