### ISSUE TITLE
[TOPIC] Using and Creating Services in Strapi

### ISSUE THREAD

**Issue by bigpreshy** [strapi/community-content#320]
**My Request**

I'd like to write an article on this @malgamves 
**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by malgamves** [comment]
Hey @bigpreshy could you share an outline with me for what you'll cover here.

**Comment by bigpreshy** [comment]
Outline

1. Introduction to Services

2. Services and Controllers
a) How Services in Strapi slightly relates to Controllers
b) Overriding the default strapi Services(understanding the shadow function in node_module)

3 Creating Services
a) CLI
b) Mannually adding

4 Custom Services and Usages
a) Filtering content
b) Triggering notification
c) Email 

5. Conclusion

**Comment by malgamves** [comment]
@bigpreshy this looks good. in section 4. Will you give actual examples of implementing these services? 

Also looks good. Can't wait to see a draft. Keep [submission guidelines](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46) in mind before requesting a review :D

**Comment by bigpreshy** [comment]
Yes.
I will give examples. 
Note: I will be using Twillo's Free trial for the SMS

**Comment by malgamves** [comment]
Awesome, sounds great! When might you have a draft ready?

**Comment by bigpreshy** [comment]
Already working on it. By  Wednesday, my draft should be ready.

**Comment by malgamves** [comment]
Cool! Did you send this already??

**Comment by vickywane** [comment]
@bigpreshy @malgamves any update on this?

**Comment by malgamves** [comment]
hey @bigpreshy I saw the submission, thanks for that. We're bolstering our review capacity so this should be out soon. @vickywane it was done already and will be published.
