### ISSUE TITLE
[TOPIC] [SPANISH] Nuxtjs + Strapi + TailwindCSS hosted on Netlify Food Recipe App

### ISSUE THREAD

**Issue by brunogonzales** [strapi/community-content#326]
**My Request**

Hi, I would like to make a tutorial for LATAM devs. I will include English subs for those who want to follow along. Would any be interested in watching it?

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by malgamves** [comment]
Hey @brunogonzales would this be a blog post or video?? You mentioned subs (subtitles?)

**Comment by brunogonzales** [comment]
This would be a video in Spanish with English subtitles

**Comment by ShadaW11** [comment]
Hey @brunogonzales if you created the tutorial, please submit it [here](https://github.com/strapi/community-content/tree/master/tutorials) so we can feature it on our [website](https://strapi.io/tutorials).
