### ISSUE TITLE
How to connect the Yandex Object Storage bucket with strapi for storing data

### ISSUE THREAD

**Issue by Ulibka68** [strapi/community-content#327]
**My resource**

**My format**

- [ x] Article
- [ ] Video

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Hello, I'm write russian tutorial about saving strapi data to russian service like AWS S3:

Tutorial name in English:
How to connect the Yandex Object Storage bucket with strapi for storing data

Tutorial name in Russian language:
Strapi сохранение файлов на Яндекс Object Storage

Link to tutorial
https://habr.com/ru/post/546938/

**Comment by ShadaW11** [comment]
Hello @Ulibka68 thank you for creating it, can you please [submit your tutorial](https://github.com/strapi/community-content/tree/master/tutorials) here so we can feature it on our [website](https://strapi.io/tutorials). We also love if you would join our ["write for community" program](https://strapi.io/write-for-the-community)
