### ISSUE TITLE
[TOPIC] Pagination in Strapi using GraphQL

### ISSUE THREAD

**Issue by philipszdavido** [strapi/community-content#330]
This article will show how to add pagination to your GraphQL datasets in Strapi. I will build a real-life app to also demonstrate the process.

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by philipszdavido** [comment]
@malgamves I am picking this, can I start writing?

**Comment by malgamves** [comment]
Could you share an outline of what this looks like?? @philipszdavido

**Comment by philipszdavido** [comment]
**Outline**

* Introduction to Strapi
* What is Pagination?
* Pagination and GraphQL
* Types of pagination
* Scaffold Strapi project - News feed app
* Demo - Offset-based pagination
* Demo - Cursor-based pagination
* Conclusion

**Comment by philipszdavido** [comment]
@malgamves can I start writing this?

**Comment by malgamves** [comment]
hey @philipszdavido yes you can. Let me know when you have a draft 👍

**Comment by philipszdavido** [comment]
@malgamves I have a draft https://www.dropbox.com/scl/fi/tkqlldqp0vvmjknzs7jj0/Pagination-in-Strapi-using-GraphQL.paper?dl=0&rlkey=ruh6ihuu2m2no6ghtnbc21vsi

**Comment by malgamves** [comment]
Thanks @philipszdavido - adding this to the review queue.
