### ISSUE TITLE
[ISSUE] broken link in cloudinary blog

### ISSUE THREAD

**Issue by dpinol** [strapi/community-content#331]
**The concerning content**
https://strapi.io/blog/adding-cloudinary-support-to-your-strapi-application
**Issue**
In the conlusions, the link in the word "here" is broken

> You can check more about other upload providers on the Strapi documentation **here** or on npmjs

thanks

**Comment by Mcastres** [comment]
Good catch @dpinol, I updated the link, it will be fixed in the next build :)
