### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Build a blog with React, Strapi and Apollo

### ISSUE THREAD

**Issue by DimiKalligas** [strapi/community-content#333]
Hello,

I tried following your article, but it is not working. Even downloaded the code, corrected some wrong folders in imports, but still produced error 'Could not find "client" in the context or passed in as an option.' (Although App is wrapped inside ApolloProvider)

So, it might need some minor updating.

Thanks,
Dimitris

**Comment by vcoisne** [comment]
Thanks @DimiKalligas . We'll take a look at it shortly.

**Comment by ShadaW11** [comment]
@Mcastres Did you get a chance to review and update this article?

**Comment by ShadaW11** [comment]
Hey @Mcastres I wanted to check if you managed to check the article?

**Comment by Mcastres** [comment]
Not yet Shada. I will take the time this week to give it an update. @DimiKalligas I can only recommend to follow this [tutorial](https://strapi.io/blog/build-a-blog-with-next-react-js-strapi) which is using Next.js instead. It is better for SEO ;)

**Comment by ShadaW11** [comment]
@Mcastres awesome thank you

**Comment by DimiKalligas** [comment]
Thanks, Mcastres!
