### ISSUE TITLE
[TOPIC] Localization with Strapi

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#337]
**My Request**
Following the release of i18n, it would be awesome to have a piece of content about localization using Strapi

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by bigpreshy** [comment]
I'd like to work on this.

**Comment by ShadaW11** [comment]
Hey @bigpreshy what do you have in mind for this topic?

**Comment by Code-Kat** [comment]
I'm interested in working on this if it's still available.

**Comment by ShadaW11** [comment]
Hello @Code-Kat, thank you for your interest, we just published this article on our blog. But there are plenty of other articles available. looking forward to working with you.
