### ISSUE TITLE
[TOPIC] Multilingual Content Management System

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#338]
**My Request**
Following the release of i18n it would be great to have an article about the advantages of having a multilingual cms.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by KevinKipkorir** [comment]
Hello. Can I participate in writing this?

**Comment by vcoisne** [comment]
@KevinKipkorir yes that would be great. Do you have an outline in mind ?

**Comment by KevinKipkorir** [comment]
Yes. I'd like to write a detailed article about this topic.I will cover;The value,need and imprrtance of Multilingual Content Management System.I will also cover Developing Multilingual sites with Headless CMS with  Strapi.How do i proceed?

**Comment by vcoisne** [comment]
@KevinKipkorir thank you for this outline. Overall LGTM. Can we include a section advantages of having a multilingual cms + advantages of Strapi i18n ?

When do you think you'll be able to work on this :) ?

**Comment by KevinKipkorir** [comment]
Yes, I will do that. I will incorporate the advantages of having a Multilingual CMS and Strapi in detailed in the introduction section. _ I will send my first draft of the article on or before 7, May. Thank you ;)

**Comment by KevinKipkorir** [comment]
@vcoisne Hello. Following our discussion earlier, I came up with the following draft regarding the topic. 
https://docs.google.com/document/d/1OG807PbntzF54GdQt-Ppb0WrseNYY-rtk-kb0HhHQCc/edit?usp=sharing 
Thanks.

**Comment by malgamves** [comment]
Hey @KevinKipkorir , please follow the review and submission process in the [FAQ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46)

**Comment by KevinKipkorir** [comment]
Hello @malgamves .I made changes to the document after reviewing  the submission process.
https://www.dropbox.com/scl/fi/vx24mr181lalqfrakvosz/Multilingual-Content-Management-System..paper?dl=0&rlkey=jodgn905yjo8usp2jsabgznpx

**Comment by malgamves** [comment]
Thanks @KevinKipkorir we're adding this to our review backlog and will get to you as soon as possible with comments on the document 👯

**Comment by KevinKipkorir** [comment]
Thanks. Do you have any DevOps related topics currently available? I would
love to take on that category  as well.

**Comment by malgamves** [comment]
Please have a look at the issues on the repo, there might just be some.

**Comment by KevinKipkorir** [comment]
Alright. Thanks

**Comment by ShadaW11** [comment]
Hey @KevinKipkorir, awesome article. just sent you an email.

**Comment by KevinKipkorir** [comment]
Yes, I received it.Thank you for the opportunity.Let me i will be sending
my Twitter handle link and Photo.
