### ISSUE TITLE
[TOPIC] Localize your content and succeed globally

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#339]
**My Request**
Following the release of i18n,it would be great to have a piece of content about how you can succeed globally by localizing your content.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by xTrilton** [comment]
Hello @Mcastres, What a magnificent topic you just crafted. I was kindly asking if you can assign me this topic.

**Comment by Mcastres** [comment]
Is the topic free to take @malgamves?

**Comment by xTrilton** [comment]
-Strapi localization use case.
-Taking SEO into account when translating content.
-Externalize  locale-specific data
-Locale Frameworks
-Benefits of Internationalizing Software

**Comment by xTrilton** [comment]
Below are links to articles I have published before.

https://boemo1mmopelwa.medium.com/simplifying-communication-with-google-translate-and-speech-to-text-8e52588cc843

https://boemo1mmopelwa.medium.com/implementing-etherium-blockchain-in-android-with-web3j-485ea0747088

**Comment by vcoisne** [comment]
@xTrilton sorry for the delay. Looks good. I have assigned this topic to you. Please refer to our [FAQ](https://www.notion.so/strapi/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46) for submission when ready for review.

**Comment by ShadaW11** [comment]
Hey @xTrilton still interested in this topic?

**Comment by xTrilton** [comment]
Yes, I will be submitting it Mid July.

**Comment by ShadaW11** [comment]
Awesome, thank you @xTrilton

**Comment by ShadaW11** [comment]
Hey @xTrilton how are you? Been a while, I hope you had a chance to finish the article?

**Comment by xTrilton** [comment]
Hello Shada,

I will be submitting the article in the middle of July. Which is next week,
as I had stated previously. Thanks for keeping in touch. Looking forward to
working with you next week :).

Have a nice day!

Best Regards,
Boemo Wame Mmopelwa
Technical Writer

**Comment by ShadaW11** [comment]
Heyy @xTrilton Thank you for the update. Happy to know that, and looking forward to receiving your article. Have an awesome day.

**Comment by xTrilton** [comment]
Hello @ShadaW11 , @Mcastres 

I just submitted the article via email to @malgamves and @ShadaW11.

Looking forward to hearing your feedback.

**Comment by ShadaW11** [comment]
Hey @xTrilton thank you, well received, we will get back to you as soon as possible with feedback

**Comment by xTrilton** [comment]
Hello @ShadaW11  do you want me to make any changes to the document?

**Comment by ShadaW11** [comment]
Hello @xTrilton Your article has already been reviewed and scheduled to be published tomorrow. Once its published, I will send you the link of the article here on GitHub, and you can go ahead and send us an invoice using the guidelines mentioned in the FAQ section in this [page](https://strapi.io/write-for-the-community). Please note that to publish your article, you will have to first submit your author details by filling the form (if you already filled it before, no need to refill again) in the bottom of this [page](https://strapi.io/write-for-the-community)

**Comment by xTrilton** [comment]
Hello, @ShadaW11 do you accept PayPal for payment transactions?

**Comment by ShadaW11** [comment]
@xTrilton no we will send the payment to your bank account.
