### ISSUE TITLE
[TOPIC] How to boost productivity with Strapi?

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#34]
**My Request**
Internal uses of Strapi

Strapi increases productivity
Content creators focus on content
Devs focus on dev work

**Preferred Format**

- [x] Article
- [ ] Video

**Community vote**
🚀 If you can make the article!

**Comment by Quadrisheriff** [comment]
Hi, please assign this topic to me.

**Comment by Mcastres** [comment]
Sure! Are you using Strapi in your team? Tell me more about it :)

**Comment by Quadrisheriff** [comment]
I am not using Strapi in my team. I just want to write about how a headless Strapi separates your front-end concerns from your cms, thus improving your developer experience and team productivity.

**Comment by Mcastres** [comment]
Hey @Quadrisheriff, just checking if there is any new about this one :)

**Comment by ShadaW11** [comment]
Hey @Quadrisheriff still interested in this subject?

**Comment by Code-Kat** [comment]
I’d be interested in writing about this if it’s still available.

**Comment by ShadaW11** [comment]
Hello @popoolatopzy I would suggest you include what maxime mentioned in his request: 
Strapi increases productivity
Content creators focus on content
Devs focus on dev work

apologies for the delay in getting back to you.

**Comment by popoolatopzy** [comment]
Alright @ShadaW11 , here is the new outline

- Introduction
- The benefit of effective productivity
- how to boost productivity 
   Strapi increases productivity
   Content creators focus on content
   Devs focus on dev work
- Conclusion

**Comment by ShadaW11** [comment]
@popoolatopzy Sounds good, I suggest that you expand more on point 2, 4 and 5 when writing your article. You can go ahead and start working on the article.

**Comment by popoolatopzy** [comment]
Hello @ShadaW11 , here is the link to the draft
https://www.dropbox.com/scl/fi/rfjfb9i0slg26lq98m2p0/How-to-boost-productivity-with-Strapi.paper?dl=0&rlkey=f7bbrw45b9i7ab85ofvr6yfgw

**Comment by ShadaW11** [comment]
@popoolatopzy thank you, our team will review the content and get back to you.

**Comment by popoolatopzy** [comment]
Alright

**Comment by ShadaW11** [comment]
@popoolatopzy your article has been published, please create and issue your invoice.
