### ISSUE TITLE
[TOPIC] i18n (Localization) with a Headless CMS

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#340]
**My Request**
Following the release of i18n it would cool to have an article about using i18n on your headless cms.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by vickywane** [comment]
@malgamves I want to work on this first before moving to best practices with i18n. 

I would send in an outline now.

**Comment by vickywane** [comment]
@malgamves @Mcastres this is an outline for the i18n feature with Strapi as a CMS.

 Outline:

- A general Introduction to i18n ( Internationalization )
- Benefits of adding i18n to an application
- Using i18n with Strapi
- Building a demo news blog to demo i18n with Strapi
- Conclusion

**Comment by malgamves** [comment]
Hey @vickywane could you do another app? We already have a news app being worked on. What frontend will you use for it?

**Comment by vickywane** [comment]
> Hey @vickywane could you do another app? We already have a news app being worked on. What frontend will you use for it? 

Alright. I could also switch the demo application to be an ecommerce store, displaying images for sale. Irregardless of the type of demo application built, it needs to demonstrate the i18n plugin in use.

I would make use of any of the existing Strapi-templates for React.js.

**Comment by malgamves** [comment]
Sure @vickywane sounds good to me! Ecommerce it is. When do you think you'll have a draft out??

**Comment by vickywane** [comment]
Next two weeks max

**Comment by malgamves** [comment]
Hey @vickywane sure, please follow the review and submission process in the [FAQ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46)
