### ISSUE TITLE
[TOPIC] i18n best practices on Strapi

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#341]
**My Request**
Following the release of i18n, it would be awesome to have a piece of content about the best practices of the i18n feature on Strapi.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by vickywane** [comment]
@Mcastres  @malgamves Can i propose an outline for an article on this

**Comment by malgamves** [comment]
hey @vickywane yes, would love to see an outline

**Comment by vickywane** [comment]
Hello @malgamves , 

I think it would be better if i start with explaining i18n first in [this article request](https://github.com/strapi/community-content/issues/340#issuecomment-824003615), then i can come back here to work on this, if not taken by someone else.

**Comment by Kaperskyguru** [comment]
Can i take this up?
