### ISSUE TITLE
Request for strapi tutorial

### ISSUE THREAD

**Issue by Abdulbarict** [strapi/community-content#344]
Please share a tutorial for learning strapi.

**Comment by MattieBelt** [comment]
Hey @Abdulbarict you should check this out: https://strapi.io/blog/welcome-to-strapi-academy.

**Comment by vcoisne** [comment]
@Abdulbarict you can also check out https://strapi.io/tutorials and https://www.youtube.com/channel/UC2w6UgktMHgTS-PN4D0utNw
