### ISSUE TITLE
[TOPIC] Strapi with Flutter tutorial

### ISSUE THREAD

**Issue by obitodarky** [strapi/community-content#345]
**My resource**
A detailed article that shows a Strapi setup and producing an API for a sample Flutter app with relevant tutorials and guides throughout. I will make a blog where I show what Strapi is, how to get started with Strapi and how to use it as an easy backend solution for a sample Flutter App that I will show how to build as well. This will help Flutter Devs get introduced to Strapi and its community.  

**My format**

- [x] Article
- [ ] Video

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by vcoisne** [comment]
@obitodarky that sounds awesome! How are things coming along on your end ?

**Comment by obitodarky** [comment]
@vcoisne I haven't started the blog yet but I have planned a small layout, do take a look.

- Intro to Strapi and Headless CMS
    - What is Headless CMS
    - What is Strapi
    - Why Strapi for Flutter
- Installing Strapi
    - Creating a project
    - Creating an admin user
    - Creating a Content Type     
    - Adding Content 
    - Publishing 
- Using API inside a Flutter App
    - Creating a project
    - Making Models for API Data
    - Fetching data from API
    - UI to show the data
    
 If there is anything I have missed or you have something in mind that you would like to see, please let me know!
 I haven't thought on what kind of app would I use but I would love to have your opinion on that.

**Comment by vcoisne** [comment]
Outline LGTM. I have assigned this topic to you. Please refer to our [FAQ](https://www.notion.so/strapi/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46) for submission when draft is ready for review 🙏

**Comment by ShadaW11** [comment]
Hey @obitodarky; been a while, any update on the article?

**Comment by obitodarky** [comment]
Hi @ShadaW11 
Sadly, not much. I haven't got enough time to work on the article, but I have kind of managed to get the UI part done for the mobile app. Functionally, would an app where you can see descriptions of movies, and add them to favorites work? Where we fetch this data from the Strapi API? 

Is there anything else you would like to see involving Strapi? The best I have right now are just some screenshots from the app, but integrating Strapi is still left sadly.  
If there is a structure where issues are closed after some point then do let me know because I'm not sure when I'll get the time to write an article...

**Comment by ShadaW11** [comment]
Hey @obitodarky I would love to see the integration of Strapi. I understand the time constraint. I will be closing the issue but would love to have you join our ["write for community" program](https://strapi.io/write-for-the-community) and maybe you would be able to write an article for us in the future.
