### ISSUE TITLE
[UPDATE OUTDATED CONTENT]  Import content plugin

### ISSUE THREAD

**Issue by Alhasan-softwear** [strapi/community-content#347]
**Description**
can you teach us how to make a later version of the plugin and the plugin is outdated please I kindly wish that the author should please edit it or remove it so no future developer will think it works thx 

**Link of the content**

https://strapi.io/blog/how-to-create-an-import-content-plugin-part-1-4
**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by vcoisne** [comment]
Thanks a lot @Alhasan-softwear for the heads up. I just reached out to the author cc @pouyamiralayi

**Comment by ShadaW11** [comment]
Hey @pouyamiralayi would you be interested in updating the plugin?

**Comment by PaulBratslavsky** [comment]
This is a great topic and would be nice to get someone update the previous article.  Let me know if anyone is interested on working on this topic.

**Comment by PaulBratslavsky** [comment]
We currently have this plug-in in the marketplace https://market.strapi.io/plugins/strapi-plugin-import-export-entries 

We are also working on the data export/import feature for the future that will be native to Strapi.  As I have more details I will let you know, in the mean time I will be closing this issue.
