### ISSUE TITLE
[REQUEST] Accessing Strapi content using vanilla Javascript (no frameworks)

### ISSUE THREAD

**Issue by russellwark** [strapi/community-content#354]
Can we have a short tutorial on how to access Strapi content via an API call using simple vanilla Javascript?

**Comment by purnimagupta** [comment]
@russellwark, As I understand, do you mean creating collections via Strapi Admin Panel and then using vanilla javascript to fetch the data from the database and displaying it on the screen?

**Comment by ChrisAchinga** [comment]
Taking up the task @russellwark

**Comment by osorvr** [comment]
@purnimagupta I need a tutorial or blog that can demonstrate that incase you know a link.

**Comment by zaracooper** [comment]
Hey @ShadaW11 . If this is still a worthwhile topic, could I take it on?

**Comment by ShadaW11** [comment]
Hey @zaracooper yes, would you please submit an outline?

**Comment by zaracooper** [comment]
Sure. I'll have one before the end of tomorrow. Thank you, @ShadaW11 .

**Comment by zaracooper** [comment]
Hey @ShadaW11. Here's the outline.

---

**Title:** _Build an Editorial Website with Vanilla JS and Strapi_

**Outline:**
1. Project introduction
    - Explain what an editorial website is
    - Explain how Strapi can support editorial organizations
    - Breakdown the project
2. Setting up the Strapi server
3. Creating article content types
4. Public roles setup on Strapi
5. Adding test data
6. Creating the editorial website
    - Make the landing page
    - Adding a script to fetch a list of articles
    - Make an article page
    - Adding a script to fetch a specific article
7. Conclusion
    - Explain what you should have accomplished by the end of the tutorial
    - Link to Strapi website and documentation

**Comment by ShadaW11** [comment]
Hey @zaracooper please go ahead

**Comment by zaracooper** [comment]
Hey @ShadaW11 . [Here's the draft.](https://www.dropbox.com/scl/fi/eywfezr9r21rbffkctal6/%5BDraft%5D-Build-an-Editorial-Website-with-vanilla-JavaScript-and-Strapi.paper?dl=0&rlkey=nelbdlblnpojhtwxmdw8squif)

**Comment by zaracooper** [comment]
Awesome. Thank you @ShadaW11 .

**Comment by ShadaW11** [comment]
Your article will be published today, thank you @zaracooper

**Comment by zaracooper** [comment]
Thank you, @ShadaW11 . Really appreciate the update.
