### ISSUE TITLE
[ISSUE] A listed tutorial card links to a wrong tutorial page

### ISSUE THREAD

**Issue by overgrowninfnat** [strapi/community-content#357]
**The concerning content**
In [strapi.io/tutorials](https://strapi.io/tutorials) is shown a tutorial card "How to build an E-commerce Store with Nuxt.js and Strapi" that links to a wrong tutorial page

**Issue**
The tutorial card "How to build an E-commerce Store with Nuxt.js and Strapi" links to ["How to Build a Real-time Chat Forum using Strapi, Socket.io, React and MongoDB"](https://strapi.io/blog/how-to-build-a-real-time-chat-forum-using-strapi-socket-io-react-and-mongo-db)

![strapiError](https://user-images.githubusercontent.com/17546550/116734941-2a2f8500-a9ee-11eb-8682-032162161c92.png)

**Comment by vcoisne** [comment]
Thank you @overgrowninfnat for the heads up. Really appreciate it. 

Ping @Mcastres - can you please take a look?

**Comment by Mcastres** [comment]
Thanks for the heads up @overgrowninfnat, it's fixed!
