### ISSUE TITLE
[TOPIC] JAMstack in 2020

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#36]
**My Request**

JAMstack in 2020

**Preferred Format**

- [x] Article
- [ ] Video

**Community vote**
🚀 If you can make the article!

**Comment by Quadrisheriff** [comment]
Hey there, I'd like to work on this 👍

**Comment by malgamves** [comment]
Awesome! Assigned this to you @Quadrisheriff . When do you think you'll be done with this?

**Comment by MenakaBasker** [comment]
@malgamves If it is still open, You can assign it to me. Thanks in advance.

**Comment by malgamves** [comment]
hey, @MenakaBasker sadly this topic has been taken up already. Feel free pick one "[Looking for Author](https://github.com/strapi/community-content/issues?q=is%3Aissue+is%3Aopen+label%3A%22Looking+for+author%22)"

**Comment by malgamves** [comment]
This was published - [Jamstack in 2021](https://strapi.io/blog/what-is-the-jamstack)
