### ISSUE TITLE
[TOPIC] What is JAMstack

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#37]
**My Request**
What is JAMstack

**Preferred Format**

- [x] Article
- [ ] Video

**Community vote**
🚀 If you can make the article!

**Comment by alexfinnarn** [comment]
I'm just perusing and lurking here for now, but to note, they call it the "Jamstack" since sites are built with more than JS as the language, e.g. Hugo and Go.  

https://github.com/jamstack/jamstack.org/issues/279

Still a lot of opinions, but I think that issue is good content for this article.

**Comment by zaracooper** [comment]
@malgamves could you assign me this?

**Comment by malgamves** [comment]
Awesome @zaracooper , I can't wait to have a look at this when it's done

**Comment by zaracooper** [comment]
@malgamves shared the dropbox paper draft with you. Let me know what you think.

**Comment by malgamves** [comment]
Thank you! I'll give it a review and mention you on the doc should I need any changes

**Comment by malgamves** [comment]
This was published - [What is the Jamstack?](https://strapi.io/blog/what-is-the-jamstack)
