### ISSUE TITLE
[TOPIC] The expansion of open source softwares

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#38]
**My Request**
The expansion of open source softwares

Why and how open source softwares are taking over the world

**Preferred Format**

- [x] Article
- [ ] Video

**Community vote**
🚀 If you can make the article!

**Comment by viclotana** [comment]
Hi, I am interested in writing about this.

**Comment by Mcastres** [comment]
Sure! It is yours ;)

**Comment by Mcastres** [comment]
Hey @viclotana, any news on this :)
