### ISSUE TITLE
[TOPIC] JAMstack + Open source

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#39]
**My Request**
JAMstack + Open source

Using the JAMstack is great but using open source JAMstack is awesome

**Preferred Format**

- [x] Article
- [ ] Video

**Community vote**
🚀 If you can make the article!

**Comment by narduin** [comment]
It's a great topic, I might be able to write something about open source Jamstack if you're still looking!

**Comment by Mcastres** [comment]
We might are still looking for this. Can you confirm @malgamves?

**Comment by malgamves** [comment]
Yes, we are @Mcastres ! If you are willing to get started with it @narduin I could assign it to you!

**Comment by viclotana** [comment]
I would like to take this on

**Comment by malgamves** [comment]
hey @viclotana - someone already expressed interest. We'll wait a bit to hear from them before moving forward.

**Comment by Mcastres** [comment]
Hey @narduin, just checking if there is any new about this :)

**Comment by narduin** [comment]
>  would like to take this on

I'm really sorry, I missed this reply!
I started working on a draft but I currently can't progress until my work schedule clears a bit.

If @viclotana is still interested, we could work together on this. Or is it not how you prefer to do things?

**Comment by vcoisne** [comment]
@narduin sorry about the late reply. You can join forces with someone else if that works for you and
@viclotana ?

**Comment by ShadaW11** [comment]
Hello @narduin any update on this topic? did you get a chance to progress? 
@viclotana Are you still interested in writing about this topic?

**Comment by zaracooper** [comment]
Hi @ShadaW11. Could I work on this if it's available?

**Comment by ShadaW11** [comment]
Hey @zaracooper Yess still available. If you are interested in this topic, please share with me an outline of what you have in mind.

**Comment by zaracooper** [comment]
Ok. I'll make an outline and post it here before the end of tomorrow. Thanks, @ShadaW11 .

**Comment by zaracooper** [comment]
Hey @ShadaW11 . Here's the outline.

----

**Title:** 
Beginner's Guide to Opensource Jamstack

**Outline:**
1. Introduction
    - What is Jamstack and why it's important
    - What is Opensource and why it's significant
    - Types of Jamstack Opensource Projects
    - Examples of popular projects
2. Static Site Generators
    - What they are
    - How they work
    - Applications of SSGs
    - Examples of some opensource SSGs
3. Headless CMSs 
    - What they are
    - How they work
    - Applications of Headless CMSs
    - Examples of some opensource Headless CMSs
4. Contributing to Opensource Jamstack Projects
    - How to get started with your contribution
    - Tips for successful contributions
5. Conclusion
    - Reiterate points covered in the article

**Comment by ShadaW11** [comment]
Hello @zaracooper thanks, looks good; Please go ahead and work on it.

**Comment by zaracooper** [comment]
Awesome. Thanks @ShadaW11. I'll have a draft for you by 21st September.

**Comment by ShadaW11** [comment]
Great thanks

--

Shada Wehbe

Program Marketing Manager - Paris, France

Website <https://strapi.io/> | Get a demo <https://strapi.io/demo> | Roadmap
<https://portal.productboard.com/strapi/1-roadmap/tabs/2-under-consideration>



Before you go: Learn what is Strapi in just 3 minutes
<https://strapi.io/documentation/v3.x/getting-started/quick-start.html>

**Comment by zaracooper** [comment]
Hey @ShadaW11 . I was wrapping up this piece but I feel like it only touched on the Javascript-Markup part of Jamstack. I didn't touch on the open-source APIs available out there like Strapi. 

I want to add a paragraph or two about it. Could I submit this before the end of the week instead of the 21st?

**Comment by ShadaW11** [comment]
Hey @zaracooper Yes, I prefer to have API covered in the piece, please feel free to send it in the next few days.

**Comment by zaracooper** [comment]
Awesome. Thank you so much for understanding @ShadaW11 .

**Comment by zaracooper** [comment]
[Here's the draft](https://www.dropbox.com/scl/fi/eb0r4bsxcpcps5v2bepza/Draft-Beginner-s-Guide-to-Opensource-Jamstack.paper?dl=0&rlkey=qazw2ym51ugk586mird8ti6mf) @ShadaW11 . I shared it with you on Dropbox as well.

**Comment by ShadaW11** [comment]
@zaracooper Thanks will get back to you asap

**Comment by zaracooper** [comment]
Hey @ShadaW11. Did you get a chance to look at the piece?

**Comment by ShadaW11** [comment]
Hey @zaracooper apologies for the delay. I will get back to you hopefully this week.

**Comment by zaracooper** [comment]
No problem. Thank you.

**Comment by ShadaW11** [comment]
Hey @zaracooper your article has been reviewed. Could you please check the comments

**Comment by zaracooper** [comment]
Ok @ShadaW11 . Making the changes now.

**Comment by zaracooper** [comment]
Hey @ShadaW11 . I'm done with the changes but I had one question on a comment that was not clear.

**Comment by MattieBelt** [comment]
Hey @zaracooper,

I just elaborated by comment, changes looks great, thanks for writing this article!

**Comment by zaracooper** [comment]
Thanks, @MattieBelt . @ShadaW11, I'm done addressing the comments.

**Comment by ShadaW11** [comment]
@zaracooper thank you, your article will be published soon

**Comment by ShadaW11** [comment]
@zaracooper your article was published. Feel free to issue an invoice. Thank you
