### ISSUE TITLE
Using Ansible For Automatic Deployment Of A Strapi CMS To Amazon AWS

### ISSUE THREAD

**Issue by hauben** [strapi/community-content#395]
**Using Ansible For Automatic Deployment Of A Strapi CMS To Amazon AWS**

Maybe the tutorial I recently published on [Medium.com](https://haubenschild.medium.com/automate-your-amazon-aws-deployment-of-your-strapi-based-project-with-ansible-4ac3e7dc8d4d) could be used/adapted.

Draft: Use Ansible to automatically spin up the needed AWS cloud infrastructure and place a configured Strapi application into it.

**My format**

- [x] Article
- [ ] Video

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hey @hauben awesome content, You can [feature](https://github.com/strapi/community-content/tree/master/tutorials#how-to-write-a-tutorial) your tutorial on [Strapi](https://strapi.io/tutorials). Would be awesome if you could also join our ["write for community" program ](https://strapi.io/write-for-the-community) and work on new tutorials.
