### ISSUE TITLE
[ISSUE] Toast UI tutorial doesn't work

### ISSUE THREAD

**Issue by slavik0329** [strapi/community-content#397]
**Toast UI tutorial doesn't work**

**Change the default WYSIWYG to Toast UI editor tutorial**

After installing the npm toastui strapi module and building admin UI, the wysiwyg editor does not display.

**Comment by Mcastres** [comment]
Hello @slavik0329 👋 
I just tested the editor this morning and I can confirm that it is working. However the connection to the media lib is not working anymore.

Are you sure that you built your admin?

**Comment by slavik0329** [comment]
@Mcastres Yes, I have run Yarn build and waited for rebuild. It seems that strapi is unable to even recognize the plugin when its in node_modules.

**Comment by Mcastres** [comment]
This would need an update from the plugin which seems to be outdated.
