### ISSUE TITLE
[TOPIC] x reasons you should open source your project

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#40]
**My Request**
x reasons you should open source your project

List the benefits from making your project open source

**Preferred Format**

- [x] Article
- [ ] Video

**Community vote**
🚀 If you can make the article!

**Comment by bigpreshy** [comment]
I can make write this article

**Comment by Mcastres** [comment]
Great @bigpreshy, same as the other one, I'll assign you the issue

**Comment by bigpreshy** [comment]
Should I post a link of what I have done so far here?

**Comment by malgamves** [comment]
hey @bigpreshy yes! Have you self published or would you like this published on the Strapi blog?

**Comment by bigpreshy** [comment]
I'd like this to be published in Strapi blog

**Comment by malgamves** [comment]
Awesome! Could you share a link to a Dropbox Paper file so I can review it and publish it. 🎊

**Comment by bigpreshy** [comment]
Please, I am really sorry for the belatedness

**Comment by bigpreshy** [comment]
https://paper.dropbox.com/doc/tbqovN7vj7AywYLlEt4XH

**Comment by malgamves** [comment]
No worries @bigpreshy I'm having a look now. Thanks for sending it in.
