### ISSUE TITLE
[TOPIC] Flow of Admin Panel

### ISSUE THREAD

**Issue by yateshchhabra1995** [strapi/community-content#401]
**My Request**
I am using the community edition, as by installing the **npx create-strapi-app my-project --quickstart** In this, i signup with admin account on localhost.  but when we create Collection Types and add some data in that collection, like having Categories as Collection and  we enter the name of the Category as Dinner or something else. I want to know the flow of the api where its stores in which folder it exists. I checked in the api folder there is only routes defined and nothing in the services and controllers.
I checked for the documentation, but nothing find in that.
Like in a Scenario, I want if the collection created or updated by admin, it will be printed  in the console.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by ShadaW11** [comment]
Hey @yateshchhabra1995 Thank you for writing this. We will be working on creating more beginner content. In the meantime you can get direct support by [posting in our forum here](http://forum.strapi.io)
