### ISSUE TITLE
[SUBMIT] Custom routes, external data, graphql resolvers

### ISSUE THREAD

**Issue by RazvanCretu** [strapi/community-content#407]
**Create custom routes to fetch external data and allow graphql with custom resolvers.**

Hello 👋 

I would like to provide an article for the community in which I would describe how to set-up custom routes in order to be able to fetch external data and also create custom graphql queries/resolvers in order thw newly created routes.

**My format**

- [x] Article
- [ ] Video

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hey @RazvanCretu Thank you an apologies for the delay. Would you be able to send over an outline of what you have in mind for this article? similar to [this](https://github.com/strapi/community-content/issues/421)

**Comment by RazvanCretu** [comment]
Hi @ShadaW11 no worries at all, it's a busy month for me too.

Basically what I want is to:
* create some custom endpoints that will point to an external data api
* create custom graphql resolvers for those endoints and enable custom graphql queries/mutations
* connecting it to a frontend like nextjs (maybe)

Other than the third point I don't see it related to the one you mentioned.

Let me know if this works. :)

**Comment by ShadaW11** [comment]
Hey @RazvanCretu apologies for the confusion, my reference was for the outline structure and not content. Connecting it to Nextjs frontend would be AWESOME, would you be able to do that? Could you also please fill in the author form in this page https://strapi.io/write-for-the-community and go over the FAQ ( for more details around article guidelines, payment & invoice submission)

**Comment by RazvanCretu** [comment]
Hi @ShadaW11 Sorry fot the late reply too , I was quite busy with my thesis last couple of weeks.

Sure, I could connect it to a NextJs frontend.

I've completed the form you mentioned and once I got some free time I'll start to work on it :)

Thanks for letting me know!

**Comment by ShadaW11** [comment]
Hey @RazvanCretu Perfect, yes, I understand no worries take your time. I assigned you the article. If you need any help, I'm here 👋

**Comment by ShadaW11** [comment]
Hey @RazvanCretu any update?

**Comment by RazvanCretu** [comment]
Hi @ShadaW11 

I only got the code part for now. I just finish with my thesis last week. 
I'll start on the article this week and I am expecting to finish it by the next Monday.

Does this work?

**Comment by ShadaW11** [comment]
Hey @RazvanCretu yes, that would be great.

**Comment by RazvanCretu** [comment]
Hi @ShadaW11 

It is ready for review :)

**Comment by ShadaW11** [comment]
@RazvanCretu Awesome. Thank you for sharing the article. I will get back to you once it is reviewed.

**Comment by ShadaW11** [comment]
@RazvanCretu Your article has been published, please send the edited invoice. Thank you.
