### ISSUE TITLE
[TOPIC] How to build a Forum App using Next and Strapi

### ISSUE THREAD

**Issue by Kaperskyguru** [strapi/community-content#409]
**My Request**

This article intends to explain how to build a real-world Forum application using Strapi backend and NuxtJS for the frontend.

In this article, we are going to handle Authentication and Authorization. We will implement best practices in building a scalable application with strapi.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by Kaperskyguru** [comment]
I want to work on this topic

**Comment by ShadaW11** [comment]
@Kaperskyguru Thank you, as suggested, lets work on the other articles that you suggested first before we proceed.

**Comment by Kaperskyguru** [comment]
Hello @ShadaW11,

Below is my outline for this article.

Introduction
What is Strapi - A Headless CMS?
Scaffolding a Strapi project
Build the Forum collections
Build the Post collections
Seed the databases
Allowing Public access
Building the Nutx.js app
Set up Tailwind CSS
Build components
Testing the app
Conclusion.

The article will be focused on introducing beginners or readers to building a real-world Forum System with Nuxt.js and Strapi as the backend.

**Comment by ShadaW11** [comment]
Hey @Kaperskyguru we would like to have more nextjs content if that's possible.

**Comment by ShadaW11** [comment]
Please @Kaperskyguru update the outline here also please

**Comment by Victory-ET** [comment]
Hey @ShadaW11, 
I would love to take on this topic. 
Here's my outline:

# Topic: Building a Forum app with NextJs and Strapi

> While programming, programmers encounter various challenges which make them solicit help with solving these problems. Forums provide a tech community of enthusiasts who can assist with these problems. We will be building a forum site with [NextJs](nextjs.org) on the Front-end and [Strapi](strapi.io) for content management

## Goals

In this tutorial, we will cover building a forum website and providing user authentication and authorization on the site.

## Prerequisite 

To fully grasp this tutorial, knowledge of NextJs and Strapi is required.

## Outline

- Installing dependencies

- What is Strapi

- Strapi Setup

	- Collection and field setup

	- Forum collection and database

- Building the website layout

	- View page layout

	- Upload page

		- Form creation

		- Upload data from the form

- Building comment section 

- Connecting Strapi to the front-end

- Adding user authentication and authorization

- Conclusion

- Resources

**Comment by ShadaW11** [comment]
Hey @Victory-ET Outline looks good, can you please register here https://strapi.io/write-for-the-community and then please go over the guidelines prior to writing your article. one last thing, I suggest waiting until the final v4 release is out (in around 20 days) to write the article.

**Comment by Victory-ET** [comment]
Hi @ShadaW11,

Thanks a lot for the feedback. I will get started as soon as v4 is released. I'm looking forward to it.

**Comment by ShadaW11** [comment]
Hey @Victory-ET can you start working on the article right away?

**Comment by Victory-ET** [comment]
Hi @ShadaW11,

I'm done with the article. Here is a link to it: https://www.dropbox.com/scl/fi/1tz75onvqjdkvozist1xh/How-to-Build-a-Forum-App-with-NextJs-and-Strapi-CMS.paper?dl=0&rlkey=1n5kaazcahi15w8qo5xvu2k1b

**Comment by ShadaW11** [comment]
Hello @Victory-ET thank you, someone from the team will review the article and get back to you as soon as possible.

**Comment by ShadaW11** [comment]
Hello @Victory-ET can you please double check the image template you used, the title is still the old one.

**Comment by Victory-ET** [comment]
Hello @ShadaW11, I've corrected the mistake on the image. Thanks.

**Comment by ShadaW11** [comment]
hello @Victory-ET your article will be published this week. Feel free to issue an invoice.

**Comment by Victory-ET** [comment]
Thanks, @ShadaW11.  I've submitted the invoice via the form. I used the GitHub issue link as the article link.
