### ISSUE TITLE
[TOPIC] Build a Crypto Stats App with Electron and Strapi

### ISSUE THREAD

**Issue by Kaperskyguru** [strapi/community-content#410]
**My Request**

This article is intended to demonstrate how to build a Desktop application with Strapi backend and Electron. In this article, we will create a desktop version of a Crypto Statistics App (Coinstats). Furthermore, it will demonstrate how Strapi can be used to develop a Desktop application with Electron.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by Kaperskyguru** [comment]
I want to work on this topic

**Comment by ShadaW11** [comment]
@Kaperskyguru you have a lot of open topics, I suggest you send a proposal for the other ones before proceeding on this.

**Comment by Kaperskyguru** [comment]
Hello @ShadaW11,

The Crypto world is trending now and I want to show the readers how to build a Crypto Statistics Desktop App with Strapi.

Below is my outline for this article.

Introduction
What is Strapi - A Headless CMS?
Scaffolding a Strapi project
Build the Crypto collections
Seed the databases with Coinbase API
Allowing Public access
Building the Electron.js app
Creating Electron.js pages and Menus
Testing the app
Conclusion.

The article will be focused on introducing beginners or readers to building a real-world Crypto Currency Statistics System with Electron.js and Strapi as the backend.

**Comment by ShadaW11** [comment]
Hey @Kaperskyguru Looks good
