### ISSUE TITLE
[TOPIC] Build a Crypto Alert App with Strapi and Next.js

### ISSUE THREAD

**Issue by Kaperskyguru** [strapi/community-content#411]
**My Request**

This article intends to demonstrate how to develop a Crypto Alerting Application with Strapi and Nuxt.js. The App will alert users when the price of a coin is up to a fixed amount and below a certain threshold.

The article will show how to use Authentication and Authorization, manage different user accounts, and different types of users with Strapi.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by Kaperskyguru** [comment]
I want to work on this content

**Comment by ShadaW11** [comment]
@Kaperskyguru Heyy Could you please send me an outline of what you have in mind?

**Comment by Kaperskyguru** [comment]
Hello @ShadaW11,

The Crypto world is trending now and I want to show the readers how to build a Crypto App with Strapi.

Below is my outline for this article.

Introduction
What is Strapi - A Headless CMS?
Scaffolding a Strapi project
Build the Crypto collections
Seed the databases with Coinbase API
Allowing Public access
Building the Nuxt.js app
Build components
Testing the app
Conclusion.

The article will be focused on introducing beginners or readers to building a real-world Crypto Currency alerting System with Nuxt.js and Strapi as the backend.

**Comment by ShadaW11** [comment]
Hey @Kaperskyguru same comment, would you be able to use next?

**Comment by ShadaW11** [comment]
Thank you updating the title, @Kaperskyguru please update the outline as well
