### ISSUE TITLE
[TOPIC] How to build a Ticketing App using Vue.js and Strapi

### ISSUE THREAD

**Issue by Kaperskyguru** [strapi/community-content#412]
**My Request**

In this article, I intended to cover everything related to build a real-world Ticketing System with Strapi and Vue.js, where users can buy, book, sell, and use tickets for upcoming events.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

**Comment by Kaperskyguru** [comment]
I want to work on this topic

**Comment by ShadaW11** [comment]
Hey @Kaperskyguru, nice, can you please send me an outline of what you have in mind?

**Comment by Kaperskyguru** [comment]
Hello @ShadaW11,

Below is my outline for this article.

Introduction
What is Strapi - A Headless CMS?
Scaffolding a Strapi project
Build the Ticket collections
Build the Event collections
Seed the databases
Allowing Public access
Building the Vue app
Set up Tailwind CSS
Build components
Testing the app
Conclusion.

The article will be focused on introducing beginners or readers to building a real-world Ticketing System with Vue.js and Strapi as the backend.

**Comment by ShadaW11** [comment]
Hello @Kaperskyguru its a good topic and the outline is good, but we need to choose among the ones you have submitted the top ones. So I believe this we can work on next month.

**Comment by ShadaW11** [comment]
@oviecodes any update?

**Comment by oviecodes** [comment]
Hey @ShadaW11 , it's in progress

**Comment by ShadaW11** [comment]
any update @oviecodes

**Comment by oviecodes** [comment]
hey @ShadaW11 , here's the link to the article

https://www.dropbox.com/scl/fi/oamvdmajkmvh21ycd6fx8/How-to-build-a-Ticketing-App-using-Vue.js-and-Strapi.paper?dl=0&rlkey=kg50qbdt3rwus9bs8bsqql6rh

**Comment by ShadaW11** [comment]
@oviecodes thanks, your article is being reviewed. I will get back to you as soon as possible with feedback.

**Comment by ShadaW11** [comment]
@oviecodes your article is approved please issue your invoice
