### ISSUE TITLE
[UPDATE] Include Scottish Gaelic in the i18n Plugin

### ISSUE THREAD

**Issue by conorjohn** [strapi/community-content#416]
**My update**

Hello 👋 

I'm adding Celtic (Irish, Manx, Cornish, Welsh etc) languages to this app I am making with Strapi as the CMS, genuinely love it. I noticed Scottish Gaelic was missing, do you think we could add add that to the plugin? If it's something I can help with that'd be great. And is there a way I can contribute if I notice any more missing? Because I noticed Navajo is missing too but I don't have a use for it at the moment.
![image](https://user-images.githubusercontent.com/7226984/121781859-a2b56400-cb9e-11eb-9f74-f089ae74b0e6.png)

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thanks for your time

**Comment by ShadaW11** [comment]
Hey @conorjohn thank you, would you mind posting this message [here](https://github.com/strapi/strapi)

**Comment by conorjohn** [comment]
Oh sorry, do you mean file this as an issue under /strapi/strapi? 
I'm not used to filing tickets like this

**Comment by conorjohn** [comment]
Oh sorry @ShadaW11  do you mean file this as an issue under /strapi/strapi?
I'm not used to filing tickets like this

**Comment by ShadaW11** [comment]
@conorjohn yes exactly. No worries at all.

**Comment by derrickmehaffy** [comment]
> Hey @conorjohn thank you, would you mind posting this message [here](https://github.com/strapi/strapi)

@ShadaW11 for questions like this, they should be going to our forum: https://forum.strapi.io and not the monorepo
