### ISSUE TITLE
[TOPIC] The top 10 static website generators in 2020

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#42]
**My Request**
The top 10 static website generators in 2020

**Preferred Format**

- [x] Article
- [ ] Video

**Community vote**
🚀 If you can make the article!

**Comment by malgamves** [comment]
Hey @Mcastres  I'd like to take this

**Comment by malgamves** [comment]
Hey @Mcastres I'm ready to go ahead and publish this.
