### ISSUE TITLE
[SUBMIT] Creating a Photo Gallery with Strapi and Cloudinary

### ISSUE THREAD

**Issue by bigpreshy** [strapi/community-content#421]
**My resource**

I'd like to work on tutorial where I'd create photo gallery with Strapi.
Here is my outline:
Getting started
Setting Up Strapi (Content Type creation)
Setting up Cloudinary (for photo storage)
Setting up a frontend (React and Redux)
Connecting the frontend to Strapi (to fetch the data)
Beautifying it.
**My content is**

- [x] Creating a Photo Gallery with Strapi and Cloudinary

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hey @bigpreshy love the outline, would it possible to replace Reach with Nextjs?

**Comment by bigpreshy** [comment]
> Hey @bigpreshy love the outline, would it possible to replace Reach with Nextjs?


I can replace React with Nextjs. But I personally think it might be an overkill because of I won't use so many features of Nextjs...
But React, it's unopinionated.

**Comment by ShadaW11** [comment]
Hey @bigpreshy; yes it would be great if you can replace It with Nextjs. I would suggest adding some functionalities to utilize the features of Nextjs.

**Comment by bigpreshy** [comment]
Okay. I can do that

**Comment by ShadaW11** [comment]
Hey @bigpreshy any update on this article?

**Comment by ShadaW11** [comment]
Hello @bigpreshy How are you? I hope you have been able to finish the article?

**Comment by bigpreshy** [comment]
I am still on it. Will finish soon

**Comment by ShadaW11** [comment]
@bigpreshy awesome, any update?

**Comment by bigpreshy** [comment]
Yes.
[Here](https://paper.dropbox.com/doc/HCTBrIudEU59VPqD1x0Ah)

**Comment by ShadaW11** [comment]
Hey @bigpreshy Apologies for the delay, well received, I will get back to you as soon as possible.
