### ISSUE TITLE
[SUBMIT] How to create a blog with SvelteKit and Strapi

### ISSUE THREAD

**Issue by arnu515** [strapi/community-content#422]
**My resource**
[SvelteKit](https://kit.svelte.dev) is a new SSR framework, like NextJS, but for React instead of Svelte. It looks really promising, and I want to teach the Strapi community how they can create a blog website with SvelteKit using Strapi as the CMS.

Outline:
- Introduction
- Goals
- Prerequisites
- Creating a Strapi Project
  - Creating Content Types
  - Setting up Roles and Permissions
- Creating a SvelteKit Project
  - Adding TailwindCSS to our project
- Fetch blog posts
- Authentication and Authorization
- Create posts
- Update posts
- Delete posts
- Conclusion

**My content is**

- [x] A basic introduction to [SvelteKit](https://kit.svelte.dev) and Strapi

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hey @arnu515 awesome outline and subject, looking forward to your article. 
Next steps:
- Please register your author details by [filling the form](https://strapi.io/write-for-the-community) if this is your first article. 
- Take a look at our [article guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md) before you start writing.

**Comment by arnu515** [comment]
[Here's my article in Dropbox Paper](https://www.dropbox.com/scl/fi/a8j2h6foueim7yconlp89/Untitled-2.paper?dl=0&rlkey=33uhw7rokc4dspnvlndw92udr)

[And here's the original file in markdown](https://gist.github.com/arnu515/72c95b2d68a8e6837d9c30064c464a24), if you need that too

Hope it'll get accepted 🤞

**Comment by ShadaW11** [comment]
Hey @arnu515 thank you so much. Will get back to you with feedback soon.

**Comment by ShadaW11** [comment]
Hey @arnu515 Could you please give me edit access on dropbox

**Comment by arnu515** [comment]
Sure. [Here's the new link](https://www.dropbox.com/scl/fi/a8j2h6foueim7yconlp89/Untitled-2.paper?dl=0&rlkey=1ry34uivug0wqldf38pxwxmtx)

**Comment by ShadaW11** [comment]
Thank you. Could you please register in the form in this page to collect your author details when publishing the article:
https://strapi.io/write-for-the-community

**Comment by arnu515** [comment]
I've registered for the form there. Thank you

**Comment by ShadaW11** [comment]
[Your article has been published](https://strapi.io/blog/how-to-create-a-blog-with-svelte-kit-strapi). Congrats @arnu515 check our community page to issue and submit a payment.
