### ISSUE TITLE
[TOPIC] To-do app using Svelte, Strapi and TailwindCSS

### ISSUE THREAD

**Issue by ejirocodes** [strapi/community-content#423]
**My resource**
[Svelte](https://svelte.dev/) is a component framework that runs at build time, converting your components into highly efficient imperative code that surgically updates the DOM. Svelte approach to building web apps is unique and I will like to teach the Strapi community how they can build a to-do app with Svelte using Strapi as the CMS and Tailwind for styling.

**Outline:**

- Introduction
- Goals
- Prerequisites
- Creating a Strapi Project
- Creating Content Types
- Setting up Roles and Permissions
- Bootstrap a Svelte Project
- Adding TailwindCSS to our project
- Fetch Todo items
- Authentication and Authorization
- Create todo items
- Update todo items
- Delete todo items
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think? @malgamves **
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ejirocodes** [comment]
@ShadaW11, I've submitted my details and gone through the guideline. I'll start working on the article as soon as possible. Thanks :)

**Comment by ShadaW11** [comment]
Thanks @ejirocodes looking forward for your article.

**Comment by ejirocodes** [comment]
Hi @ShadaW11, here is a [link](https://www.dropbox.com/scl/fi/f1wz40u1a5ifq4952pq5g/Building-a-To-do-app-with-Svelte-Strapi-and-TailwindCSS.paper?dl=0&rlkey=zbq1hu3sda1a3raqxtgfjklaj) to the article, let me know what you think.

**Comment by ShadaW11** [comment]
Hey @ejirocodes thank you so much, your article is being reviewed, I will get back to you with feedback.

**Comment by ejirocodes** [comment]
Thanks for the update @ShadaW11

**Comment by ShadaW11** [comment]
@ejirocodes Your article has been published. Please check our FAQ to issue and submit an invoice. Thank you again. Awesome article

**Comment by ShadaW11** [comment]
@ejirocodes Well received, you should receive the payment in 10 working days max. thank you so much.

**Comment by ejirocodes** [comment]
Awesome! Thanks for the update, @ShadaW11
