### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by lazy59** [strapi/community-content#425]
**The concerning content**
`articles-categories.gql` always get the same result

**Issue**
No matter what the `id` is, the same result will be returned by `graphql`.
![image](https://user-images.githubusercontent.com/27847851/122949091-f9e0e300-d3ad-11eb-8995-afc09c6acdf3.png)

**Comment by ShadaW11** [comment]
Hello @lazy59, @Mcastres will get back to you as soon as possible. However our community content section is not used for support but rather for articles. For future queries, you can post on our [form](http://forum.strapi.io) and we would be happy to help out.

**Comment by Mcastres** [comment]
Hey @lazy59, do you have a repository of this project where I can test?

**Comment by lazy59** [comment]
Hey, thank you for your reply. I've solved the problem by adding new collection types and deleting the old ones. Although I don't know why the problem happened before, it seems to work well now.
And the repository I use is [nuxt-strapi-apollo-blog](https://github.com/strapi/community-content/tree/master/tutorials/code/nuxt-strapi-apollo-blog).
