### ISSUE TITLE
[Request New Content] Building a Marketing Site with Forms FUnctionality with React and Strapi 

### ISSUE THREAD

**Issue by malgamves** [strapi/community-content#426]
Hello 👋 

I would like to see a tutorial that used Strapi and React to build a Startup Site that has form functionality for something like a news letter. It would be nice to see if any React 18 features can be talked about to. 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Kaperskyguru** [comment]
Hello @ShadaW11, @malgamves,

I will love to take up this task.

Below is my outline for this article.

Introduction
What is Strapi - A Headless CMS?
Scaffolding a Strapi project
Build the Newsletter collections
Seed the databases
Allowing Public access
Overview Of React 18
Building the React app
Build components
Testing the app
Conclusion.

The article will introduce beginners or readers to building a real-world Marketing Site with form implementation using React.js and Strapi as the backend.

**Comment by ShadaW11** [comment]
Hey @Kaperskyguru Looks good.

**Comment by ShadaW11** [comment]
@Kaperskyguru the dropbox link is missing the core content of the article. Kindly provide an estimated date of delivery. The article has been in progress since more than 3-4 months.

**Comment by ShadaW11** [comment]
The topic is now open for other authors.

**Comment by Vic-Orlands** [comment]
@ShadaW11, I would love to work on this article. Below is my outline;

Outline;

- Introduction
- Back-end Setup
    - Strapi Setup
        - Add Newsletters
    - Mailchimp Setup
- Front-end Setup
    - React Setup
    - Build Marketing Site (including React 18 features)
    - Mailchimp Integration
- Conclusion

**Comment by ShadaW11** [comment]
Hello @Vic-Orlands thank you for pitching the outline, its a great one. Can you make sure to take into consideration also all the elements mentioned in the above outline?

**Comment by ShadaW11** [comment]
@Kaperskyguru I know you wrote part of the article. Maybe you can share with @Vic-Orlands what you have worked on already?

**Comment by Vic-Orlands** [comment]
@ShadaW11 Okay, I will reach out to @Kaperskyguru about the elements.

**Comment by Vic-Orlands** [comment]
@ShadaW11 I have reached out to him. I will begin working on the tutorial while waiting for him to share what he has worked on. The article will be ready in two weeks' time i.e on the 17th

**Comment by Vic-Orlands** [comment]
@ShadaW11 I am done with the article. Added a React 18 feature as requested and also a newsletter form functionality. This is the draft link https://www.dropbox.com/scl/fi/zh1wfytqjg4nrvl9tyk59/Building-a-Marketing-Site-with-Forms-Functionality-with-React-and-Strapi.paper?dl=0&rlkey=xpi93ar6jz35zlnymxjoyuszh

**Comment by Vic-Orlands** [comment]
@ShadaW11 any update on this?

**Comment by Vic-Orlands** [comment]
> @Vic-Orlands Sure, also make sure that your article is v4 compatible.

The article is v4 compatible @ShadaW11

**Comment by ShadaW11** [comment]
Hello @Vic-Orlands thank you for the update. Apologies for the delay - due to the holiday break. Our team will review your article asap.

**Comment by Vic-Orlands** [comment]
Okay, thank you

**Comment by Vic-Orlands** [comment]
@ShadaW11 any update yet.

**Comment by Vic-Orlands** [comment]
@ShadaW11 

> Hello @Vic-Orlands thank you for the update. Apologies for the delay - due to the holiday break. Our team will review your article asap.

Still haven't gotten any reply since this and no one has tried reviewing the draft.

**Comment by ShadaW11** [comment]
Hello @Vic-Orlands I am extremely sorry for the delay. I have added your article in the top of our pipeline, your article will be reviewed in one working week. Please note that the reviewer will leave comments inside the dropbox article. Thank you

**Comment by Vic-Orlands** [comment]
> Hello @Vic-Orlands I am extremely sorry for the delay. I have added your article in the top of our pipeline, your article will be reviewed in one working week. Please note that the reviewer will leave comments inside the dropbox article. Thank you

Hello @ShadaW11 seems like I might just forget about the article because at this point, it is annoying and disappointing. This is the 3rd month and yet nothing.

**Comment by malgamves** [comment]
Hey @Vic-Orlands we're a little understaffed but will get a reviewer on this today. Thanks for being so patient on this

**Comment by Vic-Orlands** [comment]
Okay, no problem

**Comment by ShadaW11** [comment]
@Vic-Orlands apologies, we were busy with StrapiConf, I will be sending your payment right away. Thank you and we hope you publish soon additional articles.
