### ISSUE TITLE
[Request New Content] Next Blog with Previews and Next Image

### ISSUE THREAD

**Issue by malgamves** [strapi/community-content#427]
Hello 👋 

I'd love to see if someone can put together a piece on how to build a Next.js blog that leverages Next previews and optimized images with content from Strapi.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by amirtds** [comment]
@malgamves I can take this one ✋

**Comment by ShadaW11** [comment]
Hey @amirtds, Could you please share an outline for the proposed article.

**Comment by amirtds** [comment]
Hi @ShadaW11 It will look something like following

- Intro
  - What is Strapi
  - Why use Strapi as your Headless CMS
  - What is Nextjs
  - Optimize image loading with next/image
  - Get draft previews with Nextjs preview mode
- Installation
  - Nextjs
  - Strapi
- Setup and Development
  - Create blog content type in Strapi
  - Setup Strapi blog APIs
  - Data fetching in Next.js
  - Create components and pages
  - Use Next Image
  - Setup Next.js Preview mode
- Demo Site
 - Final Thoughts on the topic

I will record videos for installation and development section

**Comment by ShadaW11** [comment]
Hello @amirtds looks great. I would suggest using screenshots or GIFs instead of video recordings. Looking forward to receiving the article

**Comment by amirtds** [comment]
Hi @ShadaW11 Awesome. sure thing I can using Screenshots and GIFs instead of video. 🚀

**Comment by amirtds** [comment]
Hi @ShadaW11 The doc is ready at https://www.dropbox.com/scl/fi/e1kivp5ojyzis91z2ggcn/How-to-use-Image-and-preview-in-your-NextjsStrapi-blog.paper?dl=0&rlkey=qhctxtbfc4080ssfas7o4ltd4 If you have any questions or comment feel free to let me know

**Comment by ShadaW11** [comment]
Hey @amirtds thank you, I will check the article and get back to you as soon as possible

**Comment by amirtds** [comment]
Thanks @ShadaW11 for letting me know. Looking forward to hearing from you 👋

**Comment by ShadaW11** [comment]
Hey @amirtds Congrats your article is now published. https://strapi.io/blog/how-to-use-image-and-preview-in-your-nextjs-strapi-blog Please check our FAQ in the [Write for the Community](https://strapi.io/write-for-the-community) page to submit an invoice. Also please sign up on our [forum](https://forum.strapi.io/t/how-to-use-image-and-preview-in-your-nextjs-strapi-blog/8050) to automatically receive notifications once a comment is made on the blog post.

**Comment by cubiteDevops** [comment]
Woohoo Thanks @ShadaW11 for letting me know. 👏

**Comment by amirtds** [comment]
Woohoo Thanks @ShadaW11 for letting me know. 👏

**Comment by ShadaW11** [comment]
Hey @amirtds your payment will be issued next week. Could you also please keep an eye on the comments written on your blog post and reply to them? https://strapi.io/blog/how-to-use-image-and-preview-in-your-nextjs-strapi-blog

**Comment by amirtds** [comment]
Hi @ShadaW11 Thanks for letting me know. I keep an eye on the blog post.
