### ISSUE TITLE
[TOPIC] The top 10 front-end frameworks in 2020

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#43]
**My Request**
The top 10 front-end frameworks in 2020

**Preferred Format**

- [x] Article
- [ ] Video

**Community vote**
🚀 If you can make the article!

**Comment by hacktivist123** [comment]
Hey @Mcastres I can work on this.

**Comment by Mcastres** [comment]
Awesome @hacktivist123 ! It's yours :)

**Comment by hacktivist123** [comment]
Thanks, I’ll get to it.
