### ISSUE TITLE
[Request New Content] 10 reasons to move from Traditional to headless CMS

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#432]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by daacode** [comment]
Hello @ShadaW11 I'm interested in this topic

**Comment by ShadaW11** [comment]
Hey @daacode Thank your your interest in this topic, but I suggest you focus on the other article first and then start on other ones.

**Comment by zanasruth** [comment]
Hello, I'm interested in this topic

**Comment by zanasruth** [comment]
Hello, @ShadaW11 I'm interested in this topic

**Comment by ShadaW11** [comment]
Hello @zanasruth happy to hear from you. Can you please share an outline of what you have in mind for this article?

**Comment by zanasruth** [comment]
Hi @ShadaW11. Sorry for my late response. Here's the outline I've prepared:


What is a Headless CMS?

What is a Traditional CMS?

Differences Between a Traditional and Headless CMS

10 Reasons you should go Headless
1. Omnichannel Freedom
2. Future proof Tech Stack 
3. Scalability
4. Faster Editing
5. Security 
6.  Easy Third-Party API Integration 
7. Frontend Flexibility 
8. No-bloat Systems
9. Brand Customization
10. Performance

Conclusion

**Comment by ShadaW11** [comment]
Hello @zanasruth Great outline. I would suggest starting with an intro to CMS & content, then adding 2 short paragraphs before the 10 reasons. 3 lines introducing what a traditional cms is, and another 5 lines introducing what a Headless CMS is and then the 10 reasons below the 2 paragraphs. Can you please let me know when will you deliver the article? Looking forward to it.

**Comment by zanasruth** [comment]
Hi @ShadaW11 

I will adjust the outline and make the additions you highlighted. 

The article will be ready by next week Friday

**Comment by ShadaW11** [comment]
Awesome @zanasruth looking forward to receiving it.

**Comment by zanasruth** [comment]
Hi @ShadaW11. ![The draft is ready](https://www.dropbox.com/scl/fi/md5bpf7clr85gh2q6pjnr/10-Reasons-To-Move-From-Traditional-To-Headless-CMS.paper?dl=0&rlkey=b08c610q7f5iyane2cl91uyqz). I look forward to your feedback.

**Comment by zanasruth** [comment]
Hi @ShadaW11. The draft is ready. Here's a link to [the article](https://www.dropbox.com/scl/fi/19g9f5br52cn862stb5pr/10-Reasons-To-Move-From-Traditional-To-Headless-CMS.paper?dl=0&rlkey=svzbdkj22znwssparp90u7qsn). I look forward to your feedback.

**Comment by ShadaW11** [comment]
Hello @zanasruth No worries, thank you. I will review the article and get back to you asap.

**Comment by zanasruth** [comment]
Alright. I look forward to your feedback.

**Comment by oyedeletemitope** [comment]
Is this still open

**Comment by ShadaW11** [comment]
Hello @oyedeletemitope unfortunately not, the article has been written and is pending review.

**Comment by ShadaW11** [comment]
@zanasruth hello, i have added some comments. Please take a look once possible.

**Comment by zanasruth** [comment]
Alright @ShadaW11. I will check them out

**Comment by zanasruth** [comment]
Hi @ShadaW11. I've made edits to the draft based on your comments. Sorry for the delay

**Comment by ShadaW11** [comment]
@zanasruth sure will take a look

**Comment by zanasruth** [comment]
Hi @ShadaW11. Is there any progress with the article? Please let me know. Thank you.

**Comment by ShadaW11** [comment]
@zanasruth thank you for working on the article. The edits look great. The article will be posted soon.

**Comment by zanasruth** [comment]
I'm happy to hear that @ShadaW11. Thank you

**Comment by ShadaW11** [comment]
hello @zanasruth your article has been published, feel free to issue and send us an invoice. Please check the FAQ section in the link here for guidelines. https://strapi.io/write-for-the-community

**Comment by zanasruth** [comment]
Alright. Thank you @ShadaW11
