### ISSUE TITLE
[Request New Content] How to Choose a Headless CMS

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#433]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by nefejames** [comment]
Hi @ShadaW11 I would love to take this topic

**Comment by ShadaW11** [comment]
Hey @nefejames, great, could you please share a detailed outline of the article?

**Comment by nefejames** [comment]
Yes, I will send in an outline soon.

**Comment by nefejames** [comment]
Hi @ShadaW11. Here's the outline I've prepared:

# Article Outline
### What is a Headless CMS
### Benefits of using a Headless CMS
### Things to Consider when Choosing a Headless CMS

- **General Considerations**
  * Ease of use
  * Storage
  * Security
  * CDN
  * Templates and Starter themes 
  
-  **Content Team Considerations**
   * Media asset management system
   * Intuitive User Interface
   * Internalization and Localization support

- **Technical Considerations**
  * Documentation
  * What kind of APIs are available?
  * Extensibility and Plugins
  * Image Optimization
  * Is Authentication available
  * Popularity and Tech Ecosystem support
  * Is it Open Source?
  * What SDKs are available?

- **Business Considerations**
  * Customer Support and Training
  * Pricing and budget
  * Ecommerce support
  * Product maturity
  * Scalability

**Comment by nefejames** [comment]
Hi @ShadaW11. Have you had any chance to review the outline I sent you? I'm still waiting on feedback so I can proceed. Let me know

**Comment by ShadaW11** [comment]
Hey @nefejames I think it would also be interesting to have a section that answers this question: "do you need a Headless CMS" before the considerations. I also think Content consideration is a very important aspect. Could you add few other things to expand more on that? Let me know what you think.

**Comment by nefejames** [comment]
Hi @ShadaW11. Your suggestions make sense. I'll add them to the outline. However, I need some clarification on "content considerations". Can you shed more light on that? Thank you

**Comment by nefejames** [comment]
Hi @ShadaW11 I'm still waiting for some clarification on you regarding "content considerations" so I can proceed with the article

**Comment by ShadaW11** [comment]
Hello @nefejames Apologies for the delay. I meant expanding more on "Content Team Considerations" such as editing experience, creating & reusing content, content delivery...I hope its clearer now. Happy to answer any further questions and looking forward to getting your feedback.

**Comment by nefejames** [comment]
Yes, it's clearer now. I've filled the author form. I will have a draft ready soon. Cheers

**Comment by ShadaW11** [comment]
Awesome @nefejames looking forward to reading the article.

**Comment by ShadaW11** [comment]
Hello @nefejames  any update on the article?

**Comment by nefejames** [comment]
Hi @ShadaW11. I'll have a draft ready for review by Friday.

**Comment by nefejames** [comment]
Hi @ShadaW11. I'm about to wrap up on the draft, but I have some questions.

Where do I place the image and the SEO metadata for the article? In the Dropbox document? An example document of how it will look would be helpful for first time Strapi writers.

**Comment by ShadaW11** [comment]
Hello @nefejames awesome news, [here is an example.](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x) Im here if you have any other questions

**Comment by nefejames** [comment]
Hi @ShadaW11. I have a draft ready for review.

**Comment by ShadaW11** [comment]
Hello @nefejames your article will be reviewed this week. thank you. I will get back to you as soon as possible.

**Comment by nefejames** [comment]
Alright. I look forward to your feedback @ShadaW11.

**Comment by ShadaW11** [comment]
Hello @nefejames apologies for the delay. I will get back to you soon.

**Comment by nefejames** [comment]
I'm glad to hear that @ShadaW11. Cheers!

**Comment by nefejames** [comment]
Hi @ShadaW11. Any updates on the article?

**Comment by ShadaW11** [comment]
Hello @nefejames apologies for the delay its still in progress. I will keep you updated as soon as possible.

**Comment by nefejames** [comment]
Alright @ShadaW11. Thank you

**Comment by ShadaW11** [comment]
Your article has been published. @nefejames thank you and looking forward to your next one. Please check the FAQ in the write for the community to issue and submit an invoice.
