### ISSUE TITLE
[Request New Content] How to build a voice application with Strapi

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#434]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by vickywane** [comment]
Hi @ShadaW11  👋🏾

This seems to be an interesting tutorial to build.

I can think of building a React native voice recorder application whose data is powered by Strapi. 
More like a simplified version of Clubhouse. 

Does this make any sense and would you like me to create an article outline on this?

**Comment by ShadaW11** [comment]
Hey @vickywane Yes, is there a chance to use Next.js in the application? if yes, would you be able to create an outline for this topic?

**Comment by vickywane** [comment]
@ShadaW11 Is there a hard requirement on using *Next.js*?

If not, i would prefer to use React Native and build it as a mobile application. 

1. There are quite a little tutorials on mobile applications using Strapi, and there are alot on Next.js

2. Also, i would also like to use the native audio recording APIs available in React Native applications.

Cc: @Mcastres @malgamves

**Comment by ShadaW11** [comment]
Hey @vickywane 

Thank you for the clarification. Makes sense. There is no hard requirement on using Next.js for this specific tutorial but rather a general requirement to produce more nextjs content. However, please go ahead and send me an outline with react and we can move forward from there.

**Comment by ShadaW11** [comment]
Heyyy @vickywane awesome outline. Looking forward to receiving the article. Please let me know if you need any help

**Comment by vickywane** [comment]
Thanks @ShadaW11 .

I would begin working on this and have it ready within the next two weeks. 

I am existing community author with Strapi. I wrote [this](https://strapi.io/blog/building-applications-for-an-international-audience-using-strapi-i18n-plugin) article that was recently published. I also filled the form when the article was published. 

Do i need to refill the form?

**Comment by ShadaW11** [comment]
Hey @vickywane Thanks for getting back to me. No need to resubmit the form, just make sure the article follows the guidelines mentioned in the FAQ. Im here to help if you have any questions. Looking forward to receiving the article.

**Comment by ShadaW11** [comment]
Hey @vickywane any update on the article?

**Comment by vickywane** [comment]
@ShadaW11 i will submit this before Friday

**Comment by vickywane** [comment]
Hello @ShadaW11 . 

The draft for this is ready for review in this [dropbox paper document](https://www.dropbox.com/scl/fi/ba7b11fasdb7zi6cudl45/Managing-data-your-voice-application-using-Strapi.paper?dl=0&rlkey=sruzo742985qtkmdl40lvs90j).

**Comment by ShadaW11** [comment]
Hey @vickywane awesome, thanks. Will take a look and get back to you as soon as possible.

**Comment by ShadaW11** [comment]
@vickywane your article is published https://strapi.io/blog/building-a-voice-recording-application-with-strapi  🎉🎉
Please register in the strapi forum to get automated notifications when someone comments on your blog post. Also please check our FAQ to submit an invoice. And a big thank youuuu.

**Comment by vickywane** [comment]
🔥
‘
