### ISSUE TITLE
[SUBMIT]  how to create an api with strapi by rebuilding the mdn expressJs local library website

### ISSUE THREAD

**Issue by okuninoshi** [strapi/community-content#438]
**My resource**
Hello 👋 

this article shows how fast and easy to create api with strapi by rebuilding the mdn expressJs local library website    

Introduction
Prerequisitess
what you'll learn
what you need to know
Setting up a Strapi project
Setting up NextJS project
Integrating Strapi API with NextJS
deploying to production
Conclusion

**My content is**

- [x] A Strapi Tutorial

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you .

**Comment by okuninoshi** [comment]
hello @ShadaW11 , i have no Permission to push the tutorial code !

**Comment by Mcastres** [comment]
Hello @okuninoshi, what is the `mdn expressJs local library website` exactly?
Also, you can create a Pull Request if you want to add your code to the repository.

I will take care of reviewing it

**Comment by okuninoshi** [comment]
@Mcastres when i was learning express i took the mozilla developer network tutorial on expressJs, so i thought it will be great to rebuild the site with Strapi and nextJS to show how easy to build an API with modern tools like Strapi.

**Comment by Mcastres** [comment]
I see! You are referring to [this project](https://github.com/mdn/express-locallibrary-tutorial).
Then yes, it can be a good idea however the frontend of the website is very poor.

Are you planning on improving it using Next.js? Adding beautiful assets?

**Comment by okuninoshi** [comment]
yeah, i'm using geist-ui library by vercel, i didn't focus too much on the ui but i can improve it :)  you can see it
[here](https://next-local-library.vercel.app/catalog)

**Comment by Mcastres** [comment]
I see, the style is very minimalistic 😃 
I think it's fine since the purpose of this tutorial is to demonstrate the API part of Strapi 👍

**Comment by ShadaW11** [comment]
Thank you @Mcastres for the feedback. Hey @okuninoshi great, please go ahead and start writing the article. Before, you do that, Please register your author details by filling the form [here](https://strapi.io/write-for-the-community#contact), scroll up and read the FAQ (how to submit, how to get paid...) then go over the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md) here and start writing your article.

**Comment by okuninoshi** [comment]
hello @ShadaW11 I wrote the article you can check it [here](https://www.notion.so/how-to-create-an-api-with-strapi-by-rebuilding-the-mdn-expressJs-local-library-website-f79003989d4748cfb46c6c39c98dead9), I read the guidelines and how to submit the article before I opened the issue. if anything is missing or wrong please add a comment

**Comment by ShadaW11** [comment]
Hello @okuninoshi thank you for writing the article. Can you please paste the content on drops and share the link with me. (This was mentioned in our [FAQ](https://strapi.io/write-for-the-community)) because we will review and comments and that's easier to manage in dropbox. I also would like to check that your article is not public or published on any other platform? The article should be posted first on our blog. Looking forward to reviewing your article on dropbox. please share with me the link here once possible. Thank you again and looking forward to publishing it.

**Comment by ShadaW11** [comment]
@okuninoshi Im here if you have any questions

**Comment by ShadaW11** [comment]
Hey @okuninoshi I hope you are doing well. Could you please fill the form [here](https://strapi.io/write-for-the-community#contact) to collect your author details,  and share with me the dropbox link of the article as soon as possible so we can take a look and leave feedback please

**Comment by okuninoshi** [comment]
hello @ShadaW11, I'm fine thank you. [this](https://www.dropbox.com/sh/59vycisos1cxssw/AACfc8k3sCDxQq1F-b0IBjSYa?dl=0) is the link to the article.

**Comment by ShadaW11** [comment]
Hey @okuninoshi Thank you. Im so sorry to ask you to do this again 😕. Is there a chance you can please add the article in dropbox in a format similar to this [article](https://www.dropbox.com/scl/fi/xb7lfkvqdfakni6hm9265/Build-a-Crypto-Alert-App-with-Strapi-and-Next.js.paper?dl=0&rlkey=rv1vixd6461sjsljljdu4p0xx)? Unfortunately I cannot leave feedback on the current link you shared with me 🙏

**Comment by ShadaW11** [comment]
https://www.dropbox.com/scl/fi/4knhvpkpukyu9zm0blzzl/how-to-create-an-API-with-strapi-by-rebuilding-the-mdn-express.js-local-library-website..paper?dl=0&rlkey=mjc8z78u2x8d4rsi2t5a5as2z

**Comment by ShadaW11** [comment]
Hello @okuninoshi your article has been reviewed and will be published this week. I will get back to you once its live and the next steps.

**Comment by okuninoshi** [comment]
thank you @ShadaW11.

**Comment by ShadaW11** [comment]
Hello @okuninoshi your article is now published 🎉🎉🎉, https://strapi.io/blog/how-to-create-an-api-with-strapi-by-rebuilding-the-mdn-express-js-local-library-website please check our FAQ to learn how you can issue and submit your invoice. 

Also make sure you click on discussion under your blog post, register https://forum.strapi.io/ and click on "watching" to receive automatically a notification once a new comment is made. We rely on you to supoort the community. Thank you

**Comment by okuninoshi** [comment]
thank you @ShadaW11 I'm honoured.

**Comment by ShadaW11** [comment]
We hope you will write soon for us new articles. Thank you
