### ISSUE TITLE
[SUBMIT] Set default file upload provider

### ISSUE THREAD

**Issue by kwinyyyc** [strapi/community-content#44]
**My resource**

The way to change default file upload provider to Cloudinary.
Comments are welcome! Thanks!
https://medium.com/@kwinten.yc.li/strapi-set-default-file-upload-provider-to-s3-cloudinary-rackspace-5b8ef6f61daa

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Thanks for this article @kwinyyyc !
