### ISSUE TITLE
Build an E-commerce shopping cart with Svelte, Tailwind CSS and Strapi

### ISSUE THREAD

**Issue by ejirocodes** [strapi/community-content#443]
**My resource**
[Svelte](https://svelte.dev/) is a component framework that runs at build time, converting your components into highly efficient imperative code that surgically updates the DOM. Svelte approach to building web apps is unique and I will like to teach the Strapi community how they can build a to-do app with Svelte using Strapi as the CMS and Tailwind for styling.

**Outline:**

- Introduction
- Goals
- Prerequisites
- Creating a Strapi Project
- Creating Content Types
- Setting up Roles and Permissions
- Bootstrap a Svelte Project
- Adding TailwindCSS to our project
- Building the frontend (Shopping Card, Card component, Product Details, Checkout page)
- Fetching Products from our Strapi Backend
- Adding items to Cart
- Update shopping Cart
- Delete Items from Cart
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think? @malgamves, @ShadaW11  **
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hey @ejirocodes I really like this topic and outline, when would you be able to work on this article?

**Comment by ejirocodes** [comment]
I hope to finish it before the week runs out

**Comment by ShadaW11** [comment]
Hello @ejirocodes As I mentioned before, I really like the outline and topic and for now, we will be pausing this article and I should have more visibility in the next couple weeks.

**Comment by ejirocodes** [comment]
Thanks for the update, @ShadaW11

**Comment by ejirocodes** [comment]
Hi @ShadaW11, I noticed you closed this. Can I get more insight as to what should be changed in the outline. Thanks

**Comment by ShadaW11** [comment]
Hello @ejirocodes I closed it as another writer has submitted an article with a similar content.

**Comment by ejirocodes** [comment]
Alright. Thanks for the update
