### ISSUE TITLE
[SUBMIT] Understanding and using Relations in Strapi

### ISSUE THREAD

**Issue by philipszdavido** [strapi/community-content#447]
This article will show how to use relations in collections in Strapi. I will build a real-life app to also demonstrate the process.

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hey @philipszdavido can you please share with me an outline of what you have in mind?

**Comment by philipszdavido** [comment]
Hello @ShadaW11 , see the outline of the post below:

**Outline**

**Understanding and using Relations in Strapi**
- What is Strapi?
- Relations in Database fields
- Setting up Strapi project
- One-to-one
- One-to-Many
- Many-to-Many
- Test app
- Conclusion

**Comment by ShadaW11** [comment]
Hello @philipszdavido thank you for sending the outline. As mentioned in the email and on discord, we have paused the tutorials for now until the release of the V4. I will get back to you in the next couple weeks with some updates.

**Comment by philipszdavido** [comment]
OK

**Comment by ShadaW11** [comment]
Hello @philippkhon we have resumed tutorials for the writers who commit to updating their articles after the v4 release without extra compensation. If this is something you can commit on doing. We can discuss the submitted outline.

**Comment by philipszdavido** [comment]
@ShadaW11 OK, but I will be paid for this article?

**Comment by ShadaW11** [comment]
@philipszdavido Yes of course, but when you update it after the V4, you will not be paid.

**Comment by ShadaW11** [comment]
@philippkhon Please take a look at our blog and documentation, I saw some similar content. could you also expand more on the real life app that you will demonstrate?

**Comment by philipszdavido** [comment]
The real-life app will be a Q/A app just like Quora. In that way, we can cover all the relations in Strapi. Yeah, there are similar contents in the Strapi docs and blog but they are not close enough to this😁.

Also, I have submitted many article proposals, but I saw you commented that I focus on this, yes that's good. Can we start the monthly posts we did before the pause for the v4?

**Comment by ShadaW11** [comment]
@philippkhon sounds good, I like the app idea. Please go ahead and work on it. Unfortuantely we are working on article by article basis. I will keep you updated. but please go ahead and start working on this.

**Comment by philipszdavido** [comment]
OK, thanks. I'll start.

P.S I think you are not tagging me. Mine is @philipszdavido 😁

**Comment by ShadaW11** [comment]
@philipszdavido you are right. fixed and thanks.

**Comment by ShadaW11** [comment]
Hello @philipszdavido is the article ready?

**Comment by philipszdavido** [comment]
@ShadaW11 Almost, I will submit it today. Thanks so much.

**Comment by philipszdavido** [comment]
Hello @ShadaW11 The article is ready, see the link https://www.dropbox.com/scl/fi/di2rxq4davemkc693d4ly/Understanding-and-using-Relations-in-Strapi.paper?dl=0&rlkey=hrzkn9ds2t5g82eb14r5u56er

Sorry for the delay.

**Comment by MattieBelt** [comment]
Hey @philipszdavido,

Awesome you spending some time on writing for the community! 
One thing I noticed that you didn't mention anything about one-way relations, how'd you fit this concept in the article? 👀

**Comment by philipszdavido** [comment]
@MattieBelt Thanks.

So I mentioned the ones here because they will fit into the Q/A app I will build in the article.

**Comment by MattieBelt** [comment]
@philipszdavido,

Okay but the article should be focused around,
> Understanding and using Relations

right? 

> So I mentioned the ones here because they will fit into the Q/A app I will build in the article.

Likewise you didn't use the many-to-many relations in the app 😉

**Comment by philipszdavido** [comment]
@MattieBelt 

Yes, the many-to-many didn't later in fit when I was building the app, so I just explained what it is. The Q/A app had only **one-to-one** and **one-to-many** relations.

**Comment by MattieBelt** [comment]
> Yes, the many-to-many didn't later in fit when I was building the app, so I just explained what it is. The Q/A app had only **one-to-one** and **one-to-many** relations.

Yes great, so don't you think you should also explain the one-way relations  and their usage?
I hope you understand my request. 🙃

**Comment by philipszdavido** [comment]
OK, so the one-way relations are: one-to-one, one-to-many, many-to-one, many-to-many right?

So I should explain them, right?

**Comment by MattieBelt** [comment]
[All possible relations in Strapi.](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#relations)

Handled in the Article:
- [ ] One-Way
- [ ] Many-One (one-way Many-to-One) 
- [x] One-to-One
- [x] One-to-Many / Many-to-One
- [x] Many-to-Many
- [ ] Polymorphic

**Comment by philipszdavido** [comment]
Good.

**Comment by MattieBelt** [comment]
> So I should explain them, right?

I guess so as the article is all about relations right, so at least explaining them is a good thing to do.

**Comment by philipszdavido** [comment]
@MattieBelt Thanks 😀 I will explain them very well with pictures too. 💯

**Comment by ShadaW11** [comment]
@MattieBelt thank you for the awesome review, Hey @philipszdavido could you please confirm whenever you are done with the updates? I believe Mattie is totally right. I think its pretty much the basics to explain that as its what the whole article is about. Looking forward to your the updated article.

**Comment by philipszdavido** [comment]
@ShadaW11 Yes, I will do it.💯

**Comment by philipszdavido** [comment]
Hi @ShadaW11 I have updated the article, take a look.

**Comment by ShadaW11** [comment]
@philipszdavido thanks, @MattieBelt I hope the update covers the points you mentioned above?

**Comment by philipszdavido** [comment]
@MattieBelt Thanks 💯💯

**Comment by ShadaW11** [comment]
@philipszdavido awesome thank you. Will review the article and get back to you

**Comment by ShadaW11** [comment]
Hello @philippkhon your article has been published, thank you.
