### ISSUE TITLE
[UPDATE] outdated props for react-markdown in tutorial

### ISSUE THREAD

**Issue by ruizhen88** [strapi/community-content#452]
Hi, I noticed an outdated version of `react-markdown` used in the tutorial [Build a blog with React, Strapi and Apollo](https://strapi.io/blog/build-a-blog-with-react-strapi-and-apollo).

`ReactMarkdown` component in `./containers/Article/index.js` should have props `children` instead of `source` to provide markdown to be rendered.

Here's their doc: https://github.com/remarkjs/react-markdown

A huge thanks to the team for the useful content. Cheers!

**Comment by ShadaW11** [comment]
Hey @ruizhen88 thank you soooo much. Would you be interested in updating the tutorial?
