### ISSUE TITLE
[SUBMIT] customization of Strapi backend (Routes, Services, Controllers, Queries)

### ISSUE THREAD

**Issue by oviecodes** [strapi/community-content#456]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by oviecodes** [comment]
I Would like to write an article that shows users how to customize the backend of their Strapi application.

Outline:

Introduction to Strapi
Getting started with Strapi
A basic overview of Strapi application
Introduction to Strapi services
customization of Strapi services
Introduction to Strapi controllers
Customization of Strapi controllers
Introduction to Strapi queries and their functions
Introduction to Strapi routes
Customization of Strapi routes
Conclusion

**Comment by oviecodes** [comment]
Hey @ShadaW11 , I would like to take this up.

**Comment by ShadaW11** [comment]
Hey @oviecodes  thank you for sending the outline. As mentioned in the email and on discord, we have paused the tutorials for now until the release of the V4. I will get back to you in the next couple weeks with some updates. I will keep the issue open but there is no need to work on it for now.

**Comment by oviecodes** [comment]
Hey @ShadaW11 what's the update on this article.
