### ISSUE TITLE
[SUBMIT] Using Strapi with React, Deno, and Deno Deploy

### ISSUE THREAD

**Issue by Symbitic** [strapi/community-content#464]
**Using Strapi with React, Deno, and Deno Deploy**

I know that submissions have been paused until the release of V4, but I thought I'd like to put this out there.

Deno is a new JavaScript runtime similar to Node.js, but it has several modern features, like support for ES Modules and TypeScript out-of-the-box. Deno Deploy is a new serverless platform built exclusively for Deno. In this case, we use it for server-side rendering of React components.

This tutorial walks you through creating a new Strapi API, a new server with Deno, and then deploying it with Deno Deploy.

Outline:
1. Introduction
2. Prerequisites
3. Setup
    1. Strapi Setup
    2. Deno Setup
    3. React Setup
    4. Deno Deploy Setup
4. Alternatives
5. Conclusion

Here is the complete example, in less than 100 lines of code:
```tsx
/// <reference path="https://raw.githubusercontent.com/denoland/deployctl/main/types/deploy.fetchevent.d.ts" />
/// <reference path="https://raw.githubusercontent.com/denoland/deployctl/main/types/deploy.window.d.ts" />

import * as React from "https://esm.sh/react@17.0.2";
import * as ReactDOMServer from "https://esm.sh/react-dom@17.0.2/server";

import { createElement as h } from "https://esm.sh/react@17.0.2";

// @ts-ignore Because VSCode occasionally complains that Deno is not defined.
const STRAPI_API_URL = Deno.env.get("STRAPI_API_URL") ||
  "http://localhost:1337";

interface Package {
  name: string;
  description: string;
  github: string;
  stars: number;
}

interface Props {
  data: Package[];
}

function App({ data }: Props) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
        <title>Hello from JSX</title>
      </head>
      <body>
        <div className="container">
          <h1>Hello, World!</h1>
          <table className="table">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Stars</th>
                <th scope="col">URL</th>
              </tr>
            </thead>
            <tbody>
              {data.map((pkg: Package) => (
                <tr>
                  <th scope="row">{pkg.name}</th>
                  <td>{pkg.description}</td>
                  <td>{pkg.stars}</td>
                  <td>
                    <a href={pkg.github}>{pkg.github}</a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </body>
    </html>
  );
}

async function getData(path: string) {
  const url = `${STRAPI_API_URL}${path}`;
  const response = await fetch(url, {
    headers: {
      "Content-Type": "application/json",
    },
  });
  return response.json();
}

addEventListener("fetch", async (event: FetchEvent) => {
  // Fetch data.
  const data = await getData("/packages");

  // Render React components to a string.
  const str = ReactDOMServer.renderToString(<App data={data} />);

  // Prepend the DOCTYPE for better compatibility.
  const body = `<!DOCTYPE html>${str}`;

  const response = new Response(body, {
    headers: { "content-type": "text/html; charset=utf-8" },
  });

  event.respondWith(response);
});
```

**Comment by ShadaW11** [comment]
Hey @Symbitic very interesting. I will try and check if we can find a slot for this in our august calendar before the V4. Would you be able to commit to updating the article after the V4 release?

**Comment by Symbitic** [comment]
@ShadaW11 absolutely. In fact, I already have most of it written, because I was recording things as I went along. The only Strapi-specific parts are running create-strapi-app with npx and adding test data with the web interface. Unless either of those will be going through significant changes for the V4 release, I could have it available within a few days. Otherwise, I will look forward to August.

**Comment by ShadaW11** [comment]
Hello @Symbitic Apologies for not getting back to you earlier. Unfortunately, I do not really know the impact of v4. What I would suggest is either have the article written and commit to updating it after the v4 release. Or we can wait for another couple weeks. Strapi has a write for community program to compensate writers for the time and effort. You can join by filling the form [here](https://strapi.io/write-for-the-community) Then take a look at our FAQ section to check the article guidelines. Unfortunately, updating the article after v4 will not be paid but we will definitely be paying once the article is ready. Please let me know if that works for you. Looking forward to hearing from you and publishing your first article.

**Comment by Symbitic** [comment]
@ShadaW11 no problem. I can wait another few weeks. I'll fill out the form and be ready to update everything as soon as v4 is released and then publish it. I need some time to learn how to write in Dropbox Paper anyway since that's what the rules require. So I'll probably wait until after v4 is released.

Thanks for your help.

**Comment by ShadaW11** [comment]
Hello @Symbitic Just saw your email. Awesome article. I added the URL [here](https://www.dropbox.com/scl/fi/56jbtt8hopf3wccglk8fx/Rendering-React-SSR-with-Deno-and-Deno-Deploy.papert?dl=0&rlkey=vdje76qh4uupcoyx8ycelc1mx) 
I will get back to you once your article is reviewed.

**Comment by Symbitic** [comment]
@ShadaW11 thank you!

**Comment by ShadaW11** [comment]
@Symbitic Your article will be published next week, please submit an invoice. (check the process in the FAQ section in the write for the community page) The article URL is not ready yet, therefore please use the title of the article.

**Comment by ShadaW11** [comment]
@Symbitic your article is published, please refer to the FAQ section to issue and submit an invoice. Thank you and looking forward to your next article.
