### ISSUE TITLE
[SUBMIT] Publish blog post on Dev.to, Hashnode and Medium at the same time from Strapi.

### ISSUE THREAD

**Issue by amirtds** [strapi/community-content#465]
**My resource**

Publish blog post on Dev.to, Hashnode and Medium at the same time from Strapi.

- Introduction
- Dev.to APIs
- Hashnode APIs
- Medium APIs
- Content Structure
- Publish workflow
- How to automate the deployment to multiple platforms
- Let's see how it works in real world
- Conclusion

**My content is**

Tutorial

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @amirtds awesome tutorial and outline, and would love to see this article. However, we will put it on hold until the release of the v4 as we expect some changes to affect this tutorial. I will reach out to you once it is possible to work on this article.

**Comment by amirtds** [comment]
Thanks @ShadaW11 sounds great. Looking forward to v4 🚀

**Comment by ShadaW11** [comment]
Hello @amirtds As mentioned earlier, we have reduced the number of articles as V4 will be released in the next few weeks. However, few tutorials that are being approved, are those written by authors that commit to updating their article after the V4 without additional compensation. We currently compensate all writers for their articles and we will continue to do so. But we are aware that updating the tutorial will require some time and efforts, therefore, we give you the freedom to either wait a month until the V4 release or go ahead and submit this article and update it after the release without additional compensation. If you would like to commit on updating the article, please get back to me and I would be able to look for a spot for this tutorial.

**Comment by amirtds** [comment]
Hi @ShadaW11 thanks for letting me know. No problem I can wait for a month for V4 to start working on this article.

**Comment by ShadaW11** [comment]
Hey @amirtds maybe you can work on this article?

**Comment by amirtds** [comment]
Hi @ShadaW11 Absolutely, I can start working on this article.

**Comment by amirtds** [comment]
Hi @ShadaW11 I prepared the draft [here](https://www.dropbox.com/scl/fi/rb1kv1nfsjczxug6rtl1s/Publish-blog-post-from-Strapi-to-Multiple-Platforms.paper?dl=0&rlkey=w43gexul78clozpvob9payo6k). I'm going to make some minor changes tomorrow, should be ready for your review.

**Comment by ShadaW11** [comment]
Hey @amirtds perfect. I will have someone from our team review the article.

**Comment by amirtds** [comment]
@ShadaW11 The doc should be ready for review. Seems no project assigned to this issue
![Screen Shot 2021-10-21 at 13 40 20](https://user-images.githubusercontent.com/5863396/138337503-f8e6a3c9-b7ea-4930-ac62-9d4b280c8131.png)
I can't see it in the project under `in progress` or `in review` feel free to assign the `Write for the Community Program` project to this issue. Thank you

**Comment by ShadaW11** [comment]
@amirtds thank you so much. Loved your article. Its published now and your payment will be issued.
