### ISSUE TITLE
How to add image from MediaLib at cursor position in Quill Editor

### ISSUE THREAD

**Issue by tufail** [strapi/community-content#468]
**How to add image from MediaLib at cursor position in Quill Editor**
 
Hello 👋 

I followed the article https://strapi.io/blog/how-to-change-the-default-wysiwy-to-quill-editor and I have added the Quill Editor in my strapi admin. But whenever I am selecting image it is appending at the end of the content but not at the position where my cursor is? Please let us guide how can we add image from media lib at the cursor position.
 

 
Thank you.

**Comment by ShadaW11** [comment]
Hello Tufail, thank you for writing us. Maybe @Mcastres can you help with this as he is the author of the article.

**Comment by Mcastres** [comment]
Hi @tufail, I will probably not have the time to check this before I go on vacation. I will give a look when I'll come back on mid august :)

**Comment by Mcastres** [comment]
Hello @tufail, sorry for not going over this sooner. As the v4 will arrive, we'll need to completely update the Quill editor tutorial and hopefully fix this behavior.

**Comment by dougsmith1000** [comment]
@Mcastres, hello! I've been working and found this limitation as well. I've been considering making a button inside of the editor so I have access to the quillRef and create a custom blot. However,it would require a bit of extra code and state lifting. The v3 Quill implementation is relatively simple, so I'd like to avoid the confusion of that if possible. If it's not, let me know and I can try to do an in-editor button.

**Comment by Mcastres** [comment]
I'm not sure to understand what you want me to do here @dougsmith1000 🤔

**Comment by dougsmith1000** [comment]
@Mcastres, just let me know if you know of a more streamlined way of doing it with native strapi methods. If not, I can make a custom blot that communicates with the medialib component. I can post up my work when I have it working.

**Comment by Mcastres** [comment]
For now, I don't have any idea :/
