### ISSUE TITLE
Building a PWA with Nuxt.js and strapi

### ISSUE THREAD

**Issue by olawanlejoel** [strapi/community-content#474]
## Hello 👋 

In this article, I will explain how to build a Progressive Web app with Nuxt.js and Strapi by building a Food catalog application which would receive her content from strapi and get displayed via nuxt.

## Outline

- Introduction
- Requirements/Prerequisites
- Understanding PWA
- What is Strapi?
    - Getting started with Strapi/setup
    - Creating collections and data fields
- What is Nuxt.js
    - Setting up a Nuxt.js app
    - Connecting strapi with Nuxt.js App
- Building a foods catalog app
    - Display all foods on the Homepage
    - Create dynamic routes for foods
    - Styling our app
- Conclusion
    - Useful resources

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hello @olawanlejoel We currently have our food advisor project that we work on internally, therefore, I would suggest creating an app with different functionality. I would also suggest using Nextjs if possible; Looking forward to hearing from you.

**Comment by olawanlejoel** [comment]
Hi @ShadaW11, so sorry for the late response and I’m so happy to get started here.

Talking about an app with a different functionality - I was thinking of a drug verification app where all approved drugs will be uploaded on strapi with their details and a unique code.

The app will check for the unique code, if it exists or not to know if a drug is approved or fake.

I have not used next.js before so It would be difficult for me. I’d prefer using Nuxt but if you insist on next.js I might have to learn first.

Thanks and I hope to hear from you soon.

- Joel

**Comment by ShadaW11** [comment]
Hello @olawanlejoel its okay to use Nuxt and important that you use a language you are comfortable with. I am still not sure about the tutorial. There are a lot of trending topics and I think we need an app that could be used by our community. Maybe you can take a look online for some inspiration. Also when publishing an outline, below is a sample (to include what each section will talk about including the features of the app);

Outline:

Introduction
Goals
Prerequisites
Creating a Strapi Project
Creating Content Types
Setting up Roles and Permissions
Bootstrap a Svelte Project
Adding TailwindCSS to our project
Building the frontend (Shopping Card, Card component, Product Details, Checkout page)
Fetching Products from our Strapi Backend
Adding items to Cart
Update shopping Cart
Delete Items from Cart
Conclusion

**Comment by ShadaW11** [comment]
Hello @olawanlejoel any update on the outline?

**Comment by olawanlejoel** [comment]
Yes. I will be sending in an outline tomorrow. I want to make it solid
enough to get through this stage. Thanks so much for the check up!

**Comment by olawanlejoel** [comment]
## Outline

- Introduction
- Requirements/Prerequisites
- Understanding PWA
- What is Strapi?
    - Getting started with Strapi/setup
    - Creating collections and data fields
    - Setting up roles and permission
- What is Nuxt.js
    - Setting up a Nuxt.js app
    - Connecting strapi with Nuxt.js App
- Building a Linktree app
    - Building the frontend (Add link page, home page, login and sign up page)
    - Creating and integrating authentication into application.
    - Storing data to strapi
    - Fetching data from strapi
    - Perfecting our app
- Conclusion
    - Useful resources

**Comment by ShadaW11** [comment]
Could you please clarify what the app will do? @olawanlejoel

**Comment by olawanlejoel** [comment]
This is an an app that will allow users to create an account to house links to all their profiles, publications, and lots more just like the regular linktree website but this time around we will be working with strapi.

**Comment by olawanlejoel** [comment]
Hi @ShadaW11. I don’t know if you got my reply please.

**Comment by ShadaW11** [comment]
Hello @olawanlejoel Outline looks good, could you please commit to updating your application after the V4 release? If yes, please go ahead and start working on the tutorial. Please let me know when you will be able to deliver?

**Comment by olawanlejoel** [comment]
Hi @ShadaW11 , I will deliver this article at the end of the month, this will give me time to build the app well and write a befitting article to explain all the process in plain words.

I’ll definitely update the article when a new release is out!

**Comment by ShadaW11** [comment]
@olawanlejoel great ill keep the issue open.

**Comment by olawanlejoel** [comment]
@ShadaW11 , the reason I closed it was my pitch was not really clear and I would prefer I work on another tutorial so it can be streamlined towards PWA as the topic says. I would prefer to pitch something different and keep pwa in mind.

something like building a photo gallery then making the app a progressive web app
