### ISSUE TITLE
[SUBMIT] Building an Unsplash clone using Next JS and Strapi

### ISSUE THREAD

**Issue by suhailkakar** [strapi/community-content#475]
**My content is**

I would like to write an article where we will create an Unsplash Clone using Next JS, Tailwind, and Strapi and some of the headings are 

- Outline
- Introduction
- What is Next JS
- What is Tailwind CSS
- Initializing the application
- Adding Authentication 
- Creating Profile for users
- Creating the Homepage
- Uploading Images to Strapi
- Getting the link of Images from Strapi

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hello @suhailkakar thank you for submitting the outline, I like the outline, I would suggest adding additional feature to it? Note that we have reduced the number of articles as V4 will be released in the next few weeks. Therefore, current tutorials that are being approved, are those written by authors that commit to updating their article after the V4 without additional compensation. We currently compensate all writers for their articles and we will continue to do so. But we are aware that updating the tutorial will require some time and efforts, therefore, we give you the freedom to either wait a month until the V4 release or go ahead and submit this article and update it after the release. 
If you decide to go ahead and write the article, please register as an author by filling the form [here](https://strapi.io/write-for-the-community) Then go over the FAQ section in details. I will confirm your outline after the edits and you would be able to go ahead and start. Looking forward to hearing from you.

**Comment by suhailkakar** [comment]
Hi @ShadaW11 , Thanks for your reply, 

Sure, I will add many feature to it also I am planning to publish after release of V4

**Comment by ShadaW11** [comment]
Hello @suhailkakar great, happy to hear that. Keep me updated on the progress. thank you.

**Comment by ShadaW11** [comment]
Hey @suhailkakar no worries at all. Looking forward to receiving it. Feel free to ping me whenever its ready.

**Comment by suhailkakar** [comment]
Hi @ShadaW11 , I would like to change my article title/topic. 

Is it fine?

Thanks

**Comment by suhailkakar** [comment]
@ShadaW11 Ya sure, just give me some time, I am going to prepare the outline and let you know

**Comment by suhailkakar** [comment]
Okay sure
Thanks!

**Comment by jerimkaura** [comment]
I think I can write about this article.

**Comment by ShadaW11** [comment]
hello @jerimkaura please submit an outline of what you plan on writing

**Comment by jerimkaura** [comment]
### Article outline

### Introduction

#### Getting to know Strapi.
Introduces the reader to the Strapi CMS and highlights a few areas of applications, software built-in Strapi and benefits of using Strapi CMS

#### The Next.js framework
The reader also gets to know what Next.js is and the benefits that make it preferable in the areas of application.

### Project Goal
The goal is to create a website like Unsplash using STrapi CMS and Nextjs framework.

### Prerequisites
- Code editor
- NodeJs

### Project setup

- Basic installation of project dependencies including Strapi and Nextjs.

### Setting up Strapi
The strapi will form the backend CMS from managing the content that appears on the frontend. Here is where the reader will learn how to create a superuser and the required collections.

### Setting up NextJs
NextJs will be used as the frontend framework that handles how images are displayed on the website. This section will discuss how to set up Next.js to consume the API from Stapi.

### React Dropzone for image upload
This section will discuss react dropzone and how to use it to upload images to the Strapi backend.

### Creating the image listing page
Here, we will walk the reader through building a page that lists images uploaded by various users to the Strapi backend.

### Users and permissions
This section discusses how users profiles are created and different users are given different permissions(user groups). It also contains the authentication module for users.

### Testing the application
The section will provide screenshots of the application tested for functionality against the project goals

### Conclusion
Will provide a summary of everything discussed in the article. It gives a reader a chance to reflect and internalize what the article talks about in-depth.

**Comment by ShadaW11** [comment]
hello @jerimkaura I would suggest building on the initial outline submitted and taking into consideration my feedback above. Could you please do so and then edit your outline accordingly?

**Comment by jerimkaura** [comment]
> Introduces the reader to the Strapi CMS and highlights a few areas of applications, software built-in Strapi and benefits of using Strapi CMS

Sure I am on it.

**Comment by ShadaW11** [comment]
@jerimkaura Could you please register your author details by filling the form here https://strapi.io/write-for-the-community 
Then go over the guidelines and the FAQ section before you start working on your article.
If you have any questions, please reach out to me.

**Comment by PaulBratslavsky** [comment]
I am going to close this due to inactivity and the fact that we already have similar content published on our blog and youtube channel.
