### ISSUE TITLE
Auth0 + Strapi

### ISSUE THREAD

**Issue by yestellar** [strapi/community-content#478]
Hello. This tutorial covers Auth0 provider connection process. 

Link: https://youtu.be/8-AweO-cshw
Language: Russian

Regards

**Comment by ShadaW11** [comment]
Hello @yestellar thank you for submitting the video, looks great. @Mcastres could we add this video under tutorials?

**Comment by Mcastres** [comment]
Sure, I'll do it! Thanks @yestellar :)

**Comment by yestellar** [comment]
Thank you!

**Comment by Mcastres** [comment]
Done :)
