### ISSUE TITLE
[REQUEST] Strapi with Laravel Tutorial

### ISSUE THREAD

**Issue by mostofa62** [strapi/community-content#489]
Hello Team, 
I am looking for a 
Strapi with laravel example

**Comment by ShadaW11** [comment]
Hello @mostofa62 good point, I look forward to seeing an article published around this topic.

**Comment by bigpreshy** [comment]
I'd like to work on this

**Comment by ShadaW11** [comment]
@bigpreshy great, could you please submit an outline?

**Comment by bigpreshy** [comment]
- Introduction
- Setting up a Strapi Project 
- Setting up a Laravel Project 
- Consuming  Strapi  Data in a Laravel Project
> Doing CRUD(Create Read Update Delete) operations 
- Conclusion

**Comment by ShadaW11** [comment]
@bigpreshy As mentioned on Discord, please add a section to compare strapi and larvel as well. Looking forward to reading this article.

**Comment by ShadaW11** [comment]
Hello @bigpreshy your article has been published. Please review the FAQ to issue and send an invoice. Looking forward to more articles.
