### ISSUE TITLE
[TOPIC] How to create corporate websites using strapi

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#49]
**My Request**
How to create a corporate website using Strapi

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by bigpreshy** [comment]
I can take this up

**Comment by Mcastres** [comment]
Awesome! I'll assign you the issue :)

**Comment by Mcastres** [comment]
Hello @bigpreshy how are you doing?
Have you had a chance to work on this content recently?

**Comment by malgamves** [comment]
Hey @bigpreshy just checking to see if there's any progress here. Will wait a few days before marking this as "Looking for Author".

**Comment by oviecodes** [comment]
Hey @malgamves and @Mcastres , I could take this up if @bigpreshy is not.

**Comment by malgamves** [comment]
Hey @oviecodes - I just assigned #22 to you. Happy to assign this to you after you're done with that. We'll leave it open for now.

**Comment by icebert04** [comment]
Hello @Mcastres and @malgamves,

I am thinking if you guys can give me a Go-ahead on writing this particular topic (link below)...

https://github.com/strapi/community-content/projects/1#card-36860857

My plan is to build a static site generation using Next.js and Tailwindcss.

Let me know what you think.

**Comment by malgamves** [comment]
Let's go with it @icebert04 - is it possible to add page generation from strapi in your tutorial? I'd like the app you build to make new pages in the frontend when we add content to pages in Strapi. What do you think about that?

**Comment by icebert04** [comment]
Hi @malgamves, 

I've been working on a Startup recently and probably won't have the time to contribute to writing articles for Strapi at this moment.

Please give my assignment to someone else.

Thanks for your trust and more power to Strapi for the year 2021.

Best,

Francis

**Comment by oviecodes** [comment]
Hey @malgamves , I'd like to take this up immediately after the social auth tutorial is done.

**Comment by malgamves** [comment]
Hey @oviecodes We'll keep this open for now just in case someone else wants to have a go at it. Happy to hand it to you then no one takes it up.

**Comment by alloyking1** [comment]
I can write on this if no one else is working on it. @malgamves

**Comment by malgamves** [comment]
Hey @alloyking1 - you're currently working on a few. If no one get this is a few weeks we can assign it to you :D

**Comment by alloyking1** [comment]
Okay. I'll hold on till then. Thanks

**Comment by hannydevelop** [comment]
Hello @malgamves is this still open? I'll love to work on it if it's still open. I finished #163 few days ago.

**Comment by malgamves** [comment]
Hey @hannydevelop - we're closing this in favor of the full stack apps we're looking for at the moment.

**Comment by vcoisne** [comment]
@malgamves does it make sense to keep this open ?

**Comment by malgamves** [comment]
nope closing it!

**Comment by muyiwexy** [comment]
@malgamves Hello there, what exactly is the task about. Is it we have to create a website with Javascript and connect it to strapi to deliver the contents of the website? a template will be appreciated

**Comment by malgamves** [comment]
hey @muyiwexy we have templates available for those [here](https://github.com/strapi/starters-and-templates)
