### ISSUE TITLE
[SUBMIT] Deploying Strapi API to App Engine using Cloud SQL on Google Cloud Platform

### ISSUE THREAD

**Issue by vickywane** [strapi/community-content#490]
Hello 👋 

I noticed there is a shortage of content being created here that focuses on Deployments.
Hence, i will like to create an article that that compliments the deployment section within the documentation and focuses on deploying a strapi Application to the Google Cloud Platform, using the [App Engine](https://cloud.google.com/appengine) for running the Node.js app and the [Cloud SQL](https://cloud.google.com/sql) for creating a Postgres Database.

## Outline

- Quick Introduction of Strapi
- Prerequisites  
- App Engine and Cloud SQL 
- An explanation of what the App Engine and Cloud SQL services are
benefits
- An estimated cost of running this application for a month using the pricing calculator

### Demo Strapi API
- Cloning a template application and testing it locally from console using cURL.

### Database
- Provisioning A Cloud SQL instance with the Postgres Database option
- Connecting to Postgres Database using [Cloud SQL Auth Proxy](https://cloud.google.com/sql/docs/mysql/sql-proxy) 

### Deploying API to App Engine
- Writing configuration file for app engine deployment 
- Deploying application to App Engine
- Testing deployed application through Endpoint URL
 
### Conclusion

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Cc @ShadaW11 
Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @vickywane outline looks good but are you sure a similar content is not already published on our blog or documentation? Can you please take a look and confirm? If you find similar points, you can replace few of them in your outline with something else. Im definitely looking for a deployment article. I would also want to confirm that you are willing to update your article after the V4 without additional cost? Can you please confirm this. Best

**Comment by MattieBelt** [comment]
> are you sure a similar content is not already published on our blog or documentation

Hey @ShadaW11 and @vickywane,
I wanted to note here that there already is a detailed deployment guide on how to deploy your strapi instance on GCP with App Engine and Cloud SQL:
https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html

**Comment by vickywane** [comment]
Hello @MattieBelt @ShadaW11 

Going through the documentation, I can see there is a guide for using the App Engine and Cloud SQL on Google Cloud. 
However, there is no guide for using the[ App Service](https://azure.microsoft.com/en-us/services/app-service/) on Azure ( what's available is using an Azure VM instance) 

I will switch the initial outline to using the App Service on Azure for running the API, and Azure PostgresSQL for the Postgres Database. 

Yes, @ShadaW11 when informed, I will be willing to update this tutorial to use the new V4 at no cost.

**Comment by ShadaW11** [comment]
Hello @MattieBelt thank you so much for your help 🙏 @vickywane could you please double check and submit an updated outline to verify the content is unique before you start working on it.

**Comment by ShadaW11** [comment]
Hello @vickywane Apologies for the delay. Thank you for sending over the edited outline. Unfortunately, we believe that a big portion of the content is already existing, in addition to the V4 release date that is very near and hence making this content outdated. I would suggest you work on another topic. Looking forward to receiving awesome article from you.
