### ISSUE TITLE
Connect Strapi to Shopify to import data from Shopify

### ISSUE THREAD

**Issue by akashkashhyap** [strapi/community-content#496]
Hello Community, 

Can someone please make a tutorial on how to connect and sync Strapi and Shopify; to import data from Shopify store and manage all contents from Strapi? I have found a tutorial on Strapi doc but the process manually created a product on Strapi and added product id from Shopify store. The idea is  to manage all content types from Strapi and Shopify will only manage cart and shipping. It might involve all the lifecycle hooks like update, delete and create. As of now we are planning to use Nuxtjs to manage the frontend.

Thank you.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ShadaW11** [comment]
Hello @akashkashhyap We just [published a post on our blog](https://strapi.io/blog/integrate-shopify-into-your-strapi-website), I hope it is helpful.

**Comment by akashkashhyap** [comment]
Thank you for responding to my request.

**Comment by akashkashhyap** [comment]
It is more or less same as what was explained in the video. The developer suggests to copy product id from Shopify and add it to the ShopifyID field created on Strapi. There are multiple products for any ecommerce store. Would it means that we have to manually add ids to Strapi from Shopify?

**Comment by ShadaW11** [comment]
Would you mind if you add your comment on the [GitHub issue here](https://github.com/strapi/community-content/issues/431)? I would like the author to update his tutorial to include your request. It would be great if you could explain that to him, I think its a great add to the article.

**Comment by akashkashhyap** [comment]
No.
Thanks for link again
