### ISSUE TITLE
Understanding JavaScript normal function and arrow function

### ISSUE THREAD

**Issue by Frank-dev20** [strapi/community-content#505]
**My resource**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Title**
#Understanding JavaScript normal function and arrow function
 
**Outline** 
JavaScript is the modern programming language of the web and since its development, it has gained wide acceptance by more developers. What makes JavaScript even more powerful is its usage as a server-side language (Node js). JavaScript is a functional programming language and also an Object-Oriented Programming Language. In this tutorial, we will explore the functional aspect of JavaScript. We'll talk about normal function declaration, expression, and arrow function. Their advantages and disadvantages, how to use them, and when to use them.

-[] Introduction
-[] Prerequisite
-[] Objective
-[] What is a function?
-[] Examples of normal function
-[] What is an arrow function
-[] Example of arrow function
-[] What is the difference between normal function and arrow function
-[] Which one should I use normal function or arrow function
-[] Conclusion

**Comment by ShadaW11** [comment]
Hello @Frank-dev20 thank you for submitting the outline. Its interesting, however, it would be more useful to have it connected to Strapi. Is there a chance you can submit something else or edit the current outline?

**Comment by Frank-dev20** [comment]
> Hello @Frank-dev20 thank you for submitting the outline. Its interesting, however, it would be more useful to have it connected to Strapi. Is there a chance you can submit something else or edit the current outline?

Oh, I see. I have to write in connection with Strapi.

**Comment by ShadaW11** [comment]
Hello @Frank-dev20 awesome feel free to modify or suggest a new topic.
