### ISSUE TITLE
[Request New Content] Creating a blog / e-commerce with Astro

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#506]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by octalpixel** [comment]
hey @ShadaW11 I would like to take this topic. I will send in an outline shortly

**Comment by ShadaW11** [comment]
hello @octalpixel looking forward to it

**Comment by octalpixel** [comment]
**My resource**
Hello 👋 
In this article, I will explain how to build a  personal blog using Astro. The application will use a mixture of React as the Astro Renderers for creating components and Tailwind for styling them. Strapi will have the functionality of CMS for the authors and function as a headless CMS for the frontend.

**Title**: Build a blog using Astro, React and Strapi

**Outline**
- Introduction
- What is Astro and Why use
- What is Strapi
- Project Setup
     - Installing the right Node version
     - Installing Strapi and Astro
- Review Strapi Concepts
- Setup Strapi
   - Creating collections and data fields in Strapi 
   - Testing API endpoints
- Review Astro Contents
- Setup Astro
   - Installing VS Code extension for Astro
   - Installing React as Astro renderer
- Building blog application
   - Display all blogs on the home page
   - Display a single blog post
   -  A local search
- Deployment
   - Deploy backend to Heroku
   - Deploy frontend to Netlify
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hello @octalpixel thank you for submitting the outline, it looks awesome. Could you please go over the guidelines mentioned within our FAQ section [here](https://strapi.io/write-for-the-community).
If you havent, please register your author details in the page above by filling the form. 
Kindly confirm that all the above are clear for you. Note that you will be compensated for your article as mentioned within our FAQ.
However, we expect that some aspects of the tutorial might become outdated after the V3 release, could you please confirm that you are committed to updating the tutorial after the V4 (screenshots, code...) without additional compensation?
Looking forward to hearing from you.

**Comment by octalpixel** [comment]
@ShadaW11  I have registered and also have read through the FAQ. Thanks for pointing me to them.

Also, I confirm that I will update any screenshot/code necessary when v4 is released.

**Comment by ShadaW11** [comment]
@octalpixel awesome please go ahead and get started working on it. im here if you have questions.

**Comment by ShadaW11** [comment]
Any update? @octalpixel

**Comment by octalpixel** [comment]
> Any update? @octalpixel

Hey @ShadaW11  , yep will give you and update end of the week.

**Comment by octalpixel** [comment]
Hey @ShadaW11  thanks for your patience. Here is the link the draft of the article https://www.dropbox.com/scl/fi/tdk71y5yznz9t9eqm4zo3/Astro-Strapi.paper?dl=0&rlkey=y5qs7197zqkcdwqpzggl7n148

**Comment by ShadaW11** [comment]
@octalpixel thank you, we will review the content and get back to you soon.

**Comment by ShadaW11** [comment]
Hello @octalpixel please go ahead and issue and submit your invoice. Your article is approved and will be published this week.
