### ISSUE TITLE
Create a Crypto converter with svelte and Strapi

### ISSUE THREAD

**Issue by alloyking1** [strapi/community-content#508]
**My resource**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article

Outline
About the app
The app will be a simple crypto currency converter. It will consume external crypto API's that returns real time crypto currency rates. It will be able to convert the value of one coin to another. An example would be converting Bitcoin to BNB. if the value of BTC is entered, it will calculate and give the equivalent value in BNB. The API consumption will be done in strapi. Svelte will be used for the front end.

Introduction
What’s is svelte 
Pros and cons of svelte
Strapi over view
Setting up svelte project
Create our crypto converter front end with svelte
Setting up Strapi project
Create our crypto converter backend with Strapi 
Conclusion 

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
@alloyking1 I would like you to expand more on the app features . What will the app do?

**Comment by ShadaW11** [comment]
@alloyking1 any update?

**Comment by alloyking1** [comment]
@ShadaW11 I added a description of the feature of the app.

**Comment by ShadaW11** [comment]
@alloyking1 please confirm that you commit to updating the tutorial after the V4 release without additional compensation. once you do, you can go ahead and start working on the article.

**Comment by alloyking1** [comment]
yes, sure @ShadaW11.

**Comment by ShadaW11** [comment]
@alloyking1 please go ahead

**Comment by ShadaW11** [comment]
@alloyking1 any update on the article?

**Comment by alloyking1** [comment]
Yes. The article is about 80% done. I’ll send a draft once it’s complete

**Comment by ShadaW11** [comment]
Hello @alloyking1 any update?
