### ISSUE TITLE
[ISSUE] Error in frontend 

### ISSUE THREAD

**Issue by munne01** [strapi/community-content#516]
**The concerning content**

https://strapi.io/blog/build-a-blog-with-vue-strapi-and-apollo
**Issue**
warning  in ./src/main.js

After following the full guide i get two errors in the frontend part of the code which says this 
"WARNING  Compiled with 2 warnings14:11:46

 warning  in ./src/main.js

"export 'default' (imported as 'Vue') was not found in 'vue'

 warning  in ./src/main.js

"export 'default' (imported as 'VueRouter') was not found in 'vue-router'" and i dont know where to go from here beacuse it't my first time working with strapi and Vue.

The two files i have uploaded are my main.js and my package.json if that would be of any help.

[main.zip](https://github.com/strapi/community-content/files/7203113/main.zip)
[package.zip](https://github.com/strapi/community-content/files/7203114/package.zip)

Thanks in advance

**Comment by ShadaW11** [comment]
Hello @munne01 this blog post will be updated after the V4 release. thank you for bringing our attention to this.
