### ISSUE TITLE
[SUBMIT] How to work with Strapi,docker, Postgres and Dokku (Self hosting heroku)

### ISSUE THREAD

**Issue by Eventyret** [strapi/community-content#517]
**My resource**

Hi everyone, so I noticed that Docker has been covered quite a few times but not with [Dokku](https://dokku.com/) (Think of dokku like your own Heroku, you can host it on Heroku you can host it yourself)

I wanted to make this possible into 3 parts.
- Part 1 covers setting up strapi from scratch, with SQLite (Now this has been ofc documented well before so my main focus would be Part 2 and 3)
 - Part 2 Dockerize with a plain `node.js` image and use it for development. We will also add docker-compose for local development so you can have your own Postgres database just like in production.
 - Part 3 covers setting up `dokku` from scratch, then enabling SSL and deploying our project. To finish this off we using a small Github Action script to automate the whole process.

This tutorial should be for developers that want to use docker for deployment but maybe self host it without hassle.

**My content is**

- [X] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @Eventyret Interesting outline, my only concern is that maybe some similar content exist in our resource center (documentation, blog) or online. Could you please take a quick look online through google search and make sure a similar article does not exist? Thank you.

**Comment by Eventyret** [comment]
Thanks for getting back to me @ShadaW11  i would say Part 1 is covered in docs, so that can be taken out. As it's just following the documentation.
The difference on Part 2 is most guides even documentation shows how to do this with `docker-compose` and also using the `strapi` docker image. This image is built from scratch using nodejs instead. So there is a difference meaning I believe a bit lighter etc.
Part 3 is covered by many mostly how to install `dokku` etc. Some like this [blog article](https://grahambailey.io/deploy-strapi-with-dokku/amp/) does not show how to deploy it with docker image but rather just deployment.

So it might seem "general", thought it's personal experience how I built it from scratch using resources and docs to build it on my own.

**Comment by ShadaW11** [comment]
Hello @Eventyret apologies for the delay. And thank you for expanding on the above outline. I now see the difference which I would suggest - adding additional elements to the article to have a unique value that cannot be found in other articles. Please note that we compensate for all articles published on our blog. You can check the details here in the FAQ section (payment, guidelines... https://strapi.io/write-for-the-community. Otherwise, I can accept it with the existing outline as a free guest post.

**Comment by Eventyret** [comment]
I'm happy to go a free guest post. Wanted to make a post not really get anything for it 😊😉

**Comment by ShadaW11** [comment]
@Eventyret awesome, go for it and thank youuu

**Comment by Eventyret** [comment]
Will do, will take a few weeks i think

**Comment by ShadaW11** [comment]
Hey @Eventyret Hows it going? hows the progress going?

**Comment by Eventyret** [comment]
Been busy with setting into my new role have been writing some of it but still few sections to go

**Comment by ShadaW11** [comment]
@Eventyret thank you for the update, take your time.

**Comment by Eventyret** [comment]
Still working on this just wanted to give an update.

**Comment by ShadaW11** [comment]
@Eventyret thank you for the update. I appreciate it.

**Comment by ShadaW11** [comment]
Hey @Eventyret its been a while, hows everything going.

**Comment by Eventyret** [comment]
Think we can close it as I wrote the normal guides without strapi in my blog. Https://Blog.dehlin.dev

**Comment by Eventyret** [comment]
Think we can close it as I wrote the normal guides without strapi in my blog. Https://Blog.dehlin.dev

**Comment by ShadaW11** [comment]
@Eventyret sure - it would be great to have you publish an article on the Strapi Blog as well

**Comment by Eventyret** [comment]
Feel free to repost it etc 😁😊
