### ISSUE TITLE
[TOPIC] Developing a one-click deploy button for both back and front end

### ISSUE THREAD

**Issue by JohnBauer-Strapi** [strapi/community-content#52]
**My Request**
Story on how Strapi contributor created a pretty cool one-click deploy button

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by malgamves** [comment]
Not sure if this is still relevant @Mcastres - you use one click buttons on all starters now. Will close it for now if that's okay with you.
