### ISSUE TITLE
Incomplete path in a tutorial 

### ISSUE THREAD

**Issue by jeangregoire2** [strapi/community-content#522]
**The concerning content**

Hi, 
I was following your new « Build a static blog with Gatsby 4 and Strapi » tutorial here : https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi

At some point when creating the individual articles, I had a problem saying basically that I my gatsby-node.js was trying to create a page in the components which caused an issue. After a bit of research on Gatsby's site documents, I realised that there was a word missing in one of the paths you are suggesting. 

At some point, you write : 

**Now we need to create a page that will display each one of your articles.

    Create a src/article/{StrapiArticle.slug}.js file containing the following:**
    
    The path for this should be src/PAGES/article/{StrapiArticle.slug}.js
    
    Thanks for your incredible turtorials. It's a great help for us beginners with strapi!

**Comment by ShadaW11** [comment]
Hello @jeangregoire2 thank you, this blog post will be updated soon after the V4 release.
