### ISSUE TITLE
Please do a latest deployment on app engine [SUBMIT]

### ISSUE THREAD

**Issue by mwanikigeorge** [strapi/community-content#523]
**My resource**

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by MattieBelt** [comment]
Hey @mwanikigeorge, there already exists an tutorial on how to deploy on G App Engine, take a look at the docs: https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/google-app-engine.html

**Comment by ShadaW11** [comment]
@MattieBelt thank youuuu.
