### ISSUE TITLE
Create a Temperature converter using NextJs, TailwindCss and Strapi

### ISSUE THREAD

**Issue by chyke007** [strapi/community-content#524]
My resource

Hi, I will like a create a new tutorial about creating a temperature converter website using Next JS, Tailwind and Strapi. This is the outline for the tutorial.

Outline

Introduction
Prerequisite
What is Next Js
What is Tailwind Css
What is Strapi JS
Scaffolding a Strapi Project
Building the Temperature collection
Scaffolding a NextJs project
Building NextJs Components
Seeding Strapi
Allowing Public access
Testing App
Conclusion

Also, I am committed to updating the article after the Strapi V4 release.

What do you all think?
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hello @chyke007 love the idea, however the V4 beta will be out in a few days. Lets wait until next week and we will then check if its possible to work on the article.

**Comment by chyke007** [comment]
Ok @ShadaW11 Would wait then, thanks

**Comment by ShadaW11** [comment]
Hello @chyke007 the V4 beta has been released. Please let me know if you would be able to start working on the article?

**Comment by chyke007** [comment]
Yes @ShadaW11 I would love to commence work now.

**Comment by ShadaW11** [comment]
awesome @chyke007 however, the new beta V4 release does not include the design system so any screenshots used in the article should be updated at the of the month without additional compensation. do you agree to that?

- If this is your first article, please register here https://strapi.io/write-for-the-community
Then go over the guidelines (payment, how to submit and article guidelines)

**Comment by chyke007** [comment]
Yes, it is my first time and I have registered already, however I don't understand what you mean by design system here.

**Comment by ShadaW11** [comment]
Please check out the V4 discussion on Discord. The design system of strapi
is still not released with the beta V4. So screenshots should be updated
after the V4.

--

Shada Wehbe

Program Marketing Manager - Paris, France

Website <https://strapi.io/> | Get a demo <https://strapi.io/demo> | Roadmap
<https://portal.productboard.com/strapi/1-roadmap/tabs/2-under-consideration>



Before you go: Learn what is Strapi in just 3 minutes
<https://strapi.io/documentation/v3.x/getting-started/quick-start.html>

**Comment by chyke007** [comment]
Yes I have read about v4. I would commence work next week on this

**Comment by ShadaW11** [comment]
@chyke007 perfect go ahead. thank you.

**Comment by chyke007** [comment]
Hi @ShadaW11 I have shared my draft with you

**Comment by ShadaW11** [comment]
Your article has been published and invoice well received. Thank you so much. looking forward to receiving future articles.
