### ISSUE TITLE
User authentication with Nuxt.js and strapi

### ISSUE THREAD

**Issue by AsaoluElijah** [strapi/community-content#525]
I'll love to write a comprehensive article on how to build a user authentication system with nuxt.js and strapi.
This will cover the step by step process of integrating signup, login, and forgotten password features in a nuxt.js application, using strapi as backend.

### Outline
Introduction
Prerequisite
Setting up a new nuxt.js application
Setting up a new strapi application
Scalfolding the front-end
Designing the API with strapi
Integrating the API with Nuxt
Implementing forgotten password using **strapi-provider-email-nodemailer**
Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hello @AsaoluElijah thank you for submitting an outline. However we already have some similar articles on our blog here https://strapi.io/blog Feel free to suggest other articles.
