### ISSUE TITLE
[Request New Content] Advantages of using a Next.js + Strapi vs plain React + Strapi 

### ISSUE THREAD

**Issue by vcoisne** [strapi/community-content#532]
**My Request**

People who are new to Headless CMS, Jamstack types of development might wonder: Are there significant advantages of using a Next.js + Strapi vs just a React + Strapi?

Meta-frameworks like Next or Nuxt leave less room for decision making which sometimes cripples developers as using something like React and Vue means you have to pick tools for routing, state management and authentication for example. There are trade-offs of course React and Vue are baselines so if you want to build websites in a particular way they are great places to start. 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ShadaW11** [comment]
@Saintdavidking awesome looking forward to receiving your article.

**Comment by Saintdavidking** [comment]
Hello @ShadaW11 , here is the link to the article draft
https://www.dropbox.com/scl/fi/dgvnj0c0tj0cwnawjlo2q/Advantages-of-using-Next.js-Strapi-vs-CRA-Strapi.paper?dl=0&rlkey=s6pryb5oqmyeyvm758xrfe6ut

**Comment by ShadaW11** [comment]
Hello @Saintdavidking thank you, ill get back to you soon with feedback.

**Comment by Saintdavidking** [comment]
Hello @ShadaW11 am patiently expecting your feedback

**Comment by ShadaW11** [comment]
@Saintdavidking your content is published, please issue and send your invoice following the FAQ section in the write for community page on our website. thank you
