### ISSUE TITLE
[Request New Content] Build a News Aggregator Site

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#533]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by icode247** [comment]
Hello @ShadaW11 
Has this topic been taken? I can write on this topic

**Comment by icode247** [comment]
Hello @ShadaW11 
Has this topic been taken? I can write on this topic

**Comment by ravgeetdhillon** [comment]
Hey @ShadaW11 ,

Pitch:

This tutorial will help the readers to build a news aggregator app with Strapi and Nuxt.js. The news will be aggregated from different feeds and update in the Strapi News Collection. News aggregation will be automated using a CRON job which will run every 1 hour and fetch new feed items.

Here is the outline for the article:

```
Introduction
Prerequisites
What is Strapi
What is Nuxt.js
Scaffolding a Strapi v4 Project
Building the News Collection
Building the FeedSource Collection
Scaffolding a Nuxt.js project
Building Nuxt.js app
Allowing Public access
Testing App
Conclusion
Include screenshots
Include code
Link to GitHub Repo
```

Let me know if this is okay with you. Thanks.

**Comment by ravgeetdhillon** [comment]
Hey @ShadaW11, Perfect I'll add these things as well. One more thing. Is there any deadline that I need to follow?

**Comment by ShadaW11** [comment]
Hello @icode247 thank you but maybe you can focus on other articles.

**Comment by ravgeetdhillon** [comment]
Hey @ShadaW11, I have written the tutorial.

Here is the [Dropbox link](https://paper.dropbox.com/doc/Build-a-News-Aggregator-App-using-Strapi-and-Nuxtjs--BVUuocM8ZLDWvbSIWAGgoqJoAQ-tlbSgZBOYsGDgokm0vjfu).

Let me know about any edits. I would be happy to assist.

Thanks.

**Comment by ShadaW11** [comment]
Hello @ravgeetdhillon thank you so much.  Your article looks awesome. Someone from our team will review the article and get back to you with feedback.

**Comment by ShadaW11** [comment]
@ravgeetdhillon Your article has been published. Please check the FAQ section to learn how you can issue and submit your invoice.
