### ISSUE TITLE
[Request New Content] Serve different content based on user data/membership - Strapi Tutorial

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#534]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ShadaW11** [comment]
Hello @icode247  Can you please explain in short what is the use case? what will you build? what are the different membership levels of this app? Im not sure I understand well. thanks

**Comment by icode247** [comment]
Hello, @ShadaW11 I have written the tutorial.
Here is the [dropbox](https://www.dropbox.com/scl/fi/mbti3l4uor272l698reix/How-to-Serve-Different-Content-Based-on-User-Data_Membership-with-Strapi-and-React.paper?dl=0&rlkey=f1s9dwuo7zdhgzwx8iv2w1fjx) link to the draft.
Let me know if there are edits.

Thanks.

**Comment by ShadaW11** [comment]
Hey @icode247 thank you, will take a look and get back to you with feedback

**Comment by ShadaW11** [comment]
Hey @icode247 Can you please check the comments left on your article?

**Comment by icode247** [comment]
Hello @ShadaW11, I have resolved all the comments on my draft.

**Comment by icode247** [comment]
Hello @ShadaW11, I have resolved all the recent comments on my draft.

Thanks.

**Comment by ShadaW11** [comment]
@icode247 thank you our reviewer will get back to you with feedback.

**Comment by ShadaW11** [comment]
Hello @icode247 your article has been published. Please check the FAQ section to submit and issue your invoice.

**Comment by icode247** [comment]
@ShadaW11  I have sent an invoice.
