### ISSUE TITLE
[Request New Content] X things to consider before choosing a CMS for your online ecommerce store

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#536]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Caleb335** [comment]
Hi, I'd love to work on this.

What do I need to know?

**Comment by Vic-Orlands** [comment]
Hi @ShadaW11 if this article is still available, I would love to write about it. I will send an outline immediately if confirmed.

**Comment by Vic-Orlands** [comment]
@ShadaW11 any update on the article

**Comment by ShadaW11** [comment]
@Vic-Orlands your article is still in review. I will get back to you this week with Feedback.

**Comment by ShadaW11** [comment]
@Vic-Orlands can you please check the comments left by our reviewer on your article and ping me once you the changes in the article are implemented?

**Comment by Vic-Orlands** [comment]
@ShadaW11 changes have been made. You can check now

**Comment by ShadaW11** [comment]
@Vic-Orlands your article has been published, please submit your invoice
