### ISSUE TITLE
[SUBMIT] How to Build a Blog using Blazor WASM and Strapi

### ISSUE THREAD

**Issue by sumitkharche** [strapi/community-content#538]
**My resource**

Hello 👋 
I'll like to write on this topic.

 - **Title**: How to Build a Blog using Blazor WASM and Strapi
- **Short Description**: In this article, I'm going to show you how to create a simple but blazing fast blog using [Blazor WebAssembly](https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor), [Tailwind CSS](https://tailwindcss.com/), and [Strapi](https://strapi.io/). We will be using Strapi which is the leading open-source headless CMS to store our posts and Blazor for frontend.

**Outline**
- Introduction
- TL;DR
- Prerequisites
- What is Blazor?
- What is Strapi
- Setting up a Strapi project
- Setting up Blazor project
<ul>
<li> Building a Blog Application
<ul>
<li>Integrating Strapi API with Blazor App</li>
<li>Display all blogs on the home page</li>
<li>Display a single blog post</li>
</ul>
</li>
</ul>

- Deployment
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by sumitkharche** [comment]
What do you think on this article request? @ShadaW11 
If it will approve then I can immediately work on it and finish it asap.

**Comment by sumitkharche** [comment]
@ShadaW11 Thank you for approving this topic.
I will do the above mentioned steps.

**Comment by sumitkharche** [comment]
@ShadaW11 Is there any updates from reviewer on this article.

**Comment by ShadaW11** [comment]
Hello @sumitkharche I will get back to you this week with some feedback. thank you

**Comment by ShadaW11** [comment]
@sumitkharche You article has been published on our blog. Can you please issue and submit an invoice? please check the FAQ section to review the instructions https://strapi.io/write-for-the-community

**Comment by ShadaW11** [comment]
@sumitkharche can you please send us your bank account to issue your payment please.
