### ISSUE TITLE
[SUBMIT] Using Database Transactions to safely write custom business logic in Strapi

### ISSUE THREAD

**Issue by willnode** [strapi/community-content#539]
**My resource**
Hi, I am willing to create a guide to use database transactions which are important when writing custom business logic. It uses a (possibly) undocumented feature in the underlying query system in Strapi. It may take longer to write. Anyway, this is the outline for the tutorial:

**Outline**

Introduction
Prerequisite
Why Database Transaction?
How Strapi Handles Database
Writing Custom Controller in Strapi
Strapi Query Functions
Writing Database Transactions
Handling Transaction Errors
Testing the App
Other Examples with Transactions
Conclusion

I'm willing to update the article/wait for Strapi v4 release.

**My content is**

- [X] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by willnode** [comment]
+ Thanks, without MongoDB it will be easier to write actually.
+ For in-depth explanation I will explain by transferring user balance to another. That won't be the only example though.
+ Yes, I use transactions right in one of my projects which also uses Strapi.

**Comment by willnode** [comment]
I have updated the outline.

**Comment by ShadaW11** [comment]
Hey hey @willnode hows everything going?

**Comment by willnode** [comment]
Almost there! I'll share the link in a few hours.

**Comment by willnode** [comment]
Sorry for taking so long, [here's the draft ready to review](https://www.dropbox.com/scl/fi/lsbrrl6adt2tmebypq72y/Using-Database-Transactions-to-Write-Queries-in-Strapi.papert?dl=0&rlkey=dj3qs264po3pl0yul0l1imnrc).

**Comment by ShadaW11** [comment]
Hey @willnode no worries at all, thank you so much for submitting it. I will go over the article and get back to you.

**Comment by ShadaW11** [comment]
Hello @willnode I noticed you archived your article before completing the review? Any reason for that? Is it because of Knex support?

**Comment by willnode** [comment]
Somebody did. I'm not doing that. I'll unarchive it.

**Comment by ShadaW11** [comment]
@willnode great article, thank you for the effort. Mattie left you some comments. Would you mind taking a look at the feedback?

**Comment by willnode** [comment]
Hi, thanks for the comments @MattieBelt. Sorry, I can't take a look today. I will do it tomorrow.

**Comment by willnode** [comment]
I have made changes according to the feedback. Sorry for taking so long :)

**Comment by ShadaW11** [comment]
Hello @willnode your article is reviewed and will be published soon. Please issue and submit your invoice. Thank you and looking forward to your next article.

**Comment by willnode** [comment]
Thanks for the good news @ShadaW11 .  I'll be waiting for the published URL link 😄

(also I'm sending you an email to ask about something, In case you haven't noticed it yet).

**Comment by ShadaW11** [comment]
Thank you @willnode  your invoice is well received.
