### ISSUE TITLE
[SUBMIT] Create, Retrieve, Update and Delete (CRUD) application using Flutter and Strapi

### ISSUE THREAD

**Issue by Maxiggle** [strapi/community-content#540]
**My resources**

## Overview
In this tutorial, we will learn how to build a Create, Retrieve, Update and Delete (CRUD) application using Flutter and Strapi. We will call End-points provided to us by Strapi using the HTTP package in our app.
We will build screens where different operations will take place like adding/creating a new user, Retrieve User data, Updating user data, and Deleting data.

## Outline

- What is headless CMS
- Why  Strapi
-  Setup Flutter project
    - File Structure
- Add Http package to `yaml file` to fetch APIs
- Setup Strapi
- Create a strapi collection type
- Add fields 
    -  Name
    -  E-mail 
    -  Password
- Adding roles and permissions
- Build screens
    - Create a user screen to add users
    - Display user screen
    - Create My Details screen
    - Edit function
    - Delete function
- Test App
- Conclusion
- Resources

-->

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
@Maxiggle any update

**Comment by Maxiggle** [comment]
I will be submitting the complete draft tommorrow

**Comment by Maxiggle** [comment]
It took me some time to build the app, as i had some conflicts with my localhost

**Comment by Maxiggle** [comment]
Hello @ShadaW11 this is the link to the draft.
I used Dropbox 
https://www.dropbox.com/scl/fi/ec7g9hxm1jz3pacb5plka/Build-a-Simple-CRUD-Application-Using-Flutter-and-Strapi.paper?dl=0&rlkey=wny42wd06hoalumqvjjdpof4v

**Comment by ShadaW11** [comment]
@Maxiggle great thank you, will get back to you with feedback soon.

**Comment by Maxiggle** [comment]
Ok

**Comment by Maxiggle** [comment]
@ShadaW11 
Hi, I haven't gotten any update about reviewing the draft.

**Comment by ShadaW11** [comment]
hey @Maxiggle the article is still in review, apologies for the delay

**Comment by Maxiggle** [comment]
Ok then thankyou @ShadaW11

**Comment by Maxiggle** [comment]
@ShadaW11 What's going on
The Editor that reviewed my draft has not said anything yet after making some changes and created picture lead for the article

**Comment by ShadaW11** [comment]
@Maxiggle your article is approved, feel free to issue your invoice; I noticed that you did not register your author details here, https://strapi.io/write-for-the-community Can you please fill the form asap

**Comment by ShadaW11** [comment]
@Maxiggle please submit your invoice once possible to be able to issue your payment.
