### ISSUE TITLE
[SUBMIT] 5 Features A Headless CMS must have

### ISSUE THREAD

**Issue by oyedeletemitope** [strapi/community-content#541]
**I'll like to write on this**

Here is my outline

Introduction
What is an headless CMS
Choosing a headless CMS over a traditional CMS
5 Features A CMS must have
Conclusion

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @oyedeletemitope we have already published many articles around this subject such as:
  https://strapi.io/blog/traditional-vs-headless-cms-a-comparison 
and this https://strapi.io/blog/how-to-choose-a-headless-cms I would suggest pitching another article. Looking forward to it;
