### ISSUE TITLE
Build a Trello clone with React and Strapi

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#542]
I would like to write an article on how to build a drag and drop task management platform (like trello, and github board) with react and strapi.

Below is my outline

### Outline

Introduction
Prerequisite
Creating a new react app
What is strapi
Scalfolding a new strapi project
Building tasks collection on strapi
Building the front-end
Connecting front-end to strapi
Testing app
Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hello @lucky4242 great please go ahead and start working on it.

**Comment by lucky4242** [comment]
@shada w11 thanks, and  working on it

**Comment by ShadaW11** [comment]
@lucky4242 any update?

**Comment by lucky4242** [comment]
@shada i will be submiting it next week

**Comment by lucky4242** [comment]
Hi @ShadaW11 
This is the link to the tutorial
https://www.dropbox.com/scl/fi/v5jej9ln6c46hj4xx2ut5/Build-a-Trello-Clone-Application-with-React-and-Strapi.paper?dl=0&rlkey=e3kj5wfmbcshkzsewpyfaxy18

**Comment by lucky4242** [comment]
Hi @ShadaW11 
What is the current status of my project? I upgraded it to the new Strapi version4.
https://www.dropbox.com/scl/fi/v5jej9ln6c46hj4xx2ut5/Untitled.paper?dl=0&rlkey=e3kj5wfmbcshkzsewpyfaxy18
sorry for the delay

**Comment by lucky4242** [comment]
Hi @ShadaW11
What is the current status of my project?

**Comment by ShadaW11** [comment]
@lucky4242 Hello Opuama and apologies for the delay due to the holiday period. Our reviewers will review your article and get back to you asap. Thank you again for your patience.

**Comment by lucky4242** [comment]
Hi @ShadaW11
Any update on my project?

**Comment by ShadaW11** [comment]
Hello @lucky4242 yes, can you please check the comments left on your article and tackle them asap to prepare it for publishing?

**Comment by ShadaW11** [comment]
@lucky4242 I saw that you started working on the comments. Please ping me once all are fixed.

**Comment by ShadaW11** [comment]
Hello @lucky4242 thank you, I saw a few other comments pending by our reviewer. Can you please work on them, we planned on publishing the article today? Also can you please issue and submit your invoice

**Comment by ShadaW11** [comment]
@lucky4242 Thank you for addressing the comments, please issue and submit your invoice.

**Comment by lucky4242** [comment]
Hi
 @ShadaW11 invoice submitted.

**Comment by ShadaW11** [comment]
@lucky4242 please check again the resolved comments

**Comment by lucky4242** [comment]
hi 
@ShadaW11 comments resolved

**Comment by ShadaW11** [comment]
Hello @lucky4242 great, one last thing missing, can you please add a link to the repo with the example code?

**Comment by lucky4242** [comment]
hello @ShadaW11 
Github repo link  created

**Comment by ShadaW11** [comment]
@lucky4242 I still can't see the repo link in the dropbox article? where exactly in the article did you add it?

**Comment by ShadaW11** [comment]
@lucky4242 great thank you, your article will be published this week.
