### ISSUE TITLE
Create a ChatBot Assistant using NextJs, TailwindCss and Strapi

### ISSUE THREAD

**Issue by chyke007** [strapi/community-content#543]
My resource

Hi, I will like a create a new tutorial about creating a Chat Bot Assistant using Next JS, Tailwind and Strapi. This is the outline for the tutorial.

Outline

Introduction
Prerequisite
What is Next Js
What is Tailwind Css
What is Strapi JS
Scaffolding a Strapi Project
Building the Bot collection
Scaffolding a NextJs project
Building NextJs Components
Seeding Strapi
Allowing Public access
Testing App
Conclusion

Also, I am committed to updating the article after the Strapi V4 release.

What do you all think?
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
@chyke007 please go ahead and start working on it.

**Comment by chyke007** [comment]
Hi @ShadaW11 here is a link to the finished tutorial:

https://www.dropbox.com/scl/fi/5m93jdoj9bjo224n9lq4w/Create-a-ChatBot-Assistant-using-NextJs%2C-TailwindCss-and-Strapi.paper?dl=0&rlkey=grcvo9zyb4do0dwqigjtqbmv3

**Comment by ShadaW11** [comment]
Hello @chyke007 thank you, your article will be reviewed as soon as possible.

**Comment by bigpreshy** [comment]
@chyke007 I have left a few comments for you on the article. Kindly attend to them. Thanks

**Comment by ShadaW11** [comment]
@chyke007 your article has been published, in case you havent please submit your invoice.
