### ISSUE TITLE
[SUBMIT] Tutorial: how to setup and use Strapi for store your app's logs

### ISSUE THREAD

**Issue by zeppaman** [strapi/community-content#545]
In most application scenarios, a frontend application produce logs that need to be collected and managed centrally. Most of the services required paid subscriptions. This article explains how to set up Strapi to act as a backend for collecting logging and showing them to the developers. The result of this step to step guide is a replicable solution for ingesting logs from any frontend application and the javascript code for connecting.

The article will be accompanied by a GitHub repo with the source code related.

Outline:
- Introduction
- Install and configure Strapi
- The javascript library
- Test it on a javascript application
- Conclusion

**My content is**

- [ X ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hey @zeppaman, seems like an interesting use case. If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling the form. Then please scroll to the FAQ section and go over the article guidelines, how to submit article, issue invoice and get paid. Looking forward to receiving the article.

**Comment by zeppaman** [comment]
Thank you @ShadaW11. The form was filled! Can I share the article link by mail? or do I have to use this thread?

**Comment by ShadaW11** [comment]
awesome @zeppaman once the article is ready, add the dropbox link here and we'll have someone review it asap. No need to email the link. thank you

**Comment by zeppaman** [comment]
here is the link:
 https://www.dropbox.com/scl/fi/677ksalyk9qieya3fw9ky/How-to-setup-and-use-Strapi-for-storing-your-app-s-logs.paper?dl=0&rlkey=5wl2aoa2m8h18qsi03wi68in7

**Comment by zeppaman** [comment]
@ShadaW11 when I have sent the link in my prev message I forgot to ask about the images. I created it in Figma, but I don't know if I have to export and upload them somewhere. thanks

**Comment by ShadaW11** [comment]
@zeppaman no worries at all will take a look at the figma file.

**Comment by ShadaW11** [comment]
@zeppaman Hello, apologies for the delay. Your article is now live. Feel free to issue and submit the invoice, the invoice template and how to details are in the write for the community page.

**Comment by ShadaW11** [comment]
@zeppaman please dont forget to prepare and send your invoice once possible.
