### ISSUE TITLE
[ISSUE]  portfolio website using strapi

### ISSUE THREAD

**Issue by Ezekiel8807** [strapi/community-content#548]
**My Request**

Hello 👋

I would love to create a portfolio website using strapi.👨🏿‍💻👨🏿‍💻
I hope my request is granted

**Comment by ShadaW11** [comment]
Hello @Ezekiel8807 thank you for proposing a tutorial idea. Can you please submit an outline of what you have in mind for this tutorial?

**Comment by Ezekiel8807** [comment]
This are the outline

1. Introduction
2. Features of the application
3. Prerequisites
4. Installation of Strapi
5. Building portfolio using Vue and strapi
6. Conclusion

**Comment by ShadaW11** [comment]
Thank you for taking the time to submitting the outline. I would suggest including other interesting use cases as we currently have similar articles already published on our blog here http://strapi.io/blog
