### ISSUE TITLE
[SUBMIT] Strapi Authentication in Nuxt.js

### ISSUE THREAD

**Issue by ramigs** [strapi/community-content#55]
**My resource**
Strapi Authentication in Nuxt.js

**My format**

- [X] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Interesting tutorial! Thanks for this @ramigs !

**Comment by Mcastres** [comment]
Hello @ramigs, how are ? 
Have you had a chance to work on this content recently?

**Comment by ramigs** [comment]
Hi Maxime,

Yes, I have.

Already have the entire workflow done in terms of code (including registration with email confirmation and password reset).
Also wrote the main outline and majority of of the article's sections. 
By the end of next week I'll have a version ready for feedback and review :)

**Comment by Mcastres** [comment]
Awesome! Can't wait to see it :)

**Comment by ramigs** [comment]
Happy to announce that the article is ready:

[Markdown version](https://github.com/ramigs/strapi-nuxt-article/blob/master/strapi-nuxt.md)

Any feedback/review is very welcome :)

**Comment by ramigs** [comment]
While this article was being reviewed, got to know about the release of [@nuxtjs/strapi](https://strapi.nuxtjs.org/).

This means that this app will probably be rewritten (using the new package) and the article updated accordingly.

Since the package was release pretty recently, I'll also try to contact the authors/maintainers to find out if they have any suggestion regarding the output/outline of the article or in what way could it help move the project forward.

**Comment by malgamves** [comment]
Awesome, let's wait a few days @ramigs and then we'll publish if the issue isn't resolved.
