### ISSUE TITLE
[SUBMIT] How to build a Product Information Manager (PMI) using Strapi

### ISSUE THREAD

**Issue by amirtds** [strapi/community-content#558]
**My resource**

How to build a Product Information Manager (PMI) using Strapi

- Pre-requisites
- Goals
- Introduction
- What is a PMI ?
- Step 1 - Create product content type
- Step 2 - Collect Products data into Strapi
- Step 3 - Enrich Products Data
- Step 4 - Stream Products Data into multiple sales channels - Shopify and NextJS website
- Let's see how it works in real world
- Conclusion

**My content is**

Tutorial

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @amirtds can you please explain more about what you plan on building in this outline?

**Comment by amirtds** [comment]
Hi @ShadaW11 Thanks for taking a look at this.
Sure, the idea behind [PMI](https://www.akeneo.com/what-is-a-pim/) is to have a single source of truth for product information and distribute this information to different channels like Shopify or other ecom site.
In this article, we can show how we can use Strapi as a single source of truth for products and enrich products data using UI. Also using webhooks to publish products in different sales channels like Shopify etc.

**Comment by amirtds** [comment]
Hi @ShadaW11 Let me know please what do you think. Thanks

**Comment by ShadaW11** [comment]
Hey @amirtds its been a while, do you still have time to work on this?

**Comment by amirtds** [comment]
Hi @ShadaW11 Sure, would be great to get back to this article

**Comment by TiaraOluwanimi** [comment]
@amirtds, any update on this?

**Comment by amirtds** [comment]
@ShadaW11 @TiaraOluwanimi I have the initial version for review by tomorrow EOD.

**Comment by amirtds** [comment]
@ShadaW11 @TiaraOluwanimi The tutorial is ready for review [here](https://www.dropbox.com/scl/fi/50zwcutryzzxyea77nvfd/How-to-build-a-Product-Information-Manager-using-Strapi.paper?dl=0&rlkey=zgtjjg5xccnw1ll21g2e21tn7)

**Comment by amirtds** [comment]
Thanks @TiaraOluwanimi for your review. I took care of your comments

**Comment by amirtds** [comment]
Hi @TiaraOluwanimi Let me know please if you need anything from my end, thank you //cc @ShadaW11

**Comment by amirtds** [comment]
@TiaraOluwanimi Is there anything that is blocking this article to get published ?

**Comment by dessireugarte** [comment]
Hello @amirtds 👋
Sorry for the late reply. We have been having some internal changes that have delayed a little the articles. 
But this article will be live next week. I will get back to you when is public so you can move forward with your invoice and payment.

**Comment by amirtds** [comment]
Hi @dessireugarte 
Happy to hear from you, Thank for the heads up. Sounds great, Looking forward to get the tutorial published 👋

**Comment by dessireugarte** [comment]
Hello @amirtds  👋 Your article is [live](https://strapi.io/blog/how-to-build-a-product-information-manager-using-strapi)! Congrats and great job 🎉

Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) and soon you will receive your payment. Please feel free to reach out to me if you have any questions!

**Comment by amirtds** [comment]
Awesome thank you @dessireugarte I submit the invoice

**Comment by amirtds** [comment]
Hi @dessireugarte Seems I didn't receive the payment yet, could you please let me know if you need anything from my end, thanks

**Comment by malgamves** [comment]
I'll check that @amirtds could you message me on discord?

**Comment by amirtds** [comment]
@malgamves Thanks, That's odd i didn't receive an email form you. Let me send you a msg over discord
