### ISSUE TITLE
Create a Url Shortener using NextJs, Tailwind CSS and Strapi

### ISSUE THREAD

**Issue by chyke007** [strapi/community-content#561]
My resource

Hi, I will like a create a new tutorial about creating a Url Shortener using Next JS, Tailwind and Strapi. This is the outline for the tutorial.

Outline

Introduction
Prerequisite
What is Next Js
What is Tailwind Css
What is Strapi JS
Scaffolding a Strapi Project
Building the Url collection
Scaffolding a NextJs project
Building NextJs Components
Seeding Strapi
Allowing Public access
Testing App
Conclusion

Also, I am committed to updating the article after the Strapi V4 release.

What do you all think?
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
@chyke007 interesting app idea, my only concern is knowing if this app can be created without Strapi? I want to ensure that Strapi will be the core of the app.

**Comment by chyke007** [comment]
Strapi would act as the core as it would be used to store the urls(both original and shortened) as well as keep track of number of times a shortened url is visited.

**Comment by ShadaW11** [comment]
so a bitly clone? if so, please go ahead and start working on it. @chyke007

**Comment by chyke007** [comment]
Yes

**Comment by chyke007** [comment]
@ShadaW11 
The finished link: https://www.dropbox.com/scl/fi/u5i0pstrappm8td4h1tld/Create-a-Url-Shortener-using-NextJs%2C-Tailwind-CSS-and-Strapi.paper?dl=0&rlkey=g58ebv9g26i2ege5jt4ekinap

**Comment by ShadaW11** [comment]
Thank you @chyke007 your article has been reviewed and published. Please issue your invoice.
