### ISSUE TITLE
[SUBMIT]

### ISSUE THREAD

**Issue by Alex-husar** [strapi/community-content#562]
# **Content Going Global: A Sneak Peek into Website Localization**

Have you ever opened a website that wasn’t in your language? Let’s assume you land on a page and see a bunch of symbols or words that you can’t comprehend. What do you do next? Either close the site or search for settings to switch the region or language. Two clicks here and there, and you see content that you can understand.

Most likely, you haven’t given it much thought, but website localization and content adaptation are a huge scope of work that requires the input of many specialists. In order to reach and cater to the needs of a global audience, businesses that target multiple countries or clients speaking different languages invest a lot of time and resources into supporting a multi-lingual online presence.

What obstacles can occur during the process? How should you adapt content according to the audience and region specifics? Which things should you keep in mind when localizing a site and creating a separate content plan? This article will answer these questions, give tips, and show you the “behind the scenes” of website localization.

## **Why Do Businesses Localize Their Sites and Content?**

(_Going global and expanding the market is crucial for many businesses who plan to obtain clients from various countries. In most cases, you can’t just copy-paste content into Google translate and expect the users to enjoy their experience. It must be equally easy for an English-speaking customer to browse or shop on an eCommerce site as it is for a Japanese-speaking one_.)

## **The Peculiarities of Language-Specific Website Design**

(_Languages differ greatly from one another: this implies average word length, size and span of symbols, and even the direction in which a user reads words. All of this and more must be taken into consideration when adapting a design for the content to look good in various languages. I’ll back up these ideas with visual examples._)

## ** \
Some Insights into the Technical Side of Localization**

(_Approaches to site\app\content localization; how different site constituents are translated;  plus a link to the Strapi article and plugin product page_)

## **Adapting Content for a Language & Region**

(_Again, using machine translation is usually not enough to bring value to the user. Wordplay, voice, humor, and calls to action can be among the main obstacles. Therefore, content should be presented bearing in mind many things, including cultural and linguistic peculiarities. \
 \
For example, even American English and British English have discrepancies in word use (pants vs. trousers). Other languages, like European Portuguese and that spoken in Brazil, have such vocabulary and phrase usage differences too. Content creators must not forget about that. \
 \
Similarly, the content plan should ideally be tweaked according to the specifics of the country, not only language. Holidays, backgrounds, and values must be kept in mind._

_Working with an international team of contributors. For the best results, equip the team with translators and content creators from the country of origin_)

## **Major Takeaways**

**My content is**

- A Strapi Tutorial / Guide / How to article

**Comment by ShadaW11** [comment]
Hello @Alex-husar thank you so much for pitching your article. Its a great topic. However, my concern is that we have similar articles already published on our blog: 
https://strapi.io/blog/localize-your-content-and-succeed-globally
https://strapi.io/blog/strapi-localization-best-practices
https://strapi.io/blog/i18n-implementation-best-practices-in-strapi

I would be happy to review any new ideas that would be of great value.
