### ISSUE TITLE
[SUBMIT] Building a URL Shortner Service with Strapi, Vercel Edge Functions, Next.js and Refine

### ISSUE THREAD

**Issue by octalpixel** [strapi/community-content#563]
**My resource**

Hello 👋 

In this article, we will be covering on building a service to shorten, share, and track links using Strapi and Vercel Edge functions. The article will focus on the aspect of using Strapi to quickly build a REST API and not the CMS part of it. A frontend will be built using Next.js and Chakra to manage links and view tracking stats.

**Title**: Building a URL Shortner Service with Strapi, Vercel Edge Functions, Next.js, and Refine

**Outline**
- Introduction
- What is Edge Functions
- What is Vercel Edge Functions and Why ?
- Creating API with Strapi
- Frontend Setup Next.js 
    - Implementing next-auth with Strapi 
    - Create a dashboard to create links and see stats
- Create Next.js middleware
    - Setup Redirects
    - Tracks stats 
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @octalpixel As discussed earlier, another author has mentioned a similar use case. If they won't be taking the topic, ill get back to you.

**Comment by octalpixel** [comment]
All good @ShadaW11
