### ISSUE TITLE
[SUBMIT] Fetch and Display Strapi Data in Chart.js

### ISSUE THREAD

**Issue by bigpreshy** [strapi/community-content#567]
**My resource**
Outline

- Introduction
- What is Strapi, Setting up a Strapi Project
- Creating data collection
- Setting up project and fetching the data using [Chart.js](https://www.chartjs.org/)
- Seeding Strapi with data
- Giving Permission 
- Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @bigpreshy We will resume working on new tutorials after we have updated a big portion of our content.

**Comment by ajibade3210** [comment]
Hello @ShadaW11 @PaulBratslavsky Can i pick up this article

**Comment by vcoisne** [comment]
@ajibade3210 unfortunately at the moment we're no longer looking for intro level tutorials as we already have a backlog. Closing for now.
