### ISSUE TITLE
[SUBMIT] How to create a user profile

### ISSUE THREAD

**Issue by drewtownchi** [strapi/community-content#57]
**My Request**
How to create a section on your site that allows users to view information about themselves, their favorite blog posts/recipes/etc. Also, how to edit their information and the required controller work in order to let users edit their own information.

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by Mcastres** [comment]
Awesome! This can be very interesting and a part that can be implemented in our blog tutorials series
