### ISSUE TITLE
[SUBMIT] Hospital Patient Record App

### ISSUE THREAD

**Issue by Victory-ET** [strapi/community-content#570]
**My Request**

Hello 👋 

In this article, we will build a Record application focusing on Patient Records. The app will focus on managing patient records in relation using the Strapi CMS and will provide all records for any patient when a request is made. These records will be fetched from an API and stored in Strapi.

Title: Build a Hospital Patient Record App with NextJs and Strapi

Outline

Here is an example:
Outline
- Introduction
- What is Strapi?
- Setting up a Strapi project
- Building our App
- Fetching API data to Strapi
- Integrating the app with Strapi
- Testing the App
- Conclusion
- Resources 

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by wesley974** [comment]
Hello, very interesting! I'm a sysadmin, any date for the full tutorial?

**Comment by ShadaW11** [comment]
Hey @Victory-ET I love the tutorial idea. When would you be able to deliver the article? 
@wesley974 any feature you think should be included in the above tutorial?

**Comment by Victory-ET** [comment]
Ho @ShadaW11 @wesley974 Thanks for the prompt reply. I will be able to deliver the article on the 20th of December.

**Comment by wesley974** [comment]
@Victory-ET Would be awesome if you could do it from scratch, give all the necessary knowledge to build the app fully with JWT feature. Perhaps using NodeJS/express stack.

**Comment by ShadaW11** [comment]
@Victory-ET Hello, I hope you are doing well. How's the progress going? Please note that we released v4 as you may have seen therefore, please make sure your app is compatible with v4

**Comment by Victory-ET** [comment]
Hi @ShadaW11 I'm still working on the tutorial and will soon make a submission. I'm aware of the v4 release and will make use of it. Thanks

**Comment by ShadaW11** [comment]
@Victory-ET any update on this article?

**Comment by Victory-ET** [comment]
Hi @ShadaW11 ,

Thanks for checking in on me. I will be making a submission on this next week.

**Comment by Victory-ET** [comment]
Hi @ShadaW11,

I am done writing the draft for the article, here is a link to the article written using Dropbox:
[Building a Hospital Records app](https://www.dropbox.com/scl/fi/g20eb2870j4atp6um4bgt/Building-a-Hospital-Record-App-with-Strapi-CMS.paper?dl=0&rlkey=1l6oex6tsp3qrl65sdu667j63)

**Comment by malgamves** [comment]
Thanks @Victory-ET we'll have someone take a look.

**Comment by Victory-ET** [comment]
Hi @malgamves my article has been reviewed by the person assigned. What's the next step please

**Comment by Victory-ET** [comment]
Hi @ShadaW11 , thanks for the update 🎉🙂. Looking forward to it.

**Comment by ShadaW11** [comment]
Hey @Victory-ET your article has been published, please issue your invoice. Guidelines for the invoice are found in the FAQ section here https://strapi.io/write-for-the-community
