### ISSUE TITLE
Creating a survey application using Strapi and react.js [SUBMIT]

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#574]
**My resource**

Hello 👋 

I will like to create a survey application using Strapi for the backend and react.js for the frontend.

Outline

Introduction
Prerequisite
What is Strapi
What is React Js
installation of strapi
installation of  react.js
reasons for survey application 
features of the application
building the survey app
Conclusion

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @popoolatopzy can you please expand on the features of the application? what will it include the first 7 points in the outline above should be very brief, please expand on the features aspect.

**Comment by popoolatopzy** [comment]
@ShadaW11 the features of the application  will include:

Rating scales
random questions
Yes or No questions
localized question

**Comment by Popoolayemi** [comment]
Hello  @ShadaW11  sorry for the delay on this article, I missed the notification, but am almost done with the article draft which will be ready before  Wednesday this week. 
Can I still submit the draft?

**Comment by popoolatopzy** [comment]
Hello @ShadaW11 sorry for the delay on this article, I missed the notification, but am almost done with the article draft which will be ready before Wednesday this week.
Can I still submit the draft?

**Comment by ShadaW11** [comment]
@popoolatopzy I did not know that you are still working on this, can you please expand your tutorial using a few of the plugins available in our marketplace? https://market.strapi.io

**Comment by popoolatopzy** [comment]
Alright, I'll do that

**Comment by ShadaW11** [comment]
@popoolatopzy Perfect, please let me know which plugins you plan on using? and what will they bring to the tutorial?  Also do you have an estimation on when it will be ready?

**Comment by popoolatopzy** [comment]
I'll make use of 
**DeepL** : the plugin will be use to translate the survey questions to different languages.
**Graphs Builder**: this plugin will be use to analyzing the  answered survey questions in a graph form at the strapi dashboard 

The article  draft will be ready  before june 3

**Comment by popoolatopzy** [comment]
Hi, any updates on this draft?

**Comment by popoolatopzy** [comment]
Hello @PaulBratslavsky , any updates on this draft?

**Comment by dessireugarte** [comment]
Hello @popoolatopzy 👋
The article was posted today on the Strapi blog https://strapi.io/blog/creating-a-survey-application-using-strapi-and-react-js

**Comment by dessireugarte** [comment]
Hello @popoolatopzy 👋
Just wanted to confirm you submitted your invoice and got your payment?

**Comment by popoolatopzy** [comment]
@dessireugarte ,Yes I've received the payment. Thank you 😊
