### ISSUE TITLE
[SUBMIT] Building and deploying a grocery list application with svelte and Strapi on Netlify

### ISSUE THREAD

**Issue by icode247** [strapi/community-content#575]
**My resource**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @icode247 can you please share what you have in mind in an outline? technical features and overall app functionalities.

**Comment by icode247** [comment]
### Quick Summary:
According to the documentation
_Svelte is a radical new approach to building user interfaces._

In this tutorial, the reader will learn how to build and deploy grocery list application on Netlify with Svelte, and Strapi. They will apply the knowledge from this tutorial to combine Strapi and Svelte to build web applications.

### Goal:
By the end of this tutorial, the reader will understand how to build and Deploy Strapi and Svelte applications on Netlify. They will know how to set up a Strapi application, Fetch, Create, Update, Delete data from a Strapi with Svelte.

### Outline:

- Introduction to Headless CMS
- Why use Strapi
- What is Svelte
- Create a Strapi Project
- Create Content Types
- Create Svelte Project
- Install dependencies
- Creating routes
> - Items route
> - Add  item route
> - Update Item route
> - Delete Items route
- Testing our application
- Conclusion

**Comment by icode247** [comment]
Hello, @ShadaW11 the outline is ready.

**Comment by ShadaW11** [comment]
Hello @icode247 thank you, we will put it on hold for a few days. Would you be able to help us update our current tutorials with v4? https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d? Best

**Comment by vcoisne** [comment]
Hi @icode247 thanks for the outline. However, at this time we're not looking for intro-level Svelte tutorials as we already have some published on our blog and are prioritizing more advanced tutorials. Closing for now.
