### ISSUE TITLE
what is new in strapi v4 [SUBMIT]

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#576]
**My resource**

Hello 👋 

I'll like to write on new strapi v4 features.

Outline

- Introduction
- overview of strapi v3
- overview of strapi v4
- installation of strapi v4
- features of strapi v4
- getting started with strapi v4
- Conclusion

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @popoolatopzy great idea, but we will have to put it on hold a few days. We would like to have a big part of our tutorials updated, would you be able to help us with that? https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d

**Comment by popoolatopzy** [comment]
Hello @ShadaW11 , how are you doing?

can I go ahead and start working on this topic

**Comment by ShadaW11** [comment]
Hello @popoolatopzy we are still focusing on updating our tutorials with v4, it would be great if you can help us with that. Then hopefully in a week or two, we will resume to creating new articles.

**Comment by malgamves** [comment]
hey @popoolatopzy you can go ahead with this. 

I'd like to know what specific differences you'll point out between v4 and v3.

**Comment by popoolatopzy** [comment]
Hello @malgamves this is the link to the article draft, 
https://www.dropbox.com/scl/fi/dltl4pqw7fetcmvyy75io/What-is-new-in-strapi-v4.paper?dl=0&rlkey=z1b4uertx58gy8b2xuha13vou

**Comment by malgamves** [comment]
Thanks, we'll have this reviewed @popoolatopzy

**Comment by popoolatopzy** [comment]
Any update  on this article

**Comment by popoolatopzy** [comment]
Hello @malgamves , any updates on this article?

**Comment by PaulBratslavsky** [comment]
@popoolatopzy  we have many articles in the pipeline, and a release cadence to make sure that we publish articles following our content calendar and not all at once. This is usually the main reason why there is a wait from time reviewed to the time published. @TiaraOluwanimi
