### ISSUE TITLE
How to  design suitable content for your audience [SUBMIT]

### ISSUE THREAD

**Issue by xTrilton** [strapi/community-content#577]
Title: How to design suitable content for your audience

In this article, you will learn how to optimize your content for your targeted audience and how to design content with the customer’s needs in mind.

We will cover the following points:

1. Creating a target audience and content strategy.
2. Enriching content by using Strapi, a headless CMS.
3. Improving content by using analyzed customer feedback.
4. Designing content with the customer’s needs in mind.
5. Consistently using the same design pattern.
6. Screening content and removing irrelevant content.
7.  Creating clear and simple content. 
8. Conclusion

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @xTrilton we have paused on the new articles for a few weeks and are looking to update our current tutorials with v4 that we released yesterday. Feel free to help us update our articles here: https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d

**Comment by PaulBratslavsky** [comment]
Going to close this due to inactivity. Feel free to reach out to me with any questions that you may have.
