### ISSUE TITLE
[SUBMIT]

### ISSUE THREAD

**Issue by Saintdavidking** [strapi/community-content#582]
**My resource**

Hello 👋 

I will like to write on this topic **When and how should headless CMS be used?**

Outline:

- Introduction
- what is a headless CMS
- How do I choose the right headless CMS?
- overview of strapi (as an example of headless CMS)
- how to setup strapi 
- benefits of using headless cms
- Use cases for Headless CMS
- when to use headless CMS
- how to use headless CMS
- conclusion
 
**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @Saintdavidking thank you for the above outline. Unfortunately, we have already a few similar articles with similar topics already published on our blog. I invite you to take a quick look and hopefully propose some new outline. It would be great working with you.
