### ISSUE TITLE
[SUBMIT] How to create, extend, and change a content data model in Strapi

### ISSUE THREAD

**Issue by Saintdavidking** [strapi/community-content#583]
My resource

Hello 👋

**### How to create, extend, and change a content data model in Strapi** 

Outline:

Introduction
Overview of Strapi
installation of strapi
what is Model
how to create a model in strapi
how to extend a model in strapi
how to change a content data model using strapi
components and relation in strapi
Conclusion

What do you all think?
heart I love it!
rocket I can help you!

**Comment by ShadaW11** [comment]
Hello @Saintdavidking thank you for sharing the outline. I am afraid that we have a lot of articles already published on our blog around this topic. It would be great to have you write some posts for us. Could you pitch new top ideas?

**Comment by Saintdavidking** [comment]
alright but i searched before pitching out this topic and i feel there are no article on the blog that talks about it this way

**Comment by Nabellaleen** [comment]
Hi,
None of the published articles nor the documentation talk about "changing" a data model in Strapi ; always creating and extending, but never editing it later (with necessary migrations, ...).

It's really missing.
