### ISSUE TITLE
[UPDATE OUTDATED CONTENT] food delivery app

### ISSUE THREAD

**Issue by powerlesbian** [strapi/community-content#585]
I've been trying to follow your food delivery app tutorial.  the backend doesn't build.  The front end next-apollo imports are broken and won't compile. Could you please help by updating the tutorial.

**Comment by ShadaW11** [comment]
Hey @powerlesbian  We apologise for that and doing our best to update the tutorials as soon as possible. I will ping you here once the update is released.

**Comment by ShadaW11** [comment]
The updates on this tutorial will be made here - https://github.com/strapi/community-content/issues/735
