### ISSUE TITLE
[TOPIC] Content Modeling Best Practices 

### ISSUE THREAD

**Issue by vcoisne** [strapi/community-content#59]
**My Request**

Best practices for building and managing your Strapi content models, field management, etc

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by hannydevelop** [comment]
Hello @malgamves and @Mcastres can I work on this topic? I could turn in a draft by 16/11/2020

**Comment by Mcastres** [comment]
That would be great!
Can you tell me more about what you'll be working on exactly? What is going to be you approach for this?

**Comment by hannydevelop** [comment]
This article would explain the best practices the target audience need to consider while creating and managing their Strapi content models. First, I would introduce the target audience to the different model types briefly and would go on to explain when they should use content modeling and the best practices to consider whilst using content modeling.

This article would span the following section:

**Introduction**
**Strapi Modeling Types**
**Implementing Content Type's Modeling**
**Conclusion**

Implementing content type modeling will consist of code samples and guides for the target audience to successfully create their models and guides on how to create and manage models efficiently.

**Comment by malgamves** [comment]
Sounds good @hannydevelop - looking forward to reading the draft.

**Comment by hannydevelop** [comment]
Hello @malgamves, @Mcastres I may have to move submitting this article draft to a weeks time, got caught up with something.
Thanks for understanding!

**Comment by malgamves** [comment]
Hey @hannydevelop - that's alright. Let u know if there's anything we can help with.

**Comment by Mcastres** [comment]
Hey @hannydevelop, just checking if there is any new about this :)
