### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by malwayson** [strapi/community-content#591]
Can we have a tutorial on how to customize admin ui for strapi v4. eg: edit home page, auth pages, sidebar etc..

**Comment by Marktawa** [comment]
I would like to write a tutorial for this request.

**Comment by PaulBratslavsky** [comment]
@Marktawa I know it has been a while are you still interested in this topic?

**Comment by Marktawa** [comment]
Hi @PaulBratslavsky 
I'm working on #670. If no one else wants it, I will work on it after I complete #670.

**Comment by PaulBratslavsky** [comment]
@Marktawa I send a note to check the invoice status for #670 if you still like to pick up this issue you can do so.  Just let me know if you want to take it.  It will be great to see an article on customizing the Admin UI, It can be done by using our extension system, or you can also use patch-package to override the code in the node modules.

**Comment by Marktawa** [comment]
Hi @PaulBratslavsky 

Ok great. Let me work on an outline for this article. I assumed there were tutorials that covered customization of the Admin UI.
As for #670, the matter has been resolved. So no worries.

**Comment by vcoisne** [comment]
Closing this as we already have tutorial on the topic.
