### ISSUE TITLE
[UPDATE OUTDATED CONTENT] 

### ISSUE THREAD

**Issue by onedawa** [strapi/community-content#593]
**Description**
<!--
[Hello 👋 
This tutorial is outdated. The files are not where they are supposed to be
**[Link of the content](https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi)**

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!](https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi)

**Comment by derrickmehaffy** [comment]
No context or remotely any effort put into this issue, closed.
