### ISSUE TITLE
[UPDATE OUTDATED CONTENT] - How to change the WYSIWYG editor in Strapi

### ISSUE THREAD

**Issue by chunkingz** [strapi/community-content#595]
**Description**
Please update the article - How to change the WYSIWYG in Strapi

I had tried following the tutorial link below, but I couldn’t as much of the folder structure and code has changed.

**Link of the content**
[How to change the WYSIWYG in Strapi](https://strapi.io/blog/how-to-change-the-wysiwyg-in-strapi)

**Comment by ShadaW11** [comment]
Hello
