### ISSUE TITLE
Unable to deploy Strapi v4 to Heroku using the old documentation

### ISSUE THREAD

**Issue by Kunalgoel9** [strapi/community-content#604]
**The concerning content**

**Issue**

I just completed my first project in Strapi v4 but I am unable to deploy it to heroku 
can anyone help me with this?

**Comment by ShadaW11** [comment]
@Kunalgoel9 we have updated the tutorial with v4, I hope that helps

**Comment by Kunalgoel9** [comment]
this error is coming again

remote: ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/design-system/Carousel' in '/tmp/build_7a488f6f/node_modules/@strapi/plugin-upload/admin/src/components/MediaLibraryInput/Carousel'

**Comment by ShadaW11** [comment]
can you please leave a comment under the article and please add the error above so the author can help you resolve it? https://strapi.io/blog/deploying-a-strapi-api-on-heroku

**Comment by Kunalgoel9** [comment]
I have commented on the article

**Comment by zaracooper** [comment]
@ShadaW11 could I work on this?

**Comment by ShadaW11** [comment]
@zaracooper apologies for the late reply, in fact the article has already been updated to v4.
