### ISSUE TITLE
[SUBMIT]Publication workflow "workaround" in Strapi 

### ISSUE THREAD

**Issue by Saintdavidking** [strapi/community-content#605]
**My resource**

Hello 👋 

Topic: Publication workflow "workaround" in Strapi 

Description: 

What is a Publication Workflow, and how does it work? The term " workflow" refers to all of the actions and procedures that must be completed in order to obtain the desired end result. The successful dissemination of high-quality content is the final step in publishing. As a result, a publishing workflow encompasses everything that must occur in order for a publication to take place.

Outline:
Introduction.
Overview of Strapi.
What is a Publication workflow?
Importance of Publication workflow: {
RBAC.
Dynamic Zones.
Providers.
Draft and Publish.
}
Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Hello @Saintdavidking a similar issue is open, I will be providing you the right to write this content if the other author doesn't get back to me in the next day or two. Thank you so much.

**Comment by Saintdavidking** [comment]
Alright, but when will the issues be updated for other options

**Comment by PaulBratslavsky** [comment]
I am closing this because it is similar to this topic which is being worked on. [TOPIC] Publication workflow "workaround" in Strapi #58
