### ISSUE TITLE
[UPDATE OUTDATED CONTENT] E-commerce website with Nuxt.js, GraphQL, Strapi and Stripe

### ISSUE THREAD

**Issue by rowild** [strapi/community-content#606]
**Link of the content**
https://strapi.io/blog/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-setup-part-1-7

**What do you all think?**
👍 Nice!!!!
❤️ I love it!!!!
🚀 I can help you!

You kindly mention that we can report outdated things, since software keeps evolving and tutorials should be updated. There is not much in this case, except that the given link to chapter 2 in the bottom of the tutorial is wring. Tt should be:

https://strapi.io/blog/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-restaurants-list-part-2-7

This might be true for the upcoming chapters, too, but I haven't worked that far yet.

Thank you for that tutorial!

**Comment by rowild** [comment]
As a side note: the animated gifs are most likely a lot of work, but they do not help at all. They are too fast and too small. It would be a lot better to have separate images that could be enlarged.

**Comment by J-rayX** [comment]
Hi @rowild @ShadaW11 ,
I could get up this series and try to update it.

Asides from updating the content, the URL routing needs an update also, as I pointed to @vcoisne earlier on. 
If you notice, only the 2nd part is available at strapi.io/blog/. The other parts are still on blog.strapi.io.

**Comment by vcoisne** [comment]
thanks @J-rayX we have already updated the URLs :) @ShadaW11 will get back to you with regard to updating that series to v4 :)

**Comment by J-rayX** [comment]
> thanks @J-rayX we have already updated the URLs :) @ShadaW11 will get back to you with regard to updating that series to v4 :)

Oh, great! Thanks for the update about the URLs @vcoisne.

**Comment by ShadaW11** [comment]
@J-rayX Indeed, the article is updated by our community and is under review. The update should be published in the next week or two.

**Comment by vcoisne** [comment]
This is done. https://strapi.io/blog/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-restaurants-list-part-2-7
