### ISSUE TITLE
[SUBMIT]

### ISSUE THREAD

**Issue by Muhtoyyib** [strapi/community-content#609]
Topic: 

Javascript Modules: Complete beginners’ guide

Summary:
  Javascript modules were created to make javascript code easy to use, organized and make it very easy to maintain. They are also called ES Module or ECMAScript Modules. In this article, I will cover :

Outline
What is a module?
Introduction to ES Modules. Why do we use them?
How to use ES Modules. Step by step guide
What are other modules used in Javascript?
Conclusion
.

What do you think about it?

**Comment by ShadaW11** [comment]
@Muhtoyyib Thank you for pitching the outline, would you mind creating something more relevant to Strapi?

**Comment by Muhtoyyib** [comment]
Yes I would

**Comment by malgamves** [comment]
Thanks for your submission, will close this issue now :)
