### ISSUE TITLE
[REQUEST] Add Traversy Media Strapi.js Tutorial

### ISSUE THREAD

**Issue by hugocarreiracosta** [strapi/community-content#61]
Add Strapi.js tutorial made by Traversy Media on https://strapi.io/tutorials.

Link:  https://www.youtube.com/watch?v=6FnwAbd2SDY

**Comment by hugocarreiracosta** [comment]
I created the PR for adding  #62

**Comment by Mcastres** [comment]
Thanks for your contribution Hugo :)
