### ISSUE TITLE
 [UPDATE OUTDATED CONTENT] A Deep Dive into Strapi GraphQL

### ISSUE THREAD

**Issue by vcoisne** [strapi/community-content#611]
https://strapi.io/blog/a-deep-dive-into-strapi-graph-ql

Hello 👋

Please explain which article or tutorial has an issue.
--> Its on v3

**Issue**
Describe the issue
--> I think v4 introduced a fair amount of graphQL related changes

**Comment by zaracooper** [comment]
@ShadaW11 could I update this?

**Comment by ShadaW11** [comment]
@zaracooper Do you have time to work on this?

**Comment by zaracooper** [comment]
Sorry @ShadaW11. No, not at this time.

**Comment by PaulBratslavsky** [comment]
I am keeping this open since this is related to an initiative around GraphQl best practices that I am looking to do in the near future.  But if anyone wants to pick this article up before me, you can do that as well.  At the moment I am working on Strapi v3 to v4 migration content.

**Comment by Oluwoleopeyemi** [comment]
Hello @dessireugarte and @PaulBratslavsky , I will like to update  this article

**Comment by Oluwoleopeyemi** [comment]
Hello @dessireugarte and @PaulBratslavsky , I will  like to update  this article

**Comment by dessireugarte** [comment]
Hello @Oluwoleopeyemi 👋
Have you worked on Strapi articles or v4 updates?
If yes, please go ahead. Otherwise, take a look at the guidelines [here](https://strapi.io/write-for-the-community). Please share the draft when it is ready, so @PaulBratslavsky and @TiaraOluwanimi review it.

**Comment by Oluwoleopeyemi** [comment]
Alright, thank you.

**Comment by Oluwoleopeyemi** [comment]
Hi @dessireugarte and @TiaraOluwanimi here is the link to this article update

https://www.dropbox.com/scl/fi/agg9qw3u6xairc99tr6u4/Untitled.paper?dl=0&rlkey=mevmjtcc4mcfyhc0cqvd5p0wo

**Comment by dessireugarte** [comment]
Hello @Oluwoleopeyemi 
We will review this draft soon and get back to you. Thank you!

**Comment by Oluwoleopeyemi** [comment]
Hi @dessireugarte and @TiaraOluwanimi 
Any update on the article?

**Comment by Oluwoleopeyemi** [comment]
Hi @dessireugarte and @TiaraOluwanimi
Any update on the article?

**Comment by dessireugarte** [comment]
Hello @Oluwoleopeyemi  👋
Just wanted to let you know that your article will be published around the second week of December. I'll let you know if we need any changes or when it is published!

**Comment by dessireugarte** [comment]
Hello @Oluwoleopeyemi 👋 I left a comment on the draft. Could you please take a look?

**Comment by PaulBratslavsky** [comment]
@Oluwoleopeyemi while reviewing your article I saw that the Vue JS app has not been updated to use Strapi v4.  

Here is the change I had to make in the app to be able to render the post on screen, but you will have to do all the additional changes to reflect working with the Strapi v4 graphql response structure. 

@dessireugarte this article is not ready to publish until the changes are made.

@Oluwoleopeyemi let me know when you are done and please provide links to both repos. 

Strapi v4 projerct
Updated Vue Js project. Thank you.

``` javascript

<template>
  <div>
    <div class="container">
      <div class="container">
        <div class="customPadding">
          <div class="row">
            <div class="col-sm">
              <div class="customCard">
                <h1
                  style="
                    font-size: 3rem;
                    text-align: center;
                    padding-bottom: 6rem;
                  "
                >
                  All Blog Post
                </h1>
              </div>
              <div v-for="blog in blogs.data" :key="blog.id">
                <router-link
                  class="nav-link"
                  :to="{ path: '/blog/' + blog.id }"
                >
                  <div class="container">
                    <div class="customCard">
                      <div
                        class="
                          card
                          shadow-lg
                          p-3
                          mb-5
                          bg-white
                          rounded
                          mr-5
                          ml-5
                        "
                      >
                        <div class="card-head" style="padding: 4rem">
                          
                          <h1 style="font-size: 6rem">
                            {{ blog.attributes.Title }}
                            <hr />
                          </h1>
                        </div>
                        <div class="card-body text-center">
                          <p style="line-height: 26pt">{{ blog.attributes.Body }}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </router-link>
                <br />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import gql from "graphql-tag";
export default {
  name: "HelloWorld",
  data() {
    return {
      blogs: [],
    };
  },

  apollo: {
    blogs: {
      query: gql`
        query {
          blogs {
            data {
              id
              attributes {
                Title
                Body
              }
            }
          }
        }
      `,
    },
  },
};


</script>

<style>
.customPadding {
  margin-top: 12rem !important;
  margin-bottom: 12rem !important;
  /* padding: 4rem; */
}
</style>


```

**Comment by Oluwoleopeyemi** [comment]
Okay, I will work on it

**Comment by PaulBratslavsky** [comment]
@Oluwoleopeyemi just wanted to check if you are still working on this article?

**Comment by Oluwoleopeyemi** [comment]
Hi
I am still working on the article
But I having some issue, I'd get back to you soon.

Best Regards
Emmanuel

**Comment by Oluwoleopeyemi** [comment]
Hi
@PaulBratslavsky @dessireugarte 

I'm done with the article and I have address the issue.
Sorry for the delay,
Here is a link to a new Dropbox that contains the article.


https://www.dropbox.com/scl/fi/00bkwrqjy0ons6pnb2qu7/A-Deep-Dive-into-Strapi-GraphQl.paper?dl=0&rlkey=w93xcgm8azej63y8xpqhstajr

**Comment by dessireugarte** [comment]
Hello @Oluwoleopeyemi 👋 
Thanks for updating it. Could you please also update the covers with the new template? 
We will review the article and get back to you soon.

**Comment by PaulBratslavsky** [comment]
@Oluwoleopeyemi I noticed some additional changes.  I left comments in the dropbox post.  Thank you.

**Comment by Oluwoleopeyemi** [comment]
Hi @PaulBratslavsky @dessireugarte 
I have made the necessary changes, I'm looking forward to your feedback

Best,
Emmanuel

**Comment by dessireugarte** [comment]
Hello @Oluwoleopeyemi 
The images are still not available and the covers should be updated.

**Comment by Oluwoleopeyemi** [comment]
Hello
I have updated both the image and the cover image initially, but i don't
know if there is a new cover image

**Comment by PaulBratslavsky** [comment]
@Oluwoleopeyemi I added some notes in the dropbox link.

**Comment by Oluwoleopeyemi** [comment]
@PaulBratslavsky @dessireugarte 
I have addressed the issue, please check it out.

Best
Emmanuel

**Comment by Oluwoleopeyemi** [comment]
@PaulBratslavsky @dessireugarte 
Any update on the article?

**Comment by PaulBratslavsky** [comment]
@Oluwoleopeyemi I had made some comments, doesn't see that you addressed all of them yet.  Let me know if you have any questions.  https://www.dropbox.com/scl/fi/00bkwrqjy0ons6pnb2qu7/A-Deep-Dive-into-Strapi-GraphQl.paper?dl=0&rlkey=w93xcgm8azej63y8xpqhstajr.

**Comment by Oluwoleopeyemi** [comment]
Hi @PaulBratslavsky 

I have addressed the issue and updated the repo. Please check it out and let me know your feedback.

**Comment by dessireugarte** [comment]
Hello @Oluwoleopeyemi! Could you please share your email address with me so I can send you access to Dev.to? Also, could you share with me your Hashnode user?

**Comment by Oluwoleopeyemi** [comment]
Hi @dessireugarte 

Thanks for reaching out, here is my email address : oluwoleopeyemi31@gmail.com 
And my hashnode account: oluwoleopeyemi1.hashnode.dev

**Comment by dessireugarte** [comment]
Your article update is [live](https://strapi.io/blog/a-deep-dive-into-strapi-graph-ql)! 🎉
You can now publish the article on [Dev.to](http://dev.to/) and Hashnode. 

To ensure you don't miss any comments on your post, please register on our forum by clicking the discussion link at the bottom of your article. Please follow our [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice for your work. 

You should register once as an "Individual Vendor," please fill out [this](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform) form. If you have any questions about the form, please do not hesitate to ask. Please note that in the W-8BEN form, section 5 is not mandatory, and sections 6a & 6b are only required if you have a tax number in your country. If you already did this step, there is no need to do it again. 

To receive payment for your work, you should submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform).

If you would like to promote your article, we have some [templates](https://github.com/1645b77a97a640d2a32047297b6bc3f0) that can help you get started! Please feel free to reach out to @vcoisne if you have any further questions.
