### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Web scraping with Strapi

### ISSUE THREAD

**Issue by zepxtor** [strapi/community-content#616]
**Description**
Please could you update the article "Web scraping with Strapi", it does not work anymore due to v4 changes.

Thank you!!

**Link of the content**
https://strapi.io/blog/web-scraping-with-strapi

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
@zepxtor Yes, definitely we have it in our pipeline

**Comment by nimishbongale** [comment]
Can I potentially take this up @ShadaW11?

**Comment by zepxtor** [comment]
@ShadaW11 could @nimishbongale update it? Thanks!

**Comment by nimishbongale** [comment]
> Hello @nimishbongale I apologise for the delay, are you still interested in updating this article?

I'm going to have to look back at this, but if anyone else is willing to do the same they can take this up!

**Comment by ShadaW11** [comment]
@nimishbongale thank you for the feedback

**Comment by PaulBratslavsky** [comment]
@nimishbongale just wanted to check in and see if you are still interested in this topic?

**Comment by nimishbongale** [comment]
> @nimishbongale just wanted to check in and see if you are still interested in this topic?

Not atm, but I can try pulling in someone who might be able to!

**Comment by unforswearing** [comment]
@ShadaW11 @PaulBratslavsky 

I would like to work on this topic -- is it still available for updating?

**Comment by zepxtor** [comment]
Hello @ShadaW11 @PaulBratslavsky

Would love to see this content updated, but will never be if it takes so long to reply.

Any chance @unforswearing could work on this content?

Thanks!

**Comment by unforswearing** [comment]
Hello @ShadaW11 and @PaulBratslavsky - Wanted to check in one last time about updating this content. Do you still need help with this?

**Comment by PaulBratslavsky** [comment]
@unforswearing sorry for the super late response, been going through the older issues and just saw you responded. If you are still interested let me know.

**Comment by unforswearing** [comment]
@PaulBratslavsky No worries, thanks for the reply. Yes, I am still available to work on this -- let me know how I can get started!

**Comment by dessireugarte** [comment]
Yes, you can get started @unforswearing

**Comment by dessireugarte** [comment]
Hello @unforswearing 👋
Are you still working on this topic? Otherwise, we will assign it to another author.

**Comment by unforswearing** [comment]
Hi @dessireugarte, I am still working on this. I can have the update complete by mid-week next week.

**Comment by dessireugarte** [comment]
Hello @unforswearing 👋 Just wanted to check how are you doing with this update?

**Comment by dessireugarte** [comment]
Hello @unforswearing! Since we didn't have any answer, we will close this issue.

**Comment by unforswearing** [comment]
@dessireugarte I understand. I have been traveling to attend to a family emergency that required most of my time the past few months, sorry for failing to reply before.

**Comment by dessireugarte** [comment]
No worries @unforswearing! Feel free to add another topic if you are interested in the future!
