### ISSUE TITLE
Create Custom API in Strapi

### ISSUE THREAD

**Issue by bhambrij-upwork** [strapi/community-content#618]
**My Request**

I am new to Strapi, would like to create custom API's for reporting purpose on content built using strapi content builder in Strapi.

Please help with Custom API documentation

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by enosemi** [comment]
Hi @bhambrij-upwork  I will like to take this topic, I will send an outline to you soon

**Comment by vivmagarwal** [comment]
Hi, @ShadaW11 I can take up the task of writing an article on this topic. 

**Outline:**
- Introduction
- Creating custom Routes in Strapi
- Creating custom Controllers in Strapi
- Querying data from multiple collections
- Filtering Data
- Conclusion

**Comment by malgamves** [comment]
Hey @vivmagarwal 

I love the idea! Go for it. Would love to see this.

**Comment by vivmagarwal** [comment]
@malgamves here it is: https://www.dropbox.com/scl/fi/je5rbogod9rt716cs9nb8/How-to-Create-a-Custom-API-End-point-in-Strapi.paper?dl=0&rlkey=5er3brsx1g0qt1ss40oa817pi 🚀

**Comment by ShadaW11** [comment]
Hello @vivmagarwal your article will be published soon, ill get back to you once it is posted on the blog and thank you.

**Comment by ShadaW11** [comment]
Hello
