### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Build a Real-time Chat Forum using Strapi, Socket.io, React and MongoDB

### ISSUE THREAD

**Issue by oabeleda** [strapi/community-content#619]
**Description**

**Link of the content**
https://strapi.io/blog/how-to-build-a-real-time-chat-forum-using-strapi-socket-io-react-and-mongo-db

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by nextrapi** [comment]
This guide can not be updated to v4 as Strapi does not support mongoDB anymore.

**Comment by ShadaW11** [comment]
Hello @nextrapi interested, would you share what you have in mind?
