### ISSUE TITLE
My article about how to Create an ecommerce Website using React.js + Strapi + SnipCart

### ISSUE THREAD

**Issue by ihssanehatim** [strapi/community-content#626]
[**Create your ecommerce Website using React.js + Strapi + SnipCart in under an hour**](https://brightshine.io/create-your-ecommerce-website-using-react-js-strapi-snipcart-in-under-an-hour/)

**Comment by malgamves** [comment]
Hey @ihssanehatim this is pretty cool! If you'd like to update your article to work with v4, we can publish it on our blog 🎊

**Comment by ihssanehatim** [comment]
@malgamves can you check now?

**Comment by ihssanehatim** [comment]
Please, have you cleared the cache on the website (you can refresh mutliple times or just ctrl+refresh) , this is what I have now :
<img width="879" alt="Screen Shot 2022-02-24 at 14 47 27" src="https://user-images.githubusercontent.com/52088496/155536225-6a9f1d10-f625-42f4-bfa9-c80b79d65cfb.png">

**Comment by ihssanehatim** [comment]
Thank you @malgamves 💯 , sure I'll keep you posted if I have any;
May I have the link once it's published on the blog ?

**Comment by malgamves** [comment]
hey @ihssanehatim sorry for the misquote, I meant that we only publish content on our blog that hasn't been published anywhere else so we can't publish your post.

**Comment by ihssanehatim** [comment]
Hi @malgamves no worries as all the ideas I get I publish them on my own blog; I just loved to share with you too, so more people get to read it, thank you anyways I'll close the issue 😄
