### ISSUE TITLE
[SUBMIT] Content System Principles

### ISSUE THREAD

**Issue by Aurelsicoko** [strapi/community-content#63]
**My resource**
Atomic, molecular, and component structures use to be more and more common. These principles are used for the graphic (design system) and development (components). We can apply these to content modeling. I would like to write a kind of essay to explain our vision of content modeling. How powerful it can be, how easy it can be maintained, and more. It's a conceptual article to explain the foundations of the vision to become one of the most flexible and customizable open-source headless CMS.

I already started a [draft](https://www.notion.so/strapi/Managing-Content-at-scale-8f2cbcbd3a6f4f659dccfbcdf6484ee0) with very basic concepts.

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Hey @Aurelsicoko, any update on this?
