### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to create an import content plugin (part 1/4)

### ISSUE THREAD

**Issue by foxleigh81** [strapi/community-content#633]
**Description**

**Link of the content**

https://strapi.io/blog/how-to-create-an-import-content-plugin-part-1-4

**Comment by ShadaW11** [comment]
@foxleigh81 thank you for reporting it. We are working on updating our content.

**Comment by ayhid** [comment]
@ShadaW11 I am interested in the article can I make the updates or it has to be the original author who makes it ?

**Comment by ShadaW11** [comment]
Hello @ayhid No need to have the original author work on this. You can work on this article. However, if it is your first article. Please make sure that you registered [here](https://strapi.io/write-for-the-community)

Than please go over the [v4 writers guide](https://www.notion.so/strapi/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d)

**Comment by hubertnare** [comment]
Hie Shada, I am working on updating this article.

**Comment by ShadaW11** [comment]
@hubertnare please go ahead and start working on this.

**Comment by PaulBratslavsky** [comment]
@hubertnare just wanted to check in if you are still working on this?

**Comment by hubertnare** [comment]
Hey @PaulBratslavsky,

unfortunately, I will not be able to continue working on this.
