### ISSUE TITLE
[SUBMIT] Realtime chat application using Strapi, Next, Socket.io, and PostgreSQL

### ISSUE THREAD

**Issue by divofred** [strapi/community-content#637]
**My resource**

**Introduction**

Sending and receiving text messages in recent times are frequently done online and in real-time. Text messages in real-time chat applications are sent and received immediately, depending on the speed of the router. Realtime messaging is very essential in chat applications and Socket.io grants us this privilege.

**Goal**

This article would be focused on integrating Strapi with PostgreSQL and Socket.io. It will be a modification of [How to Build a Real-time Chat Forum using Strapi, Socket.io, React, and MongoDB](https://strapi.io/blog/how-to-build-a-real-time-chat-forum-using-strapi-socket-io-react-and-mongo-db) article. We will implement authentication and use Strapi V4 features.

**Overview**

Users will be authenticated using JSON Web Token. After users have been authenticated, they will be redirected to their specified groups. Users within a specific group can communicate with one another. All messages will be stored in PostgreSQL using Strapi as CMS.

**Topic of Interest** 

- Strapi
- Web Sockets
- Next
- PostgreSQL

**Outline**

- Prerequisites
- Getting Started
  - Setting up PostgreSQL
  - Setting up Strapi
  - Setting up Socket.io
  - Setting up our Frontend
- Frontend
  - Refactoring our Next App
  - Creating Routes
  - Creating the Sign-up/Sign-in Route
  - Connecting the Next to the Server
- Fetching data from Strapi APIs
- Feature 1: Enable a user to join a room
- Feature 2: Conversations
- Feature 3: Show which users are online
- Feature 4: Notify users if someone leaves the chat room
- Handling CORS
- Conclusion
- Resource

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open-source, or jam stack
- [x] Web socket, Database 

**What do you all think?**
❤️ You love it?
🚀 I can help you!

**Comment by ShadaW11** [comment]
Hello @divofred thank you for pitching your article interesting outline, im afraid we might have something similar already published in our blog, can you please take a look and confirm your article will have unique features?

**Comment by divofred** [comment]
Hey @ShadaW11.

I took a look at a similar article like [this](https://strapi.io/blog/how-to-build-a-real-time-chat-forum-using-strapi-socket-io-react-and-mongo-db)
 
**Uniques Features**
- Authentication
  - Email Auth.
  - Token Auth.
  - Role Auth.
- A SQL database (PostgreSQL).
- Implementing Strapi V4 features.

If there are more features you will love to add, please do so.

Looking forward to hearing from you,

_Fredrick Emmanuel_.

**Comment by malgamves** [comment]
Hey @divofred awesome, when will you have a draft?

**Comment by divofred** [comment]
Hey @malgamves,

The draft will be ready in 2-3 weeks.
What do you think?

**Comment by PaulRichez** [comment]
Hey @divofred, nice, I look forward, i need it :)

**Comment by divofred** [comment]
@malgamves @ShadaW11 Can I start working on the draft?

**Comment by malgamves** [comment]
hey @divofred how is this going?

**Comment by malgamves** [comment]
can't wait to see it

**Comment by divofred** [comment]
Hi @malgamves @ShadaW11,
I am done with the draft, I'm sorry for the delay. I encountered some challenges along the way.
I will send you the link to the draft today.

**Comment by ShadaW11** [comment]
@divofred Hey, thank you for the update, perfect 🤩 , looking forward to receiving it.

**Comment by divofred** [comment]
Phew @ShadaW11, the draft is ready😀.
[Here is the link to draft.](https://www.dropbox.com/scl/fi/s2wte12km5yhmr14s12th/Realtime-chat-application-using-Strapi%2C-Next%2C-Socket.io%2C-and-PostgreSQL.paper?dl=0&rlkey=uapbhop8ilnr94wi36p5d2ltu)

**Comment by ShadaW11** [comment]
Thank you @divofred someone from our team will review it asap

**Comment by divofred** [comment]
Thanks @ShadaW11.

**Comment by divofred** [comment]
Hello @TiaraOluwanimi @ShadaW11,
What's the next step?
Should I submit an invoice?

**Comment by divofred** [comment]
Hello @dessireugarte, Thanks for publishing the article. How would I send an invoice?

**Comment by divofred** [comment]
Hello @dessireugarte  @ShadaW11, Thanks for publishing the article. I've submitted an invoice.
