### ISSUE TITLE
[SUBMIT] Create a slug system in Strapi v4

### ISSUE THREAD

**Issue by cwray-tech** [strapi/community-content#638]
**My resource**

## Title: Create a slug system in Strapi v4
With the new UID field in V4 it is a lot easier to create a slug system in Strapi. I want to write an article sharing how to do that, as an update to the v3 guide in the Strapi Docs.

### Outline
- Background
- Strapi 3 Slug system
- Strapi v4 makes generating slugs easy
- Steps to generating slugs automatically in Strapi v4:
-- steps
- Using your slug on the frontend
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**

**Comment by cwray-tech** [comment]
@ShadaW11 @malgamves I have this article already written, so if you would like I can submit a pr with it for review.

**Comment by malgamves** [comment]
Hey @cwray-tech could you send a link to the dropbox and we'll get it reviewed!

**Comment by malgamves** [comment]
You can share it here @cwray-tech

**Comment by cwray-tech** [comment]
@malgamves https://www.dropbox.com/scl/fi/mftz8zn97i4bq2mx15c9f/Create-a-slug-system-in-Strapi-v4.paper?dl=0&rlkey=0b2qkdsdg2v1gi5b9u2rxized

Thank you!

**Comment by malgamves** [comment]
Awesome @cwray-tech someone is on it!

**Comment by ShadaW11** [comment]
Hello @cwray-tech your article will be published next week, I will reach out with a link once it is on our blog - thank you again

**Comment by cwray-tech** [comment]
@ShadaW11 sweet! Thank you 😊

**Comment by cwray-tech** [comment]
@ShadaW11 Could I see what the author information text says about me? If possible it'd be great to throw in a backlink to our company [Magnet Co](https://magnet.co).

**Comment by ShadaW11** [comment]
Hey @cwray-tech feel free to share any updated author info you have - https://strapi.io/blog/how-to-create-a-slug-system-in-strapi-v4

**Comment by cwray-tech** [comment]
@ShadaW11 Thank you! Could you update my title to be Senior Engineer at [Magnet Co](https://magnet.co)

If you can include the backlink that'd be great but no worries if no.

**Comment by ShadaW11** [comment]
Hello @cwray-tech I updated your title but unfortunately cannot add a backlink. I have also not received your invoice, please follow the guidelines in this link (FAQ section) https://strapi.io/write-for-the-community

**Comment by ShadaW11** [comment]
@cwray-tech Hello Chris, I tried reaching out via email but I havent heard from you. All articles that include a backlink are not compensated. Therefore, if you would like to have a backlink to Magnet Co in the article, the article will be considered a guest post and no need for an invoice. If you would like to get compensated for the article, please issue your invoice following our guidelines. The invoice received to my email does not follow the guidelines. More details here: (FAQ section) https://strapi.io/write-for-the-community

**Comment by cwray-tech** [comment]
@ShadaW11 I apologize! Which email do you have for me? You can use chris@solmediaco.com in the future.

About the backlink, that is fine. The rules have evidently changed since I wrote last year. I have a big favor to ask of you though. Could you update my bio to say Software Engineer at Soltech? I deeply appreciate it. 

About the invoice I will try to update. The issue is that I need to run this through my company for tax and accounting purposes. I cannot use the template, other than for the key parts of the invoice like address of Strapi, detail of the service, etc. We also had an issue last year with my bank not providing all of the details that are requested to be included in the invoice for payment. This may have changed so I will look into it. @malgamves should be familiar with that if he remembers, or the correspondence may be in his email. I will do my best to add those details though.
