### ISSUE TITLE
Installing strapi on Docker Compose

### ISSUE THREAD

**Issue by alemarengo** [strapi/community-content#639]
I followed the guide [here](https://strapi.io/blog/how-to-self-host-your-headless-cms-using-docker-compose)
but this is what the terminal shows:
`ERROR: no matching manifest for linux/arm/v7 in the manifest list entries`
I tried to install it on a Raspberry Pi 4B, with `mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnueabihf (armv8l) using readline 5.2`

**Comment by ShadaW11** [comment]
@alemarengo thank you for reporting the issue, can you please post it on the strapi forum or in discord and someone from the community or the team will help you out.
