### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by AlexColibri** [strapi/community-content#640]
**The concerning content**
https://strapi.io/blog/build-a-blog-with-react-strapi-and-apollo

**Issue**

**Comment by ShadaW11** [comment]
Hello @AlexColibri can you please clarify what the issue is? is it outdated?

**Comment by AlexColibri** [comment]
Yes, i think this not working with latest strapi version or query not
working with slug parameter. Is outdated

lun., 7 feb. 2022, 14:05 Shada ***@***.***> a scris:

**Comment by Mcastres** [comment]
This article has been updated with Strapi v4 but it will appear on our next website deployment :)
