### ISSUE TITLE
Topic: Understanding static HTML export in NextJS

### ISSUE THREAD

**Issue by Saintdavidking** [strapi/community-content#641]
**My resource**
Hello 👋 

Topic:  
Using Java + Strapi Vs Python + Strapi, what to choose and difference btw the two top programming language with Strapi .

Outline: 

> Introduction to Strapi
> Overview of Java
> Overview of Python
> why is choosing between Java and Python Important.?
> Why should python and java be compared?
> How can python and java be compared?
> Conclusion

**What do you all think?**

**Comment by malgamves** [comment]
Thanks for your submission, I don't think this content is relevant for our audience. I'll close the issue. Happy to re-open if you have a different idea.

**Comment by Saintdavidking** [comment]
OUTLINE:
 brief overview of HTML 
 Why use static HTML 
 Using static HTML import inNext.JS 
 Next.JS Static HTML Export Supported Features 
 Next.JS Static HTML Import nonvalid Features 
 Code Portability 
 SEO benefits 
 Improved First Paint Times
