### ISSUE TITLE
[SUBMIT] Implement Push Notification Building an Asset Manager using Strapi, Cron jobs, and Rest API

### ISSUE THREAD

**Issue by maxiggle** [strapi/community-content#642]
**My resource**

**Overview:**
> Push notification is user friendly and a necessary part of most popular applications today, ranging from mobile applications to web applications. With strapi cron jobs and REST API , we can build push notification for our applications.

**Goal** 
   In this tutorial, we will look at how we will implement notification in our asset manager application using cron jobs and RESTFUL 
   API. We will be able to add assets, remove assets, delete assets, update assets, log transactions and view logs.
  We will also look at how to configure and set up this Jamstack application.

**Prerequisites:**:
In other to follow this tutorial, you need:
- NPM
- Node.js
- React.js installed
- Tailwind css
- Axios

**Outline**

- Need for push notification
- React Router v6
- Setting up strapi
- Create content types
- Create collection
    - Assets
    - Log
    - Notification
- Adding assets
- Setting up roles and permission
- Dependencies for our frontend
    - Tailwaind css
    - Axios
- Building out our UI
    - Creating Routes
    - Implement Signup page
    - implement login page
    - implement navigation
    - Implement assets page
    - Displaying our assets
    - implement logs
    - implement assets notification
- Error handling
- Running and deploying testing our app

- **Conclusion**
- **Resources**

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by malgamves** [comment]
Super cool post @Maxiggle - when can you have a draft ready?

**Comment by Maxiggle** [comment]
Sorry for the late reply, I just got saw this reply.
I will get it ready by next week friday

**Comment by ShadaW11** [comment]
Hello @maxiggle apologies for the delay, your article will be published soon.

**Comment by maxiggle** [comment]
Alright
Thankyou

**Comment by maxiggle** [comment]
Hello @ShadaW11 , its been almost a week now since you said the article would be published.
Please what's going on?

**Comment by ShadaW11** [comment]
Hello @maxiggle thank you for being patient, we have a backlog of articles, so publishing your article can take time - up to 10 days. However, your article was published today. Feel free to issue an invoice. Thank you again for writing awesome articles and I hope you submit more soon.

**Comment by maxiggle** [comment]
Thank you @ShadaW11 
I have also sent my invoice
Thanks
