### ISSUE TITLE
Article Proposal - Powerful & Flexible Plugin Creation with Strapi v4 [SUBMIT]

### ISSUE THREAD

**Issue by vivmagarwal** [strapi/community-content#661]
**Powerful & Flexible way to create custom plugins with Strapi v4**

Over the last week, it took a lot of time to figure out most of the subtle changes in the way we create plugins in the new Strpai v4. I'd love to share my learnings.

**Outline**
- Introduction
- Important Developer API's
- Step by Step creating a custom Strapi Plugin
  - Routes
  - Controllers
  - Services
  - Settings API
  - Fields API
  - injectContentManagerComponent
  - 
- Resources
- Conclusion

**My content is**
- A Strapi How to article [Hands on]

**What do you all think?**
❤️ I love it!
🚀 I can help you!
🎥 Do you prefer a video or a written Article for the topic?

**Comment by malgamves** [comment]
hey @vivmagarwal this is awesome! What plugin will you build? Love how you're covering all these aspects!

**Comment by vivmagarwal** [comment]
Hi, @malgamves I'm working on updating the following blog: https://strapi.io/blog/how-to-build-a-strapi-custom-plugin. So the plugin would be allowing users to send an email directly from the plugin page. I will add a few more features to the plugin to introduce some more APIs. I think once it's updated, I'll add the link to the blog post here and we'll be good to close this issue.

**Comment by malgamves** [comment]
Could you come up with another usecase? or do you mean you are working on updating that article @vivmagarwal

**Comment by vivmagarwal** [comment]
Yes, @malgamves I am working on updating the article. In case you have a great use-case, I'll be happy to create a plugin first and then write on it!!

**Comment by malgamves** [comment]
Could we do do something with Twilio or Courier? Sending notifications in Strapi? @vivmagarwal

**Comment by vivmagarwal** [comment]
Sure thing, I will surely explore it in the upcoming weekend. Thanks for the suggestion @malgamves

**Comment by malgamves** [comment]
hey @vivmagarwal how is this going?

**Comment by vivmagarwal** [comment]
Hi @malgamves , as I updated in the discord channel, 
I'm occupied with a project this month, I'll be taking this up the next month

**Comment by PaulBratslavsky** [comment]
@vivmagarwal hey just wanted to check in if you will have time to do this article.  Making my way through the issues to see which have been inactive for a while.

**Comment by PaulBratslavsky** [comment]
Closing this for now, @vivmagarwal let me know in the future if you will be interested in picking this topic up in the future.
