### ISSUE TITLE
[SUBMIT] STRAPI V4 y todo lo que tiene 💯

### ISSUE THREAD

**Issue by xAgustin93** [strapi/community-content#665]
**My resource**
Aprende a usar Strapi v4 desde cero

**Video URL**
https://youtu.be/5oABPVjj3HA

**My content is**

- [X] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
Thanks for submitting the video, Shada is no longer here, so I am taking over some of the duties and have to double check how we handles video content.  I believe videos submitted would have to be uploaded to our channel and use our  branding. @dessireugarte

**Comment by dessireugarte** [comment]
Hola @xAgustin93 👋 
Si entendí bien, ¿quisieras que agreguemos el video a los tutoriales en nuestra página web?
