### ISSUE TITLE
[SUBMIT]Headless CMS As A Microservice

### ISSUE THREAD

**Issue by oyedeletemitope** [strapi/community-content#667]
**My resource**

Hello 👋 

I'd love to write on these topic. Here is my outline:

Introduction
- What are microservice?
- How it works(its architecture)?
- Why is it important ?
- Headless Cms as a microservice?
- How does strapi standout( strapi as a microservice)
- Integrate strapi with pretty much everything
- conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by malgamves** [comment]
Hey @oyedeletemitope this is a cool concept. 

Will you build anything to back your arguement?

**Comment by oyedeletemitope** [comment]
Hello @malgamves I won't be building anything as this article is just showing how microservice works and the role headless CMS plays in microservice.

**Comment by oyedeletemitope** [comment]
Can I proceed with the article?

**Comment by malgamves** [comment]
Hey i'm not really sure I get the main take away of the article. It is using a Headless CMS as an additional micro-service in a micro service architecture? What are you hoping readers better understand after seeing this?

**Comment by oyedeletemitope** [comment]
Microservices employ the use of a headless CMS to provide speed, flexibility. consistent user experience. After reading this article, the user will be able to
- understand why using a microservice is better than just using a monolithic service.
- The role a headless CMS plays in a microservice architecture.
- How Strapi fulfills this role

**Comment by oyedeletemitope** [comment]
so @malgamves, what do you think?

**Comment by Ashimi0x** [comment]
Hello @malgamves Since my last article is out to be published soon. Permit me to take on this next.

**Comment by malgamves** [comment]
This issue is closed, you can go for other issues on the repo tagged "intermediate" @Ashimi0x

**Comment by Ashimi0x** [comment]
oh alright.

**Comment by fbede4** [comment]
Hi, can I ask why was this issue closed? I would like to use strapi in a similar architecture and I have a few vague points about how it can be done.
