### ISSUE TITLE
[TOPIC] How to make a blog using eleventy and Strapi

### ISSUE THREAD

**Issue by Intromech** [strapi/community-content#67]

**Comment by Mcastres** [comment]
I'll update your issue since you didn't used the right format, but please use our issue template to propose a topic idea

**Comment by malgamves** [comment]
I'll take this

**Comment by malgamves** [comment]
[Building a Blog with 11ty and Strapi](https://strapi.io/blog/building-a-blog-with-11ty-and-strapi)
