### ISSUE TITLE
[Request] How to setup amazon s3 upload provider plugin - Strapi v4

### ISSUE THREAD

**Issue by noctufaber** [strapi/community-content#670]
**My Request**
The amazon s3 upload provider tutorials (https://strapi.io/tutorials) are way out of date. Can you please provide a version 4 tutorial to setup amazon s3 upload provider plugin?

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Marktawa** [comment]
Hi @TiaraOluwanimi 
I would love to work on a tutorial for this topic.

**Comment by PaulBratslavsky** [comment]
@Marktawa that would be awesome.  Can you provide a brief outline of the steps you will cover in your article.

**Comment by Marktawa** [comment]
Hi @PaulBratslavsky

Great. I will prepare an outline for the article.

**Comment by Marktawa** [comment]
Hi @PaulBratslavsky 
Here's a brief outline

# Set up Amazon S3 Upload Provider Plugin for your Strapi App

- Introduction
  - What is Strapi
  - What is Amazon S3
- Prerequisites
  - Strapi v4
  - AWS Account
  - Node v12 to v16
- Set up AWS
  - Create AWS Account
  - Create IAM policy Strapi
  - Set up permissions (**AWS Policy Actions**)
  - Access credentials
- Set up Strapi
  - Create demo Strapi app
  - Install `@strapi/provider-upload-aws-s3` plugin
  - Configure plugin
- Test demo app
- Recommendations
- Conclusion

**Comment by Marktawa** [comment]
Hey @PaulBratslavsky 
What's your take on my outline?

**Comment by Marktawa** [comment]
Hey @PaulBratslavsky 

Here's my finished [draft](https://www.dropbox.com/scl/fi/zee2uy0romu10geydmefa/How-to-setup-Amazon-S3-Upload-Provider-Plugin-for-your-Strapi-App.paper?dl=0&rlkey=ocfd9qeh1ap779r62wc23aijs) and [repo](https://github.com/syboxdigital/strapi-aws-s3)

**Comment by PaulBratslavsky** [comment]
@Marktawa looks great, if you are happy with your draft we can move forward @TiaraOluwanimi

**Comment by dessireugarte** [comment]
Hello @Marktawa  👋
Just wanted to let you know that your article will be published around the second week of September. I'll let you know when it is published!

**Comment by Marktawa** [comment]
Noted

**Comment by Marktawa** [comment]
Hi 👋 @dessireugarte 

> _Quick feedback, I have noticed in the last articles you include a screenshot of the login section in the admin panel of v3. We shouldn't include any screenshots referring to v3 since the articles are v4. I changed them, just take it into consideration for future articles._

Thanks for the feedback. I wasn't aware of my error. I assumed the login sections for v3 and v4 were the same. Thanks for the correction once again.

**Comment by Marktawa** [comment]
Hi 👋 @dessireugarte 

I submitted the invoice for this article on September 5th, but I have not yet received the payment. May you kindly look into this matter?

Thank you in advance.

**Comment by PaulBratslavsky** [comment]
@malgamves when you get a chance can you check the status of this invoice?  Thank you.

**Comment by Marktawa** [comment]
Hi @PaulBratslavsky 

Thanks, I received the payment.
