### ISSUE TITLE
[SUBMIT] Flutter Authentication with Strapi

### ISSUE THREAD

**Issue by Ethiel97** [strapi/community-content#676]
The article is about how to build a Flutter mobile app with an authentication system backed by Strapi. After authenticating the user, he will be directed to a home page. 

Outline
Introduction
What is Authentication 
What is Flutter 
Setting up a Strapi project
Integrating Strapi authentication API with Flutter 
Display list of items in Flutter app home page
Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article

**What do you all think?**

**Comment by malgamves** [comment]
Hey @Ethiel97 

why are you setting up Gridsome/Nuxt project in this app? 
I would love it if you could add more functionality to your app besides a home page. Can you display list of items and implement something like infinite scroll in the app?
Will user registration happen on app to?

Would love to more concise description.

**Comment by Ethiel97** [comment]
Sorry! it was en error. I've removed it.
Yes I can implement a display of list items. But would like to implement this in another tutorial like " Consume your Strapi API with Flutter or Build your Todo app with Flutter and Strapi". What do you think ?

**Comment by Ethiel97** [comment]
So I can write this tutorial, that's why I've submitted it :) @malgamves

**Comment by malgamves** [comment]
I think we can add the list of items in this tutorial too - if you can let's go ahead!

**Comment by Ethiel97** [comment]
Yes I can for sure

**Comment by Ethiel97** [comment]
@malgamves what's the next step please?

**Comment by malgamves** [comment]
Please follow these [guidelines](https://docs.google.com/document/d/1IfzUSFz0eAuVBNr7Hc2QCS5sqVGNF4QLmjhbZtC9rr8/edit) to write an article and share a draft when ready @Ethiel97

**Comment by Ethiel97** [comment]
Ok great. I'll get back to you with a draft soon

**Comment by ShadaW11** [comment]
hey @Ethiel97 do you still plan on delivering this article?

**Comment by Ethiel97** [comment]
Yes @ShadaW11 certainly. You'll hear from me shortly.

**Comment by Ethiel97** [comment]
I've started writing the tutorial. I'm pretty new here in this program, so I may have made a lot of mistakes. Please bear with me :) Here's the draft link: [Draft]( https://paper.dropbox.com/doc/Flutter-Authentication-with-Strapi--BjEdTJbk2rQIGFbk8usaullKAg-26XdnPahBGPDv7eDz606z)

@ShadaW11

**Comment by Ethiel97** [comment]
> hey @Ethiel97 do you still plan on delivering this article?
I've started writing the tutorial. I'm pretty new here in this program, so I may have made a lot of mistakes. Please bear with me :) Here's the draft link: [Draft]( https://paper.dropbox.com/doc/Flutter-Authentication-with-Strapi--BjEdTJbk2rQIGFbk8usaullKAg-26XdnPahBGPDv7eDz606z)

@ShadaW11

**Comment by Ethiel97** [comment]
https://paper.dropbox.com/doc/26XdnPahBGPDv7eDz606z
@PaulBratslavsky what do you think of this please? This is my outline

**Comment by PaulBratslavsky** [comment]
@Ethiel97 sorry for a late response, but it looks good.  You can continue on this.  Let me know if you have any questions.🙂

**Comment by vcoisne** [comment]
Hi @Ethiel97 I;m closing this one due to inactivity and because we're looking for more advanced articles at the moment.
