### ISSUE TITLE
[TOPIC] Best React, Vue, Angular packages in 2021

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#69]
**My Request**
List of the best  React, Vue, Angular packages in 2020

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by krissnawat** [comment]
@Mcastres I would like to pick this topic.

**Comment by malgamves** [comment]
Let's do it! When do you think you can have something for me to look at @krissnawat ?

**Comment by Mcastres** [comment]
Hey @krissnawat, just checking if there is any news about this :)

**Comment by pieroborrelli-dev** [comment]
Hey @malgamves is this post still available? I have the skills and the time to write it!
Let me know,
Pieor

**Comment by pieroborrelli-dev** [comment]
Hey @malgamves for sure, I'm ready to write the article as soon as you send me its details. 
Waiting for your updates.
I'm sure the final result will be great.

**Comment by malgamves** [comment]
I'd like to see an article on what you're excited for in the frontend space this should cover
- past events in 2020 that had an effect on frontend developers
- an overview of the current frontend ecosystem
- changes you'd like to see
- the role of headless cms in the frontend ecosystem
- devtools, packages or libraries to watch out for this year

When do you think you'll have this ready @pieroborrelli-dev ??

**Comment by pieroborrelli-dev** [comment]
@malgamves That sounds great. I could send you the full article in about a week. Does Sunday 11 April sounds good to you? I will write the full article, add images, and check everything is polished. 

If that sounds good, I would like to ask you a couple of questions before starting:

* Do you have a preferred tool for me to submit the article?
* Where should I submit the final product
* What is the pay rate for the article and which payment method do you use?

Can't wait to start working on it!
Piero

**Comment by pieroborrelli-dev** [comment]
> @malgamves That sounds great. I could send you the full article in about a week. Does Sunday 11 April sounds good to you? I will write the full article, add images, and check everything is polished.
> 
> If that sounds good, I would like to ask you a couple of questions before starting:
> 
> * Do you have a preferred tool for me to submit the article?
> * Where should I submit the final product
> * What is the pay rate for the article and which payment method do you use?
> 
> Can't wait to start working on it!
> Piero

Hey @malgamves are you still up for me to write this article?

**Comment by malgamves** [comment]
hey @pieroborrelli-dev yes April 11 sounds great!! Have a look at our [FAQs ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46) they will answer your questions.

and yess!! I'm still up for you to write this article. Still good on the timeline?

**Comment by krissnawat** [comment]
@malgamves i like to participate on topic 
devtools, packages or libraries to watch out for this year

**Comment by pieroborrelli-dev** [comment]
> hey @pieroborrelli-dev yes April 11 sounds great!! Have a look at our [FAQs ](https://www.notion.so/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46) they will answer your questions.
> 
> and yess!! I'm still up for you to write this article. Still good on the timeline?

Hey @malgamves I confirm you the send date for April 11. Will send you an email with the full article on that date!

**Comment by malgamves** [comment]
hey @pieroborrelli-dev great, changed that for you don't worry about it. Can't wait to see it.


@krissnawat looks like it's been taken :p

**Comment by pieroborrelli-dev** [comment]
hey @malgamves I'm about to send you the article, sorry for the little delay, I had a problem with my internet connection.

**Comment by pieroborrelli-dev** [comment]
Hey @malgamves I've correctly submitted the article to you via mail. Hope you will enjoy it. 
Waiting for your feedback,
Piero

**Comment by malgamves** [comment]
Just seen it, I will have a look :D thanks @pieroborrelli-dev
