### ISSUE TITLE
Understanding the Different Types/Categories of Strapi Hooks[UPDATE]

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#696]
**My update**

Hello 👋 @malgamves 

This article is among the first 50 tutorials to be updated, and it has been updated, reviewed, and ready to be published, but I can get in touch with shade any longer.
here is the link to the article
 https://www.dropbox.com/scl/fi/aq1xj70kb77cl50bvu7ga/Understanding-the-Different-TypesCategories-of-Strapi-Hooks.paper?dl=0&rlkey=ye7vhvxiw7ztz83u26uvp0rta

I believe you can assist.

Thank you.

**Comment by ShadaW11** [comment]
Hey @lucky4242 I believe all is good on this article (its published), apologies for the delay, you can reach out to me on discord if you have any questions.
