### ISSUE TITLE
How to Create a Blog with SvelteKit and Strapi

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#697]
Initial article
https://strapi.io/blog/how-to-create-a-blog-with-svelte-kit-strapi	

Dropboxlink - v4 update
https://www.dropbox.com/scl/fi/vm3wpgxjpp7fv7da76lsr/How-to-Create-a-Blog-with-SvelteKit-and-Strapi.paper?dl=0&rlkey=iw2s4f1w949bm9teu7hhxsyji

**Comment by NafunaAfrica** [comment]
so whats the status with this?
