### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by dodo007** [strapi/community-content#70]
Modifying nested objects trough the code. 

I do not understand how to modify repeatable components inside a model. There is no documentation for that and Mongoose does not work as expected when used with  

const result = strapi.query('statscustomer').model.find({ id:"5eb5b14972385865715099dc" });
result.toObject();

error TypeError: result.toObject is not a function

So I can't continue the project. It would be nice if someone could help me with this. 

<img width="404" alt="Screenshot 2020-05-08 at 16 01 18" src="https://user-images.githubusercontent.com/8824825/81445663-9d0a7500-9179-11ea-8b9d-b17eb36a1e34.png">

![Screenshot 2020-05-08 at 15 59 31](https://user-images.githubusercontent.com/8824825/81445839-f8d4fe00-9179-11ea-8889-39ad420514df.png)

These two images show the structure I'm trying to edit. So if anyone could give me a hint that would be life-saving

**Comment by Mcastres** [comment]
Hello @dodo007 I'm closing this issue as it is not a correct issue for this repository. If you'd like to get help on this, please join our slack https://slack.strapi.io? You could get some answers in the "#help" channel
