### ISSUE TITLE
[REQUEST] HOW TO SET UP AN ECOMMERCE FOR REACT 

### ISSUE THREAD

**Issue by jamesaduke** [strapi/community-content#705]
SET UP REACT E-COMMERCE USING POSTGRESQL

**Comment by ShadaW11** [comment]
@jamesaduke are you looking to work on this tutorial or requesting our community to work on it?

**Comment by Dmuasya** [comment]
Hi, @ShadaW11 I'm willing to work on this tutorial.

**Comment by PaulBratslavsky** [comment]
@Dmuasya sorry for late response, I took over some of Shada's duties recently and been catching up with all issue submission.  Let me know if you are still interested in doing this.

**Comment by Dmuasya** [comment]
@PaulBratslavsky Thanks for getting back to me & I'm still interested.

**Comment by PaulBratslavsky** [comment]
@Dmuasya sorry for supper late response.  Based on your outline it looks like it will mostly cover the front-end portion where Strapi is used as a basic API.  For the time being, we have plenty of frontend articles that cover how to use framework x with Strapi.  So at the moment, we are looking for articles that are more specific to Strapi backend customizations and use cases.

For the time being, I will be closing this issue.  Let me know if you have any additional questions.
