### ISSUE TITLE
[TOPIC] Authentication with Strapi

### ISSUE THREAD

**Issue by Mcastres** [strapi/community-content#71]
**My Request**
A complete tutorial on using authentication in Strapi

**Community vote**
👍 Upvote if you like this idea
🚀 If you can make the tutorial/article!

**Comment by adriatic** [comment]
This issue will be addressed with **[Symphony](https://github.com/strapi/community-content/issues/95)** as will many other projects in this collection. We would have to decide whether to refer these projects to the Symphony project or cut out relevant components from the Symphony and implement these components as independent projects as defined here.

**Comment by malgamves** [comment]
This is being worked on in #55 so I'll close this
