### ISSUE TITLE
[UPDATE] How to deploy a Strapi API on Ubuntu 16.04

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#719]
Hello 👋

This [article](https://strapi.io/blog/how-to-deploy-a-strapi-application) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by ikeadeoyin** [comment]
Hi @ShadaW11 @TiaraOluwanimi 
I can work on this. I would love to update this tutorial.

**Comment by PaulBratslavsky** [comment]
Thank you @ikeadeoyin for taking this on.

**Comment by PaulBratslavsky** [comment]
Hey, @ikeadeoyin.  Hope you are doing wonderfully.  Just wanted to check in and see how you are progressing on the article.

**Comment by ikeadeoyin** [comment]
Hi @PaulBratslavsky 
It is going quite fine. I will share my updates soon.

**Comment by Marktawa** [comment]
Hey @ikeadeoyin 
Are you still interested in this article? If you're not, I can work on it.

**Comment by ikeadeoyin** [comment]
@Marktawa 
I am still interested in working on the article.

**Comment by vcoisne** [comment]
Hello @ikeadeoyin ! Any update on this one ?

**Comment by danielonugha0** [comment]
Hi @ikeadeoyin @PaulBratslavsky

I would love to write on this topic
Best regards
DO
