### ISSUE TITLE
[UPDATE] Deploying a Strapi API on Heroku in 5 min

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#721]
Hello 👋

This [article](https://strapi.io/blog/deploying-a-strapi-api-on-heroku) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by PaulBratslavsky** [comment]
@lucky4242 I just recently took over some of Shada's responsibilities and just wanted to check in to see if you are still interested in doing this article?

**Comment by lucky4242** [comment]
Yes i am interested

**Comment by lucky4242** [comment]
Hello @PaulBratslavsky
I've completed the article's update.
here is the link
https://www.dropbox.com/scl/fi/3gakpnm17do3m2vlh9sr1/Deploying-a-Strapi-API-on-Heroku-in-5-min.paper?dl=0&rlkey=gupk256zozcay2cipt8k1pvkv

**Comment by lucky4242** [comment]
Hello @PaulBratslavsky
waiting for response

**Comment by dessireugarte** [comment]
Hello @lucky4242 👋
This article is already updated and the content is pretty similar.

**Comment by PaulBratslavsky** [comment]
I am closing this issue based on @dessireugarte response. As well as we have great documentation on this topic.
