### ISSUE TITLE
[UPDATE] Deliveroo clone with Next.js, GraphQL, Strapi and Stripe - Setup (1/7)

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#723]
Hello 👋

This [article](https://strapi.io/blog/strapi-next-setup) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by PaulBratslavsky** [comment]
I think we definitely need more GraphQl articles. So this updated will be great.  Anyone want to take this on let me know, I can also help answer any GraphQl related questions in Strapi v4 you may have.

**Comment by vcoisne** [comment]
@PaulBratslavsky given how popular this one is, I wonder if we shouldn't update ourselves or highlight it on Discord or something ?

**Comment by Melanie12** [comment]
Can we find and tag the original author?

**Comment by hubertnare** [comment]
Hi @PaulBratslavsky , @vcoisne , and @Melanie12 .

I am willing to update this one.

**Comment by PaulBratslavsky** [comment]
@vcoisne @Melanie12 @hubertnare can take on this update if the original owner does not have the time for the update.

**Comment by PaulBratslavsky** [comment]
@hubertnare going to assign this update to you.  Thank you.

**Comment by hubertnare** [comment]
Sure, update en route 🚀 🚀

**Comment by hubertnare** [comment]
Hi @PaulBratslavsky ,

While working on this I realized this issue is precisely the same as issue  #889 but with different titles. Instead, I intend to tackle issue #1080

**Comment by PaulBratslavsky** [comment]
This seems to be a duplicate of https://github.com/strapi/community-content/issues/889 closing since the articles have been written and are awaiting review.
