### ISSUE TITLE
[UPDATE] Build a blog with Nuxt (Vue.js), Strapi and Apollo

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#725]
Hello 👋

This [article](https://strapi.io/blog/build-a-blog-using-nuxt-strapi-and-apollo) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by boulaffasae** [comment]
Hi @TiaraOluwanimi @ShadaW11 I will work on this article

**Comment by ShadaW11** [comment]
@boulaffasae thank you, the article will be reviewed asap.

**Comment by ShadaW11** [comment]
@boulaffasae please submit your invoice.

**Comment by boulaffasae** [comment]
Hi @PaulBratslavsky, you think you can continue with the invoice process ?
