### ISSUE TITLE
[UPDATE] How to create an import content plugin (part 1/4)

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#726]
Hello 👋

This [article](https://strapi.io/blog/how-to-create-your-own-plugin-part-1-4) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by Marktawa** [comment]
I am interested in updating this article.

**Comment by ShadaW11** [comment]
@Marktawa apologies this issue was opened before and someone is working on It https://github.com/strapi/community-content/issues/633 . It would be great if you can work on a different open issue. thank you so much.
