### ISSUE TITLE
[UPDATE] Build a blog with Next (React.js) and Strapi

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#727]
Hello 👋

This [article](https://strapi.io/blog/build-a-blog-with-next-react-js-strapi) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by lucky4242** [comment]
Hi,
I would love to work on this article.
