### ISSUE TITLE
[UPDATE] Build a blog with Angular, Strapi and Apollo

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#728]
Hello 👋

This [article](https://strapi.io/blog/build-a-blog-with-angular-js-strapi-and-apollo) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by PaulBratslavsky** [comment]
I am not to familiar with Angular, but if anyone one wants to work on this, let me know, I can help you with Strapi v4 GraphQl related Questions.

**Comment by Eventyret** [comment]
I'm very familiar with angular @PaulBratslavsky  but not to much with graphQL, so on the other hand, if anyone wants to write it but needs help with Angular do give me a tag I don't mind assist with it.

**Comment by Marvel-D** [comment]
Hello.
I am conversant with the tech stack needed for this article and would like to update it

**Comment by Marvel-D** [comment]
@PaulBratslavsky is this article still available?

**Comment by PaulBratslavsky** [comment]
@Marvel-D Sorry for late response, we have many article reviews in the cue and at the moment we are not taking any new article submission until January.  But if you are still interested, I can assign the update to you and you can start on it in January.  Just let me know if this is something you would like to do?

**Comment by Marvel-D** [comment]
Yes, I can do that

**Comment by PaulBratslavsky** [comment]
@Marvel-D just wanted to check in if you started on this update?

**Comment by Marvel-D** [comment]
yes @PaulBratslavsky.
I am on it.

**Comment by PaulBratslavsky** [comment]
@Marvel-D I hope you are well.  I know it has been a while. But wanted to check in and see if you are still looking to publish this article?

**Comment by Marvel-D** [comment]
Yes, I'm still interested.

**Comment by PaulBratslavsky** [comment]
@Marvel-D thank you. Let me know when you get a draft.

**Comment by hanakhelifa** [comment]
Hi @Marvel-D,
I joined Strapi last month, and I'm working on Community Content. As we are currently revamping the Write For the Community program, I am doing a bit of cleaning up on this repo. I see this issue is open for more than a year now, and that there is no draft, so I'll close it to keep the repo up-to-date with upcoming changes. Feel free to reach out to me if needed :)
