### ISSUE TITLE
[SUBMIT] Setting up and using Elastic App Search

### ISSUE THREAD

**Issue by drewtownchi** [strapi/community-content#73]
**My resource**
This would be a tutorial series on how to setup, index data and then query/search that data using Strapi and Elastic App Search.  

https://www.elastic.co/app-search/

**My format**

- [x ] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Hello @drewtownchi ! How are you?
Have you had a chance to work on this content recently?

**Comment by malgamves** [comment]
Hey @drewtownchi just checking to see if you've made any progress here. Will wait a few days before marking this "Looking for Author"

**Comment by alloyking1** [comment]
Hi, I can write a detailed tutorial on this. @Mcastres

**Comment by Mcastres** [comment]
That would be quite interesting! Can you give me more details about it?

**Comment by alloyking1** [comment]
I could create a simple application with strapi and elastic searching demonstrating complex search features using elastic app search. This feature would be implemented in a strapi application. then write a detailed tutorial on it. Does that work? @Mcastres

**Comment by Mcastres** [comment]
That would be great! Alright, it's yours ;)

**Comment by alloyking1** [comment]
Thanks @Mcastres .  Working on it

**Comment by malgamves** [comment]
hey @alloyking1 - any progress here?

**Comment by alloyking1** [comment]
Yes. I'm making progress. Sorry about any delays.

**Comment by malgamves** [comment]
No worries, share as soon as you can :D

**Comment by ShadaW11** [comment]
Hey @alloyking1 Its been a while, did you manage to finish this article?

**Comment by alloyking1** [comment]
Yes I did. I have also informed Michael that I did. He is currently
reviewing it. Can I get started on other topics while these are being
reviewed ?

**Comment by alloyking1** [comment]
Oh.. I just had a second look at it. I was working on other strapi articles
for a while. This particular article has not been completed yet. I can get
back on it ASAP.

**Comment by ShadaW11** [comment]
@alloyking1 awesome. Thank you so much. Looking forward to receiving the article.

**Comment by ShadaW11** [comment]
Hey @alloyking1 do you have an estimation of when the article could be ready?

**Comment by ShadaW11** [comment]
Hey @alloyking1 any update on this?

**Comment by dessireugarte** [comment]
Hello @oviecodes 👋 
This topic is still available. Could you share an outline with @PaulBratslavsky in this issue of what you would like to cover?

**Comment by oviecodes** [comment]
Alright @dessireugarte

**Comment by oviecodes** [comment]
Hey @dessireugarte I'll have to build the application using strapi and elastic search so as to know what goes into building such an application.

Using elastic search, I'll build a complex search engine for a demo strapi application.

**Comment by malgamves** [comment]
@oviecodes will you cover the process of building? the benefits of elastic search over others? Specific elastic search features?

We'd like an idea of information you'll present in the article and the angle you want to go for before you can go for it. Are you familiar with the technology?

**Comment by oviecodes** [comment]
Table of content

1. Introduction to Strapi
2. Basic requirements
3. What is elastic search
4. What to consider before using elastic search
5. The need and benefits of using elastic search
6. Building our Strapi application
7. Integrating elastic search into a strapi application
8. Conclusion 

@malgamves @dessireugarte @PaulBratslavsky  here are some of the things I'll cover in this article.

**Comment by malgamves** [comment]
hey @oviecodes what type of application will you build that leverages search? Can you implement search on an existing large project life [foodadvisor](https://github.com/strapi/foodadvisor) maybe?

**Comment by oviecodes** [comment]
@malgamves that would be nice... When can I get started and can you point me to the repository...

**Comment by malgamves** [comment]
As soon as you update the outline and get it validated ;)

**Comment by oviecodes** [comment]
Table of content

1. Introduction to Strapi
2. Basic requirements
3. What is elastic search
4. What to consider before using elastic search
5. The need and benefits of using elastic search
6. Looking at the Strapi [foodadvisor](https://github.com/strapi/foodadvisor) application
7. Making modifications to the application for search functionalities.
8. Integrating elastic search into the  strapi [foodadvisor](https://github.com/strapi/foodadvisor) application
9. Testing the application
10. Conclusion

@malgamves @dessireugarte @PaulBratslavsky here's the updated version of the outline

**Comment by malgamves** [comment]
Looks great to me!!

**Comment by oviecodes** [comment]
Alright @malgamves I'll get started with the article.

**Comment by oviecodes** [comment]
Hello @dessireugarte @malgamves here's a link to the draft

https://www.dropbox.com/scl/fi/b2zi3qq5kge36hk7j60oi/Setting-up-and-using-Elastic-Search-with-Strapi.paper?dl=0&rlkey=th9a8sk2g37912dof3plkmvjb

**Comment by dessireugarte** [comment]
Thanks @oviecodes! I'll get back to you if we have feedback 👍

**Comment by PaulBratslavsky** [comment]
@oviecodes @dessireugarte the article looks good we can move it to review. @TiaraOluwanimi this is ready to be reviewed. Thank you.

**Comment by dessireugarte** [comment]
Hello @oviecodes! Your article will be published in the second week of November. But could you send your invoice and let me know when you send it?

**Comment by oviecodes** [comment]
Alright @dessireugarte I'll do that.

**Comment by dessireugarte** [comment]
Hello @oviecodes  👋
Just wanted to let you know that your article will be published next week. I'll let you know if we need any changes from you or when it is published!

**Comment by dessireugarte** [comment]
Hello 👋 
Your article is [live](https://strapi.io/blog/how-to-set-up-and-use-elasticsearch-with-strapi)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment.
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by dessireugarte** [comment]
Hello @oviecodes! 
Could you please submit the invoice again with the right amount in dollars ($150)? If you submit it after today, please could it be done with the date December 1st? Otherwise, Finance will reject the invoice. 
Just so you know, I already notified the Finance team that you still haven't received your payment on the other articles.

**Comment by oviecodes** [comment]
Why is this for $200 @dessireugarte

**Comment by dessireugarte** [comment]
Sorry @oviecodes, my bad. There is new pricing on the articles/tutorials, just so you have that in mind, I'm sending you the [link](https://strapi.io/write-for-the-community) with the information. But it will be until January 2023, so I already submitted your invoice.

**Comment by dessireugarte** [comment]
@oviecodes could you please resend the invoice? It got rejected since it is missing information.

**Comment by oviecodes** [comment]
Alright @dessireugarte just to be clear, should I send the invoice with the date December 1st?
Concerning the other payments should I submit another invoice?
