### ISSUE TITLE
[UPDATE] Strapi Starter React Blog

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#730]
Hello 👋

This [article](https://strapi.io/blog/strapi-starter-react-blog) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by lucky4242** [comment]
Hi.
I would love to update this article.

**Comment by lucky4242** [comment]
Hi @ShadaW11,
Here is the link to the updated article.
https://www.dropbox.com/scl/fi/i28e47by735vuv3ir2l2i/Strapi-Starter-React-Blog.paper?dl=0&rlkey=b8o9c27vq9rgmunfxdff6n5a0

**Comment by ShadaW11** [comment]
Thanks, @lucky4242 we will review your article as soon as possible.

**Comment by ShadaW11** [comment]
If you haven't please issue your invoice @lucky4242 and thank you so much for working on the article.
