### ISSUE TITLE
[UPDATE] Webhooks explained and how to use them in Strapi

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#731]
Hello 👋

This [article](https://strapi.io/blog/webhooks) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by popoolatopzy** [comment]
Hi, I'll be working on updating  this article.

**Comment by popoolatopzy** [comment]
Hello @ShadaW11, am done updating the article, here is the link to the article 
https://www.dropbox.com/scl/fi/m6jtofaqe31k0dov5na9u/Webhooks-explained-and-how-to-use-them-in-Strap.paper?dl=0&rlkey=b3m0f4m4dssh2t4e7nl0glmp6

**Comment by ShadaW11** [comment]
@popoolatopzy please submit your invoice. your article is published.
