### ISSUE TITLE
[UPDATE] Creating a Strapi Dynamic Zone & Rendering it in your Nuxt.js App

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#736]
Hello 👋

This [article](https://strapi.io/blog/creating-strapi-dynamic-zone-in-nuxtjs-app) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by boulaffasae** [comment]
Hi @TiaraOluwanimi @ShadaW11 I will work on this article

**Comment by boulaffasae** [comment]
Hello @TiaraOluwanimi 

I updated the article https://www.dropbox.com/scl/fi/rtc95soluigmog5prxget/Creating-a-Strapi-Dynamic-Zone-Rendering-it-in-your-Nuxt.js-App.paper?dl=0&rlkey=1zzdray3hbq1tt47ang08rhdr

PR can be found at https://github.com/strapi/community-content/pull/790

I removed the Apollo/GraphQL section, Strapi GraphQL plugin doesn't support filters :/
