### ISSUE TITLE
[UPDATE] Strapi Authentication in Nuxt.js

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#737]
Hello 👋

This [article](https://strapi.io/blog/strapi-authentication-in-nuxt-js) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by boulaffasae** [comment]
Hi @TiaraOluwanimi @ShadaW11 I will work on this article

**Comment by ShadaW11** [comment]
https://www.dropbox.com/scl/fi/6h2twfgu08nvwb35dql4v/Strapi-Authentication-in-Nuxt.js-..paper?dl=0&rlkey=3mepulwk5vv28gzg1wjhtyev2 @TiaraOluwanimi

**Comment by boulaffasae** [comment]
Hi @TiaraOluwanimi 

I create a new PR https://github.com/strapi/community-content/pull/788

**Comment by ShadaW11** [comment]
Hello @boulaffasae your article was published and your invoice will be paid asap.
