### ISSUE TITLE
[UPDATE] How to change the default WYSIWYG to Quill Editor

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#739]
Hello 👋

This [article](https://strapi.io/blog/how-to-change-the-default-wysiwy-to-quill-editor) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by ShadaW11** [comment]
this article has been updated and published
