### ISSUE TITLE
[UPDATE] How I Hosted my Strapi CMS Driven Website for Free

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#741]
Hello 👋

This [article](https://strapi.io/blog/how-i-hosted-my-strapi-cms-driven-website-for-free) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by ibn-ashimi** [comment]
Hi, @PaulBratslavsky I will like to work on this.

**Comment by PaulBratslavsky** [comment]
@ibn-ashimi that would be great.  You can get started on the update, just keep in mind we are no longer using MongoDB.

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 
Are you still working on this?

**Comment by ibn-ashimi** [comment]
Yes, I will share an update with the Draft in no time.

**Comment by dessireugarte** [comment]
Hello @Ashimi0x! Are you still working on this topic?

**Comment by Ashimi0x** [comment]
Yes, I am.

**Comment by vickywane** [comment]
@dessireugarte @Ashimi0x any update here?

**Comment by Ashimi0x** [comment]
Yes @dessireugarte Sorry for the delay. I should send it in this week.

**Comment by PaulBratslavsky** [comment]
@Ashimi0x just wanted to check in and see if you are still interested in finishing this article.  Thank you.

**Comment by Ashimi0x** [comment]
Yes. @PaulBratslavsky  I will get it across later this week 🙏🏿

**Comment by hanakhelifa** [comment]
Hello @Ashimi0x,
As we are revamping the Write for the community program, I am cleaning up the issues so everything is up-to-date with the new program. I see this article is more than a year in the making, so I'll close the issue. I'm remain available if needed, both here and on Discord

**Comment by Ashimi0x** [comment]
I have just had quite a busy schedule and the changes in the program got me quite confused. I can't find you on Discord. I will like to send a direct message.

**Comment by divofred** [comment]
Here it is:
https://discord.gg/strapi

**Comment by hanakhelifa** [comment]
@Ashimi0x Just reached out to you on Discord :)
