### ISSUE TITLE
[UPDATE] A Bite-sized Guide to Content Modelling in Strapi

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#746]
Hello 👋

This [article](https://strapi.io/blog/content-modelling-bite-sized-guide) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by TechMakanaki** [comment]
I will like to work on this article.

**Comment by TiaraOluwanimi** [comment]
@TechMakanaki, thanks for your patience. Are you still interested in updating this?
