### ISSUE TITLE
[UPDATE] Headless CMS and Strapi SEO best practices

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#747]
Hello 👋

This [article](https://strapi.io/blog/headless-cms-strapi-seo-best-practices) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by PaulBratslavsky** [comment]
I am closing this issue since it has been completed.
