### ISSUE TITLE
[UPDATE] How to build a Strapi Custom Plugin

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#748]
Hello 👋

This [article](https://strapi.io/blog/how-to-build-a-strapi-custom-plugin) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by Marktawa** [comment]
I am interested in updating this article.

**Comment by ShadaW11** [comment]
Hello @Marktawa this article will not be updated, as another version has been released already here: https://strapi.io/blog/how-to-create-a-strapi-v4-plugin apologies for that.
