### ISSUE TITLE
[UPDATE] Learning Strapi Authentication Flows with the Facebook Provider

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#749]
Hello 👋

This [article](https://strapi.io/blog/learning-strapi-authentication-flows-facebook-provider) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by Marktawa** [comment]
I am interested in updating this article.

**Comment by ShadaW11** [comment]
Hello @Marktawa happy to hear that. If this is your first article, please register here https://strapi.io/write-for-the-community 
Once you do, please go over  

🔑 [SEO & Article Guidelines](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VWm5J_8q1pvHVFDBjc6cbh6fW35KrPN4K9CMVN824Dzp3lLBGV1-WJV7CgXnNW5bW0tN1RG99XW1dWLQR5dnR2VW1QC3Y36VBrTwW7wHfx17bFHYSW6Lh-393VglwGW7mpFsk58VhpJW1Dn_Qn3ZLF08W2x7clD8yxnBXW4tK0-K9bhBXTVR1FQQ20n3lWW10LklZ2TnnjNW1XbwsZ30-N42W45L2Mx1z7VM6W3vYK2P4NlZznW4HPft28l1YLVW5Jc44G209snvW1SrrMD30nq6wW7b_Xvh6_vSjHW4fpJ1N5ZFZYNN1ZNJHqScX1LW3ZfsK_1sCPDFW5dtHjr1dLNfZW4wL7xF2--4NYW4xmBCc1_v4P-3d6Y1)

⁉️ [Go through FAQ section](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VWm5J_8q1pvHVFDBjc6cbh6fW35KrPN4K9CMVN824Dyw3lLzNV1-WJV7CgG2XW9dSmbZ331Tf1W4wlV1-25-7WNW4TL6q075yhFDW4dmJ1T8PdRrYW2bSMtc2rVWypN1W0_stLj2phW8mBscl2z_CBcN78VGXLdN5ldW7Z-5B-1TbC4KW2YXtx68Ts3WGW7_1ZFg2dlmhVW2l__wR453TP8N96nCsz-2dSRN4mDwvm2QtPWN4n_HldSJ12NW73L-j35SLBjWW8KpJMb8thGg3W545SS91FlJBQ3hpd1)
💬 [Join the WFC Discord channel](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VWm5J_8q1pvHVFDBjc6cbh6fW35KrPN4K9CMVN824Dyc3lLztV1-WJV7CgDNlW5VY6tK6YsBZTW5_6nVG5p3bDLW1fxTJK3yk3lPN5Cc7DzhW-wbW8JSwqg5FZ0psN6dVMTr7XS4XW1ywNQw7F4SZ0W7r2qy-6LghyLW5JKWdx90TfSyW4TJK6P8bT0_VN5L7J_ZgWFs_W9gQF5X3T9D5wW77wx338fRhXDVpwSx67MBWHZW9hdb-G6sm9lhVshTh03xZ4SC34W11)

⚙️[ Read the Writer's Guide: How to update content with v4](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VWm5J_8q1pvHVFDBjc6cbh6fW35KrPN4K9CMVN824Dzp3lLBGV1-WJV7CgSCbVXRQ9f3Q4F0DW1NsZVt7W1-c9N5VLf2HdHlgKW3FZ1Pd7jMCShW5VTdpY7zmFk4W7QjYfX20H8hsV5FQ371hbyRTW73Vc4Y2ymNxyW1nntph20kdSNW4D9Sc164nPV4W6bmrPd8gZfMdW121ygP20T9BNW4gL14s95XhHFW94dwpf2n7JFmW5kBjzf7xqsfMW61KDp26_WjFKW4zDj8d1Nh4njW5C-gw-20cgXfW4KmKZj5jlqC5W68S0hb5YpxsvW1tQMLt6btG3NW3V952J8TbJP8W4p-dbG45HY6NW3tRHrm1W_hzG31T71)
📹[ Watch this Video: Improve your Writing Skills: Strapi's technical writing workshop](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VWm5J_8q1pvHVFDBjc6cbh6fW35KrPN4K9CMVN824Dz53lLBmV1-WJV7CgFZKW80kWWD8WTtRBW6wlxPR8RF_qNW49pkdn6kqMQjW85QH3B5fn4ckN6kwL4gX-R5ZVpsSBx236Kc-W38qKGS7sBCDfW4-qJ9Q4B4qg-W5PVZRt5v51qxW833m-B1HSDhNW4sh0G673Zm0-W7BPTTn1C8173MSkxj7KTGh9W3sVXbx3gQSmQW47Kw9Z4z1WftW4JVrqt3BqjT1W4P6-qN2dwt27W6bXz2S3gQb2kW6SMgFz2L25BGW92cDKm575WwDW6f88XQ7kKd9DW1t5lGQ7QV-vW3mwh1)

**Comment by Marktawa** [comment]
Hi @ShadaW11 

Thank you for assigning me the tutorial.

I have gone over the material and will start updating the article.

**Comment by ShadaW11** [comment]
@Marktawa Perfect

**Comment by ShadaW11** [comment]
Thank you @Marktawa someone from our team will be reviewing it. @TiaraOluwanimi

**Comment by dessireugarte** [comment]
Hello 👋 Just wanted to confirm you submitted your invoice and got your payment?

**Comment by Marktawa** [comment]
Hey @dessireugarte 

Yes, I received the payment. Thanks
