### ISSUE TITLE
[TRANSLATE pt-BR]

### ISSUE THREAD

**Issue by ianfelix** [strapi/community-content#75]
### **Documentação Strapi**

**O Strapi é um projeto de código aberto [Headless CMS](https://strapi.io/) desenvolvedores adoram**

O Strapi é um CMS Headless flexível e de código aberto, que oferece aos desenvolvedores a liberdade de escolher suas ferramentas e estruturas favoritas, além de permitir aos editores gerenciar e distribuir facilmente seu conteúdo. Ao tornar o painel de administração e a API extensíveis por meio de um sistema de plug-ins, o Strapi permite que as maiores empresas do mundo acelerem a entrega de conteúdo enquanto criam belas experiências digitais.

> De onde vem o nome?
> 
> Strapi vem da palavra Bootstrap, e ajuda a inicialização com a sua API 🎉
> Este foi o propósito original deste projeto.
> 

### **Recursos**

**Estrutura de conteúdo personalizada**
Você pode gerar o painel de administração em apenas alguns cliques e obter toda a configuração do CMS em alguns minutos.

**Fácil gerenciamento de conteúdo**
O painel de administração do Strapi oferece uma interface intuitiva para criar, editar e excluir seu conteúdo.

**API amigável ao desenvolvedor**
Se seu conteúdo tiver que ser exibido para o mundo, é necessária uma API. O Strapi fornece uma API que atenderá facilmente às suas necessidades. Busque todos os dados necessários através de uma API REST ou GraphQL.

**Funções e permissões**
O Strapi possui um sistema de usuário interno que permite gerenciar quem pode acessar e o que acessar.

**Sistema de plug-in**
Precisa de um novo recurso para seu aplicativo? Busque um plugin no mercado e tadah! A instalação de um terminal GraphQL nunca foi tão fácil.

**Customização**
Cada parte do seu aplicativo pode ser facilmente personalizada. A arquitetura do Strapi permite que você estenda seu aplicativo para corresponder ao seu caso de uso exato.

Não fique atolado pela tecnologia que você não precisa!

--------------------------------------------------------------------------------------------------------------
### **O ecossistema Strapi**

**Código fonte**
Strapi é um projeto de código aberto, todo o código-fonte do Strapi está sob a licença MIT. O projeto principal pode ser encontrado no repositório [strapi / strapi](https://github.com/strapi/strapi) GitHub e você encontrará todas as outras ferramentas na organização [Strapi](https://github.com/strapi) GitHub.

**Mercado**
Os plugins oficiais do Strapi podem ser encontrados na seção de marketplace do painel de administração. Infelizmente, o mercado Strapi não está aberto a contribuições externas, mas fique atento, pois isso pode mudar em um futuro próximo.

Com isso dito, você ainda pode [desenvolver e usar seus próprios plugins](https://strapi.io/documentation/3.0.0-beta.x/plugin-development/quick-start.html).

**Roteiro**
Strapi é um projeto orientado para a comunidade, com ênfase na transparência. Queremos compartilhar nossa visão do futuro da Strapi e ter sua ajuda para concretizá-lo. Suas idéias são muito importantes e ajudarão a direcionar o projeto na direção certa; portanto, visite o [The Roadmap](https://portal.productboard.com/strapi/1-public-roadmap/tabs/2-under-consideration) e compartilhe suas idéias.

**Tutoriais e guias**
Para ajudar você a começar com o Strapi, nós e a comunidade fornecemos uma infinidade de recursos! Você encontrará [tutoriais](https://strapi.io/tutorials/) no site oficial e também documentação.

**Demo**
Quer ver o Strapi em ação? confira o [vídeo de demonstração](https://strapi.io/demo) ou solicite uma demonstração ao vivo através do formulário presente na página.

**Blog**
Para notícias e anúncios de longo prazo, confira nosso [blog](https://strapi.io/blog) .

#Mídia social
Mantemos várias contas de redes sociais para manter contato direto com a comunidade e dar atualizações sobre as novidades do Strapi:

⭐️ [GitHub](https://github.com/strapi/strapi)
🐧 [Twitter](https://twitter.com/strapijs)
‍💻 [ Facebook](https://www.facebook.com/strapijs/)
📸 [Instagram](https://www.instagram.com/strapijs/)

**Community vote**
👍 Upvote if you need it too
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Hey @ianfelix, can you explain what this translation is about?

**Comment by ianfelix** [comment]
> Hey @ianfelix , você pode explicar o que é esta tradução?

documentation translation for pt-br

**Comment by malgamves** [comment]
Hey @derrickmehaffy  and @lauriejim it looks like @ianfelix would like to translate a portion of the Strapi documentation to Portuguese. Could you you help him out?

**Comment by derrickmehaffy** [comment]
Currently our documentation can't handle translations yet, we are looking at this for the big doc review but it will take us some time to figure out the best solution
