### ISSUE TITLE
[UPDATE] How to Build a Learning Platform with Strapi CMS and Gridsome

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#751]
Hello 👋

This [article](https://strapi.io/blog/how-to-build-a-learning-platform-with-strapi-cms-and-gridsome-1) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by miracleonyenma** [comment]
Is this still available for an update?
I would like to make a submission

**Comment by ShadaW11** [comment]
hey @miracleonyenma your article will be reviewed soon.
