### ISSUE TITLE
[UPDATE] How to Build a Podcast app using Strapi and Nextjs

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#752]
Hello 👋

This [article](https://strapi.io/blog/how-to-build-a-podcast-app-using-strapi-and-nextjs) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by IsaacThaJunior** [comment]
Hey there, I'm available to work on this

**Comment by IsaacThaJunior** [comment]
@TiaraOluwanimi I would love to work on this if it is still available.

**Comment by ShadaW11** [comment]
Hello @IsaacThaJunior are you still interested in working on this?

**Comment by IsaacThaJunior** [comment]
Yes @ShadaW11 I am still interested in working on this

**Comment by ShadaW11** [comment]
Perfect, @IsaacThaJunior please go ahead and start working on it.

If this is your first article update please register [here](https://strapi.io/write-for-the-community) before you get started.

Once you register, please go over the guidelines [here](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md)

If this is your first article update please review this guide quick before you get started. https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d

Please reach out if you have any questions.

**Comment by ShadaW11** [comment]
@IsaacThaJunior any update

**Comment by IsaacThaJunior** [comment]
@ShadaW11 it's coming along fine. I just encountered some issues with accessing deeply nested data even with the ?populate=* param in the search query. I am trying out some solutions and will submit a draft of the article by Friday.

**Comment by IsaacThaJunior** [comment]
@ShadaW11 Here is a link to the finished article. Do let me know if there are any issues.

https://www.dropbox.com/scl/fi/0ao2z1ldc7xtphxd0f8h0/V4-Tutorial-Update.paper?dl=0&rlkey=p3bu58e8qwtln8tg5xksehon6

**Comment by dessireugarte** [comment]
Hello @IsaacThaJunior  👋
Just wanted to confirm you submitted your invoice and got your payment.

**Comment by IsaacThaJunior** [comment]
@dessireugarte Yes i did. My apologies for the late reply

**Comment by dessireugarte** [comment]
Awesome 🎉
