### ISSUE TITLE
[UPDATE] How to Build a CSS Tricks Website Clone with Strapi and Next.js

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#753]
Hello 👋

This [article](https://strapi.io/blog/building-a-css-tricks-website-clone-with-strapi-next-js) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by chyke007** [comment]
This article has been updated @TiaraOluwanimi

**Comment by PaulBratslavsky** [comment]
I am closing this issue since it looks like it has been completed already.
