### ISSUE TITLE
[UPDATE] How to Build a Secure To-do App using Nuxt.js, Strapi, and Magic

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#754]
Hello 👋

This [article](https://strapi.io/blog/how-to-build-a-secure-to-do-app-using-nuxt-js-strapi-magic) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by Marktawa** [comment]
I am interested in updating this article.

**Comment by ShadaW11** [comment]
@Marktawa please complete your first article that is assigned to you and then you can start working on other ones.

**Comment by hubertnare** [comment]
Hey @PaulBratslavsky 

The plugin, Magic, hasn't been maintained for at least a year. So, my thinking is long periods of zero maintenance; 1. brings security concerns 2. Compatibility issues (in this context version 4 support issues).

**Comment by PaulBratslavsky** [comment]
Closing due to https://www.npmjs.com/package/strapi-plugin-magic not having a v4-supported Strapi plugin.
