### ISSUE TITLE
[UPDATE] How to Build a CRUD App with React and a Headless CMS

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#755]
Hello 👋

This [article](https://strapi.io/blog/how-to-build-a-crud-app-with-react-and-a-headless-cms) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by lucky4242** [comment]
Hi,
I would love to work on this article

**Comment by ShadaW11** [comment]
Hello @lucky4242 someone else is working on this, I sent you some suggestions on discord.

**Comment by hubertnare** [comment]
I will work on this article.

**Comment by Qodestackr** [comment]
I can work on this. How do I join slack or discord??

**Comment by ShadaW11** [comment]
Hello @Qodestackr, Hubert is updating this article but there are many articles that you can work on. To join our discord, please click [here](https://discord.com/invite/strapi)

**Comment by ShadaW11** [comment]
@hubertnare any update on the article?

**Comment by ShadaW11** [comment]
https://www.dropbox.com/scl/fi/769p1wvqggcrfmlnht2wo/How-to-Build-a-CRUD-App-with-React-and-a-Headless-CMS.papert?dl=0&rlkey=r7l0alucwhoaatekt7whvs9vh @TiaraOluwanimi ie for review

**Comment by ShadaW11** [comment]
@hubertnare please submit your invoice

**Comment by hubertnare** [comment]
Done!
