### ISSUE TITLE
[UPDATE] Build a To-Do App with Strapi GraphQL Plugin and Flutter

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#756]
Hello 👋

This [article](https://strapi.io/blog/build-a-to-do-app-with-strapi-graph-ql-plugin-and-flutter) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by maxiggle** [comment]
Do you need the original writer to update it or someone else can do?

**Comment by maxiggle** [comment]
Please do you need someone to do the update or the original author

**Comment by maxiggle** [comment]
Alright, I will work on it.
I am pretty much familiar with flutter

**Comment by ShadaW11** [comment]
Hello @maxiggle are you still interested in updating this article?

**Comment by maxiggle** [comment]
Yes I am

**Comment by ShadaW11** [comment]
Perfect, please go ahead and start working on it @maxiggle

**Comment by ShadaW11** [comment]
If this is your first article update please review this guide quick before you get started. https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d

**Comment by maxiggle** [comment]
Ok sure thing

**Comment by ShadaW11** [comment]
@maxiggle any update

**Comment by maxiggle** [comment]
I am on the project, I am kinda rebuilding the app and changing some contents

**Comment by maxiggle** [comment]
Yes
I am still working on it please

**Comment by dessireugarte** [comment]
Hello @maxiggle 👋
Just wanted to check if you are still interested in updating this article?
