### ISSUE TITLE
[UPDATE] Social Authentication with Strapi & Nuxt.js: Getting Started (1/3)

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#757]
Hello 👋

This [article](https://strapi.io/blog/social-authentication-with-strapi-and-nuxt-js-getting-started) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by miracleonyenma** [comment]
Hey @ShadaW11 👋🏾
I'm interested in updating this article

**Comment by ShadaW11** [comment]
@miracleonyenma ive informed the writer that was supposed to work on this article - if he doesn't get back to me - ill let you know asap

**Comment by miracleonyenma** [comment]
Awesome. Thanks ✨

**Comment by dessireugarte** [comment]
Hello @miracleonyenma 👋
Are you still interested in writing this series?

**Comment by miracleonyenma** [comment]
Hey @dessireugarte 👋🏾

Absolutely, I'm interested.
Can I go ahead?

**Comment by dessireugarte** [comment]
Yes please @miracleonyenma!
Let us know when you have a draft :)

**Comment by lucky4242** [comment]
Hi @PaulBratslavsky 
I would love to update this article, if its still available.
Thanks.

**Comment by lucky4242** [comment]
hello @PaulBratslavsky can i work on this ?

**Comment by PaulBratslavsky** [comment]
@lucky4242 that will be awesome.  I will assign this update to you.

**Comment by dessireugarte** [comment]
@lucky4242 could you condense it into two parts article? The first and last parts would better fit in one part instead of two. Also, the update for everything would be $150. Would that work on your end?

**Comment by lucky4242** [comment]
Hi @PaulBratslavsky.
ok

**Comment by lucky4242** [comment]
Hi @dessireugarte.
I can't say whether I can condense it right now because there's a chance I'll add additional features and writings to it because it's an outdated article.
But I have started working on it.

**Comment by PaulBratslavsky** [comment]
@lucky4242 hope you are well.  Just wanted to check in and see how you are doing on the update?

**Comment by lucky4242** [comment]
Hi @paul Bratslavsky.
I am ok from my end. And i am still working on the article. should be done
by next week.

**Comment by PaulBratslavsky** [comment]
@lucky4242 thank you.

**Comment by hanakhelifa** [comment]
Hello @lucky4242, and thanks for updating the series as well as adding some additional features. 
I joined Strapi a few weeks ago, and I'll be working with Paul on the Write for the Community program. I wanted to check in with you, do you have everything to finish the article? Let us know when it's good for a review.

**Comment by hanakhelifa** [comment]
As we are revamping the Write For the Community program, we'll pause incoming request. I see that here, there is no draft yet, so I will close this issue. I'll make sure to come back to you to present the new program. Feel free to reach out to me on Discord (same name as here) if you have any question.

**Comment by lucky4242** [comment]
hi @hanakhelifa 
i had issue with my system  but now am done with it the update

**Comment by hanakhelifa** [comment]
Update (as we were talking by email): @lucky4242 is done updating the article, and we'll publish the three updates of the article in the two upcoming weeks. :)
