### ISSUE TITLE
[UPDATE] Pagination in Strapi using GraphQL

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#758]
Hello 👋

This [article](https://strapi.io/blog/pagination-in-strapi-using-graph-ql) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by ath34-tech** [comment]
Hey, I am interested in writing article on this topic, if this is available i am more than happy to write.

**Comment by ath34-tech** [comment]
@PaulBratslavsky @TiaraOluwanimi  can i take this topic?

**Comment by divofred** [comment]
@PaulBratslavsky @dessireugarte, I am interested in taking up this update.

**Comment by PaulBratslavsky** [comment]
@divofred just assigned it to you

**Comment by divofred** [comment]
Hello @PaulBratslavsky @dessireugarte @TiaraOluwanimi, I am done with this update.
[Here ](https://www.dropbox.com/scl/fi/buij8rdfcfvz82jxi4o0p/Pagination-in-Strapi-using-GraphQL.paper?dl=0&rlkey=bjo1mzej0o5eor05307xk4zc7) is the Dropbox link.

**Comment by dessireugarte** [comment]
Thanks @divofred. We will review the draft 👍

**Comment by divofred** [comment]
Hello @dessireugarte, What's the update on this article?

**Comment by dessireugarte** [comment]
Hello @divofred   👋
Just wanted to let you know that your article will be published around the second week of December. I'll let you know if we need any changes or when it is published!

**Comment by dessireugarte** [comment]
Hello @divofred 👋 
Your article is [live](https://strapi.io/blog/how-to-add-pagination-in-strapi-using-graph-ql)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform). 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!
