### ISSUE TITLE
[UPDATE] The new way to generate a Strapi application

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#760]
Hello 👋

This [article](https://strapi.io/blog/the-new-way-to-generate-a-strapi-application) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by Vic-Orlands** [comment]
Can I write on the update, i.e if it is free

**Comment by ShadaW11** [comment]
I believe the article needs to be expanded as it will be updated - its pretty old - what do you think we can add to it? @Vic-Orlands

**Comment by IsaacThaJunior** [comment]
Hey there @ShadaW11 I am available to work on this if it is still open

**Comment by IsaacThaJunior** [comment]
Can i write on this if it is still available?

**Comment by Saintdavidking** [comment]
Hello, @TiaraOluwanimi  is this topic still available for update? I will love to update this article with the new version 4 release either with a video or just content

**Comment by Saintdavidking** [comment]
Hello, @dessireugarte  is this topic still available for update? I will love to update this article with the new version 4 release, please do let me know if it is still available

**Comment by dessireugarte** [comment]
Hello @IsaacThaJunior @Saintdavidking 👋 
Sorry for the late reply. Since @IsaacThaJunior wrote first, if you are still interested we can assign the update to you. Otherwise you can start @Saintdavidking

**Comment by IsaacThaJunior** [comment]
Hey there, I am still interested in writing this

**Comment by dessireugarte** [comment]
Great @IsaacThaJunior! 
I agree as well that it might need to be expanded a little. What would you cover on the update?

**Comment by Marvel-D** [comment]
Hello @dessireugarte 
I am interested in updating this article if it is still open.

**Comment by dessireugarte** [comment]
Hello @Marvel-D 👋
I will close this issue since now our documentation covers all this step-by-step. But if you are interested in writing an article, you could check the looking for author tag. Or on our discord, we have a Best Practices AMA video ( more to come ), and we would love to get some of those topics covered and translated into blog posts. You can find the video [here](https://discord.gg/JeQJcfEg8W).
