### ISSUE TITLE
[UPDATE] Understanding and Using Relations in Strapi

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#762]
Hello 👋

This [article](https://strapi.io/blog/understanding-and-using-relations-in-strapi) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by KanizoRGB** [comment]
Hello I can help with this

**Comment by miracleonyenma** [comment]
Hey @TiaraOluwanimi @ShadaW11, I would like to make a submission on this. Thanks!

**Comment by TiaraOluwanimi** [comment]
Hello, @miracleonyenma. Please, go ahead.

**Comment by ShadaW11** [comment]
Always add your dropbox link here on GitHub for future reference @miracleonyenma  https://www.dropbox.com/scl/fi/d7aqjbmcmc9lx0cbu7tge/Understanding-and-using-Relations-in-Strapi.paper?dl=0&rlkey=y03v2my67pt93f5wu95gduzzr

**Comment by miracleonyenma** [comment]
Oh, I'll keep that in mind. Thank you ✨

**Comment by ShadaW11** [comment]
@miracleonyenma Can you please submit your invoice?

**Comment by miracleonyenma** [comment]
@ShadaW11 👋🏾
I just submitted the invoice. Thanks
