### ISSUE TITLE
[SUBMIT]BUILD A 3D PORTFOLIO WEBSITE WITH VITE, REACT,THREE.JS AND STRAPI

### ISSUE THREAD

**Issue by oyedeletemitope** [strapi/community-content#764]
**My resource**

The most visually mind-blowing website in the world all tend to follow a similar pattern. They use 3d animations that bring the content to life when a page is scrolled. In this tutorial, we’ll build a 3d portfolio using Vite, React, Three.js and Strapi. A portfolio is a collection of photos or photographs of examples of your works used when entering competitions or applying for jobs. Your portfolio website is likely to be the first place someone goes after reading your CV, so it’s vital to make a great first impression.

Outline
Introduction
What is Vite
What is Three.js
What Strapi is
Building the portfolio
Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Love the idea, can you please start working on it? @oyedeletemitope

**Comment by oyedeletemitope** [comment]
Yes, I’ll get started on this right away

**Comment by oyedeletemitope** [comment]
Hello @ShadaW11  here is a link to the article

https://www.dropbox.com/scl/fi/10b0pn792zeari0j4q6iw/Build-a-simple-3d-portfolio-with-Vite-React-Three.js-and-Strapi.paper?dl=0&rlkey=cfjouydk6ups09r09939n0czt

**Comment by ShadaW11** [comment]
@oyedeletemitope awesome, thank you so much. Someone from our team will review your article asap

**Comment by TiaraOluwanimi** [comment]
@oyedeletemitope, I left comments for you on the doc. Please, check them and attend to them. Thanks!

**Comment by oyedeletemitope** [comment]
Hello @TiaraOluwanimi  I have attended to them all. Do let me know if there's anything else

**Comment by oyedeletemitope** [comment]
Hello @TiaraOluwanimi any update on the article?

**Comment by oyedeletemitope** [comment]
Hello please I submitted an invoice for this article weeks back and I haven’t seen anything. I just want to ask if the payment has been initiated or I submit a new invoice.

**Comment by dessireugarte** [comment]
Hello @oyedeletemitope 👋
Sorry for the late reply. Have you received news about your payment?

**Comment by oyedeletemitope** [comment]
Yes. Thank you I’ve received it

**Comment by dessireugarte** [comment]
Awesome! 👏
