### ISSUE TITLE
[Static website vs Dynamic website]

### ISSUE THREAD

**Issue by Saintdavidking** [strapi/community-content#768]
Proposed Topic:  Static website vs Dynamic website

I will drop outline if the topic is approved, i hope it is approved

**Comment by IsaacThaJunior** [comment]
I would love to write on this if the topic is still available

**Comment by ShadaW11** [comment]
Hello @Saintdavidking can you please submit an outline to better assess the value/fit of the article?

**Comment by Saintdavidking** [comment]
Topic: 

Static website vs Dynamic website

Outline:

1. Introduction to Website
2. What is a Static website
3. What is a Dynamic website
4. Advantages and Disadvantages of a Static website
5. Advantages and Disadvantages of a Dynamic website
6. Examples of Static and Dynamic Website
7. Static Website vs Dynamic Website: The difference
8. Conclusion

**Comment by ShadaW11** [comment]
@Saintdavidking can you please include how Strapi will be mentioned within the above outline.

**Comment by Saintdavidking** [comment]
Topic: 
Static website vs Dynamic website

Outline:

1. Introduction to Website
2. What is a Static website:
**Benefits of Strapi in a Static website
4. Dynamic and Static building tools using Strapi
-What is Strapi 
-How to install Strapi 
-How to manage static website content in Strapi 
-How to manage dynamic content in Strapi

5. What is a Dynamic website
**Benefits of Strapi in Dynamic Website.

6. Advantages and Disadvantages of a Static website
7. Advantages and Disadvantages of a Dynamic website.
8. Examples of Static and Dynamic Website.
9. Static Website vs Dynamic Website: The difference
10. Conclusion

**Comment by Saintdavidking** [comment]
Hello @ShadaW11  this is the link to the article
https://www.dropbox.com/scl/fi/gltn24l7e9v3b996x4g6x/Static-vs-dynamic.paper?dl=0&rlkey=vbq87bai6b0phksb7os4y7jbc

**Comment by TiaraOluwanimi** [comment]
@Saintdavidking, thanks for your patience. I'll review this asap and get back to you (via the doc).

**Comment by Saintdavidking** [comment]
Hello @TiaraOluwanimi, I have made some changes as required to the document and added the image, I am waiting for your feedback

**Comment by dessireugarte** [comment]
Hello @Saintdavidking   👋
Just wanted to let you know that your article will be published the second week of August so you can proceed to submit your invoice and get your payment.

**Comment by Saintdavidking** [comment]
Alright thanks @dessireugarte

**Comment by malgamves** [comment]
processed 🚀

**Comment by dessireugarte** [comment]
Your article is [live](https://strapi.io/blog/static-website-vs-dynamic-website) @Saintdavidking 🎉
Since you already submitted your invoice, you will get your payment soon. Feel free to reach out if you have any questions!
