### ISSUE TITLE
[SUBMIT] User Authentication with React and Strapi

### ISSUE THREAD

**Issue by marvelken** [strapi/community-content#770]
**User  Authentication with React and  Strapi**

**Introduction**

React is a popular choice for building complex web applications. Almost every web application requires user authentication. One of the popular options is to make use of a social login provider like Google or Facebook. Uniquely we can build authentication with React and Strapi backend.

**Goal**
In this article we are going to create a react login form that uses Strapi for its backend. this article is both beginner and intermediate level developer-friendly.

**Outline**
- Preparing development area 
- creating a new strapi application
- Starting App State
- Create the Login component
    -  Adding React Hooks
    - Starting the JSX
    - Username Input
    - Password Input
- Finish the form
    -  handle submit function
    -  Displaying the success screen
    - Testing the form 
-  Creating Auth context and state
- Conclusion

-->

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
Thank you for submitting the outline @marvelken interesting - im just thinking that we have had some similar articles published already on the blog, maybe we can develop / add functionality in this tutorial? here's a link to our blog - https://strapi.io/blog - @TiaraOluwanimi what do you think?

**Comment by marvelken** [comment]
Hi Shada,
So sorry for the belated reply, I have been shocked up with work. About the
article I feel there are much differences, maybe writing it will show how
different they both are, Should I go on?

**Comment by Sachin-chaurasiya** [comment]
Hey @ShadaW11, I would like to work on this issue.

**Comment by Namankataria01** [comment]
Hey Guys i am looking for this for months i can't even find a single tutorial on this .
you can aslo add how to persist user in react

**Comment by dessireugarte** [comment]
Hello @marvelken 👋
Are you still available to write this article?

**Comment by dessireugarte** [comment]
Hello @Sachin-chaurasiya 👋
Are you still interested in writing this article?

**Comment by Sachin-chaurasiya** [comment]
> Hello @Sachin-chaurasiya 👋 Are you still interested in writing this article?

Hello @dessireugarte, Yes, I would love to 💯 .
Please assign this issue to me.

**Comment by Namankataria01** [comment]
Hey @Sachin-chaurasiya  can you help me with thit issue ?

**Comment by Namankataria01** [comment]
> **User Authentication with React and Strapi**
> 
> **Introduction**
> 
> React is a popular choice for building complex web applications. Almost every web application requires user authentication. One of the popular options is to make use of a social login provider like Google or Facebook. Uniquely we can build authentication with React and Strapi backend.
> 
> **Goal** In this article we are going to create a react login form that uses Strapi for its backend. this article is both beginner and intermediate level developer-friendly.
> 
> **Outline**
> 
> * Preparing development area
> * creating a new strapi application
> * Starting App State
> * Create the Login component
>   
>   * Adding React Hooks
>   * Starting the JSX
>   * Username Input
>   * Password Input
> * Finish the form
>   
>   * handle submit function
>   * Displaying the success screen
>   * Testing the form
> * Creating Auth context and state
> * Conclusion
> 
> -->
> 
> **My content is**
> 
> * [ ]  A Strapi Tutorial / Guide / How to article
> 
> **What do you all think?** ❤️ I love it! 🚀 I can help you!
> 
> Thank you for submitting your article proposal.

Also the user persistance

**Comment by dessireugarte** [comment]
Great @Sachin-chaurasiya! If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form. Then please scroll to the FAQ section and review the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md), how to submit an article, issue an invoice and get paid.

Before getting started, can you confirm what the outline would look like?

**Comment by Sachin-chaurasiya** [comment]
> Great @Sachin-chaurasiya! If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form. Then please scroll to the FAQ section and review the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md), how to submit an article, issue an invoice and get paid.
> 
> Before getting started, can you confirm what the outline would look like?

Thanks, @dessireugarte, I will do that.
Should I share the outline here or somewhere else?

**Comment by Sachin-chaurasiya** [comment]
> Great @Sachin-chaurasiya! If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form. Then please scroll to the FAQ section and review the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md), how to submit an article, issue an invoice and get paid.
> 
> Before getting started, can you confirm what the outline would look like?

@dessireugarte I have filled the form, please check.

**Comment by dessireugarte** [comment]
Thanks @Sachin-chaurasiya ! You share the outline here please

**Comment by Sachin-chaurasiya** [comment]
> Thanks @Sachin-chaurasiya ! You share the outline here please

Yes, I will share it here!

**Comment by Sachin-chaurasiya** [comment]
@dessireugarte Here is the outline for the topic.

**Topic:**  **User Authentication with React and Strapi**

**Outline:**  

- Introduction
    - About the topic
    - About the project that we will be building
- Setting up the development environment
- Creating a new strapi application
- Creating Collections
- Creating Relations between collections
- Creating React Application
- Installing required dependencies
- Creating Auth context for managing current user
- Creating Auth forms
    - SignIn
    - SignUp
- SignUp flow
    - User inputs
    - Error handling
    - Displaying Success screen
- SignIn Flow
    - User inputs
    - Error handling
    - Displaying Success screen
- Logout flow
- Conclusion

**Comment by Sachin-chaurasiya** [comment]
@dessireugarte, Any update?

**Comment by dessireugarte** [comment]
Hello @Sachin-chaurasiya 👋
Thanks for the outline. 
You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x).

Once your article is ready, please share the dropbox link to your article in a comment on this GitHub issue.

**Comment by Sachin-chaurasiya** [comment]
> Hello @Sachin-chaurasiya 👋 Thanks for the outline. You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x).
> 
> Once your article is ready, please share the dropbox link to your article in a comment on this GitHub issue.

Sure @dessireugarte, Thank you 🚀 .

**Comment by Sachin-chaurasiya** [comment]
Hey @dessireugarte , Just to provide an update.
I'm almost finished with the draft, I will share the draft link by Wednesday (IST).
Thank you!

**Comment by dessireugarte** [comment]
Awesome! Thanks for the update! 👍

**Comment by Sachin-chaurasiya** [comment]
Hello @dessireugarte , Here is the link for the draft article.
Please share your feedback.
https://www.dropbox.com/scl/fi/97wv008otqhpdqd8hsvcw/User-Authentication-with-React-and-Strapi-v4.paper?dl=0&rlkey=17e291tpv7llqio3kyj2l6dga

**Comment by Sachin-chaurasiya** [comment]
Thanks for the review @TiaraOluwanimi, excited to see my first article on the strapi blog 🚀 .

**Comment by Sachin-chaurasiya** [comment]
Hello @dessireugarte , Is there any update on when we are publishing this article?

**Comment by dessireugarte** [comment]
Hello @Sachin-chaurasiya  👋
Just wanted to let you know that your article will be published around the third week of October. I'll let you know when it is published!

**Comment by Sachin-chaurasiya** [comment]
> Hello @Sachin-chaurasiya 👋 Just wanted to let you know that your article will be published around the third week of October. I'll let you know when it is published!

Hello, @dessireugarte 👋 Thanks for the update.

**Comment by dessireugarte** [comment]
Hello @Sachin-chaurasiya  👋 
Your article is [live](https://strapi.io/blog/strapi-authentication-with-react)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by Sachin-chaurasiya** [comment]
> Hello @Sachin-chaurasiya 👋  Your article is [live](https://strapi.io/blog/strapi-authentication-with-react)! 🎉 Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you! Please feel free to reach out to me if you have any questions!

Thank you so much @dessireugarte 🚀 . 
Looking forward to more contributions.
