### ISSUE TITLE
connecting my express app to strapi

### ISSUE THREAD

**Issue by Emmaroeneyoh** [strapi/community-content#772]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by DesmondSanctity** [comment]
I can write on this topic

**Comment by muyiwexy** [comment]
@ShadaW11 Hello there, I will like to write on this topic.

**Comment by divofred** [comment]
@muyiwexy I don't think using Express with a Headless CMS like Strapi will be great.
I think Strapi is trying to make API applications serverless.

**Comment by sammychris** [comment]
Hello @ShadaW11, I would like to write on this topic.

**Comment by sammychris** [comment]
In this article, I will create an issue tracker app using express. And make use of Strapi API to help manage data and its states. 

The App will allow users to make, find, update and delete an issue. Each issue will have a unique id. This gives each user access to the issue they created.

The app will allow just 3 issues per IP address in a day.
Strapi CMS will manage every issue information, IP addresses, users name, and issue current state. This is where an admin can either resolve or reject an issue.

The issues will contain 3 statuses: pending, resolved, or reject. Depending on how long it took the Strapi Admin to respond.
Most of the interactions with the app will be done via Postman.

Here is an example:
Outline

    Introduction
    What is Strapi?
    Setting up a Strapi project
    Shallow dive into node and express
    Building our App
    Connecting our express App to Strapi via API
    Fetching API data from Strapi
    Posting API data to Strapi
    Testing the App
    Conclusion
    Resources

Please, just in case there are any suggestions or adjustments, I will gladly make changes right away.
Thanks...

**Comment by ShadaW11** [comment]
I agree with @divofred - any feedback on the outline suggest by Sammychris, thank you @sammychris interesting outline, im just thinking about the use case and how we can add some interesting functionality.

**Comment by ShadaW11** [comment]
@sammychris Any feedback?

**Comment by sammychris** [comment]
Still on it. I will let you know when I'm through. Thanks

**Comment by Abdull600** [comment]
Has anyone written about this article?

**Comment by dessireugarte** [comment]
Hello @sammychris 👋
Are you still interested in writing this article?

**Comment by sammychris** [comment]
Yes, Sorry I took too long. Hopefully before the end of next week.

**Comment by dessireugarte** [comment]
No worries @sammychris!
I will assign you the issue and change the status then 👍

**Comment by dessireugarte** [comment]
Hello @sammychris 
Unfortunately, this topic has taken too long so we will close the issue.
