### ISSUE TITLE
Data Import => I have some data in a strapi installation v4. After I generate a new strapi folder using npx create-strapi...... I wish to import the data from the previous installation to this new one. But despite,  taking the backup of the database , pointing the new installation to the the database , dropping the database and restoring its content through the backup, using the strapi default database sqllite taking its backup and restoring to postgres, nothing has worked so far. Is there a way to overcome this  ?

### ISSUE THREAD

**Issue by mpalsule** [strapi/community-content#774]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ShadaW11** [comment]
Hello @mpalsule thank you for reaching out. Can you please post this message on our discord channel - in order to get the right support - this is the channel for the WFC Program. If you are following a certain tutorial and getting this error. please reach out.
