### ISSUE TITLE
STRAPI SOCKET.IO: server.listeners is not a function

### ISSUE THREAD

**Issue by jetmaquiling** [strapi/community-content#777]
Took me two days to figure out what was the problem with my server after updating to version 4. 
You might get an error saying "server.listening is not a function".
To solve the problem you will just simply change a the socket directory in the boostrap.js file.
-----------------------------------------------------------------------
WORKS FOR VERSION 3 ONLY
var io = require("socket.io")(strapi.server, {
    cors: {
      origin: [
        localhost:3000
      ],
      methods: ["GET", "POST"],
      allowedHeaders: ["my-custom-header"],
      credentials: true,
    },
  });
-----------------------------------------------------------------------
WORKS FOR VERSION 4 
var io = require("socket.io")(strapi.server.httpServer, {
    cors: {
      origin: [
        localhost:3000
      ],
      methods: ["GET", "POST"],
      allowedHeaders: ["my-custom-header"],
      credentials: true,
    },
  });

instead of "strapi.server" use "strapi.server.httpServer"
-----------------------------------------------------------------------
thats all thank you I hope it helps....

**Comment by ShadaW11** [comment]
Hello @jetmaquiling which tutorial where you were reviewing when you came across this issue?
