### ISSUE TITLE
[SUBMIT] Create a Simple To-Do List Application With Strapi and ReactJS

### ISSUE THREAD

**Issue by TheGhoulRe** [strapi/community-content#791]
**My resource**

This article covers the following
* Building simple RESTful APIs with Strapi
* Integrating React frontends with Strapi
* Communicating between frontend and backend

The to-do list application is a very simple application, which I think accurately covers the above. It involves creating collections, manipulating items, and creating RESTful APIs using the collections. Majority of what is done using Strapi are manipulating collections and creating APIs, which makes this project very useful.

Outline
Introduction
What is Strapi?
Setting up Strapi
Build the backend
Setting up React
Build the frontend
Integrating the frontend with Strapi
Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by TheGhoulRe** [comment]
Hi @ShadaW11, I have the draft for my article prepared here:

https://www.dropbox.com/scl/fi/92rlbxg8fwn6nmclmakp8/How-to-build-a-To-Do-list-application-with-Strapi-and-ReactJS.paper?dl=0&rlkey=yducqqac7wgjm2eq2n3w0k7y1

**Comment by ShadaW11** [comment]
Hello @TheGhoulRe Thank you for submitting the article, we usually cross check that the content you submit does not already exist on our blog before asking you to proceed working on your article. 

I will get back to you with feedback on our reviewer checks your article. For next time, please wait for the feedback from our team before working on an article.

**Comment by TheGhoulRe** [comment]
Hi, @TiaraOluwanimi. I have added the link to the repo for this article.

**Comment by dessireugarte** [comment]
Hello 👋
[Your article](https://strapi.io/blog/how-to-build-a-to-do-list-application-with-strapi-and-react-js) is already available in the Strapi blog. Sorry for the delay with this article. 
Please submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) to receive your payment.

**Comment by malgamves** [comment]
processed ⚡
