### ISSUE TITLE
Straps import

### ISSUE THREAD

**Issue by lifeofgurpreet** [strapi/community-content#792]
Your import tutorial doesn't work in version 4. A lot of people need importing with a database please help update your tutorial for it

**Comment by ShadaW11** [comment]
Hello @lifeofgurpreet can you please share with me the link of the tutorial and we will update it asap?

**Comment by PaulBratslavsky** [comment]
We currently have this plugin on the market place https://market.strapi.io/plugins/strapi-plugin-import-export-entries and currently working on a feature that will make this easier in the future.  For now, we are closing this issue.
