### ISSUE TITLE
Strapi tutorial with Node.js, Express.js and Mongodb (without React.js)

### ISSUE THREAD

**Issue by Shubham-731** [strapi/community-content#794]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by sammychris** [comment]
A simple journal app, created using Node, Express, MongoDB, and Strapi. This app will contain a user registration and login route. This user data will be stored in MongoDB. After the user is logged in, the authenticated user will then have the access to create, update and delete its own journals. Strapi will manage the data of the journals.

Question: Should I install Strapi and Use MongoDB Atlas as Default Database? or should I use MongoDB separately just like the article?

Here is an example:
Outline

    Introduction
    What is Strapi?
    Setting up a Strapi project
    Shallow dive into the node, express, and MongoDB
    Building our App
    Connecting our express App to Strapi via API
    Testing the App
    Conclusion
    Resources

**Comment by ShadaW11** [comment]
Hello @sammychris we have already existing journal apps published on the blog. We are currently looking to have v4 supported tutorials therefore using MongoDB is not an option.
