### ISSUE TITLE
[TOPIC] Custom Query Examples

### ISSUE THREAD

**Issue by ibdf** [strapi/community-content#80]
The custom query section is very vague. A few examples would go a long way.

**Comment by Mcastres** [comment]
Hello @ibdf. What do you mean exactly wit the custom query section?

**Comment by ibdf** [comment]
@Mcastres I've been reading the docs, when I get to the custom query sections (https://strapi.io/documentation/3.0.0-beta.x/concepts/queries.html#custom-queries) it tells me I need to use the underlying ORM models. It even gives me some simple examples, but it doesn't tell me where any of it goes. Where do I write these custom queries? What folder/file? Is there a function I call? What params are passed? If the docs have this information elsewhere, then maybe add a link.

It would be great to have a full example on how to create your own queries.

Thanks.

**Comment by lauriejim** [comment]
`strapi.query` is used to request your database everywhere.
For example, when you have a request to your API endpoint it's:
route > controller > service > query
See the content of default service functions - [docs](https://strapi.io/documentation/3.0.0-beta.x/concepts/services.html#core-services)

In custom query docs, you access to `strapi.query(modelName, plugin).model` witch is the instance of the ORM you are using (Bookshelf for SQL databases or Mongoose for Mongo)
Then there is not specific params, you are just following the Bookshelf or Mongoose docs to execute the request you want to do.
