### ISSUE TITLE
[Request New Content] E-commerce, with inventory management backend.

### ISSUE THREAD

**Issue by uamin** [strapi/community-content#805]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ShadaW11** [comment]
Can you please explain more what functionalities you are looking for? @uamin

**Comment by Claradev32** [comment]
Hi @ShadaW11,
If this topic is available, I can work on it.

Thanks

**Comment by dessireugarte** [comment]
Hello @Claradev32 👋
If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form? Then please scroll to the FAQ section and review the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md), how to submit an article, issue an invoice and get paid.
Before getting started, can you provide an outline of what you were thinking of covering?

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 👋
Great! Could you please share the outline you propose for this topic?

**Comment by ibn-ashimi** [comment]
Sure. Sending soon.

**Comment by ibn-ashimi** [comment]
https://www.dropbox.com/scl/fi/ugg6paeopt44t2mlq3hj3/E-commerce-with-inventory-management-backend.paper?dl=0&rlkey=nwhc4q0clrvkm0vwobbsc3dd8

@dessireugarte my outline.

**Comment by dessireugarte** [comment]
Hello @Mcastres and @PaulBratslavsky 
This is the outline proposed by @ibn-ashimi 

Outline:
- Introduction
- What is Strapi
- Prerequisites
- Project setup
- Backend Setup
- Creating Frontend layout
- Product Page
- Cart Page
- Handing Payments
- Deployments
- Conclusion

Could you please take a look?

**Comment by Mcastres** [comment]
What E-commerce solution are you going to use?

**Comment by PaulBratslavsky** [comment]
@ibn-ashimi let us know if you are still interested in writing this article and what e commerce solution you were going to use?

**Comment by ibn-ashimi** [comment]
Hi @PaulBratslavsky @Mcastres 

I need to re-understand this. I assumed I'm supposed to build an E-commerce platform utilizing Strapi. Is there a need for a third party Ecom solution?

**Comment by ibn-ashimi** [comment]
Hi @PaulBratslavsky. For this, I will use snipcart.

**Comment by Ashimi0x** [comment]
@PaulBratslavsky would you want me to go ahead with this?

**Comment by daacode** [comment]
@PaulBratslavsky @dessireugarte Can I work on this

**Comment by Ashimi0x** [comment]
@PaulBratslavsky @dessireugarte 

I will be using SnipCart. and my Outline goes as follows:

- Introduction
- Overview of Snipcart and Strapi
- Setting up the Development Environment
- Creating the Product Catalog in Strapi
- Designing and Implementing the Frontend
- Payment Integration with Snipcart
- Integrating Snipcart with Strapi
- Customizing the Snipcart Frontend
- Testing and Deploying the Integration
-  Conclusion 

and I will be working with this repository that I had just created:
[Inventory-Commerce](https://github.com/Ashimi0x/inventory-commerce)

**Comment by Ashimi0x** [comment]
Hello @PaulBratslavsky @dessireugarte

**Comment by PaulBratslavsky** [comment]
@Ashimi0x hope you are well.  We are finally catching up with our back log of articles.  I know it has been a while.  If you are still interested in writing this article you can start.  Just confirm here that you got my message.

**Comment by Ashimi0x** [comment]
@PaulBratslavsky  absolutely! I will get to it.

**Comment by hanakhelifa** [comment]
@Ashimi0x Hi there, do you have a draft or an ETA to share with us?

**Comment by Ashimi0x** [comment]
Yes, I will give you a draft by tuesday.

**Comment by lucky4242** [comment]
hi @hanakhelifac. 
I am done with one of the tutorial updates but it has been removed from the issue board. how can i make contact on discord?

**Comment by Ashimi0x** [comment]
Oh Absolutely! You haven't responded to me yet on Discord.

**Comment by vcoisne** [comment]
@Ashimi0x did you ever write a draft for this ?
