### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Registration and Login (authentication) with Vue.js and Strapi

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#808]
**Description**

https://strapi.io/blog/registration-and-login-authentication-with-vue-js-and-strapi

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by chyke007** [comment]
I can work on this

**Comment by Marienoir** [comment]
Hello @ShadaW11 
I would like to update this content. 
Please confirm so I can send in the proposed outline.

**Comment by ShadaW11** [comment]
@chyke007 apologies for the delay, are you still interested in working on this?

**Comment by chyke007** [comment]
Yes

**Comment by ShadaW11** [comment]
Perfect, please go ahead and start working on it. @chyke007

**Comment by ShadaW11** [comment]
@chyke007 any update

**Comment by chyke007** [comment]
i am almost done with this article, just some few errors to fix, hopefully tomorrow I should submit the draft

**Comment by chyke007** [comment]
@ShadaW11 the draft: https://www.dropbox.com/scl/fi/akbrgp1kkpfkj168hxi4g/V4-Tutorial-update(Registration-and-Login-(authentication)-with-Vue.js-and-Strapi).paper?dl=0&rlkey=bppr24mh45aosa8uy23c1ezbm


Would update the repo to point to a new one later in the day

**Comment by ShadaW11** [comment]
@chyke007 perfect thank you

**Comment by chyke007** [comment]
@TiaraOluwanimi can you please review as i have updated the content with the needed changes

**Comment by TiaraOluwanimi** [comment]
Hey, @chyke007. It's already been reviewed. You'll be notified once it is published. :)

**Comment by chyke007** [comment]
Apologies @TiaraOluwanimi I meant the other article on react

**Comment by dessireugarte** [comment]
Hello @chyke007 👋 
I just wanted to double-check if you have submitted your invoice and received news about your payment with this article?
Could you share the issue of the react article you mean, please?

**Comment by chyke007** [comment]
Hi, @dessireugarte I haven't yet submitted an invoice for this yet as I intended to submit for 2 articles: this, and https://github.com/strapi/community-content/issues/811.


The react article(https://github.com/strapi/community-content/issues/811) needed to update some packages and change the structure to suit this, I completed the work on that last month.

**Comment by dessireugarte** [comment]
Could you please submit your invoice using [this](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) form?
I am giving a follow up to the other article and will get back to you if we need anything else or when we post it 👍

**Comment by chyke007** [comment]
How much is it again for an update? @dessireugarte

**Comment by dessireugarte** [comment]
Hello @chyke007 👋
Compensation for v4 updates will be 70USD  - exceptions apply for tutorial series. More information [here](https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d)
