### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Strapi’s User Roles and Permissions for Admin Panel

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#809]
**Description**

https://strapi.io/blog/strapi-s-user-roles-and-permissions-for-admin-panel

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Marktawa** [comment]
I would like to work on this.

**Comment by ShadaW11** [comment]
@Marktawa thank you for sending over the outline. Please ping me once you complete working on the other issue assigned to you and then we can explore other opportunities.

**Comment by icode247** [comment]
Hi @ShadaW11 
I can work on this.

**Comment by ShadaW11** [comment]
@icode247 please go ahead and work on this

**Comment by icode247** [comment]
Yes, am rounding up today. I will send it over tomorrow.

**Comment by icode247** [comment]
Hi @ShadaW11 ,
Here is the Dropbox link to the updated article. https://www.dropbox.com/scl/fi/2ngd3mqnbhaa3mionfaic/Strapi%E2%80%99s-User-Roles-and-Permissions-for-Admin-Panel.paper?dl=0&rlkey=p5csztcc3ndqfdid975vyggzb

**Comment by icode247** [comment]
Hi @ShadaW11 , @malgamves ,
I have not received any feedback on the payment for this article.

Thanks

**Comment by dessireugarte** [comment]
Hello @icode247 👋 Have you submitted your invoice and had news about your payment?
Let me know otherwise I'll ping the team

**Comment by icode247** [comment]
I have not. I have attached my invoices here. The invoice submission form is not working again.
[Ekekenta Odionyenfe Clinton June 27, 2022 How to Use and Create Services in Strapi (SMS & Email Services).pdf](https://github.com/strapi/community-content/files/9173258/Ekekenta.Odionyenfe.Clinton.June.27.2022.How.to.Use.and.Create.Services.in.Strapi.SMS.Email.Services.pdf)
[Ekekenta Odionyenfe Clinton June 27, 2022 Strapi’s User Roles and Permissions for Admin Panel.pdf](https://github.com/strapi/community-content/files/9173259/Ekekenta.Odionyenfe.Clinton.June.27.2022.Strapi.s.User.Roles.and.Permissions.for.Admin.Panel.pdf)

Thanks

**Comment by dessireugarte** [comment]
Thank you @icode247! 
@malgamves I add assign you this issue that is pending to receive the payment.

**Comment by malgamves** [comment]
Hey @icode247 the form is working fine ([try it again](https://forms.gle/LRYqaDUyGmS7DsLf6)) it helps us keep things organized. I'll put it through as soon as I get it.

**Comment by icode247** [comment]
Hi @malgamves,
I have submitted the forms for the payment.
Thanks
