### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Use and Create Services in Strapi ( SMS, Email Services)

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#810]
**Description**

https://strapi.io/blog/how-to-use-and-create-services-in-strapi-sms-email-services

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by icode247** [comment]
Hi @ShadaW11,
I can will update this blog.

**Comment by ShadaW11** [comment]
Hello @icode247 perfect. thank you

**Comment by icode247** [comment]
Hi @ShadaW11,
The draft is ready. https://www.dropbox.com/scl/fi/bk67f6jf0bmefv8pup6wr/How-to-Use-and-Create-Services-in-Strapi-(-SMS%2C-Email-Services.paper?dl=0&rlkey=ds2be8vxlbr80am2zalqhrs0p

**Comment by ShadaW11** [comment]
Thank you @icode247 we will be reviewing your article as soon as possible.

**Comment by ShadaW11** [comment]
@TiaraOluwanimi

**Comment by icode247** [comment]
Hi @ShadaW11 , @malgamves ,
I have not received any feedback on the payment for this article.

Thanks

**Comment by dessireugarte** [comment]
Hello @icode247 👋
Sorry for the delay! 
Your article is [live](https://strapi.io/blog/how-to-create-and-use-sms-and-email-services-in-strapi-1)! Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. Please feel free to reach out to me if you have any questions!
