### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Protected routes and Authentication with React and Node.js

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#811]
**Description**

https://strapi.io/blog/protected-routes-and-authentication-with-react-and-node-js

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by chyke007** [comment]
I can work on this

**Comment by TiaraOluwanimi** [comment]
Okay, @chyke007.

**Comment by chyke007** [comment]
Should I wait till it is assigned to me @TiaraOluwanimi?

**Comment by ShadaW11** [comment]
Hello @chyke007 yes please go ahead. I assigned it to you

**Comment by Qodestackr** [comment]
Hey can I implement this?

**Comment by chyke007** [comment]
https://www.dropbox.com/scl/fi/340s6evq812yhm0xd7lcv/V4-Tutorial-updateProtected-routes-and-Authentication-with-React-and-Node.js.paper?dl=0&rlkey=3f9czn8ugdf5fc5e7gr84fnzl

**Comment by ShadaW11** [comment]
@chyke007 a developer from our team is reviewing your merge request and will be resolved soon. thank you.

**Comment by chyke007** [comment]
@TiaraOluwanimi  can you please review as I have updated the content with the needed changes

**Comment by TiaraOluwanimi** [comment]
@chyke007, pls check the doc and make changes. Thanks

**Comment by dessireugarte** [comment]
Hello @chyke007 @TiaraOluwanimi 👋
Have the changes been made?

**Comment by chyke007** [comment]
I have made the changes

**Comment by dessireugarte** [comment]
@TiaraOluwanimi Could you let us know if the changes are ok? So we can post it in the blog 👍

**Comment by chyke007** [comment]
@dessireugarte @TiaraOluwanimi any updates on this. It's over 2 months since I submitted a draft.

**Comment by PaulBratslavsky** [comment]
@TiaraOluwanimi can you confirm that this article is ready to publish.

**Comment by TiaraOluwanimi** [comment]
@PaulBratslavsky. Yup, it is.

**Comment by chyke007** [comment]
@dessireugarte any update on the state of this article?

**Comment by PaulBratslavsky** [comment]
@TiaraOluwanimi I double checked the published article, it is still the old version and not the updated article.

**Comment by dessireugarte** [comment]
Hello @chyke007 👋
Sorry, for the big delay on this article. It was my bad and I apologize, thanks for letting us know. I scheduled it to be published in the first week of October. Please feel free to submit your invoice!

**Comment by dessireugarte** [comment]
Hello @chyke007  👋 
Your article is [live](https://strapi.io/blog/protected-routes-and-authentication-with-react-and-node-js-1)! 
Sorry for the delay in this article. Please feel free to reach out to me if you have any questions!

**Comment by chyke007** [comment]
Thanks for the help so far @dessireugarte
