### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Deploying and Scaling the Official Strapi Demo App "Foodadvisor" with Kubernetes & Docker

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#813]
**Description**

https://strapi.io/blog/deploying-and-scaling-the-official-strapi-demo-app-foodadvisor-with-kubernetes

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by FaithKovi** [comment]
Hello, @ShadaW11 I am interested in updating this article. I have signed up for the writer's program and also joined the discord channel.

**Comment by FaithKovi** [comment]
Hello, @ShadaW11 Any feedback on this?

**Comment by dessireugarte** [comment]
Hello @FaithKovi 👋
Sorry for the late reply, are you still interested in updating this article?

**Comment by FaithKovi** [comment]
Hello, @dessireugarte Yes, I am interested.

**Comment by dessireugarte** [comment]
If this is your first article update, please register [here](https://strapi.io/write-for-the-community) before you start and review this guide quickly before you get started. [https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d](https://www.notion.so/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d)

You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x).

Once your article is ready, please share the dropbox link to your article in a comment on this GitHub issue.

**Comment by FaithKovi** [comment]
My article is ready, this is the link
https://www.dropbox.com/scl/fi/v2cxi7tbd9d1wdn996hna/Deploying-and-Scaling-the-Official-Strapi-Demo-App-_Foodadvisor_-with-Kubernetes-Docker.paper?dl=0&rlkey=50t5t45x9oslc842xa61eebfo

**Comment by dessireugarte** [comment]
Hello @FaithKovi 👋
Thanks for sharing the draft. I assigned the issue to @TiaraOluwanimi to review your article.

**Comment by FaithKovi** [comment]
@TiaraOluwanimi I have made the changes.

**Comment by FaithKovi** [comment]
Hello @malgamves 
This article was published. I Submitted my invoice in September and I am yet to receive my pay.

**Comment by dessireugarte** [comment]
Hello @FaithKovi!
Have you received your payment?

**Comment by FaithKovi** [comment]
Yes @dessireugarte
