### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Build a Notion Clone With Strapi and Next.js 

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#814]
**Description**

https://strapi.io/blog/how-to-build-a-notion-clone-with-strapi-and-next-js (both parts)

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by ShadaW11** [comment]
[hubertnare](https://github.com/hubertnare) will be working on this article

**Comment by hubertnare** [comment]
Great! Working on it. Update en route.

**Comment by hubertnare** [comment]
Link to Part 1:
https://www.dropbox.com/scl/fi/ej9cojuduv504vr4q7q9n/How-to-build-a-Notion-clone-with-Strapi-4-and-Next.js-1_2.papert?dl=0&rlkey=f0eapxshgfv18780qca2xysi8

**Comment by hubertnare** [comment]
Link to Part 2 (Final Part of the article):

https://www.dropbox.com/scl/fi/e8btxz4l8yk88vpz3qsww/How-to-build-a-Notion-clone-with-Strapi-4-and-Next.js-2_2.papert?dl=0&rlkey=s9mk4hd3b3no55ft10orcr6x8

**Comment by ShadaW11** [comment]
Awesome work, thank you, we will review it asap and get back to you. @hubertnare

**Comment by ShadaW11** [comment]
@TiaraOluwanimi FYI

**Comment by dessireugarte** [comment]
Hello @hubertnare  👋 
Have you submitted your invoice?

**Comment by hubertnare** [comment]
Yeah but when Shada was still available

**Comment by dessireugarte** [comment]
Did you receive your payment?
cc @malgamves

**Comment by hubertnare** [comment]
The last time I checked, they said the invoice was processed. But, I didn't receive any payment.

**Comment by malgamves** [comment]
let's continue chatting on Discord
