### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Handling Previews in a Headless Architecture

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#815]
**Description**

https://strapi.io/blog/handling-previews-in-a-headless-architecture

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Marktawa** [comment]
I am interested in updating this article.

**Comment by ShadaW11** [comment]
@Marktawa  please complete your first article that is assigned to you and then you can start working on other ones.

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋 are you still interested in updating this article?

**Comment by Marktawa** [comment]
Hi @dessireugarte 
I am still interested in updating this article.

**Comment by dessireugarte** [comment]
Ok @Marktawa!
You can review this guide quickly before you get started. https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d

You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x).

Once your article is ready, please share the dropbox link to your article in a comment on this GitHub issue.

**Comment by Marktawa** [comment]
Hi @dessireugarte 

Here's the [completed draft](https://www.dropbox.com/scl/fi/1ospydoxgzty49t9ir0fo/Handling-Previews-in-a-Headless-Architecture.paper?dl=0&rlkey=8ipxbo0shl73iequan8ijju7r). and the [Github code repository](https://github.com/Marktawa/strapi-nextjs-previews).

I would also like to update this article on [Implementing Previews with Nuxt Applications using a Strapi backend](https://strapi.io/blog/implementing-previews-with-nuxt-applications-using-a-strapi-backend). It was referenced in the article I just updated, so it would make sense if it was also up to date. Should I create an issue for it?

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋 
Thanks for the draft, I add @TiaraOluwanimi to the thread so she can give a follow-up to this update. 
Regarding the other article, I created [this](https://github.com/strapi/community-content/issues/909) issue. Would you be interested in updating it? So I can assign it to you!

**Comment by Marktawa** [comment]
Ok, thanks @dessireugarte 

Yes, I am interested in updating the other article. I will ping you in the [issue thread.](https://github.com/strapi/community-content/issues/909)

**Comment by dessireugarte** [comment]
Great! Please go ahead! @Marktawa 👍

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋 
Just wanted to let you know that your article will be published around the last week of August. I'll let you know when it is published!

**Comment by dessireugarte** [comment]
Hello @Marktawa  👋 
Your article is [live](https://strapi.io/blog/handling-previews-in-a-headless-architecture-1)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. Let me know if you have any questions!

**Comment by Marktawa** [comment]
Hey @dessireugarte 

Thanks for notifying me.
