### ISSUE TITLE
[Request New Content] 3 Plugins to power up your Strapi Blog

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#816]
**My Request**

As you may know we have launched our [Strapi Market](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VW6mp65Bb7ZhW875vlJ7mC4nHVfQRxk4JGtrPN72QTZc3lLztV1-WJV7CgYpsW7fq_-H6lTbjcW6khZk73yGqWkW34YNyk7g69ZMW7s-ckP3ZRbXlW1xQr8Q2Ml0V7F6_0Lcy4jLfW7m-CZ43FwxPKMPvNnnrnDN-W4lwQnb3H7HsNW1bT0KG2VnRJHW8Bs29086DwVyW7MCmd96TGWZtW4gsKfP7wjHJKW8r1PrC2LZZFTF4rBsR4qwb5MHHg3JkfprZ31fj1), the official web plugin marketplace, a few months ago. Today, we have more than 60 plugins published, with many more in the pipe. So, we are looking to expand our content library covering the Plugin topic. Please check the current existing plugins (v4) and submit your outline 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Marktawa** [comment]
I would like to write an article for this request.

**Comment by ShadaW11** [comment]
Hello @Marktawa can you please send us an outline.

**Comment by Marktawa** [comment]
Hi 👋  @ShadaW11 

# **Title**: 3 Plugins to power up your Strapi Blog

### **Description**

Plugins are a powerful tool to customize your Strapi app. [The Strapi Market](https://market.strapi.io/) is the official marketplace to find plugins comprising more than 60 plugins to choose from. These plugins were developed by the Strapi team, technology and solution partners, and individual community members. You can find plugins that integrate Strapi with other tools, such as Sentry, Mux, and Moesif, and plugins that extend Strapi features, such as SEO, content versioning, comments moderation, internationalization, database configuration, sitemap, and more.

This tutorial aims to show how you can enhance functionality in your Strapi blog, by making use of 3 plugins from the Strapi Market. You will use the official Strapi SEO plugin to make your content more SEO friendly, the Internationalization (i18n) plugin to help distribute the content in different languages, and the Comments plugin to moderate comments on your blog. You will start by creating a simple static blog with Strapi as the backend and Jekyll for the frontend. Then you will install the plugins and show their use cases. At the end of this tutorial, you should know how to install and use plugins from the Strapi Market to power up your app.

### **Outline**

- Introduction
  - Why Strapi?
  - What is Strapi Market?
  - What is Jekyll?

- Goals
 
  - Build a simple static blog using Jekyll and Strapi
  - Install and showcase the functionality of the following plugins:
    - [Internationalization (i18n) plugin](https://market.strapi.io/plugins/@strapi-plugin-i18n)
    - [SEO plugin](https://market.strapi.io/plugins/@strapi-plugin-seo)
    - [Comments plugin](https://market.strapi.io/plugins/strapi-plugin-comments)
 
- Prerequisites
  - Strapi v4 (latest version)
  - Node.js: only LTS versions are supported (minimum v12)
  - npm (minimum v6) or yarn to run the CLI scripts
  - Ruby v2.5.0 or higher
  - RubyGems
  - GCC and Make

- Backend Setup
- Frontend Setup
- Internalization Plugin
  - Features
  - Installation
  - Configuration
  - How to use it
- SEO Plugin
  - Features
  - Installation
  - Configuration
  - How to use it
- Comments Plugin
  - Features
  - Installation
  - Configuration
  - How to use it
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
👍  Nice!
❤️ I love it!
🚀  I can help you!

**Comment by ShadaW11** [comment]
Hello @Marktawa 

> # **Title**: 3 Plugins to power up your Strapi Blog

Great outline. @Marktawa You can start working on this.

If this is your first article update please register [here](https://strapi.io/write-for-the-community) before you get started.

Once you register, please go over the guidelines [here](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md)

Please reach out if you have any questions.

**Comment by Marktawa** [comment]
Thank you @ShadaW11 

I will start right away.

**Comment by ShadaW11** [comment]
Any update @Marktawa

**Comment by Marktawa** [comment]
@ShadaW11 Still working on it. I will post a draft by the end of the week.

**Comment by TiaraOluwanimi** [comment]
Hello, @Marktawa, any updates?

**Comment by Marktawa** [comment]
Hi @TiaraOluwanimi 
I'm still working on the article. I should be done before end of week.

**Comment by Marktawa** [comment]
Hi @TiaraOluwanimi 

Sorry for the lack of updates. Here's my [current draft](https://www.dropbox.com/scl/fi/t47ph0q6z2x594ror3tym/3-plugins-to-power-up-your-Strapi-Blog.paper). I just recently updated my own fork of the [jekyll-strapi plugin](https://github.com/Marktawa/jekyll-strapi-mod) to make it compatible with Strapi version 4. It took me longer than expected. I'm now left with showcasing the plugins.

**Comment by TiaraOluwanimi** [comment]
Hello, @Marktawa. Are you done now?

**Comment by Marktawa** [comment]
Hi @TiaraOluwanimi 

I'm now done. Here's the link to the [dropbox paper draft](https://www.dropbox.com/scl/fi/j32z7gkpr82mr0tutle8l/3-plugins-to-power-up-your-Strapi-Blog.paper?dl=0&rlkey=y0kwxlnrxv226yo5tvww8txoq) and the [Github project repo](https://github.com/Marktawa/jekyll-strapi-blog)

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋
Just wanted to let you know that your article will be published around the third week of August. I'll let you know when it is published!

**Comment by dessireugarte** [comment]
Hello @Marktawa  👋 Your article is [live](https://strapi.io/blog/3-plugins-to-power-up-your-strapi-blog)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. Please feel free to reach out to me if you have any questions!

**Comment by Marktawa** [comment]
Hi @dessireugarte 
Thanks for the update
I will send an invoice.
