### ISSUE TITLE
[Request New Content] The must have Strapi Plugins for your business website

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#817]
**My Request**

As you may know we have launched our [Strapi Market](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VW6mp65Bb7ZhW875vlJ7mC4nHVfQRxk4JGtrPN72QTZc3lLztV1-WJV7CgYpsW7fq_-H6lTbjcW6khZk73yGqWkW34YNyk7g69ZMW7s-ckP3ZRbXlW1xQr8Q2Ml0V7F6_0Lcy4jLfW7m-CZ43FwxPKMPvNnnrnDN-W4lwQnb3H7HsNW1bT0KG2VnRJHW8Bs29086DwVyW7MCmd96TGWZtW4gsKfP7wjHJKW8r1PrC2LZZFTF4rBsR4qwb5MHHg3JkfprZ31fj1), the official web plugin marketplace, a few months ago. Today, we have more than 60 plugins published, with many more in the pipe. So, we are looking to expand our content library covering the Plugin topic. Please check the current existing plugins (v4) and submit your outline 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Tiioluwani** [comment]
I'm interested in writing on this topic

**Comment by Tiioluwani** [comment]
I'm interested in writing on this

**Comment by ShadaW11** [comment]
@Tiioluwani can you please submit a plugin

**Comment by Tiioluwani** [comment]
Plugins are the most powerful feature of the CMS. They allow developers to create custom pages, add additional functionality and even modify existing features. They can also be used in business websites. In this article, we'll be talking about what plugins are, how strapi plugins provides great  custom features for your CMS website and the best strapi plugins for your business website.
Outline:
-Introduction
-What are plugins
-Why are plugins useful
-Strapi plugins (marketplace)
-The must have strapi plugins for your business website
-Conclusion

**Comment by ShadaW11** [comment]
Hello @Tiioluwani thank you for submitting your outline, we would like to focus more and expand on point 5 (the must have...) Each of the first 4 points could be summarised in a 3 line summary. Can you expand to specify exactly what plugins you plan on using, and use case?

**Comment by Tiioluwani** [comment]
These are the plugins i would be focusing on
-Measurement protocol: Applied in sending data to google analytics.
-EZ forms: This plugin enables the storing of data on your database, sending of notifications, easy consumption of forms from your frontend etc.
-SEO: This plugin helps in making friendly strapi ccontents
-GoogleAuth: Used in making google authentication for users
-REST cache: This plugin helps in speeding up HTTP requests
-Awesome SEO: Applied in viewing SEO analysis of your website, setting URLS etc.
-Big Blue button: Facilitates web conferencing into strapi thus enabling the launching of online classes within strapi

**Comment by Tiioluwani** [comment]
Any update on this

**Comment by dessireugarte** [comment]
Hello Paul 👋 What do you think about this outline?

**Comment by Saintdavidking** [comment]
Hello, @dessireugarte is this topic still available, I will like to take on this topic if it is still available!

**Comment by Saintdavidking** [comment]
Hello, @kilinkis is this topic still available, I will like to take on this topic if it is still available!

**Comment by dessireugarte** [comment]
Hello @Saintdavidking 👋 
Could you share what the outline would look like for this topic?

**Comment by Saintdavidking** [comment]
Outline:
-Introduction
-What is Strapi and Installation of Strapi
-What are plugins
-Why are plugins useful
-The must-have strapi plugins for your business website

- [ ] The Internationalization (i18n) plugin
- [ ] GoogleAuth plugin
- [ ] Awesome SEO plugin
- [ ] The EZ Forms plugin
- [ ] The Publisher plugin
- [ ] The Localazy plugin
- [ ] measurement protocol plugin

-Conclusion

**Comment by Tiioluwani** [comment]
@dessireugarte 
@PaulBratslavsky 
I didn't get a feedback on my outline

**Comment by dessireugarte** [comment]
Hello @Saintdavidking 👋 Thanks for the outline. This tutorial will be done by @Tiioluwani, but there are other tutorials we are currently looking for an author. Feel free to ping me on Discord. 

@Tiioluwani regarding the plugins, I would include CKEditor 5 and Import Export Entries. And I'd use SEO or Awesome SEO, not both. 
What do you think?

**Comment by Tiioluwani** [comment]
@dessireugarte 
No problem at all

**Comment by dessireugarte** [comment]
Thanks @Tiioluwani! Please let us know when your draft is ready so we can review it. Is this the first article you write?

**Comment by Tiioluwani** [comment]
@dessireugarte This would be my first article for strapi but I've written for other platforms before

**Comment by dessireugarte** [comment]
Ok perfect @Tiioluwani 
Can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form? Then please scroll to the FAQ section and review the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md), how to submit an article, issue an invoice, and get paid.
You can start writing your draft. We use Dropbox to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x). 
Once your article is ready, please share the link here so we can review the article.

**Comment by Tiioluwani** [comment]
Hi @dessireugarte 
@TiaraOluwanimi 
Here is the link to the draft of this  article
https://www.dropbox.com/scl/fi/9zy9dcicqa4ykkt7xcj0g/The-Must-Have-Strapi-Plugins-for-Your-Business-Website.paper?dl=0&rlkey=vfi026pb650aq1e14lr6tedgh

**Comment by dessireugarte** [comment]
Hello @Tiioluwani ! I left some comments and shared the draft with the team for review. 
cc @TiaraOluwanimi

**Comment by Tiioluwani** [comment]
@dessireugarte I've made adjustments in response to your comments.

**Comment by dessireugarte** [comment]
Hello @Tiioluwani 👋
I left some comments and I am just currently waiting for access to the Figma file to edit the covers. 
After changing them, the article is ready for one last review on your side and uploading to the backend @TiaraOluwanimi 👍

**Comment by Tiioluwani** [comment]
Hello @dessireugarte 
Any updates

**Comment by dessireugarte** [comment]
Hello @Tiioluwani 👋
Just wanted to let you know that your article will be published next week. I'll let you know if we need anything else or when it is published!

**Comment by Tiioluwani** [comment]
@dessireugarte 
Thanks, I will be expecting to hear from you

**Comment by dessireugarte** [comment]
Hello 👋 
Your article is [live](https://strapi.io/blog/8-awesome-strapi-plugins-for-your-corporate-website)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also, please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment.
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!
