### ISSUE TITLE
[Request New Content] 5 reasons to add on site-search to your website

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#818]
**My Request**

As you may know we have launched our [Strapi Market](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VW6mp65Bb7ZhW875vlJ7mC4nHVfQRxk4JGtrPN72QTZc3lLztV1-WJV7CgYpsW7fq_-H6lTbjcW6khZk73yGqWkW34YNyk7g69ZMW7s-ckP3ZRbXlW1xQr8Q2Ml0V7F6_0Lcy4jLfW7m-CZ43FwxPKMPvNnnrnDN-W4lwQnb3H7HsNW1bT0KG2VnRJHW8Bs29086DwVyW7MCmd96TGWZtW4gsKfP7wjHJKW8r1PrC2LZZFTF4rBsR4qwb5MHHg3JkfprZ31fj1), the official web plugin marketplace, a few months ago. Today, we have more than 60 plugins published, with many more in the pipe. So, we are looking to expand our content library covering the Plugin topic. Please check the current existing plugins (v4) and submit your outline 

The blog post should focus on using the below plugin
https://market.strapi.io/plugins/strapi-plugin-meilisearch#install-now-section

Objective of this blog post is to highlight the below :
- Why install this plugin 
- Include a Use Case
- and How this plugin helped you achieve...

Feel free to include additional plugins in the blog post
**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Victory-ET** [comment]
Hi @ShadaW11 

I've previously used meilisearch and would love to undertake writing this article. I will send an outline ASAP.

**Comment by ShadaW11** [comment]
Hey @Victory-ET great, can you please send your outline.

**Comment by Victory-ET** [comment]
Hi @ShadaW11,

Here is an outline for the proposed topic.

# 5 Reasons to Add On-site Search to Your Website

## Introduction

Dynamic webpages with a high amount of site content are usually complex for users to navigate looking for specific data. These sites use On-site search (also called internal search), which uses a search bar to return the results of a search query made by the user. This simple implementation provides relevant content to users' needs, saving time and effort spent searching for data.


## Goals

In this tutorial, readers will learn what on-site search is, when to use it, how they can build a web application implementing search functionality with a CMS, and its benefits.


## Outline
- What is On-site Search?
    - Why and when do we use this?
- What is Meilisearch?
    - Why use Meilisearch?
- What is StrapiCMS?
- Using Meilisearch in a movies web application as a Use Case 
    - Front-end setup
    - Strapi setup
    - Installing the Meilisearch plugin
    - Integrating Search functionality in our application
- Conclusion
    - Meilisearch benefits in the movie web application
    - Resources

**Comment by ShadaW11** [comment]
@Victory-ET looks good, please go ahead and start working on it.

**Comment by Victory-ET** [comment]
Hi @ShadaW11,

Am almost done with the article and will be making a submission next week.

**Comment by ShadaW11** [comment]
@Victory-ET perfect thanks

**Comment by Victory-ET** [comment]
Hi @ShadaW11,

I'm done writing the draft for the article. Here is a link to the article written on [dropbox paper](https://www.dropbox.com/scl/fi/bopvjoz66ddak4b9byukg/5-Reasons-to-Add-On-site-Search-to-Your-Website.paper?dl=0&rlkey=mmp3mzycd9127c4pnjpsvn0q4)

**Comment by ShadaW11** [comment]
@Victory-ET perfect someone from our team will review it asap

**Comment by Victory-ET** [comment]
@ShadaW11 

Thanks. Looking forward to it.
