### ISSUE TITLE
[SUBMIT] Strapi Deployment on Kubernetes with HTTPS

### ISSUE THREAD

**Issue by IamRajatBadjatya** [strapi/community-content#82]
**My resource**
A step by step guide to setup and deploy Strapi with HTTPs on Kubernetes. I have already published the article on Medium and hope it would be useful for other members of the Strapi community.
**Article link:**
[Deploy Strapi on Kubernetes with HTTPs](https://medium.com/@rajatbadjatya/deploy-strapi-on-kubernetes-with-https-1e3437bf2ca3?source=friends_link&sk=37c847d0b5bd1274989cab7023136776)

**My format**

- [x] Article

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
That is awesome @IamRajatBadjatya!
Thanks for your contribution :)

**Comment by IamRajatBadjatya** [comment]
Thnx @Mcastres :-), what's this Done status means? What would be the next step from here?

**Comment by Mcastres** [comment]
Look you Slack DM ;)

**Comment by justinkillen** [comment]
@IamRajatBadjatya the strapi.sh file syntax is bad - the 'else' on line 44 doesn't have an if statement above it to match

**Comment by malgamves** [comment]
Hey @IamRajatBadjatya could you confirm @justinkillen 's query.
