### ISSUE TITLE
[SUBMIT] Strapi internals, customizing the backend - Part 1 

### ISSUE THREAD

**Issue by miracleonyenma** [strapi/community-content#820]
**My resource**

Hello 👋 

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What it's about**

This article is going to cover a few aspects of customizations to the Strapi backend. We’re touching on controllers, services, policies, webhooks and routes, and a few other things.
​​
​ This article is based on the [Strapi internals, customizing the backend workshop](https://www.youtube.com/watch?v=kohbOP6Eh9I) video by Richard from StrapiConf 2022.

**Outline**

- Strapi internals, customizing the backend - Part 1 Models, controllers & routes
  - Introduction
    - What is Koa?
  - Goals
    - Our use case
  - Prerequisites
  - Setting up
  - Creating our Models
    - Product content-type schema
    - Order content-type schema
  - What we’re building
  - Custom controllers & routes
    - What are controllers?
    - Create a controller

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by ShadaW11** [comment]
@miracleonyenma Awesome thank you so much, someone will review it asap.

**Comment by ShadaW11** [comment]
Link to part 2 of this article - https://github.com/strapi/community-content/issues/821

**Comment by ShadaW11** [comment]
@TiaraOluwanimi If you havent, can you please submit the invoice.
