### ISSUE TITLE
[SUBMIT] How to build a plugin with TypeScript

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#823]
**My resource**

As you may know we have launched our [Strapi Market](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VW6mp65Bb7ZhW875vlJ7mC4nHVfQRxk4JGtrPN72QTZc3lLztV1-WJV7CgYpsW7fq_-H6lTbjcW6khZk73yGqWkW34YNyk7g69ZMW7s-ckP3ZRbXlW1xQr8Q2Ml0V7F6_0Lcy4jLfW7m-CZ43FwxPKMPvNnnrnDN-W4lwQnb3H7HsNW1bT0KG2VnRJHW8Bs29086DwVyW7MCmd96TGWZtW4gsKfP7wjHJKW8r1PrC2LZZFTF4rBsR4qwb5MHHg3JkfprZ31fj1), the official web plugin marketplace, a few months ago. Today, we have more than 60 plugins published, with many more in the pipe. So, we are looking to expand our content library covering the Plugin topic. Please check the current existing plugins (v4) and submit your outline

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by Dmuasya** [comment]
Hi, May  I send an outline?

**Comment by oviecodes** [comment]
Hey @ShadaW11 I'm currently working on this, I'll have  a draft for you very soon.

**Comment by oviecodes** [comment]
@malgamves I'm was working with @ShadaW11 on this. I'll be having a draft soon. Should I send it to you once I'm done.

**Comment by dessireugarte** [comment]
Hello @oviecodes 👋
Yes you can send the draft over here and I will give a follow-up

**Comment by oviecodes** [comment]
@PaulBratslavsky I'm was working with @ShadaW11 on this. I'll be having a draft soon. Can I send it to you once I'm done?

**Comment by Claradev32** [comment]
Hi @ShadaW11 
I can work on this topic

**Comment by oviecodes** [comment]
Alright @dessireugarte I'll do so this weekend

**Comment by oviecodes** [comment]
hey @dessireugarte , i was thinking of having 2 or 3 parts for the article
1. introduction to strapi plugins
2. developing the frontend of the plugin
3. developing the backend of the plugin

**Comment by oviecodes** [comment]
Hello @dessireugarte here's a link to the article https://www.dropbox.com/scl/fi/wc5lfr282pv22qmshmdc8/How-to-build-a-plugin-with-TypeScript.paper?dl=0&rlkey=z4goby2lkwliiv5mw1954dsw2

**Comment by TiaraOluwanimi** [comment]
Well received, @oviecodes. You'll see review comments on the doc soon.

**Comment by oviecodes** [comment]
Thanks @TiaraOluwanimi

**Comment by dessireugarte** [comment]
Hello @oviecodes  👋
Just wanted to let you know that your article will be published around the last two weeks of August. I'll let you know when it is published!

**Comment by oviecodes** [comment]
Alright @dessireugarte Thanks

**Comment by dessireugarte** [comment]
Hello 👋 
Your article is [live](https://strapi.io/blog/how-to-build-a-plugin-with-type-script)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. Please feel free to reach out to me if you have any questions!
