### ISSUE TITLE
[Request New Content] Creating a Strapi Plugin Is Easier Than You Think

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#824]
**My Request**

As you may know we have launched our [Strapi Market](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VW6mp65Bb7ZhW875vlJ7mC4nHVfQRxk4JGtrPN72QTZc3lLztV1-WJV7CgYpsW7fq_-H6lTbjcW6khZk73yGqWkW34YNyk7g69ZMW7s-ckP3ZRbXlW1xQr8Q2Ml0V7F6_0Lcy4jLfW7m-CZ43FwxPKMPvNnnrnDN-W4lwQnb3H7HsNW1bT0KG2VnRJHW8Bs29086DwVyW7MCmd96TGWZtW4gsKfP7wjHJKW8r1PrC2LZZFTF4rBsR4qwb5MHHg3JkfprZ31fj1), the official web plugin marketplace, a few months ago. Today, we have more than 60 plugins published, with many more in the pipe. So, we are looking to expand our content library covering the Plugin topic. Please check the current existing plugins (v4) and submit your outline

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ath34-tech** [comment]
hey @ShadaW11 i am open to write tutorial on this, maybe make a task scheduling plugin or todo plugin(same in v4 official plugin development video)

**Comment by ath34-tech** [comment]
@malgamves well i thought to write something like scheduling a task with date and time in a calender or google calender. nothing fancy just basic app similar to todo app

**Comment by ath34-tech** [comment]
@malgamves can u tell if i can work on draft or not?

**Comment by ath34-tech** [comment]
@PaulBratslavsky will , will send a draft tomorrow or day after

**Comment by ath34-tech** [comment]
@PaulBratslavsky here is basic outline of heading i will be going to use in articles and topics i will explain:
[outline](https://docs.google.com/document/d/1F8hs5wjAhsv6sd4_64eIdQJQtugghTC2Zt0HHTaTYIY/edit?usp=sharing)

**Comment by PaulBratslavsky** [comment]
@ath34-tech Looks great you can start on it.  Thank you. 🙂

**Comment by ath34-tech** [comment]
@PaulBratslavsky  how should i share the draft? in google docs or markdown?

**Comment by PaulBratslavsky** [comment]
@ath34-tech You can share it via google docs. What was the exact issue you were having with sending emails? You can probably create a similar example using nodemailer.

**Comment by ath34-tech** [comment]
[draft](https://docs.google.com/document/d/1MIpsDUFfb56ALpLqdJp4krWZhccgwDV7J4Urx1CLC_w/edit?usp=sharing
)@PaulBratslavsky here is a draft

**Comment by ath34-tech** [comment]
[draft](https://docs.google.com/document/d/1MIpsDUFfb56ALpLqdJp4krWZhccgwDV7J4Urx1CLC_w/edit?usp=sharing)

**Comment by PaulBratslavsky** [comment]
@ath34-tech look good.  Also, if you have the completed project on github, go ahead and share the link.  Would love to check it out.  If you are happy with your draft, we can submitted to the next step in the process.

**Comment by ath34-tech** [comment]
@PaulBratslavsky here github Project:[project](https://github.com/ath34-tech/StrapiBasicPlugin)
I think i am okay with draft so you can proceed.

**Comment by dessireugarte** [comment]
Hey @PaulBratslavsky I checked is it ok to put it in the loop to Olamide so she can review it and include it in the pipeline?

**Comment by PaulBratslavsky** [comment]
@dessireugarte yes, thank you.

**Comment by TiaraOluwanimi** [comment]
Hello, @ath34-tech. You didn't grant edit access to your doc, so I made a dropbox copy. I've made some comments there. Pls, check and revert asap. Thanks

**Comment by ath34-tech** [comment]
@TiaraOluwanimi any updates on article?

**Comment by dessireugarte** [comment]
Hello @ath34-tech  👋
Just wanted to let you know that your article will be published around the last two weeks of August. I'll let you know when it is published!

**Comment by dessireugarte** [comment]
Hello  @ath34-tech 👋 Your article is [live](https://strapi.io/blog/making-a-simple-strapi-plugin)! 
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. Please feel free to reach out to me if you have any questions!

**Comment by ath34-tech** [comment]
@dessireugarte how much amount will i need to put as "fees"?

**Comment by ath34-tech** [comment]
@dessireugarte i am from india and we don't have IBAN system here, so what should I put in the branch code/sort code section?

**Comment by dessireugarte** [comment]
Hello @ath34-tech!
Regarding the fees, it will depend on the number of words. Please check how it is paid in the [FAQ](https://strapi.io/write-for-the-community). 

Regarding the IBAN, @malgamves what is usually done in this case?
