### ISSUE TITLE
[Request New Content] A Beginners Explainer to Strapi Plugin Development

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#825]
**My Request**

As you may know we have launched our [Strapi Market](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VW6mp65Bb7ZhW875vlJ7mC4nHVfQRxk4JGtrPN72QTZc3lLztV1-WJV7CgYpsW7fq_-H6lTbjcW6khZk73yGqWkW34YNyk7g69ZMW7s-ckP3ZRbXlW1xQr8Q2Ml0V7F6_0Lcy4jLfW7m-CZ43FwxPKMPvNnnrnDN-W4lwQnb3H7HsNW1bT0KG2VnRJHW8Bs29086DwVyW7MCmd96TGWZtW4gsKfP7wjHJKW8r1PrC2LZZFTF4rBsR4qwb5MHHg3JkfprZ31fj1), the official web plugin marketplace, a few months ago. Today, we have more than 60 plugins published, with many more in the pipe. So, we are looking to expand our content library covering the Plugin topic. Please check the current existing plugins (v4) and submit your outline

A few elements we'd like to cover in this article
What Is a Strapi Plugin?
Why Create a Plugin?
Getting Started With Plugins
Installing a New Plugin
Learning Plugin Development

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Marienoir** [comment]
Hello @ShadaW11 
I would like to write content for this article

**Comment by Takeddiney** [comment]
Hey @ShadaW11 ! 
I would like to write this article :rocket:

**Comment by ShadaW11** [comment]
Hello, can you please submit your outlines?

**Comment by Marienoir** [comment]
Hi @ShadaW11 
This is my outline for the article

# Title:  A Beginners Explainer to Strapi Plugin Development
## Description
Strapi is an open-source and headless content management system ( CMS )that gives developers the freedom to use their favorite tools and frameworks during development. Strapi has an official web plugin marketplace  [The Strapi Market](https://market.strapi.io/)  which comprises more than 60 plugins to choose from.  
Plugins also referred to as add-ons, are software that is available to give extra functionalities to our application. They have been known to help developers customize their applications in regards to styles and easy accessibility. Strapi plugins were developed to power up your Strapi app with industry-leading software and also easily add custom features.  They can be installed from the Marketplace or as npm packages. You can create your own plugins (see [plugins development](https://docs.strapi.io/developer-docs/latest/development/plugins-development.html)) or extend the existing ones.  

This tutorial aims to give an approach to what a Strapi plugin is,  and how to get started with plugin development as a beginner. You will learn how to use the official Strapi Scheduler plugin to publish or depublish any collection type in the future. At the end of this tutorial, you should know how to get started with Strapi plugin development, and how to install and use plugins from the Strapi Market to power up your application.

## Outline
### Introduction

- What Is a Strapi Plugin?

- Why Strapi?

- What Is a Strapi Plugin?

- Why Create a Plugin?

### Goals

-  Installing Strapi and creating a Strapi project.
- Install and showcase the functionality of the scheduler plugin: [Scheduler plugin](https://market.strapi.io/plugins/@webbio-strapi-plugin-scheduler)
## Description
- Getting started with the scheduler plugin
- Features
- Installation
- Configuration
- How to use it

### Prerequisites

- Strapi v4 (latest version)
- npm (minimum v6) or yarn 

### Conclusion

My content is

- [ ]  A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**Comment by Takeddiney** [comment]
Hello @ShadaW11 
This is my proposed outline for this topic

**What Is a Strapi Plugin? **
I will be defining what a Strapi plugin is with an Introduction about Strapi

**Why Creating a Plugin?**
A short description for Plugin usage with an example or two

**Getting Started With Strapi Plugins**
A mini introduction to Strapi Marketplace and some popular plugins and how to Set up a Strapi application and take a look at the Marketplace

**Installing a New Plugin**
I will create a mini-tutorial on how to Install a Plugin from Strapi Marketplace with steps & screenshots

**Learning Plugin Development**
 With codes and steps, I will create a mini-tutorial on how to develop your custom plugin for WebP images convertion as a plugin example

**Comment by ShadaW11** [comment]
@Marienoir I like your article outline. What type of app will you build at the end of the tutorial that will highlight the need of using the scheduler plugin?

**Comment by ShadaW11** [comment]
@Takeddiney I believe your outline can be transformed to another article. Can you please open another issue? and develop more your outline? I like the outline but I think here the focus should be on learning plugin development, instead of a mini tutorial maybe you can expand on that part? please open a new issue and we continue discussing this topic there.

**Comment by Marienoir** [comment]
@ShadaW11 Thanks.
I intend to build a book store application using vanilla JavaScript and Strapi. Then highlighting how the scheduler plugin can be used to schedule books being added and also removed from the site.
However if you have a better option, I am open to suggestions. 
Thanks

**Comment by ShadaW11** [comment]
Sounds good, @Marienoir good for it. If this is your first article update please register [here](https://strapi.io/write-for-the-community) before you get started.

Once you register, please go over the guidelines [here](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md)

Please reach out if you have any questions.

**Comment by Marienoir** [comment]
Alright @ShadaW11 
I am on it and would reach out if I have questions too.
Thanks

**Comment by Marienoir** [comment]
Yes @ShadaW11 
I would send in my draft today. Just making some final refactoring

**Comment by Marienoir** [comment]
@ShadaW11 I have sent in my article draft. 
Thanks

**Comment by Marienoir** [comment]
@dessireugarte Alright that is fine with me
Thanks

**Comment by dessireugarte** [comment]
Hello @Marienoir 👋 Just want to make sure you received news about your payment?

**Comment by Marienoir** [comment]
Yes, I have @dessireugarte 
Thanks for reaching out 😊

**Comment by dessireugarte** [comment]
Great! 
Thanks to you! Take care 👋
