### ISSUE TITLE
[Request New Content] 5 Things to Keep in Mind Before Creating a Strapi Plugin

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#826]
**My Request**

As you may know we have launched our [Strapi Market](https://www.strapi.io/e3t/Ctc/5D+113/cQNTM04/VW6mp65Bb7ZhW875vlJ7mC4nHVfQRxk4JGtrPN72QTZc3lLztV1-WJV7CgYpsW7fq_-H6lTbjcW6khZk73yGqWkW34YNyk7g69ZMW7s-ckP3ZRbXlW1xQr8Q2Ml0V7F6_0Lcy4jLfW7m-CZ43FwxPKMPvNnnrnDN-W4lwQnb3H7HsNW1bT0KG2VnRJHW8Bs29086DwVyW7MCmd96TGWZtW4gsKfP7wjHJKW8r1PrC2LZZFTF4rBsR4qwb5MHHg3JkfprZ31fj1), the official web plugin marketplace, a few months ago. Today, we have more than 60 plugins published, with many more in the pipe. So, we are looking to expand our content library covering the Plugin topic. Please check the current existing plugins (v4) and submit your outline

A few elements we'd like to cover in this article
What type of plugin are you building?
What are you building?
Plan?
Features?
Research?
Maintenance?
How Strapi can help?

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by icode247** [comment]
Hi @ShadaW11 ,
I can work on this topic

**Comment by dessireugarte** [comment]
Hello @icode247 👋
 Can you provide an outline of what you are thinking of covering?

**Comment by oviecodes** [comment]
Hello @dessireugarte I can take this up.

**Comment by dessireugarte** [comment]
Hello @oviecodes 👋 
Could you please provide an outline?

**Comment by oviecodes** [comment]
- Introduction to Strapi
- What are plugins?
- Good news - Strapi allows you to create plugins.
- Planning phase
    - What problem are you trying to solve?
    - Where to look for solutions
    - Typescript / Javascript
- Deciding which features to include
    - Homepage
    - settings page
    - activation and deactivation
- Researching 
    - Looking at plugins in the marketplace to avoid reinventing the wheel
    - Using the Strapi forum or the discord channel to perform survey for the demand of your plugin
    - Using some Strapi inbuilt features to give your plugin the strapi feel
- Maintenance
    - How can you adapt the plugin
- How Strapi can help
    - Getting your plugin to the marketplace

**Comment by oviecodes** [comment]
@dessireugarte what do you think about the outline?

**Comment by oviecodes** [comment]
Hello @dessireugarte

**Comment by dessireugarte** [comment]
Hello @oviecodes 👋 
The outline looks great. You can start writing the article. I will include @TiaraOluwanimi so you can share the draft for review with her when it is ready.

**Comment by oviecodes** [comment]
Hello @dessireugarte , @TiaraOluwanimi here's a link to the article
https://www.dropbox.com/scl/fi/y0nku5hocd81gyp9r94je/5-Things-to-Keep-in-Mind-Before-Creating-a-Strapi-Plugin.paper?dl=0&rlkey=t96nzu81ak8dxk91vq7a3qgm6

**Comment by dessireugarte** [comment]
Hello @oviecodes 👋
Just wanted to let you know that your article will be published around the last week of September. I'll let you know when it is published!

**Comment by oviecodes** [comment]
Alright @dessireugarte Thanks for the information.

**Comment by dessireugarte** [comment]
Hello 👋 
Your article is [live](https://strapi.io/blog/5-things-to-keep-in-mind-before-creating-a-strapi-plugin)! 🎉
Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform)!
Feel free to reach out to me if you have any questions!

**Comment by oviecodes** [comment]
Thanks @dessireugarte but the author name in the article is wrong I'm Alexander Godwin. It says Godwin Alexander Ekainu.

**Comment by oviecodes** [comment]
Thanks @dessireugarte I'll do so, I still haven't been paid for the last article. I hope everything is good?

**Comment by dessireugarte** [comment]
Hello @oviecodes! Could you let me know when you submitted your invoice? 
Seems there is a small delay in some payments, let me know and I will check. I might take some time in answering since I am leaving for a couple of days but as soon as I am back I will check

**Comment by oviecodes** [comment]
Thanks @dessireugarte I submitted my invoice on the 5th of September.

**Comment by oviecodes** [comment]
Hello @dessireugarte , please is there any response about the invoice?

**Comment by dessireugarte** [comment]
@malgamves are there any news about this payment?

**Comment by oviecodes** [comment]
@malgamves any updates on the payment?

**Comment by malgamves** [comment]
hey @oviecodes yes, we've processed it but please refer too [this message](https://discord.com/channels/811989166782021633/843965836887851078/1031584885258866760) that explains delays we've been facing lately.
