### ISSUE TITLE
[Request New Content] How to import data from another CMS using a plugin

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#828]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by dillionmegida** [comment]
Hi @dessireugarte if I understand this request correctly, the goal of this article is to show how to import data from a different CMS (any choice) to Strapi using a plugin right?

Does this tutorial create the plugin, or would this tutorial use an existing plugin?

**Comment by dessireugarte** [comment]
Hello @dillionmegida 👋 
There isn't any plugin available to migrate data from one CMS to Strapi. So if you propose another way to migrate the data, that would be ok as well 👍

**Comment by PaulBratslavsky** [comment]
I am going to close this topic for the time being. There is a feature that the team is working on that will make migrating data easier, but it is still in the works. Also, at the moment, this topic has to be handled based on each case, making it hard to make a tutorial covering all use cases.
