### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Create Pages on the fly with Dynamic Zone

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#831]
**Description**

Hello 👋

This [article](https://strapi.io/blog/how-to-create-pages-on-the-fly-with-dynamic-zone) is outdated and needs to be updated.

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Cpaczek** [comment]
Does the Nuxt JS one still need to be updated, I couldn't see an issue but I could do it for nuxt

**Comment by FeliciaSephodi** [comment]
I'd like to take this article!

**Comment by dessireugarte** [comment]
Hello @FeliciaSephodi  👋
If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form? Then please scroll to the FAQ section and review the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md), how to submit an article, issue an invoice, and get paid.
You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x). 
Once your article is ready, please share the link here and we will review it.

**Comment by FeliciaSephodi** [comment]
Thank you I'm working on the draft.

**Comment by hanakhelifa** [comment]
Hi there,
As we are currently revamping the Write For the Community program, I am doing a bit of cleaning up on this repo. I see this issue is open for more than a year now, and that there is no draft, so I'll close it to keep the repo up-to-date with upcoming changes. Feel free to reach out to me if needed :)

**Comment by FeliciaSephodi** [comment]
Hi Hana

Are you closing every issue or will there be other open ones?
