### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Announcing Strapi 3.1 - Administrator Roles & Permissions

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#832]
**Description**

This article requires update:
https://strapi.io/blog/announcing-3.1-role-based-access-control

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by ikeadeoyin** [comment]
@ShadaW11 
I can work on this. I would love to update the article.

**Comment by TiaraOluwanimi** [comment]
@ikeadeoyin, are you still up for this?

**Comment by Saintdavidking** [comment]
Hello, @dessireugarte is this topic still available for the new strapi v4 ?

**Comment by PaulBratslavsky** [comment]
@Saintdavidking sorry for supper late response, if you are still interested let us know.

**Comment by Saintdavidking** [comment]
Hi @PaulBratslavsky i am still interested, can i start with already?

**Comment by dessireugarte** [comment]
Hello @Saintdavidking  👋
We won't be accepting new updates this year, but if you want to, you can get started, and we can give a follow-up to this one in January. Would that be ok with you?

**Comment by adeola-dev** [comment]
Hello @TiaraOluwanimi, 
I would like to take on this update, how do I get started?

**Comment by Saintdavidking** [comment]
@dessireugarte i have started working on it

**Comment by Saintdavidking** [comment]
Hi @dessireugarte 
Here is the link to the updated dropbox paper.
https://www.dropbox.com/scl/fi/8l5vv1mgaa4oham9iz3d4/Strapi-Administrator-Roles-Permissions.paper?dl=0&rlkey=gkiv5v4h6mx0zhxn31sr1o2bo

**Comment by Saintdavidking** [comment]
Hi @dessireugarte, i want know if there is any update  about this  article update

**Comment by dessireugarte** [comment]
Hello @Saintdavidking.
Please don't write any article unless anyone in the Strapi team gives the green light. Otherwise, we will need to reject the draft. 
We will review the draft and get back to you with feedback.

**Comment by Saintdavidking** [comment]
Hi @dessireugarte, Thanks for the response, and sorry for any inconvenience, I only started based on your reply:
```
[dessireugarte](https://github.com/dessireugarte) commented [on Nov 22, 2022](https://github.com/strapi/community-content/issues/832#issuecomment-1323771400)
Hello @Saintdavidking 👋
We won't be accepting new updates this year, but if you want to, you can get started, and we can give a follow-up to this one in January. Would that be ok with you? 
```

**Comment by Saintdavidking** [comment]
Hi @PaulBratslavsky I want to know if there is any update about this issue

**Comment by PaulBratslavsky** [comment]
@Saintdavidking were you looking to update this article? We now have RBAC available in the CE without limiting number of roles.  This will be a great update.

**Comment by Saintdavidking** [comment]
@PaulBratslavsky  Yes, I already updated the article with the former v4 but, i will recheck it so i can update it to the latest version

**Comment by PaulBratslavsky** [comment]
@Saintdavidking Ok thank you for letting me know.

**Comment by Saintdavidking** [comment]
@PaulBratslavsky here is the updated version of the article update.

https://www.dropbox.com/scl/fi/ovbv4cbft96snzgsbgzi1/Strapi-Administrator-Roles-Permissions.paper?rlkey=0cjmhcslssam6wkhzxb4yr6t7&dl=0

**Comment by PaulBratslavsky** [comment]
@Saintdavidking thank you. Will add to the review queue.

**Comment by Saintdavidking** [comment]
Hi @PaulBratslavsky 

I want to ask if there is any information regarding this update 🙂

**Comment by Saintdavidking** [comment]
> Hi @PaulBratslavsky
> 
> I want to ask if there is any information regarding this update 🙂

@PaulBratslavsky @TiaraOluwanimi

**Comment by hanakhelifa** [comment]
Hello @Saintdavidking, I'll review this one this week and get back to you here.

**Comment by Saintdavidking** [comment]
Hi @hanakhelifa ,is there any update on the review

**Comment by hana75** [comment]
Topic has been reviewed and closed, closing the issue

**Comment by Saintdavidking** [comment]
What is the next step, what should I do after it is now completed.

**Comment by Saintdavidking** [comment]
> Topic has been reviewed and closed, closing the issue

Hello, any updates on this??
