### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to use Image and preview in your Nextjs - Strapi blog

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#834]
**Description**

This article requires update
https://strapi.io/blog/how-to-use-image-and-preview-in-your-nextjs-strapi-blog

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by achingachris** [comment]
@ShadaW11 

I can take up the task and work on creating an updated version.

**Comment by TiaraOluwanimi** [comment]
Hello, @achingachris. Are you still up for this?

**Comment by achingachris** [comment]
Yes, I'm up for the task. What's the next steps

**Comment by dessireugarte** [comment]
Hello @achingachris 👋 Please submit the draft when it is ready so we can review it!

**Comment by achingachris** [comment]
> Hello @achingachris wave Please submit the draft when it is ready so we can review it!

Here is the outline:

1. Introduction
2. Prerequisites
3. Starting a Strapi Project: Using starters
4. Displaying Images from Strapi to NextJS 
5. Creating Image preview on Click
6. Conclusion
7. References

**Comment by dessireugarte** [comment]
@PaulBratslavsky Do you think the outline changes from this article are ok? I'm not sure if we should use the starters since the only one maintained by us is [this](https://github.com/strapi/starters-and-templates/tree/main/packages/templates/ecommerce) one.
What do you think?

**Comment by Marktawa** [comment]
Hi @dessireugarte 

I want to update this tutorial if it's free.

**Comment by lucky4242** [comment]
Hi @dessireugarte 
i would love to work on this article.
thanks.

**Comment by PaulBratslavsky** [comment]
@lucky4242 we are in the process of creating a new next js starter and will be sunsetting all the other ones. And archiving the old article with the link to the news starter.  At the moment we are not updating previous old started articles and templates.
