### ISSUE TITLE
[Request New Content] Deploying Strapi to your own VPS

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#835]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ibn-ashimi** [comment]
Hello, Can I take on this article?

**Comment by ShadaW11** [comment]
Hello @ibn-ashimi Can you please submit your outline?

**Comment by ibn-ashimi** [comment]
Hi @ShadaW11 
Outline:

Introduction
prerequisite
Installations
Setting up
Deployment
Conclusion.

What do you think?

**Comment by ShadaW11** [comment]
Hello, you need to submit a more detailed outline  @ibn-ashimi please focus on this article. There is no need to pitch other articles in the same time.

**Comment by ibn-ashimi** [comment]
My resource

A Virtual Private Server allows you to have flexibility over your deployment and is a lot more secure. I will like to teach the Strapi community how they can purchase a VPS and deploy their Strapi app.

Outline:

- Introduction
- Goals
- Prerequisites
- Things to consider before purchasing a VPS
- Installations
- Setting up
- Deployment
- Conclusion.

My content is

[x] A Strapi Tutorial / Guide / How to article

[ ] About Headless, CMS, javascript, open-source, or jam stack
[ ]  Other, specify

**What do you all think? @ShadaW11  **

**Comment by ibn-ashimi** [comment]
Hey @TiaraOluwanimi @ShadaW11

Here is a dropbox link: https://www.dropbox.com/scl/fi/lslrund8ag8yuq74buwl8/Deploying-Strapi-to-your-own-VPS.paper?dl=0&rlkey=a2jk02z32bogg0tf569z7nhva

Looking forward to your feedback.
Cheers.

**Comment by ibn-ashimi** [comment]
Hi @TiaraOluwanimi I have updated the draft with the images

**Comment by ibn-ashimi** [comment]
@TiaraOluwanimi Hello, Could you please confirm if there is any other correction i need to make on my draft?

**Comment by ibn-ashimi** [comment]
Hi @PaulBratslavsky

**Comment by ibn-ashimi** [comment]
Hello @PaulBratslavsky @TiaraOluwanimi.

Any update please?

**Comment by ibn-ashimi** [comment]
Hi @TiaraOluwanimi Any latest update on this please?

**Comment by ibn-ashimi** [comment]
Hi @TiaraOluwanimi Any latest update on this please?

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 👋 Your article will be posted in the following days. I'll let you know when you can submit your invoice.

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 👋
This article is published https://strapi.io/blog/deploying-strapi-to-your-own-vps 
You can now submit your invoice [here](https://docs.google.com/forms/u/2/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform)

@malgamves will give it a follow-up

**Comment by ibn-ashimi** [comment]
Alright, Thanks.

Who do i talk to, to have my author bio edited tho?

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 👋 
We have made the change you sent to @PaulBratslavsky 👍

**Comment by ibn-ashimi** [comment]
Thank you so much.

**Comment by malgamves** [comment]
processed it last week, you should get it in a week. Let me know if you don't and i'll follow up @ibn-ashimi

**Comment by ibn-ashimi** [comment]
Alright @malgamves.I haven't yet but perhaps before the end of the week.

**Comment by ibn-ashimi** [comment]
Alright @malgamves i haven't yet but perhaps before the week runs out.

**Comment by ibn-ashimi** [comment]
Hi @malgamves I haven't gotten this.

**Comment by malgamves** [comment]
checking this for you :)) please text on Discord, I'm malgamves there too

**Comment by ibn-ashimi** [comment]
HI @malgamves This has been taken care of. Thanks a lot.
