### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Build a Photo Gallery with Strapi, Nextjs and Cloudinary

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#836]
**Description**

This article requires update
https://strapi.io/blog/how-to-build-a-photo-gallery-with-strapi-nextjs-and-cloudinary

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Marienoir** [comment]
Hello @ShadaW11 
I would like to make an update to this article.
Thanks

**Comment by malgamves** [comment]
hey yes it @Marienoir - @TiaraOluwanimi could you confirm?

**Comment by ath34-tech** [comment]
i am open to write on this topic

**Comment by TiaraOluwanimi** [comment]
@Marienoir, it's available. Pls, go ahead.

**Comment by Marienoir** [comment]
Alright, thanks
I would get on it.

**Comment by dessireugarte** [comment]
Hello @Marienoir 👋 Do you have any news on this update?

**Comment by Marienoir** [comment]
@dessireugarte 
I am still on it. I would send in the updated draft by next week.

**Comment by dessireugarte** [comment]
Perfect! Thanks @Marienoir

**Comment by Marienoir** [comment]
Hello @dessireugarte 

This is an updated content draft 
https://www.dropbox.com/scl/fi/erp30nc4gy8b0dkxriyny/How-to-Build-a-Photo-Gallery-with-Strapi-Nextjs-and-Cloudinary.paper?dl=0&rlkey=ghc8l7c7adpwwqcgvjpavhb2i

**Comment by dessireugarte** [comment]
Thank you @Marienoir! We will review this article and get back to you.

**Comment by dessireugarte** [comment]
Hello @Marienoir  👋
Just wanted to let you know that your article will be published around the last two weeks of August. I'll let you know when it is published!

**Comment by Marienoir** [comment]
Alright, @dessireugarte 😊

**Comment by dessireugarte** [comment]
Hello @Marienoir @TiaraOluwanimi 👋
I left a comment in the draft!

**Comment by Marienoir** [comment]
Hello @dessireugarte @TiaraOluwanimi 
I have implemented the comments in the draft

**Comment by dessireugarte** [comment]
Hello @Marienoir  👋 
Thanks for being responsive. Your article is [live](https://strapi.io/blog/how-to-build-a-photo-gallery-with-strapi-nextjs-and-cloudinary-1)! 🎉

Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. Please feel free to reach out to me if you have any questions!
