### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Building Custom Resolvers with Strapi

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#837]
**Description**

This article requires update
https://strapi.io/blog/building-custom-resolvers-with-strapi

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
I wanted to take a stab at this article, can find a link to the draft here. https://github.com/PaulBratslavsky/how-to-create-custom-graphql-resolver-strapi-v4

**Comment by PaulBratslavsky** [comment]
Here is the draft https://github.com/PaulBratslavsky/how-to-create-custom-graphql-resolver-strapi-v4

**Comment by dessireugarte** [comment]
Thanks @PaulBratslavsky ! Since it is published, I'm closing the issue.
