### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Serve Different Content Based on User Data/Membership with Strapi and React

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#839]
**Description**

This link requires update
https://strapi.io/blog/how-to-serve-different-content-based-on-user-data-membership-with-strapi-and-react

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by ayhid** [comment]
Hello @ShadaW11  I am interested in updating this article.
I am already registered in the writing for the community program.

**Comment by divofred** [comment]
@dessireugarte @PaulBratslavsky. I can work on this update, if it's available.
Thanks

**Comment by ath34-tech** [comment]
I will like to take over this issue if it is free

**Comment by FeliciaSephodi** [comment]
If nobody is taking this article I'd like to take it.

**Comment by dessireugarte** [comment]
Hello @ath34-tech!
Are you still interested in this article?

**Comment by ath34-tech** [comment]
@dessireugarte yes i am interested, i will send draft tomorrow or day after

**Comment by ath34-tech** [comment]
@dessireugarte  hey sorry i got busy due to some work, i wanted to know if I can keep outline same as this only change project I am gonna make. like I can write tutorial of making same movie list application where different role can read,write ,update the list.
What you say?

**Comment by ath34-tech** [comment]
@dessireugarte  any comment?

**Comment by ath34-tech** [comment]
@dessireugarte @PaulBratslavsky any new update regarding this?

**Comment by dessireugarte** [comment]
Hello @ath34-tech 👋
We won't be accepting new updates this year, but if you want to, you can get started, and we can give a follow-up to this one in January. Would that be ok with you?

**Comment by ath34-tech** [comment]
Yes no problem @dessireugarte

**Comment by divofred** [comment]
There has been no progress on this. @dessireugarte @PaulBratslavsky, I'll love to take it up, if possible.

**Comment by dessireugarte** [comment]
Hello @divofred! 
We won't update this tutorial anymore. We will soon share some articles to update.
