### ISSUE TITLE
[UPDATE OUTDATED CONTENT] i18n implementation and Best Practices in Strapi

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#840]
**Description**

This article requires update
https://strapi.io/blog/i18n-implementation-best-practices-in-strapi

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by popoolatopzy** [comment]
Hello @PaulBratslavsky I'll like to work on updating this article.

**Comment by popoolatopzy** [comment]
Hi @PaulBratslavsky , here is the updated draft for this article
https://www.dropbox.com/scl/fi/85nmofklqye1x81sz9oq8/i18n-Implementation-and-Best-Practices-in-Strapi.paper?dl=0&rlkey=64cxgp8jugdmc38s4klqnaa0w

**Comment by dessireugarte** [comment]
Hello @TiaraOluwanimi 👋 This one is ready to be reviewed.

**Comment by TiaraOluwanimi** [comment]
@popoolatopzy, I dropped a comment on the doc for you. Pls check and revert. Thanks

**Comment by popoolatopzy** [comment]
Thank you @TiaraOluwanimi , I"ve attended to your comment

**Comment by popoolatopzy** [comment]
@dessireugarte thank you for the update

**Comment by dessireugarte** [comment]
Hello 👋 Your article is [live](https://strapi.io/blog/i18n-implementation-and-best-practices-in-strapi)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
Please feel free to reach out to me if you have any questions!
