### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Build a Forum App with NextJs and Strapi CMS

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#841]
**Description**

This article requires update
https://strapi.io/blog/how-to-build-a-forum-app-with-next-js-and-strapi-cms

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Victory-ET** [comment]
Hi @ShadaW11,

I would love to update this tutorial. As I'm the author it's my responsibility to update it and it would be much easier for me to do.

**Comment by Victory-ET** [comment]
Hi @ShadaW11,

I've updated the mentioned article using Strapi V4. Here's a link to the article on [dropbox paper](https://www.dropbox.com/scl/fi/fnwp5udhh8xe0f7pcwe90/How-to-Build-a-Forum-App-with-NextJs-and-Strapi-CMS.paper?dl=0&rlkey=om5dtsmye1qmwmp9fn6yed1f3).

**Comment by ShadaW11** [comment]
@Victory-ET thank you, we'll review it asap

**Comment by ShadaW11** [comment]
@TiaraOluwanimi

**Comment by dessireugarte** [comment]
Hello @Victory-ET 👋 
Did you already submit your invoice and receive payment for this article?

**Comment by Victory-ET** [comment]
Hi @dessireugarte ,

I have not sent in an invoice for this yet.

**Comment by dessireugarte** [comment]
Hello @Victory-ET! 
Could you please submit it [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform)?
