### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Auth0 Provider and Strapi Tutorial

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#844]
**Description**

This article requires update
https://strapi.io/blog/auth0-provider-and-strapi-tutorial

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Shivansh2407** [comment]
Hey @ShadaW11, can I take issue, to update the content. Thanks!

**Comment by TiaraOluwanimi** [comment]
Hi, @Shivansh2407. Yes, please.

**Comment by dessireugarte** [comment]
Hello @Shivansh2407 👋 any news on this?

**Comment by Marienoir** [comment]
Hello @dessireugarte 
Is this article still available for update?
I would like to do an update on this article
Thanks

**Comment by dessireugarte** [comment]
Hello @Marienoir 👋
Yes, go ahead. Please let me know when you have a draft to review it.

**Comment by Marienoir** [comment]
Alright, I will get on with this update

**Comment by Marienoir** [comment]
Hello @dessireugarte 👋
This is the link to the updated content 
https://www.dropbox.com/scl/fi/cjn933og7ljztpsw5oa0u/Auth0-Provider-and-Strapi-Tutorial.paper?dl=0&rlkey=89irepcrafe2ifkacw7ahtr54

**Comment by PaulBratslavsky** [comment]
@Marienoir this looks great, if you are happy with the draft I will submit it for review.🙂

**Comment by Marienoir** [comment]
Hello @PaulBratslavsky 
Yes, this update is okay with me.

**Comment by dessireugarte** [comment]
Hello @Marienoir   👋
Just wanted to let you know that your article will be published around the second week of September. I'll let you know when it is published!

**Comment by dessireugarte** [comment]
Hi @Marienoir  👋 
Your article is [live](https://strapi.io/blog/auth0-provider-and-strapi-tutorial-1), congrats on the update! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!
