### ISSUE TITLE
[UPDATE OUTDATED CONTENT] A Guide to Using Hugo

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#845]
**Description**

A link to the article can be found here
https://strapi.io/blog/guide-to-using-hugo-site-generator

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Ezekiel8807** [comment]
I would love to write on this

**Comment by TiaraOluwanimi** [comment]
Hello, @Ezekiel8807, still up for this?

**Comment by dessireugarte** [comment]
Hello @Ezekiel8807 👋 Any news on this update?

**Comment by Ezekiel8807** [comment]
I'm off on this

**Comment by FeliciaSephodi** [comment]
I'd like to work on this. 🙋‍♀️

**Comment by FeliciaSephodi** [comment]
I'd love to write this!🙋‍♀️

**Comment by dessireugarte** [comment]
Hello @FeliciaSephodi 👋
I'll assign the issue to you. Let me know when the draft is ready, so we can review it 👍

**Comment by FeliciaSephodi** [comment]
Thank you I'll start working on it.

**Comment by FeliciaSephodi** [comment]
I'll be sending the draft by the weekend.
