### ISSUE TITLE
[Request New Content] Video to Article: Render, Remix, and Strapi: Let's Build a Productivity Tips App

### ISSUE THREAD

**Issue by ShadaW11** [strapi/community-content#846]
**My Request**

Objective: Transform the workshop video into a blog post.
Deadline to submit: 23 May 
Link to video
https://youtu.be/zPT_K4Q8_RA

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by TheGhoulRe** [comment]
Hi @ShadaW11, can I work on this

**Comment by ShadaW11** [comment]
Yes please go ahead @TheGhoulRe  I sent you details on discord.

**Comment by ShadaW11** [comment]
As mentioned on Discord, please register to join the WFC program, go over the guidelines and then go over the video briefly and submit your outline. Once you do, I will review it and make sure it covers everything we need. Please note that the deadline for submission is on 25 May.

**Comment by ibn-ashimi** [comment]
Hello @ShadaW11 Here is my outline

Introduction
- What are Strapi, Remix and Render
Goals
- What we’re building
Prerequisites
Setting up
Configuring Strapi
Building App
Deployment
Conclusion

**Comment by TheGhoulRe** [comment]
Hi @ShadaW11, That wasn't me

The list of topics I'll be covering in this article are:

1. Introduction
2. Prerequisites
3. Why Remix?
4. Why Strapi?
5. The Strapi APP
6. The Remix APP
    1. step 1
    2. step 2
    3. step 3
    4. step 4
    5. step 5
7. Deploy to Render
8. Conclusion

**Comment by ShadaW11** [comment]
@ibn-ashimi please focus on the other article you are working on.

**Comment by ShadaW11** [comment]
@TheGhoulRe I have sent you an email. Can you please confirm receiving it.

**Comment by TheGhoulRe** [comment]
@ShadaW11, I have received the email

**Comment by ShadaW11** [comment]
@TheGhoulRe following our conversation on Discord, I assigned the article to you.

**Comment by TheGhoulRe** [comment]
Thank you @ShadaW11

**Comment by ShadaW11** [comment]
https://www.dropbox.com/scl/fi/9qs0m0aw8lpg0knuoc52w/Build-a-productivity-tips-application.paper?dl=0&rlkey=y4riy3k4s8q26h1yn87g0levc

**Comment by ShadaW11** [comment]
Thank you so much @TheGhoulRe for your efforts. Please submit your invoice. Your article was published.
