### ISSUE TITLE
[UPDATE]How to Build a Real-time Chat Forum using Strapi, Socket.io, React and MongoDB

### ISSUE THREAD

**Issue by divofred** [strapi/community-content#859]
**My update**
@ShadaW11 @TiaraOluwanimi @PaulBratslavsky  This [article](https://strapi.io/blog/how-to-build-a-real-time-chat-forum-using-strapi-socket-io-react-and-mongo-db) makes use a NoSQL database (MongoDB) and Strapi v3 codes.
I'll use a supported database and implement Strapi v4 features.
**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by divofred** [comment]
@TiaraOluwanimi What do you think about this update?

**Comment by PaulBratslavsky** [comment]
Closed due to similar content.
