### ISSUE TITLE
[TOPIC] Connect Cloudinary support with Strapi.

### ISSUE THREAD

**Issue by RuchikaPegasus** [strapi/community-content#86]
An updated new tutorial to connect cloudinary support with strapi.

**Comment by RazvanCretu** [comment]
Hi @Mcastres 

I would like to engage on this one if none is assigned. Is it okay?

**Comment by Mcastres** [comment]
Sure! Will it be a video or an article?

**Comment by RazvanCretu** [comment]
I'll make an article.

**Comment by Mcastres** [comment]
Awesome! Can't wait to review it!

**Comment by RazvanCretu** [comment]
Hi @Mcastres ,

This is now done. I've shared the paper with you on Slack so you can review it. Let me know if there are any imporvements needed.

**Comment by Mcastres** [comment]
Thanks I'll review it today :)

**Comment by malgamves** [comment]
This was published - [Adding Cloudinary support to your Strapi Application](https://strapi.io/blog/adding-cloudinary-support-to-your-strapi-application)
