### ISSUE TITLE
[SUBMIT] Building a School Website with Strapi CMS using Vanilla JS

### ISSUE THREAD

**Issue by Dmuasya** [strapi/community-content#861]
**My resource**

Hello 👋 

This article will be about a school website that I built with some backend services. I have worked with local JSON data before and it's difficult to update and delete the content. Luckily [Strapi](https://strapi.io/) is an open-source Headless CMS, you can design APIs quickly, and manage content smoothly. Readers will learn how to build a school website with Strapi CMS using vanilla.Js

Outline:
- Introduction
- What is REST APIs
- How to read DOCS
- How to work with Strapi CMS?
- HTML structure with meaningful Classes
- JS DOM, ES6 Syntax & ES6 Modules
- How to Fetch Data and show it on the Screen
- Async/Await & Fetch API
- Responsive Design
- SASS(SCSS) modules & BEM Convention
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open-source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by Dmuasya** [comment]
Hi @malgamves Do I proceed with writing the draft article? 
@ShadaW11

**Comment by PaulBratslavsky** [comment]
@Dmuasya yes you can proceed.  Thank you.

**Comment by PaulBratslavsky** [comment]
@Dmuasya can you please confirm if you are currently working on this?  Thank you.🙂

**Comment by PaulBratslavsky** [comment]
@Dmuasya Thank you.

**Comment by Dmuasya** [comment]
Hi, @PaulBratslavsky 
Here is the link to the draft article [LINK ](https://www.dropbox.com/scl/fi/96fxn2w3tgksr3mx2684y/Final-Building-a-School-Website-with-Strapi-CMS-using-Vanilla-JS.paper?dl=0&rlkey=vve0m5ysn4rcejt29l8q88mcn)

**Comment by Dmuasya** [comment]
Hello @TiaraOluwanimi I made the updates you requested

**Comment by dessireugarte** [comment]
Hello @Dmuasya   👋
Just wanted to let you know that your article will be published around the second week of September. I'll let you know when it is published!

**Comment by Dmuasya** [comment]
> Hello @Dmuasya 👋 Just wanted to let you know that your article will be published around the second week of September. I'll let you know when it is published!

**Comment by dessireugarte** [comment]
Hello @Dmuasya 👋
I guess it is an error, but the tutorial is in v3 and we are not longer posting any tutorial in v3. Could you please update accordingly? 
cc @TiaraOluwanimi

**Comment by Dmuasya** [comment]
Hello @TiaraOluwanimi Please confirm the updates.

**Comment by dessireugarte** [comment]
Hello @TiaraOluwanimi 👋 
This article is ready for one last review and then update in the backend.

**Comment by dessireugarte** [comment]
Hello @Dmuasya  👋 
Your article is [live](https://strapi.io/blog/how-to-build-a-school-website-with-strapi-cms-using-vanilla-javascript)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by Dmuasya** [comment]
Hi, @malgamves I sent an invoice but have yet to receive any feedback.

**Comment by Dmuasya** [comment]
Hey, @malgamves Please resend the email because I can't seem to find it.
