### ISSUE TITLE
FORUM WEBSITE TUTORIAL

### ISSUE THREAD

**Issue by crimsonflower420** [strapi/community-content#863]
**My Request**
Can you guys make a tutorial on how to use strapi to build a forum?

Would be very useful to a lot of people I think.

Best,

Grant
**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by shivanshsrivastava24** [comment]
@grantgolland can I please take this up. Thanks!

**Comment by PaulBratslavsky** [comment]
@shivanshsrivastava24 can you come up with an outline of what you were thinking of writing about.

**Comment by PaulBratslavsky** [comment]
@shivanshsrivastava24 let me know if you are still interested working on this article.

**Comment by bhagatpratham** [comment]
I think the article is available for this [here.](https://strapi.io/blog/how-to-build-a-forum-app-with-next-js-and-strapi-cms)

**Comment by grantgolland** [comment]
Very cool! Thanks for making this

**Comment by PaulBratslavsky** [comment]
Closing issue due to similar article already existing https://strapi.io/blog/how-to-build-a-forum-app-with-next-js-and-strapi-cms
