### ISSUE TITLE
[SUBMIT] Build a Blog  APP with Remix and Strapi

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#865]
A brief outline:

- What is Strapi
- Why Remix
- Goal
- Prerequisites
- Setup Backend with Strapi CMS
- Setting up a Remix Project
- Project dependencies
- Building components
- Creating the Pages
- Displaying posts
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by kimkimani** [comment]
Hi @ShadaW11, What's your thought on this subject?

**Comment by PaulBratslavsky** [comment]
@kimkimani hey I Paul.  Nice to meet you.  I will be taking in some of Shada's responsibilities here, did you start working on the article? Do you have any questions?

**Comment by kimkimani** [comment]
Not yet @PaulBratslavsky. I wanted to know if the topic looks good so that I can start working on the article.

**Comment by PaulBratslavsky** [comment]
@kimkimani I think it will be good.   In the "Why Remix" It would be nice to see an explanation what benefits Remix offers vs using something like Next JS. ( like what does it to better and why )

Also , were you planning on covering deployment in this article. Maybe that can be part 2.

**Comment by PaulBratslavsky** [comment]
@kimkimani just wanted to check in on how you are doing on your progress?

**Comment by kimkimani** [comment]
The draft is ready @PaulBratslavsky.

https://www.dropbox.com/scl/fi/8plr7c7nbg03b6osywwmm/Build-a-Blog-APP-with-Remix-and-Strapi.paper?dl=0&rlkey=b81rdbh3z0hjb2od47wnxr1ny

**Comment by PaulBratslavsky** [comment]
@TiaraOluwanimi this article is ready to be reviewed.

**Comment by dessireugarte** [comment]
Hello @kimkimani 👋 Just wanted to let you know that your article will be published around the first week of September. I'll let you know when it is published!

**Comment by dessireugarte** [comment]
Hello @kimkimani 👋 
Could you please fill out [this](https://strapi.io/write-for-the-community) form?
I didn't find your information and we need to make the article public 😊

**Comment by dessireugarte** [comment]
Hello 👋 
Your article is [live](https://strapi.io/blog/how-to-build-a-blog-app-with-remix-and-strapi-cms)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. Please feel free to reach out to me if you have any questions!
