### ISSUE TITLE
Building a Job Nina with Sapper and Strapi v4

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#868]
Job nina is a website where job seekers can apply for positions. So, using strapi as our backend, I will build a site with Sapper where job seekers can apply for jobs and even write a specific job they need. 

Outline
Introduction
What is sapper
What Strapi is
Setting up a Strapi project
building our project
testing our project
Conclusion

-->

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
At the moment we are not looking for this type of article so will be closing the issue for the  time being.
