### ISSUE TITLE
[ISSUE] Strapi Food App tutorial asks to install mongoDB

### ISSUE THREAD

**Issue by nuno-ferrao** [strapi/community-content#871]
nextjs-react-hooks-strapi-food-app-1 asks us to boot the project using MongoDB, but Strapi no longer allows for this option. We can only select an SQL-based database.

EXPECTED: Tutorial should be updated to reflect this.

**Comment by PaulBratslavsky** [comment]
@nuno-ferrao thank you we are currently in the process of looking for the author to take care of this.

**Comment by PaulBratslavsky** [comment]
@nuno-ferrao I am going to close this issue because it is a duplicate of https://github.com/strapi/community-content/issues/889. The author started working on this.🙂
