### ISSUE TITLE
[Request New Content] Strapi v4 Authentication with Remix 

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#872]
**My Request**

Strapi v4 Authentication with Remix 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by miracleonyenma** [comment]
Hey @dessireugarte @ShadaW11 

This is awesome! ❤️
I'm interested in writing an article for this topic. I'll create an outline and share ASAP!

**Comment by miracleonyenma** [comment]
Hey @dessireugarte @PaulBratslavsky 

Here's my proposed outline for this topic:

# Strapi v4 Authentication with Remix
Authentication is an integral part of any application with users, but setting up a complete authentication & authorization workflow from scratch will be incredibly time-consuming and unproductive unless in some unique cases. With Strapi, we have access to [multiple authentication providers like Google, Twitter](https://docs.strapi.io/developer-docs/latest/plugins/users-permissions.html#setting-up-the-provider-examples), etc.
This enables us to easily set up authenticated requests to our Headless CMS API to fetch data or perform actions that are only available to authenticated and authorized users.
Now we can quickly set up a robust authentication system for our application and focus on building.

In this article we’ll take a look at how we can setup a simple Remix application and implement user authorization and authentication with Strapi


## Brief overview

This article will cover the concept of a Headless CMS, what Strapi is and how to set it up. We’ll also briefly dive into the concept of authentication and authorization and solutions with Strapi. Then, we’ll dive into how we can build the frontend using Remix and how we can implement authentication in a Remix application.


## Goals

At the end of this tutorial, we would have covered how to add authentication to our Remix application with Strapi.


## **Outline**
- Brief introduction to Headless CMS
    - What is Strapi?
- Authentication in Strapi
- What is Remix?
- Goals
- Prerequisites
- Set up Strapi
    - Create collection types
    - Configure Roles & permissions
- Set up Remix
    - Add TailwindCSS for styling
- Authentication in Remix
    - Authentication flow
- Build the login page
- Registration page 
- Logout Action
- Authenticated User Dashboard 
    - Validating authentication status
- Set up password Reset functionality
    - Request password reset page
    - Create new password page
- Conclusion 
- Further reading & resources



There you go, I'm looking forward to your feedback and suggestions ✨

**Comment by dessireugarte** [comment]
Hello @miracleonyenma 👋 How are you doing? 
It looks good to me. I changed the status so you can get started! 👍 
Let us know when it's good for the review!

**Comment by TiaraOluwanimi** [comment]
@miracleonyenma, any updates on this?

**Comment by TiaraOluwanimi** [comment]
Hello,  @miracleonyenma. I need to confirm if you're working on this or if we should re-open it to other writers.

**Comment by miracleonyenma** [comment]
Hey @TiaraOluwanimi, I apologize for the delay, I'm currently working on the draft and will be making a submission soon. Thanks.

**Comment by miracleonyenma** [comment]
Hey @TiaraOluwanimi @dessireugarte @PaulBratslavsky 
I'm pleased to announce that the draft is ready 🎉

Here's [the link to it in Dropbox Paper](https://www.dropbox.com/scl/fi/6b0qsyotoqkk6gdhf5kw2/Strapi-v4-Authentication-with-Remix.paper?dl=0&rlkey=ufcr668p9r1gbgz52z23byv9a)

Looking forward to the review! 🤸🏾‍♂️

**Comment by dessireugarte** [comment]
Awesome! Thanks @miracleonyenma 👏
We will review the article and get back to you!

**Comment by dessireugarte** [comment]
Hello @miracleonyenma   👋
Just wanted to let you know that your article will be published the second week of August so you can proceed to submit your invoice and get your payment.

**Comment by miracleonyenma** [comment]
Hey @dessireugarte 👋🏾. 
That's awesome. Thank you so much.

I went ahead and created the invoice but wasn't able to submit it because the form seems to be closed?
![image](https://user-images.githubusercontent.com/42788603/181875656-7c24d68f-ccea-4f96-8169-73ec311e1d17.png)

I got the link to this form from the FAQ section of the [WFC page](https://strapi.io/write-for-the-community)

Has the form been moved? What steps should I take to successfully submit my invoice?

Thanks in advance. ✨

**Comment by malgamves** [comment]
we'll update the link on the WFC page, thanks for the heads up. Also, processed your invoice 🚀

**Comment by dessireugarte** [comment]
Hello @miracleonyenma 👋
Your [article](https://strapi.io/blog/strapi-v4-authentication-with-remix) is live! 🎉

Since you already submitted your invoice, you will soon receive your payment. Feel free to reach out if you have any questions!
