### ISSUE TITLE
[Request New Content] Deployment options and how to pick one

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#873]
**My Request**

Article explaining the most popular deployment options used with Strapi. What should be taken into consideration for each option before deciding on one and use cases (if relevant). 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by hubertnare** [comment]
@PaulBratslavsky may I work on this?

**Comment by PaulBratslavsky** [comment]
@hubertnare Yes.  It will b awesome. Can you provide an outline of what you were thinking of covering?

**Comment by hubertnare** [comment]
Okay sure! Sending in a bit...

**Comment by PaulBratslavsky** [comment]
@hubertnare are you still interested in writing this artcle.

**Comment by hubertnare** [comment]
Hey Paul my apologies for the delay, will send the outline in the next 24 hrs to come...

**Comment by hubertnare** [comment]
Hie @PaulBratslavsky 

unfortunately for some reasons I will not be able to continue working on this. But, below, I listed some points to consider when writing the article.

Here are some points to include when writing this article;

## [Title] Strapi deployment options and how to pick one.

### [Introduction] A brief, motivating introduction plus a teaser of the upcoming Strapi Cloud (future best deployment option).

### Migrations between Strapi environments && how to handle different migrations;
- Development
- Production
- Test

### Frontend & Backend deployments (separation of concern);
- using webhooks to trigger rebuild events.

### Deployment considerations;
- One-click deployments.
- Manual deployments.

### Deployment options available;
- 21YunBox
- Amazon AWS
- Azure
- Cleavr
- e.t.c 

### Pros and Cons of the aforementioned "Deployment options"

### Additional software that can supplement or enhance the deployment process, when utilizing Strapi in a production-like environment,

**Comment by dessireugarte** [comment]
Hello @hubertnare! 
Thanks for sharing the outline. We will look for a new author then.

**Comment by ibn-ashimi** [comment]
@dessireugarte Can i take this up?

**Comment by bomanaps** [comment]
I would love to write on this.

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 👋 
Thanks for reaching out. Please go ahead and let us know when the draft is ready to review.

**Comment by dessireugarte** [comment]
Hello @bomanaps 👋 Someone else to it but other articles are currently without an author assigned, would you be interested in any of [these](https://github.com/strapi/community-content/projects/1)? The cards with the "Looking for an author" tag.

**Comment by ibn-ashimi** [comment]
Alright @dessireugarte. Thanks!

**Comment by spirobel** [comment]
I wrote something tangentially related to this: https://twitter.com/spirobel/status/1555473443839098880 it also has a small video to show how easy it is. I think this is truly the easiest option to get people started. It is basically just 2 clicks.  No need to learn about databases haha.  I original wrote this as a reply in Pauls awesome coding group 🙂 😅 😎  but I thought it might also be helpful to others so I put it in my substack: https://spirobel.substack.com/p/a-first-look-at-strapi?utm_source=%2Finbox&utm_medium=reader2 more than happy if you want to copy and paste parts from this.

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 👋
Just wanted to check if you are working on this draft?

**Comment by ibn-ashimi** [comment]
Yes I am. I will be done soon.

**Comment by ibn-ashimi** [comment]
https://www.dropbox.com/scl/fi/r02rqmxubwey7xvltyjs2/Strapi-Deployment-Options-and-How-To-Pick-One.paper?dl=0&rlkey=wnb3bbkx7qgie6fcwogk1fzh8

Hi @TiaraOluwanimi @dessireugarte

**Comment by dessireugarte** [comment]
Thanks @ibn-ashimi!
We will review the article, and get back to you if we need changes.

**Comment by TiaraOluwanimi** [comment]
Hello, @ibn-ashimi. I dropped a couple of comments on the doc. Please, check, fix, and revert. Thanks!

**Comment by ibn-ashimi** [comment]
Hi Boss @TiaraOluwanimi. Have you had time to check this?

**Comment by dessireugarte** [comment]
Hello @TiaraOluwanimi 
This article is good to be added to the backend. I'll let you know asap when we are publishing this one @ibn-ashimi

**Comment by ibn-ashimi** [comment]
Thank you @dessireugarte

**Comment by ibn-ashimi** [comment]
@dessireugarte Any update on this?

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi. I previously said it was ready, but there was one last review done and feedback from the review. I left comments on the document. After those changes, we will publish it asap.

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi! Did you get the chance to make the changes requested?

**Comment by ibn-ashimi** [comment]
yes please. Take a look.

**Comment by dessireugarte** [comment]
@ibn-ashimi I left this comment: 
Hello ​@Abdulwahab. I still feel this article is not providing too much information about the deployment options. I made some changes to the structure, and I had to delete the one-click deployment options since we don’t maintain them anymore. I expanded the introduction of Heroku to exemplify how could each option could be described (including the most popular ones). As soon as the changes are done, we will publish it ​👍

**Comment by dessireugarte** [comment]
Hello @ibn-ashimi 👋 
Your article is [live](https://strapi.io/blog/6-top-deployment-options-for-your-strapi-application)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
Please feel free to reach out to me if you have any questions!

**Comment by ibn-ashimi** [comment]
Thank you very much, @dessireugarte

**Comment by ibn-ashimi** [comment]
Hi, @malgamves. I have submitted my invoice.

**Comment by ibn-ashimi** [comment]
any update on this @dessireugarte
