### ISSUE TITLE
Build A Twitter Clone with React and Strapi

### ISSUE THREAD

**Issue by marvelken** [strapi/community-content#875]
Introduction
Setting up REact.js & Tailwind CSS
Initialising the Build
Building the Sidebar Component
Building the SidebarRow Component
Building the Feed Component (1/2)
Building the Widgets Component
Implementing Responsive Design
Building the TweetBox Component
Setting up Strapi
Explaining and Implementing Server-Side Rendering
Pulling Tweets from Strapi to the Feed
Building the Feed Component (2/2)
Building the Tweet Component 
Implementing Comment Functionality
Implementing react-hot-toast
Implementing the Login Functionality 
 Implementing the Image URL Functionality
Adding Tweet Functionality using Mutations

**Comment by PaulBratslavsky** [comment]
Sorry for super late response, trying to catch up with all the submissions.  You cam get started with this if you are still up for it?

**Comment by marvelken** [comment]
Hi Strapi/Community-Content,
I would get started with it.

Regards.

**Comment by marvelken** [comment]
Hi Paul,
I am done with draft, you can help with the edits.
https://www.dropbox.com/scl/fi/bjc2246l040xpk075l6ak/Build-a-Twitter-Clone-with-React-and-StrapiCMS.paper?dl=0&rlkey=oqeegdvrusknqwwr11uzdkuup

**Comment by hanakhelifa** [comment]
Hello @marvelken,
Thank you for your submission here, I like the idea of tutorials for clones of simple popular application.
I'll close this topic as I see the article has already been published on Medium and openreplay, and because this topic is more than a year old right now. :)
