### ISSUE TITLE
[SUBMIT] How to create a realtime Bidding App using Strapi v4, Vue and Socket IO

### ISSUE THREAD

**Issue by i1d9** [strapi/community-content#876]
**My resource**

Hello 👋 

Goal
In this tutorial, we will be building a real-time bidding application using Vue, Socket IO and Strapi. We will learn how to extend and override strapi plugin functions. We will also create service functions for our collections and call them within socket communication flows. In addition, we will use strapi's jwt authentication system to verify user token before accepting a socket connection.

Outline - 

- Introduction
- Prerequisites
- Why Strapi, Socket IO and Vue?
- Initialize a strapi project
- Creating new user roles
- Creating Collections
- Extending Collection services
- Extending User Permissions Plugin
- Socket IO Initialization
- Socket Authentication
- Initialize the vue project
- Installation of auxiliary dependencies
- Creation of components
- Mapping of components to routes
- Setting state persistency
- Socket Initialization
- Loading Data through socket connections
- Manipulating Data through socket connections
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by i1d9** [comment]
@PaulBratslavsky  Here's the [Article](https://www.dropbox.com/scl/fi/jrha49e6tg0hjx1xx4csp/How-to-create-a-real-time-Bidding-App-using-Strapi-v4-Vue-and-Socket-IO.paper?dl=0&rlkey=y8tq4anar7az7dv39fd8245wn) Draft. I'm looking forward to your comments.

**Comment by PaulBratslavsky** [comment]
This sounds awesome.  Keep going.

**Comment by PaulBratslavsky** [comment]
@i1d9 Looks great. Do you have any changes that you need to make, or will this be your final draft?

**Comment by i1d9** [comment]
@PaulBratslavsky Thank you for the feedback. That's the final draft.

**Comment by dessireugarte** [comment]
Hello @i1d9 👋
Just wanted to let you know that your article will be published next week so you can proceed to submit your invoice and get your payment.

**Comment by dessireugarte** [comment]
Hello @i1d9 👋 Your article is [live](https://strapi.io/blog/how-to-create-a-real-time-bidding-app-using-strapi-v4-vue-and-socket-io)! 🎉
You can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) to get your payment.
