### ISSUE TITLE
Building a Job Nina with Sapper, Strapi v4 and Netlify

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#877]
Job nina is a website where job seekers can apply for positions. So, using strapi as our backend, I will build a site with Sapper where job seekers can apply for jobs and even write a specific job they need.

Outline
Introduction
What is sapper
What is Strapi 
Setting up a Strapi project
building our project
testing our project
Conclusion

**Comment by lucky4242** [comment]
Okay, I'm working on it.

**Comment by PaulBratslavsky** [comment]
@lucky4242 thank you 🙂

**Comment by lucky4242** [comment]
Hello @PaulBratslavsky 
Here is the draft for this article https://www.dropbox.com/scl/fi/hzngfijv2nvuic8u2czk2/Building-a-Job-Nina-with-Sapper-Strapi-v4-and-Netlify.paper?dl=0&rlkey=vj7dbeejjz1bkeoppaqtv61yn

**Comment by lucky4242** [comment]
Hello @Paul Bratslavsky
It's been almost 20 days since I submitted this draft and no response from
anyone yet
Here is the tutorial draft.
https://www.dropbox.com/scl/fi/hzngfijv2nvuic8u2czk2/Building-a-Job-Nina-with-Sapper-Strapi-v4-and-Netlify.paper?dl=0&rlkey=vj7dbeejjz1bkeoppaqtv61yn

And also a draft update to this tutorial.
https://www.dropbox.com/scl/fi/3gakpnm17do3m2vlh9sr1/Deploying-a-Strapi-API-on-Heroku-in-5-min.paper?dl=0&rlkey=gupk256zozcay2cipt8k1pvkv

Thanks

**Comment by dessireugarte** [comment]
Hello @lucky4242 👋
Sorry for the delay, I included @TiaraOluwanimi so your article is reviewed and we can publish it. We will keep you updated 😊

**Comment by lucky4242** [comment]
Hi @Dessire Ugarte Amaya ***@***.***>
what's the update on this article?

**Comment by lucky4242** [comment]
Hi  @dessire
Please what's the update on this article?
https://www.dropbox.com/scl/fi/hzngfijv2nvuic8u2czk2/Building-a-Job-Nina-with-Sapper-Strapi-v4-and-Netlify.paper?dl=0&rlkey=vj7dbeejjz1bkeoppaqtv61yn

**Comment by dessireugarte** [comment]
Hello @lucky4242 👋
Sorry for the delay on this article, 
On October third we will post it on the blog. I will ping you as soon as we post it.

**Comment by dessireugarte** [comment]
Hello @lucky4242  👋 
Your article is [live](https://strapi.io/blog/building-a-job-nina-with-sapper-strapi-v4-and-netlify)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by lucky4242** [comment]
Hi @Dessi
It's 10days past now  i sent an invoice, yet no response. Hope to hear from
you soon

**Comment by dessireugarte** [comment]
Hello @lucky4242 👋
Daniel shared [this](https://discord.com/channels/811989166782021633/843965836887851078/1031584885258866760) message on Discord. We are working on that, soon you will get it. Otherwise, you can contact us again.
