### ISSUE TITLE
User Registration and Login (authentication) with Sapper and Strapi v4 

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#878]
Registration and login  is all about authentication with strapi.

I will drop outline if the topic is approved, i hope it is approved

**Comment by PaulBratslavsky** [comment]
@lucky4242 can you provide a brief outline of what you will cover in this tutorial, just to give me more context on what to expect.  Makes it easier for me to decide which articles to approve.  Thank you.  And sorry for my late response, been trying to catch up with all the submissions.

**Comment by lucky4242** [comment]
Hi @PaulBratslavsky
Ready to work on this topic 
Here is the outline 

Introduction.
Goal.
Prerequisite.
What is Sapper?
Installing Sapper.
Building the Frontend.
What is Strapi. 
Initializing a Strapi project.
Creating Collections.
User registration.
User login.
Building our poject.
Testing. 
Conclusion.

**Comment by lucky4242** [comment]
Hi @PaulBratslavsky 
can i start working on this article?

**Comment by PaulBratslavsky** [comment]
@lucky4242 sorry for the late reply; moving into 2023 at the moment, we are looking for more Strapi-specific articles that cover strapi code-specific topics.  Will be closing this issue for now.
