### ISSUE TITLE
[SUBMIT]How to Make API calls in Android using Retrofit and Strapi CMS

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#879]
- Outline
- Introduction
- What is Retrofit
- What is Strapi
- Setting up API using Strapi
   - Managing Backend Content using Strapi
   - Creating the API Access Token
   - Consuming Strapi API using Android
- Setting up Android Studio
  - Adding application dependencies
  - Creating Client Interfaces
  - Creating Models
  - Setting up application Layouts
  - Setting up Adapters
  - Setting up Strapi Authorization Headers on Android
  -  Setting up Retrofit
  - Displaying Strapi API Data on Android
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@kimkimani sorry I am trying to catch up with all submissions here.  Sorry for late response.  But can you give an outline of what you would like to cover in this article.

**Comment by kimkimani** [comment]
@PaulBratslavsky I can use this issue to build the mobile application using android instead of flutter

**Comment by kimkimani** [comment]
Hello, @PaulBratslavsky  This one is ready for review.

https://www.dropbox.com/scl/fi/l0hdbizi6u8vr9g6qcei0/How-to-Make-API-calls-in-Android-using-Retrofit-and-Strapi-CMS.paper?dl=0&rlkey=vbqugnmrgzbvbe700jjyxgg13

**Comment by PaulBratslavsky** [comment]
@kimkimani we will add this to our review cue, we currently have a lot of articles at the moment and doing the best we can.

**Comment by PaulBratslavsky** [comment]
@kimkimani I know it has been a while, hope you are well.  Your article is reviewed and we can schedule it to publish.  Sorry for the delay, we have been working with a smaller team.  Just confirm that you are ok with us publishing your article.

**Comment by hanakhelifa** [comment]
Hi @kimkimani,
Thanks for your article! All the reviews have been made–can you confirm that we can go ahead and publish with your name?

**Comment by kimkimani** [comment]
Hello @hanakhelifa 

Yes, that will be fine

**Comment by hanakhelifa** [comment]
@kimkimani Awesome, we'll get it published next week then. Could you fill the table at the top of the document until then, that contains information such as your name so we can put the proper author name, as well as a meta description.

**Comment by kimkimani** [comment]
Great. I have added these sections

**Comment by hanakhelifa** [comment]
Hi @kimkimani 
Closing this issue as we've done the review and published the article :)
