### ISSUE TITLE
[SUBMIT] Strapi Deployment on Heroku with Postgres

### ISSUE THREAD

**Issue by Balaji2198** [strapi/community-content#88]
**My resource**
Step by step guide to setup and deploy Strapi on Heroku with Postgres. Comments are welcome! Thanks!

**Article link:**
https://medium.com/techzap/deploying-strapi-on-heroku-ac48e663afd8

**My format**

- [x] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Thanks Balaji for this contribution! We really appreciate that :)
