### ISSUE TITLE
[SUBMIT] How to Perform Flutter Authentication with Strapi

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#880]
- What is Strapi
- What is Flutter
- Installing Strapi
- Overview of Strapi application
- Create Strapi locally
- Setup Flutter project
- Setup our networking logic
    - Add Http library to fetch APIs
    - Implement API fetching layer
- Build screens 
    - Build login screen 
    - Build registration screen
    - Build listing screen 
- Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by kimkimani** [comment]
Hello @PaulBratslavsky I have updated the outline for this one

**Comment by PaulBratslavsky** [comment]
@kimkimani ok, so this is ready? https://www.dropbox.com/scl/fi/zsiitixlihth5vhbkwwfj/How-to-Perform-Flutter-Authentication-with-Strapi.paper?dl=0&rlkey=istibvspkyrwlcfk05jsgk3qm

**Comment by kimkimani** [comment]
Yes @PaulBratslavsky

**Comment by PaulBratslavsky** [comment]
@kimkimani we are finally catching up with our back log of articles.  Let us know if you are still interested in us publishing this article.

**Comment by kimkimani** [comment]
Hello @PaulBratslavsky, Let make a few updates just to make sure everything is up to date

**Comment by PaulBratslavsky** [comment]
@kimkimani just let me know when you are ready.  Thank you.

**Comment by hanakhelifa** [comment]
Hi @kimkimani!
Do you have an update or an ETA to share with us? :)

**Comment by kimkimani** [comment]
Hello @hanakhelifa, I will this post ready at he end of this week

**Comment by kimkimani** [comment]
Hello @hanakhelifa and @PaulBratslavsky, The draft looks good now: https://www.dropbox.com/scl/fi/4thdcoemcqhsjtpdsou21/Untitled.paper?rlkey=268x4y3i9qbzxozd2axw2y4f8&dl=0

**Comment by hanakhelifa** [comment]
Hello @kimkimani, Thanks for your draft. I reviewed it last week. I still need to add a few comments, but I think we can aim for a publication this week. :)

**Comment by kimkimani** [comment]
Thank you @hanakhelifa

**Comment by hanakhelifa** [comment]
Hi @kimkimani 
The article is published [right here](https://strapi.io/blog/mastering-flutter-authentication-with-strapi-cms-a-step-by-step-guide) 🙌
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. You can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment.
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by hanakhelifa** [comment]
Closing the issue as we've done the review and published the article
