### ISSUE TITLE
[SUBMIT] Strapi: Accept Payments Via Paystack

### ISSUE THREAD

**Issue by Otrex** [strapi/community-content#882]
**My resource**

Although major payment processors like Paypal and Stripe exist, most of them don't work in some countries like Nigeria due to several reasons. Startups in such countries find it difficult to setup their businesses and accept payment due to the tedious and expensive process it takes to setup up both their platform and their payment processor. So this is where Strapi and Paystack comes in. 
Paystack is among the number one payment providers in Africa today. it is backed by notable investors as well as some of the best payments companies on the planet and supports countries that may not be supported by their competitors like Paypal and others. They provide very-easy-to-implement APIs and can also be used for much more complication payment processing.

Goals
So in this tutorial, we would be demonstrating the power of the Paystack payment processor by building a savings app using the Ionic-Vue as the framework and Strapi. 

Outline

- Introduction 
- Setup Server
    - Setup the Strapi project
        - Installing Strapi
        - Installing paystack-api-ts npm package
    - Create models to handle both transactions and users
    - Create routes to make payments
    - Create webhook to update transaction state
- Setup the Client App
    - Setup the Ionic(Vue) project
    - Setup the routes
    - Create pages to handle register, login, make payment, view profile
- Integrate the Strapi and Paystack APIs
    - Integrate the Strapi API developed
    - Integrate the Payment PopUp on the UI
- Testing

Conclusion & Resources

- Github source code
- VueJS
- Ionic
- Strapi

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@Otrex I like it, let me know if you already started on this?

**Comment by PaulBratslavsky** [comment]
@Otrex I know it has been a while, just wanted to check in if you still have the bandwidth to finish your article?

**Comment by Otrex** [comment]
Yeah...  I can

**Comment by Otrex** [comment]
I thought you guys had stopped the author programme. So I just stopped too

**Comment by PaulBratslavsky** [comment]
@Otrex thank you for your patients, we have had a lot of previous article submissions that we were working through and our team size got smaller so it has been taking us longer then expected to get to all the articles.  I am looking forwards to your post. Thank you.

**Comment by Otrex** [comment]
Hi @PaulBratslavsky, please can I submit this by Monday? I encountered some challenges when I was trying to update the packages I used.

**Comment by PaulBratslavsky** [comment]
@Otrex you can submit it when it is ready.

**Comment by hanakhelifa** [comment]
Hello @Otrex, do you have a draft or an ETA to share with us? 
I see that you mentioned working on it on July 2022. As we are revamping the WFC program, I am doing some triage in previous posts. I'll close issues that are inactive, let me know when you can.

**Comment by Otrex** [comment]
Hi, so sorry for the delay. The draft is almost complete. Please give me till next tomorrow to submit it. Thanks

**Comment by Otrex** [comment]
Hi, please i'll be dropping the draft before the end of today.

**Comment by Otrex** [comment]
Hi, here is the link to the draft https://docs.google.com/document/d/1TKRTj-6R3ZIdaggn82lqWzY4RbeIwzWTyOoytCNsiCE/edit?usp=sharing

**Comment by Otrex** [comment]
Please I am making some updates to the draft. I'll inform you when it's completed

**Comment by hanakhelifa** [comment]
Hi @Otrex 
Thanks for this submission! Make sure to ping me when you need a review here.

**Comment by hana75** [comment]
Closing the issue for now as the topic seems on hold.
