### ISSUE TITLE
Resource for learning strapi

### ISSUE THREAD

**Issue by Hemanth85534** [strapi/community-content#888]
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Saintdavidking** [comment]
Hello, @Hemanth85534 I will like to take on this topic

**Comment by Smart-duke** [comment]
Can I take up this?

**Comment by PaulBratslavsky** [comment]
This is currently not a topic that we are looking for.  Thank you for submitting.
