### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Tutorial: Create a food ordering app with Strapi and Next.js

### ISSUE THREAD

**Issue by EdenSweden** [strapi/community-content#889]
**Description**
The tutorial describes how to connect Mongo with Strapi, but yarn create strapi-app no longer supports Mongo. I attempted to install an older version of Strapi to follow the tutorial, but the other packages were not compatible with the newest version of node.

**Link of the content**
https://strapi.io/blog/nextjs-react-hooks-strapi-food-app-1

Thank you!

**Comment by divofred** [comment]
Hi @PaulBratslavsky, can I update this article?

**Comment by PaulBratslavsky** [comment]
@divofred yes, that would be a great idea.  So instead of using MongoDB, we can use PostgreSQL.

**Comment by divofred** [comment]
Hello @PaulBratslavsky, Should I send an outline?

**Comment by PaulBratslavsky** [comment]
@divofred I am still waiting for the response to your question.  Want to make sure that I get the right information before you embark on this update.

**Comment by divofred** [comment]
@PaulBratslavsky Noted. I'll be waiting for your response.

**Comment by divofred** [comment]
Hello @dessireugarte @PaulBratslavsky.
I'm done with this update.
[Here's](https://www.dropbox.com/scl/fo/sf60p0z71pen8ysn44l5i/h?dl=0&rlkey=qw6c2pv4zqg034ph01kr3iy0v) the dropbox link.

**Comment by PaulBratslavsky** [comment]
@divofred thank you so much we will start the review. @TiaraOluwanimi this is ready to be reviewed.  Thank you.

**Comment by divofred** [comment]
@TiaraOluwanimi, are you done reviewing?

**Comment by dessireugarte** [comment]
Hello @TiaraOluwanimi! This article update is ready to be reviewed, it is an update of a tutorial series. Please take into consideration that the URLs that are at the end of each article will change so we should change them accordingly to the new slug shown on the backend.

**Comment by TiaraOluwanimi** [comment]
@divofred 
I don't have access to the document(s). Could you please grant me access? makinde.mide@gmail.com

**Comment by divofred** [comment]
@TiaraOluwanimi, Done.

**Comment by divofred** [comment]
@TiaraOluwanimi I am done with the task.

**Comment by divofred** [comment]
Hello @PaulBratslavsky @dessireugarte @TiaraOluwanimi, What's the update on this article?

**Comment by dessireugarte** [comment]
Hello @divofred 👋 Sorry for the late reply. Currently, Olamide is reviewing the series of articles, and we expect to publish this between the last week of November and the first of December. I'll let you know when it is published. 
Thanks for your patience.

**Comment by dessireugarte** [comment]
Hello @divofred 👋 I would like to double-check that you run the code and made sure it is working. Olamide tried the tutorial, but it didn't work.

**Comment by divofred** [comment]
Yes @dessireugarte, I ran the code and it worked well. Please, what error did @TiaraOluwanimi get?

**Comment by divofred** [comment]
Hello @dessireugarte, I haven't gotten a response from you.

**Comment by PaulBratslavsky** [comment]
I am closing this issue since this is referencing  #723 as mentioned by [hubertnare](https://github.com/hubertnare)

**Comment by divofred** [comment]
@PaulBratslavsky @dessireugarte I have been waiting for a response, but haven't got any.

**Comment by divofred** [comment]
@dessireugarte @PaulBratslavsky Please, what is the update on this?

**Comment by PaulBratslavsky** [comment]
@divofred will look into sorry for the delay.

**Comment by PaulBratslavsky** [comment]
@dessireugarte this is finally ready to publish https://github.com/PaulBratslavsky/food-app-article-update/tree/main I finished final review and updates.  @divofred thank you for your patients this was a huge update.

**Comment by divofred** [comment]
Hello @dessireugarte, has a publication date been assigned for this update?

**Comment by PaulBratslavsky** [comment]
@divofred Strapi team had its onsite event last week.  I believe the content should be scheduled at some time this week.

**Comment by dessireugarte** [comment]
Hello @divofred!
We will publish it by the end of next week. I'll keep you updated.

**Comment by divofred** [comment]
Thanks for the update 🙂@PaulBratslavsky @dessireugarte

**Comment by dessireugarte** [comment]
Hello @divofred  👋 
The tutorial series is [updated](https://strapi.io/blog/nextjs-react-hooks-strapi-food-app-1)! 🎉
To ensure you don't miss any comments on your post, please register on our forum by clicking the discussion link at the bottom of your article. Please follow our [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice for your work. 

To receive payment for your work, you should submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) for $200 (more info [here](https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d)), and soon you will receive your payment.

If you would like to promote your article, we have some [templates](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) that can help you get started! Please feel free to reach out to us if you have any further questions.
