### ISSUE TITLE
[SUBMIT] Boosting productivity with Strapi plugins 

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#891]
**My resource**

Hello 👋 
I'll like to write on this topic here is my outline

 ### Boosting productivity with Strapi plugins

- Introduction 
- What is Strapi?
- What is Strapi plugins?
- Strapi installation 
- Plugins installation 
- x plugins for boosting productivity 
- Benefits of using plugins 
- Conclusion 

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@popoolatopzy which plugin were you thinking of demonstrating and talking about?

**Comment by PaulBratslavsky** [comment]
This will be awesome @popoolatopzy .  Keep it up.  Let me know when you have adraft.

**Comment by popoolatopzy** [comment]
Thank you @PaulBratslavsky I've started working on the draft

**Comment by popoolatopzy** [comment]
Hello @PaulBratslavsky here is the link to the artcle draft https://www.dropbox.com/scl/fi/ojpnbkdauqv1qxvsw6j6x/Boosting-Productivity-With-Strapi-Plugins.paper?dl=0&rlkey=ecytakw2s0f7jn3695vnsucxl

**Comment by PaulBratslavsky** [comment]
@TiaraOluwanimi  this article is ready for the review.

**Comment by dessireugarte** [comment]
Hello @popoolatopzy   👋
Just wanted to let you know that your article will be published around the third week of September. I'll let you know when it is published!

**Comment by popoolatopzy** [comment]
Thank you for the update ❤

**Comment by dessireugarte** [comment]
Hello @popoolatopzy  👋 
Your article is [live](https://strapi.io/blog/boosting-productivity-with-strapi-plugins)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Let me know if you have any questions.
