### ISSUE TITLE
[SUBMIT] How to Build a Notes App with Remix and Strapi CMS

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#892]
Please describe what your article will be about in few sentences and include an outline with the main topics covered in the article.

A brief outline:

- What is Strapi
- What is Remix
- Prerequisites
- Overview
- Build Strapi CMS Backend
- Setting up Strapi
   - Creating Notes collection with Strapi
   - Strapi API Access permissions
- Build Remix Backend
  - Setting up Remix application
  - Create Remix routes
  - Showing the Notes
  - Adding a Note
  - Deleting a Note
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by kimkimani** [comment]
Hey @PaulBratslavsky, What's your opinion on this subject?

**Comment by PaulBratslavsky** [comment]
@kimkimani I think you can work on this after you get done with the other article you are working on.

**Comment by kimkimani** [comment]
Hello @PaulBratslavsky, This one is ready.

https://www.dropbox.com/scl/fi/4g67383g3oxw0a57hik3t/How-to-Build-a-Notes-App-with-Remix-and-Strapi-CMS.paper?dl=0&rlkey=ovb8cx4631gtemdcmi7vz5h6y

**Comment by PaulBratslavsky** [comment]
This looks good.  Can you just do a brief  paragraph to summarize what you covered in the conclusion sections.  Thank you.

**Comment by kimkimani** [comment]
This looks good now @PaulBratslavsky

**Comment by PaulBratslavsky** [comment]
@TiaraOluwanimi this is ready for review.

**Comment by dessireugarte** [comment]
Hello @kimkimani  👋
Just wanted to let you know that your article will be published around the third week of September. I'll let you know when it is published!
