### ISSUE TITLE
[TOPIC] Tutorial on advanced customization for Strapi Policies

### ISSUE THREAD

**Issue by ElijahMansur** [strapi/community-content#893]
**My Request**

Hello 👋 

I would like to see an extension of the strapi policies documentation or a tutorial to show how to use policyContext and what things you can do with it. I would also like to see some examples of pulling in external libraries to do custom checks for policies

Thank you.

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by PaulBratslavsky** [comment]
Great topic. Would love to find an author for this.

**Comment by TheGhoulRe** [comment]
Hello @PaulBratslavsky, Can I have this topic?

Here's my outline:
1. Introduction
2. Prerequisites
3. Optional: Setting up a project
4. Overview of policies
5. Creating global policies
6. Creating API policies
7. Creating plugin policies
8. Overview of policyContext
9. Conclusion

**Comment by PaulBratslavsky** [comment]
@TheGhoulRe love the topic you may start. Thank you.

**Comment by PaulBratslavsky** [comment]
If you can, can you show how to return error messages when policy fails. If you have question about how to do this let me know.

**Comment by PaulBratslavsky** [comment]
@TheGhoulRe 
``` javascript
const utils = require('@strapi/utils');
const { PolicyError } = utils.errors;

module.exports = (policyContext, config, { strapi }) => {
  console.log(policyContext.request.body, 'policyContext');
  console.log("Is authenticated policy");

  if (policyContext.state.user) return true;
  throw new PolicyError('You are not allowed to perform this action', {
    policy: 'isAuthenticated',
  });;
};
```

Here is an example.  This is currently not documented in the docs. Try it out and let me know how it goes.

**Comment by TheGhoulRe** [comment]
Hi @PaulBratslavsky, it works. Thank you! 

I'm done with the draft. I also added the section on returning messages. Here's the draft paper: https://www.dropbox.com/scl/fi/g8vjca07449ml64n46dc3/Advanced-customisation-for-Strapi-policies.paper?dl=0&rlkey=g5su7104tbohk7jissu3dqtiq

**Comment by PaulBratslavsky** [comment]
@TheGhoulRe it looks good, but there were couple of images that were not showing up for me.  Let me know if that is happening for you, otherwise we can move this to review process by our reviewer.

**Comment by TheGhoulRe** [comment]
@PaulBratslavsky I don't have the same issue. All the images are showing up for me

**Comment by PaulBratslavsky** [comment]
@TheGhoulRe sorry for delayed response, we have a lot of articles in the cue and it has been taking time to review the topics.  I will review it as soon as I am able to get to it.

**Comment by TheGhoulRe** [comment]
Alright @PaulBratslavsky, thanks for the update!

**Comment by TheGhoulRe** [comment]
Hey @PaulBratslavsky, it's been a long while since I got an update on the topic

**Comment by PaulBratslavsky** [comment]
@TheGhoulRe I apologize for the delay. We currently have one person reviewing articles for WFC (me) and have a long backlog of articles.  I will look over yours this week.  Once again apologize for the delay.  Thank you for reaching out.

**Comment by PaulBratslavsky** [comment]
@GhoulKingR I apologize for the delay.  I know it has been a long time. I hope you are well.  I am finally catching up with the back log of article.  Our team has shrunk in size so it was taking me a while to get through all the items.  I would still like to publish your article.  Let me know if that is still ok with you. Thank you for understanding Paul.

**Comment by GhoulKingR** [comment]
Hi @PaulBratslavsky

No need to apologize; I completely understand that sometimes things can get busy and priorities shift. I appreciate your update and your dedication to catching up on the backlog of articles.

I'm still very much interested in having my article published, so please go ahead with it whenever you're ready.

**Comment by PaulBratslavsky** [comment]
@GhoulKingR we are ready to publish your article.

I did add some updates to improve the flow of the article and create a project example app to add as reference. 
[project](https://github.com/PaulBratslavsky/strapi-policy-examples)

updated article [here](https://github.com/PaulBratslavsky/strapi-policy-examples/blob/main/README.md)

I am in the process of scheduling the post.  Can you provide me with your updated bio.
- image
- full name
- bio

you can email me at paul.bratslavsky@strapi.io

**Comment by GhoulKingR** [comment]
Wow, that's awesome! I've sent my updated bio to your email.

Thank you for keeping me in the loop.

**Comment by PaulBratslavsky** [comment]
@GhoulKingR You are welcome. 🙂

**Comment by GhoulKingR** [comment]
Hey @PaulBratslavsky, would I still get paid for it?

**Comment by PaulBratslavsky** [comment]
@GhoulKingR yes, once it is published, will be scheduled for Tuesday next week. you will be able to submit your invoice.

**Comment by GhoulKingR** [comment]
Hi @PaulBratslavsky, is it okay to submit an invoice now?

**Comment by PaulBratslavsky** [comment]
@GhoulKingR yes.  Thank you.
