### ISSUE TITLE
[TOPIC] Strapi deployment on azure web app.

### ISSUE THREAD

**Issue by maks-bondarenko** [strapi/community-content#90]
I've been playing with a strapi for a few days and really find its great (especially after having a production level experience with sitefinity and orchard cms), but unfortunately I cannot take strapi further than a sandbox.
We use an azure as a hosting and official docu offers only deployment to VM (I believe same for AWS).
Which would be insane maintaining separate VM just for strapi where all infrastructure is hosted in a way of either simple web apps or functions.
The best I could find is "https://github.com/youkou2/Strapi-On-Azure-WebApp" but it did not work for me.
Would be nice to have official docu how to do it without Voodoo magic.
Thanks in advance.

**Comment by ahrherrera** [comment]
I am facing similar problems using Azure Web App

see here https://stackoverflow.com/questions/62355445/strapi-on-azure-does-not-run

**Comment by cwray-tech** [comment]
So, before I can say I could do this... Can you clarify what you mean by separate VM just for Strapi @maks-bondarenko? You will need a Node server for sure to run Strapi.

If you are okay with a separate instance being set up, then I could do a tutorial on how to set up Strapi on Azure App Service. You could also give input on what you are looking for @ahrherrera

**Comment by simonerlandsen** [comment]
@cwray-tech I am guessing that @maks-bondarenko is refering to this: https://strapi.io/documentation/v3.x/deployment/azure.html that says that "You will want to use an Azure Virtual Machine for Strapi deployments, the Azure web-app (IIS) deployments are not recommended".

I have strapi v3.0.0-beta.18.6 running in production on a linux web app in azure with a mysql service for db. I want to upgrade to v3.1.6 and have gotten it to work locally, but I am having trouble making it work on a test instance of a azure linux app service that also had v3.0.0-beta.18.6 running before. So I would also love a tutorial on how to set up Strapi on a Azure App Service :)

**Comment by cwray-tech** [comment]
@simonerlandsen cool! I hope I can pull this off. I am pretty new to Azure/Deployments, so I will be using Microsoft Docs heavily.😄

**Comment by simonerlandsen** [comment]
@cwray-tech I got it working today. I am no expert, but if you get stuck along the way, let me know.

What tripped me up was that the setting "host" in server.js used to work by setting it to the domain name of the webpage, but now does not, but setting it to 0.0.0.0 worked, but I can't find anything about this change in the Strapi migration guides or the general docs.

For anyone (maybe @maks-bondarenko and/or @ahrherrera) wondering about settings and database options when setting up Strapi 3.x (3.1.6 for me atm) on Azure, here is a setup with example values for a Azure App Service with Linux and a Azure Database for MySQL server, with env vars in comments:

`
// config/server.js

// getting values from env vars in Azure app configuration, and setting dev defaults
module.exports = ({ env }) => ({
  host: env("APP_HOST", "0.0.0.0"), // APP_HOST: 0.0.0.0
  port: env.int("PORT", 1337), // do not set PORT value in web app configuration, because it gets set by azure
  url: env("PROXY_URL", null), // PROXY_URL: https://my-app.azurewebsites.net:443
  admin: {
    auth: {
      secret: env("ADMIN_JWT_SECRET", <your jswt secret here>),
    },
  },
});
`

`
// config/database.js

// getting values from env vars, and setting dev defaults
module.exports = ({ env }) => ({
  defaultConnection: "default",
  connections: {
    default: {
      connector: "bookshelf",
      settings: {
        client: env("DATABASE_CLIENT", "mysql"), // DATABASE_CLIENT: mysql
        host: env("DATABASE_HOST", "127.0.0.1"), // DATABASE_HOST: my-database-name.mysql.database.azure.com
        port: env.int("DATABASE_PORT", 3306), // DATABASE_PORT: 3306
        database: env("DATABASE_NAME", "strapi"), // DATABASE_NAME: mydatabasename
        username: env("DATABASE_USERNAME", "strapi"), // DATABASE_USERNAME: mydatabaseusername
        password: env("DATABASE_PASSWORD", "strapi"), // DATABASE_PASSWORD: mydatabasepassword
        ssl: env.bool("DATABASE_SSL", true), // DATABASE_SSL: true
      },
      options: {
        debug: env.bool("DATABASE_DEBUG", true), // DATABASE_DEBUG: false
        ssl: env.bool("DATABASE_SSL", true),
        pool: {
          min: 0,
          max: 10,
          // need to adjust theese up from the defaults so app does not crash before azure has done it's work
          idleTimeoutMillis: 30000,
          createTimeoutMillis: 30000,
          acquireTimeoutMillis: 30000,
        },
      },
    },
  },
});

`

**Comment by Mcastres** [comment]
Hey @maks-bondarenko, we have an official doc for deploying to [Azure](https://strapi.io/documentation/developer-docs/latest/deployment/azure.html).

Feel free to reopen this if needed.

**Comment by frode** [comment]
> 
> 
> @cwray-tech I got it working today. I am no expert, but if you get stuck along the way, let me know.
> 
> What tripped me up was that the setting "host" in server.js used to work by setting it to the domain name of the webpage, but now does not, but setting it to 0.0.0.0 worked, but I can't find anything about this change in the Strapi migration guides or the general docs.
> 
> For anyone (maybe @maks-bondarenko and/or @ahrherrera) wondering about settings and database options when setting up Strapi 3.x (3.1.6 for me atm) on Azure, here is a setup with example values for a Azure App Service with Linux and a Azure Database for MySQL server, with env vars in comments:
> 
> ```js
> // config/server.js
> 
> // getting values from env vars in Azure app configuration, and setting dev defaults
> module.exports = ({ env }) => ({
>   host: env("APP_HOST", "0.0.0.0"), // APP_HOST: 0.0.0.0
>   port: env.int("PORT", 1337), // do not set PORT value in web app configuration, because it gets set by azure
>   url: env("PROXY_URL", null), // PROXY_URL: https://my-app-name.azurewebsites.net:443
>   admin: {
>     auth: {
>       secret: env("ADMIN_JWT_SECRET", <your jwt secret here>),
>     },
>   },
> });
> ```
> 
> ```js
> // config/database.js
> 
> // getting values from env vars, and setting dev defaults
> module.exports = ({ env }) => ({
>   defaultConnection: "default",
>   connections: {
>     default: {
>       connector: "bookshelf",
>       settings: {
>         client: env("DATABASE_CLIENT", "mysql"), // DATABASE_CLIENT: mysql
>         host: env("DATABASE_HOST", "127.0.0.1"), // DATABASE_HOST: my-database-host-name.mysql.database.azure.com
>         port: env.int("DATABASE_PORT", 3306), // DATABASE_PORT: 3306
>         database: env("DATABASE_NAME", "strapi"), // DATABASE_NAME: mydatabasename
>         username: env("DATABASE_USERNAME", "strapi"), // DATABASE_USERNAME: mydatabaseusername
>         password: env("DATABASE_PASSWORD", "strapi"), // DATABASE_PASSWORD: mydatabasepassword
>         ssl: env.bool("DATABASE_SSL", true), // DATABASE_SSL: true
>       },
>       options: {
>         debug: env.bool("DATABASE_DEBUG", true), // DATABASE_DEBUG: false
>         ssl: env.bool("DATABASE_SSL", true),
>         pool: {
>           min: 0,
>           max: 10,
>           // need to adjust theese up from the defaults so app does not crash before azure has done it's work
>           idleTimeoutMillis: 30000,
>           createTimeoutMillis: 30000,
>           acquireTimeoutMillis: 30000,
>         },
>       },
>     },
>   },
> });
> ```

@simonerlandsen Would you like to share more details of your setup? No other changes to the Azure App Service Linux service?

**Comment by simonerlandsen** [comment]
@frode actually, come to think of it, I am using a server.js file as starting point as apposed to something like `npm run strapi`

server.js
```javascript
"use strict";
const strapi = require("./node_modules/strapi/lib/index");
const strapiDev = require("./node_modules/strapi/lib/commands/develop");

if (process.env.DEV_MODE === true) {
  strapiDev();
} else {
  strapi().start();
}
```

It is there from a time where I wanted to make an earlier version of Strapi run on a windows azure web app and picked it up from here: https://github.com/youkou2/Strapi-On-Azure-WebApp

I would have thought that strapi v3 would run without it, but if you are having trouble with the normal setup that maybe it doesn't.
