### ISSUE TITLE
[SUBMIT] How To Build A Minimal Ecommerce Shopping App With NextJs And Strapi as Backend

### ISSUE THREAD

**Issue by Abdull600** [strapi/community-content#900]
**My resource**

**My content is**
Introduction
In this tutorial, I'll teach you how to build a minimal e-commerce shopping app with nextjs and strapi. 

Prerequisites 

1. HTML
2. JavaScript
3. Tailwind
4. React
5. NextJs

Setting up a Strapi project
In this section, I'll teach you how to set up strapi and add products to the strapi platform.

Setting up NextJs project
In this section, we'll set up our NextJs project; from creating components to creating our pages for routing, and using React context API to add products to our shopping cart.

Integrating Strapi API with NextJs
In this section, we'll see how we can fetch data from the products we created in strapi to our NextJs app and display the products in our storefront.

Conclusion
Wrap up the whole tutorial and try to explain what we might have achieved after the tutorial.

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript
- [ ] Ecommerce Shopping App, React Context API

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@Abdull600 can you provide an outline of what you would like to cover.  More particularly on  how would you structure the "products" data.  It would be really nice to see the use of dyanamic zones.

**Comment by Abdull600** [comment]
> use

Sure, I'll do that very soon.

**Comment by PaulBratslavsky** [comment]
@Abdull600 let me know how things are going?

**Comment by Abdull600** [comment]
Okay, am still writing but once am done, I'll propably start submit a well structured article.

**Comment by Abdull600** [comment]
https://www.dropbox.com/scl/fi/l7683039806fkz8va76od/How-to-build-a-minimal-ecommerce-shopping-app-with-nextjs-and-strapi-as-backend..papert?dl=0&rlkey=j7pdkdogvbc1kyoxgtfhrrxst

**Comment by Abdull600** [comment]
Hey @TiaraOluwanimi !

I have dropped the link to the draft. Mind reviewingmy article.

Regards

**Comment by PaulBratslavsky** [comment]
It's a good starting point, but I would recommend creating a more complex content structure, where you use strapi dynamic zones and components.  Maybe you have different types of products, each can be represented by a component in strapi, and you can choose the appropriate one in the dynamic zone. 

You can reference this article https://strapi.io/blog/creating-strapi-dynamic-zone-in-nuxtjs-app ( it's old ) but it will give you some idea.

Then on the front end, your app can display appropriate content based on the strapi component used.

**Comment by PaulBratslavsky** [comment]
I am going to be closing  this issue for the time being.  We can revisit this topic in the future.
