### ISSUE TITLE
[Request New Content] Migration from v3 to v4 from a simple Strapi application 

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#902]
**My resource**

https://www.youtube.com/watch?v=NSvdQKVvV9k 

**My content is**

- [ x ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

A tutorial explaining how to migrate a simple Strapi application from v3 to v4. For example, a blog page or static website. 

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
I am going to work on this article.
