### ISSUE TITLE
[Request New Content] Audit Log in Strapi v4

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#903]
**My Request** 
Context: 
Many users are concerned about being able to track usage logs in their project to know who performs which actions. It's a very frequent inquiry.

There are two methods to add audit logs to your project. You can follow this "[audit log guide](https://medium.com/@adenleabbey/audit-log-trail-with-strapi-74f6bdf70daf)" or this [video](https://medium.com/@adenleabbey/audit-log-trail-with-strapi-74f6bdf70daf) that leverages a simple " [middleware](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/middlewares.html) " concept to get this up and running. Or you can directly install this "[audit log community plugin](https://www.npmjs.com/package/strapi-plugin-audit-log)" developed by VirtusLab. This feature is also implemented in our [FoodAdvisor](https://github.com/strapi/foodadvisor/) demo if you'd like to test it before.

Request: 
Tutorial explaining audit log in Strapi v4 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by popoolatopzy** [comment]
Hello @dessireugarte I'd like to work on this article

**Comment by dessireugarte** [comment]
Hello @popoolatopzy 👋
Could you please send an outline of what you would be covering?

**Comment by popoolatopzy** [comment]
Hello @dessireugarte, Here is my outline for the article 

##### Introduction 
##### What is audit log in strapi?
##### Prerequisites 
##### Strapi installation 
##### Creating collections types
- Articles
- AuditLog
##### Overview of lifecycle in strapi 
##### Lifecycle configuration (Audit log)
-   afterCreate
-   afterUpdate
-   afterDelete
-   afterFindOne
-   afterFindMany
##### Testing the audit log 
##### Conclusion

**Comment by popoolatopzy** [comment]
Hi @dessireugarte, what is your view on the outline.

**Comment by dessireugarte** [comment]
Hey @popoolatopzy! Thanks for sharing the outline! 
@PaulBratslavsky  what do you think about this outline?

**Comment by PaulBratslavsky** [comment]
@dessireugarte I think this is a great article, a lot of people ask about some example of using Lifecycle methods. @popoolatopzy you can start on this.

**Comment by popoolatopzy** [comment]
Thank you @dessireugarte and @PaulBratslavsky  , I will start working on the draft now.

**Comment by popoolatopzy** [comment]
Hello @dessireugarte here is the draft for the article
https://www.dropbox.com/scl/fi/p7ygnpd68kh5ubpu9xstw/Audit-Log-in-Strapi-v4.paper?dl=0&rlkey=sxeodovezqneb573o0nlow210

**Comment by TiaraOluwanimi** [comment]
Hey, @popoolatopzy. Thanks. I'll be dropping comments on the doc.

**Comment by popoolatopzy** [comment]
Thanks @TiaraOluwanimi, I've attended to your comment

**Comment by popoolatopzy** [comment]
Thanks @TiaraOluwanimi , I've attended to your comment

**Comment by popoolatopzy** [comment]
Hello @dessireugarte 👋 
Any update on this article.

**Comment by dessireugarte** [comment]
Hello @popoolatopzy 👋 
Your article will be published next week. I'll let you know when it is published!
