### ISSUE TITLE
[Request New Content] Implementing A/B Testing in Next.js and Strapi

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#904]
**My Request**
Context: 
Many users are used to legacy CMS or SaaS that empowers them with AB testing functionality that allows the marketing team to measure and compare the efficiency of their company.

Regarding A/B Testing, there is a large spectrum of implementations based on each customer's needs and preferred method. You can leverage frontend capabilities like [A/B Testing React Components](https://github.com/pushtell/react-ab-test) or a SaaS tool like [Optimizely](https://www.optimizely.com/products/intelligence/full-stack-experimentation/).

Request: 
Tutorial implementing A/B Testing in Next.js and Strapi. It could be another technology instead of Next.js, that is mostly a recommendation. 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Umoren** [comment]
🚀 I can make the article.

**Comment by dessireugarte** [comment]
Hello @Umoren 👋
If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form? Then please scroll to the FAQ section and go over the article guidelines, how to submit an article, issue an invoice and get paid. 
Before getting started, can you provide an outline of what you were thinking of covering?

**Comment by Umoren** [comment]
Hi @dessireugarte 
This isn't my first article.
This is my outline proposal for the article:

- Introduction
    - What is AB Testing
    - Why is it important
    - How it works
 - Implementing AB testing in Nextjs
    - Creating landing pages with Strapi
    - Implementing the AB Test logic with `Middleware`
- Conclusion

**Comment by Umoren** [comment]
Hi @dessireugarte 
Do you approve this outline?

**Comment by dessireugarte** [comment]
Hello @Umoren 👋
I shared this outline with the team and the feedback I received is that it would be good to explore integrations like [Conscia.ai](https://conscia.ai/) or  [Uniform.dev](https://uniform.dev/). 
Also, in the introduction, could you expand on A/B testing specifically with headless vs monolithic CMSs. 

What do you think?

**Comment by Umoren** [comment]
Hi @dessireugarte 
This is the revised outline for the artilce

- Introduction
  - What is AB Testing
  - Why is it important
  - How it works
  - AB Testing with monolithic CMSs vs headless CMS

- Introducing Uniform.dev
   - What it is
   - How it works
- Implementing AB testing with Uniform.dev using Nextjs
   - Setting up the project
   - Integrating Uniform.dev
   - Running tests

- Conclusion

**Comment by dessireugarte** [comment]
Hello @Umoren 👋
Thanks for the outline. You can start writing your draft. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x).

**Comment by Umoren** [comment]
Alright I'll update the outline and share it with you.

**Comment by dessireugarte** [comment]
Hello @Umoren 👋 
Any news about this article?

**Comment by dessireugarte** [comment]
Hello @Umoren! We didn't have any answer from you, so we will make this topic available again. Would that be ok for you?

**Comment by Umoren** [comment]
Hi @dessireugarte 
I'm sorry i've been inactive for a while
Can I get an extension till Friday to deliver the draft?

**Comment by dessireugarte** [comment]
Sure, thanks @Umoren 👍

**Comment by dessireugarte** [comment]
Hello @Umoren 👋 
Do you have any news about this article?
