### ISSUE TITLE
[Request New Content] Create a refresh token feature in your Strapi application 

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#906]
**My Request**
Tutorial explaining how to Create a refresh token feature in your Strapi v4 application 

Examples: 
- https://github.com/olyphotographer/strapi-refresh-tokens 
- https://medium.com/geekculture/adding-refresh-token-to-strapi-v-3-2b75c01bd704

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Marienoir** [comment]
Hello @dessireugarte 
I will like to work on this article

**Comment by dessireugarte** [comment]
Hello @Marienoir 👋
Could you please share an outline of the topics you will be covering?

**Comment by Marienoir** [comment]
Hi @dessireugarte  
This is my proposed outline for the article

# Title:  Create a refresh token feature in your Strapi application

## Outline

- ### Introduction

1. Brief introduction to Strapi.

2. Why authenticate your Strapi application?

- ### Prerequisites

1. Strapi v4 (latest version)

1. npm (minimum v6) or yarn 

- ### Goals

1. Installing Strapi and creating a Strapi project.
3. Showcasing how to add a user in the collection types and assign roles and permission.
4. Testing an authenticated user in an API client.
5. Explanation of the response gotten from the client and what JWT means
6. Why do we need to implement a refresh token for our authenticated user?
7. Introduction to the Refresh token feature.
8. Configure the Auth and config folder in the Strapi directory.
9. Creating a revoke handler and using this function across the necessary files.
10. Verifying that the refresh token feature has been implemented.
- ### Frontend Implementation 
1. A mini-app that has 2 screens i.e the login and dashboard pages that showcases how an authenticated user can have access to the dashboard and when the token expires, the user will be denied access to log in.
2. We would create a refresh token for this user and the user will then be allowed access to the mini-app.

### Conclusion

My content is

- [x]  A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**Comment by dessireugarte** [comment]
Thanks @Marienoir! Please go ahead and let us know when you have a draft to review 😊

**Comment by Marienoir** [comment]
Alright
I would get started and would let you know when I have a draft to review.

**Comment by PaulBratslavsky** [comment]
@Marienoir just wanted to check in how is your progress going.

**Comment by Marienoir** [comment]
@PaulBratslavsky 
The progress is going well. I would try to submit a draft as soon as possible
Thanks

**Comment by Marienoir** [comment]
Hello @PaulBratslavsky 
This is a draft of the article
 https://www.dropbox.com/scl/fi/mwqyy43gp76ofw139dtha/Create-a-refresh-token-feature-in-your-Strapi-application.paper?dl=0&rlkey=pu45uaywbocmdnbwdk011j36q

**Comment by dessireugarte** [comment]
Thanks @Marienoir 👋
I include @TiaraOluwanimi in the conversation to review the article. We will let you know when we have an estimated date to publish it.

**Comment by dessireugarte** [comment]
Hello @Marienoir  👋 How are you? 
I just wanted to let you know that your article will be published around the third week of September. I'll let you know when it is published!

**Comment by Marienoir** [comment]
Hello @dessireugarte 
Thanks for the update 😊

**Comment by dessireugarte** [comment]
Hello @Marienoir  👋 
Your article is [live](https://strapi.io/blog/how-to-create-a-refresh-token-feature-in-your-strapi-application)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post so you automatically receive notifications when someone adds comments. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by Marienoir** [comment]
Hello @dessireugarte 
Thanks for publishing this. I have a few concerns though. Some sections of the blog are not properly formatted. Some texts are being formatted with the codes
An example is this. You might want to check again. Thanks
![Capture](https://user-images.githubusercontent.com/40265625/195562572-2979443e-46ae-4dfc-ab2c-d570acfedc8b.PNG)

**Comment by dessireugarte** [comment]
Hello @Marienoir 👋
You are right, thanks for letting us know. 
The change is done 👍
