### ISSUE TITLE
[SUBMIT] Micro Frontend using Module Federation

### ISSUE THREAD

**Issue by oyedeletemitope** [strapi/community-content#908]
**My resource**

Hello 👋 

Micro frontend is a concept from microservice. They are a popular approach to increasing flexibility. It allows teams to combine components built in different frameworks or libraries.

In this tutorial, we are taking a look at the cross platforming nature of the micro frontend. We’ll do this by building an app with a particular frontend framework and also share its state to another framework entirely. 

## What will we be building?

A task tracker app with react and Strapi and also share its state in solid js. I chose solid js because of its similarities with react and also solid js has also been tipped to be the next react in the tech industry so it’ll be nice to see how we can share states btw them. 

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@oyedeletemitope can you provide an outline of the structure of the post and what you would like to cover.  I think this is an interesting idea, and would like to learn more.

**Comment by oyedeletemitope** [comment]
Hello @PaulBratslavsky here's the outline:

- Introduction
- what is microfrontend?
- Benefits of microfrontend
- Brief look at the tools and dependencies that we'll be using(module federation, strapi)
- Building the project(A task tracker app with react and strapi)
- sharing the state with solid js
- conclusion

This tutorial may be in two-part for me to cover every detail needed although, I don't know yet.

**Comment by PaulBratslavsky** [comment]
@oyedeletemitope you can get started on this.🙂

**Comment by oyedeletemitope** [comment]
Thank you @PaulBratslavsky. I’ll share a draft once I’m done.

**Comment by oyedeletemitope** [comment]
Hello @PaulBratslavsky @TiaraOluwanimi I made a few tweaks to this tutorial. Here are the links to the drafts:

https://www.dropbox.com/scl/fi/doui9rtfl8z784m1h2bp1/Micro-Frontend-using-Module-Federation-part1.paper?dl=0&rlkey=aglh5lly0qr8sbexl3m49s4g6

https://www.dropbox.com/scl/fi/s1d0ecvz2d3wk2mh93n2p/Micro-Frontend-using-Module-Federation.paper?dl=0&rlkey=k936uo6qposo0ee1691u9nq8i

**Comment by TiaraOluwanimi** [comment]
@PaulBratslavsky, could you pls approve the tweaks and confirm if it's ready for review?

**Comment by oyedeletemitope** [comment]
@dessireugarte any update on this?

**Comment by dessireugarte** [comment]
Hello @oyedeletemitope 👋
Sorry for the delay, we will review the article, and I scheduled to post it by the end of December. But it will depend if there are changes needed or not. We will let you know, and thanks for your patience.

**Comment by dessireugarte** [comment]
Hello @oyedeletemitope 👋 Is there a reason why you did a two-part tutorial? I think they should be merged them.

**Comment by oyedeletemitope** [comment]
The first part explains the concept of microfrontend and it’s benefits why the second shows the practical aspect. If you think they should be merged then no problem. Is there anything you want me to do on my end?

**Comment by dessireugarte** [comment]
Yes, I think the article will be better as one single article! Could you please merge them @oyedeletemitope ? :)

**Comment by oyedeletemitope** [comment]
Done, here's a link to the merged article

**Comment by PaulBratslavsky** [comment]
> 

Not sure if there is supposed to be a new link here.

> Done, here's a link to the merged article

**Comment by oyedeletemitope** [comment]
My apologies. here's the link to the article :

https://www.dropbox.com/scl/fi/doui9rtfl8z784m1h2bp1/Micro-Frontend-using-Module-Federation-part1.paper?dl=0&rlkey=aglh5lly0qr8sbexl3m49s4g6

**Comment by oyedeletemitope** [comment]
@dessireugarte any update on this draft?

**Comment by PaulBratslavsky** [comment]
@dessireugarte this article is ready to publish.

**Comment by dessireugarte** [comment]
Hello @oyedeletemitope  👋 
Your article is [live](https://strapi.io/blog/a-quick-introduction-to-micro-frontend-using-module-federation)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also, please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) for $150, and soon you will receive your payment.
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by dessireugarte** [comment]
Hello @oyedeletemitope! Could you please update the invoice you sent with the correct dates?

**Comment by oyedeletemitope** [comment]
Hello @dessireugarte apologies for that, I’ve updated the dates and resubmitted the form

**Comment by dessireugarte** [comment]
Thank you @oyedeletemitope! I submitted your invoice. The bank account is a new one right?

**Comment by oyedeletemitope** [comment]
No, a colleague of mine once used my other account for payment on strapi. I don’t know if I would be allowed to submit that one too. Can I?

**Comment by dessireugarte** [comment]
@oyedeletemitope ok no problem!
Quick question, did you use [this](https://www.youtube.com/watch?v=lKKsjpH09dU) video tutorial as a resource to build this tutorial?

**Comment by oyedeletemitope** [comment]
@dessireugarte no, I used another resource, did my research and also I had once written on microfrontend before https://www.section.io/engineering-education/microfrontend-using-module-federation-in-solid-js/
