### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Implementing Previews with Nuxt Applications using a Strapi backend

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#909]
**Description**
Update this article https://strapi.io/blog/implementing-previews-with-nuxt-applications-using-a-strapi-backend 

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Marktawa** [comment]
Hey 👋 @dessireugarte 

As previously mentioned in issue #815, I am interested in updating this article.

**Comment by dessireugarte** [comment]
Great! Yes, please go ahead! Let me know when you have the draft ready 👍

**Comment by Marktawa** [comment]
Hey 👋 @dessireugarte 

Here's the [draft](https://www.dropbox.com/scl/fi/mvw1l2eaguo32d5tja0bm/Implementing-Previews-with-Nuxt-Applications-using-a-Strapi-backend.paper?dl=0&rlkey=13lon0ww3ibf949sscmg3uaut) and the [repo](https://www.github.com/Marktawa/strapi-nuxt-preview).

**Comment by dessireugarte** [comment]
Thanks @Marktawa!
I assigned @TiaraOluwanimi so the article is reviewed. We will contact you if we need any changes.

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋
This article as well is already scheduled to be published around the first week of September. I'll let you know as well!

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋 
Your article is [live](https://strapi.io/blog/implementing-previews-with-nuxt-applications-using-a-strapi-backend-1)! 🎉
Please feel free to submit your invoice and let me know if you have any questions!

**Comment by Marktawa** [comment]
Hi 👋 @dessireugarte

I submitted the invoice for this article on September 7th, but I have not yet received the payment. May you kindly look into this matter?

Thank you in advance.

**Comment by Marktawa** [comment]
Hey 👋  @dessireugarte 

Thank you I have received the payment. You can ignore my previous message.
