### ISSUE TITLE
[SUBMIT] Strapi: Como crear ENDPOINTS personalizados

### ISSUE THREAD

**Issue by xAgustin93** [strapi/community-content#91]
**My resource**
Crea endpoint personalizado
https://youtu.be/AipINo-Xvn4

**My format**
- [ ] Article
- [x] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Great video @xAgustin93!
Thanks for this contribution :)
