### ISSUE TITLE
[UPDATE OUTDATED CONTENT] Implementing Previews with Next Applications using a Strapi backend

### ISSUE THREAD

**Issue by Marktawa** [strapi/community-content#915]
**My update**

Hello 👋 

I want to update this article -> [Implementing Previews with Next Applications using a Strapi backend](https://strapi.io/blog/implement-previews-with-next-applications-using-a-strapi-backend)

I want to make it compatible with Strapi version 4.

**Link to the content** -> [Implementing Previews with Next Applications using a Strapi backend](https://strapi.io/blog/implement-previews-with-next-applications-using-a-strapi-backend)

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by Marktawa** [comment]
I want to update it.

**Comment by Marktawa** [comment]
Hi @dessireugarte 

Here's the [complete draft](https://www.dropbox.com/scl/fi/u41pj3sy1nnq4bw5sixl1/Implementing-Previews-with-Next-Applications-using-a-Strapi-backend.paper?dl=0&rlkey=m7gyh4t33wol0sftvthe7xhe0) and the [GitHub repo](https://github.com/syboxdigital/strapi-nextjs-preview-blog)

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋 
Thanks for the draft. I assigned the issue to @TiaraOluwanimi, so the article is reviewed.

**Comment by dessireugarte** [comment]
Also, this article will be published around the third week of September. I'll let keep you updated!

**Comment by Marktawa** [comment]
Noted.

**Comment by dessireugarte** [comment]
Hello @Marktawa  👋 
Your article is [live](https://strapi.io/blog/implementing-previews-with-next-applications-using-a-strapi-backend)! 🎉
Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform)!
Let me know if you have any questions!

**Comment by Marktawa** [comment]
Hi 👋 @dessireugarte

I submitted the invoice for this article on September 19th, but I have not yet received the payment. May you kindly look into this matter?

Thank you in advance.

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋 
Your invoice has been submitted. There has been a small delay in the payments, but you should receive the payment soon 🙏

**Comment by Marktawa** [comment]
Hey 👋 @dessireugarte 

I am happy to say I have received the payment.

Please check #953 and #985. I have submitted the complete drafts.
