### ISSUE TITLE
[Request New Content] Build a Web 3.0 Book Library DApp with Solidity, React and  Strapi

### ISSUE THREAD

**Issue by sparkle666** [strapi/community-content#916]
I would love to write on this article.
@PaulBratslavsky

**Comment by PaulBratslavsky** [comment]
@sparkle666 that is great.  I think this will be a cool article. Can you provide a brief outline before starting.

**Comment by sparkle666** [comment]
@PaulBratslavsky 
Below is the outline

1. Introduction  and prerequisites
2. Setting up Hardhat
3. Writing the contract
4. Testing the contract
5. Deploying contract to Alchemy
6. Setting up the front-end
7. Installing and setting up Strapi
8. Layering out the UI
9. Hooking up the contract
10. Conclusion

**Comment by PaulBratslavsky** [comment]
@sparkle666 you can start on this, let me know when you do, and I will change status to `in progress`

**Comment by sparkle666** [comment]
Yeah, I have started with it. @PaulBratslavsky

**Comment by dessireugarte** [comment]
Hello @sparkle666 👋
I just want to confirm you are still working on this article
