### ISSUE TITLE
[Request New Content] Deploy Strapi v4 in AWS

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#918]
**My Request**

A step-by-step tutorial explaining how to deploy Strapi v4 in AWS with a configuration script that setups the infrastructure and application for production (with load balancing).

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ibn-ashimi** [comment]
My resource
Hello 👋 @dessireugarte 

In this article, we will be covering how to deploy Strapi v4 in AWS with a configuration script that setups the infrastructure and application for production (with load balancing).

Title: Deploy Strapi v4 on AWS with automation script for production
Outline

Introduction
Prerequisites
Setup Strapi locally
Setting up environment
Application Configuration
Deployment
Putting it all together
Conclusion
My content is

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

What do you all think?
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
This is similar to what @omarkhairy21 is working on already.
