### ISSUE TITLE
[TOPIC] User registration API mobile and email verification on React

### ISSUE THREAD

**Issue by thesanjivkumar** [strapi/community-content#92]

**Comment by adriatic** [comment]
**[Same comment](https://github.com/strapi/community-content/issues/71#issuecomment-638493345)** as many other topics in this collection of issues

**Comment by malgamves** [comment]
hey @thesanjivkumar could you give us a little more context on what you would like this tutorial to be like? What problem would you like it to solve?

**Comment by Mcastres** [comment]
Closing this as we don't have much details about it :)
