### ISSUE TITLE
[SUBMIT] How to Create an online course certificate verification using Typescript Next JS and Strapi

### ISSUE THREAD

**Issue by zelief** [strapi/community-content#922]
**My content is**

- [ ] A Strapi Tutorial with NextJS typescript
- [ ] Create an online course certificate page using jsPDF
- [ ] Generating a pdf using data from Strapi and jsPDF

**Outline**
- Introduction
- Creating a NextJS app with Typescript
- Creating the Certificate Page in NextJS
- Generating a PDF using jsPDF with static data
- Creating a local Strapi app
- Create a Certificate Collection Type
- Input several data
- Use data from Strapi on our certificate page with dynamic routes
- Import the certificate data (if possible, haven't tried it)
- Conclusion

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment]
@zelief I like this idea, you can get started with this when you are ready. Thank you.
