### ISSUE TITLE
[SUBMIT]

### ISSUE THREAD

**Issue by Ksound22** [strapi/community-content#924]
**My resource**

# Article Proposal

## Title
How to Make a REST API With Strapi and Deploy It 

## Description
An article that describes in detail how to make an API with Strapi and deploy it to Heroku. 

Its an API containing African countries, their populations, capital cities, and currencies. 

The article will also show how to consume the API in a React app.

## Outline
- Introduction
- Goals of this Article
- Prerequisites - Basic Skills and What you need to Have in Place
- What is Strapi?
- How Can I Get Started with Strapi?
- How to Build the API
  - How to Create the Collection for the API
  - How to Add Fields to the Collection
  - How to Add the Content with the Strapi GUI
  - How to Add the Content with Postman
- How to Deploy the API to Heroku
- How to Consume the API in a React App
- Final Thoughts

**Comment by PaulBratslavsky** [comment]
@Ksound22  We already have some articles very similar to this. Are there are other topics that you were thinking of doing.

**Comment by PaulBratslavsky** [comment]
Another idea, you can write similar topic, just using React and Typescript, and chat about benefits of using Typescript on the front end.

**Comment by Ksound22** [comment]
I have another idea. And I'm sure it has not being done.

Let me send it's outline. And then we'll come back to this.

**Comment by Ksound22** [comment]
I'm going to close this and create another one.

**Comment by Ksound22** [comment]
Thank you.
