### ISSUE TITLE
How to Host Strapi with Zero Downtime Deploys

### ISSUE THREAD

**Issue by digitaldesigndj** [strapi/community-content#927]
How to host Strapi on ubuntu behind nginx as a proxy, with certbot for https. We deploy a test server and a flip flop strategy to enable zero downtime deployments.

Why? our eCommerce web-hook can fire at any time, and Strapi has to be ready for it.

* Hosting behind nginx is good, your node processes don't run as root. It also enables zero downtime deployments.
* We need a test instance, but it can use the same database as production. (this might be a bad assumption?)
* Assumes Ubuntu current LTS server
* Needs 2 domains, `api.example.com` &  `api.test.example.com`
* Basic `nvm` Setup
* Create 2 instances of your project with git clone `api.1337.example.com` and `api.1338.example.com`
* Don't forget `.env` secrets
* Basic Nginx install and config
* Basic Certbot how-to
* Basic PM2 setup
* How to start everything up 

How to deploy code from test to production

1. Get your deployment code onto the test server (api.test.example.com) and make sure it works.
2. Are you ready? Are you sure?
3. Stop the test server `pm2 stop api.1338.example.com`
4. Make sure that wasnt production and then delete the test server `pm2 delete api.1338.example.com`
5. Modify the test server instance (example 1338) .env file and change the URL var: `URL=api.example.com`
6. Build the test server instance (example 1338) with the new url `npm run build`
7. Start the test instance `pm2 start "npm start" --name api.1338.example.com` 
8. go to `/etc/nginx/sites-enabled` and modify `api.example.com` and `test.example.com`. Swap port `1337` for `1338` in each file.
9. test your nginx config changes `sudo nginx -t`
10. deploy your changes (This makes the your new code live) `sudo nginx -s reload` port 1337 and 1338 should have swapped places.
11. change the note about which server is production `mv 1337_is_production 1338_is_production`
11. time to fix the test server, that used to be production, go to `/var/www/api.1337.example.com`
12. Stop it with pm2 `pm2 stop api.1337.example.com`
13. Make sure that wasn't production and then delete the server `pm2 delete api.1337.example.com`
14. `git pull` the latest changes then `npm install`
15. on the 1337 instance open the `.env` file and change the URL var: `URL=api.test.example.com`
16. build 1337 with `npm run build`
17. Start with `pm2 run "npm run develop" --name api.1337.example.com`
18. Your test server and production server should both have the latest code.

Conclusion
You can update code without downtime, and restart the test server any time you wish.
Code will be a little bit of `nginx.conf` basic but functioning, and lots of shell commands.

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@digitaldesigndj this would be a cool article based on the steps that you mentions above. You can get started with it when you are ready.

**Comment by PaulBratslavsky** [comment]
@digitaldesigndj just let me know when you stat so I can change it to `in progress`

**Comment by digitaldesigndj** [comment]
Go ahead and do that. It won't be done until this weekend at best, but I have started. Thanks!

**Comment by dessireugarte** [comment]
Hello @digitaldesigndj 👋
I'd just like to confirm you are working on this article

**Comment by digitaldesigndj** [comment]
Yes, still a work in progress

**Comment by dessireugarte** [comment]
Hello @digitaldesigndj!
Just wanted to check how are you doing with this draft.

**Comment by dessireugarte** [comment]
Hello @digitaldesigndj !
I am closing this issue since we didn't receive any news about it.
