### ISSUE TITLE
Strapi Comments Plugin

### ISSUE THREAD

**Issue by Carl1990uk** [strapi/community-content#931]
**My Request**

Hello 👋 
Is there any tutorial on implementing the strapi-plugin-comments ?
I have read the docs and it's not making much sense (I am new to Strapi)

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by PaulBratslavsky** [comment]
@Carl1990uk this is a great suggestion.  Hope some one will pick this up, I also been meaning to checkout the plugin if I get to it before someone picks this up, I can write a quick block post.

**Comment by dillionmegida** [comment]
Hi @dessireugarte can I pick this up?

**Comment by Saintdavidking** [comment]
Hello, @malgamves is this topic still available?

**Comment by malgamves** [comment]
thanks for the interest @dillionmegida and @Saintdavidking - I would like @Carl1990uk to elaborate on what they are looking for. We have two comments plugins on the [Strapi marketplace](https://market.strapi.io/). Would you like to know how to build them or use them?

**Comment by ibn-ashimi** [comment]
The https://market.strapi.io/plugins/strapi-plugin-comments in his message matches the slug of this plugin ([https://market.strapi.io/plugins/strapi-plugin-comments](https://market.strapi.io/plugins/strapi-plugin-comments)) @malgamves @PaulBratslavsky.

I will like to work on an article explaining how to set it up. The guide doesn't seem to be very clear to a regular user.

**Comment by malgamves** [comment]
Hey @ibn-ashimi thanks! The scope of what you're suggesting doesn't really match what we're looking for at the moment so I'll have to pass and suggest proposing that in the near future or proposing a more advanced and in-depth article on how Strapi plugins and how they operate.

**Comment by PaulBratslavsky** [comment]
Based on @malgamves feedback I will close this issue.
