### ISSUE TITLE
[Request New Content] TypeScript vs JavaScript with Strapi

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#935]
**My Request**

An article describing what is JavaScript, what is TypeScript, benefits and cons of using each with Strapi.  

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Ubaydah** [comment]
I will like to take this topic

**Comment by Ubaydah** [comment]
My Outline:

- Introduction
- What is Strapi 
-  What is Javascript
- What is typescript
- Benefits of using Strapi with Javascript 
- Benefits of using Strapi with typescript
- Conclusion 

let me know what you think  @PaulBratslavsky

**Comment by dessireugarte** [comment]
I would suggest these changes: 

- Introduction
- What is JavaScript?
- What is TypeScript?
- TypeScript vs JavaScript: Main differences 
- What is Strapi?
- Pros and cons of using Strapi with JavaScript
- Pros and cons of using Strapi with TypeScript
- Conclusion

What do you think @PaulBratslavsky ?

**Comment by Ubaydah** [comment]
This is great @dessireugarte, I will love to work on it.

**Comment by dessireugarte** [comment]
Hello @Ubaydah 👋
You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x).

Once your article is ready, please share the dropbox link to your article in a comment on this GitHub issue 👍

**Comment by Ubaydah** [comment]
> Hello, @Ubaydah sorry to bother you just want to know if you are still working on this topic?

Yes, I am.

**Comment by TiaraOluwanimi** [comment]
Hi, @Ubaydah. How's it going? How's the piece coming along?

**Comment by Ubaydah** [comment]
> Hi, @Ubaydah. How's it going? How's the piece coming along?

going okay, will turn the first draft in soon

**Comment by Ubaydah** [comment]
Hi @TiaraOluwanimi @dessireugarte 

This is the link to my article draft, looking forward to your feedback.

https://www.dropbox.com/scl/fi/x46vertgf0u5nneqf7vlm/TypeScript-vs-JavaScript-with-Strapi.paper?dl=0&rlkey=9ldl4m7j1lx548ocb350t79wn

**Comment by Ubaydah** [comment]
Hi @TiaraOluwanimi @dessireugarte, This is the link to the draft of my article. https://www.dropbox.com/scl/fi/x46vertgf0u5nneqf7vlm/TypeScript-vs-JavaScript-with-Strapi.paper?dl=0&rlkey=six10iny32ngqer4x3y6xpqvj.

I look forward to your feedback.

**Comment by dessireugarte** [comment]
Hello @Ubaydah 👋 I left some comments. Now @TiaraOluwanimi will review it and then we can give you a publication.

**Comment by Ubaydah** [comment]
> Hello @Ubaydah 👋 I left some comments. Now @TiaraOluwanimi will review it and then we can give you a publication.
Thanks for the feedback @dessireugarte , I have implemented the changes.

Looking forward to your review @TiaraOluwanimi

**Comment by Ubaydah** [comment]
Thanks for the review @TiaraOluwanimi

**Comment by Ubaydah** [comment]
@dessireugarte when is it going to be published?

**Comment by dessireugarte** [comment]
Hello @Ubaydah 👋
We will publish your article on Monday. I'll get back to you that day.

**Comment by dessireugarte** [comment]
Hello @Ubaydah  👋 
Your article is [live](https://strapi.io/blog/typescript-vs-javascript-which-one-should-you-use-with-strapi)! 🎉 I changed the title to make it more SEO friendly. Also, I'm fixing the issue with the numbered lists, since they shouldn't be listed like that. 
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!
