### ISSUE TITLE
[Request New Content] What is TypeScript? 

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#936]
**My Request**

An article describing what TypeScript is, why you should use it, and how to get started with Strapi using TypeScript. Add any other relevant information in the outline. 
Here is an article as inspiration diving into ["What is the Jamstack](https://strapi.io/blog/what-is-the-jamstack)?

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by TechMakanaki** [comment]
I will love to write about this topic.

**Comment by dessireugarte** [comment]
Hello @TechMakanaki 👋
If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form? Then please scroll to the FAQ section and go over the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md), how to submit an article, issue an invoice and get paid.
Before getting started, can you provide an outline of what you were thinking of covering?

**Comment by TechMakanaki** [comment]
Hi @dessireugarte here is the outline for the project

Outline
Introduction
Overview of Typescript
Features
Compatibilities
Plugins
Why using TypeScript
What is Strapi?
Prerequisites
Strapi (typescript) Installation
Conclusion

**Comment by dessireugarte** [comment]
Hello @TechMakanaki 👋
Looks good to me. 
Could you confirm that this outline is good to get started @PaulBratslavsky ?

**Comment by TechMakanaki** [comment]
@dessireugarte okay thank you. Can I start?

**Comment by dessireugarte** [comment]
Hello @TechMakanaki 👋
Yes, you can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x).

Once your article is ready, please share the dropbox link to your article in a comment on this GitHub issue, so @TiaraOluwanimi can review it.

**Comment by Saintdavidking** [comment]
Hello, @TechMakanaki  sorry to bother you just want to know if you are still working on this topic?

**Comment by TechMakanaki** [comment]
@Saintdavidking I'm still working on it presently and I will be done with it soon. 
Thanks.

**Comment by TechMakanaki** [comment]
Good morning, @dessireugarte.
I am done with the draft, here is the link to the dropbox paper below;

https://www.dropbox.com/scl/fi/6v3qye5parko7u2e5t2pj/Untitled.paper?dl=0&rlkey=zzuoxyedn8zitda34gmfm6yqf

**Comment by dessireugarte** [comment]
I left some comments @TechMakanaki

**Comment by TechMakanaki** [comment]
Thank you i will do the needful

**Comment by TechMakanaki** [comment]
Hello, @dessireugarte I have re-paraphrased all the sentences you commented on.
Kindly cross-check and get back to me.
Thanks.

**Comment by dessireugarte** [comment]
Hello @TiaraOluwanimi 
I think this article is ready, could you please take one last look and if it is ready, upload it to the backend?

**Comment by TiaraOluwanimi** [comment]
Done @dessireugarte

**Comment by dessireugarte** [comment]
Hello @TechMakanaki 👋 
Your article is [live](https://strapi.io/blog/what-is-typescript)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. Now you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by TechMakanaki** [comment]
@dessireugarte good day, please there is an error in the article publication. Can you please reply so we can rectify it. Thank you

**Comment by dessireugarte** [comment]
Hello @TechMakanaki 👋
Sorry about that. We already made the changes 👍

**Comment by TechMakanaki** [comment]
Hello, @dessireugarte 
I have not received the payment for the article yet.
Please kindly consider my request.
Thanks 👍

**Comment by TechMakanaki** [comment]
Hello @dessireugarte
