### ISSUE TITLE
How to build a job board with Tailwind CSS, Next.js and Strapi

### ISSUE THREAD

**Issue by TreciaKS** [strapi/community-content#938]
**A beginner’s guide on how to build a job board with Tailwind CSS, Next.js and Strapi**

Outline
- Introduction
- A brief introduction to Next.js and Strapi
- Setting up Strapi
- Build the architecture of your content
- Creating your content with Strapi’s content manager
- Setting up your front end
- Connecting the backend to the frontend
- "Dynamic API routes”
- Conclusion

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by ChisomUma** [comment]
Hi, I would love to write on this topic. Looking forward to your response.

**Comment by ChisomUma** [comment]
I have already applied through the Strapi authorship form.

**Comment by TreciaKS** [comment]
Hey, Thanks. Unfortunately, I've already written this on this topic.

**Comment by TreciaKS** [comment]
Hey @dessireugarte. Here is the draft for the article:
https://www.dropbox.com/scl/fi/y31koxxbcjmv19t3euh1q/How-To-Build-A-Job-Board-With-Next.js%2C-Tailwind-CSS-and-Strapi.paper?dl=0&rlkey=jcny2xmi7zjy4mnkef8slmddz

**Comment by dessireugarte** [comment]
Thank you @TreciaKS!
@TiaraOluwanimi will review your article and we will post it next week 😊

**Comment by dessireugarte** [comment]
Your article is [live](https://strapi.io/blog/how-to-build-a-job-board-with-next-js-tailwind-css-and-strapi) @TreciaKS 🎉🙌
