### ISSUE TITLE
[Request New Content] Deploying and scaling Strapi on a Kubernetes Cluster

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#939]
**My Request**

Deploying and Scaling Strapi on a Kubernetes cluster diving into general guidance, best practices and patterns for a safe & easy deployment.

This topic is available again. We released this week the docs [Running Strapi in a Docker container](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/docker.html#development-and-or-staging-environments) that could facilitate writing this article. 

The main pain points identified:

Strapi's docker support
Horizontal scaling concerns (not just k8s)
Statelessness capability (just file uploads and the fact you can't use the content-type builder)
Any feature restrictions (it's just pretty much cron jobs, file uploads, content-type builder)

The author that decides to write this article will have guidance from someone in the Strapi team. 

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by FaithKovi** [comment]
Hello @dessireugarte 
I am interested in writing this article.

**Comment by dessireugarte** [comment]
Hello @FaithKovi 👋
Great, could you please provide an outline?

**Comment by FaithKovi** [comment]
Hello @dessireugarte. Here is an outline for the article

- Introduction
- What is Strapi - A Headless CMS?
- Scaffolding a Strapi project
- Platform for deployment
        What is Kubernetes?
        What is a Kubernetes Cluster?
- Deploying Strapi on a Kubernetes Cluster
        Containerize the Strapi application
        Deploying an image to a Container Registry
        Configuring the Kubernetes Ingress
        Scaling the application
- Testing the app
- Stopping and Deleting the cluster
- Conclusion.

**Comment by PaulBratslavsky** [comment]
@FaithKovi you can get started on this.  Thank you. Just confirm when you get started.

**Comment by FaithKovi** [comment]
okay, thanks @PaulBratslavsky. I will get started

**Comment by dessireugarte** [comment]
Hello @FaithKovi 👋
How are you doing with this article?

**Comment by FaithKovi** [comment]
@dessireugarte you can assign someone else to this topic.

**Comment by kimkimani** [comment]
@FaithKovi Is this the same topic https://strapi.io/blog/deploying-and-scaling-the-official-strapi-demo-app-food-advisor-with-kubernetes-and-docker ?

**Comment by FaithKovi** [comment]
@kimkimani no its not. View the request stated.

**Comment by dessireugarte** [comment]
This topic is available again. We released the docs this week on [Running Strapi in a Docker container](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/docker.html#development-and-or-staging-environments) that could facilitate writing this article. 

The author that decides to write this article will have guidance by someone in the Strapi team.

**Comment by kimkimani** [comment]
@dessireugarte I would love to work on this topic. However, just to ask, is this an article or a tutorial?

**Comment by dessireugarte** [comment]
Great news @kimkimani! It would be a tutorial. Do I assign you the topic?

**Comment by kimkimani** [comment]
Yes @dessireugarte

**Comment by dessireugarte** [comment]
Great @kimkimani ! You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x). If you would need some assistance in the process, please let me know and I can put you in contact with someone in the team to guide you. 
Once your article is ready, please share the link here so we can review the article.

**Comment by chepeftw** [comment]
Hello @kimkimani, just checking ... are you working on this article? Otherwise I would love to write this article, but checking first of course 😊, let me know, thanks

**Comment by dessireugarte** [comment]
Hello @kimkimani 👋
Any news on this article?

**Comment by kimkimani** [comment]
> Hello @kimkimani 👋 Any news on this blog post?

Hello @dessireugarte, I'm currently working on #947 and #979.

**Comment by kimkimani** [comment]
> Hello @kimkimani! We didn't have any answer from you, so we will make this topic available again. Would that be ok for you?

Sure, no problem @dessireugarte

**Comment by chepeftw** [comment]
In that case, can I take this topic? Thanks in advance

**Comment by dessireugarte** [comment]
Hello @chepeftw 👋
I assigned you this topic. 
If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form? Then please scroll to the FAQ section and review the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md), how to submit an article, issue an invoice, and get paid.
You can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x). 
Once your article is ready, please share the link here.

**Comment by chepeftw** [comment]
Hello,
I just wanted to let you know that I'm about to finish this article, everything is ready but currently I'm double checking everything and preparing all the support material. I hope to be done in the next weeks. Let me know if you have any questions, have a nice day.

**Comment by chepeftw** [comment]
Hello @dessireugarte and @PaulBratslavsky,
The article draft is ready, I wrote it in 2 parts given the length. So the first part is beginner and intermediate, and the second part is advanced. I wrote it in markdown to make it easier for you.
Here is the link of the draft: https://gist.github.com/chepeftw/d40bbde231586aad0df0a6c536ec9a14

Please let me know your comments, have a nice day and talk to you soon.

**Comment by PaulBratslavsky** [comment]
@chepeftw I am working through your article and have run into this issue, I think it is mac specific.  Is this something you have encountered before?

``` bash
| Something went wrong installing the "sharp" module
strapi-k8s-strapi-1    |
strapi-k8s-strapi-1    | Cannot find module '../build/Release/sharp-linuxmusl-arm64v8.node'
strapi-k8s-strapi-1    | Require stack:
strapi-k8s-strapi-1    | - /opt/app/node_modules/sharp/lib/sharp.js
strapi-k8s-strapi-1    | - /opt/app/node_modules/sharp/lib/constructor.js
strapi-k8s-strapi-1    | - /opt/app/node_modules/sharp/lib/index.js
strapi-k8s-strapi-1    | - /opt/app/node_modules/@strapi/plugin-upload/server/services/image-manipulation.js
```

Thanks in advance.

**Comment by chepeftw** [comment]
Hi @PaulBratslavsky , can you share more information of where you got this issue? Was it while building the docker image or while running the container? Or while running which command or which part? Thanks in advance 😃

**Comment by chepeftw** [comment]
@PaulBratslavsky have you tried adding the `.dockerignore`? It could be that your local node_modules folder is mixing up with the container's one and causing that issue. I did ran into that a similar issue but I don't have a M1 Mac but could be the same.

**Comment by PaulBratslavsky** [comment]
I do have one.  I will clone your repo, try it, and see if it works; maybe I am missing something.  I will let you know how it goes.   But your article is clear and well-written.  Also, I would not be surprised if there is a m1  mac issue.  Will let you know if that's the case also.  Thanks for the help.

**Comment by Eventyret** [comment]
I suggest try with the dockerize tool then do modifications to that.

Also would suggest use a production Dockerfile instead of development 1 due size and 2 better scaling

**Comment by PaulBratslavsky** [comment]
@chepeftw after pulling your code, I had the same issue on my m1 mac; I ended up using https://github.com/strapi-community/strapi-tool-dockerize to regenerate docker-compose.yaml I feel like I missed typing something.  

Including the reference to the tool in the article can make it easier for folks to set up the initial docker image. 

run the following command

``` bash 
    npx @strapi-community/dockerize
```

Complete the steps:
``` bash
✔ Do you want to create a docker-compose file? 🐳 … No / Yes
✔ What environments do you want to configure? › Both
✔ Whats the name of the project? … strapi-k8s
✔ What database do you want to use? › MySQL
✔ Database Host … localhost
✔ Database Name … strapi-k8s
✔ Database Username … strapi
✔ Database Password … ***********
✔ Database Port … 3306

```

Then I run the following command
``` bash 
   docker-compose --env-file .env up
```

This builds successfully

``` bash 
strapi-k8s    | ┌─────────────────────────────┐
strapi-k8s    | │ http://localhost:1337/admin │
strapi-k8s    | └─────────────────────────────┘
```
@Eventyret does this tool update node_modules and packages that I might have been missing? That is why this has fixed the issue for me on my m1 mac?  Otherwise I can't spot other beg differences.

**Comment by Eventyret** [comment]
> @Eventyret does this tool update node_modules and packages that I might have been missing? That is why this has fixed the issue for me on my m1 mac? Otherwise I can't spot other beg differences.

Yes it installs the packages needed if your using postgres or MySQL.

It creates the database files and modifies them to spec, it also creates env variables in .env file.

Last but not least it builds a prod file if both or production is selected. On top of creating a dockerignore file ☺️

**Comment by chepeftw** [comment]
@PaulBratslavsky I have an M1 Mac at home that I'll use to try to replicate the issue. I'll do add a reference to the `dockerize` tool but I do want to find the source of the issue and make the proper fix. I'll get back to you within the next couple of days 😊

**Comment by chepeftw** [comment]
Hey @PaulBratslavsky, so I tested the code in a M1 Mac (2020, Ventura 13.0, Docker 4.16.2) and it works. My best guess is that you might have the Dockerfile cached since I relied on one from the docs. So could you try to remove all Docker cache with the following cmds and let me know if it works:
```
docker system prune
docker image rm mystrapiapp mysql:5.7
docker system prune
```
This should clean all the Docker cache and afterwards if you run again the `docker-compose --env-file .env up` it should work. Let me know please, either way, tomorrow I'll add the dockerize tool reference to the draft.

**Comment by chepeftw** [comment]
Hey @PaulBratslavsky , just letting you know that I updated the draft by adding the references to the dockerize tool. @Eventyret don't hesitate on reviewing the reference just in case you want me to change something or highlight something else or something like that. Let me know your comments 😊.

**Comment by Eventyret** [comment]
I can take a look from my side of things :)

**Comment by dessireugarte** [comment]
Hello  @chepeftw 👋 
Paul reviewed the articles and they are [live](https://strapi.io/blog/how-to-deploy-and-scale-strapi-on-a-kubernetes-cluster-1-2)!  🎉

Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also, please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform) using [this](https://docs.google.com/document/d/1FlyE2LMfogSjsT3xsJacAXkCdArTfIUM6Ag-t5Gf5nI/edit) template. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!
