### ISSUE TITLE
[SUBMIT] DESPLEGAR STRAPI en HEROKU con MONGODB

### ISSUE THREAD

**Issue by xAgustin93** [strapi/community-content#94]
**My resource**
DESPLEGAR STRAPI en HEROKU con MONGODB

**Source**
https://youtu.be/qi4NFFIPXV0

**My format**
- [ ] Article
- [x] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
Great video Agustin!
