### ISSUE TITLE
[SUBMIT] Building a Markdown Editor with Next.Js and Strapi CMS

### ISSUE THREAD

**Issue by ChisomUma** [strapi/community-content#941]
## Introduction

If you are to write technical content or build blogs for such, you will probably make use of markdowns to create article content. Markdown is a format for creating content with different forms of formatting, making it easy to add unique properties such as bold text, italics, different text sizes, and inserting of code blocks.

## Goals

At the end of this tutorial, readers will learn about markdown and its applications and will be able to build a Markdown Editor with Next and Strapi.

## Outline
- What is Markdown?
- What is Strapi?
- Building the Markdown Editor
    - Installing dev dependencies
    - Building the Front-end of the Application
    - Setting up Content Structure on Strapi
    - Connecting the Application to Strapi
- Conclusion
- Resources

Thank you for submitting your article proposal.

**Comment by osamajandali** [comment]
I want to submit a request for writing this tutorial.
This is my first time here..is this one taken or still open ?

**Comment by ChisomUma** [comment]
Hi, I am sorry it is already taken.

**Comment by dessireugarte** [comment]
Hello @ChisomUma 👋
Thanks for sharing the outline. It looks good to me but let's wait for @PaulBratslavsky confirmation on the outline. 
After that you can get started.

**Comment by PaulBratslavsky** [comment]
@ChisomUma I like it.  I am assuming you are implementing the Another common question we get around this topic is how to style the generated markdown.  

Would love if you can cover that in this article, will really help. Also, when you mean markdown editor, are you referring to be able to write markdown from your next js and post to Strapi or just displaying markdown from Strapi in your Next js app?

**Comment by ChisomUma** [comment]
Hi @PaulBratslavsky, Yes! I will be covering styling in the generated markdown. 

On your question, the article will feature a note editor where users can enter text in the form of markdown, which will then be stored in Strapi, and be fetched and displayed in the correct formatting, in a view area.

**Comment by PaulBratslavsky** [comment]
@ChisomUma I would recommend using some sort of WYSIWYG editor to help write the markdown in your next js app rather than using a simple text field.

**Comment by Sachin-chaurasiya** [comment]
Hello @PaulBratslavsky @dessireugarte, I would love to write on this topic.

**Comment by Enecode** [comment]
Hello @PaulBratslavsky @dessireugarte Kindly assign this topic to me.

**Comment by dessireugarte** [comment]
Hello!
We are currently trying to focus on more advanced topics, so we are no longer going to continue with this topic and I'll close the issue.
