### ISSUE TITLE
[SUBMIT] How to write Jest tests for Strapi Plugins

### ISSUE THREAD

**Issue by Cpaczek** [strapi/community-content#942]
## Introduction

If you a writing a plugin that lots of other people and companies or if other people are going to contribute to it tests are a must. We just had a security issue which could of been caught by unit tests. However, there are not guides on how to write tests for a custom Strapi plugin.

## Outline

- What is Jest
- Add Jest to your plugin
- Mocking the Strapi Object
- Mocking `ctx`
- Testing Controllers
- Testing Services
- Running Tests
- Automatically Run Tests with Github Actions
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

I can write this article :) However I am curious as to what the payment structure/requirements are.

**Comment by Cpaczek** [comment]
Just finished up writing tests for my plugin hence why I want to write an article :) https://github.com/excl-networks/strapi-plugin-ezforms/tree/master/tests

**Comment by PaulBratslavsky** [comment]
@Cpaczek great topic. You can start on it. Just confirm when you get started. Thank you. 🙂

**Comment by dessireugarte** [comment]
Hello @Cpaczek 👋 
Could you confirm if you are writing this article?

**Comment by Cpaczek** [comment]
> Hello @Cpaczek 👋 Could you confirm if you are writing this article?

Yes I plan on writing this, I don't have a firm timeline right now.

**Comment by dessireugarte** [comment]
Hello @Cpaczek! How is this topic doing? Let us know otherwise we will close this issue since it has taken a long time now.

**Comment by Cpaczek** [comment]
> Hello @Cpaczek! How is this topic doing? Let us know otherwise we will close this issue since it has taken a long time now.

Hi, sorry been super busy, I don't have a set time to work on this so if someone else wants to take it over they can.

**Comment by Cpaczek** [comment]
@dessireugarte Here is the first draft, please let me know your thoughts: https://gist.github.com/Cpaczek/4c9d559cbfe13ffad5bc334ce4477ac6 

I wrote it in markdown as I could not figure out how to duplicate the dropbox thing.

**Comment by dessireugarte** [comment]
Hello @Cpaczek 👋
Thanks for submitting the draft. We will review it, and if we have any comments or suggestions, we will let you know. Otherwise, we will publish it between the first and second week of January.

**Comment by dessireugarte** [comment]
Hello @Cpaczek 👋 Could you please register on the Write for the Community page [form](https://strapi.io/write-for-the-community#contact)?

**Comment by Cpaczek** [comment]
> Hello @Cpaczek 👋 Could you please register on the Write for the Community page [form](https://strapi.io/write-for-the-community#contact)? 

Done

**Comment by PaulBratslavsky** [comment]
@Cpaczek I like your article, when reviewing it, I realized some people would like to follow along.  But you only provided a completed example.  I forked your repo and removed the jest, test and test.yaml file.  This way folks can have a fresh start and follow along with your tutorial.  I think it would be helpful to include it.  Let me know what you think.  Otherwise your article is all set to go.

**Comment by PaulBratslavsky** [comment]
You can just share the link https://github.com/PaulBratslavsky/strapi-jest-tutorial just to keep it simple. Thank you.

**Comment by Cpaczek** [comment]
> You can just share the link https://github.com/PaulBratslavsky/strapi-jest-tutorial just to keep it simple. Thank you.

Okay I added it to the Gist

**Comment by PaulBratslavsky** [comment]
@Cpaczek this has been reviewed and scheduled for publishing will let you know when it goes live.

**Comment by dessireugarte** [comment]
Hello @Cpaczek! Thanks for submitting your invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

If you already did that step, then I would only be missing your proof of bank details (bank statement, bank letter, online screenshot). You can send the bank account details to my email address dessire.ugarte-amaya@strapi.io 

Please feel free to reach out to me if you have any questions!

**Comment by dessireugarte** [comment]
Hello @Cpaczek!
Could you please confirm for us when you receive your payment?

**Comment by Cpaczek** [comment]
> Hello @Cpaczek!
> Could you please confirm for us when you receive your payment? 

Yes thank you
