### ISSUE TITLE
How to create a landing page on the fly without the need to develop

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#944]
**My Request**

An article for marketers or content managers explaining, if Strapi is set up properly, how an individual from the content team can create a new landing page from scratch using components in the dynamic zone

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by femakin** [comment]
Please can I work on this ?

**Comment by dessireugarte** [comment]
Hello @femakin 👋 Are you still interested in writing this article?

**Comment by femakin** [comment]
I couldn't get a better material/Resources on the Topic

**Comment by dessireugarte** [comment]
Ok, thanks @femakin

**Comment by jasminetracey** [comment]
@dessireugarte would this article be an improvement on https://strapi.io/blog/how-to-create-pages-on-the-fly-with-dynamic-zone?

**Comment by PaulBratslavsky** [comment]
@jasminetracey great question. The previous article was done using v3 using the v3 Food Advisor app.  So that needs to be updated too.  

But for this particular issue, we are looking for someone to write about how to structure content on the front end using a  landing page example.  

For instance, how would you structure your strapi content to populate this landing page https://demo.web3canvas.com/themeforest/mediclick/yoga.html

You can accomplish this by using things like Dynamic zones, components, and repeatable components. So that is what we would like to highlight.  

Let me know if you have additional questions.

**Comment by dessireugarte** [comment]
As Paul said @jasminetracey. This is a resource for content managers, and the objective is after Strapi is set up, they can create a landing page without the need for coding or the help of a developer.

**Comment by Marienoir** [comment]
Hello @dessireugarte @PaulBratslavsky 
I will like to create content for this article.
I can share an outline if my request is approved
Thanks

**Comment by PaulBratslavsky** [comment]
@Marienoir we are currently not taking any new article submissions until January.  If you are still interested in writing the article please provide an outline for us to better understand what you will cover.  We are looking for something that demonstrates a use case using Strapi dynamic zoned and compnents.

**Comment by Marienoir** [comment]
@PaulBratslavsky 
Yes, I am interested in still writing this article. I would submit it by January though. 
### Article Outline: How to create a landing page on the fly without the need to develop

Outline
- Introduction
    - Understanding Strapi as a Headless CMS
    - A non-technical approach to using Strapi for a landing page
- Goal
    - Here, we will be creating a home page for a fitness company called Stri-Fitness.
- Prerequisites
- Step 1: Scaffolding a Strapi Project
- Step 2: Build the Stri-Fitness Collection.
- Step 3: Populate Content for the landing page
- Step 4: Understanding dynamic zones and components in a non-technical term
- Step 5: Application of repeatable components and dynamic zones in the Str-Fitness landing page 
- Step 6: Preview your home page with an option to deploy to Netlify in a non-technical explanation.
- Conclusion

**Comment by TechMakanaki** [comment]
Hello @PaulBratslavsky and @dessireugarte I will like to work on this article.
I will provide my outline if I get a headstart from you.

**Comment by Marienoir** [comment]
Hello @PaulBratslavsky @dessireugarte 
Happy holidays 🙂
I submitted a proposed article outline last year.
Can I start working on a draft as it is January already?
Thanks

**Comment by dessireugarte** [comment]
Hello @Marienoir!
Would you be open to waiting for Strapi Cloud Soft Launch release (end of this month) to include the deployment in Strapi Cloud in the tutorial?

**Comment by Marienoir** [comment]
Hello @dessireugarte 
Alright, I could wait till the launch then so I include that feature
Thanks for getting back to me

**Comment by Marienoir** [comment]
Hello @dessireugarte @PaulBratslavsky 
As regards this content, can I now start working on this draft as the Strapi cloud has been launched?

**Comment by PaulBratslavsky** [comment]
@Marienoir before you start can you give me an idea of what dynamic zone components are you going to create to show case the landing page example.  Like, Hero Section, Features etc... Just want to get a better idea of how you will be demoing the dynamic zones and components functionality.  Thank you.

**Comment by Marienoir** [comment]
@PaulBratslavsky I intend to use the following components

1. Hero section
2. Features
3. Time schedule
4. Pricing
5. Frequently Asked Questions
6. CTA
7. Footer

**Comment by daacode** [comment]
@PaulBratslavsky @dessireugarte Can I work on this?

**Comment by Marienoir** [comment]
@PaulBratslavsky @dessireugarte Please what is the update on this article?

**Comment by PaulBratslavsky** [comment]
@Marienoir Sorry for the delay, our team size has decreased so we have been catching up with all of the backlog in WFC.  If you are still interested, you can start working on it.   Please let me know if you are still interested in writing this.

**Comment by hanakhelifa** [comment]
Hello @Marienoir, do you have a draft or an ETA to share so far?
As we are revamping the program, we'd need to finish those started draft this month. Let us know if it's still OK for you.

**Comment by Marienoir** [comment]
Hello @hanakhelifa 
I am still working on the draft. An ETA would be in a week time from now.
However, I have some issues I would like to clarify from @PaulBratslavsky 
I have not able to get him during the office hours, guess I will just ask here or send him a DM

**Comment by hanakhelifa** [comment]
You can attend the following office hour if needed :)

**Comment by Marienoir** [comment]
Hello @hanakhelifa @PaulBratslavsky 
 This is a draft of the article
https://hackmd.io/@marynoir/B1NIVaTRh
Thanks

**Comment by Marienoir** [comment]
Hello @PaulBratslavsky @hanakhelifa 
I have submitted a draft of the article

**Comment by vcoisne** [comment]
Hi @Marienoir your blog post is live https://strapi.io/blog/how-to-create-a-landing-page-on-the-fly-without-the-need-to-develop 

Please feel free to submit the invoice here https://forms.gle/Ruz8maZvfhdjk1ri7

**Comment by Marienoir** [comment]
Thanks @vcoisne 
I have submitted an invoice in this regards.

**Comment by vcoisne** [comment]
@Marienoir we have updates to the form for compliance reasons. Do you mind re-submitting the form please ?

**Comment by Marienoir** [comment]
Hello @vcoisne 
I have resubmitted the form.
Thanks.

**Comment by vcoisne** [comment]
@Marienoir payment has been requested to our finance team.
