### ISSUE TITLE
[SUBMIT] How to Build Android Apps with Kotlin and GraphQL using Strapi CMS and GraphQL Plugin

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#945]
- Prerequisites
- What is Strapi
- GraphQL vs. REST
- Setting up Strapi Locally
   - Managing Backend Content using Strapi
   - Creating the API Access Token
   - Generating Strapi GraphQL endpoint
- Consuming Strapi API using Android
- Setting up Android Studio
- Adding application dependencies
- Configuring GraphQL in Android
  - Writing GraphQL Queries
  - Generating Schema
- Setting up Apollo Client
- Adding Strapi authorization headers
- Making using GraphQL request using Apollo Client
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by kimkimani** [comment]
@PaulBratslavsky I want to cover this topic.

Create Strapi with GraphQL, explain and implement the concept using Android GraphQL.

**Comment by PaulBratslavsky** [comment]
Due to many beginner articles in cue.  We are currently looking for articles showcasing more of Strapi's backend customizations that cover intermediate to advanced topics.  Will be closing this issue at this time.
