### ISSUE TITLE
[SUBMIT] How to Make HTTP Requests with Ktor in Android using Kotlin and Strapi CMS

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#947]
- Introduction
- Goal
- Prerequisites 
- What is Ktor
- Why Ktor
- Setting up Strapi locally
  - Create Strapi Notes App Backend
  - Managing the Notes Content
  - Creating the API Access Token
- Setting up an Android project
- Adding the required libraries
- Setting up the data models
- Setting up the API endpoints
- Processing the API data
- Creating XML files
- Testing
- Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@kimkimani  You can start working on this one.

**Comment by dessireugarte** [comment]
Hello @kimkimani! Are you still working on this blog post?

**Comment by kimkimani** [comment]
Hello @dessireugarte, yes I'm working on it

**Comment by dessireugarte** [comment]
Hello @kimkimani 👋 Just wanted to check how are you doing with this article?

**Comment by kimkimani** [comment]
Hello @dessireugarte Can I please submit this one after the holiday?

**Comment by dessireugarte** [comment]
@kimkimani sure no problem 👍

**Comment by dessireugarte** [comment]
Hello @kimkimani!
Since we didn't hear back on this topic, we will close this issue.
