### ISSUE TITLE
[SUBMIT] React and GraphQL: Build React App using GraphQL and Strapi GraphQL

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#948]
Introduction
Outline
Prerequisites
What is Strapi CMS
Why a headless CMS
Why Strapi
What is React
What is GraphQL
When to use GraphQL
Setting up Strapi locally
Create Strapi Backend App 
Managing the Notes Content
Creating the API Access Token
Create React Application
Perform operations with the GraphQL server
Reading data with GraphQL
Writing data with GraphQL
Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by femakin** [comment]
Please is this still open ?

**Comment by PaulBratslavsky** [comment]
@kimkimani were you thinking of using next js?

**Comment by kimkimani** [comment]
@PaulBratslavsky Just ReactJS. Next can still work on this one. Which should I pick? Or do we cover them individually? I am open to any suggestions.

**Comment by Bishopukpai** [comment]
Hi, can I write on this topic

**Comment by icode247** [comment]
Hi @kimkimani 
I can work on this topic

**Comment by PaulBratslavsky** [comment]
@kimkimani I think the way the current outline is, the article is too basic.  We have already a video and a couple of articles that showcase the basic use of graphql on the front end.   

But we have this article that needs to be updated https://strapi.io/blog/a-deep-dive-into-strapi-graph-ql more specifically would like to cover the filtering options in Strapi v4

**Comment by virgincodes** [comment]
@PaulBratslavsky  so what do you need to be changed in [it](https://strapi.io/blog/a-deep-dive-into-strapi-graph-ql), i think I can drop a draft by next Monday

**Comment by PaulBratslavsky** [comment]
@virgincodes basically the majority of the article will have to be rewritten due to the changes made to graphql in v4 from the response that you get back, to the way filtering work.  I would also add how to get components and dynamic zones.

**Comment by dessireugarte** [comment]
@virgincodes @PaulBratslavsky the article mentioned by Paul is already being updated #611
