### ISSUE TITLE
[TOPIC] Symphony

### ISSUE THREAD

**Issue by adriatic** [strapi/community-content#95]
# About Symphony

![image](https://user-images.githubusercontent.com/2712405/82606714-873b7d80-9b85-11ea-887d-13b261359300.png)

Symphony is the code name for the project proposing to build a relatively complex distributed application intended to become a part of the Strapi community created advanced education tool

Since the Symphony app aims to illustrate all modern concepts (starting with Identity Management - aka Authentication and Authorization) we plan to present the use of several alternative services (AUTH0, AWS AIM, OKTA, Microsoft IAM). Similarly, we plan to make use of several available variants of any other service that are if importance to our app.

Symphony is not ready to start - please see the status by checking the **[Symhony Organization Site](https://adriatic.github.io/symphony/)** for details. This document itself is in its initial form and is being changed daily

**Comment by malgamves** [comment]
Hey @adriatic the Symphony site seems to be down. How is the project going?

**Comment by ShadaW11** [comment]
Hello @adriatic It seems the website is still down. Any progress?

**Comment by adriatic** [comment]
Hello, @ShadaW11 - I am not a member of Strapi contributors group for at least a year. Sorry for not indicating this more clearly.
