### ISSUE TITLE
How to integrate Push Notifications into your applications using Strapi v4 and Firebase Cloud Messaging[SUBMIT]

### ISSUE THREAD

**Issue by i1d9** [strapi/community-content#956]
Hello 👋 

In this tutorial, we will be developing a microblogging application to demonstrate how we could use a Strapi instance to trigger push notifications. We will be using a Flutter application as a client to enable us to test the notifications on various platforms.

Outline
- Introduction
- Prerequisites
- The stack: Strapi, Flutter and Firebase Notifications
- Initializing a Strapi project
- Creating Collections
- Extending User Permission Plugin
- Firebase Setup
- Firebase Functions
- Saving relations between collections
- Initializing the flutter project
- Notification Configuration
- UI components
- Conclusion.

**My content is**

- [X] A Strapi Tutorial / Guide / How to article
- [X] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by i1d9** [comment]
@TiaraOluwanimi I'm looking forward to your feedback about this [Article](https://www.dropbox.com/scl/fi/skcdals2xjj4h0gdjgy5y/How-to-integrate-Push-notifications-on-your-applications-using-Strapi-v4-and-Firebase-Cloud-Messaging.paper?dl=0&rlkey=0pj2aditqkabr2enfo45fqfjd)

**Comment by PaulBratslavsky** [comment]
@i1d9 can you give me a quick overview of the flow of the functionality of the app and which parts are going to be handled where.  Just so I can get a better understanding of what is going to happen where.  Also, can you add some detail on how you will extend User Permissions Plugin.  Just so I can have more context on what the article will cover in more detail. Thank you.

**Comment by i1d9** [comment]
@TiaraOluwanimi I'm looking forward to your feedback about this [Article](https://www.dropbox.com/scl/fi/skcdals2xjj4h0gdjgy5y/How-to-integrate-Push-notifications-on-your-applications-using-Strapi-v4-and-Firebase-Cloud-Messaging.paper?dl=0&rlkey=0pj2aditqkabr2enfo45fqfjd)

**Comment by dessireugarte** [comment]
Hello @i1d9 👋
Thanks for submitting the article. Remember you can't start writing an article without the approval of the outline since we need to ensure we are not duplicating existing content.  Maybe I missed the issue where you shared it? 

Regarding feedback, for the article, Paul shared his feedback on this issue.

**Comment by i1d9** [comment]
@dessireugarte Okay...I'll take that into account when creating my next issue

**Comment by dessireugarte** [comment]
Hello @i1d9 👋
I'm waiting for a reviewer to take a look at your content and then I'll get back to you! Sorry for the delay on this

**Comment by PaulBratslavsky** [comment]
Will add this to my list of articles to review, and will get back to you as soon as I am done.

**Comment by PaulBratslavsky** [comment]
@i1d9 I am currently working on reviewing your article, can you please double-check that you provided the correct GitHub link for both projects?  For Strapi I am getting different content types than what you specified in the tutorial.  Looks like it is from a bidding app you were working on.

Also the code example in the article where you show how to extend the user permissions plugin was an image for me rather than a code snippet.  Can you check that too? Just so it is easier to copy code.  Thank you.  So far everything looks great.  Would love to get the review done by this week so we can add it to the cue.

**Comment by i1d9** [comment]
@PaulBratslavsky I've updated the article with the suggested changes

**Comment by dessireugarte** [comment]
Hello @i1d9  👋
Just wanted to let you know that your article will be published around the second week of December. I'll let you know if we need any changes or when it is published!

**Comment by PaulBratslavsky** [comment]
@i1d9 I added few minor fix suggestions otherwise everything else looks good.  Let me know if you have any question.  Thank you.

**Comment by i1d9** [comment]
@PaulBratslavsky Hey...I'll added the suggested changes and let you know once I'm done

**Comment by i1d9** [comment]
@PaulBratslavsky Hey...I've made the changes and updated the source code repo

**Comment by PaulBratslavsky** [comment]
@dessireugarte this article is all set to get published.

**Comment by dessireugarte** [comment]
Hello @i1d9 👋 
Your article is [live](https://strapi.io/blog/how-to-integrate-push-notifications-into-your-applications-using-strapi-and-firebase-cloud-messaging)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform).
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by i1d9** [comment]
@dessireugarte I've filled the following in the W-8BEN form Part I 1, 2, 3 and 8. Is that okay?
