### ISSUE TITLE
How to Build a Chat Application Using Strapi CMS, PHP, MySQL and Vanilla JS 1/3 [Request New Content]

### ISSUE THREAD

**Issue by lucky4242** [strapi/community-content#958]
This article is about developing a chat application in which different users interact with one another. This chat app also displays active and inactive online users. Strapi will handle all incoming and outgoing messages between users.

Here is the outline
part(1)
Introduction
User Authentication(Registration )
User Verification (login)
Creating Header page
Creating index Page

Creating Search Page(part 2)
Creating User Page
Creating chat platform

Strapi Installation (part 3)
Creating collection types
Integrating Chat Message with Strapi
Logout
Testing
Conclusion

Thank you.

**Comment by ajibade3210** [comment]
@PaulBratslavsky is this topic still available I'd like to pick it up

**Comment by dessireugarte** [comment]
Hello @lucky4242 👋 
We already have similar topics in our blog. So we would prefer to share different topics. Please feel free to add other requests you might have!
