### ISSUE TITLE
[TOPIC] How to configure Socket.io on Strapi

### ISSUE THREAD

**Issue by Marcosul** [strapi/community-content#96]
I need a tutorial on how to configure Socket.io on Strapi. I can not! Need help.

**Comment by brunoagatao** [comment]
I would be happy to take this one off your hands.

**Comment by Mcastres** [comment]
Don't forget to check our FAQ: https://www.notion.so/strapi/Strapi-Write-for-the-Community-FAQs-b1fa0282d68a4c3e933fdd5e05f61a46

**Comment by malgamves** [comment]
This was sort of covered in this [article](https://strapi.io/blog/how-to-build-a-real-time-chat-forum-using-strapi-socket-io-react-and-mongo-db) so I'll close this.
