### ISSUE TITLE
[SUBMIT] HOW TO SEND EMAIL NOTIFICATIONS WITH STRAPI AND MAIL CHIMP

### ISSUE THREAD

**Issue by Bishopukpai** [strapi/community-content#974]
This article is about  learning how to use strapi and sendgrid to send email messages to specified email addresses. Strapi will be used as the backend API that will send the message from a specified sender to a receiver.

This article will have the following sections:
1. Introduction
2. Setting Up sendgrid account
3. Setting Up strapi project
4. Integrating Sendgrid with strapi
5. setting up the email messaging logics
6. conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article

**Comment by Xemarij** [comment]
I am new here in the Strapi community. I notice the "Looking for author" label, is the project available. If so please assign it to me, I am interested.

**Comment by PaulBratslavsky** [comment]
@Bishopukpai @Xemarij there is already a video resource on this exact topic https://www.youtube.com/watch?v=FMkRFVA75OU&t=143s If you would like to cover a similar topic I would recommend using strapi-provider-email-nodemailer with mandril.

**Comment by Xemarij** [comment]
Thank you Paul.
The topic "HOW TO SEND EMAIL NOTIFICATIONS WITH STRAPI AND SENDGRID" is
okay with me. The video will definitely help.

Kind regards,
Tauqeer Khurram

**Comment by PaulBratslavsky** [comment]
@Xemarij if you are going to write this article it would have to use something else like I mentioned above. So the new title will be "HOW TO SEND EMAIL WITH STRAPI USING MANDRIL AND NODEMAILER"   If Mandril does not work for you, you can provide another email provider.  Because we already have an example of how to send email via sendgrid.  The goal is to offer something that we haven't covered yet.

**Comment by Xemarij** [comment]
Hi @PaulBratslavsky,
The Mandrill has been deprecated as you may know. It is now "Mailchimp Transactional Email" therefore I will stick to NODEMAILER. The topic of the article would be "HOW TO SEND EMAIL WITH STRAPI USING NODEMAILER." FYI.

**Comment by Xemarij** [comment]
Hi @Bishopukpai and  @PaulBratslavsky,
Any updates on this????

**Comment by PaulBratslavsky** [comment]
@Xemarij sorry for the delay, we have a lot of article that we have in cue that will keep us busy until the end of the year.  

I knew that MailChimp acquired Mandril but did not know that they changed the name. What we are looking for is not so much an article on how to use nodemailer, but how to send Strapi emails with MailChimp integration.  

But let me know if you are still interested, we can submit this in January.

**Comment by Xemarij** [comment]
Hi  @PaulBratslavsky,
Thank you for reaching back to me. Paul, yes I am still interested in
writing the blogpost.
I propose the title of the article to be "How to integrate Strapi with
MailChimp and Send Emails." However, I have carefully researched for the
APi or methods to integrate Strapi and MailChimp. I have found nothing that
is doable. I also went through the Strapi and mailchimp documentations. If
it is possible could you share with me the links and videos.

Kind Regards,
Tauqeer Khurram

**Comment by Xemarij** [comment]
Hi @PaulBratslavsky,
I have completed the article. Please let me know when and how to send it.

Kind regards,
Tauqeer Khurram

**Comment by Xemarij** [comment]
[How to Send Email Notifications with Strapi and Mailchimp.docx](https://github.com/strapi/community-content/files/10306774/How.to.Send.Email.Notifications.with.Strapi.and.Mailchimp.docx)

Hi @PaulBratslavsky,
I have finished the draft for the article and I am submitting for review. Please proceed, I am waiting for your feedback.

All the best,
Tauqeer Khurram @Xemarij

**Comment by PaulBratslavsky** [comment]
**NOTICE: At this time Strapi DOES NOT allow for content written by ANY AI platform, while you can use these AIs for research, the content SHOULD NOT be written by the AI.**

We take an ABSOLUTELY ZERO TOLERENCE policy on this, any content submitted will be given one (1) warning and any further submissions that violate this rule will be banned from our writing programs.
