### ISSUE TITLE
[Request New Content] Headless CMS vs Backend framework

### ISSUE THREAD

**Issue by vcoisne** [strapi/community-content#975]
**My Request**

Compare Headless CMS vs Backend framework, differences, similarities, where it fits in the overall stack, etc

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by Saintdavidking** [comment]
Hello @PaulBratslavsky 
i will like to take on this topic

**Comment by PaulBratslavsky** [comment]
@Saintdavidking sounds good. Can provide an outline when you are ready?  Thank you.

**Comment by Saintdavidking** [comment]
Hello @PaulBratslavsky, this is my proposed outline

Topic: Headless CMS vs Backend framework

Outline:

- Introduction
- What is a Headless CMS
- What is a Backend framework
- Example of a Headless CMS (Strapi)

       - Overview of Strapi
       - Strapi installation

- Headless CMS vs Backend framework [Pros and Cons of Headless CMS]

 Conclusion

**Comment by vcoisne** [comment]
@Saintdavidking I don't think we need the example of Headless CMS section as it has been covered many times, I would rather want to focus on comparison with popular backend frameworks like Express or Django.

**Comment by Saintdavidking** [comment]
Hello @PaulBratslavsky  How about this?
 outline

Topic: Headless CMS vs Backend framework

Outline:

Introduction

What is a Headless CMS

What is a Backend framework

Example of Backend frameworks.

Headless CMS vs Backend framework 
- [Pros and Cons of Headless CMS]
- Similarities and cocomparison

Conclusion

**Comment by dessireugarte** [comment]
Thanks,@Saintdavidking! 
Does the outline proposed by David looks good to you @vcoisne?

**Comment by Saintdavidking** [comment]
Hi @dessireugarte @vcoisne any update about this topic ? Is it good to go?

**Comment by Saintdavidking** [comment]
Hi @dessireugarte  @vcoisne  @PaulBratslavsky @ any update about this outline? Is it good to go?

**Comment by popoolatopzy** [comment]
Hi @dessireugarte is this topic still available?

**Comment by Saintdavidking** [comment]
Hello, @dessireugarte any update about this outline? Is it good to go?

**Comment by Saintdavidking** [comment]
Hello @dessireugarte,
below is the link to the article draft:

https://www.dropbox.com/scl/fi/umd38st648cakxehze07t/Headless-CMS-vs-Backend-framework.paper?dl=0&rlkey=ght3u9qzj9jxh2ytp1apoqce6

**Comment by Saintdavidking** [comment]
Hi @dessireugarte

**Comment by Saintdavidking** [comment]
Hi, @PaulBratslavsky 
Is there any update on the review?

**Comment by PaulBratslavsky** [comment]
@Saintdavidking I added some notes to your post.  Was not sure if you were aware of all the features of Strapi that make it a viable choice over frameworks.  I felt the comparison was not complete.

**Comment by Saintdavidking** [comment]
> @Saintdavidking I added some notes to your post. Was not sure if you were aware of all the features of Strapi that make it a viable choice over frameworks. I felt the comparison was not complete.

Thanks for the corrections, I have made the required corrections to the document.

**Comment by PaulBratslavsky** [comment]
@Saintdavidking thank you for submitting your article. After careful review with our team, we have determined that this article is better suited to be written internally by our team. 

We appreciate your dedication, and although we are unable to feature your article on the Strapi website, we would like to offer you a compensation of $50 as a gesture of our gratitude for your efforts.

Furthermore, we encourage you to publish the article on your own platform if you so choose. Once again, thank you for your submission, and we look forward to future opportunities to collaborate.

**Comment by Saintdavidking** [comment]
@PaulBratslavsky can you tell what is missing in the article so I can include it or is this the final decision?

**Comment by PaulBratslavsky** [comment]
@Saintdavidking thank you.  I will check on the status.

**Comment by dessireugarte** [comment]
Hello @Saintdavidking! Could you please resubmit the invoice? We didn't receive it.

**Comment by dessireugarte** [comment]
Hello @Saintdavidking!
Could you please submit the invoice with the updated date?

**Comment by Saintdavidking** [comment]
HI @dessireugarte !
I have just updated the invoice and resend it.
