### ISSUE TITLE
[SUBMIT] Build and Deploy a Portfolio Website Using Next.js and Strapi

### ISSUE THREAD

**Issue by ajibade3210** [strapi/community-content#976]
## Introduction
Having a portfolio to showcase what you do and what you've been up to is one of the best ways to present yourself online. In this article, we will build a simple portfolio website using Strapi, Nextjs, Tailwind, and Vercel.

## Outline

- Introduction
- Setting Up Strapi
- Creating Content Types
- Adding Content Through the Strapi CMS
- Authentication in Strapi
- Setting Up NextJs Application and Tailwind
- Setting Up NextJs Application Dark Mode
- Consume data and image from Strapi with Nextjs
- Deploy Next.js to Vercel
- Conclusion

**My content is**

- [X] A Strapi Tutorial / Guide / How to article
- [X] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

I can write this article :)

**Comment by dessireugarte** [comment]
Hello @ajibade3210!
We have some similar blog posts as this with a similar outline. 
I would suggest focusing the article on leveraging Vercel with a Headless CMS and deploying your Strapi app in Vercel.
What do you think?

**Comment by ajibade3210** [comment]
Okay, it's fine. 
Do you mean I should focus the article more on deploying a Strapi application using Vercel

**Comment by PaulBratslavsky** [comment]
@ajibade3210 You can write about how to deploy Next JS app to Vercel using SSG, then you can set up a hook in Strapi that will file when new content is added and rebuild and redeploy the next js app.  So that way, the Strapi server is not being hit on every request.  Which can save on cost.  Let me know if you have any questions.

**Comment by ajibade3210** [comment]
@PaulBratslavsky this is fine if I have any question I would let you know. Can I start working on this?

**Comment by ajibade3210** [comment]
@PaulBratslavsky @dessireugarte I think I might need to deploy the strapi application for this article.
Can I use Heroku?

**Comment by dessireugarte** [comment]
@ajibade3210 why not using Vercel as we discussed previously?

**Comment by Mcastres** [comment]
@dessireugarte, you can't deploy Strapi on Vercel.

Vercel is built to deploy mostly front end.

**Comment by dessireugarte** [comment]
@Mcastres ok. Would it be ok what @ajibade3210 is suggesting?

**Comment by Mcastres** [comment]
Yep, LGTM

**Comment by dessireugarte** [comment]
Great. 
@ajibade3210 you can start writing your draft. We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x). 
Once your article is ready, please share the link here and we will review the article.

**Comment by ajibade3210** [comment]
@PaulBratslavsky @dessireugarte  Here Is a [draft](https://www.dropbox.com/scl/fi/qsv76vo1uskh9u9dct8mc/How-to-Create-an-SSG-Static-Site-Generation-Application-with-Strapi-Webhooks-and-NextJs.paper?dl=0&rlkey=r1iyi08ew2z437sxwcskhtuf2) of the article.

**Comment by ajibade3210** [comment]
Hello @PaulBratslavsky @dessireugarte Please How do i go about submitting my [DRAFT](https://www.dropbox.com/scl/fi/qsv76vo1uskh9u9dct8mc/How-to-Create-an-SSG-Static-Site-Generation-Application-with-Strapi-Webhooks-and-NextJs.paper?dl=0&rlkey=r1iyi08ew2z437sxwcskhtuf2) for this article

**Comment by dessireugarte** [comment]
Thanks @ajibade3210, we will review the article and get back to you asap.

**Comment by ajibade3210** [comment]
@dessireugarte @TiaraOluwanimi Please I am still yet to get any update on this

**Comment by dessireugarte** [comment]
Hello @ajibade3210 👋 
Sorry for the delay, we have many articles in the queue for reviewing. But we will get back to you when it is reviewed and we have the date to publish it. 
Thanks for your patience.

**Comment by dessireugarte** [comment]
Hello @ajibade3210  👋
Just wanted to let you know that your article will be published this week. I'll let you know when it is published!

**Comment by dessireugarte** [comment]
Hello @ajibade3210  👋 
Your article is [live](https://strapi.io/blog/how-to-create-an-ssg-static-site-generation-application-with-strapi-webhooks-and-nextjs)! 🎉
Please register to our forum by clicking on the discussion at the bottom of your post, so you automatically receive notifications when someone adds comments. Also please follow the [guidelines](https://strapi.io/write-for-the-community) to issue and submit an invoice. 
You should register yourself as an Individual Vendor in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform) and then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform), and soon you will receive your payment. 
If you want to promote your article, [here](https://strapi.notion.site/Promotion-Template-for-Writers-1645b77a97a640d2a32047297b6bc3f0) are some ideas and templates that might help you!
Please feel free to reach out to me if you have any questions!

**Comment by ajibade3210** [comment]
@TreciaKS @dessireugarte Just a reminder that I am still yet to get an update on this [DRAFT](https://www.dropbox.com/scl/fi/qsv76vo1uskh9u9dct8mc/How-to-Create-an-SSG-Static-Site-Generation-Application-with-Strapi-Webhooks-and-NextJs.paper?dl=0&rlkey=r1iyi08ew2z437sxwcskhtuf2)

**Comment by ajibade3210** [comment]
Thank you I have sent in my invoice
