### ISSUE TITLE
Building a Lyrics Finder App with Typescript with react and Strapi cms

### ISSUE THREAD

**Issue by CoderOfPHCity** [strapi/community-content#978]
**My resource**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by dessireugarte** [comment]
Hello @CoderOfPHCity!
Could you please share the outline of what the article would look like?

**Comment by Claradev32** [comment]
Hi @dessireugarte,
I can work on this topic with the outline below:
- What is Strapi
- Setup Strapi Project
- Configure Typescript
- Create Lyrics and Songs Content Types
- Setup React Application
- Setup the App Components
- Add Search Functionality
- Conclusion

**Comment by PaulBratslavsky** [comment]
@Claradev32 since this article is going to be around typescript, in the outline above, can you add 

-  what is typescript
- what problem does it solve
- and why you should use it

I am assuming this will cover using Typescript on both the front and backend.

**Comment by dessireugarte** [comment]
Great @Claradev32 👍
You can get started. 
If this is your first article, can you please register your author details [here](https://strapi.io/write-for-the-community) by filling out the form? Then please scroll to the FAQ section and review the article [guidelines](https://github.com/strapi/community-content/blob/master/tutorials/GUIDELINES.md), how to submit an article, issue an invoice, and get paid.
We use Dropbox Paper to submit and review drafts. Please duplicate and use this [article template](https://www.dropbox.com/scl/fi/7o4rzejzmla65hygplkai/My-First-Strapi-Article.paper?dl=0&rlkey=zoc4r7k3iw7titgsxp8vrt55x). 
Once your article is ready, please share the link here and we will review the draft.

**Comment by CoderOfPHCity** [comment]
Hello Dessi,

I created the pitch idea alongside the article and project. I would like to
continue with the article as I have invested much time and effort into
building the lyrics app project.
This is my first time working on the strapi platform, hence I had no idea
of the protocols for sending outlines. I already sent my outline to the
wrong strapi Twitter account because i was unaware of the protocols for
strapi guest writing.

I found this email in my spam folder a few hours ago.

Here is the detailed outline I already prepared:
https://docs.google.com/document/d/1yFDqz2RFzmh3aIsWCVWEwwtdCRb1S08zFCpiwtvu3lk/edit?usp=sharing

I have also started working on building the front end part of the project,
Link to GitHub repository here:
https://github.com/CoderOfPHCity/Lyrics-Finder

**Comment by CoderOfPHCity** [comment]
Link works perfectly, try checking again or refreshing your browser.

**Comment by dessireugarte** [comment]
Hello @CoderOfPHCity!
Do you currently just have the outline? I am afraid that we might not be able to continue with this topic since you could get affected by the payment situation since I have seen you are located in Nigeria, [here](https://discord.com/channels/811989166782021633/843965836887851078/1031584885258866760) is more context about it. Unless you have another location payment option, it won't be possible to continue, and then when you finish the article pay for it. 
Please let me know if you have other options for payment to review if we proceed or not with this topic.

**Comment by CoderOfPHCity** [comment]
Hello Desai, I have a complete outline of the topic here:
https://docs.google.com/document/d/1yFDqz2RFzmh3aIsWCVWEwwtdCRb1S08zFCpiwtvu3lk/edit?usp=sharing

Payment won't be an issue as I have colleagues from Nigeria who work with
Strapi too.

Kindly let me know of the payment options available so I can pick one
suitable.

There are lots of options including some I have used personally like;

deel:
https://www.deel.com

Grey:
http://grey.co

Transferwise:https://wise.com

Cryptocurrencies are also an option as well

**Comment by PaulBratslavsky** [comment]
Upon further review and content requirements changes for WFC, at this time, we are hoping to focus on more advanced topics that haven't been covered as much on our site.

Specifically, we're looking for articles that delve into Strapi backend customizations and extensions, as we already have a lot of great content available on the basics of Strapi.

We encourage you to check out issue https://github.com/strapi/community-content/issues/1155 for some topic ideas that we think would be a great fit for our current needs. And please don't hesitate to submit future ideas as well. Thank you again for your time and effort!
