### ISSUE TITLE
[SUBMIT] How to Perform React Native Authentication with Strapi

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#979]
- What is Strapi
- What is React Native
- Installing Strapi
- Overview of Strapi application
- Create Strapi locally
- Setup React Nativeproject
- Setup our networking logic
- Add Http library to fetch APIs
- Implement API fetching layer
- Build screens
- Build login screen
- Build registration screen
- Build Dashboard screen
- Build user profile
- How to reset Password/ Forgot password
- Sign out
- Conclusion

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by PaulBratslavsky** [comment]
@kimkimani nice, you can get started on this article.

**Comment by kimkimani** [comment]
@PaulBratslavsky, This one is ready https://www.dropbox.com/scl/fi/r9swrlbqwul92qwmau9zy/How-to-Implement-Authentication-in-React-Native-using-Strapi.paper?dl=0&rlkey=no674xeq0qurspfppexh9nj3n

**Comment by dessireugarte** [comment]
Hello @kimkimani 👋
We will review the article and let you know if there are changes needed to be made.

**Comment by PaulBratslavsky** [comment]
@kimkimani do you have a GitHub link to this project, I want to run the code.  I have some questions but want to test the functionality first.

**Comment by kimkimani** [comment]
Yes @PaulBratslavsky https://github.com/kimkimani/react-native-strapi

**Comment by PaulBratslavsky** [comment]
@kimkimani thank you.

**Comment by PaulBratslavsky** [comment]
@kimkimani can you also provide the GitHub link to your Strapi project used?  I would like to test the reset password functionality to make sure that it works.

**Comment by kimkimani** [comment]
Yes @PaulBratslavsky I have added that

**Comment by PaulBratslavsky** [comment]
I could not find it in the repo link you shared above can you also give me permission to add notes to your draft my email is paul.bratslavsky@strapi.io

**Comment by PaulBratslavsky** [comment]
@kimkimani also have a question about giving the public access to 
- Enable the following under User Permissions for User:
    - count
    - create
    - find
    - findOne
    
 Why would you want to have public access to these points?

**Comment by kimkimani** [comment]
@PaulBratslavsky, I think I will check and verify that. We should defiantly have access permission to only authenticated users.

**Comment by PaulBratslavsky** [comment]
Alos you don't need to use API tokens either.  And I belive resetting the password will not work unless you set up the email provider which will add additional steps to the tutorial which I have not seen you cover yet.

You can refactor your code, takeout a password reset, or at least mention that it requires extra steps to get working, and let me know once you make the changes.

Thank you.

**Comment by kimkimani** [comment]
Thank you Paul. I will work on those changes.
