### ISSUE TITLE
[SUBMIT] How to create automated tests for Strapi API using PactumJS

### ISSUE THREAD

**Issue by a7medayman6** [strapi/community-content#981]
### **A beginner’s guide on how to create and run automated tests for Strapi API using PactumJS.**

**Outline**

* Introduction
* What is Strapi?
* What is PactumJS?
* Setting up Strapi locally
* Create a demo To-do List back-end app using Strapi
* Setting up PactumJS
* Making requests
    * GET request with parameters
    * POST request
    * DELETE request
    * More request types
* Response validation
    * Basic assertions
    * Basic matching techniques
* Conclusion

**My content is**

- [x] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by a7medayman6** [comment]
Hello! 

I'm very excited to start working on my first article for Strapi, please let me know when can I start working on the draft.

**Comment by PaulBratslavsky** [comment]
@a7medayman6 yes you can start working on this.  Thank you.

**Comment by a7medayman6** [comment]
Hello @PaulBratslavsky ,

Unfortunately I won't be available for the next couple of weeks, but I will work on it as soon as I can, keep it assigned to me please.
 
Thank you.

**Comment by PaulBratslavsky** [comment]
@a7medayman6 I will mark it as on hold but it will still be assigned to you.

**Comment by a7medayman6** [comment]
Hello @PaulBratslavsky, sorry for the late reply, I had something going on.
I started working on the draft, I will finish it as soon as I can and share it with you.

Thank you.

**Comment by a7medayman6** [comment]
Hello @PaulBratslavsky, @Mcastres, Here is my [Draft](https://www.dropbox.com/scl/fi/38qkzzuq1jsboz7oopodp/How-To-Create-Automated-Tests-For-Strapi-API-using-PactumJS.paper?dl=0&rlkey=js0wp0zpf43hyvfz1402uq2hd). Let me know when you get the chance to review it. 

Thanks.

**Comment by a7medayman6** [comment]
@dessireugarte, @PaulBratslavsky, @Mcastres, 
Is there any updates?

**Comment by PaulBratslavsky** [comment]
@a7medayman6 we added to the review cue will let you know when it is complete.

**Comment by PaulBratslavsky** [comment]
@a7medayman6 one small tiny change otherwise the article looks good.  Great job.  I added the message in the drop box doc you shared.  Thanks.

**Comment by a7medayman6** [comment]
@PaulBratslavsky Thank you.

**Comment by a7medayman6** [comment]
@PaulBratslavsky @dessireugarte Is there any updates?

**Comment by dessireugarte** [comment]
Hello @a7medayman6! I'm very sorry for the delay. 
Your article is live! 🎉

You should register yourself once as an "Individual Vendor," please fill out [this](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform) form. If you have any questions about the form, please do not hesitate to ask. Please note that in the W-8BEN form, section 5 is not mandatory, and sections 6a & 6b are only required if you have a tax number in your country.

You should submit your invoice to receive payment for your work [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform). Please feel free to reach out to us if you have any further questions.

**Comment by a7medayman6** [comment]
@dessireugarte Hello, Sorry for being late, I was very busy.
I have a question about the invoice, what is the verfication link? I don't think my bank provides this.

**Comment by dessireugarte** [comment]
Hello @a7medayman6!
You just need to provide an image or anything as proof that your account is a real bank account. 
Let me know if you have any other questions.

**Comment by a7medayman6** [comment]
Thank you @dessireugarte, 
I submitted both forms.

**Comment by dessireugarte** [comment]
Thank you @a7medayman6! I submitted your invoice to the Finance team, you should be getting your payment in the next two weeks.
