### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by kartikdani** [strapi/community-content#983]
I want to use strapi with django framwe work can you please provide me the tutorial for the same

**Comment by PaulBratslavsky** [comment]
@kartikdani django is another way to create an api using python, where Strapi is a way to create an api using javascript.  You would not use both.  I would recommend checking out our course on building an application with Strapi and Next JS.  https://youtu.be/EnuvFyJE6dg. 

I will be marking this issues as closed.
