### ISSUE TITLE
[SUBMIT] How to build a flashcard System using Strapi custom controllers and routes, NextJs, and Tailwind CSS.

### ISSUE THREAD

**Issue by Theodore-Kelechukwu-Onyejiaku** [strapi/community-content#984]
### Outline
* Introduction
* What is a Flashcard?
* Benefits of a flashcard.
* What is Strapi?
* What is Tailwind CSS
* Scaffolding a Strapi Project
* Building the flashcard Collection Type.
* Setting Up Roles for Public and Authenticated Users
* Customizing flashcard controller
* Adding a custom controller for liking a flashcard.
* Adding a custom router for liking a flashcard.
* Scaffolding a NextJs Project.
* Implement a light/dark theme with Tailwind.
* Buiding Next.js Components (Layout, Login/Sign-in, Create Flashcards, )
* Building Next.js Pages (dashboard, edit flashcard, 404, 
* Implementing authentication and logout, creation of flashcards, like flashcards, edit flashcards, delete flashcard and card flipping.
* Demo of Application (Video Link)
* Conclusion

- [x] A Strapi Tutorial / Guide / How to article
- [x] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @PaulBratslavsky @Mcastres .

Good day, I sure hope you are doing great.
I am glad to write for Strapi.

Here is the Project Demo link on Youtube of creating a Flashcard System with Strapi Custom Controllers and Routers, with NextJs and Tailwind CSS.

I have finished the work, and only left with writing the article.

https://www.youtube.com/watch?v=a-FursKUuqw&t=211s

Best,
Theodore

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @dessireugarte, @PaulBratslavsky and @Mcastres.
I sure hope you are doing fine.

Please what do you think of my topic, article, and project?

Thanks.

**Comment by dessireugarte** [comment]
Hello @Theodore-Kelechukwu-Onyejiaku 👋
Thanks for submitting the outline. Unfortunately, we already have very similar tutorials (you can check [them here](https://strapi.io/blog)), and we are trying to bring new topics to the blog. 
If you have other proposals, feel free to submit them so we can review them 👍

**Comment by Theodore-Kelechukwu-Onyejiaku** [comment]
Hi @dessireugarte 

Thanks for your response.
