### ISSUE TITLE
[UPDATE OUTDATED CONTENT] How to Build a Blog using Blazor WASM and Strapi

### ISSUE THREAD

**Issue by dessireugarte** [strapi/community-content#985]
**Description**
Update this article with Strapi v4 https://strapi.io/blog/how-to-build-a-blog-using-blazor-wasm-and-strapi

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by Marktawa** [comment]
Hey @dessireugarte 

I would like to work on this.

**Comment by Marktawa** [comment]
Hey 👋  @dessireugarte 
Here's a [complete draft of the tutorial](https://www.dropbox.com/scl/fi/v3bi4umqvz1rz6uo2e6hi/How-to-Build-a-Blog-App-using-Blazor-WASM-and-Strapi.paper?dl=0&rlkey=22befzxkh60xma24u0r7c5ye4). I also put a [demo video](https://youtu.be/qznajT3e8Tg).

**Comment by dessireugarte** [comment]
Thank you @Marktawa 👏 
We'll review the draft and get back to you.

**Comment by Marktawa** [comment]
🙏 Thanks @dessireugarte

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋
Just wanted to let you know that your article will be published next week. I'll let you know if we need any changes from you or when it is published!

**Comment by dessireugarte** [comment]
Hello Mark 👋 
Your article is [live](https://strapi.io/blog/how-to-build-a-blog-app-using-blazor-wasm-and-strapi)! 🎉
Updates now will be under the main author's name and a mention of the update writer at the top. 

You should register yourself **once** as an "Individual Vendor" in this [form](https://docs.google.com/forms/d/e/1FAIpQLScIl6QgX72c5hiVvdwjkIOXju5hkIHU5-Sz3FU8mYQRFsqJFQ/viewform), please let me know if you have any questions about the form. Just be aware that in the W-8BEN form:
- 5 is not mandatory
-  6a & 6b are only necessary if you have a tax number in your own country. 

Then you can submit your invoice [here](https://docs.google.com/forms/d/e/1FAIpQLSeD59R4fR5dEJIRh4JhUpBlKAi9yX5YeJIMsn-3gUFVj-bMjg/viewform). 
Please feel free to reach out to me if you have any questions!

**Comment by dessireugarte** [comment]
Hello @Marktawa 👋
I received your invoice. Is there a specific reason why it is submitted by $200? I'm wondering since [the v4 updates compensation](https://strapi.notion.site/Writer-s-Guide-V4-Tutorial-Update-68953d4073bf43b7bcba3d8284741c6d) is usually $70.

**Comment by dessireugarte** [comment]
Hello @Marktawa! 👋 Could you please submit the invoice again with the right quantity ($70)? And if it is done after today, could it be done with the date of December 1st? Otherwise, Finance will reject the invoice.

**Comment by Marktawa** [comment]
Hey @dessireugarte 👋 
I have just submitted the invoice again according to your instructions. 🙏 I made the necessary corrections.
