### ISSUE TITLE
[SUBMIT] Deploying a Strapi Docker Container to AWS ECS Using Docker

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#987]
**My resource**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by emmanueletukudo** [comment]
Hello, I am pretty new to the Strapi community. If this article topic is still open, I'll like to write about it.

**Comment by PaulBratslavsky** [comment]
We currently have an article in review that covers this process.  Will be closing the issue due to article similarity.
