### ISSUE TITLE
[SUBMIT] Deploying a Strapi Kubernetes Cluster on Amazon EKS

### ISSUE THREAD

**Issue by kimkimani** [strapi/community-content#988]
**My resource**

**My content is**

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by segunjkf** [comment]
Hello I am interested in this article.

**Comment by ethan-gallant** [comment]
I don't think this is something that's EKS specific but the existing kubernetes tutorial is definitely far from proper.

**Comment by PaulBratslavsky** [comment]
@ethan-gallant is this the tutorial you are referring to https://strapi.io/blog/deploying-and-scaling-the-official-strapi-demo-app-food-advisor-with-kubernetes-and-docker would like to hear your feedback if it is.

@kimkimani since we already have an article published on Kubernetes deploy we will hold of for now on publishing a similar article.

**Comment by ethan-gallant** [comment]
@PaulBratslavsky yeah that is the tutorial I am referring to. There are several best practices in the template YAMLs etc. So while it may work, it's far from ideal or what should be "recommended".

I think some changes should be:
- Ingress / Configuring proper termination
- TLS termination with Cert Manager or the like
- MiniKube is definitely not the target here. I don't even know why it's included. [Kind](https://kind.sigs.k8s.io/) or similar should be used if you're looking to have a "demo" cluster, but it's out of scope imo.
- No notes on using ConfigMaps or ENV variables to pass secrets to the Strapi instance
- No notes on persistence strategy for the instance.
- `kubectl expose` is used but this generally is only used for debugging purposes when debugging existing applications. The exposure should be done in a YAML by creating a "service" object.

In my honest opinion something like how [Quarkus](https://quarkus.io/guides/deploying-to-kubernetes) handles deploying to Kubernetes in their guides would be ideal.
