### ISSUE TITLE
adityastrapi

### ISSUE THREAD

**Issue by adityayadav7** [strapi/community-content#99]
**My resource**
Describe what your resource will be about. (tutorial or article)

**My format**

- [ ] Article
- [ ] Video

**What do you guy's think?**
❤️ I love it!
🚀 I can help you!

**Comment by Mcastres** [comment]
What it is about @adityayadav7 ?

**Comment by malgamves** [comment]
hey, @adityayadav7 closing this for now. I'm more than happy to re-open it when you give more context for the type of support you need.
