### ISSUE TITLE
[SUBMIT] Powering a video streaming app using strapi

### ISSUE THREAD

**Issue by i1d9** [strapi/community-content#991]
Hello 👋 

This tutorial will build a video streaming application using a Strapi server instance and VIte.js. We will learn how to add custom routes and their respective controller functions. In addition, we will add some logic to serve video content into bufferable chunks by modifying response headers sent back to the client's browser.

Outline
- Introduction
- Prerequisites
- Initializing a Strapi project
- Creating Collections
- Extending Collection APIs: Controllers and Routes
- Initializing the Vite application
- Installing auxiliary dependencies
- UI components and routes
- Conclusion.

**My content is**

- [X] A Strapi Tutorial / Guide / How to article
- [X] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

**Comment by icode247** [comment]
Hi @PaulBratslavsky , @Mcastres .
I can work on this topic

**Comment by Mcastres** [comment]
@i1d9 are you working on this or have you just submitted an idea?

**Comment by i1d9** [comment]
@Mcastres I've already started working on it. You could change the issue label and assign it to me

**Comment by Mcastres** [comment]
Thanks for the reactivity @i1d9!

**Comment by i1d9** [comment]
Here is the [tutorial](https://www.dropbox.com/scl/fi/s0skqrzw0zs32n2sq920b/Powering-a-video-streaming-app-using-Strapi..paper?dl=0&rlkey=0aa0f6udoxcb89yzx5zrbtbsq)

**Comment by PaulBratslavsky** [comment]
@i1d9 great tutorial I added some small notes.  But otherwise looks good.  Great job.  Let me know if you have any questions.
