### ISSUE TITLE
[SUBMIT] Building a job board with Strapi and Vue

### ISSUE THREAD

**Issue by Tammibriggs** [strapi/community-content#992]
Hello 👋 

This tutorial will introduce Strapi and how it works by building a job board that includes features for searching for and filtering jobs and a form for applying for a job.

## Outline
- Prerequisite
- Introduction to Strapi
- Setting up a Strapi project
  - Creating the collection content types
- Building a Job board
  - Setting up Vue
  - Creating new jobs
  - Fetch and display all jobs
  - Search and filter jobs
  - Applying for a job
- Conclusion 

**My content is**

- [ *] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by noblefresh** [comment]
I'm interested on this topic, can I work on it?

**Comment by dessireugarte** [comment]
Hello @Tammibriggs 👋
We already have two similar articles with different technologies, so we are not going to proceed with this topic. 
[- Building a Job Nina with Sapper, Strapi and Netlify](https://strapi.io/blog/building-a-job-nina-with-sapper-strapi-v4-and-netlify)
[- How to Build a Job Board with Next.js, Tailwind CSS, and Strapi ](https://strapi.io/blog/how-to-build-a-job-board-with-next-js-tailwind-css-and-strapi)

Feel free to share other ideas you might have as a content request!
