### ISSUE TITLE
Create dynamic zones in nuxt: missing images

### ISSUE THREAD

**Issue by Kapcash** [strapi/community-content#993]
**The concerning content**

[Creating Dynamic Zone in Nuxtjs](https://strapi.io/blog/creating-strapi-dynamic-zone-in-nuxtjs-app)

**Issue**

There are **missing images** in the article, which doesn't allow use to get the full demonstration and results.

**Comment by PaulBratslavsky** [comment]
@malgamves let me know if this is something you will be able to update? Otherwise, we can ask someone in the community.

**Comment by JericksonJ** [comment]
Hi @PaulBratslavsky ,

Can I work on this?

**Comment by PaulBratslavsky** [comment]
The article should be already updated, the issue is that the project is no longer deployed.  For the time being, I will remove the link to the working project example.  Will follow the tutorial to complete a new project, deploy to production and share.

**Comment by hanakhelifa** [comment]
Closing this issue as we are revamping the WFC program.
